[NON-MODULAR] Adds a note about the 150 character minimum Flavor Text to the Join Game menu.
Skyrat-SS13/Skyrat-TG pull request #10059
Opened 2021-12-14 00:43 UTC by Iamgoofball

## About The Pull Request
Adds a note about the 150 character minimum Flavor Text to the Join Game menu.

## How This Contributes To The Skyrat Roleplay Experience
This should reduce the amount of confusion from new players.

## Changelog

:cl:
spellcheck: Adds a note about the 150 character minimum Flavor Text to the Join Game menu.
/:cl:

2021-12-14 00:46 UTC, GoldenAlpharex requested changes

2021-12-14 00:46 UTC, GoldenAlpharex commented on code/modules/mob/dead/new_player/new_player.dm
> +	dat += "<div class='notice'>If you don't see any jobs, make sure you have at least 150 characters of Flavor Text written!</div>"
Couldn't you just make it display that only if there's actually a failure with the flavor text requirement?

2021-12-17 00:50 UTC, Zonespace27 commented
This could possibly be closed with the merging of #10063

2021-12-17 01:15 UTC, Gandalf2k15 commented
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10063

2021-12-17 01:15 UTC, closed without merging