Added some donator items.
Skyrat-SS13/Skyrat-TG pull request #10056
Opened 2021-12-13 23:21 UTC by Useroth

Well, sharing is caring, innit?

One uniform comes from this PR but I guess it will be nice to have a copy of the sprites in case they change in future.
https://github.com/Skyrat-SS13/Skyrat-tg/pull/9963

2021-12-14 04:27 UTC, GoldenAlpharex requested changes

2021-12-14 04:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
> +	ckeywhitelist = list("1ceres","thebamboozler","irrigoimport","zeskorion","wizardlywoz","aether217","duckymomo", "samarai1000", "funkyfetusstrikesback")
```suggestion
	ckeywhitelist = list("1ceres", "thebamboozler", "irrigoimport", "zeskorion", "wizardlywoz", "aether217", "duckymomo", "samarai1000", "funkyfetusstrikesback")
```

2021-12-14 04:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/mask/breath/vox/octus
```suggestion
// Donation reward for Octus
/obj/item/clothing/mask/breath/vox/octus
```

2021-12-15 17:16 UTC, Gandalf2k15 approved these changes

2021-12-15 17:16 UTC, merged