Changed Freighter loot/cargo
Skyrat-SS13/Skyrat-tg pull request #10311
Opened 2021-12-27 19:50 UTC by ForrestWick

## About The Pull Request
>antag gear spawners replaced with less gamer alternatives, either fixed items (antidrop implant autosurgeon, syndi cosmetics, etc) or just the armory contraband spawner. Two weak antag gear spawners exist in the crates meant for Interdyne and DS2.
>labels added to a couple crates/boxes or changed to be more clear (NTSS13 is the station itself)
>replaced the Cybersun hardsuit spawner (which got turned into an Elite Syndi MODsuit unit) with a security modsuit for the freighter chief
>changed contents of the vault safe into being some diamond, a metal, and a stable metal extract
>added a crate with two healium crystals to offer some atmos options for selling stuff
>added an account registration machine to the cargo hold

## How This Contributes To The Skyrat Roleplay Experience

Apparently people are powergaming the ruin/role. While this in itself might not instantly stop that, the idea is now the gear they are getting is less insane and more flexible for merchant/store gimmick stuff. 

## Changelog

:cl:
balance: removed some of the gamer loot from the cargo freighter role, replaced with stuff that can actually be sold. Also switched out the spiders for zombies and added a couple extra mobs.
/:cl:

2021-12-27 19:56 UTC, ArdentSpark commented
The central command crate was bait to be broken open so good that thats gone, is that a thermal monocle? If so I'm not thrilled about that

2021-12-27 20:05 UTC, ArdentSpark commented
Also is that two NTSS13 crates? It did always confuse me as to why the freighter was delivering to everyone but the station itself, so that's neat!

2021-12-27 20:13 UTC, axietheaxolotl requested changes

2021-12-27 20:13 UTC, axietheaxolotl commented on _maps/RandomRuins/SpaceRuins/skyrat/cargodiselost.dmm
> +/obj/item/clothing/glasses/thermal/monocle,
uhh, no.

2021-12-27 20:15 UTC, ForrestWick commented
> Also is that two NTSS13 crates? It did always confuse me as to why the freighter was delivering to everyone but the station itself, so that's neat!

They always were able to, it's just that nobody remembers the station was called Exodus

2022-01-04 19:49 UTC, GoldenAlpharex requested changes
I love the fact you're balancing this. However, those things shouldn't be varedited in the map itself, it should be handled in the code, so they can be re-used if need be, and to reduce the size of the map file itself.

If you need help with that, ask us on the Discord!

2022-01-18 00:19 UTC, closed without merging