Cyborg Tipping modularization
Skyrat-SS13/Skyrat-TG pull request #10741
Opened 2022-01-16 15:32 UTC by theOOZ

## About The Pull Request

Reverts [#10667](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10667) and [#10688](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10688)

Adds [#10740](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10740) modularly

## Changelog
JohnFulpWillard and theOOZ
:cl:
qol: Tipping mobs over all runs on right click, rather than running on both right and left click.
balance: You can now tip Borgs over.
/:cl:

2022-01-16 16:51 UTC, Gandalf2k15 commented
Aaah non-modular changes, pls fix

2022-01-16 16:52 UTC, theOOZ commented
> Aaah non-modular changes, pls fix

it is because this PR has [10740](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10740) inside of it.

2022-01-16 17:11 UTC, theOOZ commented
It's not gonna pass CI until #10740 is merged, which is not passing CI until the reverts here are merged, funny.

2022-01-18 03:51 UTC, KathrinBailey commented on modular_skyrat/modules/altborgs/code/robot_tipping.dm
> +		self_right_time = 60 SECONDS, \
```suggestion
		self_right_time = 15 SECONDS, \
```
As tempting as it is to lazily sit back on my bed and watch Skyrat alienate and burn off the last few borg players they've yet to get rid of, I still have a duty of care to the last two or three of them to quality control some of this stuff.
Letting some crybaby shitter give a borg a 60s stun if they stand still for a few seconds or start typing? No thanks, that can stay on TG.

2022-01-18 03:59 UTC, KathrinBailey requested changes
I know this isn't your PR so you aren't to blame but I'm getting tired of all the crybully shit against borgs as of late so the stun can be made 15s here or I'll make it 15s elsewhere.

2022-01-18 03:59 UTC, KathrinBailey commented on modular_skyrat/modules/altborgs/code/robot_tipping.dm
> +	self_right_time = 60 SECONDS,
```suggestion
	self_right_time = 15 SECONDS,
```
see above

2022-01-18 07:21 UTC, CandleJaxx commented
i unironically see no downside to the tipping- that is placed there so that malf borgs can be non-lethally detained, and it's the same amount as handcuffs. that should stay entirely

2022-01-18 16:53 UTC, theOOZ commented
My personal preference is that this PR keeps balance changes out of it. As it stands it adds visual effects to roombas and a component for having a visual icon_state instead of a y180- flip. Changes to the numbers can be made after this is merged. 💚

2022-01-22 04:16 UTC, KathrinBailey approved these changes
will do the unflip changes myself separately, that way no one can @ you with salt-fuelled aggression

2022-01-22 04:17 UTC, merged