[Modular] Food Flavor Fix II (revenge of the vegans)
Skyrat-SS13/Skyrat-TG pull request #10763
Opened 2022-01-17 01:00 UTC by theOOZ

## About The Pull Request

This is my offer for how we should keep our species taste-preferences.

## How This Contributes To The Skyrat Roleplay Experience

It's accurate to species and unlike the previous fix allows for example, mammals to have a vegan diet.

## Changelog
:cl:
qol: Better species taste-preference
/:cl:

2022-01-17 07:07 UTC, ErdinyoBarboza commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/vulpkanin.dm
> +	disliked_food = TOXIC | CLOTH
TOXIC food is a toxic_food var, this will cause it to be bigged

2022-01-17 07:09 UTC, ErdinyoBarboza commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/insect.dm
> +	liked_food = GROSS | RAW | TOXIC | CLOTH
Try to keep it to 3/3 at max, normally races have 2 liked 3 disliked. Were pushing limits even at 3/3

2022-01-17 07:11 UTC, ErdinyoBarboza commented
Most lizard food are Gross for example, Having GROSS in liked makes the species like the more "exotic" meat based foods

2022-01-17 07:20 UTC, ErdinyoBarboza requested changes
Make sure to not raise Liked foods more then Disliked Foods. Try to keep it at 3/3 at max.
If you will make TOXIC foods disliked, add a food type for the toxic_food pref. If people want to make vegan/vegetarian vulpans etc they can take Deviant, by making Vulpans not dislike veggies but like raw meat you kinda make them be able to eat almost anything which is bad for the balance of the system. The insect Likes/Dislikes is made around normal variant being common insects while when taking deviant it makes them into fake moths.

2022-01-17 07:23 UTC, ErdinyoBarboza commented
Current mammals can have a vegan diet by taking Deviant which will make them not like meat. Or by taking the vegeterian trait.

2022-01-17 13:04 UTC, theOOZ commented
> Current mammals can have a vegan diet by taking Deviant which will make them not like meat. Or by taking the vegeterian trait.

I want to avoid this unless we rename it to veganism, which would be a non-modular change.

2022-01-18 00:24 UTC, Sir-Lagsalot commented
If balance is a concern here, dislike for both fruit and vegetables is kind of excessive, since that eliminates, like, _most_ prepared foods. It's also kind of weird considering a large number of our anthromorphs are just modded humans.

2022-01-18 00:28 UTC, theOOZ commented
> If balance is a concern here, dislike for both fruit and vegetables is kind of excessive, since that eliminates, like, _most_ prepared foods. It's also kind of weird considering a large number of our anthromorphs are just modded humans.

ive updated all species which had fruit and veggies in their dislikes to more rational choices

2022-01-18 16:47 UTC, thestubborn commented
i still think its weird anthromorphs as a species have veggies in their dislikes (I know its reversible but its weird having to put the 'eats weird shit' which comes up on your medical record)


like I know everyone wants to be epic blue and black furred wolf man/woman

but, bro, animals eat more than meat

2022-01-20 03:29 UTC, merged