borer 1.1
Skyrat-SS13/Skyrat-TG pull request #10767
Opened 2022-01-17 09:18 UTC by jjpark-kb

## About The Pull Request
Warning: This is a lot.

1) Borers have universal objectives again
1a) Five borers need to at least produce 10 eggs
1b) Twenty hosts need to agree to be a willing host
1c) Completing objectives will boost your evolution point gain
2) Some borer abilities have been locked away and require unlocking
2a) Revive host, learn chemical through blood, willing host, and produce offspring
3) Borers will screw with your health hud, similar to miner's salve
4) Borers can only have 10 evolution points (so 10 chem and 10 stat) at a time
4a) It will tell you that you were unable to gain a point. Spend points to earn more
5) Hosts will naturally take toxin damage up to 25
6) There is a distinction between the link and the hivemind
6a) The hivemind is purple as well, but is now bold
7) Some abilities got new icons
8) Checking the "blood" (read: health) of a host will now display like a health analyzer
9) Borers can enter dead bodies
10) Borers no longer spawn other borers, but instead eggs
10a) They have some information for the beginner borer on spawners menu

Objectives:
![image](https://user-images.githubusercontent.com/55967837/149741046-3415d37f-dc91-4a71-be6e-c227f2e788ed.png)
![image](https://user-images.githubusercontent.com/55967837/149741063-15a910f9-178e-4fbf-9081-439ea5251829.png)

Some new ability icons:
![image](https://user-images.githubusercontent.com/55967837/149741137-403ae9bb-1884-4f35-b019-27877d896522.png)

Unable to gain over the limit:
![image](https://user-images.githubusercontent.com/55967837/149741212-653d5067-8598-4757-bf04-47ec7a45626c.png)

Egg:
![image](https://user-images.githubusercontent.com/55967837/149741244-0cdac798-fc17-44e1-aa7e-a323e2099109.png)

Link vs. Hivemind
![image](https://user-images.githubusercontent.com/55967837/149741362-c1f48d46-ee92-4d43-a5ef-9886dc745c0e.png)

## How This Contributes To The Skyrat Roleplay Experience
This changes borers a lot. There are some buffs and some nerfs.
People argued (and it was valid) that there was not enough drawbacks to allowing the borer inside of you; this should solve some of those arguments for now.
Borers should be limited in some ways and I hope that what I have done can make it feel more rewarding to play borer.

## Changelog

:cl:
add: borers have universal objectives again
add: borers now give the screwy health hud effect (similar to miner's salve)
add: borer hosts will naturally take toxin damage, up to 25
add: borers will now spawn eggs rather than complete borers
balance: some borer abilities have been locked behind stat evolution points
balance: borers can only have 10 chemical and 10 stat evolution points
balance: borers when checking health of host get a similar output as a health analyzer
balance: borers can now enter dead bodies
qol: a distinction between link and hivemind for borers: hivemind is bold now
imageadd: some borer abilities got new icons
/:cl:

2022-01-17 19:05 UTC, YakumoChen requested changes

2022-01-17 19:05 UTC, YakumoChen commented on modular_skyrat/modules/cortical_borer/code/cortical_borer.dm
> +GLOBAL_VAR_INIT(borer_spawner_ten, 0)
Don't hardcode the amount

2022-01-17 19:05 UTC, YakumoChen commented on modular_skyrat/modules/cortical_borer/code/cortical_borer.dm
> +	. += "1) Five(5) borers producing ten(10) eggs: [GLOB.borer_spawner_ten]/5"
These should be just numerals, and they should use a define for the amount.

2022-01-17 19:05 UTC, YakumoChen commented on modular_skyrat/modules/cortical_borer/code/cortical_borer.dm
> +	. += "2) Twenty(20) willing hosts: [length(GLOB.willing_hosts)]/20"
Ditto

2022-01-17 19:05 UTC, YakumoChen commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_egg.dm
> +	role_ban = ROLE_DRONE
Borers are an antag, they should be using a proper antagonist ban type (like xeno)

2022-01-18 01:14 UTC, Gandalf2k15 approved these changes

2022-01-18 01:14 UTC, merged