[MODULAR] Fixes Nanite Slurry
Skyrat-SS13/Skyrat-TG pull request #10778
Opened 2022-01-17 17:39 UTC by Snakebittenn

## About The Pull Request
There was supposed to be this funny little function where nanite slurry heals you based on the reac_volume of a touch application. It didn't prior because turns out adjustFireLoss and adjustBruteLoss don't work on synth limbs, thank you to @tf-4 for pointing this out for me and helping me get this off the ground. This doesn't rebalance it. Probably more synth-related PRs to come.

## How This Contributes To The Skyrat Roleplay Experience
It'd be nice for synth-unique medicine to actually fix them. This way synths have literally anything to do with medical, and roboticists can maybe take advantage of plumbing. This is actually more balanced than one would think due to there being a maximum capacity of how much reagent can be applied by throwing a bottle on them/using a hypospray's right click, and patches don't work at all. Showers do, but a plumbing setup (which has to be refilled) has to be established for that, and it'd be stationary. However, the shower does take about 20 seconds compared to a flat minute of welding to heal 100 brute damage, so it's probably worth the investment. (Numbers tested locally by me, a dumbass cat.)

## Changelog
:cl:
fix: Nanite slurry actually heals synths now.
/:cl:

2022-01-19 16:56 UTC, Snakebittenn commented
Coming back to this soon, sware on me mum.

2022-01-20 00:15 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	M.heal_bodypart_damage(1*REM, 1*REM, required_status = BODYPART_ROBOTIC)
make these vars on the chem actually

2022-01-20 13:57 UTC, Zergspower commented
after dicking around with public chems I think this should be even higher - or have an additional one that does over X like organics have.  see below with this very easy to make 5u pill as my argument 
![image](https://user-images.githubusercontent.com/22140677/150352364-81d72225-c0cd-4ee4-a51d-4f459d7c3b1b.png)

2022-01-20 15:33 UTC, tf-4 commented
> after dicking around with public chems I think this should be even higher - or have an additional one that does over X like organics have. see below with this very easy to make 5u pill as my argument

Firstly, trying to balance a race to be on par with humans is a fallacy. All races should be worse than humans. They are the baseline.
Secondly, balance should be changed in moderation. Make small, incremental buffs rather than large, sweeping buffs that then need large, sweeping nerfs two weeks down the line.
This is a fine change.

2022-01-20 15:33 UTC, tf-4 requested changes
Do put the healing as chem vars though. Hit me up on discord if you want a hand.

2022-01-20 15:43 UTC, Zergspower commented
> 

Perhaps, but maybe raising the OD limit off of 20? for 20-40 max healing over a minute with 20u consumed is borderline pointless to use this chem at all, kind of why no one uses omni as a standalone.  combined with the increased time in self-heal would make getting overheated currently is a 100% death sentence since you wouldn't be able to out heal the burn. I agree with moderation but the changes we did in the other PR removed only a small percent off their increased damaged but also took away a chunk of their survivability

2022-01-20 15:46 UTC, Zergspower commented
> > 
> 
> Perhaps, but maybe raising the OD limit off of 20? for 20-40 max healing over a minute with 20u consumed is borderline pointless to use this chem at all, kind of why no one uses omni as a standalone. combined with the increased time in self-heal would make getting overheated currently is a 100% death sentence since you wouldn't be able to out heal the burn. I agree with moderation but the changes we did in the other PR removed only a small percent off their increased damaged but also took away a chunk of their survivability

tweaking the recipe of the one i found above I can get 100/100 brute/burn healed in 32 seconds with 5u of SalAcid/Lenturi/Lib/Oxan - which is utterly overpowered given how easy it is to get them

2022-01-20 17:53 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	var/burning = 50
auto-doc and the burning var isn't a great name imo
```suggestion
	/// How much brute and burn individually is healed per tick
	var/healing = 1
	/// How much body temperature is adjusted by per tick
	var/temperature_change = 50
```

2022-01-20 17:54 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  /datum/reagent/medicine/nanite_slurry/on_mob_life(mob/living/carbon/M)
also rename this to something more descriptive
```suggestion
/datum/reagent/medicine/nanite_slurry/on_mob_life(mob/living/carbon/affected_mob)
```

2022-01-20 17:54 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +/datum/reagent/medicine/nanite_slurry/overdose_process(mob/living/carbon/M, delta_time, times_fired)
same here
```suggestion
/datum/reagent/medicine/nanite_slurry/overdose_process(mob/living/carbon/affected_mob, delta_time, times_fired)
```

2022-01-20 20:10 UTC, RatFromTheJungle commented
> > > 
> > 
> > 
> > Perhaps, but maybe raising the OD limit off of 20? for 20-40 max healing over a minute with 20u consumed is borderline pointless to use this chem at all, kind of why no one uses omni as a standalone. combined with the increased time in self-heal would make getting overheated currently is a 100% death sentence since you wouldn't be able to out heal the burn. I agree with moderation but the changes we did in the other PR removed only a small percent off their increased damaged but also took away a chunk of their survivability
> 
> tweaking the recipe of the one i found above I can get 100/100 brute/burn healed in 32 seconds with 5u of SalAcid/Lenturi/Lib/Oxan - which is utterly overpowered given how easy it is to get them

see: above

They don't need to be comparable to humans, they have a ton of enviromental protections and immunity too **A LOT** of antag weapons, they can deal with healing slower.

2022-01-21 01:08 UTC, tf-4 requested changes
Last few bits code-wise

2022-01-21 01:08 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	description = "A localized swarm of nanomachines specialized in repairing mechanical parts. Due to the nanites needing to interface with the host's systems to repair them, a surplus of them will cau
Do IPCs have mouths? I don't want to merge failRP here...

2022-01-21 01:08 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	if(!(affected_mob.mob_biotypes & MOB_ROBOTIC))
Early return this instead

2022-01-21 20:16 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	. = 1
```suggestion
```

2022-01-21 21:46 UTC, tf-4 approved these changes

2022-01-24 18:57 UTC, GoldenAlpharex requested changes
That sounds kinda useful, although you should change the PR description to reflect it's `1` and not `0.8` (unless this is working in even weirder ways than I'm assuming it does).

Also, I'd argue at this point it's kind of not just a fix.

2022-01-24 18:57 UTC, GoldenAlpharex commented on code/__DEFINES/misc.dm
> +#define VOMIT_NANITE 3 //SKYRAT EDIT ADD
You should say in your SKYRAT EDIT comment the reason why you're making said edit, so it's easier to find in the future.

2022-01-24 18:57 UTC, GoldenAlpharex commented on code/game/turfs/turf.dm
> +		V.icon_state = "vomitnanite_[pick(1,4)]" // SKYRAT EDIT END
```suggestion
	//SKYRAT EDIT START - Nanite Slurry
	else if (toxvomit == VOMIT_NANITE)
		V.name = "metallic slurry"
		V.desc = "A puddle of metallic slurry that looks vaguely like very fine sand. It almost seems like it's moving..."
		V.icon_state = "vomitnanite_[pick(1,4)]"
	// SKYRAT EDIT END
```

2022-01-24 18:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +/datum/reagent/medicine/system_cleaner/on_mob_life(mob/living/carbon/M, delta_time, times_fired)
```suggestion
/datum/reagent/medicine/system_cleaner/on_mob_life(mob/living/carbon/affected_mob, delta_time, times_fired)
```

2022-01-24 18:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  		if(R != src)
```suggestion
	affected_mob.adjustToxLoss(-2 * REM, 0)
	. = 1
	for(var/thing in affected_mob.reagents.reagent_list)
		var/datum/reagent/reagent = thing
		if(reagent != src)
```

2022-01-24 18:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			M.reagents.remove_reagent(R.type, 1 * REM * delta_time)
```suggestion
			affected_mob.reagents.remove_reagent(reagent.type, 1 * REM * delta_time)
```

2022-01-24 18:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	affected_mob.heal_bodypart_damage(healing*REM, healing*REM, required_status = BODYPART_ROBOTIC)
```suggestion
	affected_mob.heal_bodypart_damage(healing * REM, healing * REM, required_status = BODYPART_ROBOTIC)
```

2022-01-24 18:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	affected_mob.reagents.remove_reagent(type, 3.6) //gets removed from organics very fast
That 3.6 should be a define, I have no idea why it'd be that and not, say, 4, and it just in generally doesn't mean anything to me.

2022-01-24 18:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	if(prob(25))
This also should be a define, like `#define NANITE_SLURRY_ORGANIC_VOMIT_CHANCE 25`

2022-01-24 21:05 UTC, GoldenAlpharex reviewed
Those changes are good, I'll check if anything's missing.

2022-01-26 17:08 UTC, GoldenAlpharex commented on code/__DEFINES/misc.dm
> +#define VOMIT_NANITE 3 //SKYRAT EDIT ADD
```suggestion
#define VOMIT_NANITE 3 //SKYRAT EDIT ADD - Nanite Slurry
```

2022-01-26 17:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	/// How much body temperature is adjusted by per tick
```suggestion
	/// How much body temperature is increased by per overdose cycle on robotic bodyparts.
```

2022-01-26 17:11 UTC, GoldenAlpharex approved these changes
We good to go.

2022-01-26 17:26 UTC, merged