lobby camera
Skyrat-SS13/Skyrat-TG pull request #10829
Opened 2022-01-19 21:09 UTC by jjpark-kb

## About The Pull Request
adds a lobby camera. Idea is from Toolbox Station, but code has been adapted/modified.
https://gyazo.com/dc4497e78297b0138b1ea4b4aa5fe15e

## How This Contributes To The Skyrat Roleplay Experience
a nice rolling camera intro before the round

## Changelog

:cl:
add: added the lobby camera
/:cl:

2022-01-20 04:54 UTC, Zergspower commented
The menu disappears when the cam shifts

2022-01-20 06:24 UTC, jjpark-kb commented on code/__DEFINES/layers.dm
> +#define SKYRAT_LOGO 9999
```suggestion
#define BLACK_FADE 9997
#define SPLASHSCREEN_PLANE 9998 //Previous value: 9999
#define SKYRAT_LOGO 9999
```

2022-01-20 06:59 UTC, Iamgoofball commented on modular_skyrat/modules/lobby_cam/code/lobby_cam.dm
> +	spawn(0)
how old is this code?

2022-01-20 13:24 UTC, theOOZ commented
Some issues: It switches really quickly, and the black fade **also fades the menu options**.

2022-01-20 20:13 UTC, jjpark-kb commented
the menu being covered has been resolved. I tried lowering the speed and it makes it look far more jittery.

2022-01-20 20:14 UTC, theOOZ commented
is there another way the duration of the camera panning can be extended? good job on the menu thing btw

2022-01-21 06:24 UTC, SpaceVampire commented
It feels really jittery, to the point that I feel actually motion sick from looking at it. Really don't like trying to focus on OOC chat with something moving all around on the left side of my screen. Could you at least add some option for people to disable it, if they don't want it? I'm kind of sad about how this is going to be the death of cool custom title screens, but I guess that part is whatever.

2022-01-23 06:43 UTC, YakumoChen commented
The map isn't really designed to be viewed pre-round. You can see all the random item spawn markers and such. It doesn't look good.

2022-01-24 18:09 UTC, theOOZ commented
I noticed you tweaked the numbers for how the camera moves! It feels much nicer now.

I have something else to nitpick about: Is there a way to make the camera initiate later? Particularly so its loaded after the part where all lights in the map turn on? This is a Skyrat thing and has always been hugely laggy/ugly to witness, it would be nice if the lobby-camera started just after all lights were turned on.

2022-01-26 18:45 UTC, GoldenAlpharex requested changes
Aside from that minor nitpick, that code seems rather solid.

2022-01-26 18:45 UTC, GoldenAlpharex commented on modular_skyrat/modules/lobby_cam/code/lobby_eye_ss.dm
> +	for(var/mob/checking_mob in GLOB.new_player_list)
```suggestion
	for(var/mob/checking_mob as anything in GLOB.new_player_list)
```

2022-01-26 18:45 UTC, GoldenAlpharex commented on modular_skyrat/modules/lobby_cam/code/lobby_eye_ss.dm
> +	for(var/mob/checking_mob in GLOB.new_player_list)
Pretty sure this list shouldn't contain anything else than that.
```suggestion
	for(var/mob/checking_mob as anything in GLOB.new_player_list)
```

2022-01-26 18:45 UTC, GoldenAlpharex commented on modular_skyrat/modules/lobby_cam/code/lobby_eye_ss.dm
> +		if(!checking_mob.client.prefs.read_preference(/datum/preference/toggle/lobby_cam))
Clients are finnicky, let's avoid runtimes.
```suggestion
		if(!checking_mob.client?.prefs.read_preference(/datum/preference/toggle/lobby_cam))
```

2022-01-26 18:45 UTC, GoldenAlpharex commented on modular_skyrat/modules/lobby_cam/code/lobby_eye_ss.dm
> +			checking_mob.client.eye = linked_camera
```suggestion
		if(!(fading_screen in checking_mob.client?.screen))
			checking_mob.client?.screen += fading_screen
		if(checking_mob.client?.eye != linked_camera)
			checking_mob.client?.eye = linked_camera
```

2022-01-26 18:45 UTC, GoldenAlpharex commented on modular_skyrat/modules/lobby_cam/code/lobby_eye_ss.dm
> +		checking_mob.client.eye = checking_mob.client.mob
```suggestion
		if(fading_screen && (fading_screen in checking_mob.client?.screen))
			checking_mob.client?.screen -= fading_screen
		if(checking_mob.client?.eye != linked_camera)
			continue
		checking_mob.client?.eye = checking_mob.client?.mob
```

2022-01-27 04:02 UTC, merged