A small deny cooldown for airlocks
Skyrat-SS13/Skyrat-TG pull request #10891
Opened 2022-01-22 08:41 UTC by Kush1Push1

## About The Pull Request

Adds a cooldown for airlocks deny sound.
It was [dennied in TG repository](https://github.com/tgstation/tgstation/pull/64300). Round 2, I guess 🗿 

## How This Contributes To The Skyrat Roleplay Experience

Less frustrating sounds from unwanting to cooperate or say a thing people, but still visible indicator of "OPEN THE DOOR NOW NOW NOW!"

## Changelog

:cl: SishTis
qol: Airlocks have a small cooldown of deny sound.
/:cl:

2022-01-22 20:11 UTC, tf-4 commented
We actually have a different airlock noise to /tg/ and ours is much more grating. Good change.

2022-01-22 20:11 UTC, tf-4 approved these changes

2022-01-24 09:56 UTC, sasichkamega commented
If you accept this change, you will lose one of the best features.
This feature is as terrible as it is beautiful.

2022-01-28 15:27 UTC, GoldenAlpharex requested changes
`doorDeni`

2022-01-28 15:27 UTC, GoldenAlpharex commented on code/game/machinery/doors/airlock.dm
> +				playsound(src,doorDeni,50,FALSE,3)
```suggestion
				playsound(src, doorDeni, 50, FALSE, 3)
```

2022-02-05 13:05 UTC, tf-4 commented
I want this

2022-02-14 06:24 UTC, Gandalf2k15 commented
Not needed. Same reasoning as upstream.

2022-02-14 06:24 UTC, closed without merging