Fixes protected rolls getting antagonist
Skyrat-SS13/Skyrat-TG pull request #11016
Opened 2022-01-26 03:54 UTC by Gandalf2k15

## About The Pull Request

Because we can't be trusted to keep dynamic.json up to date with roles, we're just going to do it the easy way.

Jobs now have an antagonist_restricted flag which simply prevents the role from rolling a set list of antagonists. If no list is set, then it will assume all antags.

## Changelog

Not player facing.

2022-01-26 04:00 UTC, GoldenAlpharex requested changes
Also, if antag_flag is actually a bitflag, you should use that to make a `restricted_antag_flags` var instead of using a list, as that would be both faster, cleaner and easier to read.

2022-01-26 04:00 UTC, GoldenAlpharex commented on code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +	cost = 12
Why's the weight and cost being changed here?

2022-01-26 04:05 UTC, Gandalf2k15 commented on code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +	cost = 12
That file was reset to TG.

2022-01-26 19:12 UTC, GoldenAlpharex approved these changes
Looks good, I'll test-merge it first to be sure we don't end up with everyone unable to be antag.

2022-01-27 01:05 UTC, tf-4 commented on code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
> +		else if(!P.client.prefs?.read_preference(/datum/preference/toggle/be_antag))
```suggestion
		else if(P.client?.prefs && !P.client.prefs.read_preference(/datum/preference/toggle/be_antag))
```

2022-01-27 01:05 UTC, tf-4 commented on code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
> +		else if(is_banned_from(P.client.ckey, BAN_ANTAGONIST))
```suggestion
		else if(is_banned_from(P.client?.ckey, BAN_ANTAGONIST))
```

2022-01-27 22:45 UTC, Gandalf2k15 commented
tests show this works well

2022-01-27 22:45 UTC, merged