[Modular][Ready] Few bits of clothing
Skyrat-SS13/Skyrat-TG pull request #11031
Opened 2022-01-26 22:16 UTC by ArthurStan

## About The Pull Request
My first PR to Skyrat, doing this mostly as a test run to see if i still got the handle of things. Trying to port some clothes from Paradise with a few tweaks of my own.

Feedback is more than appreciated, let me know if i forgot something, or messed up somehow.

## How This Contributes To The Skyrat Roleplay Experience
One of the clothing pieces is a coat which i recoulored and renamed to mention an faction from the lore, seeing as SR's wiki shares the same lore as Paradise, i figure that having that could add some possibilities for future RPs, if it works, i plan on adding more gear from said faction, or other factions as well.

The other clothes are mostly basic stuff which i noticed were missing. Some suits 'n such.

## Changelog

:cl:
add:
- Four new suits, one of which is togglable to an more casual version.
- One coat, also togglable.

expansion: 
- References one of the factions which exist on the lore, but not in game.

/:cl:

2022-01-26 22:33 UTC, Zonespace27 commented
CL isn't formatted right, it has to be formatted like this:

`qol: thing here`
`add: the thing I added`

2022-01-27 00:52 UTC, tf-4 requested changes
Put screenshot of the sprites in game in the PR body pls

2022-01-27 00:52 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/under/misc.dm
> +	desc = "Climbing the ranks, no matter the consequences"
```suggestion
	desc = "Climbing the ranks, no matter the consequences."
```

2022-01-27 08:58 UTC, tf-4 commented
Needs the images of them in game if you can, rather than in the editor

2022-02-13 00:20 UTC, closed without merging