[MODULAR] Food Flavor Fix III: Fixes these NUTS
Skyrat-SS13/Skyrat-TG pull request #11056
Opened 2022-01-27 11:14 UTC by ErdinyoBarboza

## About The Pull Request
The latest Food Pref "fix" revenge of vegans fucked up the food prefs (by forgetting a vegetarian food quirk exists) to the point of making almost everyone hate Lizard Cuisine and NUTS somehow. This PR gives all the affected races simpler food prefs.

## How This Contributes To The Skyrat Roleplay Experience
Having 80% of the crew hate nuts is bad for Cooks, Lizards and Teshari. This makes everyone have far more sane food prefs.

## Changelog

:cl:
fix: Fixes the food prefs to enjoy eating (these) nuts and streamlines food prefs.
/:cl:

2022-01-27 12:22 UTC, theOOZ commented
Don't remove raw from likes

2022-01-27 13:20 UTC, GoldenAlpharex requested changes
`VEGETABLE`

2022-01-27 14:03 UTC, thestubborn commented
everyone who isnt a lizard should hate lizard food though?

2022-01-27 14:09 UTC, ErdinyoBarboza commented
everyone hating lizardfood due to NUTS meant even the junkfood they normally enjoy is bad such as gallerys peanuts

2022-01-29 03:22 UTC, YakumoChen commented
> everyone hating lizardfood due to NUTS meant even the junkfood they normally enjoy is bad such as gallerys peanuts

To be fair Gallery's Peanuts is manufactured by pure spite.

2022-02-08 02:20 UTC, merged