Renames NT Rep to NT Consultant
Skyrat-SS13/Skyrat-TG pull request #11206
Opened 2022-02-01 17:37 UTC by tf-4

## About The Pull Request

Renames all occurrences of "Nanotrasen Representative" to "Nanotrasen Consultant".

Made on host request.

## Changelog
:cl:
tweak: "Nanotrasen Representative" has been renamed to "Nanotrasen Consultant".
/:cl:

2022-02-01 17:40 UTC, Zonespace27 commented
What was the reason behind requesting this change?

2022-02-01 18:07 UTC, tf-4 commented
> What was the reason behind requesting this change?

@hugmeorelse

2022-02-01 18:22 UTC, AtoriBirb commented
I understand the why of it but it still seems like punishing the role for the antics of bad faith players. Kinda a common thing, we should just hold people playing it to a higher standard.

2022-02-01 18:35 UTC, Morokite commented
I 100% get the heart behind this. The NT rep gives a bit more power because they seemingly represent the will of NT. But the NT rep is fallible to a degree. I don't think we *have* to push a name change. I think we just have to push the ruleset better and discourage people from using it inappropriately. 
But also I feel like I may or may not have been involved in this change request from a sour apple of a round.
This is a case of, I think it's fine as is, and we can just all strive to do/enforce it better.
But honestly it's just a small name change at the end of the day so it won't matter in the long term.

2022-02-01 19:10 UTC, GoldenAlpharex commented
I liked the sound of NT Rep.

2022-02-01 19:11 UTC, Zonespace27 commented
Name-wise, I prefer representative over consultant

2022-02-01 19:13 UTC, GoldenAlpharex requested changes
This was a quick review, I probably missed something.

2022-02-01 19:13 UTC, GoldenAlpharex commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +	display_order = JOB_DISPLAY_ORDER_nanotrasen_consultant
RegEx user detected.

2022-02-01 19:25 UTC, hugmeorelse commented
> I understand the why of it but it still seems like punishing the role for the antics of bad faith players. Kinda a common thing, we should just hold people playing it to a higher standard.

It's not "bad faith" players, considering this is only for Veteran Crew. Misuse of this will get you removed from Veteran Crew extremely quick.

This role has no control over Station Command. They have always been a consultant, acting as the bridge between Central Command and Station Command, and the title has always been misleading.

2022-02-01 19:30 UTC, tf-4 commented
Forgot icon states, will take me a moment to hunt them down.

2022-02-09 22:40 UTC, kannthus commented
I feel its a little unnecessary, but at the same time if the names are staying as alt titles I don't think it's the end of the world. I fear newer players might misunderstand "Consultant" written on an airlock as the term for a medical personnel room, having it say "NT Consultant" rather then just "Consultant's room" will help with the ambiguity

2022-02-11 06:31 UTC, Zonespace27 commented on modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm
> +	alt_titles = list("Nanotrasen Consultant", "Nanotrasen Diplomat", "Central Command Consultant", "Nanotrasen Representative")
```suggestion
	alt_titles = list("Nanotrasen Consultant", "Nanotrasen Diplomat", "Central Command Consultant", "Nanotrasen Representative", "Central Command Representative")
```
May as well?

2022-02-15 08:51 UTC, tf-4 commented
Can't sit here and resolve merge conflicts while it's in limbo anymore. Feel free to fix the conflict and merge it, or don't.

2022-03-01 11:48 UTC, Gandalf2k15 commented
Rip TOM.

2022-03-01 12:03 UTC, merged

2022-03-02 09:09 UTC, OrionTheFox commented
this broke the hud icon :dying: