malf can no longer doomsday
Skyrat-SS13/Skyrat-TG pull request #11221
Opened 2022-02-02 01:40 UTC by jjpark-kb

## About The Pull Request
removes the doomsday ability, objective, and the doomsday device from malf ai.

## How This Contributes To The Skyrat Roleplay Experience
why do we want complete station-ending objectives...? 

## Changelog

:cl:
del: removed the doomsday ability and objective from malf ai
/:cl:

2022-02-02 01:48 UTC, theOOZ commented
I think this is taking good action out of the server.

I'm fairly certain this is live reviewed in the round by the staff team, and we have a policy team in case more caution is needed.

2022-02-02 01:50 UTC, tf-4 commented
This was made on Xyel's request

2022-02-02 01:52 UTC, hugmeorelse commented
> I think this is taking good action out of the server.
> 
> I'm fairly certain this is reviewed live in the round by the staff team, and we have a policy team in case more caution is needed.

It's my decision. This has very little upside and the downside is quite a bit for something that adds little to the game. If a nuke is what is needed to make the server lively, then we're doing it wrong.

Giving them a BSA in my respective opinion gives them more of an edge as a threat.

2022-02-02 02:11 UTC, theOOZ commented
Okay, I can understand that!
There's something I still worry about which is, the doomsday mode has great effects for borgs. Stuff that works incredibly well for our server thematic like the borg's lamps being forced on and turned red. (Its called doomsday mode) Losing this would be a big shame, and keeping some of this code in so it stuff as such can still be manually called - without the big station ending event - would make this disable hurt our silicon content much less.

2022-02-02 02:30 UTC, theOOZ commented on code/modules/mob/living/silicon/robot/robot.dm
> +		//lamp_doom = connected_ai.doomsday_device ? TRUE : FALSE SKYRAT EDIT: no more doomsday
This is a really cool part about borgs that would get lost.

2022-02-02 03:27 UTC, BurgerLUA commented
Removing round-ending events is the right step in the right direction. It's unfair to a lot of antag players who can't complete their gimmick because of another antag ending the round, and it's unfair to normal players who aren't just here to secure valids.

2022-02-02 05:21 UTC, Iamgoofball commented
so what's the gameplan for malf AIs now

2022-02-02 06:04 UTC, thestubborn commented
> so what's the gameplan for malf AIs now

blow rcds
lose

2022-02-02 07:06 UTC, Zenitheevee commented
> so what's the gameplan for malf AIs now

obstruct Sec from winning

2022-02-02 10:07 UTC, restlessObserver commented
So, if malf at the end have no other choice other than kill all crew, theyll plasmaflood and decompress. Because sometimes death is right ending, sometimes good people are ment to loose and be left defeated in dust. And this ending, sometimes, much more interesting then "good always wins" situation. And play it til the end is much harder. The point - not to delete doomsday function. Its to make players roleplay this situation, not to go cryo and PM about how they erps were interrupted.

2022-02-03 00:50 UTC, Gandalf2k15 requested changes
please instead of making all these non modular changes, literally just disable the AI's button for it.

2022-02-03 04:07 UTC, hugmeorelse commented
> So, if malf at the end have no other choice other than kill all crew, theyll plasmaflood and decompress. Because sometimes death is right ending, sometimes good people are ment to loose and be left defeated in dust. And this ending, sometimes, much more interesting then "good always wins" situation. And play it til the end is much harder. The point - not to delete doomsday function. Its to make players roleplay this situation, not to go cryo and PM about how they erps were interrupted.

ERP is not that common on Skyrat. Also, don't strawman. 

This isn't about ERP. This is about it being pretty boring all things considered.

2022-02-03 05:46 UTC, Grox103FM commented
Are you really have that much engineers what you need to repair the station after malfunction AI? Round end antagonists very dangerous and destructive, and after hour of war against them you need three hours to recovery. Instead of fighting the threat you fighting consequences. And, after round end antag you have disbalansed crew with mechs and many guns. Other antags will be no match to security, and its very painful to play against OP crew.

2022-02-15 14:01 UTC, closed without merging