[MODULAR] Feign impairment ceiling increase 1 minute -> 1 hour
Skyrat-SS13/Skyrat-TG pull request #11299
Opened 2022-02-06 08:22 UTC by Zonespace27

## About The Pull Request
Increases the amount of time feign impairment can last to up to 3600 seconds, being one hour.

## How This Contributes To The Skyrat Roleplay Experience
The one minute limit seems arbitary, you can cancel the impairment whenever you want and keep extending it manually forever.

## Changelog

:cl:
qol: Feign impairment now has a time limit of 1 hour, instead of 1 minute
/:cl:

2022-02-06 17:22 UTC, tf-4 commented
Could just do away with the cap, really. An hour seems just as arbitrary as a minute does.

2022-02-06 17:24 UTC, Zonespace27 commented
My concern with removing it entirely is that giving people the ability to set a number to anything without a cap has the potential for bad things

2022-02-06 18:06 UTC, tf-4 commented
> My concern with removing it entirely is that giving people the ability to set a number to anything without a cap has the potential for bad things

well, just put it to something like 5 hours that a round won't reasonably exceed.

2022-02-06 18:08 UTC, Zonespace27 commented
Done

2022-02-06 18:09 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/human.dm
>  	var/duration = input(src, "Enter how long you will feign [impairment]. (1 - 60 seconds)", "Duration in seconds", 25) as num|null
```suggestion
	var/duration = input(src, "Enter how long you will feign [impairment].", "Duration in seconds", 25) as num|null
```

2022-02-06 18:10 UTC, tf-4 approved these changes

2022-02-06 19:05 UTC, tf-4 requested changes
Suggested a better way on discord

2022-02-07 09:44 UTC, tf-4 approved these changes

2022-02-07 19:41 UTC, hugmeorelse commented
Is there a way to turn it on and off instead? @Zonespace27

2022-02-07 19:46 UTC, Zonespace27 commented
> Is there a way to turn it on and off instead? @Zonespace27

The variables this affects aren't booleans, and I've said my piece on setting this to be infinite

2022-02-10 02:57 UTC, hugmeorelse commented
> > Is there a way to turn it on and off instead? @Zonespace27
> 
> The variables this affects aren't booleans, and I've said my piece on setting this to be infinite

But is there a way to turn on and off?

2022-02-10 03:00 UTC, Zonespace27 commented
> > > Is there a way to turn it on and off instead? @Zonespace27
> > 
> > 
> > The variables this affects aren't booleans, and I've said my piece on setting this to be infinite
> 
> But is there a way to turn on and off, i.e. changing the timer from an hour to one second to make it go away?

Yes, this was a function beforehand to let you turn it off.

2022-02-14 21:04 UTC, merged