Makes security record photo generation not happen all at once
Skyrat-SS13/Skyrat-TG pull request #11334
Opened 2022-02-07 05:15 UTC by monster860

## About The Pull Request
Makes security record photo generation happen in a way as to *not* produce a massive amount of lag. In addition, potentially maybe fix a race condition that causes glitchy photo generation.

I'm not 100% sure if this is the best solution to the problem, it might be a further improvement to make a subsystem for generating flat icons.

2022-02-07 05:15 UTC, thestubborn commented
non modular

changelog

2022-02-07 05:57 UTC, nevimer commented
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346

This does this, it's calling the wrong proc

2022-02-07 23:00 UTC, Gandalf2k15 approved these changes
Looks good

2022-02-08 03:28 UTC, GoldenAlpharex requested changes

2022-02-08 03:28 UTC, GoldenAlpharex commented on modular_skyrat/modules/deferred_icon/code/deferred_icon.dm
> +		out_list["[D]"] = image(body.appearance)
Please avoid single-letter vars.

2022-02-08 03:28 UTC, GoldenAlpharex commented on modular_skyrat/modules/deferred_icon/code/deferred_icon.dm
> +	return get_human_image(null, J, P, DUMMY_HUMAN_SLOT_MANIFEST, show_directions)
Here too, single-letter var bad.

2022-02-22 00:21 UTC, closed without merging