(technically)[MODULAR] Fixes the MCR's damage and the lasers too actually + Expands the MCR mods and puts superheated emitter behind illegal tech
Skyrat-SS13/Skyrat-TG pull request #11377
Opened 2022-02-08 13:29 UTC by ErdinyoBarboza

## About The Pull Request
Apparently some time ago the base lasers damage without editing anything else. Damage has been lowered back to its TG value thus keeping the PR modular.

Second part of this PR moves the superheating MCR attachment into its own node that requires Illegal Tech researched. This is not a straight up removal as a Hellfire Upgrade has been added that works the same way normal hellfire lasers work with a damage of 25, better wounding capacity and an extra power usage of %20 increase.
![image](https://user-images.githubusercontent.com/25566633/152996119-c2488e08-c05d-4d13-91d9-5d0e17ad68e5.png)

## How This Contributes To The Skyrat Roleplay Experience
When MCR's were merged it caused an uprise in usage of lasers. However something was odd, they were somehow far too strong. Yet there was no code editing the damage of lasers in the MCR PR. This is apparently because of the upgraded base Beam Projectile damage. Which was not edited in any of its childs. Thus more used laser weapons were not affected by this buff (Captains Lasgun and currently Blueshields Lasgun), as well as the Lasgun and Egun were not preferred weapons due to Ballistics and further on Hardlight Bullets existing. Thus this effect was not felt till the merging of MCRs. 

Here are a few other projectiles to compare to:
```
/obj/projectile/bullet/c32
    name = ".32 bullet"
    damage = 15
/obj/projectile/bullet/c46x30mm
    name = "4.6x30mm bullet"
    damage = 20
/obj/projectile/beam/laser/hellfire
	name = "hellfire laser"
	wound_bonus = 0
	damage = 25
/obj/projectile/beam/laser
	damage = 27 // SKYRAT EDIT: 20
	wound_bonus = -30
	bare_wound_bonus = 40
```
As you can see rest of the weaponry were never changed and were in a good spot. However lasers being buffed the same amount of the HP upgrade was, meant that they did not follow the lethality rating of the rest of the guns.

Before this PR, a laser type weapon takes 5 hits to crit an unarmored person with a damage of 27.
Whereas normal bullets and the lasers in this merge takes 6.75 hits to crit someone with a damage of 20.

This PR should bring Lasers and by extension MCR's to a closer line in Skyrat Combat as the damage upgrade was the equivalent of upping the damage of 357 to 81 or in a way making the HP pool of people 100 just for that gun in its balance.

___
Second part of this PR adds a new emitter upgrade called hellfire emitter which fires lasers statistically equal to a hellfire laser.

This is a stand in for superheat emitter upgrades which have been moved to their own illegal tech requiring node in order to balance the immense amount of firestacks they they can put on people and their damage has been reduced to 15 as a tradeoff for the firestacks.

## Changelog

:cl:ErdinyoBarboza, ToryJ for making me code dive
balance: Removes the %35 Damage Buff from Base Lasers, returning them to 20 damage from 27. Superheated Lasers now do 15 damage while keeping their firestacks but require Illegal Technology Research. However Hellfire Emitter Upgrade came in its place which makes the lasers more likely to wound as well as provide the same statistics as hellfire lasers (25 Damage but %20 more power usage)
spellcheck: Fixes some of the comments in the MCR Module
imageadd: Adds a sprite for the Hellfire Emitter Upgrade
/:cl:

2022-02-08 16:51 UTC, Zenitheevee commented
My only *Real* issue here is that it further makes the diffuser pointless to take. 
20 damage split 3 ways 
Vs
25 damage, a *default* wound bonus opposed to the default laser's -30, At the cost of 20% increase power use...

2022-02-08 17:47 UTC, Gandalf2k15 commented on modular_skyrat/modules/microfusion/code/microfusion_gun_attachments.dm
> +	var/projectile_override =/obj/projectile/beam/laser/microfusion/scatter
```suggestion
	var/projectile_override = /obj/projectile/beam/laser/microfusion/scatter
```

2022-02-08 17:48 UTC, Gandalf2k15 commented on modular_skyrat/modules/microfusion/code/microfusion_gun_attachments.dm
> +	var/projectile_override =/obj/projectile/beam/laser/microfusion/hellfire
```suggestion
	var/projectile_override = /obj/projectile/beam/laser/microfusion/hellfire
```

2022-02-08 17:49 UTC, Gandalf2k15 commented on modular_skyrat/modules/microfusion/code/microfusion_gun_attachments.dm
> +	var/projectile_override =/obj/projectile/beam/laser/microfusion/scatter
```suggestion
	var/projectile_override = /obj/projectile/beam/laser/microfusion/superheated
```

2022-02-08 18:53 UTC, Zonespace27 commented on modular_skyrat/modules/microfusion/code/microfusion_gun_attachments.dm
> +The gun can fire volleys of shots.
wrong comment i think

2022-02-12 06:46 UTC, OrionTheFox commented on modular_skyrat/modules/microfusion/code/cargo_stuff.dm
> +	desc = "Micron Control Systems Incorporated supplied MCR-01 Military spec attachments! This crate comes in a utilitarian repeater loadout."
```suggestion
	desc = "Micron Control Systems Incorporated supplied MCR-01 Military spec attachments! This crate comes with two utilitarian repeater loadout."
```

2022-02-12 06:51 UTC, OrionTheFox commented on modular_skyrat/modules/microfusion/code/microfusion_designs.dm
> +	build_path = /obj/item/microfusion_gun_attachment/suppressor
Desc, ID, and Build_path arent to the proper things

2022-02-12 06:51 UTC, OrionTheFox commented on modular_skyrat/modules/microfusion/code/microfusion_designs.dm
> +	id = "microfusion_gun_attachment_suppressor"
description is wrong

2022-02-12 06:52 UTC, OrionTheFox commented on modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
> +		//reload_timer(user, attacking_item)
do we need this commented out code?

2022-02-12 06:53 UTC, OrionTheFox commented on modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
> +			to_chat(user, span_notice("You insert [inserting_cell] into [src]!"))
would be easier if this just early-returned for if(!display_message)

2022-02-12 06:53 UTC, OrionTheFox commented on modular_skyrat/modules/microfusion/code/microfusion_techweb.dm
> +/datum/techweb_node/quantum_microfusion
path is outdated

2022-02-14 06:23 UTC, Gandalf2k15 requested changes
Fix up requested changes

2022-02-14 07:37 UTC, ErdinyoBarboza commented
@Gandalf2k15 its ready

2022-02-16 16:46 UTC, Gandalf2k15 commented
[09:40:33] Runtime in stack_trace.dm,3: Invalid techweb nodes detected
  proc name: stack trace (/proc/stack_trace)
  src: null
  call stack:
  stack trace("Invalid techweb nodes detected")
  Research (/datum/controller/subsystem/research): initialize all techweb nodes(0)
  Research (/datum/controller/subsystem/research): Initialize(3[48](https://github.com/Skyrat-SS13/Skyrat-tg/runs/5213960866?check_suite_focus=true#step:7:48)329)
  Master (/datum/controller/master): Initialize(10, 0, 1)

2022-02-20 12:49 UTC, Gandalf2k15 approved these changes

2022-02-20 12:49 UTC, merged