[MODULAR]Modular Disabler - Pushing(Ridable) Beams, Shoe Shenanigans, Disgust, Brutality, and More! [WIP][DRAFT]
Skyrat-SS13/Skyrat-TG pull request #11622
Opened 2022-02-20 05:17 UTC by nevimer

## About The Pull Request

Right! So, this is still very much a work in progress. I'm mostly opening a PR for this to showcase what I am working on regarding these. 

Normal disablers can be upgraded into a modular disabler with an upgrade kit available by completing toxins first test. 

As a tradeoff to the upgrade, the time to stun is significantly lower, but have self recharging ammunition (like a PKA).

The upgraded disablers expel water and sparks when firing, further reducing their effectiveness in fights due to the slip risk and heat they produce. Right now it has the backblast, but I think that goes too far and is abusable. Subject to removal. 

Also. This is probably awful code but do tell how to improve!

Have some videos from testing.
## Pushing shots:
https://user-images.githubusercontent.com/77420409/154829164-609f7db1-81cd-49fa-bef3-c9f21762b9a0.mp4

## Hallucination (Subject to Change)
https://user-images.githubusercontent.com/77420409/154829208-0c5514d4-ccd2-43f1-b901-d5660c8f51cf.mp4

## Applying pushing shot upgrade to an upgrade disabler

https://user-images.githubusercontent.com/77420409/154829415-a1bfb38d-c73a-4900-b8f4-da462d088b09.mp4

## WHAT?

Modular disablers! You attach things to them and make your disabler do things! Currently: New shot modifiers, and infinite ammo!

## WHERE?

Antag items and security items! Right after toxins, hopefully.

## WHO?

Hopefully these are in lots of peoples hands!

## WHY?

I was bored and wanted to practice writing things. It's clear that we the players are currently unhappy with the current non lethal options, and are far too lethal. This should move us away from one hit stuns and lethals as the solution to PvP encounters. 

## How This Contributes To The Skyrat Roleplay Experience

HOPEFULLY this makes both antags and security players have a bit more fun in their combat gameplayer, with weapons that are *not* lethal or stun based. 

## Quit touching security!!

Things could be better! This I hope reduces reliance on stun based combat.

## Changelog

:cl:
add: Nanotrasen Research and Development has released a new line of disabler barrel attachments. Disablers can now be upgraded to be modifiable, at a cost. 
code: Moves all the skyrat edits into the modular file, restores the TG versions where applicable. 

/:cl:

2022-02-20 05:26 UTC, Zonespace27 requested changes

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +	var/mob/living/carbon/hit = target
you could typecast the `target` argument to mob/living/carbon and just do an early return if an `istype(target)` fails

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +	var/mob/living/carbon/hit = target
ditto

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +	var/mob/living/carbon/hit = target
ditto

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +	if(ishuman(hit))
ditto

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +		hit.adjust_drowsyness(rand(10,20))
ditto

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +	if(iscarbon(hit))
ditto and early return

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/beams.dm
> +		spawn(30 SECONDS)
don't solely take my word for it but I'm pretty sure everything that needs to be delayed after the `spawn()` needs to be indented

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/disabler_modular.dm
> +/obj/item/gun/energy/disabler/upgraded
code doc comments

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/disabler_modular.dm
> +	Initialize(mapload)
never use relative pathing

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/disabler_modular.dm
> +	name = "upgraded disabler"
name should be at the very top, above all the custom variables

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/disabler_modular.dm
> +	Initialize(mapload)
add a line break between the vars and the procs

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/disabler_modular.dm
> +		var/turf/open/T = get_turf(src)
one letter vars are bad

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/disabler_modular.dm
> +			for(var/obj/item/gun/energy/disabler/upgraded/K in loc.get_all_contents())
one letter vars are bad

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/kits.dm
> +	var/obj/item/gun/energy/disabler/upgraded/target_obj = target
typecast the `target` argument to `/obj/item/gun/energy/disabler/upgraded`, do an `istype(target)` check here with an early return instead

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/kits.dm
> +	qdel(src)
```suggestion
	QDEL_NULL(src)
```

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/upgraded_templates.dm
> +/obj/item/gun/energy/disabler/upgraded/disgust // Disgusting Disabler...
Why is this here?

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/upgraded_templates.dm
> +/obj/item/gun/energy/disabler/upgraded/warcrime // Antag Item Template (Intended to buy this with TC)
same goes for here

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/uplink_items.dm
> +	name = "Warcrime Barrel"
ideally a more consise name

2022-02-20 05:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_disabler/uplink_items.dm
> +	surplus = 2
note that this knocks down the chance of it being in a surplus crate to 2%

2022-02-20 17:22 UTC, KathrinBailey commented
Wouldn't the backblast just set you on fire? It's not a shoulder-mounted disabler or something.
Also, the water is very meme-y, why would we want slip combat to ever rear its ugly head like this? Half the server were sick and tired of it back in the Cit days.

2022-02-20 17:36 UTC, nevimer commented
> Wouldn't the backblast just set you on fire? It's not a shoulder-mounted disabler or something.
> Also, the water is very meme-y, why would we want slip combat to ever rear its ugly head like this? Half the server were sick and tired of it back in the Cit days.

Water emissions and backblast are going away. They do suck. Water is probably going to be replaced with a different gas, maybe miasma? or just co2.

2022-02-20 17:39 UTC, nevimer commented
Honestly, fuck this. If people are just going to downvote it while it is a draft and not even nearing done, I'll just concentrate my efforts some where else.

2022-02-20 20:00 UTC, nevimer commented
New name, since I probably will be removing a bunch of things and don't want to make promises in a title.

2022-02-20 21:09 UTC, Zergspower commented
holy shit that's a huge buff...

2022-02-20 22:31 UTC, ArdentSpark commented
To be fair, it's not inherantly a buff. It's an upgrade system. It has the potential to be imbalanced, but balancing is easier than coding this system from scratch, and can always come after it's finished development if required

> Normal disablers can be upgraded into a modular disabler with an upgrade kit available by completing toxins first test.
> 
> As a tradeoff to the upgrade, the time to stun is significantly lower, but have self recharging ammunition (like a PKA).

Although I do think this is supposed to say "Higher", as lower time to stun means quicker stuns.
After discussing with Nevimer, we kind of came to the conclusion that the MCR is one of the most fun things in the security arsenal. If the balance is done right with these I don't think it's a bad idea, even if I disagree with limitless disablers

(also this is a draft, I'm not sure we should be worrying too much about balance at this stage.)

2022-02-21 06:22 UTC, Zergspower commented
> To be fair, it's not inherantly a buff. It's an upgrade system. It has the potential to be imbalanced, but balancing is easier than coding this system from scratch, and can always come after it's finished development if required
> 
> > Normal disablers can be upgraded into a modular disabler with an upgrade kit available by completing toxins first test.
> > As a tradeoff to the upgrade, the time to stun is significantly lower, but have self recharging ammunition (like a PKA).
> 
> Although I do think this is supposed to say "Higher", as lower time to stun means quicker stuns. After discussing with Nevimer, we kind of came to the conclusion that the MCR is one of the most fun things in the security arsenal. If the balance is done right with these I don't think it's a bad idea, even if I disagree with limitless disablers
> 
> (also this is a draft, I'm not sure we should be worrying too much about balance at this stage.)

i'm talking about the yeet them 6 tiles after hitting them once mostly - and definitely the self-recharge is too much imo. MCR's may be fun but they are currently overpowered as hell as well :<

2022-03-11 15:29 UTC, closed without merging

2022-03-11 15:29 UTC, nevimer commented
On hold for now.