[MODULAR] Rodstopper now WARNS LOUDLY to EVACUATE the AREA when it is DEPLOYED
Skyrat-SS13/Skyrat-TG pull request #11651
Opened 2022-02-21 21:40 UTC by nevimer

## About The Pull Request

The rodstopper is an undocumented mechanic that only servers to round remove players with no warning or thought behind it. People will tell you "Build the Rodstopper, CE!" - but there is no way to know what it does - you only know it somehow stops rods? Well, you'd be surprised and your round ruined when it just hard round removes you. It's one of the very few sources of that, and it's completely and utterly bullshit for its victims.

## How This Contributes To The Skyrat Roleplay Experience

Same as above.

## Changelog

:cl:

qol: Rodstopper now yells at you to RUN.

/:cl:

2022-02-21 21:50 UTC, SpaceVampire commented
Now make it actually require power in order to work, so that the meta isn't just build it right on the edge of deep space.
Because I think it would be cooler if you had to pick some out of the way actual location, or make a tiny space base for it.

2022-02-21 22:25 UTC, thestubborn commented
> with no warning or thought behind it

the thought is that
maybe
you shouldn't be able to freely remove a rod unless you're the rd
read the original pr

> but there is no way to know what it does

have you tried
examining it?

2022-02-21 22:27 UTC, thestubborn commented
oh and
https://github.com/Skyrat-SS13/Skyrat-tg/pull/8085
entire pr is a skill issue

2022-02-21 22:28 UTC, thestubborn commented on modular_skyrat/modules/rod-stopper/code/rodstopper.dm
>  	. += span_warning("It will create a localized reality-collapse when stopping a rod, keep your distance!")
HMMMM
WHATS THIS?
IS IT
TELLING YOU WHAT IT DOES?

2022-02-21 22:29 UTC, nevimer commented
@thestubborn 

Wow, what a thoughtful comment! I totally didn't see the `	. += span_warning("It will create a localized reality-collapse when stopping a rod, keep your distance!")
`
line when making this! How very insightful.

We will make all players go through the entire github pull request history every time they want to use a new object, as that is the only way to learn the game!

2022-02-21 22:31 UTC, thestubborn commented
> @thestubborn
> 
> Wow, what a thoughtful comment! I totally didn't see the ` . += span_warning("It will create a localized reality-collapse when stopping a rod, keep your distance!") ` line when making this! How very insightful.
> 
> We will make all players go through the entire github pull request history every time they want to use a new object, as that is the only way to learn the game!

if players (like you) are too dumb to examine an item, they deserve to be rr'd

2022-02-21 22:32 UTC, nevimer commented
> > @thestubborn
> > Wow, what a thoughtful comment! I totally didn't see the `. += span_warning("It will create a localized reality-collapse when stopping a rod, keep your distance!")` line when making this! How very insightful.
> > We will make all players go through the entire github pull request history every time they want to use a new object, as that is the only way to learn the game!
> 
> if players (like you) are too dumb to examine an item, they deserve to be rr'd

Wow, what a hot take!

2022-02-21 22:36 UTC, jjpark-kb commented
Do not be toxic in PRs, thanks.

2022-02-22 17:29 UTC, GoldenAlpharex requested changes
Also, like, I feel like it could become obnoxious if it plays that on a constant loop, I'd probably suggest making the timer 15 seconds instead of just 7.

2022-02-22 17:29 UTC, GoldenAlpharex commented on modular_skyrat/modules/rod-stopper/code/rodstopper.dm
> +	addtimer(CALLBACK(src, .proc/warn_area), 70, TIMER_OVERRIDE|TIMER_UNIQUE) // sound file length for looping
```suggestion
	addtimer(CALLBACK(src, .proc/warn_area), 7 SECONDS, TIMER_OVERRIDE|TIMER_UNIQUE) // sound file length for looping
```

2022-02-24 21:14 UTC, merged