[SEMI-MODULAR][SPRITES-WANTED] Upgraded Borg Snack Dispensor
Skyrat-SS13/Skyrat-TG pull request #11941
Opened 2022-03-07 10:45 UTC by ZephyrTFA

## About The Pull Request

Adds a new and improved borg snack dispensor, able to be installed by any borg.

** I still need sprites for bacon strips and a cookie made out of cloth, please send help.

## How This Contributes To The Skyrat Roleplay Experience

Lizarbs need snacks too >:(

## Changelog

:cl:
add: Upgraded Borg Snack Dispensor
/:cl:

2022-03-07 14:46 UTC, Zonespace27 requested changes

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	construction_time = 10
```suggestion
	construction_time = 1 SECONDS
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg/upgrade/snack_dispensor
```suggestion
/obj/item/borg/upgrade/snack_dispenser
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	name = "Cyborg Upgrade (Snack Dispensor)"
```suggestion
	name = "Cyborg Upgrade (Snack Dispenser)"
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/datum/design/borg_snack_dispensor
```suggestion
/datum/design/borg_snack_dispenser
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	name = "Cyborg Upgrade (Snack Dispensor)"
```suggestion
	name = "Cyborg Upgrade (Snack Dispenser)"
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	name = "Cyborg Upgrade (Snack Dispensor)"
```suggestion
	name = "Cyborg Upgrade (Snack Dispenser)"
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg/upgrade/snack_dispensor/action(mob/living/silicon/robot/R, user)
```suggestion
/obj/item/borg/upgrade/snack_dispenser/action(mob/living/silicon/robot/R, user)
```
Also, no one-letter vars please

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		var/obj/item/borg_snack_dispensor/snack_dispensor = new /obj/item/borg_snack_dispensor(R.model)
```suggestion
		var/obj/item/borg_snack_dispensor/snack_dispenser = new(R.model)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		R.model.basic_modules += snack_dispensor
```suggestion
		R.model.basic_modules += snack_dispenser
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		R.model.add_module(snack_dispensor, FALSE, TRUE)
```suggestion
		R.model.add_module(snack_dispenser, FALSE, TRUE)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg/upgrade/snack_dispensor/deactivate(mob/living/silicon/robot/R, user)
```suggestion
/obj/item/borg/upgrade/snack_dispenser/deactivate(mob/living/silicon/robot/R, user)
```
One letter vars bad

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	if(.)
Early return

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	for(var/obj/item/borg_snack_dispensor/dispensor in R.model)
```suggestion
	for(var/obj/item/borg_snack_dispenser/dispenser in R.model)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		R.model.remove_module(dispensor, TRUE)
```suggestion
		R.model.remove_module(dispenser, TRUE)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor
```suggestion
/obj/item/borg_snack_dispenser
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	var/snack_name = initial(selected_snack.name)
Unneeded var creation

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	to_chat(user, span_notice("[src] is now dispensing [snack_name]"))
```suggestion
	to_chat(user, span_notice("[src] is now dispensing [snack_name]."))
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor/attack(mob/living/patron, mob/living/user, params)
```suggestion
/obj/item/borg_snack_dispenser/attack(mob/living/patron, mob/living/user, params)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	var/mob/living/silicon/robot/borg = user
You could change the typecasting of the user argument instead of making a new var

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor/AltClick(mob/user)
```suggestion
/obj/item/borg_snack_dispenser/AltClick(mob/user)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor/afterattack(atom/target, mob/user, proximity_flag, click_parameters)
```suggestion
/obj/item/borg_snack_dispenser/afterattack(atom/target, mob/user, proximity_flag, click_parameters)
```

2022-03-07 14:46 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	var/mob/living/silicon/robot/borg = user
See previous typecasting arguments suggestion

2022-03-07 21:23 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor/attack_self(mob/user, modifiers)
```suggestion
/obj/item/borg_snack_dispenser/attack_self(mob/user, modifiers)
```

2022-03-07 21:23 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor/examine(mob/user)
```suggestion
/obj/item/borg_snack_dispenser/examine(mob/user)
```

2022-03-07 21:23 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/borg_snack_dispensor/Initialize(mapload)
```suggestion
/obj/item/borg_snack_dispenser/Initialize(mapload)
```

2022-03-07 21:25 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	build_path = /obj/item/borg/upgrade/snack_dispensor
```suggestion
	build_path = /obj/item/borg/upgrade/snack_dispenser
```

2022-03-07 21:25 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		var/obj/item/borg_snack_dispensor/snack_dispenser = new(R.model)
```suggestion
		var/obj/item/borg_snack_dispenser/snack_dispenser = new(R.model)
```

2022-03-07 21:26 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	name = "\improper Automated Borg Snack Dispensor"
```suggestion
	name = "\improper Automated Borg Snack Dispenser"
```

2022-03-09 14:37 UTC, Zonespace27 commented on code/modules/research/techweb/all_nodes.dm
> +		"borg_upgrade_snacks", // SKYRAT ADDITION - BETTER BORG SNACK DISPENSORS
```suggestion
		"borg_upgrade_snacks", // SKYRAT ADDITION - BETTER BORG SNACK DISPENSERS
```
Missed this in original pass

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/food/cookie/bacon
why not use `/obj/item/food/meat/bacon` since that already exists?

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		CRASH("[src] being used by non borg [user]")
```suggestion
		CRASH("[src] being used by non borg [user].")
```

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		CRASH("[src] being used by non borg [user]")
```suggestion
		CRASH("[src] being used by non borg [user].")
```

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	icon_state = "rsf"
icon state could be better named

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	var/borg_charge_cutoff = 200
Could make this into a preprocessor define

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	var/borg_charge_usage = 50
ditto

2022-03-09 14:37 UTC, Zonespace27 commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	/// For storing modules that we remove, since the upgraded snack dispensor automatically removes inferior versions
```suggestion
	/// For storing modules that we remove, since the upgraded snack dispenser automatically removes inferior versions
```

2022-03-10 07:57 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +/obj/item/food/cookie/bacon
because the snacks shouldnt have food levels of nutriment and other reagents

2022-03-10 07:57 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +		CRASH("[src] being used by non borg [user]")
This a CRASH, which doesnt need punctuation

2022-03-10 07:57 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	icon_state = "rsf"
That is the icon_state of the /TG/ item.

2022-03-10 07:58 UTC, ZephyrTFA commented on modular_skyrat/modules/borg_buffs/code/snack_dispensor.dm
> +	/// For storing modules that we remove, since the upgraded snack dispensor automatically removes inferior versions
I'm not going to take the effort to fix this in comments.

2022-03-10 07:58 UTC, ZephyrTFA commented on code/modules/research/techweb/all_nodes.dm
> +		"borg_upgrade_snacks", // SKYRAT ADDITION - BETTER BORG SNACK DISPENSORS
I'm not going to take the effort to fix this in comments.

2022-03-15 01:47 UTC, SpaceVampire commented
I'm not really sure why all cyborgs need access to this upgrade.
Wouldn't it make more sense to have it only work for Service Cyborgs?
It just seems weird to have the engineering or janitor robot running around with free bacon.
When instead it could be used to push one of the more specialized modules into having more use.

2022-03-23 23:52 UTC, Gandalf2k15 approved these changes
ok

2022-03-23 23:52 UTC, merged

2022-04-14 13:58 UTC, tobjv commented
idk if this is the cause or not, but when installed it seems to remove ice cream from the selection