Refits and slightly demodularizes upstream medical and detective jumpsuits for digis
Skyrat-SS13/Skyrat-TG pull request #11946
Opened 2022-03-07 21:41 UTC by Ebin-Halcyon

## About The Pull Request
Tin.
![image](https://user-images.githubusercontent.com/81479835/157122317-b327f706-0728-4fc4-957a-e6e929fef559.png)

## How This Contributes To The Skyrat Roleplay Experience

## Changelog

:cl:
imageadd: Upstream medical and security clothing now fit on digi legs
/:cl:

2022-03-08 18:46 UTC, GoldenAlpharex requested changes

2022-03-08 18:46 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/under/misc.dm
> -/obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck
Does upstream have the turtleneck now, or did you just remove it?

2022-03-08 23:00 UTC, Ebin-Halcyon commented on modular_skyrat/modules/customization/modules/clothing/under/misc.dm
> -/obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck
Upstream has it now along with a new spiffy skirt and obj sprite

2022-03-17 02:28 UTC, Ebin-Halcyon commented
guh

2022-03-18 03:42 UTC, merged