Combat overhaul - Part A: Baton specific changes
Skyrat-SS13/Skyrat-TG pull request #12058
Opened 2022-03-13 17:04 UTC by Gandalf2k15

## About The Pull Request

TBA

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-03-14 12:31 UTC, MassacreDemigirl commented
Im guessing the hit cooldown will be lowered considerably or else almost all batons become completely useless

2022-03-14 14:17 UTC, AzyreR commented
So you WANT security to harmbaton, I fail to see how this is a wanted or good change at all, knockdown is literally all the batons have going for, and with the disarm getting removed on knockdown aswell.. I'm sorry but I can't wait to see sec get outplayed by a single esword and eshield unable to do anything.

2022-03-14 16:08 UTC, RatFromTheJungle commented
> So you WANT security to harmbaton, I fail to see how this is a wanted or good change at all, knockdown is literally all the batons have going for, and with the disarm getting removed on knockdown aswell.. I'm sorry but I can't wait to see sec get outplayed by a single esword and eshield unable to do anything and resort to lethals, which is the opposite of what i thought this server's aim was.
> 
> Like you geninely expect anyone from sec to land what.. 6 hits on someone only to put them in stamcrit while being put into softcrit themselves in 5 esword hits?

>armor penning 20 damage

"The knockdown is all they have going for" ..

>Full-armor penning 20 damage

>The difference is one hit

>probably less once you factor is sec's high melee armor

2022-03-14 16:23 UTC, AzyreR commented
> > So you WANT security to harmbaton, I fail to see how this is a wanted or good change at all, knockdown is literally all the batons have going for, and with the disarm getting removed on knockdown aswell.. I'm sorry but I can't wait to see sec get outplayed by a single esword and eshield unable to do anything and resort to lethals, which is the opposite of what i thought this server's aim was.
> > Like you geninely expect anyone from sec to land what.. 6 hits on someone only to put them in stamcrit while being put into softcrit themselves in 5 esword hits?
> 
> armor penning 20 damage
> 
> "The knockdown is all they have going for" ..
> 
> Full-armor penning 20 damage
> 
> The difference is one hit
> 
> probably less once you factor is sec's high melee armor

You haven't taken into consideration that the batons stamina hit is about two time slower than a regular hit.

You haven't taken into consideration block chance.

Stamina damage can be recovered, easily fixable by using stims.

No way to knockdown, no way to slow down, no way to disarm, all you'd need to do is target their arms or legs with any weapon and you'll literally have them crawling unable to do anything but take hits.

2022-03-14 18:31 UTC, RatFromTheJungle commented
> > > So you WANT security to harmbaton, I fail to see how this is a wanted or good change at all, knockdown is literally all the batons have going for, and with the disarm getting removed on knockdown aswell.. I'm sorry but I can't wait to see sec get outplayed by a single esword and eshield unable to do anything and resort to lethals, which is the opposite of what i thought this server's aim was.
> > > Like you geninely expect anyone from sec to land what.. 6 hits on someone only to put them in stamcrit while being put into softcrit themselves in 5 esword hits?
> > 
> > 
> > armor penning 20 damage
> > "The knockdown is all they have going for" ..
> > Full-armor penning 20 damage
> > The difference is one hit
> > probably less once you factor is sec's high melee armor
> 
> You haven't taken into consideration that the batons stamina hit is about two time slower than a regular hit.
> 
> You haven't taken into consideration block chance.
> 
> Stamina damage can be recovered, easily fixable by using stims.
> 
> No way to knockdown, no way to slow down, no way to disarm, all you'd need to do is target their arms or legs with any weapon and you'll literally have them crawling unable to do anything but take hits.
> 
> If you need more of a visual representation, face to face, a naked antag with an esword against a armored officer with a baton, can just walk up to them, target their chest and tank every single baton hit the officer lands on them before they just kill the officer.

counter point: I take a 10u pill of sali-acid (can out heal most brute causing items) and face-tank the d-e-sword while spamming my baton

(it's also immensely more easy to get then dedicated anti-stamina items like bathsalts)

2022-03-16 20:02 UTC, RuneQuester commented
> > > > So you WANT security to harmbaton, I fail to see how this is a wanted or good change at all, knockdown is literally all the batons have going for, and with the disarm getting removed on knockdown aswell.. I'm sorry but I can't wait to see sec get outplayed by a single esword and eshield unable to do anything and resort to lethals, which is the opposite of what i thought this server's aim was.
> > > > Like you geninely expect anyone from sec to land what.. 6 hits on someone only to put them in stamcrit while being put into softcrit themselves in 5 esword hits?
> > > 
> > > 
> > > armor penning 20 damage
> > > "The knockdown is all they have going for" ..
> > > Full-armor penning 20 damage
> > > The difference is one hit
> > > probably less once you factor is sec's high melee armor
> > 
> > 
> > You haven't taken into consideration that the batons stamina hit is about two time slower than a regular hit.
> > You haven't taken into consideration block chance.
> > Stamina damage can be recovered, easily fixable by using stims.
> > No way to knockdown, no way to slow down, no way to disarm, all you'd need to do is target their arms or legs with any weapon and you'll literally have them crawling unable to do anything but take hits.
> > If you need more of a visual representation, face to face, a naked antag with an esword against a armored officer with a baton, can just walk up to them, target their chest and tank every single baton hit the officer lands on them before they just kill the officer.
> 
> counter point: I take a 10u pill of sali-acid (can out heal most brute causing items) and face-tank the d-e-sword while spamming my baton or the sali-acid pen from the 300 cred brute first-aid kit at cargo
> 
> (it's also immensely more easy to get then dedicated anti-stamina items like bathsalts)

Im sorry, 10U sali-acid cannot face-tank a fucking double energy sword. 

Also, you just tried to turn this into a slapfight. That's not how combat works. Deswords also have block chance. Everything AzyreR said is still correct. Bath salts are not super hard to make, and even then, just make ephinedrine and becomes immune to stamina. Or some of the maint drugs.

2022-03-17 04:12 UTC, ChungusGamer666 commented
> So you WANT security to harmbaton, I fail to see how this is a wanted or good change at all, knockdown is literally all the batons have going for, and with the disarm getting removed on knockdown aswell.. I'm sorry but I can't wait to see sec get outplayed by a single esword and eshield unable to do anything and resort to lethals, which is the opposite of what i thought this server's aim was.
> 
> Like you geninely expect anyone from sec to land what.. 6 hits on someone only to put them in stamcrit while being put into softcrit themselves in 5 esword hits?

I'd rather get beaten to a pulp than stunned, because being beaten to a pulp at least lets me fight back.
Fuck stun combat.

2022-03-18 22:01 UTC, GoldenAlpharex requested changes

2022-03-18 22:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/combat_overhaul/code/baton.dm
> +	knockdown_time = (2.5 SECONDS)
Those brackets are not necessary.
```suggestion
	knockdown_time = 0 SECONDS
	stamina_damage = 20

/obj/item/melee/baton/security
	knockdown_time = 0 SECONDS
	stamina_damage = 20

/obj/item/melee/baton/security/apply_stun_effect_end(mob/living/target)
	return FALSE

/obj/item/melee/baton/telescopic/contractor_baton
	knockdown_time = 2.5 SECONDS
```

2022-05-11 01:17 UTC, Gandalf2k15 commented
I'll revisit this another year

2022-05-11 01:17 UTC, closed without merging