[SEMI-MODULAR] Adds admin buttons for exploitable overrides, as well as an OPFOR service, letting admins easily give people exploitables. Also cleans up some code I made before.
Skyrat-SS13/Skyrat-TG pull request #12087
Opened 2022-03-15 01:41 UTC by nikothedude

## About The Pull Request

Makes a bunch of edits in some core files, does what it says in the title. It also makes a few random changes to the code I made on this.

Won't lie, made this PR while tired off my ass, so don't be surprised if there's some fuckiness in the code.

## How This Contributes To The Skyrat Roleplay Experience

Exploitables good.

## Changelog

:cl:
add: New OPFOR services for exploitables.
admin: Added new admin buttons in traitor panel for adding or removing exploitable access.
/:cl:

2022-03-15 01:50 UTC, Zonespace27 requested changes

2022-03-15 01:50 UTC, Zonespace27 commented on modular_skyrat/modules/opposing_force/code/equipment/services.dm
> +/datum/opposing_force_equipment/service/give_exploitables
this shouldn't be two different services, consolidate it into one.

2022-03-15 01:50 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human.dm
> +	if (is_special_character(usr) || usr.mind.has_exploitables_override)
remove all special character stuff and just give `has_exploitable_override` to all antagonists instead.

2022-03-15 01:50 UTC, Zonespace27 commented on code/datums/mind.dm
> +				if (has_exploitables_override)
this and 3 lines below can be consolidated into `has_exploitables_override = !has_exploitables_override`

2022-03-15 18:08 UTC, SpaceVampire commented
Do you think you improve the exploitable menu, so that it doesn't just dump directly into chat?
I feel like it would be a lot better if you could just open/close them inside of the main thing.
Pretty sure that is a lot more close to how it is handled in other codebases.

2022-03-15 19:43 UTC, nikothedude commented
> Do you think you improve the exploitable menu, so that it doesn't just dump directly into chat? I feel like it would be a lot better if you could just open/close them inside of the main thing. Pretty sure that is a lot more close to how it is handled in other codebases.

There was actually a reason I had normal record viewings dump to chat, because having a TGUI window suddenly obscuring your view might make fighting a little difficult, although I kinda question who'd be looking at records while fighting, so I might just convert it all to TGUI.

2022-03-15 19:44 UTC, nikothedude commented
Drafting this, I'm turning this into a refactor of how we handle records because god damn I was not good at code when I made it.

2022-03-25 18:31 UTC, nikothedude commented
Doing this in another PR. Im gonna change how it all works.

2022-03-25 18:31 UTC, closed without merging