Crew Monitor Robotic Races Update
Skyrat-SS13/Skyrat-TG pull request #12147
Opened 2022-03-17 13:02 UTC by Morokite

## About The Pull Request

Modifies crew.dm and CrewConsole.js to update the crew monitor with a flag for any robotic races (IPC, Synthliz, Synthhuman, etc.)

## How This Contributes To The Skyrat Roleplay Experience

Well here on Skyrat we have a ton of synth races and players who play them.
Ever see someone injured on the crew monitor, grab your medkit and some chems and rush out to help save the day then.. Uh oh. He's a synth. So all that stuff you brought is **useless**. I know I have a time or two again. And we got new friendly robot faces popping up everyday!

This just adds a little cog icon if they aren't organic.
![image](https://user-images.githubusercontent.com/84706993/158812827-5d373dba-9953-44ee-ba92-6b912ea8923c.png)

Icon updated to:
![image](https://user-images.githubusercontent.com/84706993/159103004-67d07528-e7fc-4ea6-974e-4344c748eb3b.png)

## Changelog

:cl: Deek-Za
qol: Flags non-organic races on the crew monitor.
/:cl:

2022-03-17 15:43 UTC, Zonespace27 commented
Since it's a nonmodular TGUI change, please take it upstream first.

2022-03-17 20:04 UTC, Elli-Skala commented
> Since it's a nonmodular TGUI change, please take it upstream first.

Tg doesn't appear to have any non adminbussed in synth race. So this would be quite useless to them

2022-03-17 20:04 UTC, Zonespace27 commented
> > Since it's a nonmodular TGUI change, please take it upstream first.
> 
> Tg doesn't appear to have any non adminbussed in synth race. So this would be quite useless to them

TG has IPCs

2022-03-17 20:06 UTC, Zonespace27 commented
> > Since it's a nonmodular TGUI change, please take it upstream first.
> 
> Tg doesn't appear to have any non adminbussed in synth race. So this would be quite useless to them

Less modular code for us to maintain, and it's not a *net loss* to TG

2022-03-17 23:05 UTC, Morokite commented
> > > Since it's a nonmodular TGUI change, please take it upstream first.
> > 
> > 
> > Tg doesn't appear to have any non adminbussed in synth race. So this would be quite useless to them
> 
> Less modular code for us to maintain, and it's not a _net loss_ to TG

Unfortunately it wouldn't work upstream as it takes advantage of Skyrat code written specifically for our multitude of synthetic races. We'd have to modify TGs code further to implement it for them without it breaking(And they'd only gain the functionality for extremely niche situations). And even then when it came back downstream to us, we'd have to patch it again for it to work with our setup as ours is very different. 
I'd say redoing and adding a more additional tweaks to their code for them to reap no benefit wouldn't be in their best interests. And we'd have to maintain it on our end anyway.

2022-03-17 23:17 UTC, Zonespace27 commented
Fair 'nuff

2022-03-18 21:07 UTC, YakumoChen commented
Would recommend an icon different than the cog, which is a universal symbol for settings or options. Is there no robot head icon?

2022-03-19 02:18 UTC, Morokite commented
> Would recommend an icon different than the cog, which is a universal symbol for settings or options. Is there no robot head icon? 🤖

Fair. The reason why I went with the cog is well, cause it's associated with mechanical things and machines. And I figure worst case scenario someone one-off's "What's the cog for?" and then we explain it and move on.

 As an Alternative I can adjust it's color so it doesn't look as much like the UI element cog. Or I can do a wrench if the aesthetic would be preferred to the server staff. Here's the wrench and a rustish color applied as a combo for an example.

![image](https://user-images.githubusercontent.com/84706993/159103004-67d07528-e7fc-4ea6-974e-4344c748eb3b.png)

2022-04-07 02:57 UTC, GoldenAlpharex commented
This sounds cool, you should've told me earlier, I just forgot about this.

2022-04-07 03:03 UTC, GoldenAlpharex requested changes
Ping me on Discord when you've addressed these things, we can get this merged, and then potentially look to see if we can't move that upstream at some point, if we think they'd need it.

2022-04-07 03:03 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/CrewConsole.js
> +        }
Here, this is how to do comments in HTML.
```suggestion
       <!-- SKYRAT EDIT START - Displaying robotic species Icon -->
      <Table.Cell collapsing textAlign="center">
        {is_robot ? <Icon name="wrench" color="#B7410E" size={1} /> : ""}
      </Table.Cell>
      <!-- SKYRAT EDIT END -->
```

2022-04-07 03:03 UTC, GoldenAlpharex commented on code/game/machinery/computer/crew.dm
> +		"is_robot", //SKYRAT EDIT ADD
For these comments, please add the full `SKYRAT EDIT ADDITION - Displaying robotic species Icon`, so we know why it was added. I'm not going to copy-paste this comment, but I'm sure you know what I mean by this.

2022-04-08 22:27 UTC, Gandalf2k15 approved these changes

2022-04-08 22:27 UTC, merged

2022-08-13 12:38 UTC, warface1234455 commented
lovely