[Modular] Adds a few missing families items to the loadout, adds croptop turtlenecks to the clothesmate
Skyrat-SS13/Skyrat-TG pull request #12187
Opened 2022-03-20 07:13 UTC by Ebin-Halcyon

## About The Pull Request

I was yelled at to do this.

Adds missing families gear to the loadout since it wasn't there for some reason, the WW3 reenactment gear, Yuri, Allies, and Soviet coats.

Also adds the croptop turtleneck to the autodrobe cause I forgot to put it there before. :]

## How This Contributes To The Skyrat Roleplay Experience

Stuff is way. Families isn't ran and people wanted it in the loadout menu.

## Changelog

:cl:
add: Families WW3 reenactment gear have been added to the loadout. (Yuri, Allies, and Soviet)
add: Crop top turtlenecks have been supplied to clothesmates as well.
/:cl:

2022-03-20 07:17 UTC, Zonespace27 requested changes

2022-03-20 07:17 UTC, Zonespace27 commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_suit.dm
> +	name = "Black crop top turtleneck"
capitalize this

2022-03-20 16:36 UTC, Zonespace27 commented on modular_skyrat/modules/modular_vending/code/clothesmate.dm
> +
```suggestion
```

2022-03-20 16:36 UTC, Zonespace27 approved these changes

2022-03-23 21:44 UTC, hugmeorelse commented
How about fixing Families. 🗡️

2022-03-28 16:36 UTC, GoldenAlpharex approved these changes

2022-03-28 16:37 UTC, merged