Reverts #9625
Skyrat-SS13/Skyrat-TG pull request #12185
Opened 2022-03-19 22:30 UTC by Zonespace27

## About The Pull Request
Now any job can work for the overflow job station trait, instead of just a few.

## How This Contributes To The Skyrat Roleplay Experience
![image](https://user-images.githubusercontent.com/41448081/159140537-5109ff1c-3f52-4c7d-bc94-94b8623b53f0.png)

On a slightly more serious note, I feel that it'll make some rounds feel less... samey by allowing for funny job situations to happen occasionally.

## Changelog

:cl:
expansion: Overflow Job Bureaucracy station trait can now choose any job,
/:cl:

2022-03-19 22:31 UTC, Blockzzy commented
the fucking RD council returns

2022-03-19 22:41 UTC, hugmeorelse commented
I am not so sure about this.

2022-03-21 15:29 UTC, thebestcodertoevercode commented
> I am not so sure about this.

Of course you aren't. Merge it, it's a good change.

2022-03-21 16:05 UTC, Iamgoofball commented
@hugmeorelse think about it, there's always a chance it rolls security officer

2022-03-22 23:07 UTC, hugmeorelse commented
> > I am not so sure about this.
> 
> Of course you aren't. Merge it, it's a good change.

Okay, burner account.

2022-03-23 03:30 UTC, Iamgoofball commented
the fun question of "who's burner was that"

2022-03-23 17:25 UTC, Zergspower commented
@zonespace27 concern was brought up relating to this rolling on lowpop when HOP/captain aren't on and removing all slots available to join. Yesterday it rolled and locked all positions from being joinable and the station crew did not know or understand as such, can we tweak this to affect a % of the roles and prevent an all or nothing approach?

2022-03-23 21:43 UTC, Iamgoofball commented
@Zergspower That's not what this trait does, you're referring to the Bureaucratic Error *event* which locks job slots.

This just sets the overflow role.

2022-03-23 21:48 UTC, hugmeorelse commented
How about a limited version of this for command staff where it allows for three instead of infinite?

2022-03-28 16:36 UTC, GoldenAlpharex requested changes

2022-03-28 16:36 UTC, GoldenAlpharex commented on code/datums/station_traits/negative_traits.dm
> +	//SKYRAT EDIT END
I'm still not too fond of the idea of unlimited heads of staff (or Security, or in general most non-service roles or the roles that aren't the department's most basic role), that kind of stuff usually devolves in mostly LRP stuff, due to a large amount of people joining in "for the meme", including people that A) wouldn't normally be in this position as that character (making it awkward ICly, I guess it matters less because it's a bureaucratic error) and B) don't always have sufficient experience in that role, so they'll just act like assistants with a lot of access, or even worse, they'll make the round worse for others around themselves, and C) that makes it so those that want to play those roles seriously, generally don't have the chance to during those rounds, because they'll have to share their workspace with dozens more people.

Also, I don't remember, does this station trait disable the overflow for assistants? Because if so, we might just want to have both assistants and that role as overflow, just so people aren't forced to join as Security if they don't know jack shit about it, that's just a way to speedrun tickets.

2022-06-13 22:21 UTC, GoldenAlpharex commented
My take on this still hasn't really changed.

2022-06-19 21:52 UTC, Gandalf2k15 commented
given how rarely this will happen, and how vet crew is restricted from it, it should be fine now. I miss seeing 100 captains.

2022-06-19 21:52 UTC, merged