[MODULAR][QoL] Removes empty Hypovials from standard Hypospray Kits
Skyrat-SS13/Skyrat-TG pull request #12205
Opened 2022-03-21 07:22 UTC by softcerv

## About The Pull Request
Removes the empty vials that come standard with the standard hypospray kits, including the one inserted into the hypospray.

## How This Contributes To The Skyrat Roleplay Experience
Since Hypovials are printable from the chem-master now, having empty hypovials within the kit introduces unnecessary tedium and things to discard. 

## Changelog

:cl:
qol: removes empty Hypovials from Hypospray Kits
/:cl:

2022-03-22 00:44 UTC, lessthnthree commented
So instead to fill from plumbing factories we'll then carry bottles to the chemmaster, to turn into vials, adding tedium.

2022-03-22 04:20 UTC, softcerv commented
> So instead to fill from plumbing factories we'll then carry bottles to the chemmaster, to turn into vials, adding tedium.

Most people end up discarding the empty hypovials on the floor because they use the chem-master to make new ones when making their mixes. From what I have seen, it is very rare that the included empty hypovials actually get used.

2022-03-22 11:59 UTC, Proximitron commented
As someone who plays medical often:
I usually take the hypospray out, take the empty vial out of the hypospray and discard the hypospray kit altogehter, putting the hypospray in my belt.
Others i know keep the kit but discard all the empty vials. The reason for this is very simple: The empty vials are not labelt, while the ones from the chemmaster are labled automaticly on production. As the empty vials are insufficient for every medicin you need anyway, there is really no need for them.

2022-03-24 02:34 UTC, GoldenAlpharex requested changes
Aside from the required documentation, I'd say this is a good change.

2022-03-24 02:34 UTC, GoldenAlpharex commented on modular_skyrat/modules/hyposprays/code/hyposprays_II.dm
> +	var/spawnwithvial = FALSE
If you could document those variables while you're there, that'd be great.

2022-03-24 03:00 UTC, GoldenAlpharex approved these changes
Now that's what I'm talking about!

2022-03-24 03:00 UTC, merged