[SEMI-MODULAR] Somewhat refactors the way records are handled, adds a traitor panel + OPFOR override for exploitables to allow non-antags to use them. Also adds some text to exploitables to let people know to not put sex shit in there.
Skyrat-SS13/Skyrat-TG pull request #12277
Opened 2022-03-25 20:50 UTC by nikothedude

## About The Pull Request

Heavily cleans up the code I made when I reimplemented records, and does what it says on the tin. 

## How This Contributes To The Skyrat Roleplay Experience

Better backend good, more exploitables good. Exploitables were never intended to be used f or non-con preferences and avenues, and antagonists never do that shit to begin with. More than that, the placeholder text explains how exploitables work, so people can better use them.

## Changelog

:cl:
add: Added an OPFOR service for exploitables access.
refactor: Refactored record code somewhat, should be less broken
admin: Adds a traitor panel button for toggling a exploitables override.
/:cl:

2022-03-25 22:25 UTC, Zonespace27 requested changes

2022-03-25 22:25 UTC, Zonespace27 commented on code/datums/mind.dm
> +				log_admin("[key_name(usr)] toggled [current]'s exploitables override to [has_exploitables_override].")
Use terneries to make it say on/off instead of raw number output

2022-03-25 22:25 UTC, Zonespace27 commented on code/datums/mind.dm
> +				message_admins("[key_name(usr)] toggled [current]'s exploitables override to [has_exploitables_override].")
Ditto

2022-03-25 22:25 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/examine.dm
> +		if (target_records && ((length(exploitable_text) >= 2) && ((exploitable_text) != EXPLOITABLE_DEFAULT_TEXT)))
Why 2?

2022-03-25 22:25 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/examine.dm
> +	if (src.mind.can_see_exploitables)
```suggestion
	if (mind.can_see_exploitables)
```

2022-03-25 22:25 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human.dm
> +		if (src.mind.can_see_exploitables)
```suggestion
		if (mind.can_see_exploitables)
```

2022-03-25 22:25 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human.dm
> +			var/datum/data/record/EXP = find_record("name", perpname, GLOB.data_core.general)
A better var name would be appreciated

2022-03-25 22:25 UTC, Zonespace27 commented on modular_skyrat/modules/records_on_examine/code/records_procs.dm
> +		if (antag_datum.view_exploitables)
Early continue

2022-03-25 22:25 UTC, Zonespace27 commented on modular_skyrat/modules/records_on_examine/code/record_variables.dm
> +/datum/mind/
```suggestion
/datum/mind
```

2022-03-25 22:25 UTC, Zonespace27 commented on modular_skyrat/modules/records_on_examine/code/record_variables.dm
> +	var/can_see_exploitables = FALSE
Code doc

2022-03-25 22:25 UTC, Zonespace27 commented on modular_skyrat/modules/records_on_examine/code/record_variables.dm
> +	var/has_exploitables_override = FALSE
Code doc

2022-03-26 02:42 UTC, nikothedude commented on code/modules/mob/living/carbon/human/examine.dm
> +		if (target_records && ((length(exploitable_text) >= 2) && ((exploitable_text) != EXPLOITABLE_DEFAULT_TEXT)))
Was just an arbitrary number I used.

2022-03-26 02:49 UTC, nikothedude commented
There's a problem with the implementation, mainly, I can't use ADD_VERB on a mind, only client and mob, and either of those are imperfect. So the way this is set up, if a mind swaps bodies with the verb, it needs the override switched on and off (or vice versa) to regain the verb. Anyone entering the body of a antag will see the verb, but not be able to use it, etc.

2022-03-26 02:49 UTC, nikothedude commented
However, I can't think of a way to fix this without spaghetti code, so I'll call it ready.

2022-04-02 22:05 UTC, nikothedude commented
Ignore the CI failure, I got the infamous "random for no fucking reason mice harddel" stuff.

2022-04-10 17:04 UTC, GoldenAlpharex requested changes

2022-04-10 17:04 UTC, GoldenAlpharex commented on code/datums/mind.dm
> +			if("toggleexploitables")
```suggestion
			if("toggle_exploitables")
```

2022-04-10 17:04 UTC, GoldenAlpharex commented on code/modules/admin/antag_panel.dm
> +	common_commands += "<a href='?src=[REF(src)];common=toggleexploitables'>Toggle exploitables override</a>" //SKYRAT EDIT ADDITION -- EXPLOITABLES
```suggestion
	common_commands += "<a href='?src=[REF(src)];common=toggle_exploitables'>Toggle exploitables override</a>" //SKYRAT EDIT ADDITION -- EXPLOITABLES
```

2022-04-10 17:04 UTC, GoldenAlpharex commented on modular_skyrat/modules/records_on_examine/code/records_procs.dm
> +		to_chat(current, span_danger("You now have access to the View-Crew-Exploitables verb, which shows all crew who currently have exploitable info and a link to view it!"))
It could also be a define, tbh.
```suggestion
	var/exploitable_obtention_message = span_danger("You now have access to the View Crew Exploitables verb, which shows all crew who currently have exploitable info and a link to view it!")

	if (has_exploitables_override)
		if (!has_exploitable_menu)
			add_verb(current, /mob/proc/view_exploitables_verb)
			has_exploitable_menu = TRUE
			to_chat(current, exploitable_obtention_message)
		return

	if(!has_exploitable_menu && can_see_exploitables)
		add_verb(current, /mob/proc/view_exploitables_verb)
		has_exploitable_menu = TRUE
		to_chat(current, exploitable_obtention_message)
```

2022-04-11 01:32 UTC, merged

2022-04-11 12:30 UTC, nikothedude commented
in memorium :pensive: