donator item switch
Skyrat-SS13/Skyrat-TG pull request #12440
Opened 2022-03-31 22:56 UTC by CandleJaxx

sheyehs

2022-03-31 23:19 UTC, CandleJaxx commented
github is fucking drunk lmao

2022-03-31 23:47 UTC, CandleJaxx commented
I HATE GITHUB I HATE GITHUB I HATE GITHUB

2022-04-01 02:05 UTC, GoldenAlpharex requested changes

2022-04-01 02:05 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
> +/datum/loadout_item/shoes/funksheels
```suggestion
/datum/loadout_item/shoes/funks_heels
```

2022-04-01 05:43 UTC, YakumoChen commented
if this isn't an april fools joke I'm not sure if it would be mechanically fair to include a donator item that gives you a free shoes-skateboard on spawn.

2022-04-01 19:48 UTC, CandleJaxx commented
> if this isn't an april fools joke I'm not sure if it would be mechanically fair to include a donator item that gives you a free shoes-skateboard on spawn.

you can buy them from arrivals and also: you can get a skateboard in loadout

2022-04-02 05:30 UTC, YakumoChen commented
> > if this isn't an april fools joke I'm not sure if it would be mechanically fair to include a donator item that gives you a free shoes-skateboard on spawn.
> 
> you can buy them from arrivals and also: you can get a skateboard in loadout

wheely-heels are an uncommon maint loot item, they essentially work as no-slips and let you jump over tables, but can't be dropped.

2022-04-02 20:17 UTC, CandleJaxx commented
> wheely-heels are an uncommon maint loot exclusive item, they essentially work as no-slips and let you jump over tables, but can't be dropped and are shoe-slot, with no downsides.

'exclusive' and 'essentially' are doing a lot of carry work there, as people can, again, spawn in with them roundstart with skateboards. the 'can't be dropped' is irrelevant, because if you get stunned and knocked down, you're out for a solid ten seconds without any response available. also they're heelies and it's cute as fuck

2022-04-02 21:21 UTC, CandleJaxx commented
> 'exclusive' and 'essentially' are doing a lot of carry work there, as people can, again, spawn in with them roundstart with skateboards. the 'can't be dropped' is irrelevant, because if you get stunned and knocked down, you're out for a solid ten seconds without any response available. also they're heelies and it's cute as fuck

adding onto this, the code defines the wheelies as common, with the same weight as candle boxes. you can also win them from arcade machines

2022-04-03 04:45 UTC, YakumoChen commented
>adding onto this, the code defines the wheelies as common, with the same weight as candle boxes. you can also win them from arcade machines

Neither are a timely guarantee to find in a shift, and yes, they are a lot more convienent than skateboards. The heels can be toggled at will from a button instead of resisting off and picking up the skateboard, and you don't lose it if you fall down, and it doesn't take up a spot in your backpack.

It's a clear mechanical advantage granted by loadout, especially as an item exclusive to one player.

2022-04-08 23:16 UTC, Gandalf2k15 commented
This is being closed for a few reasons, if you wish to discuss them further, please contact the host.

2022-04-08 23:16 UTC, closed without merging