[MODULAR] Oppressive Force Relocation Medicell
Skyrat-SS13/Skyrat-TG pull request #12484
Opened 2022-04-01 09:33 UTC by softcerv

## About The Pull Request
Adds in the Oppressive Force Relocation Medicell, when hit with it, security personnel will be instantly safely teleported back to security. This only works within the area of Medbay to avoid any abuse.

This Medicell comes standard with all Mediguns by default so that all medical doctors have an option to remove intrusive officers from their medbay.

## How This Contributes To The Skyrat Roleplay Experience
By giving doctors an option to remove possible intrusive factors that can interrupt or end RP, medical doctors can now have more room to properly treat and RP with their patients. This also makes security seriously consider whether or not they need to be present within medbay at any given time, discouraging them from over encroaching.

## Changelog

:cl:
add: Introduces the Oppressive Force Relocation Medicell, used to safely remove obstructive officers from medbay.
/:cl:

2022-04-01 09:36 UTC, softcerv commented
I was originally going to have it also dispense a lolipop into the officers hand, but I don't want to encourage bad officers to run into medbay just for free lolipops

2022-04-01 09:44 UTC, Jezzared commented
Personally, i like the lollipops. Very passive-agressive.
This is hilarious, but can we also get one for assistants that slaps them back to the medical lobby? I find metagangs more obtrusive than security in my own experience.

2022-04-01 14:26 UTC, Zonespace27 reviewed
smh, cant evn grammer corect, smh

2022-04-01 14:26 UTC, Zonespace27 commented on modular_skyrat/modules/modular_weapons/code/medcells.dm
> +	officer.visible_message(span_notice("[officer] teleports to back to security, reestablishing a calm medbay enviorment!"))
```suggestion
	officer.visible_message(span_notice("[officer] teleports to back to security, reestablishing a calm medbay environment!"))
```

2022-04-01 14:56 UTC, softcerv commented
> smh, cant evn grammer corect, smh

mean >:(

2022-04-01 15:53 UTC, softcerv commented
> Personally, i like the lollipops. Very passive-agressive. This is hilarious, but can we also get one for assistants that slaps them back to the medical lobby? I find metagangs more obtrusive than security in my own experience.

what if we have it so they are sent to the brig with the security officers instead?

2022-04-01 22:04 UTC, GoldenAlpharex requested changes

2022-04-01 22:04 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/medcells.dm
> +			turf_list += turf_in_area
I feel like we could afford to make that static instead, for better performance, ngl
```suggestion
	var/static/list/turf_list

	if(!turf_list)
		turf_list = list()
		for(var/turf/turf_in_area in get_area_turfs(/area/security/brig))
			if(!turf_in_area.is_blocked_turf())
				turf_list += turf_in_area
```

2022-04-02 05:28 UTC, Zonespace27 commented
Once april fools passes, make this more modifiable (have the area and access be variables on the medicell) and I'd like to see this merged for adminbus purposes

2022-04-02 05:33 UTC, softcerv commented
> Once april fools passes, make this more modifiable (have the area and required access be variables on the medicell) and I'd like to see this merged for adminbus purposes

oh yeah, I was going to make this into like an actual thing, and I can have this version be an admin one.

2022-04-02 05:36 UTC, softcerv commented
With enough tweaking and work, this could be an actually incredibly useful tool for medical players. I'm going to draft this PR until I can move this into a more balanced state for regular gameplay.

2022-04-09 01:10 UTC, softcerv commented
going to close this PR so that I can make a new one once this is in a finished state

2022-04-09 01:10 UTC, closed without merging