[SEMI-MODULAR] Removes redundant genital toggles + splits up "Uses skintones" in mutiple prefs.
Skyrat-SS13/Skyrat-TG pull request #12781
Opened 2022-04-15 18:06 UTC by Ghommie

## About The Pull Request
This PR removes the genital toggle prefs and more. The choiced preferences already have None options so the toggles are really redundant. These choiced prefs have also been refactored, to reduce copyasta.

Moving on, the "uses skintones" pref has been split into "uses skin tone" and "uses skin color" options - GoldenAlpharex suggested this would have been the better course of action - for each one of those visible organs.

Because of these changes, I have had to code a cheap replica of the savefile conversion present in the non-modular preferences_savefile.dm so that the old char prefs cold be safely converted to the newer ones, smoothly and without unwanted extra bits on some players' charaters. And I say cheap because so far it's only used for char prefs and it has no MIN version define and code, but at least it's neither fly-by-night nor one-shot solution like that tgui migration thing and can be used for future savefile updates.

## How This Contributes To The Skyrat Roleplay Experience

Currently, we have a single skin tone toggle for all reproductive organs that only changes the icon states used to render these organs to ones with a slightly pinkier hue. Players still have to **manually** set the color of each one to match more or less the tone of their character's skin, and that's no good, considering most players would want their human-er characters to be of a consistent tonality, markings aside.
So, code improvements aside, this PR aims to allow these players to check a box instead of having to guess the color of the character's skin through a color selection input box.

PLEASE DO NOT TESTMERGE THIS. IT TOUCHES SAVEFILES, SO ANY ACCIDENTAL OR NOT UNTESTMERGE MAY SCREW THINGS UP. I ALREADY TESTED THE CONVERSION LOCALLY TO MAKE SURE IT WORKS FINE.

## Changelog

:cl:
refactor: Genital prefs have been refactored. As a result, redundant toggle prefs of these organs have been removed.
qol: "Uses Skin Tone" pref has been split: each visible genital now has its own "Skin Tone" and "Skin Color" pref. This means that human-er characters can now have their bits of roughly the same color of their skin without having to guess it through the color input.
/:cl:

2022-04-15 19:57 UTC, GoldenAlpharex requested changes
I'll have to test this on my test server just to be sure that everything works properly.

That being said, are the color options disabled when "Uses Skincolor" is checked? (could be a nice UX feature if they were)

2022-04-15 19:57 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/client/preferences_savefile.dm
> +	return -1
Shouldn't there be a define for the `-1` here? Like, I don't exactly know what it stands for, looking at it quickly.

Documenting the new proc you're adding would also be greatly appreciated.
```suggestion
/datum/preferences/proc/savefile_needs_update_skyrat(savefile/save)
	var/savefile_version
	READ_FILE(save["modular_version"], savefile_version)

	if(savefile_version < MODULAR_SAVEFILE_VERSION_MAX)
		return savefile_version
	return -1
```

2022-04-15 19:57 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/client/preferences_savefile.dm
>  /datum/preferences/proc/load_character_skyrat(savefile/S)
Since you're here, yeet that single-letter variable into oblivion and give it a better name.

2022-04-15 19:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/genitals.dm
> +		return skintone2hex(H.skin_tone)
Use a better variable name than `H`.

2022-04-15 19:57 UTC, GoldenAlpharex commented on code/__HELPERS/~skyrat_helpers/unsorted.dm
> +	return accessory?.factual
What's a "factual" `sprite_accessory`?

2022-04-15 20:01 UTC, Ghommie commented on code/__HELPERS/~skyrat_helpers/unsorted.dm
> +	return accessory?.factual
https://github.com/Skyrat-SS13/Skyrat-tg/blob/bf4a8e1f4ec68e72b38d308025c5731fec517468/modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm#L21

2022-04-15 20:02 UTC, GoldenAlpharex commented on code/__HELPERS/~skyrat_helpers/unsorted.dm
> +	return accessory?.factual
:+1:

2022-04-15 20:18 UTC, Ghommie commented
> are the color options disabled when "Uses Skincolor" is checked? (could be a nice UX feature if they were)

Not yet, but I can do that.

2022-04-19 18:59 UTC, Gandalf2k15 approved these changes

2022-04-26 01:03 UTC, merged