Ghost role appearance change restriction
Skyrat-SS13/Skyrat-TG pull request #12956
Opened 2022-04-21 11:53 UTC by tf-4

## About The Pull Request

Disables selecting your custom character when spawning into a ghost role by default. Enables it on ghost roles that should have it.

## Changelog
:cl:
fix: You can no longer turn into your selected character when spawning as a ghost role that it doesn't make sense for.
/:cl:

2022-04-21 13:38 UTC, SarmentiCampbell commented
HECU and scientists too, The randomized character is legit horrid, i do not want to have a gorilla scream with a felinid laugh

2022-04-22 14:21 UTC, Gandalf2k15 requested changes
Enable HECU and black mesa roles though

2022-04-23 01:21 UTC, YakumoChen commented
HECU and Scientists should be random, they should be pure human with no mutant parts. Same goes for Enclave.

2022-04-23 13:59 UTC, Gandalf2k15 commented
> HECU and Scientists should be random, they should be pure human with no mutant parts. Same goes for Enclave.

They are already species restricted.

2022-04-23 17:49 UTC, YakumoChen commented
> > HECU and Scientists should be random, they should be pure human with no mutant parts. Same goes for Enclave.
> 
> They are already species restricted.

Does that prevent you from using mismatch parts?

2022-04-23 21:06 UTC, Gandalf2k15 commented
> > > HECU and Scientists should be random, they should be pure human with no mutant parts. Same goes for Enclave.
> > 
> > 
> > They are already species restricted.
> 
> Does that prevent you from using mismatch parts?

no but it sure as hell helps to prevent it

2022-04-23 21:06 UTC, merged