[NON MODULAR] Comments out the gas experiments
Skyrat-SS13/Skyrat-TG pull request #13173
Opened 2022-04-27 19:06 UTC by RatFromTheJungle

## About The Pull Request

Comments out the gas experiment requirement, with as little edits to the files as possible, namely, because after sitting on it for a good long while, I don't really think there's been a benefit from it at all, besides barring previously available non-issue causing content.

## How This Contributes To The Skyrat Roleplay Experience

what it says on the tin.

## Changelog

:cl:

del: Commented out (removed) gas experiment requirements

/:cl:

2022-04-27 19:50 UTC, Ghilker commented
goddamn this is both lame and he worst way to deal with this

2022-04-28 06:51 UTC, YakumoChen commented
just make them discounts

2022-04-28 11:39 UTC, ArdentSpark commented
if the experiments are 'too hard' then hyper-nob and nitrium can be swapped between T4 lasers and the implant tech node
because hyper-nob is way easier to make with T4 lasers, and nitrium can be made trivially by just, combining the superheated tritium you harvest from the ordnance chamber (which is a very very basic requirement of ordnance techs anyway) with nitrogen and BZ (nitrogen is in gas storage, BZ is in xenobiology)

2022-04-30 19:43 UTC, GoldenAlpharex requested changes
I think I'd prefer you bumping the prices of those techweb nodes by a certain amount and making those experiments provide a discount instead of just flat-out removing them.

2022-05-11 22:10 UTC, YakumoChen commented
PR about to be made redundant https://github.com/tgstation/tgstation/pull/66738

2022-05-24 17:07 UTC, Gandalf2k15 commented
https://github.com/tgstation/tgstation/pull/66738

2022-05-24 17:07 UTC, closed without merging