Adds suspenders to autodrobe.
Skyrat-SS13/Skyrat-TG pull request #13199
Opened 2022-04-28 18:23 UTC by SapphoQueer

## About The Pull Request
Simple as the title says, the rest of the outfit the mime starts with is all in the autodrobe before this PR, except suspenders, this adds them.

## How This Contributes To The Skyrat Roleplay Experience
Well, I suppose this brings people the _Full immersive mime experience_ if they decide to dress up as one, or lets a roundstart mime replace suspenders if they get lost.

## Changelog

:cl:
add: Adds suspenders to the autodrobe.
/:cl:

2022-04-28 23:02 UTC, Zonespace27 commented on code/modules/vending/autodrobe.dm
> +		/obj/item/clothing/suit/toggle/suspenders = 1,
Modularize this by putting it in the autodrobe's `skyrat_products` list in the modular_skyrat folder wherever that is defined

2022-04-28 23:02 UTC, Zonespace27 requested changes
above

2022-04-29 02:28 UTC, YakumoChen commented
I think those come in the standard costume crate, available from cargo. Maybe we should keep incentive to order the crate?

2022-04-30 18:30 UTC, theselfish commented
> I think those come in the standard costume crate, available from cargo. Maybe we should keep incentive to order the crate? For stuff other than just the clown costume, at least.

They do. But honestly?
Not only can you get suspenders in the loadout menu, not many people would be buying them.
If you get a clown crate, you get it for the clown stuff, or the mime mask.

2022-04-30 21:06 UTC, closed without merging