Makes prefs apply correctly again
Skyrat-SS13/Skyrat-TG pull request #13277
Opened 2022-05-02 18:29 UTC by ZephyrTFA

Hey, the is_accessible proc checks a lot of things, most notably it checks that the character select menu is open and on the correct page. This little if statement here makes it so half, or all if the menu isn't open, don't even apply to you. You need to actually test your shit.

2022-05-02 22:24 UTC, Gandalf2k15 requested changes
This will likely cause a lot of unintended behavior because of how is_accessible is incorrectly used. An example: You have taur body unchecked, but within, you have it set up, is_accessible is used to determine if mismatched parts are used.

2022-05-03 12:15 UTC, Gandalf2k15 commented
So refactor the way its used, add a new function to is accessible. This is not the way to do it

2022-05-03 12:59 UTC, ZephyrTFA commented
> So refactor the way its used, add a new function to is accessible. This is not the way to do it

Your bad modular code is outside the scope of my patience

2022-05-03 12:59 UTC, closed without merging

2022-05-03 13:20 UTC, Gandalf2k15 commented
> > So refactor the way its used, add a new function to is accessible. This is not the way to do it
> 
> Your bad modular code is outside the scope of my patience

It's not my code.