[MODULAR] End Title Credits Refactor / Port from Baystation
Skyrat-SS13/Skyrat-TG pull request #13308
Opened 2022-05-04 09:29 UTC by nevimer

## About The Pull Request

Finishes the end title credits sequence code that already existed in TGstation's repo by replacing it with the Baystation12 version. Rewrites a bit of it for TG compatibility. 

## Antag Objectives & Multiple antag datums
https://user-images.githubusercontent.com/77420409/166655774-a5f1e3a6-54c2-47e7-8d42-7cb82ac78e24.mp4

## Multiple Crew Demo

https://user-images.githubusercontent.com/77420409/166655843-8c6480c6-c5fc-4392-800b-821ca3cbc184.mp4

## How This Contributes To The Skyrat Roleplay Experience

Nifty flavour for the end of the round! 

## Changelog

:cl:
refactor: Replaces the broken TG version of the end credits with Baystation12's, modularly.
/:cl:

2022-05-04 20:54 UTC, theselfish commented
Is the intent of the music to hurt people's ears?

Why not take the (far better, and ear friendly) music from /vg/station?

2022-05-04 20:58 UTC, nevimer commented
> 



> Is the intent of the music to hurt people's ears?
> 
> Why not take the (far better, and ear friendly) music from /vg/station?

do you only troll the repository? The music is from baystation as an example from where its ported. Besides, theres already round end music that plays thats for some reason paired with lobby music preference.  

Most of SS13's music is all tracker stuff. Sorry you don't like it.

2022-05-04 22:18 UTC, Zonespace27 requested changes
Initial review, will do another later once this is done

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +#define CREDIT_EASE_DURATION 22
line breaks between the defines and the global vars, please

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	for(var/client/C)
no one-letter vars

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +/datum/controller/subsystem/ticker/show_roundend_report(client/C, report_type = null)
ditto

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +/* 	if(mob)
comment code bad.

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	var/list/_credits = credits
avoid having vars that are just another var name but with an underscore

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	for(var/I in GLOB.end_titles)
One letter vars bad

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +		var/atom/movable/screen/credit/T = new(null, I, src)
ditto

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +//	mob.clear_fullscreen("meeting")
bad

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +/client/proc/ClearCredits()
snake case, not camel case

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +/client/proc/RollCredits()
snake not camel case

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	var/matrix/M = matrix(transform)
no one letter vars

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +/atom/movable/screen/credit/Initialize(mapload, credited, client/P)
ditto

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	spawn(CREDIT_ROLL_SPEED - CREDIT_EASE_DURATION)
use the `addtimer(CALLBACK()` proc combo instead of `spawn`

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	var/client/P = parent
`parent` is already a typecasted var on `/screen/credit`, also no one-letter vars

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +		if(!cast.len && !chunksize)
use length() over len

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	if(chunk.len)
length over len

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	for(var/mob/living/carbon/human/H in GLOB.dead_mob_list)
mo one letter vars

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	if(corpses.len)
length over len

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	for(var/client/C)
no one letter vars, also pretty sure there's a proc to do this already

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	var/list/static/staffjobs = list("Coffe Fetcher", "Cameraman", "Angry Yeller", "Chair Operator", "Choreographer", "Historical Consultant", "Costume Designer", "Chief Editor", "Executive Assistant")
```suggestion
	var/list/static/staffjobs = list("Coffee Fetcher", "Cameraman", "Angry Yeller", "Chair Operator", "Choreographer", "Historical Consultant", "Costume Designer", "Chief Editor", "Executive Assistant")
```

2022-05-04 22:18 UTC, Zonespace27 commented on modular_skyrat/modules/credits/end.dm
> +	if(goodboys.len)
length over len

2022-05-05 15:35 UTC, ORCACommander commented
err what is wrong with the end credits referencing the normal title card music config directory?

2022-05-05 15:46 UTC, nevimer commented
> err what is wrong with the end credits referencing the normal title card music config directory?

When I ported this, I didn't realize we had anything at all cause I couldn't find it in the repo and I never heard music at round end as it's tied to an irrelevant preference.

2022-05-05 17:34 UTC, ORCACommander commented
currently round end pulls music and a bark from \config\title_music and config\reboot_themes
these folders are left blank repo side for copyright compliance and are filled with files server side. there are fail safe audio files in the event these directories are empty that are properly licensed that are embedded deep in the repot somewhere

2022-05-05 19:27 UTC, theselfish commented
> > 
> 
> > Is the intent of the music to hurt people's ears?
> > Why not take the (far better, and ear friendly) music from /vg/station?
> 
> do you only troll the repository? The music is from baystation as an example from where its ported. Besides, theres already round end music that plays thats for some reason paired with lobby music preference.
> 
> Most of SS13's music is all tracker stuff. Sorry you don't like it.

Just because I comment on your prs doesn't mean I'm 'a troll'.
I'm sorry that you view me expressing my concern over ear blaring as a joke.

2022-05-05 19:32 UTC, nevimer commented
> 



> > > 
> > 
> > 
> > > Is the intent of the music to hurt people's ears?
> > > Why not take the (far better, and ear friendly) music from /vg/station?
> > 
> > 
> > do you only troll the repository? The music is from baystation as an example from where its ported. Besides, theres already round end music that plays thats for some reason paired with lobby music preference.
> > Most of SS13's music is all tracker stuff. Sorry you don't like it.
> 
> Just because I comment on your prs doesn't mean I'm 'a troll'. I'm sorry that you view me expressing my concern over ear blaring as a joke.

If you actually played this game in with default preferences - on any server - you get your ears blasted with music anyways. Why don't you complain about hearing the same two tracks over and over again here? Your comment has no point - it's about an example track that was included and you only seek to lambast me over a song I like with no actual feedback to what is occuring in the PR. The music isn't relevant to the pull request since it doesn't cover the actual end-round music you will hear.

2022-05-05 23:46 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +	for(var/thing in GLOB.clients)
more descriptive var

2022-05-05 23:46 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +	for(var/thing in GLOB.clients)
instead of var/thing, do var/client/selected_client or something along those lines

2022-05-05 23:48 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +	var/matrix/target
documentation

2022-05-05 23:50 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +		if(H.timeofdeath < 5 MINUTES) //no prespawned corpses
are we sure this will do what the comment says? is it not possible it will filter out REALLY early on deaths?

2022-05-05 23:51 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +			staff += "[uppertext(pick(staffjobs))] a.k.a. '[C.key]'"
no ckeys (or keys).

2022-05-05 23:52 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +/datum/controller/subsystem/ticker/declare_completion()
line breaks here

2022-05-06 15:16 UTC, nevimer commented on modular_skyrat/modules/credits/end.dm
> +			staff += "[uppertext(pick(staffjobs))] a.k.a. '[C.key]'"
it's just adminwho

2022-05-06 18:08 UTC, Fikou commented
pr it upstream?

2022-05-06 19:49 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +		if(C.holder)
this feels like repeat code.

2022-05-06 19:51 UTC, jjpark-kb commented on modular_skyrat/modules/credits/end.dm
> +			staff += "[uppertext(pick(staffjobs))] a.k.a. '[C.key]'"
if that is the case, fine.

2022-05-07 21:33 UTC, Tastyfish commented
It would be cute if ghost roles were listed as unnamed extras or something but not critical

2022-05-11 01:21 UTC, Gandalf2k15 commented
This would suit upstream, looks great, you did well with the other PR, so let's try this too.

2022-05-23 22:20 UTC, nevimer commented
> This would suit upstream, looks great, you did well with the other PR, so let's try this too.

I don't think this will really work upstream due to some quirks

2022-05-24 17:47 UTC, tf-4 commented
> > This would suit upstream, looks great, you did well with the other PR, so let's try this too.
> 
> I don't think this will really work upstream due to some quirks

what quirks?

2022-05-24 17:54 UTC, nevimer commented
> > > This would suit upstream, looks great, you did well with the other PR, so let's try this too.
> > 
> > 
> > I don't think this will really work upstream due to some quirks
> 
> what quirks?

So basically, I don't trust my code enough to have it go to TG untested here - I won't see results on TG cause I don't play on TG. When I directly copy and pasted what I did here into TG, it came out a buggy mess. On here, I can at least see the feedback and the issues with it. I'd like it testmerged TBH so I can pound out the issues if and when

2022-06-07 00:25 UTC, closed without merging

2022-06-07 00:25 UTC, nevimer commented
yea maybe when I care enough I'll finish this but it won't work upstream like it will here