Adds manifest to borg integrated tablets
Skyrat-SS13/Skyrat-TG pull request #13427
Opened 2022-05-08 13:31 UTC by tf-4

## About The Pull Request

Missed it in https://github.com/Skyrat-SS13/Skyrat-tg/pull/12943

## Changelog
:cl:
fix: Cyborgs once again have access to the crew manifest.
/:cl:

2022-05-16 00:52 UTC, tf-4 commented
its not even my fault it failed CI!!!!!

2022-05-19 23:42 UTC, GoldenAlpharex requested changes

2022-05-19 23:42 UTC, GoldenAlpharex commented on code/modules/modular_computers/hardware/hard_drive.dm
> +	store_file(new /datum/computer_file/program/crew_manifest(src)) // SKYRAT EDIT ADD
```suggestion
	store_file(new /datum/computer_file/program/crew_manifest(src)) // SKYRAT EDIT ADDITION - Manifests for cyborgs
```

2022-05-22 19:13 UTC, GoldenAlpharex approved these changes
I could've sworn I approved this already.

2022-05-22 19:13 UTC, merged