Partial fix for changeling transformations
Skyrat-SS13/Skyrat-TG pull request #13527
Opened 2022-05-11 02:31 UTC by Christmas5

## About The Pull Request

One of the issues with changeling transformations was that mutant_bodyparts and body_markings in /datums/dna did not update at all. This PR should resolve that by adding these two lines to /proc/transform in changeling.dm:
> 	user.dna.mutant_bodyparts = chosen_dna.mutant_bodyparts.Copy()
> 	user.dna.body_markings = chosen_dna.body_markings.Copy()

Additionally, this PR adds underwear colors and eye emissives to the changeling profiles, allowing these to get copied over on a transformation, thus making the disguise more accurate and/or harder to see through.

This does **not** fix the issue where changelings have to use the ability twice in order for the transformation to complete.
It also does **not** fix the issue of digitigrade legs getting mixed with plantigrade clothing.

## Changelog

:cl:
fix: mutant_bodyparts and body_markings now update on a transformation.
code: Adds underwear_color, undershirt_color, socks_color and emissive_eyes to changeling profiles.
/:cl:

2022-05-12 04:49 UTC, Zonespace27 requested changes
Multi-line modularization comments work like
```
//SKYRAT EDIT START
code
more code
//SKYRAT EDIT END

2022-05-12 13:38 UTC, Christmas5 commented
> Multi-line modularization comments work like
> 
> ```
> //SKYRAT EDIT START
> code
> more code
> //SKYRAT EDIT END
> ```

My bad, I think it looks alright now?

2022-05-13 23:25 UTC, Christmas5 reviewed
Fixed(?)

2022-05-21 13:44 UTC, Zonespace27 requested changes

2022-05-21 13:44 UTC, Zonespace27 commented on code/modules/antagonists/changeling/changeling.dm
> +	//var/list/slots = list("head", "wear_mask", "back", "wear_suit", "w_uniform", "shoes", "belt", "gloves", "glasses", "ears", "wear_id", "s_store")
remove commented code

2022-05-21 13:44 UTC, Zonespace27 commented on code/modules/antagonists/changeling/changeling.dm
> +		//"neck" = ITEM_SLOT_NECK,
ditto

2022-05-21 13:44 UTC, Zonespace27 commented on code/modules/antagonists/changeling/changeling.dm
> +	//user.updateappearance(mutcolor_update = TRUE)
ditto

2022-05-21 13:44 UTC, Zonespace27 commented on code/modules/antagonists/changeling/powers/humanform.dm
> +	//var/newmob = user.humanize()
ditto

2022-05-21 13:44 UTC, Zonespace27 commented on code/modules/antagonists/changeling/powers/lesserform.dm
> +	for(var/i in user.all_scars)
no one letter vars

2022-05-21 13:44 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/hostile/headcrab.dm
> +		//changeling_datum.purchased_powers += hf
remove commented code

2022-05-23 16:05 UTC, merged