[MODULAR] Adds the suppressor to NT armories.
Skyrat-SS13/Skyrat-TG pull request #13572
Opened 2022-05-12 23:32 UTC by RatFromTheJungle

## About The Pull Request
Originally in Scarborough, and made non-contraband for gun cargo, just to be lost to the tides when scarborough became emag only.

## How This Contributes To The Skyrat Roleplay Experience

suppressed peacekeeper shotguns do more damage, and no one can tell me otherwise.

## Changelog

:cl:
add: NT Armories now carries suppressors, for all your indoor shooting needs.
/:cl:

2022-05-12 23:38 UTC, Zonespace27 requested changes
Make the NT suppressor a subtype with a different desc and maybe name, give that to whoever is given one in command already

2022-05-13 01:11 UTC, Zonespace27 requested changes

2022-05-13 01:11 UTC, Zonespace27 commented on modular_skyrat/modules/projectiles/code/guns/ballistic.dm
> +/obj/item/suppressor/nanotrasen
why is this defined in two different places

2022-05-13 01:11 UTC, Zonespace27 commented on modular_skyrat/modules/blueshield/code/blueshield.dm
> +	new /obj/item/suppressor/nanotrasen(src) //why the fuck does BS need a suppressed gun is beyond me
forgot to tick the code files, web edits are bad.

2022-05-13 10:39 UTC, Gandalf2k15 commented
How 👏 many 👏 commits

2022-05-13 10:39 UTC, merged