Removes veteran lock from Vanguard
Skyrat-SS13/Skyrat-TG pull request #13619
Opened 2022-05-15 00:11 UTC by Zonespace27

## About The Pull Request
Removes the requirement to be veteran crew from vanguard slots.

## How This Contributes To The Skyrat Roleplay Experience
Overall, I don't see the purpose in having Vanguard be veteran locked. It's not a job that requires a high amount of trust (aside from not going valid salad on the antags when they get back on station, but the only away mission we have is Black Mesa, which i have yet to see completed without a shift extension). In addition, when I run an away mission, vanguard being vet locked usually means it takes an hour-ish for all 4 slots to fill, which I do not like.

## Changelog

:cl:
config: Vanguard are no longer veteran-crew locked
/:cl:

2022-05-15 06:21 UTC, Stalkeros2 commented
Good.
You guys should probably enable other gateway missions too tbh.

2022-05-15 10:51 UTC, LeonY24 commented
it is very dangerous though

2022-05-15 22:47 UTC, theselfish commented
I have to agree with this.
Either we admit that Expo are just Gateway Miners, or we Vet Lock miners.

2022-05-16 00:11 UTC, softcerv commented
> it is very dangerous though

If it is a big issue for the game, we probably shouldn't have the job in the game in the first place.

2022-05-17 20:23 UTC, Zergspower commented
What's left for Vets? I think this was the last vet special role outside of NTRep and BS since Fleet was removed which was the goal for a lot of people.

2022-05-18 23:32 UTC, Zonespace27 commented
> What's left for Vets? I think this was the last vet special role outside of NTRep and BS since Fleet was removed which was the goal for a lot of people.

NTR, BS, hemophage, headshots, and a bit more i'm forgetting. The argument that vet losing out on things for the fun of the much wider server population isn't a strong one

2022-05-19 01:38 UTC, GoldenAlpharex commented
Considering the amount of issues we've had in the past with vanguards, even with the fact they were Veteran-only... I'm not so convinced this is a good idea.

***Especially*** since they've been allowed to be less balanced with the *express* reason that they were meant to be Veteran-only, because they'd be more likely to follow the rules.

2022-05-19 07:33 UTC, Zergspower commented
> > What's left for Vets? I think this was the last vet special role outside of NTRep and BS since Fleet was removed which was the goal for a lot of people.
> 
> NTR, BS, hemophage, headshots, and a bit more i'm forgetting. The argument that vet losing out on things for the fun of the much wider server population isn't a strong one

it is when we're still at a large net loss, the only added thing versus the many removed is headshots

2022-05-20 10:47 UTC, KathrinBailey requested changes
![image](https://user-images.githubusercontent.com/53862927/169508866-b7dd7fe2-bc1b-44a9-89c7-04a7ec03d856.png)

I'm unconcerned about "what's left for veteran crew".
If you can get agreement from a bunch of admins and/or above without a headmin explicitly saying no I'll merge.
Headmins with repo privileges feel free to close if you deem this to not be good.

2022-05-22 18:23 UTC, softcerv commented
> > > What's left for Vets? I think this was the last vet special role outside of NTRep and BS since Fleet was removed which was the goal for a lot of people.
> > 
> > 
> > NTR, BS, hemophage, headshots, and a bit more i'm forgetting. The argument that vet losing out on things for the fun of the much wider server population isn't a strong one
> 
> it is when we're still at a large net loss, the only added thing versus the many removed is headshots

You still have: Hemophages, Oversized, Clown, NT-Rep, Blueshield, and headshots. Veteran crew doesn't need more things added to it unless there is a good reason for that thing to be vet-crew only.

2022-05-22 20:19 UTC, Zergspower commented
> > > > What's left for Vets? I think this was the last vet special role outside of NTRep and BS since Fleet was removed which was the goal for a lot of people.
> > > 
> > > 
> > > NTR, BS, hemophage, headshots, and a bit more i'm forgetting. The argument that vet losing out on things for the fun of the much wider server population isn't a strong one
> > 
> > 
> > it is when we're still at a large net loss, the only added thing versus the many removed is headshots
> 
> You still have: Hemophages, Oversized, Clown, NT-Rep, Blueshield, and headshots. Veteran crew doesn't need more things added to it unless there is a good reason for that thing to be vet-crew only.

i'm... not saying add - we keep removing things from the role - and all of those except 1 isnt really a perk as not everyone wants to be a hemophage or oversized.

2022-05-23 11:10 UTC, Gandalf2k15 commented
Discussing this with people

2022-05-24 15:45 UTC, Gandalf2k15 commented
I think this time round we'll be keeping it veteran only, if you need to open it up, you can

2022-05-24 15:45 UTC, closed without merging