[MODULAR] A Wealth of Customization Options
Skyrat-SS13/Skyrat-TG pull request #13642
Opened 2022-05-16 00:04 UTC by Nerev4r

## About The Pull Request

**Welcome to the Thieves' Guild.** 
On a serious note, this PR introduces a loooooooooooooooooot of new ears, tails, horns, and taur options, lovingly borrowed from https://github.com/quotefox/Hyper-Station-13, https://github.com/VOREStation/VOREStation/pulls, https://github.com/Citadel-Station-13/Citadel-Station-13-RP, and https://github.com/sojourn-13/sojourn-station. I hate every single one of you for making me take these many screenshots, featuring our lovely model, Iantha Louge (no longer a snail for the purpose of this demonstration.)

**Tails (The Fox)**

![image](https://user-images.githubusercontent.com/12636964/168493714-84bdf76d-455e-4000-b1de-01c59e770758.png)
![image](https://user-images.githubusercontent.com/12636964/168493715-fcad5e4c-be49-40da-98c4-753add89a5be.png)
![image](https://user-images.githubusercontent.com/12636964/168493716-6b3a1cf4-a510-4847-83a8-2ca1eb6ad7d1.png)
Double Kitsune tail from Virgo, featuring new Sandfox ears. Tall, like the rabbit ears we had from @theOOZ. Does not function as a helicopter.

![image](https://user-images.githubusercontent.com/12636964/168493782-8dfe4c9b-09d1-4bc7-967b-08c9836be2c8.png)
![image](https://user-images.githubusercontent.com/12636964/168493784-cdd9a82a-eada-4ee2-99a4-a1f9f8698402.png)
![image](https://user-images.githubusercontent.com/12636964/168493786-5d808cbb-cc60-4cab-a032-df9cb85a8865.png)
_Triple Kitsune_ tail from _Virgo_, edits by myself to make the tips a bit sharper.

![image](https://user-images.githubusercontent.com/12636964/168493795-14a4c611-26df-4a25-9bed-8e5640888e9d.png)
![image](https://user-images.githubusercontent.com/12636964/168493799-36cd2f5d-5d35-4413-9fad-7e3edea18f58.png)
![image](https://user-images.githubusercontent.com/12636964/168493800-03b574ac-c431-443b-8146-521c33f8bea7.png)
_Septuple Kitsune_ tail from _Virgo_. Yes, I had to look up that word. Don't bully me.

![image](https://user-images.githubusercontent.com/12636964/168493899-89e9dad3-5957-4bc7-be5c-22bf4b62c254.png)
![image](https://user-images.githubusercontent.com/12636964/168493901-192a795e-a255-4b55-9512-54b5df29dfb1.png)
![image](https://user-images.githubusercontent.com/12636964/168493903-10f50673-9e4e-482f-806d-a02f4190b319.png)
![image](https://i.imgur.com/KXDPCaN.gif)
_Segmented_ tail from (I believe) _Virgo_, featuring _Stabbers_ horns from _Sojourn_. Kind of lobstery. I like it.

![image](https://user-images.githubusercontent.com/12636964/168493932-3f2cb476-a6ad-4519-8ef9-06242a713857.png)
![image](https://user-images.githubusercontent.com/12636964/168493935-7724def5-b9ae-4610-bf18-fb6c019e9c77.png)
![image](https://user-images.githubusercontent.com/12636964/168493940-bd0cfc8b-5fe0-4eb8-a30b-97a8dd237f35.png)
_Chameleon_ tail from _Virgo_, featuring our Uni horn. Try emoting catching flies with your tongue, it gets good reactions.

![image](https://user-images.githubusercontent.com/12636964/168494006-07e74ecc-3d45-4640-a028-052402c46ad2.png)
![image](https://user-images.githubusercontent.com/12636964/168494009-7c4d2e81-a833-43ec-8116-3e7f98cb5441.png)
![image](https://user-images.githubusercontent.com/12636964/168494012-ea6556c4-06e9-4fc6-84d4-dbee9a54f1b4.png)
_Shade(kin)_ tail from _Virgo_, (I believe,) featuring our Kangaroo ears. Come to think of it, why's there only ever been one kangaroo character? Seriously.

![image](https://user-images.githubusercontent.com/12636964/168494035-b62fc42a-ca94-4889-a88e-58fada956227.png)
![image](https://user-images.githubusercontent.com/12636964/168494039-c35daa0d-e94d-4dcc-8dee-48b2c9a1ce46.png)
![image](https://user-images.githubusercontent.com/12636964/168494042-bc874124-0fa5-47f2-ad1b-0233b86857eb.png)
_Long Shade(kin)_ tail from _Virgo_, (again, I believe.) This one doesn't have a colorable tip. I know.

![image](https://user-images.githubusercontent.com/12636964/168494063-182644a8-2605-4380-b12d-00603a902dc6.png)
![image](https://user-images.githubusercontent.com/12636964/168494067-57464109-a389-4235-80c1-4d45fa19f3a9.png)
![image](https://user-images.githubusercontent.com/12636964/168494070-5a6de484-5d7c-4455-a553-bb1e603cc9a4.png)
_Longer Shade(kin)_ tail from _Virgo_, (made you look.) OP is going to be using this one. With that exact coloration. You could probably make XLR8 from Ben 10 with this.

![image](https://user-images.githubusercontent.com/12636964/168494150-f0979d86-57b6-4f60-af5d-41c4eb9a4a78.png)
![image](https://user-images.githubusercontent.com/12636964/168494154-c880629f-1591-4894-b525-ffe4a338dfd2.png)
![image](https://user-images.githubusercontent.com/12636964/168494159-0c1b4239-4ee5-4382-ae73-009fb328019a.png)
_Big Lizard_ tail from _Virgo,_ featuring _Lifted Horns_ from Sojourn. I really did lift those horns from Sojourn too. Did you know this was originally coded as a taur? Anyway, the colors aren't flattering, but I'm sure someone could make this work. Maybe for a maximum-hitbox build. Or an extra thicc King K. Rool build.

**Taurs (No Minos, no Cens)**
**Disclaimer,** these're heavily reliant on taurs, uh, not being broken and hiding the legs. So, none of these're gonna look _as_ good as they could for the time being. Gomen nasai.

![image](https://user-images.githubusercontent.com/12636964/168494890-41d85a97-78fa-4edc-8872-94211b3d9061.png)
![image](https://user-images.githubusercontent.com/12636964/168494894-966aff89-4ede-4926-a3d7-88dd127bd81c.png)
![image](https://user-images.githubusercontent.com/12636964/168494896-233ddaf1-0814-42f9-a7b1-052a63a5a99e.png)
_Alt Tentacle_ taur from _Virgo._ This should look substantially better, and also does wonders for your hips. 

![image](https://user-images.githubusercontent.com/12636964/168494915-8de9e32c-785a-424c-9825-8c46edef403d.png)
![image](https://user-images.githubusercontent.com/12636964/168494916-9edbfda6-f9c6-484c-bbe4-b3087e77d700.png)
![image](https://user-images.githubusercontent.com/12636964/168494918-ad32a6b0-c10d-4188-8325-0667e3f2a022.png)
_Chinese Dragon_ taur from _Virgo._ This one's just badass. C'mon. Look at the claws. Look at that tail. Wowza. Awooga.

![image](https://user-images.githubusercontent.com/12636964/168495442-fa9812e1-5a14-479f-9cd5-e53dcdeca0f0.png)
![image](https://user-images.githubusercontent.com/12636964/168495446-8a162683-53de-4513-829b-2818cfba0402.png)
_Wasp_ taur from _Virgo._ This one seems to scare people. I like that.

![image](https://user-images.githubusercontent.com/12636964/168495687-1e078b6a-1dce-48b0-bce4-cce29e003f2f.png)
![image](https://user-images.githubusercontent.com/12636964/168495688-f87fce87-2846-4a24-9990-191cb04affe1.png)
![image](https://user-images.githubusercontent.com/12636964/168495691-c695dba5-a2c6-4d02-907a-8ff66aed11fe.png)
_Mantis_ taur (and arms) from _CitRP._ Imagine how good this would look if taurs were fixed. It looks cool, doesn't it.

![image](https://user-images.githubusercontent.com/12636964/168495778-22451b05-cc3c-4d93-a3bc-bdc93b03170a.png)
![image](https://user-images.githubusercontent.com/12636964/168495782-d30d33c3-403f-40e4-bfe0-790cfec7488d.png)
![image](https://user-images.githubusercontent.com/12636964/168495784-21359468-aa6b-419f-bb37-6d257d77195a.png)
_Slug_ taur from _Virgo._ You may be wondering why I didn't use a snailperson for this demonstration. Stop wondering.

**Wings (still can't fly lol)**
![image](https://user-images.githubusercontent.com/12636964/168495817-437cfaa1-7c89-4d30-b08c-e379d2932449.png)
![image](https://user-images.githubusercontent.com/12636964/168495819-6f064c3c-8c5d-4024-90f9-ac4bc9fef2f2.png)
![image](https://user-images.githubusercontent.com/12636964/168495822-cb1608e9-8f24-4a71-9370-131e08c899c8.png)
_Mantis_ arms from _CitRP._ Some of you already eat your mates, so this'll fit right in.

![image](https://user-images.githubusercontent.com/12636964/168495865-a036fa10-4c95-4ec2-ac18-27a423e3ec30.png)
![image](https://user-images.githubusercontent.com/12636964/168495869-823e8a33-abc8-48d3-aba0-fd40585dbb87.png)
![image](https: [...]

2022-05-16 00:14 UTC, Jolly-66 commented
You should try to use markdowns spoiler to try and condense the images a bit, which can be accomplish by the following:

```
<details>
<summary> Your Text Here </summary>
Whatever goes in here is going to be spoilered/hidden until someone clicks on it!
</details>
```
Example

<details>
<summary> Spooky spoiler ahead!</summary>
Boo!
</details>

2022-05-16 00:24 UTC, Nerev4r commented
fixed

2022-05-17 04:21 UTC, GoldenAlpharex commented
Since that's a lot of somewhat unrelated sprites, I'd ask you to split them into different PRs for each category. I don't want to just blindly merge all of this, especially considering that's a *lot* of sprites which can end up being rsc bloat if they're never used (which for some of them is quite likely).

2022-05-17 05:02 UTC, GoldenAlpharex requested changes
Also, as discussed on the Discord, I'd prefer not having the tail option that's two tails in a banana shape, if anything, it can always be added later if a change of heart occurs.

2022-05-17 14:53 UTC, Nerev4r commented
Atomized, double tails sent to the shadow realm.

2022-05-18 15:19 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +/datum/sprite_accessory/taur/mantis
```suggestion

/datum/sprite_accessory/taur/mantis
```

2022-05-18 15:20 UTC, tf-4 commented
Still has `ears_big.dmi` and `wings.dmi`, as well as the taur stuff.

2022-05-18 15:46 UTC, Nerev4r commented
ok that was wild but we're good

2022-05-19 01:47 UTC, GoldenAlpharex requested changes
I'm definitely not sold on the long tails.

The lizard tail just looks *really* wrong, I'd personally cut it from the PR, it really looks disproportionate and offputting.

2022-05-19 01:47 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
> +	icon_state = "shadekinlong2_large"
I really feel like those are confusing icon_state names, I got a feeling it could help having slightly more different names between them, no?

2022-05-19 01:47 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
> +	icon_state = "shadekinlong2_large"
```suggestion
/datum/sprite_accessory/tails/mammal/wagging/big/shade
	name = "Shade"
	icon_state = "shadekin_large"
	color_src = USE_MATRIXED_COLORS

/datum/sprite_accessory/tails/mammal/wagging/big/shade_long
	name = "Long Shade"
	icon_state = "shadekinlong_large"
	color_src = USE_MATRIXED_COLORS

/datum/sprite_accessory/tails/mammal/wagging/big/shade_longer
	name = "Longer Shade"
	icon_state = "shadekinlong2_large"
```

2022-05-19 01:47 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
> +	center = TRUE
Honestly, not sold on big tails, they feel just, like, slightly too big, compared to the others, y'know?

2022-05-19 16:53 UTC, GoldenAlpharex approved these changes

2022-05-19 16:53 UTC, merged