[MODULAR] More Wings
Skyrat-SS13/Skyrat-TG pull request #13667
Opened 2022-05-17 05:58 UTC by Nerev4r

## About The Pull Request

<details>
<summary> Wings (still can't fly lol) </summary>

![image](https://user-images.githubusercontent.com/12636964/168495817-437cfaa1-7c89-4d30-b08c-e379d2932449.png)
![image](https://user-images.githubusercontent.com/12636964/168495819-6f064c3c-8c5d-4024-90f9-ac4bc9fef2f2.png)
![image](https://user-images.githubusercontent.com/12636964/168495822-cb1608e9-8f24-4a71-9370-131e08c899c8.png)
_Mantis_ arms from _CitRP._ Some of you already eat your mates, so this'll fit right in.

![image](https://user-images.githubusercontent.com/12636964/168495865-a036fa10-4c95-4ec2-ac18-27a423e3ec30.png)
![image](https://user-images.githubusercontent.com/12636964/168495869-823e8a33-abc8-48d3-aba0-fd40585dbb87.png)
![image](https://user-images.githubusercontent.com/12636964/168495871-ce8273e9-d625-497d-a4fe-869a9f7c10bb.png)
_Alt Bee_ wings from _Virgo._ I can't believe we didn't already have this. What, were you expecting a bee joke? A quip about honey? A pun about stingers? What do you take me for?

![image](https://user-images.githubusercontent.com/12636964/168496123-eba542d3-00e7-448d-91ae-e892a3e91911.png)
![image](https://user-images.githubusercontent.com/12636964/168496126-2cae6876-e524-44fb-b98c-72e9fb29af52.png)
![image](https://user-images.githubusercontent.com/12636964/168496128-e8e21f73-ce66-4492-9cdd-7133d267e4e9.png)
_Insectoid_ wings from _Hyper._ *chitter.

![image](https://user-images.githubusercontent.com/12636964/168496151-918e0836-080a-4f80-a4d2-3a0f0211a4de.png)
![image](https://user-images.githubusercontent.com/12636964/168496153-339a17ac-a225-4a2e-9f87-fed4e989ffff.png)
![image](https://user-images.githubusercontent.com/12636964/168496155-b5f85fc0-4252-4a2a-9def-102c1dcd225f.png)
_Beetle_ wings from _Hyper._ Also *chitter.

![image](https://user-images.githubusercontent.com/12636964/168496169-1e8b74b6-095f-44c6-a825-33deb15ce373.png)
![image](https://user-images.githubusercontent.com/12636964/168496171-39fe51c0-281f-4abf-b367-d8a2c647ef10.png)
![image](https://user-images.githubusercontent.com/12636964/168496173-e252c77a-04a7-403e-9dd3-c9d13c4b6b25.png)
_Mini-Feathery_ wings from _Hyper._ These are just adorable. It's a shame they don't fit on Teshari.

![image](https://user-images.githubusercontent.com/12636964/168496191-82a82590-8d1b-4cd5-9850-76affcf9c4e4.png)
![image](https://user-images.githubusercontent.com/12636964/168496192-08d92eab-291e-42c2-8dd2-e5070bf90283.png)
![image](https://user-images.githubusercontent.com/12636964/168496193-571ab925-f7ae-4676-83b2-fe2a2faf0c45.png)
_Tiny-Feathery_ wings from _Hyper._ These are somehow even more adorable. My heart.

![image](https://user-images.githubusercontent.com/12636964/168496205-aafc7ea7-3449-4a52-9ef9-754747f1fdcb.png)
![image](https://user-images.githubusercontent.com/12636964/168496206-98aba530-3d70-41bb-b67d-81e690791952.png)
![image](https://user-images.githubusercontent.com/12636964/168496209-b4c51caa-3f4a-4110-8bb4-0e7fe0f6083f.png)
_Mini-Bat_ wings from _Hyper._ For short succubi.

![image](https://user-images.githubusercontent.com/12636964/168496241-343a165c-b6e0-45df-975e-864b314f43ce.png)
![image](https://user-images.githubusercontent.com/12636964/168496242-767b0c41-fc48-4dbf-9706-01b1f4465db4.png)
![image](https://user-images.githubusercontent.com/12636964/168496245-0844e04d-ddea-4f45-a1a7-0c31c97fed61.png)
_Tiny-Bat_ wings from _Hyper._ For those characters that only really *squeak.
</details>

## How This Contributes To The Skyrat Roleplay Experience
from the other pr or something i'm not filling this out five times.

## Changelog

:cl:
add: More wings, about eight of them.
/:cl:

2022-05-18 15:28 UTC, tf-4 approved these changes
The mantis arms look kinda strange but I assume they're not really intended for humans anyway. Code looks fine. Rest of the sprites are nice.

2022-05-19 01:18 UTC, GoldenAlpharex requested changes
I really like the last four, not sure about the alt bee one, the rest are fine, except the mantis one.

As I said in the taur PR, I'm not a big fan of adding "wings" that both don't behave like wings, and make it look as if you've got a second pair of arms, even if you don't, which is kind of misleading and... Visually incoherent, so to speak? I'm just really not convinced, honestly.

2022-05-19 01:18 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/beealt
```suggestion
/datum/sprite_accessory/wings/mammal/bee_alt
```

2022-05-19 01:18 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/minibat
```suggestion
/datum/sprite_accessory/wings/mammal/mini_bat
```

2022-05-19 01:18 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/minifeather
```suggestion
/datum/sprite_accessory/wings/mammal/mini_feather
```

2022-05-19 01:18 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/tinybat
```suggestion
/datum/sprite_accessory/wings/mammal/tiny_bat
```

2022-05-19 01:18 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/tinyfeather
```suggestion
/datum/sprite_accessory/wings/mammal/tiny_feather
```

2022-05-19 01:18 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +	color_src = USE_ONE_COLOR
You haven't shown sprite pictures of this one.

2022-05-19 02:02 UTC, GoldenAlpharex approved these changes
I really like the tiny and mini ones, they're very cute :)

2022-05-19 11:41 UTC, merged