[MODULAR] More Ears
Skyrat-SS13/Skyrat-TG pull request #13665
Opened 2022-05-17 05:49 UTC by Nerev4r

## About The Pull Request

<details>
<summary> Ears (Around Elves, Watch Yourselves) </summary>

![image](https://user-images.githubusercontent.com/12636964/168496484-371eb26a-be2f-402d-8fa5-e6671f208f9a.png)
![image](https://user-images.githubusercontent.com/12636964/168496485-ab6acb58-0cf8-4791-b21c-5921d3e45221.png)
![image](https://user-images.githubusercontent.com/12636964/168496486-5a5166e9-730f-4c38-a480-a4ec57e78b1a.png)
_Wide Elf_ ears from _Sojourn._ I don't have a quip for this.

![image](https://user-images.githubusercontent.com/12636964/168496497-cd7e3f46-1476-483b-b1ea-7d33561323d8.png)
![image](https://user-images.githubusercontent.com/12636964/168496498-cee6bcbc-0323-4b89-b3b4-2530d64ea66b.png)
![image](https://user-images.githubusercontent.com/12636964/168496499-d765c9f4-c7dc-4635-aac2-96a92fe3c484.png)
_Broad Elf_ ears from _Sojourn._ Broad elf, or elf broad?

![image](https://user-images.githubusercontent.com/12636964/168496507-1fc3d8a5-f931-45d9-bb36-281399e64cd0.png)
![image](https://user-images.githubusercontent.com/12636964/168496508-7040c58e-0dcf-4552-8cb6-2be2f2f5ce28.png)
![image](https://user-images.githubusercontent.com/12636964/168496509-5fdadd1d-c699-433c-8f57-9fc478407181.png)
_Longer Elf_ ears from _Sojourn._ They aren't actually longer on the sides. Gomen nasai.

![image](https://user-images.githubusercontent.com/12636964/168738085-16d31f63-7487-4b96-abbb-68debe068074.png)
![image](https://user-images.githubusercontent.com/12636964/168738099-c161e899-6b62-4125-a31d-c3becacf83c1.png)
![image](https://user-images.githubusercontent.com/12636964/168738114-9770bc61-c887-47bc-89c1-2b432f2dacff.png)
_Sandfox_ ears from _Virgo._ Yeah.

</details>

## How This Contributes To The Skyrat Roleplay Experience
from the other PR, i guess.

## Changelog

:cl:
add: Adds some more ears, five of them.
/:cl:

2022-05-18 15:22 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +	icon_state = "elflonger"
put these up with the base `/datum/sprite_accessory/ears/mutant/elf` ears

2022-05-18 15:38 UTC, tf-4 approved these changes

2022-05-19 00:52 UTC, GoldenAlpharex requested changes
I like these, the only thing I'd have to say is that the side view of the wide elf ones is very weird, it's as if it represented the ears as being upside down (because it's as if they were wider at the top, when you'd expect them to be wider at the bottom, following the general shape of the ear).

2022-05-19 00:53 UTC, GoldenAlpharex commented
Wait, my bad, broad elf.

2022-05-19 11:40 UTC, GoldenAlpharex approved these changes
That's better.

2022-05-19 11:41 UTC, merged