Fixes bad global used by turf emote
Skyrat-SS13/Skyrat-TG pull request #13710
Opened 2022-05-18 21:57 UTC by Tastyfish

## About The Pull Request

The turf emote was using an unmanaged global to track which turf was picked, making it entirely luck that a given user spawned the correct object if 2 people were using *turf at once.

## How This Contributes To The Skyrat Roleplay Experience

Unmanaged globals violate code standards anyway, but this shouldn't be global in any form.

## Changelog

:cl:
fix: Fixed possible edge case issues with multiple uses of turf emote at the same time.
/:cl:

2022-05-18 23:29 UTC, GoldenAlpharex requested changes

2022-05-18 23:29 UTC, GoldenAlpharex commented on modular_skyrat/modules/emotes/code/additionalemotes/turf_emote.dm
> +	var/current_turf
Just document this please!

2022-05-18 23:59 UTC, Tastyfish commented on modular_skyrat/modules/emotes/code/additionalemotes/turf_emote.dm
> +	var/current_turf
yep, done

2022-05-19 02:07 UTC, GoldenAlpharex commented on modular_skyrat/modules/emotes/code/additionalemotes/turf_emote.dm
>  	if(do_after(user,10))
```suggestion
	if(do_after(user, 1 SECONDS))
```

2022-05-19 02:07 UTC, GoldenAlpharex requested changes
Once that last little comment is done, we're good to go.

2022-05-23 10:39 UTC, merged