[NONMODULAR] [Test] Relegates Round Timer To Observers
Skyrat-SS13/Skyrat-TG pull request #13820
Opened 2022-05-23 01:32 UTC by Nerev4r

## About The Pull Request
A social experiment, if you will. A bit of a jape. Tomfoolery. Please testmerge this for about a week.
This removes the ability for people in the actual round to see how far in it is. Station time remains, as well as manual ways of checking (like your desktop clocks.) Observers and people in the lobby can still check.

## How This Contributes To The Skyrat Roleplay Experience
I noticed something during the status panel being broken. I noticed, particularly, that people seemed to be less afraid to start bigger projects/longer roleplay scenarios, and a definitive increase in continue votes. I think it'll have people act a lot better (generally) to no longer have 'it's almost two hours in' hanging over their heads like a cartoon anvil.

## Changelog

:cl:
del: Round timers are no longer viewable by the living.
/:cl:

2022-05-23 01:35 UTC, tf-4 requested changes
I thought on it a little more and I think it is useful enough to justify the effort of giving admin mobs the ability to see the round timer, in the end.

2022-05-23 01:35 UTC, tf-4 commented on code/controllers/subsystem/statpanel.dm
> +			//"Actual Round Timer: [time2text(real_round_time, "hh:mm:ss", 0)]"
just delete

2022-05-23 01:36 UTC, tf-4 commented on code/modules/mob/dead/dead.dm
> +	. += "Round Timer: [round_time > MIDNIGHT_ROLLOVER ? "[round(round_time/MIDNIGHT_ROLLOVER)]:[worldtime2text()]" : worldtime2text()]",
```suggestion
	. += "Round Timer: [round_time > MIDNIGHT_ROLLOVER ? "[round(round_time/MIDNIGHT_ROLLOVER)]:[worldtime2text()]" : worldtime2text()]"
```

2022-05-23 01:47 UTC, tf-4 approved these changes
Happy to test this.

2022-05-23 04:16 UTC, Zonespace27 requested changes, later dismissed

2022-05-23 04:16 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/living/living.dm
> +	if(client.holder)
```suggestion
	if(client?.holder)
```
never assume.

2022-05-24 03:32 UTC, francinum commented on code/modules/mob/dead/dead.dm
> +	//SKYRAT EDIT END
This entire proc is short-circuited and returns `..()` after the round has started. This code is never reached by observers or new_players when it matters. https://github.com/Skyrat-SS13/Skyrat-tg/blob/e543e0f092487f1fe32cbb63f3770dec3bf8876d/code/modules/mob/dead/dead.dm#L36-L41

2022-05-26 23:37 UTC, SingingSpock commented
I legitimately didn't play when the statpanel was broken because I couldn't see the round timer. Basically instead of deciding not to do something in the last 30 minutes because I know the shuttle call will be soon, I have to worry about this all round. This will not solve the problem of people not wanting to commit a bunch time to something that will be wiped away by the incoming tide before it comes to completion, it just hides the tide charts.

2022-05-27 19:44 UTC, realtaac commented
yeah this gets a big minus one from me, this just means people will have to sit before starting a scene like "how long has the round been? if I start a scene now will it be cut off in 5 mins" 0/10 do not recommend

2022-05-27 22:13 UTC, Nerev4r commented
tf4's implementation will be a finer solution. experiment closed.

2022-05-27 22:13 UTC, closed without merging