Ghost Cafe: Japanese Room (and a cave forge)
Skyrat-SS13/Skyrat-TG pull request #13960
Opened 2022-05-27 23:02 UTC by theselfish

## About The Pull Request

More themed rooms from the ghouls of the Ghost Cafe.
![image](https://user-images.githubusercontent.com/102828457/170798328-f6e37bf8-f2bd-4504-bc7d-652f69ef4392.png)
A Japanese (or Shinto, for branding reasons) Room based off an older model of Cafe...
![image](https://user-images.githubusercontent.com/102828457/170798391-4d7c50d9-b910-4f95-b7cd-ea18018e3ea5.png)
Unearthed from the Overlook/Cafe war is **The Forge**.
This one doesn't make vampire super soldiers for the British government, or metallic men with lasers.
Forging methods have advanced, so if anything is missing, please shout at me. Also the Lava is fake.

## How This Contributes To The Skyrat Roleplay Experience

More themed rooms are good.
Also, the Forge allows players to train themselves in forging things. I think.

## Changelog

:cl: Cursor
add: The Ghost Cafe now has a new, Japanese themed room! Oh and a 'forge' or something.
qol: Made rooms that were marked as Ghost Cafe Outdoors use the Ghost Cafe Area.
/:cl:

2022-05-27 23:15 UTC, theselfish commented
Hmf. Wonder what I missed.
![image](https://user-images.githubusercontent.com/102828457/170799380-9c1df2b1-869c-4e83-adb6-e80ba936e1bd.png)

2022-05-28 00:06 UTC, theselfish commented
It seemingly has. Bolts are screwed as my attempt at making them resulted in the id error. DIY it.

2022-05-30 06:21 UTC, softcerv commented
do you have glassblowing stuff included?

2022-05-30 18:29 UTC, theselfish commented
> do you have glassblowing stuff included?

I never even knew about that. What does it need?

2022-06-02 06:57 UTC, theselfish commented
Oh.
OK.

2022-06-02 07:13 UTC, theselfish commented
![image](https://user-images.githubusercontent.com/102828457/171573673-a291d269-afcd-4793-86db-eff4158c765d.png)

2022-06-04 12:53 UTC, theselfish commented
@GoldenAlpharex @KathrinBailey In good news, the pr has decided to work, and the bolts are here.

2022-06-07 07:01 UTC, theselfish commented
Oh for fuck's sake.

2022-06-07 07:42 UTC, theselfish commented
@Gandalf2k15 @Zonespace27 @GoldenAlpharex @KathrinBailey Please. I beg you. These merge conflicts hurt my soul.

2022-06-07 15:21 UTC, tf-4 requested changes
Not a fan of having a forging setup. We don't want to encourage people starting bloodbaths in the ghost cafe.

2022-06-07 15:32 UTC, theselfish commented
> Not a fan of having a forging setup. We don't want to encourage people starting bloodbaths in the ghost cafe.

I personally believe it gives players a safe space to learn how to forge stuff without wasting station materials.

2022-06-08 08:27 UTC, theselfish commented
@tf-4 Also, I'm fairly certain that people can already create forging equipment in the Cafe, this simply gives it a pre-established location.

2022-06-08 09:02 UTC, tf-4 commented
I don't want to encourage it. Not really gonna shift on that.

2022-06-08 12:19 UTC, theselfish commented
> I don't want to encourage it. Not really gonna shift on that.

Fine.

2022-06-08 12:23 UTC, theselfish commented
![image](https://user-images.githubusercontent.com/102828457/172615201-e890a00a-3a14-4e70-8993-4e05fa2894d2.png)


> I don't want to encourage it. Not really gonna shift on that.

I kept the stuff for fishing. But the rest is gone.

2022-06-08 18:05 UTC, tf-4 requested changes

2022-06-08 18:05 UTC, tf-4 commented on modular_skyrat/modules/ghostcafe/code/ghostcafeturf.dm
> +/turf/open/lava/planet
```suggestion
/turf/open/lava/fake
```
Would be good to have this more descriptive for admin-finding purposes. Otherwise happy with this.

2022-06-08 18:28 UTC, tf-4 approved these changes

2022-06-08 18:45 UTC, theselfish commented
@tf-4 I believe this error is unrelated. Correct?

2022-06-09 13:27 UTC, tf-4 commented
Changelog moment

2022-06-09 17:26 UTC, theselfish commented
> Changelog moment

...Wait what.

2022-06-09 17:30 UTC, theselfish commented
@tf-4 And fixed.

2022-06-09 18:06 UTC, tf-4 approved these changes

2022-06-10 19:53 UTC, merged