[Modular]makes stasis surgery modular and makes tables glow
Skyrat-SS13/Skyrat-TG pull request #13982
Opened 2022-05-29 08:21 UTC by nevimer

## About The Pull Request

Modularizes stasis operating tables and makes them glow subtly to indicate if the patient is in stasis or not. Looks cool.

https://user-images.githubusercontent.com/77420409/170858950-46612483-4e57-4caa-9f02-1dd359d0c50b.mp4

## How This Contributes To The Skyrat Roleplay Experience

Less people rotting away due to there being no visual indicator they're "on" the table

## Changelog

:cl:
code: makes stasis surgery modular
qol: made stasis surgery tables visually indicate that they're in use with a faint blue glow. Less inadvertent body decay. 
/:cl:

2022-05-29 10:31 UTC, tf-4 commented
How does it look with just the mob glowing and not the table?

2022-05-30 00:29 UTC, GoldenAlpharex requested changes
This is not needed, as there's already a ripple implemented for stasis, which also looks a lot cooler and less intrusive than a glow. It was broken, so I don't blame you for not noticing, but there's now a fix for it upstream, done by yours truly, to make it 100% functional again, rendering this PR unnecessary.

Check it out if you're curious: https://github.com/tgstation/tgstation/pull/67403

2022-05-30 01:13 UTC, nevimer commented
> This is not needed, as there's already a ripple implemented for stasis, which also looks a lot cooler and less intrusive than a glow. It was broken, so I don't blame you for not noticing, but there's now a fix for it upstream, done by yours truly, to make it 100% functional again, rendering this PR unnecessary.
> 
> Check it out if you're curious: [tgstation/tgstation#67403](https://github.com/tgstation/tgstation/pull/67403)

I'm still keeping it open since it still makes this modular AND adds a cool glow that looks stasis-like and numbing.

2022-05-30 01:19 UTC, nevimer commented
> How does it look with just the mob glowing and not the table?
![dreamseeker_sG5JhbeRcE](https://user-images.githubusercontent.com/77420409/170900729-efed29a5-5350-44c8-9330-219151269952.png)

2022-05-30 03:14 UTC, tf-4 commented
> > How does it look with just the mob glowing and not the table?
> > ![dreamseeker_sG5JhbeRcE](https://user-images.githubusercontent.com/77420409/170900729-efed29a5-5350-44c8-9330-219151269952.png)

Hmmm I think I prefer this. Dunno what others think.

2022-05-30 05:59 UTC, OrionTheFox commented
I'd say shift the color to stasis-green if anything, the blue feels out of place

2022-05-30 08:18 UTC, nevimer commented
> I'd say shift the color to stasis-green if anything, the blue feels out of place

What is Stasis-Green?

2022-06-02 02:39 UTC, nevimer commented
> > > How does it look with just the mob glowing and not the table?
> > > ![dreamseeker_sG5JhbeRcE](https://user-images.githubusercontent.com/77420409/170900729-efed29a5-5350-44c8-9330-219151269952.png)
> 
> Hmmm I think I prefer this. Dunno what others think.

It do be like this now

2022-06-13 13:50 UTC, Gandalf2k15 commented
The ripple should do, since that was its intended effect

2022-06-13 13:50 UTC, closed without merging

2022-06-13 16:31 UTC, nevimer commented
still makes it modular