[NON-MODULAR] Moves the ammunition bench lethal disk design from weapon development technology to the security basic equipment.
Skyrat-SS13/Skyrat-TG pull request #13998
Opened 2022-05-30 15:20 UTC by Moostard

## About The Pull Request
Moves the ammunition bench lethal disk design from weapon development technology to the security basic equipment.

## How This Contributes To The Skyrat Roleplay Experience
With recent science/toxins changes, this will end just like advanced weapon tech before(locked unless one of few scientists that know how toxins work does the experiment). Having no way of reloading guns for major threats is a big problem.
This makes sure that security doesn't have to use spears and/or rocks and/or exploding microfusion guns when dedicated toxin scientist isn't present.

## Changelog

:cl:
balance: Changed the tech node for the lethal ammunition bench disk (weapon development technology -> basic security equipment).
/:cl:

2022-05-31 00:44 UTC, YakumoChen commented
Move the experiment back to adv tech instead of this, or give it an easier experiment.  Lethal ammo should require slightly more effort than a 1000 point roundstart tech node.

2022-05-31 00:48 UTC, YakumoChen commented
Better yet. Don't. There are guides to toxins, microfusion stuff is fine and plentiful, and you can get the disk from cargo with some effort.

2022-05-31 10:04 UTC, Moostard commented
> Better yet. Don't. There are guides to toxins, plenty of science staff each round to do it, microfusion stuff is fine and plentiful, and you can get the disk from cargo with some effort.

This will not work.
It did not work already.

Before the scipapers we had a simple experiment.
Basically a fart explosion.
It wasn't done a lot of times even that it required 0 toxin knowledge.
It was so bad, security usually had to go to space and shoot a welding fuel tank or throw a potwater nade themselves.
So "there are toxin guides" is not helping if people simply do not want to do it.

Science might have a lot of people during highpop, but most of them are not scientists and they will not do their job.

The effort in getting a lethal disk from cargo involves farming credits as it is massively overpriced and cargo has to buy the company in the first place. Forcing people to grind bounties to be able to do their job is not fun nor good.

It is not something that makes their job easier like advanced tools.
It is literally essential for major threats.

2022-05-31 11:11 UTC, Ashrollen commented
> Better yet. Don't. There are guides to toxins, plenty of science staff each round to do it, microfusion stuff is fine and plentiful, and you can get the disk from cargo with some effort.

First things first. Ill be straight honest.Most of science does not work at even their 40% of capacity.Guides and information means nothing if person from science won't join or do their job as they should be. In fact restricting security will only push said security right now to create new methods of fight.And from what i know there is many almost warcrime level of ways in how to wage war during shift.If any person thinks  that lethal ammo matters that much to create practically block on using it, i will gladly say that sec will start using stun shamshir combo which is way more cruel than just shoot someone dead. In fact we are indeed will regress to spears/swords with toolboxes with many other issues.

If we talk about MCR and everything related to it.At best MCR can stop threat of level carp and small critters.Even ice whelp can kill you if you will be not carefull while using MCR (which will take  2 mags of normal batteries to kill that simplemob).I can make pretty much many examples how MCR lacks and im always ready to proove its not near enough in many situations.In fact its below even expected range of use. Only way to use it decently is to make same advanced researches in which lethal disk exist which totally kills purpose of that gun.

2022-06-02 03:15 UTC, theselfish commented
Just do toxins.

Seriously. What does this server have against toxins?

2022-06-02 08:47 UTC, Moostard commented
> Just do toxins.
> 
> Seriously. What does this server have against toxins?

The answer to your question was already given.
No matter how easy it is, barely anybody will do it.

If you remember medical tech experiments that were slime core scans, you already know what i meant.
If there was no scientist on xenobio, medbay would not see anything more advanced than a piece of metal.
It was changed to dissections so medbay is not suffering from "nobody in science did slimes". They can just do it themselves.

Weapon technology is locked behind a pressure bomb. It is harder than a "explosion test", which was piss easy, required 0 toxin knowledge, yet still was NOT done. But at least security werent suffering from it as they could do it themselves. Now they cannot.

2022-06-02 18:37 UTC, YakumoChen commented
Revert it, make it a discount, or move the experiment back to advanced tech. Do not move the lethal disk to a tech that makes no sense.

2022-06-02 23:09 UTC, Moostard commented
> Revert it, make it a discount, or move the experiment back to advanced tech. Otherwise don't bother. Do not move the lethal disk to a tech that makes no sense.

TG might change something with toxins sooner or later again.
How does it make no sense? I have no idea what you are talking about.
Lethal ammunition being something "advanced" makes no sense.

I have already explained the reason for it.

Weapon tech being locked by a pressure bomb is not a problem.
The disk which gives lethal options in the bench being locked behind it is.

2022-06-03 01:09 UTC, Ashrollen commented
> Revert it, make it a discount, or move the experiment back to advanced tech. Otherwise don't bother. Do not move the lethal disk to a tech that makes no sense.

What you say right now makes no sense to me.We need literally do researches to know how to make lethal ammo which exists since ages?Ammo that people can self made in crafting menu by creating improvied slugs? And not only that we need research we need research with explosion? What kind of ammo actually is if it needs whole bomb to be used in experiments.Ah right ammo which can deal damage like any ordered in guncargo magazine full of ordinary bullets.To be honest that disk is worth 1k points and nothing more.

2022-06-03 03:18 UTC, YakumoChen commented
Lethal ammo being part of **_Weapon Development_** technology is consistent with how research has functioned in the game since the advent of techwebs. Putting it in a "Security Equipment" node doesn't make sense, nor should it be in a 1000 point tech node. Every other researchable gun and ammo type is under Weapon Development, so this makes consistent sense.

Not to mention that moving the disk down a step instead of actually addressing your own concerns with research is fundamentally a lazy fix that accomplishes little to nothing.

2022-06-03 11:18 UTC, Moostard commented
> Lethal ammo being part of **_Weapon Development_** technology is consistent with how research has functioned in the game since the advent of techwebs.

That disk did not exist before gunsec.
It is a Skyrat thing.

> Putting it in a "Security Equipment" node doesn't make sense, nor should it be in a 1000 point tech node.

Lethals are not something magical/highly advanced. I do not see why it does not make sense or why point amount matters in this case.
Security always had lethal lasers in the armory. They were cheap(about 300 per one) and effective by TG balance. Those basic lasers were put on a above 1k price tag and limited supply. Replaced by MCRs, which are worse without upgrades(which are locked behind the weapon techs).

> Every other researchable gun and ammo type is under Weapon Development, so this makes consistent sense.

Every other researchable gun and ammo(mostly shotgun exotic shells) are there, yes. But none of them are essential, never were. Being unable to respond to for example blob, because your weapon cannot be reloaded with lethals is hilarious(in a bad way). Not being able to upgrade your egun to AEG does not matter. Being unable to shoot lethal lasers from said egun, because nobody in science cared about a pressure bomb, would very much matter.

> Not to mention that moving the disk down a step instead of actually addressing your own concerns with research is fundamentally a lazy fix that accomplishes little to nothing.

What do you want me to do?
Tell science to do their job?
Considering it was problematic to do the light explosion experiment (which could be done by a welding fuel tank or bottle potwater nade), i do not see pressure bomb being made often. (in fact, i have not seen it be done yet).

Exactly why medical experiments changed to dissections, so they are not 100% dependant on science, which often did not care about slime surveys, unless a dedicated xenobiologist was present.
If engineering wants powertools, but science does not feel like doing the experiment, they can easily make a BZ can or just order one and do it.
Security wants/NEEDS lethals? They are simply fckd.
Because they cannot currently do it themselves in case science does not care.

This "lazy fix" makes sure that situation does not happen.
While on TG those are additional gadgets/gear/weapon upgrades, on Skyrat it is essential because of the disk.
So this will make the pressure bomb locked weapon tech not essential anymore, but upgrades like in every other case.

2022-06-03 17:40 UTC, Zonespace27 requested changes
Make the tech attached to something less obtainable than basic sec equipment

2022-06-03 17:47 UTC, CandleJaxx commented
my rebuttal is that the weapons experiment is easy enoug has is- cooled nitrogen and hot plasma. easy... just tell science to handle it, or complain to their rd if noone does

2022-06-03 20:23 UTC, YakumoChen commented
> What do you want me to do?



> Revert it, make it a discount, or move the experiment back to advanced tech. Otherwise don't bother. Do not move the lethal disk to a tech that makes no sense.

2022-06-04 11:52 UTC, Moostard commented
I might do something different later.

2022-06-04 11:52 UTC, closed without merging

2022-06-08 01:05 UTC, Ashrollen commented
> my rebuttal is that the weapons experiment is easy enoug has is- cooled nitrogen and hot plasma. easy... just tell science to handle it, or complain to their rd if noone does

My rebuttal will be harsh this time. Man i literally see that science fucks inside their department non stop. Doing nothing. Last time i went there and two roboticist sat with stripper pole naked and did utterly nothing. They ignored my request to give me battery and jetpack which is not oh so unreal request. Wanna hear honest opinion? Science is not doing job at all. Thanks for thinking otherwise i suppose now i will start sending ahelp tickets if such simple experiment is not done or science literally decided to do nothing.