The flesh that speaks [CI CHECK]
Skyrat-SS13/Skyrat-TG pull request #14023
Opened 2022-05-31 16:11 UTC by Gandalf2k15

## About The Pull Request
Adds a new random event, akin to the hivemind from Eris. Called corrupted flesh.

Credits for the sprites and sounds: https://github.com/discordia-space/CEV-Eris/pull/2894 (Macleod962)

Because it's Eris I basically had to rewrite everything.

## Changelog

:cl:
add: A new random event, corrupted flesh.
/:cl:

2022-05-31 16:12 UTC, Zonespace27 commented on _maps/_basemap.dm
> +#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
oops

2022-05-31 16:39 UTC, Gandalf2k15 commented
Wow. Passes CI. Nice.

2022-06-01 05:56 UTC, ErdinyoBarboza commented
Great work

2022-06-01 22:52 UTC, Nerev4r commented
So, balance thoughts from the first round.
I think the ability for the fleshmind to transmit through pipes is probably the strongest part of it. Either it shouldn't rly be able to, or it should only be able to go to the nearest vent instead of just any of them.
Second, we could probably use a core weapon against wireweeds. Probably wirecutters. They take awhile to break.
Third, it could probably use an announcement? At least after five minutes after it spawns or something. Give it some grace period like blob.

Otherwise, some Nice Things.
It'd be cool for the wireweeds themselves to be able to convert people. Having to wait around for a mechiver is kinda lame, and people still get to control their bodies, so it shouldn't be too bad.
Whisperers could stand to be more common.
It'd be cool if you could willingly submit yourself for conversion, as I did write all those voicelines with the intent of even some people doing that.


![image](https://user-images.githubusercontent.com/12636964/171514500-99e3eff0-d350-45a8-9739-68a473a0df20.png)
As to bugs, these things are fucky.

2022-06-01 22:56 UTC, YakumoChen commented
hoping that the obvious system shock 2 voicelines are just a placeholder, I have reservations about using clearly copyrighted (and not open source) material on the server.

2022-06-01 23:10 UTC, Nerev4r commented
Update: It's not spawning floaters.

2022-06-01 23:37 UTC, YakumoChen commented
I saw a floater when I was playing death commando, it did spawn, and exploded on me as intended.

2022-06-01 23:38 UTC, Nerev4r commented
Scratch that, then. It doesn't spawn Whisperers, I don't believe.

2022-06-08 19:44 UTC, Gandalf2k15 commented
This is now in alpha.

2022-06-09 23:36 UTC, Tastyfish commented
Can there be an antag icon like with families, cult etc for fellow infected? I had to squint or use examine to tell if some people were part of the fleshmind. Other people had the same problem.

2022-06-11 09:33 UTC, OrionTheFox commented
was wondering what i kept thinking of when i saw this, its reminding me of Corruption from HZD <details><summary>Big image</summary>
![image](https://user-images.githubusercontent.com/76465278/173182092-5792380a-5f75-4d3c-b5fe-fd3a6baac531.png)

If only 32x32 sprites could look this good :(</details>

So, if you wanted to try some light recoloring, that might be fun to aim for. Reddish/purplish corruption vibes.

---

From what I see in the PR itself, this just looks like a rethemed mold - not that thats a bad thing, though. Personally all for leaning into that, having it pseudo-containable and with key points to aim for.
Again just looking at the PR body, the messages seem... spam-my, they could probably be toned down or only activate on triggers (i.e. taking damage has a chance of certain messages, engaging a new target gives a message, etc), and the broken glass makes me feel sad because there's no reason for the fleshmind to have broken such pretty glass.
I can give better feedback after attending a test, but otherwise people seem to be enjoying it 👍 Just dont expect me to review the code LMAO

2022-06-14 21:51 UTC, Nerev4r commented
I think the ending is a little unfitting; that is, nuking the place. You'd think the 'ending' would be maxing out the spread rate or something, so that it can convert as many people as possible rather than just killing them.

2022-06-21 20:11 UTC, YakumoChen requested changes
Remove the copyrighted sounds. I've played System Shock 2 before, and most of the mob sounds are identical or barely altered. Since you didn't claim to make them, the burden is on you to prove they aren't copyrighted.

2022-06-29 08:16 UTC, SethLafuente commented
Love it, cant wait to see it get stolen it into other servers

2022-07-01 00:56 UTC, Gandalf2k15 commented
Removed atmos from a possible spawn location

2022-08-28 03:24 UTC, Zenitheevee commented
*bruh*

2022-10-07 00:05 UTC, Zonespace27 requested changes
cobalt wanted a review

2022-10-07 00:05 UTC, Zonespace27 commented on code/datums/ai/monkey/monkey_controller.dm
> +	// SKYRAT EDIT ADDITION
this still needed?

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_boss.dm
> +	var/list/footstep_sounds = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_boss.dm
> +	var/barage = 1
two "r"s

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_boss.dm
> +	var/barage_interval = 2
ditto

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_boss.dm
> +	var/list/laser_projectile_sounds = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_controller.dm
> +	for(var/obj/structure/fleshmind/wireweed/wireweed as anything in active_wireweed)
this whole section could use a touch of documentation

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_controller.dm
> +	make_ert(/datum/ert/asset_protection, 5, "HEAD TO AND BOARD THE EMERGENCY SHUTTLE, DO NOT USE THE FERRY, STOP THE CORRUPTION AT **ALL** COSTS!!!", "the last defense of centcom", "GAMMA", FALSE, TRUE
this doesn't feel more than delta worthy

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_environment_objects.dm
> +/obj/structure/fleshmind/wireweed/examine(mob/user)
not needed

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_environment_objects.dm
> +	var/list/replacement_zones = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_event.dm
> +
```suggestion
```

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_event.dm
> +	for(var/area/iterating_area in world)
use GLOB.sortedAreas (or change the code a bit to use GLOB.areas_by_type)

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_mobs.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_mobs.dm
> +	var/faking_death = FALSE
unsure about this, will have to see how it goes in practice

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_mobs.dm
> +		angle += rand(5, 25)*pick(-1, 1)
```suggestion
		angle += rand(5, 25) * pick(-1, 1)
```

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_mobs.dm
> +	var/list/torment_lines = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/human_corruption_component.dm
> +	var/list/traits_to_give = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/human_corruption_component.dm
> +	var/list/replacement_zones = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/machine_corruption_component.dm
> +	var/list/possible_overlays = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/make_ert.dm
> +/proc/make_ert(ert_type, teamsize = 5, mission_objective_override = "Assist the station.", poll_description = "an ERT team", code = "UNKNOWN", enforce_human = FALSE, open_armory_doors = FALSE, leader
maybe move to somewhere more general-purpose?

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/make_ert.dm
> +		index = (index + 1) % spawnpoints.len
```suggestion
		index = (index + 1) % length(spawnpoints)
```

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/make_ert.dm
> +		candidates -= chosen_candidate
use LAZYREMOVE (same goes for other list ops of `candidates` and `candidate_living_exps`

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/make_ert.dm
> +			candidate_living_exps = candidate_living_exps.Cut(ERT_EXPERIENCED_LEADER_CHOOSE_TOP + 1) // pick from the top ERT_EXPERIENCED_LEADER_CHOOSE_TOP contenders in playtime
like here for example

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/make_ert.dm
> +			door.open()
may as well make these async so they don't open one
at
a
time

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_structures.dm
> +		return TRUE
```suggestion
		return TRUE
	return .
```
tg coding standard when . is non-standard

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_structures.dm
> +	var/list/join_quotes = list(
static

2022-10-07 00:05 UTC, Zonespace27 commented on modular_skyrat/modules/fleshmind/code/fleshmind_structures.dm
> +	var/list/monster_types = list(
static

2022-10-08 07:28 UTC, Gandalf2k15 commented on modular_skyrat/modules/fleshmind/code/fleshmind_controller.dm
> +	make_ert(/datum/ert/asset_protection, 5, "HEAD TO AND BOARD THE EMERGENCY SHUTTLE, DO NOT USE THE FERRY, STOP THE CORRUPTION AT **ALL** COSTS!!!", "the last defense of centcom", "GAMMA", FALSE, TRUE
It's gamma because in it's lore it has the power to destroy civilisations.

2022-11-12 04:05 UTC, Acer202 commented
This isn't gone for good, is it? It was super cool.

2022-11-12 07:26 UTC, Zonespace27 commented
> This isn't gone for good, is it? It was super cool.

It's mostly done, it just needs people to finish coding it

2023-04-04 17:42 UTC, Gandalf2k15 commented
Will re-open when ready to merge

2023-08-16 20:02 UTC, Acer202 commented
Heyhey it's me again. Skyrat RED is now a thing, prime for this kind of antag probably. Maybe this could live? (Please it was so cool)

2023-12-25 22:17 UTC, Gandalf2k15 commented
she's not dead yet captain

2023-12-31 19:13 UTC, StrangeWeirdKitten commented on code/modules/unit_tests/simple_animal_freeze.dm
> +		/mob/living/simple_animal/hostile/fleshmind,
These should probally be refactored before merge.

2023-12-31 23:27 UTC, Gandalf2k15 commented
TODO: add more abilities for the converted humans; tentacle and armblade.

2024-01-03 05:49 UTC, Detective-Google commented
the mobs for this don't seem to properly be able to aggro onto and deal with sentient simplemobs a-la miner drake form or bear form.

2024-01-05 21:01 UTC, Gandalf2k15 commented
regen no fix blood

2024-04-29 15:38 UTC, StrangeWeirdKitten commented
I got around to refactoring half the AI mob code into basic mobs on the bubber end of this PR. https://github.com/Bubberstation/Bubberstation/pull/933

2024-08-26 16:38 UTC, Gandalf2k15 commented
someday

2024-08-26 16:38 UTC, closed without merging