[SEMI-MODULAR] [READY] Underwear Ports, in 2022? Also fixing the Dutch jacket hiding your hands
Skyrat-SS13/Skyrat-TG pull request #14069
Opened 2022-06-03 01:23 UTC by Nerev4r

## About The Pull Request
Ports some undies from https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pulls

<details>
<summary> The Contents </summary>

![image](https://user-images.githubusercontent.com/12636964/171763087-1c670e52-23f7-488c-a689-93490a1623ca.png)
Leotards. Yes, this is a closet cosplay of Panam Palmer from Cyberpunk 2077. Cope.

![image](https://user-images.githubusercontent.com/12636964/171763104-64bf7a33-ee38-4336-af5b-4e42a9256bac.png)
Stirrup socks. These come in short, normal-length, knee-high, thigh-high, pantyhose, leggings, and striped knee/thigh-high. Yes, this is a closet cosplay of Envy from Fullmetal Alchemist. Yes, they were my favorite Homunculus.

![image](https://user-images.githubusercontent.com/12636964/171763196-9ca96e06-15a2-40fa-ac25-4ae000bfb7ab.png)
![image](https://user-images.githubusercontent.com/12636964/171763201-c62c412f-c01c-4ed1-a819-39f6fd889c61.png)
![image](https://user-images.githubusercontent.com/12636964/171763210-91d4e28b-acc4-4a31-918e-483acfe0c606.png)
Turtleneck undershirt. 

![image](https://user-images.githubusercontent.com/12636964/171763227-af39414d-d36f-47b7-8908-cc4abbf6e929.png)
![image](https://user-images.githubusercontent.com/12636964/171763230-89cd86e2-2adb-4a3e-8fc1-fb9028735389.png)
![image](https://user-images.githubusercontent.com/12636964/171763232-3d8a74ee-46a7-48d3-a2c3-8d23c579a48f.png)
Comes without sleeves too.

![image](https://user-images.githubusercontent.com/12636964/171763247-cde35d53-9c0d-4f7d-af79-c652460f8806.png)
Easy to recolor.

![image](https://user-images.githubusercontent.com/12636964/171767858-1c2a1672-5c8e-4e81-a5d7-c866647fa875.png)
![image](https://user-images.githubusercontent.com/12636964/171767863-42204c80-54e3-40ef-aac5-b9c264e411b7.png)
Off-shoulder top, with brastrap.

![image](https://user-images.githubusercontent.com/12636964/171767873-3a16f96e-a187-4f86-a4df-e4a628b19acf.png)
![image](https://user-images.githubusercontent.com/12636964/171767878-e0510db4-e8be-4ccb-bfc7-b6e8adf4c4b3.png)
Off-shoulder top, without brastrap. Just put bra, bikini under there.

![image](https://user-images.githubusercontent.com/12636964/171767901-661379b2-f8a5-41af-bae7-5bb3fccdc441.png)
Recolorable fishnets.

![image](https://user-images.githubusercontent.com/12636964/171768426-a69417e8-fb5f-4399-95d4-ef20531317f4.png)
![image](https://user-images.githubusercontent.com/12636964/171768431-1ee4a1d1-de54-496e-bd58-7b8b6e69e522.png)
These don't have the obligatory bra cups that the old ones did. Yes, I made a Security pinup guy. He's pretty cool.

![image](https://user-images.githubusercontent.com/12636964/171768533-1a940bca-8bcc-41c3-9dc8-18ccd53b2a92.png)
Sarashi chest bandages. For the samurai/sukeban/fem Goro Majima in you.

![image](https://user-images.githubusercontent.com/12636964/171768571-31ee5d3d-00ec-4551-9a36-d19513edd0e6.png)
Leggings.

![image](https://user-images.githubusercontent.com/12636964/171768585-802c5790-d53f-4a6a-8203-7d48af29cf39.png)
Binders. There's a strapless version.

</details>

## How This Contributes To The Skyrat Roleplay Experience
Customization good.

## Changelog

:cl:
add: Adds some binders, turtlenecks, recolorable fishnet attire, off-shoulder tops, leotards, leggings, sarashi, and stirrup socks to character setup.
add: Makes thongs recolorable.
fix: Makes the Dutch Jacket have hand cutouts again.
del: Removes the alt strapless bra, it doesn't work and the sprite for it doesn't exist. 
/:cl:

2022-06-03 02:36 UTC, Nerev4r commented
Update: This also fixes the Dutch Jacket having no hands.

2022-06-03 15:08 UTC, Gandalf2k15 commented
Sorry bot says I gotta close your pr

2022-06-03 15:36 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> -/datum/sprite_accessory/undershirt/bra_strapless_alt
?

2022-06-03 15:43 UTC, Nerev4r commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> -/datum/sprite_accessory/undershirt/bra_strapless_alt
Oh, forgot to include this in the changelog. The sprite doesn't physically exist so this doesn't work, I'm not sure if it ever did.

2022-06-06 11:03 UTC, tf-4 requested changes
Mostly just redundant subtype stuff

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	gender = FEMALE
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	gender = FEMALE
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	gender = FEMALE
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/socks/socks_knee/stirrups
```suggestion
/datum/sprite_accessory/socks/stirrups_knee
```
Don't see a reason for this to be subtype at a glance

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/socks/socks_norm/stirrups
```suggestion
/datum/sprite_accessory/socks/stirrups_norm
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/socks/socks_mid_stirrups
```suggestion
/datum/sprite_accessory/socks/stirrups_mid
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/socks/socks_thigh/stirrups
```suggestion
/datum/sprite_accessory/socks/stirrups_thigh
```
Etc

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	gender = FEMALE
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	use_static = TRUE
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	use_static = null
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	use_static = null
```suggestion
```

2022-06-06 11:03 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	use_static = null
```suggestion
```

2022-06-06 15:01 UTC, Zonespace27 submitted a review, later dismissed

2022-06-06 15:01 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "bandages"
this the correct iconstate?

2022-06-06 15:10 UTC, Nerev4r commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	icon_state = "bandages"
Yes.

2022-06-06 15:41 UTC, GoldenAlpharex requested changes
Most of these have nice shapes, but they severely lack in shading. Look at the first few, you need to squint to see the details on most of them, because there's barely any difference in color.

The last two, the binder and the leggings, are also incredibly flat and/or weirdly shaded.

The chest wrap looks fine for the most part. The fishnets, well, it's fishnet, you won't really get much better than that.

Overall, I feel like a few of these could just use a bit more shading, and more depth in their color, because having to squint to see color differences isn't too great.

Also, for the dutch jacket, I'd just honestly recommend you put it in a different PR, it'd get merged much faster.

2022-06-06 21:40 UTC, Nerev4r commented
![image](https://user-images.githubusercontent.com/12636964/172253172-587c32c2-ee20-47eb-b8b4-5c5e26575ac7.png)
![image](https://user-images.githubusercontent.com/12636964/172253193-ca20b642-727e-437f-b55f-bb91f5ddc4d7.png)
![image](https://user-images.githubusercontent.com/12636964/172253199-b649c87e-72b2-42f3-bc4d-841e2fcfbbde.png)
Regular
![image](https://user-images.githubusercontent.com/12636964/172253218-c48e69ba-45f3-4184-a78d-57b6a7dc912c.png)
![image](https://user-images.githubusercontent.com/12636964/172253220-8e6a9652-884f-44cc-9fbc-7629a0ec0469.png)
![image](https://user-images.githubusercontent.com/12636964/172253222-a1d083e9-4e24-48f9-abb6-1a88060a1af1.png)
Sleeveless
Leotard update.

![image](https://user-images.githubusercontent.com/12636964/172253259-8f8e970e-92ee-42de-98e7-9cb1ba31e81a.png)
![image](https://user-images.githubusercontent.com/12636964/172253270-633d12ba-7802-4e4d-8ef7-54c741991a3b.png)
![image](https://user-images.githubusercontent.com/12636964/172253286-57a02c98-3a48-46ef-ae00-ae1983145628.png)
Regular
![image](https://user-images.githubusercontent.com/12636964/172253307-21fa769d-6bc7-4db6-b8a9-54e3fa4c126f.png)
![image](https://user-images.githubusercontent.com/12636964/172253319-e6d5a1ff-cf61-4d0f-9eb1-fa2b5748c449.png)
![image](https://user-images.githubusercontent.com/12636964/172253332-b34416d8-5476-47b0-ab01-53261e280921.png)
Sleeveless
Turtleneck update.


![image](https://user-images.githubusercontent.com/12636964/172253411-fff3a44f-93cf-45d2-98ed-50e73c3f5dea.png)
![image](https://user-images.githubusercontent.com/12636964/172253421-f57c57d6-93a1-420c-8875-889ea07be57f.png)
![image](https://user-images.githubusercontent.com/12636964/172253433-b274240e-8eba-45c9-8031-b72d40566c99.png)
![image](https://user-images.githubusercontent.com/12636964/172253443-03a1613b-ee56-4a88-82d8-289fa8daf9cf.png)
Off-shoulder top, with brastrap.

![image](https://user-images.githubusercontent.com/12636964/172253470-96891ea5-0566-4bb1-8745-b1a6886e0731.png)
Off-shoulder top, without brastrap. Just put bra, bikini under there if you want it.

![image](https://user-images.githubusercontent.com/12636964/172253658-0cf5f3f2-6034-40bf-8f34-adc7187f1d76.png)
![image](https://user-images.githubusercontent.com/12636964/172253682-b7954e82-7fed-49a5-9a53-b6b29119a05b.png)
![image](https://user-images.githubusercontent.com/12636964/172253701-1938bb8f-53a4-411e-8192-97e4aed5a77f.png)
Leggings. I should note these are counted as socks.

![image](https://user-images.githubusercontent.com/12636964/172253776-d7181324-281c-415c-875f-ec929c10db69.png)
![image](https://user-images.githubusercontent.com/12636964/172253788-415b7cd7-ae62-4ae9-857e-547367d1c470.png)
![image](https://user-images.githubusercontent.com/12636964/172253794-80c2b0cc-3f16-4897-a3fa-620d3b400c17.png)
Binders. Happy pride month.

![image](https://user-images.githubusercontent.com/12636964/172253839-896e8fc9-f360-4e2c-8fb0-1ffc3613f174.png)
![image](https://user-images.githubusercontent.com/12636964/172253842-90c4f02e-f31a-4aa7-a032-44eb1cb0fd4d.png)
![image](https://user-images.githubusercontent.com/12636964/172253845-c4f8c7a5-fe51-4805-9e25-afb8fc236eed.png)
Strapless binders.

2022-06-08 00:30 UTC, GoldenAlpharex commented
> ![image](https://user-images.githubusercontent.com/12636964/172253172-587c32c2-ee20-47eb-b8b4-5c5e26575ac7.png) ![image](https://user-images.githubusercontent.com/12636964/172253193-ca20b642-727e-437f-b55f-bb91f5ddc4d7.png) ![image](https://user-images.githubusercontent.com/12636964/172253199-b649c87e-72b2-42f3-bc4d-841e2fcfbbde.png) Regular ![image](https://user-images.githubusercontent.com/12636964/172253218-c48e69ba-45f3-4184-a78d-57b6a7dc912c.png) ![image](https://user-images.githubusercontent.com/12636964/172253220-8e6a9652-884f-44cc-9fbc-7629a0ec0469.png) ![image](https://user-images.githubusercontent.com/12636964/172253222-a1d083e9-4e24-48f9-abb6-1a88060a1af1.png) Sleeveless Leotard update.
> 
> ![image](https://user-images.githubusercontent.com/12636964/172253259-8f8e970e-92ee-42de-98e7-9cb1ba31e81a.png) ![image](https://user-images.githubusercontent.com/12636964/172253270-633d12ba-7802-4e4d-8ef7-54c741991a3b.png) ![image](https://user-images.githubusercontent.com/12636964/172253286-57a02c98-3a48-46ef-ae00-ae1983145628.png) Regular ![image](https://user-images.githubusercontent.com/12636964/172253307-21fa769d-6bc7-4db6-b8a9-54e3fa4c126f.png) ![image](https://user-images.githubusercontent.com/12636964/172253319-e6d5a1ff-cf61-4d0f-9eb1-fa2b5748c449.png) ![image](https://user-images.githubusercontent.com/12636964/172253332-b34416d8-5476-47b0-ab01-53261e280921.png) Sleeveless Turtleneck update.
> 
> ![image](https://user-images.githubusercontent.com/12636964/172253411-fff3a44f-93cf-45d2-98ed-50e73c3f5dea.png) ![image](https://user-images.githubusercontent.com/12636964/172253421-f57c57d6-93a1-420c-8875-889ea07be57f.png) ![image](https://user-images.githubusercontent.com/12636964/172253433-b274240e-8eba-45c9-8031-b72d40566c99.png) ![image](https://user-images.githubusercontent.com/12636964/172253443-03a1613b-ee56-4a88-82d8-289fa8daf9cf.png) Off-shoulder top, with brastrap.
> 
> ![image](https://user-images.githubusercontent.com/12636964/172253470-96891ea5-0566-4bb1-8745-b1a6886e0731.png) Off-shoulder top, without brastrap. Just put bra, bikini under there if you want it.
> 
> ![image](https://user-images.githubusercontent.com/12636964/172253658-0cf5f3f2-6034-40bf-8f34-adc7187f1d76.png) ![image](https://user-images.githubusercontent.com/12636964/172253682-b7954e82-7fed-49a5-9a53-b6b29119a05b.png) ![image](https://user-images.githubusercontent.com/12636964/172253701-1938bb8f-53a4-411e-8192-97e4aed5a77f.png) Leggings. I should note these are counted as socks.
> 
> ![image](https://user-images.githubusercontent.com/12636964/172253776-d7181324-281c-415c-875f-ec929c10db69.png) ![image](https://user-images.githubusercontent.com/12636964/172253788-415b7cd7-ae62-4ae9-857e-547367d1c470.png) ![image](https://user-images.githubusercontent.com/12636964/172253794-80c2b0cc-3f16-4897-a3fa-620d3b400c17.png) Binders. Happy pride month.
> 
> ![image](https://user-images.githubusercontent.com/12636964/172253839-896e8fc9-f360-4e2c-8fb0-1ffc3613f174.png) ![image](https://user-images.githubusercontent.com/12636964/172253842-90c4f02e-f31a-4aa7-a032-44eb1cb0fd4d.png) ![image](https://user-images.githubusercontent.com/12636964/172253845-c4f8c7a5-fe51-4805-9e25-afb8fc236eed.png) Strapless binders.

Oh yeah, that's much, much better. Nice work @CandleJaxx (and whoever else worked on these, if anyone else did, good job to you too).

That being said, are the binders meant to look like your nipples are showing through? Feels a bit odd compared to the other bras to me, but that's my only critique for all of those sprites.

2022-06-08 00:42 UTC, Nerev4r commented
handled.

2022-06-08 01:01 UTC, GoldenAlpharex approved these changes
Looks fine to me, ideally we'd have uniform greyscale colors for all of these, but I don't want to deal with this for any longer.

2022-06-08 01:07 UTC, merged