[NON-MODULAR] Reduces prisoner slots from 12 to 4.
Skyrat-SS13/Skyrat-TG pull request #14081
Opened 2022-06-04 09:38 UTC by Higgin

## About The Pull Request

Reduces prisoner slots from 12 to 4. 

## How This Contributes To The Skyrat Roleplay Experience

It sucks having up to twelve people join in to potentially require your babysitting/involvement to do anything in the round or even just not die to random events. Especially when your security department is two detectives and an officer. 

One of the problems is that the more people playing prisoner, the more interesting it can become for more people to join in as prisoner. Having it possibly go up to twelve (one less than all the available security slots) with no commensurate requirement for more security (COs in particular) is ridiculous as a cap.

Four is much more manageable even with lowpop in sec but should offer enough slots for COs (who sign up actually expecting to and interested in interacting with prisoners) to have focused RP with their prisoner crews as well (without also being pulled every direction by the management hell of a vortex anomaly spawning in the middle of the prison when it has eight people in it, for instance.) 

It should also encourage the people who want to roll prisoner to roll for it roundstart during highpop hours - if the role is so popular, and the mix of people you get in prison is part of what makes it enjoyable, this should satisfy that enjoyment with a more competitive mix of people rolling for it while also making it less prone to being an unasked-for and unmanageable-in-scale pain to manage for people playing regular security. 

## Changelog

:cl:
balance: Reduced prisoner slots from 12 to 4. 
/:cl:

2022-06-04 09:41 UTC, RatFromTheJungle commented
Much like with the sec-officer counts, don't try to go below half for the first count, ala, make it 6, because down to 25% of what it was before is a /steep/ drop, especially for a popular role.

2022-06-04 10:12 UTC, Higgin commented
Four is manageable from practical experience and seems to me about the right place for it. If it'll fly at six, I'll put it there when I'm up tomorrow and come back to it after it's had some time to play out. Frequently it's when it's 5-7 prisoners and lowpop sec that I see the most issues.

2022-06-04 11:20 UTC, tf-4 requested changes

2022-06-04 11:20 UTC, tf-4 commented on code/modules/jobs/job_types/prisoner.dm
> +	total_positions = 4		// SKYRAT EDIT: Original value (0)
```suggestion
	total_positions = 6		// SKYRAT EDIT: Original value (0)
```
Like jungle said

2022-06-04 15:09 UTC, Zonespace27 commented on code/modules/jobs/job_types/prisoner.dm
> +	total_positions = 4		// SKYRAT EDIT: Original value (0)
Seconding this

2022-06-04 15:44 UTC, GoldenAlpharex commented
That kind of stuff is handled in the config anyway.

2022-06-04 23:49 UTC, tf-4 approved these changes
This is done in config but I like it conceptually

2022-06-06 14:37 UTC, Gandalf2k15 approved these changes

2022-06-06 14:44 UTC, hugmeorelse commented
This is a config change. I also don't think it's too necessary, mostly because we've already made changes to the Prisoner role and have made it very clear they shouldn't be rioting or becoming "unmanageable". I do think having it scale to security population would be ideal however if that's possible rather than a flat decrease.

2022-06-06 17:11 UTC, Iamgoofball commented
A better idea would be to apply the sec/assistant scaling system to prisoners/guards.

2022-06-19 21:58 UTC, Gandalf2k15 commented
See my comment inhttps://github.com/Skyrat-SS13/Skyrat-tg/pull/14081

2022-06-19 21:58 UTC, closed without merging