[Modular] Show prisoner policy warnings to prisoners on spawn.
Skyrat-SS13/Skyrat-TG pull request #14088
Opened 2022-06-04 22:34 UTC by nevimer

## About The Pull Request

This shows prisoners a warning about self-antag and links them to the policy documents on spawn. 

## How This Contributes To The Skyrat Roleplay Experience

Policy is a good thing.

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-06-05 04:25 UTC, Zonespace27 commented on modular_skyrat/modules/warning/prisoner_warning.dm
> +/datum/job/prisoner/after_spawn(mob/living/carbon/human/H, mob/M)
one letter vars bad

2022-06-05 04:25 UTC, Zonespace27 requested changes

2022-06-05 04:25 UTC, Zonespace27 commented on modular_skyrat/modules/warning/prisoner_warning.dm
> +	to_chat(M, (span_doyourjobidiot("As a roundstart/latejoin prisoner, you are not an antagonist. You are allowed to cause moderate amounts of drama and shenanigans, but you should not be security's ma
why is the span in brackets

2022-06-06 17:14 UTC, Iamgoofball commented on modular_skyrat/modules/warning/prisoner_warning.dm
> +	to_chat(M, (span_doyourjobidiot("As a roundstart/latejoin prisoner, you are not an antagonist. You are allowed to cause moderate amounts of drama and shenanigans, but you should not be security's ma
we have an entire system for showing per-role policy as defined by config, why isn't this being placed in there server-side?

2022-06-06 17:14 UTC, Iamgoofball commented
always fill out a changelog for your GBP

2022-06-06 19:29 UTC, Iamgoofball commented
![Code_8YxEY8QAp0](https://user-images.githubusercontent.com/4081722/172233388-927838c9-2ba5-421c-afdb-afcdf76216ef.png)
i recommend utilizing the policy.json instead

2022-06-13 13:46 UTC, Zonespace27 commented
What goof said.

2022-06-13 13:46 UTC, closed without merging

2022-06-13 16:30 UTC, nevimer commented
> What goof said.

The rest of the codebase doesn't do that. It all uses this method for every job.

2022-06-13 16:50 UTC, Zonespace27 commented
> > What goof said.
> 
> The rest of the codebase doesn't do that. It all uses this method for every job.

It shouldn't and now it doesn't (#14288)