make the current map not appear in map votes
Skyrat-SS13/Skyrat-TG pull request #14169
Opened 2022-06-07 23:17 UTC by tf-4

## About The Pull Request

Blocks the current map from appearing in the map vote

## How This Contributes To The Skyrat Roleplay Experience

Playing a map back to back is generally not great. New players may come in and vote for it while others have to play the same map repeatedly.

## Changelog
:cl:
qol: You can no longer vote for the current map in the end of round map vote.
/:cl:

2022-06-08 00:43 UTC, GoldenAlpharex requested changes
This would probably need some extensive testing to ensure that we don't get into more "democracy" votes than we already do, where only one option is presented.

2022-06-08 00:44 UTC, tf-4 commented
yeah probably

2022-06-08 21:26 UTC, Iamgoofball commented
i love democracy etc.

2022-06-11 23:05 UTC, lessthnthree commented
> This would probably need some extensive testing to ensure that we don't get into more "democracy" votes than we already do, where only one option is presented.

If 

> This would probably need some extensive testing to ensure that we don't get into more "democracy" votes than we already do, where only one option is presented.

With Kilo cut off in highpop and Delta, Blueshift in lowpop, that leaves Meta, Tram, and Icebox that would always be in the vote. So minus the recently played map it shoullllllld always have a minimum of 2 choices. Unless a map is taken out of rotation.

Could add a check so in the event there's only one option, add a 'backup' map or something.

2022-06-12 23:01 UTC, tf-4 commented
this still hasnt been TM'd and needs it

2022-06-13 14:12 UTC, Gandalf2k15 commented
confirmed working

2022-06-13 14:12 UTC, merged