[MODULAR] Yet Another Gun Balance PR, PT.II Revenge of the ammobox
Skyrat-SS13/Skyrat-TG pull request #14196
Opened 2022-06-08 21:36 UTC by RatFromTheJungle

## About The Pull Request
Standardizes all ammo-boxes to use weight_class_normal, as compared to some being /tiny/, and others being bulky, for no discernible reason (usually, the /weaker/ ammo's were bulky, while the better were tiny, letting you carry 7 boxes of makarov ammo in your internals box, but not the 15 damage peacekeeper 9mil)
## How This Contributes To The Skyrat Roleplay Experience
All boxes of ammo are now the same size, and no longer fit in cardboard boxes, to prevent holyshit you could literally carry like 600 rounds in your backpack.

## Changelog

:cl:

balance: All ammo boxes which were previously tiny, or bulky, have been made to the new standard of ambiguously  'normal sized' per corporate regulations.
/:cl:

2022-06-08 21:57 UTC, Zonespace27 requested changes

2022-06-08 21:57 UTC, Zonespace27 commented on modular_skyrat/modules/gun_cargo/code/objects/ammo_boxes.dm
> +obj/item/ammo_box/magazine/
```suggestion
/obj/item/ammo_box/magazine
```

2022-06-08 21:57 UTC, Zonespace27 commented on modular_skyrat/modules/gun_cargo/code/objects/ammo_boxes.dm
> +/obj/item/ammo_box/
```suggestion
/obj/item/ammo_box
```

2022-06-09 14:23 UTC, Draganfrukts commented
I pray every day we ain't ever gotta deal with 
Left Hand: .357 revolver
Right Hand: ammo box (.357)

2022-06-09 14:49 UTC, tf-4 commented on modular_skyrat/modules/sec_haul/code/guns/ammo.dm
> +	w_class = WEIGHT_CLASS_NORMAL
```suggestion
```

2022-06-12 00:33 UTC, Ashrollen commented
Bulky shotgun ammo box? Mhhhm...Feels like trolling.

2022-06-13 13:42 UTC, merged