Removes briefcase of cash from the smuggler satchel loot pool
Skyrat-SS13/Skyrat-TG pull request #14316
Opened 2022-06-14 18:59 UTC by tf-4

## About The Pull Request

Removes the briefcase of cash from the smuggler satchel pool and replaces it with a single 5000 credit bill, as were the contents of the briefcase.

## How This Contributes To The Skyrat Roleplay Experience

Having a briefcase inside a storage item is an oversight and not intended behaviour - if you take it out, you can't put it back in, and it can fit normal-sized (storage) items (like boxes, or BSRPEDs).
Fitting a box, in a briefcase, in a satchel, in a bag (and in a bag of holding, if you have one), is not how bag size and slots are meant to work.

## Changelog
:cl:
fix: The briefcase of cash has been replaced with cash in the smuggler's satchel loot pool.
/:cl:

2022-06-14 19:01 UTC, nevimer commented
this ruins antagingg!! i cant storage my 50 large items in my bag within my bags bag's backpage in my storage implant!! evil!! /s

2022-06-14 23:54 UTC, Elli-Skala commented
Wait tg doesn't have this problem also?

2022-06-15 00:25 UTC, tf-4 commented
> Wait tg doesn't have this problem also?

no it's a modular change

2022-06-17 19:01 UTC, GoldenAlpharex requested changes
One tiny thing, but otherwise, good change.

2022-06-17 19:01 UTC, GoldenAlpharex commented on code/game/objects/items/storage/backpack.dm
> +	var/contraband_list = list(/obj/item/storage/bag/ammo=4, /obj/item/storage/belt/utility/syndicate=1, /obj/item/storage/toolbox/syndicate=7, /obj/item/card/id/advanced/chameleon=6, /obj/item/stack/sp
Can we make this list a bit more human-readable, while you're at it?

2022-06-25 03:48 UTC, GoldenAlpharex approved these changes
Looks good to me.

2022-06-25 21:19 UTC, merged