Adds a couple wearable pelts to the loadout.
Skyrat-SS13/Skyrat-TG pull request #14492
Opened 2022-06-24 08:58 UTC by Ketrai

## About The Pull Request

Adds wearable animal pelts to the loadout.
![image](https://user-images.githubusercontent.com/28861083/175501242-bcd51709-251a-4017-a416-c100826ae2f8.png)
![image](https://user-images.githubusercontent.com/28861083/175501351-6debdad8-326f-4966-8e35-449cf70e9725.png)
![image](https://user-images.githubusercontent.com/28861083/175501458-b862f91c-cb71-4ea4-ae89-e3c2b38d2314.png)

## How This Contributes To The Skyrat Roleplay Experience

More character customization. Look like a savage! Be more difficult to be taken seriously! Make an outrageous fashion statement!

:cl:
add: Added some new wearable pelts to the loadout
/:cl:

2022-06-24 16:59 UTC, Alanii commented
Should name them.

Felinid pelt, vulpkanin pelt, etc.

🤣

2022-06-24 17:00 UTC, Nerev4r commented
Can we get the head part to be togglable like a hood?

2022-06-24 17:47 UTC, Spc-Dragonfruits commented
This is your local spriter  here with sprite advice (and misc)

### You don't really leave the eyes in when skinning an animal as they can't be preserved
![image](https://user-images.githubusercontent.com/51841793/175609762-e64a5441-0257-46cb-8b47-2bd0a3a5b377.png)

### The side perspective gets a bit weird here.
![image](https://user-images.githubusercontent.com/51841793/175609892-728ddf55-0603-4ded-9a7a-019c17fc1ec6.png)
And I suggest doing something like,
![image](https://user-images.githubusercontent.com/51841793/175610054-489049c0-a1c4-4103-88ea-c80e8fab3393.png)
Which makes the ears look aligned

### The regular tiger pelt is quite saturated
![image](https://user-images.githubusercontent.com/51841793/175611737-23de2c0c-ec43-44e3-8147-31ecb3a5a754.png)
Some hue-shifting and a couple of darker colors and it turns out much nicer

### A couple of pelts are very sleepy and fell into a pile of pillows!
![image](https://user-images.githubusercontent.com/51841793/175611937-f9ce75c0-80d0-46b5-b78a-bf292cb699c0.png)
Trying to color huge masses of colors without falling into a pillow shading trap can prove itself difficult sometimes. I'd suggest trying something like this
![image](https://user-images.githubusercontent.com/51841793/175614545-a782b168-4983-458e-b34d-ed8030e3de80.png)
_**DISCLAIMER:** This sprite is meant to be a simplified reference._
You can reduce the number of colors used and darken highlights to attain something similar. Obviously, it entails trying to fill in a couple of details - but shouldn't be too hard.

2022-06-24 22:11 UTC, Ketrai commented
These are older sprites yeah. I can see about touching them up, but it depends how much time I want to spend on this between all my other little projects.

2022-06-25 17:33 UTC, tf-4 requested changes

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	name = "Bear pelt"
```suggestion
	name = "bear pelt"
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	desc = "A luxurious bear pelt, good to keep warm in winter. Or to sleep through winter."
```suggestion
	desc = "A luxurious bear pelt, good to keep warm in winter. Or to sleep through it."
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +/obj/item/clothing/head/pelt/wolfpelt
```suggestion
/obj/item/clothing/head/pelt/wolf
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	inhand_icon_state = "wolfpelt_gray"
```suggestion
/obj/item/clothing/head/pelt/wolf/black
	icon_state = "wolfpelt_gray"
	inhand_icon_state = "wolfpelt_gray"
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +/obj/item/clothing/head/pelt/tigerpelt
```suggestion
/obj/item/clothing/head/pelt/tiger
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +/obj/item/clothing/head/pelt/tigerpeltsnow
```suggestion
/obj/item/clothing/head/pelt/snow_tiger
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +/obj/item/clothing/head/pelt/tigerpeltpink
```suggestion
/obj/item/clothing/head/pelt/pink_tiger
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	name = "Wolf pelt"
```suggestion
	name = "wolf pelt"
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	desc = "A fuzzy wolf pelt, demanding respect as a hunter, well if it isn't synthetic or anything at least. Or bought, for all the glory but none of the credit."
```suggestion
	desc = "A fuzzy wolf pelt that demands respect as a hunter... assuming it wasn't just purchased, that is, for all the glory but none of the credit."
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	name = "Shiny tiger pelt"
```suggestion
	name = "shiny tiger pelt"
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	name = "Snow tiger pelt"
```suggestion
	name = "snow tiger pelt"
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/aesthetics/clothing/clothing.dm
> +	name = "Pink tiger pelt"
```suggestion
	name = "pink tiger pelt"
```

2022-06-25 17:33 UTC, tf-4 commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_heads.dm
> +	item_path = /obj/item/clothing/head/pelt/tigerpeltpink
```suggestion
/datum/loadout_item/head/bearpelt
	name = "Brown Bear Pelt"
	item_path = /obj/item/clothing/head/pelt

/datum/loadout_item/head/bearpeltblack
	name = "Black Bear Pelt"
	item_path = /obj/item/clothing/head/pelt/black

/datum/loadout_item/head/wolfpelt
	name = "Brown Wolf Pelt"
	item_path = /obj/item/clothing/head/pelt/wolfpelt

/datum/loadout_item/head/wolfpeltblack
	name = "Black Wolf Pelt"
	item_path = /obj/item/clothing/head/pelt/wolfpeltblack

/datum/loadout_item/head/tigerpelt
	name = "Shiny Tiger Pelt"
	item_path = /obj/item/clothing/head/pelt/tigerpelt

/datum/loadout_item/head/tigerpeltsnow
	name = "Snow Tiger Pelt"
	item_path = /obj/item/clothing/head/pelt/tigerpeltsnow

/datum/loadout_item/head/tigerpeltpink
	name = "Pink Tiger Pelt"
	item_path = /obj/item/clothing/head/pelt/tigerpeltpink
```

2022-06-26 17:23 UTC, theselfish commented
Considering these mention winter. Shouldn't they have some cold protection?

Also, I'd like to say while I agree with the rest of Dragon's post. I say keep the eyes. Rule of Cool and such.

2022-07-01 18:50 UTC, Ketrai commented
![image](https://user-images.githubusercontent.com/28861083/176953750-d7d6c829-9ab8-44d7-ac3f-f0980e5ad2cc.png)

Updated bear and tiger sprites. Also fixes the wolf sprite side state ears. Eyes remain, I just like that aesthetic more. I unno, maybe the hunter put in fake eyes for effect!

2022-07-10 18:06 UTC, tf-4 approved these changes

2022-07-12 21:22 UTC, merged