Resprites Latex Items + New additions
Skyrat-SS13/Skyrat-TG pull request #14527
Opened 2022-06-26 03:07 UTC by StrangeWeirdKitten

## About The Pull Request

Resprites various latex shoes, catsuits, and gloves. Adds the high heels to GAGs and adds a new pair of heels.

Atomizes this PR. #14522

## How This Contributes To The Skyrat Roleplay Experience

#14522

## Changelog

:cl:
add: High Heels are now added to GAGs
add: Black heels are added into the loadout
add: Latex bra, panties, and socks are added to the underwear menu.
balance: Corset and Chaps are no longer ludicriously expensive
fix: Colourable cloth wraps now show color on digigrade species.
imageadd: New Various Latex Sprites
/:cl:

2022-06-26 04:47 UTC, Zonespace27 commented on modular_skyrat/modules/GAGS/greyscale_configs.dm
> +/datum/greyscale_config/wraps/worn/digi
```suggestion

/datum/greyscale_config/wraps/worn/digi
```

2022-06-26 13:18 UTC, Jolly-66 commented
If you added/updated any new clothing sprites, it's common practice to include them in your PR so we may see what they look like on players 

I would recommend putting them in a spoiler so it doesn't make your PR body long (of course, assuming there isn't a lot of changes, and you can always do multiple in one screenshot)

2022-06-26 19:50 UTC, StrangeWeirdKitten commented
> If you added/updated any new clothing sprites, it's common practice to include them in your PR so we may see what they look like on players
> 
> I would recommend putting them in a spoiler so it doesn't make your PR body long (of course, assuming there isn't a lot of changes, and you can always do multiple in one screenshot)

I had all the screen shots listed in the linked PR. Do you want actual in game screen shots of the various items?

2022-06-26 20:08 UTC, Jolly-66 commented
> Strange said something 

Ah, I didn't see that PR originally, apologies.

I'm no spritetainer nor is it my realm to exercise my hand, but it would be beneficial to have in-game screenshots.

Please feel free to do whatever with what I said. Ultimately, it's up to you and not me here, but would be appreciated no less!

2022-06-29 00:13 UTC, StrangeWeirdKitten commented
Taur sprites are broken outside of this PR. So I made a bug report. But the sprites overall will exist if style_taur_all works again.

2022-06-29 21:27 UTC, GoldenAlpharex requested changes

2022-06-29 21:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/shoes/shoes.dm
> +	icon_state = "highheels"
We typically always put `name` and `desc` first, and try to basically put the long variables lower than the short ones, when possible, to make easier to read through.
```suggestion
	name = "black heels"
	desc = "A pair of black high heels that are much smaller on your feet"
	icon_state = "highheels"
	icon = 'modular_skyrat/master_files/icons/obj/clothing/shoes.dmi'
	worn_icon = 'modular_skyrat/master_files/icons/mob/clothing/feet.dmi'
```

2022-06-29 21:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/shoes/shoes.dm
> +	body_parts_covered = TRUE
Are you sure this is a TRUE/FALSE kind of variable, and not a flag-based variable (which I suspect it is)?

2022-06-30 15:03 UTC, merged