[Modular] Adds some text to internals HUD button for additional support for lungs
Skyrat-SS13/Skyrat-TG pull request #14659
Opened 2022-07-01 03:09 UTC by nevimer

## About The Pull Request

Did you know vox only require 10KPA, but their internals start at 16kpa? Neither did I until I was testing this.
This PR adds a new HUD element over the internals hud, it tells you information about your last breath of atmosphere. 

This does not show up for synthetics or pirates, as they do not breathe. 

## Ash Walker
![dreamseeker_ufC3QoN9IW](https://user-images.githubusercontent.com/77420409/176815577-a65b6814-076e-4ae4-80a5-c31cfe855041.png)

## Vox
![dreamseeker_52VPpJtUgA](https://user-images.githubusercontent.com/77420409/176815623-ac774e6a-f85c-40a3-8016-d887d8645d7c.png)

https://user-images.githubusercontent.com/77420409/176815719-2c29cc32-c9d8-4999-96ad-4cc99d8a1ec8.mp4

## How This Contributes To The Skyrat Roleplay Experience

We got a lot of lung options, breathing modifiers, and theres really no way to tell your status unless you either code dived or became a robust knowledge gamer. This lets people have a bit more sensory emulation. 

## Changelog

:cl:
qol: adds a HUD for lungs
balance: You can now see your last breaths KPA 
/:cl:

2022-07-01 19:16 UTC, GoldenAlpharex requested changes
I'm still honestly not sold on this. I'd rather have a text that told me how much KPa was left in my internals, than the pressure it's being released at (because that's the information that's currently displayed in the stat panel anyway).

I'm still really not a fan of being able to know innately what your ideal intake pressure is, that should be obtainable through some different means, and is completely useless information as soon as you know it.

Furthermore, the second functionality of this seems really wrong, you shouldn't be able to tell the pressure of the room accurately by just breathing in it, that's the point of using an analyzer.

2022-07-01 19:16 UTC, GoldenAlpharex commented on modular_skyrat/modules/lungs_hud/internals.dm
> +/mob/living/carbon/proc/internals_text_update()
Document this proc

2022-07-01 19:16 UTC, GoldenAlpharex commented on modular_skyrat/modules/lungs_hud/internals.dm
> +		internal_hud?.maptext = MAPTEXT("<span style=\"font-size:5px\">LAST KPA:\n[pressure]\n</span>")
What happens if they haven't breathed in yet?

Also, you said that it doesn't display for those without lungs, but I don't see any code supporting that.

2022-07-01 19:16 UTC, GoldenAlpharex commented
Plus, this is more like something that would be much better off taken upstream instead of being done modularly here.

2022-07-01 21:13 UTC, Gandalf2k15 commented
I'm with golden apples, a remaining KPA gaugewould be far superior

2022-07-02 02:14 UTC, Gandalf2k15 commented
re-open with changes if upstream does not accept

2022-07-02 02:14 UTC, closed without merging