[Modular] Adds Pencilskirts As A Loadout Option.
Skyrat-SS13/Skyrat-TG pull request #14710
Opened 2022-07-03 20:35 UTC by Jureiia

## About The Pull Request
Adds the pencilskirts from PR: #14491 to the loadout under the formal suits section.

## How This Contributes To The Skyrat Roleplay Experience
These outfits look great, would let more people use them easier.

## Changelog

:cl:
add: Pencilskirts added as an option in the loadout.
/:cl:

2022-07-03 21:13 UTC, OrionTheFox commented
God bless, I saw that the loadout was a mess and it totally put me off of doing this. Thanks for getting it for me

2022-07-03 22:13 UTC, tf-4 requested changes

2022-07-03 22:13 UTC, tf-4 commented on modular_skyrat/modules/loadouts/loadout_items/under/loadout_datum_under.dm
> +/datum/loadout_item/under/formal/pencil/green/
```suggestion
/datum/loadout_item/under/formal/pencil
	name = "Black Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil

/datum/loadout_item/under/formal/pencil/black_really
	name = "Executive Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil/black_really

/datum/loadout_item/under/formal/pencil/charcoal
	name = "Charcoal Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil/charcoal

/datum/loadout_item/under/formal/pencil/navy
	name = "Navy Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil/navy

/datum/loadout_item/under/formal/pencil/burgandy
	name = "Burgandy Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil/burgandy

/datum/loadout_item/under/formal/pencil/checkered
	name = "Checkered Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil/checkered

/datum/loadout_item/under/formal/pencil/tan
	name = "Tan Pencilskirt"
	item_path = /obj/item/clothing/under/suit/skyrat/pencil/tan

/datum/loadout_item/under/formal/pencil/green
```

2022-07-04 01:38 UTC, tf-4 approved these changes

2022-07-05 03:59 UTC, merged