[MODULAR] Allows mute, foreign and no gun quirkholders to sign up for security jobs
Skyrat-SS13/Skyrat-TG pull request #14762
Opened 2022-07-06 22:51 UTC by theOOZ

## About The Pull Request

Having mute, foreign or the no gun quirk disqualifies you from playing as a security officer, this PR changes that.

## How This Contributes To The Skyrat Roleplay Experience

These three are needless limitations in my view, no guns and foreigner mostly; however I think even a mute security officer could pass with TTS/sign language.

I think a well roleplayed security member could act well enough with any one of these for them not to have to be so restricting, a mute officer has the aforementioned, a foreign officer can have another common language like draconic/nekomimetic (or play hard difficulty and pick an uncommon language), and a no gun officer just uses their baton/bola/flash.

## Changelog

:cl:
balance: Allows mute, foreign and no gun quirkholders to sign up for security jobs
/:cl:

2022-07-06 22:53 UTC, tf-4 commented
Two of these are quirks that mechanically inhibit someone's ability to roleplay, we should not be discouraging it in security
No guns is arguably *worse* than pacifist.
Not keen on any of these

2022-07-06 22:57 UTC, Zonespace27 requested changes
Mute's the only one i don't really caring about blocking sec since in the end it just prevents you from using runechat + using tacklers, albeit this can very easily be an issue if they choose to take anything *but* signing gloves

Foreign is a hard no, i'd rather be able to actually talk with the officer arresting me + it makes communicating with the team a pain

No guns is pretty bad because it makes you a liability who can be foiled by an antag backpedaling with anything ranged

2022-07-06 23:05 UTC, Nerev4r commented
I don't agree with No Guns being barred. If people want to disadvantage themselves, I don't get why we shouldn't allow them. Especially given how much bolas/a baton/a telescopic shield together can do.

2022-07-06 23:29 UTC, Moostard commented
Considering security should work as a team, having people join the department to be a liability is funny in a bad way.
If people want to disadvantage themselves, they should not disadvantage the entire department and make it painful for others.

2022-07-06 23:31 UTC, Nerev4r commented
> Considering security should work as a team, having people join the department to be a liability is funny in a bad way. If people want to disadvantage themselves, they should not disadvantage the entire department and make it painful for others.

There are seven, at the very least five other Officers, two Detectives, and a Head of Security that can pick up the extremely light amount of slack an Officer that never uses guns creates.

2022-07-07 00:20 UTC, RimiNosha commented
I'll weigh in with my mute+tongue-tied gameplay experience-

If you're running tongue-tied, mute is practically inconsequential, but by itself, it's crippling and makes you unable to do even basic communication over comms without being inventive, so take that as you will. TTS devices are clunky, and absolutely do not pass as a viable alternative to speech for a sec officer.

If we're on about tongue-tied instead of mute though, tongue tied should absolutely be allowed, it adds personal challenge without screwing over the rest of sec, provided said person doesn't swap out their gloves!

2022-07-07 02:38 UTC, Iamgoofball commented
@Zonespace27 There is a large variety of ranged weapons that are not guns, and players that want to play characters that don't use guns will simply not use guns.
https://www.youtube.com/watch?v=NzwRTXBRS2g

2022-07-07 03:54 UTC, tf-4 commented
> I'll weigh in with my mute+tongue-tied gameplay experience-
> 
> If you're running tongue-tied, mute is practically inconsequential, but by itself, it's crippling and makes you unable to do even basic communication over comms without being inventive, so take that as you will. TTS devices are clunky, and absolutely do not pass as a viable alternative to speech for a sec officer.
> 
> If we're on about tongue-tied instead of mute though, tongue tied should absolutely be allowed, it adds personal challenge without screwing over the rest of sec, provided said person doesn't swap out their gloves!

tongue-tied is already allowed, and is fine

2022-07-08 04:46 UTC, closed without merging