[NON-MODULAR] Remove Monkey and piratespeak from the language menu
Skyrat-SS13/Skyrat-TG pull request #14864
Opened 2022-07-11 23:24 UTC by SarmentiCampbell

## About The Pull Request
gatto

## How This Contributes To The Skyrat Roleplay Experience
gatto

## Changelog

:cl:
balance: station crew is no longer able to speak monkey and piratespeak.
/:cl:

2022-07-11 23:28 UTC, theOOZ commented
Keep monkey in or face my wrath.

2022-07-11 23:34 UTC, tf-4 commented
On my request

2022-07-12 03:01 UTC, magatsuchi commented
desouling

2022-07-12 03:40 UTC, theOOZ commented
monkey is not a meme language or a game impacting language. if people are taking it as “meme” then finally crack down on the amount of languages we can have. we have TWO WHOLE BONUSSES. i dont even fill those on most my characters. complete miss PR

2022-07-12 03:54 UTC, Iamgoofball commented
keep monkey in, this breaks my character

2022-07-12 03:56 UTC, Iamgoofball commented
if you want to claim that monkey and/or piratespeak is a "meme" so is bright neon glow in the dark wolf furries but nobody's out here calling them a meme

2022-07-12 03:58 UTC, Iamgoofball commented
additionally, piratespeak is accessible via the crew anyways via wearing a pirate hat from the autodrobe, of which there are several

2022-07-12 04:01 UTC, theOOZ commented
> keep monkey in, this breaks my character 

ditto

2022-07-12 07:45 UTC, Iamgoofball commented
in retrospect, someone brought up that piratespeak's accessibility via the hat requires you to forego space proofing, which i agree with as a balance idea

:+1: on removing pirate, :-1: on removing monkey

2022-07-12 08:37 UTC, Jezzared commented
We still have curators to translate piratespeak anyhow. If pirates are speaking over public comms crew will understand them anyways, and if they've got a pirate's headset the pirates already have bigger issues.

2022-07-12 08:44 UTC, Zonespace27 approved these changes
I approve the pirate removal and I don't care if monkey language exists or stays

2022-07-20 02:33 UTC, GoldenAlpharex requested changes

2022-07-20 02:33 UTC, GoldenAlpharex commented on code/modules/language/piratespeak.dm
> +	secret = TRUE // SKYRAT EDIT
Just add that in a modular file, by just doing this:
```
/datum/language/piratespeak
    secret = true```

I don't remember by heart what kind of files we already have for languages, but you should modularize this, there's no reason it's not modular.

2022-08-03 00:37 UTC, Gandalf2k15 approved these changes

2022-08-04 15:03 UTC, merged