[SEMI-MODULAR] Ghostrole Cryo Announcements!
Skyrat-SS13/Skyrat-TG pull request #14901
Opened 2022-07-14 20:25 UTC by RimiNosha

## About The Pull Request
So, this adds in one new announcement, and slightly changes up how cryo announcements work in general:

- The cryo computer now has it's own announcement radio, which is *important* if we want ghost role announcements!
- The cryo computer can be configured with custom headsets and to use a custom channel!
- Tarkon, DS2 and Interdyne ghost roles now have cryo ***wake up*** and sleep announcements!
- `announcement_system.dm` is no longer touched by any changes as a result!
- Ghost roles also now get general records for use in cryo announcements- I didn't find any player facing uses for general records, so I think this is safe!
<details>
<summary>Images!</summary>
![](https://cdn.discordapp.com/attachments/640760727489085450/997231571067224244/unknown.png)  
![](https://cdn.discordapp.com/attachments/640760727489085450/997231571482447883/unknown.png)  
![](https://cdn.discordapp.com/attachments/640760727489085450/997231571285323947/unknown.png)  
![](https://cdn.discordapp.com/attachments/640760727489085450/997231571696369856/unknown.png)  
![](https://cdn.discordapp.com/attachments/640760727489085450/997231571927060623/unknown.png)  
![](https://cdn.discordapp.com/attachments/640760727489085450/997231572128370729/unknown.png)
</details>

## How This Contributes To The Skyrat Roleplay Experience
Knowing when your fellow Tarkon/Syndie crewmembers wake up and go to sleep is really nice!

## Changelog

:cl:
add: Port Tarkon, Interdyne and DS-2 now have cryo wake up and sleep announcements.
code: Cryo announcements no longer use the Automated Announcement System.
code: Ghost roles that cryo will have their ghost role name in the cryo message.
/:cl:

2022-07-14 20:30 UTC, RimiNosha commented
Oh boy, here we go, github's image syntax isn't what it's documented to be!

2022-07-14 20:50 UTC, Zonespace27 requested changes

2022-07-14 20:50 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
>  /obj/machinery/computer/cryopod/Destroy()
make sure to del and null the headset in Destroy()

2022-07-14 20:50 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	var/announcement_channel = RADIO_CHANNEL_COMMON
code doc this var

2022-07-14 20:50 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	radio = new radio(src)
```suggestion
	radio = new (src)
```
should work

2022-07-14 20:50 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	// For figuring out where the local cryopod computer is. Must be set for cryo computer announcements.
```suggestion
	/// For figuring out where the local cryopod computer is. Must be set for cryo computer announcements.
```

2022-07-14 20:50 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	return null
```suggestion
/obj/effect/mob_spawn/ghost_role/proc/find_control_computer()
	if(!computer_area)
	    return
	for(var/cryo_console as anything in GLOB.cryopod_computers)
		var/obj/machinery/computer/cryopod/console = cryo_console
		var/area/area = get_area(cryo_console) // Define moment
		if(area.type == computer_area)
			return console
```

2022-07-14 20:50 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +			if(area.type == computer_area)
why not `istype`?

2022-07-14 20:51 UTC, RimiNosha commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
>  /obj/machinery/computer/cryopod/Destroy()
Oh yea, woops-

2022-07-14 20:58 UTC, RimiNosha commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	radio = new radio(src)
Nope, that'll instantiate `/obj/item/radio`, unless the brackets change that!

2022-07-14 20:59 UTC, Zonespace27 commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	radio = new radio(src)
Yeah, good point, am goof

2022-07-14 21:07 UTC, RimiNosha commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +			if(area.type == computer_area)
Istype does subpaths. I do not want it to match subpaths!

2022-07-17 00:52 UTC, Zenitheevee commented
So, Bit sorry about rushing for my previous PR to get rushed in.
But uh, It _is_ worth keeping in mind that the cryo-consoles have Access requirements to draw items out.
Would you mind putting them within the modularized consoles so they're no longer needed to be Var-Edited?

2022-07-17 03:46 UTC, RimiNosha commented
I thought I did that- fixed!

2022-07-17 03:50 UTC, RimiNosha commented
I'm also half-tempted to make cryo computers not require power at all- it'd make the start of Tarkon, when folk are spawning in and potentially cryoing out the most much easier to track. 

Also good if the main station runs out of power, cause it's common for folk to have to go pretty urgently and not have time to spend waiting on a shuttle that may or may not come due to a depowered console-

Which now that I think about it, might be my next PR, cause it glows in the dark, but becomes depowered along with the station despite still glowing- one of the two have to change, whether it doesn't require power, or it requires power and doesn't glow when depowered-

2022-07-17 04:03 UTC, Zenitheevee commented
> I'm also half-tempted to make cryo computers not require power at all- it'd make the start of Tarkon, when folk are spawning in and potentially cryoing out the most much easier to track.
> 
> Also good if the main station runs out of power, cause it's common for folk to have to go pretty urgently and not have time to spend waiting on a shuttle that may or may not come due to a depowered console-
> 
> Which now that I think about it, might be my next PR, cause it glows in the dark, but becomes depowered along with the station despite still glowing- one of the two have to change, whether it doesn't require power, or it requires power and doesn't glow when depowered-
> 
> Edit: 👍 for not requiring power for cryo consoles, 👎 for requiring power, for easy opinion measurement!

Generally speaking, The start of tarkon is a bit hard and thats an understandable thing, Especially when its required items like, i dunno, The modsuits, all guns and the only space suit thats guaranteed before xenos.
While i dont think there *has* been any really bad cases of griefing, One step forward is better than punishing someone because we're one step back.

2022-07-20 19:08 UTC, Jolly-66 approved these changes
Map edits are simple and simply QoL which this PR adds.

2022-07-22 22:46 UTC, jjpark-kb commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	computer_area = /area/ruin/syndicate_lava_base/dormitories // SKYRAT EDIT ADDITION - Announce cryo wake-ups!
needs to be modular.

2022-07-22 22:46 UTC, jjpark-kb commented on modular_skyrat/modules/cryosleep/code/cryopod.dm
> +	if(message_type == "CRYO_LEAVE")
switch statement here.

2022-07-29 17:16 UTC, merged