[MODULAR] Remaps the Central Command Dock and Emergency Shuttle to resolve major egress and pathing issues.
Skyrat-SS13/Skyrat-TG pull request #14938
Opened 2022-07-16 23:47 UTC by Iamgoofball

## About The Pull Request

### Central Command:

Central Command's receiving dock for Emergency Shuttles has been remapped again to accommodate Skyrat's player volume while still discouraging EORG thunderdoming.

![dreamseeker_dfmSgMMxpG](https://user-images.githubusercontent.com/4081722/179375148-4ed7d8bf-38a5-4ab3-9e16-72089928dc1f.png)
*pictured: The entrance area. Mural stolen from Interlink.*

If you head up, you can access the Security Holding Cell. Security can drop prisoners off here and they can chat with people at visitation.
![dreamseeker_tpP9B2Yt00](https://user-images.githubusercontent.com/4081722/179375177-ea9a9e0a-3e41-476f-b4cb-0315c1ec99c8.png)
*pictured: An old escape attempt that failed.*

If you head down, you can get to the Emergency Medical Clinic. Medical can ferry patients into it off the shuttle.
![dreamseeker_ieyJwKwbGW](https://user-images.githubusercontent.com/4081722/179375191-5e56a2c3-679e-4f5c-8c75-9a1644f49383.png)
*pictured: A patient standing confused in the clinic waiting area.*

Otherwise, you can head forward after disembarking to reach the main waiting area with a beautiful garden, or you can stop by the smoking stop while waiting for the next shuttle.
![dreamseeker_w24YYdadMW](https://user-images.githubusercontent.com/4081722/179375230-e87b9d8c-052c-426c-93ce-0a719cda58da.png)

### Default Skyrat Emergency Shuttle:
The default Skyrat Emergency Shuttle has swapped the locations of the Brig and Medbay on the shuttle. This allows the job where every second matters(medical) to get on and off the shuttle with stretchers without getting stuck in the rest of the crew's traffic on and off of the shuttle. Every second matters in medical because it's a literal life or death situation, and it's absurd that Medical was shoved to the far back of the shuttle despite being the most likely department to need onto the shuttle as fast as possible and with time sensitive job materials(dying patients).
![dreamseeker_BjS1S848GP](https://user-images.githubusercontent.com/4081722/179375017-3bd36ca1-0fed-4e86-8aa5-406fcc7ef87a.png)
*pictured: my characters as actors for ambiance*

Additionally, Security being at the bottom of the shuttle and the Crew entrance being at the top caused massive egress problems for the crew boarding the shuttle. Did you know Meta is the only station where the crew can use both of the general access crew doors on the escape shuttle to get on board the shuttle, as pictured below? Because of the Skyrat escape shuttle being inverted from the /tg/ standard, crewmembers trying to board on Kilo, Tram, Box, and Delta found that 1 of their doors was in the security checkpoint area, two of the public doors led to the Brig section of the shuttle and thus couldn't be used for general crew boarding and disembarking, and the third door was the only usable one?

### Chad Metastation
![StrongDMM_HN0QhRUrhi](https://user-images.githubusercontent.com/4081722/179375121-69d3a61f-da4c-4c2e-8e8d-5cafec5f68b4.png)

### Virgin Icebox:
![StrongDMM_cYXgaEBbyW](https://user-images.githubusercontent.com/4081722/179375133-11970e8c-7157-4068-ac00-8736b9ddc097.png)

By rotating Medical and Security on the Emergency Shuttle, the crew has 3x as many doors to board from on just about every map, and Medbay can get directly into their area during boarding and disembarking.

This isn't the ideal solution, I know, but since Security frankly isn't that important to justify having such priority access to shuttle boarding and disembarking, and the shuttle geometry can't be redesigned due to the sprites utilized in the shuttle's visual design, this is the best solution to the problem for now.

### Blueshift Tweak:
The second highest docking door on Blueshift's escape has had the security access helpers removed to fit the standard of the rest of the maps in the repository, and to ensure proper crew docking access when alternative shuttles are purchased.

## "What's wrong with the current CC map?"

before going into this, i want to clarify that virtual bodies tend to need way more space than real people to move around, especially as population density runs higher and skyrat has very high population density, a good 60-70 people are gonna be coming out of the emergency shuttle assuming most crewmembers happened to board the shuttle that shift, the lowest escape I've seen in a normal round is like 30-40, which is still a very large amount of spacemen

![byond_ecaUxp7UqM](https://user-images.githubusercontent.com/4081722/179374923-5f2e9997-f292-4187-a83c-3ff543b0409f.png)

as of this screenshot skyrat had over 122 connected players, which is a lot of potential escapees.

Let's take a look at the current Central Command Escape Dock with this handy diagram.
![Xp74](https://user-images.githubusercontent.com/4081722/179374890-56e445c2-76bc-43be-9ea0-5551f08551c5.png)

It's obvious that the design intention was to discourage thunderdoming by making the area no longer a literal arena to throw down in. However, this goes a bit too far and accidentally decimated the area's ability to handle the primary goal of a CC dock; receiving large amounts of spacemen at once and filtering them to where they need to go.

1. The arrows show players disembarking and the path they're going to take to get into the queue, spacemen tend to path by running in a straight line in a direction until they hit something and that's going to result in a lot of people running face first into these windows, with people following closely behind them resulting in a ton of swaps/pushes by combat mode people. Then they're going to run into the opposite traffic lane trying to get to the nearest queue to them, and then they're going to be stuck dealing with the queue.

2. Before we get to why the queue is a problem, the security exit getting 50% of the space despite holding, at most, 5% of the shuttle's occupants is going to result in a massive overcrowding at the top two exit doors, this is already an issue on Skyrat's core shuttle but is alleviated by the vanilla /tg/ dock being completely open so the crowding is easily relieved immediately upon exiting the shuttle. That won't be the case with this design, where they will continue to be crowded at every step of the process all the way until they've made it through the entire room.

3. The queue itself, highlighted with a red circle. It's a single tile hallway split into two with guard rails that is a curvy switchback system. Note that we've already identified that spacemen path best in straight lines, and this queue throws that on it's head and laughs at it. People are going to get stuck here until they perfect their tf2 scout figure eight style button presses to get through the queue optimally, and the 1x1 nature of it is going to result in a lot of people rest crawling through. A good comparison is when the Crab 17 ends up in a 2x2 room and 85% of the crew is trying to swipe their ID. Picture that, and then picture how this room will look packed with 70 people entering at once.

4. The filler rooms, as highlighted with the red squares. For a room that 70 people are all going to be trying to get through at once, why is nearly 33% of it dead space they can't access with no actual reason to exist? This should be built into the wall at the doors, not blocking and funneling people into the badly designed queues.

Overall, this map makes sense for a layout for a space real human beings exist in, but absolutely no sense for a SS13 map's layout filled with SS13 spacemen operated by players who exist in a tile based society, and definitely doesn't make sense for a room that 70 people or more are going to be filing into at once.

Not every crewmember is going to escape via the shuttle, but considering the volume of players Skyrat gets, it's good to be prepared, especially if EORG is being removed. A good disembarking area helps avoid annoyed players and helps prevent fights from starting from so many spacemen bumping elbows in such a confined space.
 [...]

2022-07-17 06:09 UTC, theselfish commented
I think the intent with the red boxes was some sort of 'bag checking' system. Like a ghost role.

But without a spawner it's just swapping places sim, yes.

2022-07-17 06:54 UTC, OrionTheFox commented
Atomize it, the CC change shouldn't be in the same PR as the shuttle change

2022-07-17 12:23 UTC, Iamgoofball commented
@OrionTheFox The shuttle change complements the redesigned CC, if you notice where the medbay and security areas line up with the medical and crew doors.

2022-07-17 21:16 UTC, Gandalf2k15 commented
bro
agh
why we making non modular changes to CC

2022-07-17 21:32 UTC, Iamgoofball commented
this is the specific skyrat centcom override since centcom has to be compiled in

2022-07-20 12:51 UTC, Jolly-66 requested changes
Two things.

Atomize out the shuttle and BlueShift changes.

Also please condense your PR body down, use markdowns spoilers.

2022-08-04 15:05 UTC, Gandalf2k15 commented
re-open with changes made to the correct automapper files instead of the core files

2022-08-04 15:05 UTC, closed without merging