EORG teleport
Skyrat-SS13/Skyrat-TG pull request #15051
Opened 2022-07-19 16:57 UTC by Kush1Push1

## About The Pull Request

Added option in game preferences, which in toggled state teleports players after emergency shuttle's docking to Central Command in the thunderdome.

### How it works

1) Emergency shuttle undocks from the station. The game checks if EORG config is toggled on (which can be changed in config file or by admins in server tab). 
Players will recieve a message about coming round-end event and their current status of EORG preference. If a text at end of the message will be clicked, their status will be changed (be/not be at EORG).
2) After the shuttle's docking with CC, there will be the teleportation of all players. If the EORG config is still on and a player still has the preference, they will be moved to thunderdome.
3) All wounds and restrains will be removed.
4) Their gear will be deleted and replaced with one of random presets (so there is no point to prepare for EORG).
5) All EORG banned players are still in rotation to marked zone.

## How This Contributes To The Skyrat Roleplay Experience

EORG can be a thing for players who wish to have it. After all, everyone want to fight in this game from time to time. Anyone else will have their round end at central command/their respected areas.

## Changelog

:cl: SishTis
add: Added EORG teleportation option in character setup's game preferences. In toggled state it teleports a player to thunderdome after round end. Admins also have a button in Server's tab to disable it for some events.
/:cl:

2022-07-19 17:08 UTC, twilightwanderer commented on code/modules/shuttle/emergency.dm
> +				//SKYRAT ADDITON BEGIN
It is better not to forget to specify a link to the module.
```
bolt_all_doors() //SKYRAT EDIT ADDITION
//SKYRAT EDIT ADDITION BEGIN - EORG MODULE
INVOKE_ASYNC(GLOBAL_PROC, /proc/process_eorg_announce)
//SKYRAT EDIT ADDITION END - EORG MODULE
```

2022-07-19 17:18 UTC, Zonespace27 requested changes

2022-07-19 17:18 UTC, Zonespace27 commented on modular_skyrat/modules/eorg/eorg.dm
> +	var/list/EORG_outfits = list(\
make these static lists

2022-07-19 17:18 UTC, Zonespace27 commented on modular_skyrat/modules/eorg/eorg.dm
> +		if(eorg_player.ckey)
early continue

2022-07-19 17:18 UTC, Zonespace27 commented on modular_skyrat/modules/eorg/eorg.dm
> +		if(eorg_candidate.client)
early continue

2022-07-19 17:18 UTC, Zonespace27 commented on modular_skyrat/modules/eorg/eorg.dm
> +		return
does nothing

2022-07-19 17:18 UTC, Zonespace27 commented on modular_skyrat/modules/eorg/eorg.dm
> +			if(eorg_player.client?.prefs?.read_preference(/datum/preference/toggle/eorg_join))
early continue

2022-07-19 17:18 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/skyrat/eorg_join.tsx
> +  name: 'Round End Grief participating',
```suggestion
  name: 'End Of Round Grief Participation',
```

2022-07-19 18:23 UTC, Iamgoofball commented
Why not just sign them up for CTF instead?

2022-07-19 20:11 UTC, weesnaw-ops commented
> Why not just sign them up for CTF instead?

while i would normally agree ctf just isnt the same as beating the shit out of people in a bloody mess

2022-07-19 20:31 UTC, Aether217 commented
It has been discussed in the past and the thunderdome will remain for staff to test things only.

Also, this more or less does nothing than bring back staff having to police eorg prep again.

2022-07-19 20:51 UTC, Gandalf2k15 commented
No, we will not be having any EORG teleporting either. That's what CTF is for.

2022-07-19 20:51 UTC, closed without merging

2022-07-19 21:09 UTC, ArdentSpark commented
They don't have to police EORG prep because their gear is deleted
[Their gear will be deleted and replaced with one of random presets (so there is no point to prepare for EORG).]

2022-07-19 21:39 UTC, theselfish commented
> Also, this more or less does nothing than bring back staff having to police eorg prep again.

![image](https://user-images.githubusercontent.com/102828457/179853167-f74b6181-700e-4ab2-9e59-664a96b639a1.png)

2022-07-20 01:06 UTC, GuiltyNeko commented
If they got teleported to CTF instead of the thunderdome, it'd be less bad and solve the "thunderdome is for admins" issue, and if their gear is deleted as mentioned, prepping means nothing.

2022-07-20 03:39 UTC, YakumoChen commented
just make a CTF button you can press at round end that automatically signs you up and teleports you to one of the random CTF beacons

2022-07-20 12:00 UTC, Kush1Push1 commented
I'll fix the issues and reopen it.

2022-08-23 14:53 UTC, hugmeorelse commented
@Zonespace27 This should have been closed and rejected as per discussion.

2022-08-23 14:54 UTC, hugmeorelse commented
@Zonespace27 I believe you should have notified staff before requesting changes, because this PR would have never been accepted.