adjusts the departmental guards supervisors + description a  bit.
Skyrat-SS13/Skyrat-TG pull request #15136
Opened 2022-07-23 01:49 UTC by capsaicinz

## About The Pull Request

flatout saying that you shouldn't be reporting to security in the job description isn't the best idea, i think, especially with some issues i've seen. while these guards don't listen to security for orders, they should still be encouraged to work together when it comes to reporting criminals, and handing in detained ones.

the wiki does a great job of explaining this! i just thought the way it was laid out in-game wasn't the best.

## How This Contributes To The Skyrat Roleplay Experience

makes the cooperation between guards and security a little clearer.

## Changelog

:cl:
spellcheck: departmental guards no longer report to **NOT SECURITY** as a supervisor, and are instead told to merely cooperate with them.
/:cl:

2022-07-23 03:29 UTC, Iamgoofball commented
:-1:
they explicitly do not report to security and do not follow orders from security unless it is a situation where the entire station is following security orders(ie. amber or red)

2022-07-23 03:33 UTC, capsaicinz commented
> 👎
> they explicitly do not report to security and do not follow orders from security unless it is a situation where the entire station is following security orders(ie. amber or red)

surprising nobody, you’ve completely misinterpreted. nowhere does it state that they are to report to security. they’re not a security job, and the second the round begins, you’re explicitly told you listen to the head of your department. what i’ve done is state what’s already in the wiki: that you’re not just there to tell security to fuck off because you don’t have to listen to them at all (according to the current state,) and your best interest is cooperation. they’re not immune to security.

i beg you, read the pr. all you’ve done is “thumbs down emoji” and then just gave the same essential message this pr already gives.

2022-07-23 03:38 UTC, Iamgoofball commented
sorry its a reflex action

2022-07-23 03:43 UTC, capsaicinz commented
it's a fair concern. i personally think it's clear enough that these guys aren't security, and i just thought that the "supervisors: **NOT SECURITY**" definitely gave the wrong message. the message should be that, while you're absolutely not subservient to security, you're still highly encouraged to work with them when you can, and that you're not thusly immune to them.

as for the wiki page, here: https://wiki.skyrat13.tk/w/index.php/Departmental_Guards

the security policy also has a section on this: https://docs.google.com/document/d/e/2PACX-1vS7mkMFjbN1jColKJMwbh0ctJzFgsfsKFItPK2XIKLA7SCid_5PpiYpMaCjLWRpE6mMIeQHCZqSPXy5/pub

if people suspect it to be too confusing, what should probably be done to supplement is make a message similar to the one you get when using an alt. job title to explain it in brief.

2022-07-23 03:45 UTC, Iamgoofball commented
``You are not given a disabler, a gun or a gun permit for a good reason, because you are not intended to have one as a civilian department guard. This means that you should not arm yourself with handguns, rifles or similar without good reason such as emergencies.``

guncargo moment

2022-07-23 11:39 UTC, tf-4 commented
removing the "NOT SECURITY" part is fine I think, but adding "work with security" is pushing it too far in the other direction. It should just not mention security.

2022-07-24 19:01 UTC, Zonespace27 requested changes
What TF4 said

2022-08-02 00:20 UTC, SingingSpock commented
Adding something to indicate that they are supposed to abide by Security Policy guidelines for weapon carry on various alerts would also be prudent, I think.

2022-08-08 00:15 UTC, Gandalf2k15 commented
This was already updated

2022-08-08 00:15 UTC, closed without merging