I made a sprite
Skyrat-SS13/Skyrat-TG pull request #15184
Opened 2022-07-25 12:09 UTC by JhinHandaGay21

## About The Pull Request
I spent the whole night creating a sprite jacket for all players and would like this jacket to be added to the game

## How This Contributes To The Skyrat Roleplay Experience
people will have more choice

## Changelog

:cl:
add: Added more things
imageadd: added some icons and images
code: changed some code
:cl:

2022-07-25 13:36 UTC, tf-4 requested changes

2022-07-25 13:36 UTC, tf-4 commented on code/modules/clothing/suits/jacket.dm
> +	 armor = list(MELEE = 1, BULLET = 1, LASER = 1,ENERGY = 1, BOMB = 1, FIRE = 1, ACID = 1)
```suggestion
/obj/item/clothing/suit/jacket
	name = "pink jacket"
	desc = "PINK PINK PINK"
	icon_state = "pink_jacket"
	inhand_icon_state = "leatherjacket"
	body_parts_covered = CHEST|GROIN|ARMS
	armor = list(MELEE = 1, BULLET = 1, LASER = 1,ENERGY = 1, BOMB = 1, FIRE = 1, ACID = 1)
```
Your indentation is off

2022-07-25 13:36 UTC, tf-4 commented on code/modules/clothing/suits/jacket.dm
> +	/obj/item/clothing/suit/jacket
```suggestion
/obj/item/clothing/suit/jacket/pink
```
This needs to be a subtype

2022-07-25 13:36 UTC, tf-4 commented on code/modules/clothing/suits/jacket.dm
> +	 body_parts_covered = CHEST|GROIN|ARMS
```suggestion
```
This is the same as the parent

2022-07-25 13:36 UTC, tf-4 commented on code/modules/clothing/suits/jacket.dm
> +	 armor = list(MELEE = 1, BULLET = 1, LASER = 1,ENERGY = 1, BOMB = 1, FIRE = 1, ACID = 1)
```suggestion
```
Shouldn't be armoured.

2022-07-25 13:36 UTC, tf-4 commented on code/modules/vending/clothesmate.dm
> +		/obj/item/clothing/suit/pink_jacket = 3,
move this to below this line here,
https://github.com/Skyrat-SS13/Skyrat-tg/blob/10a2c07de6e0b2d7fa20a40f70471d730f820563/modular_skyrat/modules/modular_vending/code/clothesmate.dm#L95

2022-07-25 13:36 UTC, tf-4 commented on code/modules/clothing/suits/jacket.dm
> +	/obj/item/clothing/suit/jacket
Move all this to `modular_skyrat/modules/customization/modules/clothing/suits/jacket.dm`. The folder is there but you just need to make a new file. Ensure the new file is ticked once you've made it.

2022-07-25 13:38 UTC, tf-4 commented
You also need screenshots taken of the sprite in game

2022-07-25 14:33 UTC, Lukaster42 commented
death.

2022-07-25 16:02 UTC, Zonespace27 requested changes
- Fix your changelog
- Modularize this as said
- Please confirm you actually tested this, seeing as you made this entirely out of webedits

2022-07-25 18:33 UTC, Zonespace27 requested changes

2022-07-25 18:33 UTC, Zonespace27 commented on код/модули/Одежда/Костюмы/jacket.dm
> +/obj/item/clothing/suit/jacket
не русский

2022-07-25 18:33 UTC, Zonespace27 commented on код/модули/Одежда/Костюмы/jacket.dm
> +/obj/item/clothing/suit/jacket/leather
...none of these other jackets are used anywhere

2022-07-26 06:32 UTC, OrionTheFox commented on code/modules/clothing/suits/jacket.dm
> +
>TG master file addition

2022-07-26 06:35 UTC, OrionTheFox commented
Also, looking at the sprite via the icondiffbot, its just- eh?
There's minimal shading, and pink with gold accents is a combination that shouldn't see the light of day anyways.
The detailing is confusing at best - why a helix on the back, if thats what thats meant to be? What's the dark colors in the front, an undershirt?
Moreover, forced colors for one-off items is bad anyways. Greyscale jackets are or can be a thing, including in this jacket's shape

2022-07-26 22:13 UTC, ChungusGamer666 commented
chad pr

2022-08-04 15:07 UTC, Gandalf2k15 commented
Re-make a PR once you have completed this.

2022-08-04 15:07 UTC, closed without merging