[FUCK] Sanitize Loaded Languages!
Skyrat-SS13/Skyrat-TG pull request #15235
Opened 2022-07-27 23:42 UTC by RimiNosha

## About The Pull Request
Uhhh, not me! I blame uh- um- TG, yea- they should've known someone was gonna mess with the language system!

<sub>/s</sub>

## How This Contributes To The Skyrat Roleplay Experience
I BROKE STUFF AND NOW IT'S NOT!

## Changelog

:cl:
fix: Fixed invisible uninteractable languages on the prefs menu, as well as being able to be assigned unobtainable languages because of said bug.
/:cl:

2022-07-27 23:46 UTC, Zonespace27 requested changes

2022-07-27 23:46 UTC, Zonespace27 commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm
> +	for(var/datum/language/lang_path in src.preferences.languages.Copy())
```suggestion
	for(var/datum/language/lang_path as anything in preferences.languages)
```

2022-07-27 23:46 UTC, Zonespace27 commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm
> +		lang_path = new lang_path()
```suggestion
```

2022-07-27 23:46 UTC, Zonespace27 commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm
> +		if(lang_path.secret)
```suggestion
		if(initial(lang_path.secret)_
```

2022-07-27 23:46 UTC, Zonespace27 commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm
> +			src.preferences.languages.Remove(lang_path)
```suggestion
			preferences.languages.Remove(lang_path)
```

2022-07-28 01:22 UTC, theselfish commented
We almost got the languages back.

2022-07-28 01:31 UTC, GoldenAlpharex approved these changes
Looks good.

2022-07-28 01:31 UTC, merged