Remove Nanotrasen Rep weapon set.
Skyrat-SS13/Skyrat-TG pull request #15249
Opened 2022-07-28 20:34 UTC by Gladi-Writes

## About The Pull Request

Note: SRQ/Gladi on discord. Chiara Nowak ingame.

Proposed change removes the NTR weapon due to:
Over-saturation of weapons when the NTR and Blueshield are around making some antagonism nearly, if not literally, impossible.
"Greenshield" Reps that due to their access to a weapon feel overly obliged to utilize force in a non-fitting way in situations.

## How This Contributes To The Skyrat Roleplay Experience

The fact that central would not expect what is effectively a paperwork jockey oversight person to be any real target or have any reason to doubt their safety.

The representative can still of course purchase their own weapon, or borrow one from security in an emergency. I think this is more fitting for playing the role how it's meant to be, and fits with the in-character idea of this role.

## Changelog

:cl:
remove: NTR weapon-set.
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-07-28 20:57 UTC, GoldenAlpharex requested changes

2022-07-28 20:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
>  		)
Just because it bothers me.
```suggestion
	)
```

2022-07-29 11:56 UTC, tf-4 approved these changes

2022-07-29 16:05 UTC, HoodMilk commented
yeah this makes sense

2022-07-30 19:29 UTC, theselfish commented
Wouldn't a one-use hold out weapon fit the Rep more than *no* gun?

Like a Derringer?

2022-07-31 17:49 UTC, TetrakoHateThis commented
By the same logic, shouldn't HoP also have their Osprey removed?

2022-07-31 18:02 UTC, tf-4 commented
> By the same logic, shouldn't HoP also have their Osprey removed?

probably but out of scope

2022-07-31 22:05 UTC, Gandalf2k15 commented
they're quite important to nanotrasen, a corporate liaison if you will

2022-08-01 03:41 UTC, SingingSpock commented
This makes no sense. Firstly, as Gandalf said, ICly the NT rep is a valuable individual worth protecting. Secondly, on an OOC level the NTR has a CC ID with access management access. That means that taking out the rep and getting their card is an easy way for anyone to get AA if the rep is unable to protect themselves. Every role that has ID edit access has a weapon and for good reason.

2022-08-02 22:25 UTC, Gandalf2k15 commented
see above

2022-08-02 22:25 UTC, closed without merging