gives the agateram an incredibly subpar dodgeroll
Skyrat-SS13/Skyrat-TG pull request #15431
Opened 2022-08-06 05:24 UTC by Hatterhat

## About The Pull Request
agateram gets a dodgeroll on rmb
- plays the Dark Souls armored roll noise
- costs 15 stam to throw out
- throws you 3 tiles max
- makes you block projectiles and melee for slightly less than a second

(i tried making it so projectiles just phased through, but sadly had no success and settled for this)
## How This Contributes To The Skyrat Roleplay Experience
miners now have another fun feature to get themselves killed using
## Changelog
:cl:
add: The energies stored within the ancient blade Agateram can now be utilized to quite literally throw yourself at your problems, giving you a moment's reprieve from getting hit by projectiles or melee hits at a decent stamina cost.
/:cl:

2022-08-06 05:29 UTC, Zonespace27 requested changes

2022-08-06 05:29 UTC, Zonespace27 commented on modular_skyrat/modules/gladiator/code/game/objects/items/gladiator_items.dm
> +	if(!user.IsImmobilized()) // no free dodgerolls
early return

2022-08-06 05:29 UTC, Zonespace27 commented on modular_skyrat/modules/gladiator/code/game/objects/items/gladiator_items.dm
> +		playsound(user, 'modular_skyrat/master_files/sound/effects/body-armor-rolling.wav', 50, FALSE)
sound licensing

2022-08-06 05:29 UTC, Zonespace27 commented on modular_skyrat/modules/gladiator/code/game/objects/items/gladiator_items.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-08-08 00:06 UTC, Gandalf2k15 approved these changes

2022-08-08 00:12 UTC, merged