Modularize Crew Monitor, fixes health status
Skyrat-SS13/Skyrat-TG pull request #15490
Opened 2022-08-09 03:59 UTC by Zergspower

## About The Pull Request

With TG Mirrors a real probability here, i've added CrewConsoleSkyrat.js to account for this

## How This Contributes To The Skyrat Roleplay Experience

Better represents the health of players who otherwise would be in peril, this would allow medical or other parties to better gauge if someone is dead or in critical in a more correct manner. Previously alive crew were showing up dead, this clearly was a cause of stress when a paramedic now assumes you are the walking dead.

## Changelog

![image](https://user-images.githubusercontent.com/22140677/183559931-cb60d30c-25b0-4f57-adad-1f97aff68b31.png)

Readdresses the math relating to the status icons that haven't been correct in quite a while, given the healthpool differences we were running off TG's formula. As you 'die' when you hit 200 damage I ensured the critical icon doesn't show until you're actually in critical now rather than the 100-125 zone.

:cl:
qol: Icons now correctly indicate health status
fix: Fixes the maths relating to the health pool, no longer working off 1-125
code: migrated CrewConsole to a Skyrat Modular file to avoid future clashes with mirrors
/:cl:

2022-08-09 04:05 UTC, Zergspower commented
i've no idea why CI Failed if anyone can explain that

2022-08-09 06:04 UTC, Zonespace27 commented
> i've no idea why CI Failed if anyone can explain that

run prettierjs
![image](https://user-images.githubusercontent.com/41448081/183576256-9cdc3159-9aa0-4c96-a578-8f741af03273.png)

2022-08-09 15:13 UTC, Zonespace27 requested changes

2022-08-09 15:13 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/CrewConsoleSkyrat.js
> +export const CrewConsole = () => {
make this a skyrat version - overrides don't work in js/ts/tsx to my knowledge

2022-08-09 15:13 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/CrewConsoleSkyrat.js
> +import { sortBy } from 'common/collections';
Replace the UI in the crew monitor file with this UI

2022-08-09 15:13 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/CrewConsoleSkyrat.js
> +import { useBackend } from '../backend';
Reset the non-SR version of this file

2022-08-09 23:04 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/.prettierrc
> +{
get rid of this
(also pull from master to be safe)

2022-08-20 06:31 UTC, Zonespace27 commented
Ping a maintainer to reopen when changes are made

2022-08-26 00:56 UTC, Zergspower commented
@Zonespace27

2022-08-26 04:52 UTC, GoldenAlpharex approved these changes
Looks good!

2022-08-27 18:05 UTC, GoldenAlpharex requested changes
My final little nitpick.

2022-08-27 18:05 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/CrewConsoleSkyrat.js
> +        {oxydam !== undefined ? (
This should make it so it displays a skull icon when they're dead, even if their health is all fine and dandy. Do make sure to test it before committing it.
```suggestion
        {oxydam !== undefined && life_status ? (
```

2022-08-28 02:50 UTC, Zergspower commented
![image](https://user-images.githubusercontent.com/22140677/187055322-a90c82f0-e0fb-445d-9333-e7e092a71c5e.png)
 Fascinating

2022-08-28 16:19 UTC, GoldenAlpharex approved these changes
Alright, it's all good to go now. Thanks for all your hard work on this!

2022-08-28 16:35 UTC, merged