Bodily fluid now carries forensic data
Skyrat-SS13/Skyrat-TG pull request #15723
Opened 2022-08-20 17:42 UTC by Zonespace27

## About The Pull Request
Bodily fluid stains now have the DNA of whodunnit.
![image](https://user-images.githubusercontent.com/41448081/185759695-5a66b0ce-f4e4-471c-b345-bece97bb0195.png)
Thank you and curse you for inspiring me

## How This Contributes To The Skyrat Roleplay Experience
It really doesn't

## Changelog

:cl:
fix: Bodily fluid now carries DNA of the person who created it
/:cl:

2022-08-20 17:44 UTC, Stalkeros2 commented
Quality of life.

2022-08-20 23:35 UTC, YakumoChen commented
do we really WANT to know? I feel like this prebreaks security, rape etc has already been removed from security duties / space law.

2022-08-24 21:36 UTC, GoldenAlpharex requested changes
Overall I'm really indifferent to this being a thing or not, I guess it makes sense, worst case scenario we can just take it out if it causes problems, I guess.

2022-08-24 21:36 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_items/lewd_items/code/technical_stuff_for_lewd.dm
> +/mob/living/proc/add_cum_splatter_floor(turf/the_turf)
Documentation here please :)

2022-08-25 00:36 UTC, Iamgoofball commented
this should not have player facing DNA because if a detective is having to scan this then something is already wrong

2022-09-05 17:11 UTC, GoldenAlpharex approved these changes
Looks good enough, yeah.

2022-09-05 17:44 UTC, merged