re-nerfs the venus
Skyrat-SS13/Skyrat-TG pull request #15922
Opened 2022-08-29 22:34 UTC by jjpark-kb

## About The Pull Request
vines now heal less when they hit a non-dead living thing.
vines now heal when ON vines and take damage when OFF vines.
vines now do not heal when walking through vines.

## How This Contributes To The Skyrat Roleplay Experience
vines are a bit strong-- addressing venus will make vines more tolerable.

## Changelog

:cl:
balance: vines heal less when hurting alive things
add: vines now take damage when off vines / heal when on vines
del: vines no longer heal while moving through vines
/:cl:

2022-08-29 23:01 UTC, Zonespace27 requested changes

2022-08-29 23:01 UTC, Zonespace27 commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +/mob/living/simple_animal/hostile/venus_human_trap/proc/check_vines()
modularize this

2022-08-29 23:10 UTC, GoldenAlpharex requested changes
I agree with Zonespace, otherwise this is good to go!

2022-08-29 23:12 UTC, YakumoChen commented
Fairly extreme nerf unless you make on-vine healing much higher or give them a large health buff. 

The health regen is the only factor that keeps Venus competitive, they are very fragile and can only beat back the crew through attrition. This will make them die extremely quickly

2022-08-30 00:28 UTC, GoldenAlpharex requested changes

2022-08-30 00:28 UTC, GoldenAlpharex commented on modular_skyrat/modules/apocolypse_of_scythes/code/venus.dm
> +	return ..()
Single (or double here) letter var bad.

2022-09-04 14:34 UTC, GoldenAlpharex approved these changes

2022-09-04 14:35 UTC, merged