Teshari GAGS clothing updates and misc sprite cleanup.
Skyrat-SS13/Skyrat-TG pull request #16025
Opened 2022-09-03 06:12 UTC by Ebin-Halcyon

## About The Pull Request

Tin, added Teshari support to a few GAGS'd items, name right now, the sundress and plaid dress and utility jumpsuits.
Updates the scarf and glove fallback sprites so they aren't piss ugly anymore.
I'll update more along with everything fucking else.
![image](https://user-images.githubusercontent.com/81479835/188258236-fa1e3402-8136-4f4f-9d87-0d40177430a7.png)
![image](https://user-images.githubusercontent.com/81479835/188258242-3fd9d178-9e4c-4697-b1ae-d378ca39ed93.png)
![image](https://user-images.githubusercontent.com/81479835/188258259-6d51272e-75ac-4b3d-93f4-ec9de6c65a1e.png)

## How This Contributes To The Skyrat Roleplay Experience

Fixes and cleanup to a species that everyone else refuses to sprite for.

## Changelog

:cl:
imageadd: FIxes a few GAGs'd items to have support for Teshari, namely sundresses and plaid skirts, updates the scarf and glove fallback sprites, check them out.
/:cl:

2022-09-03 08:43 UTC, OrionTheFox commented
Requesting DNM until #15257 - Spritefile cleanup for lots of this, including the GAGS of the related items.
That one has changes to the greyscale configs that I'd rather you dont have to deal with conflicts of

2022-09-03 10:23 UTC, Ebin-Halcyon commented
> Requesting DNM until #15257 - Spritefile cleanup for several related items, specifically GAGS skirts That one has changes to the greyscale configs that I'd rather you dont have to deal with conflicts of

All good with me, I got more than enough time to wait. 👍

2022-09-05 19:42 UTC, GoldenAlpharex requested changes

2022-09-05 19:42 UTC, GoldenAlpharex commented on code/modules/clothing/under/skirt_dress.dm
> +	greyscale_config_worn_teshari = /datum/greyscale_config/plaidskirt_worn/teshari //SKYRAT EDIT - Teshari greyscale
I feel like we could just place those overrides in a modular file instead, no?

2022-09-05 19:42 UTC, GoldenAlpharex commented on code/modules/clothing/under/skirt_dress.dm
> +	greyscale_config_worn_teshari = /datum/greyscale_config/sundress_worn/teshari
Ditto (plus you forgot the modular comment here)

2022-09-16 11:05 UTC, Ebin-Halcyon commented
Same as the bluesec PR, gonna add more to this when i'm more motivated, closing it so it doesn't go stale.

2022-11-06 02:50 UTC, Ebin-Halcyon commented
Alright let's get it, back to the slave life.

2022-11-06 11:59 UTC, tf-4 approved these changes

2022-11-15 02:36 UTC, Tastyfish requested changes

2022-11-15 02:36 UTC, Tastyfish commented on modular_skyrat/modules/GAGS/greyscale_configs.dm
> +	json_config = 'code/datums/greyscale/json_configs/sundress_worn.json'
Line unnecessary as that comes with being a subtype of `/datum/greyscale_config/sundress_worn`
```suggestion
```

2022-11-15 03:18 UTC, Tastyfish approved these changes
code

2022-11-18 04:12 UTC, GoldenAlpharex approved these changes
Looks good!

2022-11-18 04:12 UTC, merged