Ashwalkers in Lavalands now use their proper tools
Skyrat-SS13/Skyrat-TG pull request #16080
Opened 2022-09-05 20:37 UTC by IgiariValkyr

## About The Pull Request

Ashwalkers in Lavalands are known kleptomaniacs that continue to use human tools instead of the crafted tools by their tribe. Even the Ice Moon tribe uses the crafted tools. So this just brings them in line with each other.

![lavalandsurgerybeforeafter](https://user-images.githubusercontent.com/5521322/188510209-318c2ec1-5882-4cfa-8fc2-de1df693f94b.png)
![lavalandstoragebeforeafter](https://user-images.githubusercontent.com/5521322/188510219-ac508756-de05-448f-a2b4-b72c0c2053f7.png)

## How This Contributes To The Skyrat Roleplay Experience

Just brings the Lavalands Tribe to par with the Ice Moon Tribe in terms of appropriate tools.

## Changelog

:cl:
balance: Lavaland Ashwalkers now have Primative Tools instead of Human Tools
/:cl:

2022-09-05 20:42 UTC, IgiariValkyr commented
oh fuck wait I accidently deleted the lizard blood bags

2022-09-12 05:24 UTC, Zonespace27 requested changes

2022-09-12 05:24 UTC, Zonespace27 commented on _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_ash_walker1_skyrat.dmm
> -/obj/item/storage/belt/utility/full,
add a subtype of utility belts with ashwalker tools

2022-09-12 05:24 UTC, Zonespace27 commented on _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_ash_walker1_skyrat.dmm
> +/obj/structure/stone_tile/cracked{
these two tiles are stacked ontop of eachother

2022-09-12 05:24 UTC, Zonespace27 commented on _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_ash_walker1_skyrat.dmm
> -/obj/item/stack/sheet/cloth/ten,
intended to delete cloth?

2022-09-25 01:10 UTC, closed without merging