Part one of phasing out sprited 'advanced' shuttles
Skyrat-SS13/Skyrat-TG pull request #16171
Opened 2022-09-11 19:55 UTC by Paxilmaniac

## About The Pull Request
For those who are unaware of what the title means, 'advanced' shuttles are each of our shuttles that uses custom sprited walls and such, like the cargo or mining shuttles.

Now, why would we want to get rid of these? They look good (in some cases, looking at you escape pod), so what's the problem? Maintainability on the developer side, and reparability on the player side. If you want to make even the slightest change to a shuttle, you'll need to almost completely redo the sprites, and if the shuttles breaks in the round, you have no way to repair the walls back to their original state.

Images of the new ones pending mapdiff

## How This Contributes To The Skyrat Roleplay Experience
Increases the maintainability of skyrat shuttles while keeping a look that I at least hope is superior to tg's defaults.

The only reason I haven't done the ferry or arrivals yet is because there's a lot more to change than just the ferry itself, considering I'll have to edit the automapper because we decided to change arrivals of EVERY MAP.

Also how tf do I changelog this.

## Changelog

:cl:
qol: phases out most of the custom sprited shuttles, seeing as they are currently maintainer hell for anyone who wants to make the slightest change to their shape or layout
/:cl:

2022-09-11 21:14 UTC, MLGTASTICa commented
could've also just made shuttle turfs keep track of the icon-state of the above-wall and reapply it if a wall of the corresponding type is placed over..

2022-09-11 21:32 UTC, Paxilmaniac commented
> could've also just made shuttle turfs keep track of the icon-state of the above-wall and reapply it if a wall of the corresponding type is placed over..

This doesn't solve the problem of having to make completely new sprites whenever a mapper needs to change the shuttle.

2022-09-11 23:27 UTC, OrionTheFox commented
Just one note: that Exhaust Vent at the bottom of the evac shuttle is technically a wallcloset; depending on how its placed it might conflict with the tool closet

Otherwise I'll look into ways of personalizing the shuttles a bit (perhaps a way to add decals to walls so we can have department stripes) but god please kill it.
Sad to see the cargo one go though, that one was my baby (along with the spriter, bless their soul)

2022-09-12 01:34 UTC, YakumoChen commented
hated the escape shuttle anyway, all the windows were just resprited walls so you couldn't shoot through them in case someone was trolling outside (looking at you revanent)

2022-09-12 05:39 UTC, Arctaisia commented
I knew this was gonna happen eventually after I left skyrat, pff

I do like what you've done with these shuttles though!! I will admit, even as the person who edited/made a couple of the shuttle sprites for here and more recently for hyper, they're a **super big** pain in the ass to edit when needed, it's why I've thought about trying to do more modular wall sprites sometime to act as building blocks rather than set sprites slapped on.

Love your mix of floors and other design choices, like the use of dark walls near engines. Nice work! :heart:

2022-09-12 10:45 UTC, YakumoChen commented
The evac shuttle needs a LOT more chairs I think, keep in mind it typically holds upwards of 60 people on highpop

2022-09-12 13:39 UTC, Paxilmaniac commented
> The evac shuttle needs a LOT more chairs I think, keep in mind it typically holds upwards of 60 people on highpop

you’d be surprised to hear this is actually already a few more chairs than the one we have currently

2022-09-13 02:28 UTC, ORCACommander commented
this fills me with sadness

2022-09-13 19:37 UTC, kittysmooch commented
should the exhaust vent sprite on the back of the escape shuttle be on the outside of the hull rather than inside the engineering section? i thought the mechanical purpose was for antags to smuggle themselves to central command

2022-09-13 20:18 UTC, Paxilmaniac commented
> should the exhaust vent sprite on the back of the escape shuttle be on the outside of the hull rather than inside the engineering section? i thought the mechanical purpose was for antags to smuggle themselves to central command

if its on the outside then it won't move with the shuttle, its always been inside the engi room

2022-09-13 21:40 UTC, Jolly-66 requested changes
Hi. Two things.
If we're going to remove the sprites in favor of what we already, can we nuke this consoles as well? They're redundant and don't fit with their surroundings.
![image](https://user-images.githubusercontent.com/70232195/190014160-2ab60473-1f2f-41c4-9e09-b967c38ccecc.png)

Second, could you look over the turfs and give them their proper icons? Something I just noticed and figured I'd ask.
![image](https://user-images.githubusercontent.com/70232195/190014287-12d2f609-a7f8-4ca9-9fc5-346a5b9b9e39.png)

2022-09-14 03:36 UTC, Paxilmaniac commented
> Hi. Two things. If we're going to remove the sprites in favor of what we already, can we nuke this consoles as well? They're redundant and don't fit with their surroundings. ![image](https://user-images.githubusercontent.com/70232195/190014160-2ab60473-1f2f-41c4-9e09-b967c38ccecc.png)
> 
> Second, could you look over the turfs and give them their proper icons? Something I just noticed and figured I'd ask. ![image](https://user-images.githubusercontent.com/70232195/190014287-12d2f609-a7f8-4ca9-9fc5-346a5b9b9e39.png)

I've done the shuttle console thing, I'll have to look into the area icon issue later

2022-09-24 19:27 UTC, Zonespace27 commented
Paxil said it was good to go, YOLO

2022-09-24 19:27 UTC, merged

2022-09-25 04:19 UTC, Mortisduem commented
I can see why simplifying the shuttles sprites can make life easier. But please keep the sprites and art in as they can be reused in some creative ways. The "off" sprits that don't nicely line up with full sprits like walls or partial sprits like window panels or glass doors. The Ferry shuttle is a good example as it has lots of "greeble" sprites that are stuck where they are and not much else lines up with them (the tail section fins)

Here is an example of an Arrivals Shuttle that is a reuse of parts of the Skyrat Ferry shuttle, and was sized to be a little bigger then the current arrivals shuttle. I made it to be a better fit into some of the older maps like Pubby Station that had the docks on both sides of the shuttle. Its not perfect but something like this might be a happy middle ground. 

![Fancy Shuttle](https://user-images.githubusercontent.com/62526167/192127572-58a1e0f0-b7dd-4dd7-8741-69edfed1c376.png)

2022-09-25 16:57 UTC, YakumoChen commented
> I can see why simplifying the shuttles sprites can make life easier. But please keep the sprites and art in as some can be reused in some creative ways.
> 
> Here is an example of an Arrivals Shuttle that is a reuse of parts of the Skyrat Ferry shuttle, and was sized to be a little bigger then the current arrivals shuttle. I made it to be a better fit into some of the older maps like Pubby Station that had the docks on both sides of the shuttle. Its not perfect but something like this might be a happy middle ground.
> 
> ![Fancy Shuttle](https://user-images.githubusercontent.com/62526167/192127572-58a1e0f0-b7dd-4dd7-8741-69edfed1c376.png)

The sprites are still there if you go to the previous build