Flypeople are now FOV immune
Skyrat-SS13/Skyrat-TG pull request #16206
Opened 2022-09-13 20:54 UTC by JohnFulpWillard

## About The Pull Request

Eyes now give FOV out, and Flypeople eyes are immune to it.

## How This Contributes To The Skyrat Roleplay Experience

Flies generally can see all around them with a near 360 point of view, so I thought we can maybe reflect that in-game as well, making them more unique as a species.
Flypeople also can't see very well, which is why they are flashable by all directions, something I added in https://github.com/tgstation/tgstation/pull/55724

## Changelog

:cl:
balance: Fly eyes don't have an innate field of view anymore.
/:cl:

2022-09-13 22:26 UTC, Zonespace27 requested changes
Based willard PR

2022-09-13 22:26 UTC, Zonespace27 commented on code/modules/mob/living/living_fov.dm
>  		highest_fov = native_fov
skyrat edit comment

2022-09-13 22:26 UTC, Zonespace27 commented on code/modules/surgery/organs/eyes.dm
> +	var/see_all_dirs = FALSE //SKYRAT EDIT - FOV immune eyes
do the comment like
```
// SKYRAT EDIT START
stuff
stuff2
// SKYRAT EDIT END
```
when doing multi-line things, even comments

2022-09-14 04:45 UTC, GizkaFreechman commented
this is a pretty significant buff, especially when almost all fly person race traits are negative and im not saying this because im a fly main

-they take desword damage from fly swatters (guaranteed hairline fracture, after one hit) 
-pest spray and the bug spray drink, deal significant toxin damage
-their livers cause them to get drunk easier
-they have slower movespeed? (needs citation)
-organ names are randomized
-the fly stomach is the culprit behind all the puking
-the Proboscis tongue organ, is what they use to slurp that vomit
-their eyes more vulnerable to flashes (as stated in the pr).

all this, just for better FOV, I'm gonna take what I can get

2022-09-14 05:29 UTC, OrionTheFox commented
Couldnt this be done on TG as innate fov is a config anyways?

2022-09-14 17:15 UTC, JohnFulpWillard commented
> Couldnt this be done on TG as innate fov is a config anyways?

Tbh I didn't even realize this was a config until I started working on it, I'll try it now.

2022-09-14 17:35 UTC, hugmeorelse commented
I'm fine with this, considering nobody really plays flypersons all too much, and it makes sense for them. However, I'm not sure about full 360 degree FOV.

2022-09-27 00:57 UTC, closed without merging