multitools are now gentle on light fixtures
Skyrat-SS13/Skyrat-TG pull request #16212
Opened 2022-09-14 01:29 UTC by coldud13

## About The Pull Request
this annoyed me so i fixed it

## How This Contributes To The Skyrat Roleplay Experience
less broken light bulbs after fixing the ballasts

## Changelog

:cl:
qol: reduced the chance of accidentally breaking a light fixture with a multitool when repairing the ballast
/:cl:

2022-09-14 01:42 UTC, theOOZ commented
why not upstream?

2022-09-14 10:19 UTC, jjpark-kb commented on code/modules/power/lighting/light.dm
> +		if(constant_flickering)
early return; so if(!constant_flickering)

2022-09-14 10:20 UTC, jjpark-kb commented on code/modules/power/lighting/light.dm
> +			return
one indentation backwards

2022-09-14 10:21 UTC, jjpark-kb commented on code/modules/power/lighting/light.dm
> +			if(do_after(user, 2 SECONDS, src))
early return

2022-09-14 10:21 UTC, jjpark-kb commented on code/modules/power/lighting/light.dm
> +			return
redundant return if you early returned early as well as moving back the below return one indentation.

2022-09-14 10:22 UTC, jjpark-kb commented on code/modules/power/lighting/light.dm
> +	//SKYRAT EDIT
Make this modular-- I know you didn't do it, but I would appreciate it.

2022-09-14 11:01 UTC, press-mark commented on code/modules/power/lighting/light.dm
> +	//SKYRAT EDIT
moved it :)

2022-09-14 11:02 UTC, press-mark commented on code/modules/power/lighting/light.dm
> +			if(do_after(user, 2 SECONDS, src))
not 100% which part u were referring to here

2022-09-14 11:03 UTC, press-mark commented on code/modules/power/lighting/light.dm
> +			return
kept this one in but moved it down for *visual clarity*

2022-09-14 21:28 UTC, jjpark-kb commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +// attack with item - insert light (if right type), otherwise try to break the light
oh god, this isn't what I meant!

You just need to do . = ..() and then add your new functionality (the skyrat part). I am sure there are examples in the codebase about modularly adding more functionality to a proc.

2022-09-14 21:29 UTC, jjpark-kb commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +			to_chat(user, span_notice("You repair [src]'s ballast."))
if(!do_after) early return

2022-09-14 21:30 UTC, jjpark-kb commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +			to_chat(user, span_warning("[src]'s ballast is already working!"))
balloon_alert instead "ballast already working!"

2022-09-14 21:30 UTC, jjpark-kb commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +		to_chat(user, span_notice("You start repairing the ballast of [src] with [tool]."))
balloon_alert instead "repairing ballast..."

2022-09-14 21:30 UTC, jjpark-kb commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +			to_chat(user, span_notice("You repair [src]'s ballast."))
balloon_alert instead "ballast repaired!"

2022-09-15 06:52 UTC, press-mark commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +// attack with item - insert light (if right type), otherwise try to break the light
ok i think we're on the same page now

2022-09-18 05:38 UTC, Zonespace27 requested changes

2022-09-18 05:38 UTC, Zonespace27 commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +	if(istype(tool, /obj/item/multitool))
convert this to multitool_act

2022-09-18 05:38 UTC, Zonespace27 commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +		if(do_after(user, 2 SECONDS, src))
there's a tool_act proc

2022-09-18 05:38 UTC, Zonespace27 commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-09-18 07:46 UTC, press-mark commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +		if(do_after(user, 2 SECONDS, src))
think i used the right one

2022-09-18 07:48 UTC, press-mark commented on modular_skyrat/modules/aesthetics/lights/code/lighting.dm
> +			to_chat(user, span_notice("You repair [src]'s ballast."))
what does this do differently though?

2022-09-18 11:28 UTC, jjpark-kb commented
![image](https://user-images.githubusercontent.com/55967837/190899796-e0e34d82-0c28-4c33-a223-d31d51a89dd5.png)

If it doesn't work, the whips coming out.

2022-09-18 11:28 UTC, merged