Subtler fix and slight tidy up
Skyrat-SS13/Skyrat-TG pull request #16305
Opened 2022-09-19 00:53 UTC by tf-4

fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/15471
Well, the second half. The first half is already fixed. For the love of God please atomise issue reports into distinct issues so they can be closed when complete more easily.

Also deindents a little, and removes a bit of dead code.
It was a `TODO` added in a PR 24 months ago. That's not getting done. If you want to do it, feel free.

## Changelog
:cl:
fix: Subtler emotes will no longer send if you cancel target selection.
/:cl:

2022-09-19 01:00 UTC, jjpark-kb commented on modular_skyrat/modules/verbs/code/subtle.dm
> +				in_view.Remove(mob_in_view)
I feel like you can untype the for(var/mob/mob_in_view and just make it for(var/mob_in_view
then, make the !istype a !ismob

2022-09-23 18:08 UTC, tf-4 commented on modular_skyrat/modules/verbs/code/subtle.dm
> +				in_view.Remove(mob_in_view)
What's the advantage?

2022-09-24 19:40 UTC, Zonespace27 requested changes

2022-09-24 19:40 UTC, Zonespace27 commented on modular_skyrat/modules/verbs/code/subtle.dm
> +		for(var/mob/mob_in_view as anything in in_view)
cut the `as anything`, BYOND already optimizes range/view/hearers/etc. procs when you're searching for a base type (area/obj/turf/mob)

2022-09-25 12:50 UTC, tf-4 commented on modular_skyrat/modules/verbs/code/subtle.dm
> +		for(var/mob/mob_in_view as anything in in_view)
```suggestion
		for(var/mob/mob_in_view in in_view)
```

2022-09-26 01:36 UTC, GoldenAlpharex requested changes

2022-09-26 01:36 UTC, GoldenAlpharex commented on modular_skyrat/modules/verbs/code/subtle.dm
>  			return FALSE
```suggestion
			return FALSE

```

2022-09-26 01:36 UTC, GoldenAlpharex commented on modular_skyrat/modules/verbs/code/subtle.dm
> +			return FALSE
```suggestion
			return FALSE

```

2022-09-26 01:36 UTC, GoldenAlpharex commented on modular_skyrat/modules/verbs/code/subtle.dm
> +			if(!istype(mob_in_view))
If you removed the `as anything`, then the `!istype()` isn't really necessary anymore, I feel like.

2022-10-02 13:32 UTC, Gandalf2k15 approved these changes

2022-10-02 13:43 UTC, merged