Removes Xeno egg map spawn and replaces it with a borer egg
Skyrat-SS13/Skyrat-TG pull request #16352
Opened 2022-09-21 16:18 UTC by Zergspower

## About The Pull Request

As title says

## How This Contributes To The Skyrat Roleplay Experience

The current map spawn is antag bait and is causing too many issues as of late, we've made the decision to swap to a borer egg in the interim until a further decision is made

## Changelog

:cl:
code: the xeno egg map spawn is now a borer egg
/:cl:

2022-09-21 16:26 UTC, tf-4 requested changes
Remove all the map changes, don't rename the file, leave everything stock except the actual spawned structure (which needs to be changed as indicated) and the admin log (which will need skyrat edit comments)

2022-09-21 16:26 UTC, tf-4 commented on code/game/objects/effects/spawners/borer_egg_delivery.dm
> +	icon_state = "brainegg"
Leave this how it was

2022-09-21 16:26 UTC, tf-4 commented on code/game/objects/effects/spawners/borer_egg_delivery.dm
> +/obj/effect/spawner/borer_egg_delivery/Initialize(mapload)
Leave this how it was

2022-09-21 16:26 UTC, tf-4 commented on code/game/objects/effects/spawners/borer_egg_delivery.dm
> +	log_game("A borer egg has been delivered to [AREACOORD(T)]")
skyrat edit comments

2022-09-21 16:26 UTC, tf-4 commented on code/game/objects/effects/spawners/borer_egg_delivery.dm
>  	new /obj/structure/alien/egg(T)
change this to a borer egg with a skyrat edit comment

2022-09-21 16:26 UTC, tf-4 commented on code/game/objects/effects/spawners/random/medical.dm
> +		/obj/effect/spawner/borer_egg_delivery = 1,
leave this how it was

2022-09-21 16:26 UTC, tf-4 commented on tools/UpdatePaths/Scripts/60522_replace_spawners.txt
> +/obj/effect/spawner/lootdrop/two_percent_borer_egg_spawner : /obj/effect/spawner/random/medical/two_percent_borer_egg_spawner
don't touch updatepaths scripts outside of the PR they're introduced in

2022-09-21 16:53 UTC, Higgin commented
> The current map spawn is antag bait and is causing too many issues as of late, we've made the decision to swap to a borer egg in the interim until a further decision is made

can't you just leave it alone and ask staff to stop interfering with it as a way of crew getting themselves into trouble if they want to? 

I'm pretty sure from every round I've seen where the xenos were either killed or broke containment, the spawn is much less antag bait than admin bait. That went even before nu-xenos.

2022-09-21 16:56 UTC, Zergspower commented
> > The current map spawn is antag bait and is causing too many issues as of late, we've made the decision to swap to a borer egg in the interim until a further decision is made
> 
> can't you just leave it alone and ask staff to stop interfering with it as a way of crew getting themselves into trouble if they want to?
> 
> I'm pretty sure from every round I've seen where the xenos were either killed or broke containment, the spawn is much less antag bait than admin bait. That went even before nu-xenos.

I'm a little confused by this? It's a map spawn not an admin spawn

2022-09-21 17:36 UTC, RatFromTheJungle commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	new /obj/effect/mob_spawn/ghost_role/borer_egg/host_spawner(T) // SkyRat Edit: Swaps Xeno egg for Borer egg
you have to use: /obj/item/borer_egg i believe

2022-09-21 17:50 UTC, Higgin commented
> > > The current map spawn is antag bait and is causing too many issues as of late, we've made the decision to swap to a borer egg in the interim until a further decision is made
> > 
> > 
> > can't you just leave it alone and ask staff to stop interfering with it as a way of crew getting themselves into trouble if they want to?
> > I'm pretty sure from every round I've seen where the xenos were either killed or broke containment, the spawn is much less antag bait than admin bait. That went even before nu-xenos.
> 
> I'm a little confused by this? It's a map spawn not an admin spawn - this isnt removing Xenos from the midround chance, just the roundstart xenobio egg spawn chance

When the map spawn happens, the biggest issue it seems to cause is players acting in anticipation of a negative staff or playerbase response if they choose to not deal with it by killing the xeno, not feeding it, letting it sit behind a shield, etc. This should be a valid choice; but the way it's been handled, it seems to me that staff intervention reinforces that it's not.

This has been backed up in the past by follow-up messages to xeno spawns being "why did you guys kill the experiment" and "you lose fifty thousand from your budget for killing it, now here's another/something else." It's also been backed up by spawned xenos being allowed to go through, particularly on lower pops, with the caveat that they should somehow hold back from expanding/attacking crew in exchange for not being shut down early when they show up as an egg.

Every time I've seen roundstart xenos get out of whack, it's been because people fucked up in containment after playing along - usually, they threw in extra monkeys or dicked around waiting before taking out the obviously-disinterested xeno. A lot of the people who played along, after that inevitably went wrong, claimed they were doing it because they feared being punished/censured by staff or the observer community otherwise. 

I'm obviously one person, but I've never seen an antag deliberately go out and set the xeno egg loose. Usually it's somebody in science goofing around in what they suppose to be the 'intended' fashion; or somebody in command cringing from acting decisively to cut it off because they're reasonably led to believe they don't have a choice but to accept the unforced error or be seen as in bad faith. 

This is one of the few places where a policy solution fits a policy problem: if you make the policy explicitly to let the crew choose what they do and not interfere in it, you've restored meaning to the choice. That might mean people will sometimes choose to sink themselves by screwing with the xenos, maybe even as antagonists, but that's fine; they might just as soon firebomb the egg roundstart, but that's fine too. There's very little lost on a midround spawn if it gets wiped out as soon as the crew might decide to do so

2022-09-21 18:40 UTC, tf-4 commented
While I get where you're coming from, getting staff to stay away from the situation does not fix the community response issue which is just as pertinent.

And entirely irrespective of the actual choice, I don't think having an antagonist as round-impactful as xenos spawn in literally any other way than dynamic or a conscious admin decision is a good idea.

2022-09-21 18:46 UTC, tf-4 requested changes

2022-09-21 18:46 UTC, tf-4 commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +/obj/effect/spawner/xeno_egg_delivery/Initialize(mapload) // SkyRat Edit: Swaps Xeno egg for Borer egg
```suggestion
/obj/effect/spawner/xeno_egg_delivery/Initialize(mapload)
```

2022-09-21 18:46 UTC, tf-4 commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	new /obj/effect/mob_spawn/ghost_role/borer_egg/host_spawner(T) // SkyRat Edit: Swaps Xeno egg for Borer egg
```suggestion
	new /obj/effect/mob_spawn/ghost_role/borer_egg/xenobio(T) // SKYRAT EDIT: Swaps Xeno egg for Borer egg
```
You'll also need to go into `cortical_borer_egg.dm` and at the bottom add something like
```
/obj/effect/mob_spawn/ghost_role/borer_egg/xenobio
	prompt_name = "cortical borer (xenobio spawn)"
```

2022-09-21 18:46 UTC, tf-4 commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	log_game("A borer egg has been delivered to [AREACOORD(T)]") // SkyRat Edit: Adjusts verbiage to match egg type
I actually kind of feel like the original adminlog is fine here, but I'm also not an admin so feel free to ignore.
Otherwise, just some styling adjustments.

```suggestion
	// SKYRAT EDIT START - Borer egg xenobio spawn
	message_admins("A borer egg has been delivered to [ADMIN_VERBOSEJMP(T)].")
	log_game("A borer egg has been delivered to [AREACOORD(T)]")
	// SKYRAT EDIT END
```

2022-09-21 18:46 UTC, tf-4 commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	new /obj/effect/mob_spawn/ghost_role/borer_egg/host_spawner(T) // SkyRat Edit: Swaps Xeno egg for Borer egg
No it's just incorrectly pathed, you want the spawner

2022-09-21 19:02 UTC, Zergspower commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	new /obj/effect/mob_spawn/ghost_role/borer_egg/host_spawner(T) // SkyRat Edit: Swaps Xeno egg for Borer egg
ahhhh okay

2022-09-21 19:09 UTC, Zergspower commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	log_game("A borer egg has been delivered to [AREACOORD(T)]") // SkyRat Edit: Adjusts verbiage to match egg type
I was mostly just trying to get rid of the  message to the station saying Alien Egg - i feel it could go both ways honestly

2022-09-21 22:07 UTC, Higgin commented
> While I get where you're coming from, getting staff to stay away from the situation does not fix the community response issue which is just as pertinent.
> 
> And entirely irrespective of the actual choice, I don't think having an antagonist as round-impactful as xenos spawn in literally any other way than dynamic or a conscious admin decision is a good idea.

The community response issue is the chelping of observer mains with just as much stake as they'd have any other round. I see a lot less complaining about a captive xeno getting smoked from people actually in the round.

Fair point on threat if you want to keep the round moderated, but most things dynamic rolls don't start off announced in a box where you can kill them or have to enable them to be a problem. Tying it into dynamic without raising threat levels is likely going to mean more nothingburgers.

2022-09-22 02:16 UTC, Elli-Skala commented
As a xenobio main who has taken apart with running the xeno egg project I can 100% agree you can't just ignore it most of the time due to admin intervention. 


The second thing is that in the end no matter what happens some ine gets fucked over from it
1. The xeno egg gets destroyed 
2. Xeno egg gets fed and xenos break out and start killing people 
3. Xeno bio sets up a death machine for xeno organs they can't escape from

Though I honestly see people hating borers more then xenos so I'm expecting borer egg spawn to be killed alot faster or well the borer itself as you can't really choose when it spawns. I'm also expecting alot of cases where a borer spawns and rnd just abandoneds them for a shift

2022-09-22 13:00 UTC, tf-4 requested changes

2022-09-22 13:00 UTC, tf-4 commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	log_game("A borer egg has been delivered to [AREACOORD(T)]") // SkyRat Edit: Adjusts verbiage to match egg type
Still want the styling adjustments

2022-09-22 13:00 UTC, tf-4 commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> +	new /obj/effect/mob_spawn/ghost_role/borer_egg/xeno_spawner(T) // SkyRat Edit: Swaps Xeno egg for Borer egg
```suggestion
	new /obj/effect/mob_spawn/ghost_role/borer_egg/xenobio(T) // SkyRat Edit: Swaps Xeno egg for Borer egg
```

2022-09-24 19:44 UTC, jjpark-kb commented on code/game/objects/effects/spawners/xeno_egg_delivery.dm
> -	log_game("An alien egg has been delivered to [AREACOORD(T)]")
this can all be done modularly-- also, maybe make it a timed spawner instead.

2022-09-25 18:45 UTC, Iamgoofball commented
i personally smash the xeno egg immediately because that's my goddamn slime ranching pen

2022-10-06 16:26 UTC, Gandalf2k15 requested changes
Awaiting further explanation and basis.

2022-10-06 18:15 UTC, Zergspower commented
> Awaiting further explanation and basis.

it's all in admin chat - this was just me putting the code in

2022-10-06 19:20 UTC, Iamgoofball commented
@Zergspower adminchat isn't on the actual PR and viewable by current and future developers who need to know the context of changes going in

2022-10-16 20:14 UTC, Zergspower commented
If the headmins still want it they can modularize it as i dont really know how

2022-10-16 20:14 UTC, closed without merging