incompatible species for ghostroles, and character pref for black market dealer
Skyrat-SS13/Skyrat-TG pull request #16430
Opened 2022-09-25 17:55 UTC by jjpark-kb

## About The Pull Request
two things are in this PR:
1) black market can now be whatever your pref is-- you can be your person as a black market dealer; no more forced random!
2) If a ghostrole is incompatible with your current species pref, it will notify you and ask for you to either stop trying (and let you setup a pref), or just go random appearance.

## How This Contributes To The Skyrat Roleplay Experience
Simplicity when dealing with ghost roles and species incompatibility, and allowing us to use OC for black market dealer.

## Changelog

:cl:
qol: Species incompatible check on ghostrole allows you select random appearance, rather than not allowing you to spawn.
fix: You can now select your character for black market dealer.
/:cl:

2022-09-25 17:55 UTC, jjpark-kb commented
![image](https://user-images.githubusercontent.com/55967837/192157950-fbbfda81-c7f3-47c5-ad17-56ff8b5acd9c.png)
A picture showing the prompt you get when your species in your pref is incompatible with the required species on the ghost role.

2022-09-25 19:20 UTC, GoldenAlpharex requested changes
Aside from this, looks good. I'd be down for a quick test-merge just to be sure it works, before merging it, can set this up right now since my only comments aren't related to the semantics.

2022-09-25 19:20 UTC, GoldenAlpharex commented on code/modules/mob_spawn/mob_spawn.dm
> +			return
```suggestion
			return

```

2022-09-25 19:20 UTC, GoldenAlpharex commented on code/modules/mob_spawn/mob_spawn.dm
> +					spawned_human.equip_outfit_and_loadout(outfit, mob_possessor.client.prefs)
```suggestion
					spawned_human.equip_outfit_and_loadout(outfit, mob_possessor.client.prefs)

```

2022-09-26 21:32 UTC, GoldenAlpharex approved these changes

2022-09-26 21:32 UTC, merged