Fixes broken cryo on Cargodise Lost, expands areas and APC's
Skyrat-SS13/Skyrat-TG pull request #16456
Opened 2022-09-26 18:49 UTC by Zergspower

## About The Pull Request

Recently the cryo computer somehow disappeared from the .dmm and anytime someone tries it floods the logs with errors.

## How This Contributes To The Skyrat Roleplay Experience

The freighter after the big power hammer never really got a pass to assist there, and solars simply aren't really a solution all the time given their rather finicky and terrible generation. Spreading the APC's out prevents the ship de-powering in about 50 seconds while not altering the draw of the ship. 

## Changelog

:cl:
add: Added Areas and APC's
qol: spread new areas out so power can last more than a few seconds
fix: fixed cryostation error spam
/:cl:

2022-09-26 22:03 UTC, Zonespace27 requested changes, later dismissed
Your changelog's bad (not actually saying _what's_ being changed)

2022-09-26 22:03 UTC, Zonespace27 commented on modular_skyrat/modules/mapping/code/areas/space.dm
> +// Cargodise Lose Freighter
```suggestion
// Cargodise Lost Freighter
```

2022-09-26 22:09 UTC, Zergspower commented
> 

I mean, how else would you word it? I made areas, added the cryo machine back and gave said areas APC's

2022-09-26 22:10 UTC, Zonespace27 commented
> > 
> 
> I mean, how else would you word it? I made areas, added the cryo machine back and gave said areas APC's

the changelog doesn't say where the APCs are being added (to the ruin), where the new areas are (again, in the ruin), etc.

2022-09-26 22:17 UTC, Zergspower commented
> > > 
> > 
> > 
> > I mean, how else would you word it? I made areas, added the cryo machine back and gave said areas APC's
> 
> the changelog doesn't say where the APCs are being added (to the ruin), where the new areas are (again, in the ruin), etc.

how's that?

2022-09-26 23:06 UTC, Zonespace27 commented
> how's that?

If I were to read this in-game, I'd have 0 idea what you've changed because you never say **what or where is actually changed in the changelog**

2022-09-27 01:14 UTC, Zergspower commented
> 

I did?
![image](https://user-images.githubusercontent.com/22140677/192408577-36a80a85-1437-4cff-b299-f96214616e9c.png)

2022-10-02 14:02 UTC, Gandalf2k15 approved these changes

2022-10-02 14:02 UTC, merged