[modular] arachne borgs!!
Skyrat-SS13/Skyrat-TG pull request #16477
Opened 2022-09-27 15:10 UTC by SodaPoppy

## About The Pull Request

adds in the arachne sprites from the tg pr https://github.com/tgstation/tgstation/pull/68444

![image](https://user-images.githubusercontent.com/111514167/192564053-98385068-4eb1-4dac-91d0-822366dbff3a.png)

i tested it and and i'm pretty confident works, all the code checks out but :( 

## How This Contributes To The Skyrat Roleplay Experience

they look cool!! and these add some in new player personalisation and customisation!

## Changelog

:cl:
add: syndi, service, janitor, engi, clown, mining and med arachne borgs!
/:cl:

2022-10-05 14:18 UTC, ZephyrTFA commented on modular_skyrat/modules/altborgs/code/robot_model.dm
> +		"Arachne" = list(SKIN_ICON_STATE = "arachne_med", SKIN_ICON = CYBORG_ICON_MED),
This destroys my ocd, please fix

2022-10-05 17:32 UTC, GoldenAlpharex requested changes
It would also be nice to see them all in screenshots, rather just a few.

It is, after all, a requirement for sprite changes to include screenshots of what they look like in-game.

2022-10-05 17:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/altborgs/code/robot_model.dm
> +		"Arachne" = list(SKIN_ICON_STATE = "arachne_med", SKIN_ICON = CYBORG_ICON_MED),
```suggestion
		"Arachne" = list(SKIN_ICON = CYBORG_ICON_MED, SKIN_ICON_STATE = "arachne_med"),
```

2022-10-08 11:35 UTC, SodaPoppy commented
![image](https://user-images.githubusercontent.com/111514167/194705417-0fdb0661-d8a6-41d5-b2a8-2c130731a7c4.png)
![image](https://user-images.githubusercontent.com/111514167/194705422-20cf9e05-cabd-4669-8116-2998afe2f3bf.png)
![image](https://user-images.githubusercontent.com/111514167/194705433-08b2b82d-56d3-45ae-bec4-f9ddb83bc550.png)

2022-10-08 13:56 UTC, GoldenAlpharex approved these changes
Looks good to me!

2022-10-08 13:56 UTC, merged