johnny robohand bundle balance pass
Skyrat-SS13/Skyrat-TG pull request #16571
Opened 2022-10-01 00:27 UTC by dawsonkeyes

## About The Pull Request

This PR rebalances the Robohand bundle and readds it to the traitor uplink at the cost of all 20 telecrystals.
It also fixes faulty spritework for the clothing and entirely resprites the Malorian Arms 3516 pistol altogether.

![image](https://user-images.githubusercontent.com/76002401/193375664-cc2cf0a5-2d2d-40b4-aeda-121fbfd782ab.png)

## How This Contributes To The Skyrat Roleplay Experience

The kit itself is an interesting change of pace compared to the otherwise versatile nature of other available bundles. It no longer offers excess weaponry in the form of an energy sword arm, nor do the bullets instantly embed/dismember opponents, but the pistol remains a strong weapon to rely on all the same.

## Changelog

:cl:
add: readded the robohand kit to the traitor uplink for 20tc
balance: rebalanced the robohand kit for normal gameplay
/:cl:

2022-10-01 00:29 UTC, dawsonkeyes commented
a more comprehensive list of changes
- 3516 14mm rounds no longer have any changed embed or delimb chance and, save for their wall/window penetration, are the exact same as .357 rounds now
- the bundle itself has two more magazines for a total of six, fully filling the provided belt
- the pants and vest now have their proper sprites
- the pants, vest, and glasses have been given wound armor values of 100, but are otherwise unchanged from the originals armor-wise
- esword arm has been entirely gutted from the kit, get fucked
- the robot arm is now the _left arm_ instead of the right

2022-10-01 03:48 UTC, dawsonkeyes commented
for some reason the malorian was scarborough, so i made it, you know, malorian
![image](https://user-images.githubusercontent.com/76002401/193386354-72c57b49-f386-453e-af1e-abcc5428e52a.png)

2022-10-01 08:22 UTC, tf-4 requested changes
I'd rather just see it removed, but here we are.

2022-10-01 08:22 UTC, tf-4 commented on modular_skyrat/modules/robohand/code/robohand.dm
>  	damage = 60
Drop the damage a little

2022-10-01 08:22 UTC, tf-4 commented on modular_skyrat/modules/robohand/code/silverhand_bundle.dm
> +	armor = list(MELEE = 20, BULLET = 20, LASER = 20, ENERGY = 20, BOMB = 20, BIO = 0, FIRE = 0, ACID = 0, WOUND = 100)
None of this needs 100 wound armour

2022-10-01 08:22 UTC, tf-4 commented on modular_skyrat/modules/robohand/code/silverhand_bundle.dm
> +	armor = list(MELEE = 20, BULLET = 60, LASER = 20, ENERGY = 20, BOMB = 20, BIO = 0, FIRE = 0, ACID = 0, WOUND = 100)
Lower the protections a _lot_ on this

2022-10-01 08:22 UTC, tf-4 commented on modular_skyrat/modules/robohand/code/silverhand_bundle.dm
> +	armor = list(MELEE = 15, BULLET = 60, LASER = 10, ENERGY = 10, BOMB = 40, BIO = 0, FIRE = 50, ACID = 50, WOUND = 100) //exact same as the normal bulletproof vest but wound-resistant
Still doesn't need boosted wound armour

2022-10-02 13:59 UTC, Gandalf2k15 commented
That new sprite really ain't it chief

2022-10-03 00:09 UTC, dawsonkeyes commented
> That new sprite really ain't it chief

make a better one, i never said i was good at this

2022-10-03 22:05 UTC, Zergspower commented
I dont feel this needs to be in the uplink at all, given the revolver costs 12 alone and this comes with a LOT of extra stuff.

2022-10-03 22:17 UTC, Zergspower commented
77 rounds of a slightly weaker 357 plus all additional gear just doesn't belong in here for 20tc, 
For reference, left is 20tc and right is 19

![image](https://user-images.githubusercontent.com/22140677/193695448-44c8c273-eb6d-4251-a6b9-5fc0995577e9.png)

I'm also confused by the arm swap? as from what i understand the base arm doesn't provide the same as our mutant robolimbs which is needed on the left side for charging

2022-10-03 22:50 UTC, Zonespace27 commented
> I'm also confused by the arm swap? as from what i understand the base arm doesn't provide the same as our mutant robolimbs which is needed on the left side for charging

The arm change i can understand because Johnny Silverhand's robotic arm is their left, not the right

2022-10-04 19:31 UTC, dawsonkeyes commented
> 77 rounds of a slightly weaker 357 plus all additional gear just doesn't belong in here for 20tc, For reference, left is 20tc and right is 19
> 
> ![image](https://user-images.githubusercontent.com/22140677/193695448-44c8c273-eb6d-4251-a6b9-5fc0995577e9.png)
> 
> I'm also confused by the arm swap? as from what i understand the base arm doesn't provide the same as our mutant robolimbs which is needed on the left side for charging

General consensus seems to be that this belongs in opfor if it remains ingame at all, which sounds about right.

2022-10-06 23:54 UTC, closed without merging