Removes some duplicate items from nukeop uplinks
Skyrat-SS13/Skyrat-TG pull request #16614
Opened 2022-10-03 16:27 UTC by Zonespace27

## About The Pull Request
Some tot items that we added were cheaper than the nukeop version that was **exactly the same**, this corrects that

## How This Contributes To The Skyrat Roleplay Experience
Bugs bad

## Changelog

:cl:
fix: Traitor-only items no longer show up in nukeop uplinks
/:cl:

2022-10-04 14:41 UTC, GoldenAlpharex requested changes

2022-10-04 14:41 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/uplink/uplink_items.dm
> +	purchasable_from = ~(UPLINK_NUKE_OPS | UPLINK_CLOWN_OPS)
This should be a define at the top of the file or something, to explain what it does, and to avoid repetitions if we want to change that behavior.

2022-10-04 15:22 UTC, Zonespace27 commented on modular_skyrat/master_files/code/modules/uplink/uplink_items.dm
> +	purchasable_from = ~(UPLINK_NUKE_OPS | UPLINK_CLOWN_OPS)
done

2022-10-05 01:12 UTC, tf-4 approved these changes

2022-10-06 10:55 UTC, merged