Adds some quality of life to the Cafe
Skyrat-SS13/Skyrat-TG pull request #16696
Opened 2022-10-07 05:57 UTC by MidoriWroth

## About The Pull Request

After the removal of the chemistry lab and autolathe from the Cafe, I decided to add a YouTool vendor, so people have at least some access to tools without stealing the ones from the Vox Box area. This will also add the four new imported food vendors to the Cafe lobby area, and the Syndicate clothing vendor to the hidden cave next to the Ash clothing vendor. Finally, this also adds a 30-sheet stack of plasma, uranium, gold, and silver in the bar backroom, for use in making exotic drinks.

## How This Contributes To The Skyrat Roleplay Experience

Having the YouTool added in allows easier access to tools, so people can create more custom things without taking the toolbelts in the Vox Box, and food vendors allow easier access to the newly added exotic foods. The Syndicate vendor allows the use of the Syndicate clothing, and as said above, the mineral stacks allow for better drink creations.

## Changelog

:cl:
qol: Added a YouTool and Syndicate clothing vendor to the Cafe
qol: Added the imported food vendors to the Cafe
qol: Gave the Cafe back some minerals for special drinks
/:cl:

2022-10-07 10:55 UTC, YakumoChen commented
There are already tools in the lockers, there are full belts of power tools in the same room the autolathe sits in.

2022-10-07 20:06 UTC, MidoriWroth commented
huh, had no idea those belts were actually in those lockers. even so, it would still be helpful to have the youtool there just in case =)

fair enough with the mineral amounts. people who abuse them could just be punished for doing so but whatever.

2022-10-08 01:49 UTC, YakumoChen commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +/obj/machinery/vending/imported{
you don't need to manually set the prices on these. All vending machines on other z-levels have their prices zeroed.

2022-10-08 01:49 UTC, YakumoChen commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +/obj/item/stack/sheet/mineral/plasma/thirty{
/obj/item/stack/sheet/mineral/plasma/
not /obj/item/stack/sheet/mineral/plasma/thirty

2022-10-08 01:51 UTC, YakumoChen commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +	},
as above, no need to varedit

2022-10-08 01:51 UTC, YakumoChen commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +	},
same

2022-10-08 01:51 UTC, YakumoChen commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +	},
same

2022-10-08 04:00 UTC, MidoriWroth commented
all the other machines had those edits on them

2022-10-09 06:55 UTC, YakumoChen commented
Remove the chasm please, it doesn't really make sense. You can just put a trash can or something there instead.

2022-10-09 08:59 UTC, MidoriWroth commented
chasm??

2022-10-09 16:47 UTC, YakumoChen commented
Uhh I thought there was a test merge and an admin had fucked around with the cafe to put in the things you added

2022-10-16 22:34 UTC, Paxilmaniac requested changes
Please don't just leave a stack of uranium sitting in the open on a table, its just going to irradiate anyone who uses the cafe

2022-10-17 00:46 UTC, MidoriWroth commented
> Please don't just leave a stack of uranium sitting in the open on a table, its just going to irradiate anyone who uses the cafe

uranium sheets themselves don't cause radiation, it's furniture and other stuff they are built with that causes it

2022-10-17 04:03 UTC, YakumoChen commented
uranium isn't dangerous until the stack size reaches over 30 I think

2022-10-29 05:43 UTC, MidoriWroth commented
@Paxilmaniac

2022-10-30 22:25 UTC, Paxilmaniac approved these changes

2022-10-30 22:25 UTC, merged