Makes Obj Stairs have the INDESTRUCTIBLE flag - no more blob cheese
Skyrat-SS13/Skyrat-TG pull request #16758
Opened 2022-10-10 23:23 UTC by Zergspower

## About The Pull Request

Adds the INDESTRUCTIBLE flag to prebuilt stairs, these cant be replaced by crew and can only be done via Map editing or admins pushing them in manually, response mostly to blobs having a rather cheesy advantage on Multi-Z maps. This will not affect ladders and there's no intent on changing those as they can be rebuilt.

![Stairs](https://user-images.githubusercontent.com/22140677/194966544-f7d527b2-03e5-4251-b1b7-04fa5fe82fa6.gif)

## How This Contributes To The Skyrat Roleplay Experience

Less Cheese more something idk rhyming

## Changelog

:cl:
balance: Added an indestructible flag to stairs prebuilt (not affecting tile stairs)
/:cl:

2022-10-10 23:26 UTC, jjpark-kb commented
I dislike indestructible things-- especially on station. A solution I would get behind would be able to actually create stairs.

2022-10-10 23:26 UTC, jjpark-kb commented on code/game/objects/structures/stairs.dm
> +	resistance_flags = INDESTRUCTIBLE // Skrat Edit : Prevents blobbos from cheesing and destroying irreplacable stairs.
Non-modular change.

2022-10-11 00:21 UTC, jjpark-kb commented on code/game/objects/structures/stairs.dm
> +//SKYRAT EDIT END
this is still nonmodular-- you'll need to find a place you can put this modularly, or create a dm file for it.

2022-10-11 09:42 UTC, Gandalf2k15 requested changes
Instead of this make it so stairs can be constructed. There should be very few objects with the indestructible flag.

2022-10-11 16:11 UTC, Zergspower commented
> Instead of this make it so stairs can be constructed. There should be very few objects with the indestructible flag.

Again - the issue is less about them being indestructible and more the cheese factor because multi-z sucks ass for stair visuals

2022-10-11 17:42 UTC, Paxilmaniac commented
The root of the problem is not the stairs, our players are simply unable to resist throwing themselves down a pit that is clearly full of blob, and are unable to adapt by finding one of the like 70 ladders around to get down.

2022-10-11 20:17 UTC, Iamgoofball commented
skill issues are not bugs and thus don't need fixed

the core issue here is not being able to rebuild z-level transition pieces

2022-10-13 12:56 UTC, Iamgoofball commented
this can be closed
https://github.com/tgstation/tgstation/pull/70504 resolves the core issue here

2022-10-13 14:16 UTC, Zonespace27 commented
https://github.com/tgstation/tgstation/pull/70504

2022-10-13 14:16 UTC, closed without merging