[MODULARIZING] Removes Foreigner and Adds Quirk Sanitization
Skyrat-SS13/Skyrat-TG pull request #16836
Opened 2022-10-13 16:23 UTC by RimiNosha

## About The Pull Request
BEFORE YOU REACT WITH 👎, READ!!

We already have foreigner functionality with our current prefs system. This quirk is redundant, and introduces a bunch of weird behavior on our custom species, and honestly, is more effort than it's worth when we've had this underlying functionality since newprefs became a thing.

That, and I'd rather allow people to be foreigner with any language they want!

Also, you're able to start with a recorder at round start with the loadout system, so that's already covered.
![image](https://user-images.githubusercontent.com/106692773/195650812-9c3dc97e-705b-4e76-b1fc-42d1790586b5.png)
![image](https://user-images.githubusercontent.com/106692773/195650966-4e39454b-05cd-4c63-b222-52cfa851bd3d.png)

## How This Contributes To The Skyrat Roleplay Experience
Less random language breakages, and allows for some more quirky characters (ironically) than the quirk allowed.

## Changelog

:cl:
add: Added quirk sanitization.
remove: Removed Foreigner. You are able to recreate this quirk almost exactly via removing common, and optionally giving yourself a recorder via loadout.
/:cl:

2022-10-13 18:02 UTC, theOOZ commented
foreigner quirk allowed more jobs to be played. consider opening some up, currently its very strict

2022-10-13 20:23 UTC, Iamgoofball commented
:-1: removing a vanilla /tg/ quirk rather than fixing the bugs created by skyrat's code is not a good idea, foreigner breaking means we have issues with our language code, not that foreigner itself is broken

this is removing the train because a stretch of the rail it drove over is broken

2022-10-21 19:32 UTC, GoldenAlpharex requested changes
We'll have to test-merge this first, but I think this is a good change.

2022-10-21 19:32 UTC, GoldenAlpharex commented on code/modules/client/preferences.dm
> +			sanitize_quirks()
Good call.

2022-10-21 19:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/client/preferences.dm
> +			quirks_edited = TRUE
```suggestion
			quirks_edited = TRUE

```

2022-10-26 22:11 UTC, GoldenAlpharex approved these changes

2022-10-26 22:11 UTC, merged