[MODULAR] Cleans up dorm vendor code
Skyrat-SS13/Skyrat-TG pull request #16874
Opened 2022-10-15 16:41 UTC by softcerv

## About The Pull Request
Cleans up the code for the dorm vendor. Adds in autodoc comments and implements early returns.

## How This Contributes To The Skyrat Roleplay Experience
good code is HRP

## Changelog

:cl:
code: cleans up dorm vendor code
/:cl:

2022-10-17 09:01 UTC, larentoun commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm
> +	default_price = 30
Why not use `initial()`?

2022-10-24 15:02 UTC, Zonespace27 requested changes
Just do the initial() thing and lgtm

2022-10-27 00:32 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm
> +	default_price = initial(src.default_price)
```suggestion
	default_price = initial(default_price)
```

2022-10-27 00:32 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm
> +	extra_price = initial(src.extra_price)
```suggestion
	extra_price = initial(extra_price)
```

2022-10-27 00:32 UTC, Zonespace27 approved these changes

2022-10-29 19:19 UTC, tf-4 requested changes

2022-10-29 19:19 UTC, tf-4 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm
> +	update_icon()
```suggestion
	if(choice)
		current_color = choice
		update_icon()
```
No need to early return here and I feel it's more readable this way

2022-10-29 19:19 UTC, tf-4 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/lustwish.dm
> +///Preforms checks to see if the user can change the color on the vending machine.
```suggestion
///Performs checks to see if the user can change the color on the vending machine.
```

2022-10-29 23:39 UTC, tf-4 approved these changes

2022-10-29 23:39 UTC, merged