Fixes nurse hat loadout
Skyrat-SS13/Skyrat-TG pull request #16880
Opened 2022-10-16 02:47 UTC by YakumoChen

## About The Pull Request

Gives the nurse hat the correct filepath in loadout

## How This Contributes To The Skyrat Roleplay Experience

Bugs bad

## Changelog

:cl:
fix: The nurse hat ships from loadout correctly again to trained medical personnel.
/:cl:

2022-10-16 08:57 UTC, Dreathtil commented
Hopefully this particular item ends up alright as its currently one of the items in the loadout menu broked.

```
datum/loadout_item/head/bandana
	name = "Bandana"
	item_path = /obj/item/clothing/head/bandana
```
	
The item repathing PR has it listed differently now, as it is technically the Pirate bandana in code, just blankly listed as "Bandana" as all the rest of the bandanas are now under face masks
	
Item path might have to be changed to this
	
`/obj/item/clothing/head/costume/pirate/bandana`
	
Is what it is now in the costume vendor

2022-10-16 11:07 UTC, YakumoChen commented
let me know if any other hats or items are popping up
there should have been a script done for this like in the suit PR but alas.

2022-10-16 11:56 UTC, tf-4 requested changes
just one mistype

2022-10-16 11:56 UTC, tf-4 commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_heads.dm
> +	item_path = /obj/item/clothing/head//costume/morningstar
```suggestion
	item_path = /obj/item/clothing/head/costume/morningstar
```

2022-10-16 14:41 UTC, GoldenAlpharex approved these changes
There's only a few more fixes to do for hats, mostly ctrl-shift-F mass replace sort of stuff.

2022-10-17 04:02 UTC, YakumoChen commented
I have a feeling it'd be easier to write a script than try this actually

2022-10-29 02:09 UTC, YakumoChen commented
I'll maybe work on this later

2022-10-29 02:09 UTC, closed without merging