Bluespace RPD Fixes - Timer and Beam
Skyrat-SS13/Skyrat-TG pull request #16943
Opened 2022-10-18 04:22 UTC by nevimer

a little bandaid

## About The Pull Request

This fixes the bluespace RPD's cooldown and should also fix the 1,1 beam spam and accidental deletion (and charge usage) from clicking too fast during lag. Also makes the defines and variables more human readable. 

## How This Contributes To The Skyrat Roleplay Experience

Makes it less annoying to use at range! 

## Changelog

:cl:
code: Use timers for  the BSRPD a cooldown (and makes it work)
/:cl:

2022-10-18 09:55 UTC, tf-4 requested changes

2022-10-18 09:55 UTC, tf-4 commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	var/bluespace_progress = FALSE
These are better, but still not great.

```suggestion
	var/max_charge = BSRPD_CAPACITY_MAX
	var/ranged_usage_cost = BSRPD_CAPACITY_USE
	var/in_use = FALSE
```
Something like that, doesn't have to be that, would be a bit more descriptive and clearer.

2022-10-19 03:05 UTC, nevimer commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	var/bluespace_progress = FALSE
doneso

2022-10-19 10:22 UTC, tf-4 requested changes
Almost good, just another little bit

2022-10-19 10:22 UTC, tf-4 commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	var/maxium_capacity = BSRPD_CAPACITY_MAX
```suggestion
	var/current_charge = BSRPD_CAPACITY_MAX
```
I just realised this isn't even a max

2022-10-19 10:22 UTC, tf-4 commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	if(maxium_capacity < (ranged_use_cost * (in_use + 1)))
why do we even need the weird addition to what's meant to be a boolean?
`if(current_charge < use_cost)` should be all you need, no?

2022-10-20 00:55 UTC, nevimer commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	var/maxium_capacity = BSRPD_CAPACITY_MAX
why must you troll me

2022-10-20 00:56 UTC, nevimer commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	if(maxium_capacity < (ranged_use_cost * (in_use + 1)))
idk what it does because it it would always = 2 or something

2022-10-20 01:03 UTC, nevimer commented on modular_skyrat/modules/bsrpd/code/bsrpd.dm
> +	if(maxium_capacity < (ranged_use_cost * (in_use + 1)))
ah probably to prevent spamming getting free charges, but you cant overcome it anymore now.

2022-10-20 01:15 UTC, nevimer commented
weh

2022-10-20 11:13 UTC, tf-4 approved these changes

2022-10-20 11:13 UTC, merged