[MODULAR] Re-adds the fancy kimono
Skyrat-SS13/Skyrat-TG pull request #16980
Opened 2022-10-19 07:39 UTC by YakumoChen

## About The Pull Request

I went to play my character best known for their fancy kimono and found out it was gone! What the hell? Put that shit back.

## How This Contributes To The Skyrat Roleplay Experience

It has a unique sprite that the recolourable yukata can't replicate. Also, yukatas aren't kimonos. 

## Changelog

:cl:
add: Readds the fancy-looking kimono that looked different from the others.
/:cl:

2022-10-19 07:40 UTC, glitchbow commented
THANK YOU, I missed it too.

2022-10-19 23:34 UTC, Nerev4r commented
For the sake of transparency, this item was intentionally removed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/16072.

2022-10-20 00:24 UTC, YakumoChen commented
The PR body already addresses that

2022-10-20 04:26 UTC, tf-4 requested changes
Just one very minor adjustment from me

2022-10-20 04:26 UTC, tf-4 commented on modular_skyrat/master_files/code/modules/clothing/under/costume.dm
> +	icon_state = "fancy_kimono"
```suggestion
	name = "fancy kimono"
	desc = "A traditional ancient Earth Japanese Kimono. Longer and fancier than a yukata."
	icon_state = "fancy_kimono"
	icon = 'modular_skyrat/master_files/icons/obj/clothing/under/costume.dmi'
	worn_icon = 'modular_skyrat/master_files/icons/mob/clothing/under/costume.dmi'
```

2022-10-20 11:07 UTC, tf-4 approved these changes

2022-10-22 10:31 UTC, Ebin-Halcyon requested changes
Personally against this, for the same reason as Orion has put it in the discord, far too large, it's in the uniform slot which hands overlay over and the sprite quality is generally low quality, if you want to give it a shot and try to resprite it to be better, be my guest.

Another suggestion if you do up the quality on it is moving it over to the suit slot so the hands aren't overlayed on the uniform.

2022-10-22 17:48 UTC, YakumoChen commented
@Ebin-Halcyon I'm not a spriter, I have no idea where to even start with the sprite because I don't see what's low quality about it
I can move it to the suit slot pretty easily but I really don't see where the 'low quality' claim comes from. Not really a fair ask.

2022-10-22 17:49 UTC, YakumoChen commented
![image](https://user-images.githubusercontent.com/10399117/197355301-9330c1cd-f8b6-4cb0-a669-4740d1d45cda.png)
like, it's got some basic shading already, there's nothing out of place besides the fact it's a fairly big sprite but, that's not a huge deal?

2022-10-22 19:04 UTC, Ebin-Halcyon commented
> @Ebin-Halcyon I'm not a spriter, I have no idea where to even start with the sprite because I don't see what's low quality about it I can move it to the suit slot pretty easily but I really don't see where the 'low quality' claim comes from. Not really a fair ask.

A quick list off of the low quality things of the original sprite
- Lack of outlines
- Mediocre colors
- strangely asymmetrical shading on the arms and other places

Sprites that go more than 3+ pixels off the sprite also look very garish and offputtingly large in game, ala the old victorian dresses.
In the end I can't close or merge the PR itself right now, so it's up to other maintainers. I'm just not a fan of the overall quality.

2022-10-26 21:50 UTC, glitchbow commented
> Sprites that go more than 3+ pixels off the sprite also look very garish and offputtingly large in game, ala the old victorian dresses. In the end I can't close or merge the PR itself right now, so it's up to other maintainers. I'm just not a fan of the overall quality.

Is that why Victorian dresses were removed? I find that ridiculous. I liked both the fancy kimono and the Victorian dress, the latter of which I would also like put back in but I'm new to formatting sprites for BYOND. This is something I would be willing to learn to sprite for, honestly, especially considering how much I value the character I designed with that dress. To me, these sound a little less like "quality" issues and more of difference in personal tastes. I think similar comments were once made about Tallborgs being garish and yet they're the most commonly played cyborg type in the server now.

Ideally, a good fix for the fancy Kimono would to make it colorable, outlined a little better, and _maybe_ edit the sleeve asymmetry, although you can see from the front it is a patterned, asymmetrical style dress. I assume that's what you meant by "other places". ~~Might as well PR to remove Vertical Split on Hair Gradient and Heterochromatic as a trait if we want to complain about sprite symmetry, pff.~~ I really do dislike the removal of content over the adjustment of it.

If the suit slot is needed to justify the pixel size, I'm fine with that as well. It wouldn't be realistic to put a coat over an item like this anyhow.

2022-10-27 04:46 UTC, YakumoChen commented
redoing it in #17196 because of merge conflicts

2022-10-27 04:46 UTC, closed without merging