[NO GBP] Borer QOL and fixes
Skyrat-SS13/Skyrat-TG pull request #17021
Opened 2022-10-20 01:46 UTC by Zonespace27

## About The Pull Request
No GBP since *some* of these were caused by me, but not all

- Cooldowns no longer happen if the action doesn't happen
- Empowered offspring works
- Added empowered offspring visual messages

## How This Contributes To The Skyrat Roleplay Experience
QoL good, bugs bad

## Changelog

:cl:
fix: Empowered offspring borer upgrade now works
fix: Cooldowns on borer abilities no longer occur if the ability fails
/:cl:

2022-10-22 16:31 UTC, GoldenAlpharex requested changes

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +		return FALSE
```suggestion

	. = ..()
	if(!.)
		return FALSE

```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +	if(. == FALSE)
The purpose of using `!.` instead of `. == FALSE` is that `!.` catches empty `return` statements too.
```suggestion
	if(!.)
```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +		return FALSE
```suggestion

	. = ..()
	if(!.)
		return FALSE

```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +		return FALSE
```suggestion

	. = ..()
	if(!.)
		return FALSE

```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +		return FALSE
```suggestion

	. = ..()
	if(!.)
		return FALSE

```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +		return FALSE
```suggestion

	. = ..()
	if(!.)
		return FALSE

```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +	if(. == FALSE)
```suggestion
	if(!.)
```

2022-10-22 16:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/cortical_borer/code/cortical_borer_abilities.dm
> +			return FALSE
Okay I'm tired of writing the same suggestion over and over, I think you get it by now.
```suggestion

		. = ..()
		if(!.)
			return FALSE

```

2022-10-26 04:53 UTC, Zonespace27 commented
> Looks at my code

kids, this is why you don't write code during burnout
I'll redo this later

2022-10-26 04:53 UTC, closed without merging