Fixes supermatter surge (and sadly has to nerf it) (also code cleaning?)
Skyrat-SS13/Skyrat-TG pull request #17038
Opened 2022-10-20 04:13 UTC by nevimer

## About The Pull Request
upstream bug in line 42 of supermatter_hit_procs breaks this code, it overflows into multiplying by negatives or something and as such we have to tame it down to not * by negatives??

So this PR updates our modular event by toning down the values used to not overflow it. Lame, I  know, but it makes the event function again. Also cleans up the code a bit. 

## How This Contributes To The Skyrat Roleplay Experience

good event that is worth fixing.

## Changelog

:cl:
fix: supermatter surge now doesn't overflow values??
code: cleaned up SM surge code a little bit
/:cl:

2022-10-20 11:19 UTC, tf-4 reviewed
Seems like an odd fix ngl, I'm wondering if there's a better way to do this that'll keep the high values. But I'm not at my PC to check atm.

2022-10-20 11:19 UTC, tf-4 commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
> +	priority_announce("The supermatter surge has dissipate d.", "Anomaly Cleared")
```suggestion
	priority_announce("The supermatter surge has dissipated.", "Anomaly Cleared")
```

2022-10-20 11:19 UTC, tf-4 commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
> +	starting_surge_power = our_main_engine
```suggestion
	starting_surge_power = our_main_engine.bullet_energy
```
Is this not necessary somehow?

2022-10-20 12:26 UTC, nevimer commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
> +	starting_surge_power = our_main_engine
somehow i probably backspaces that out when commiting

2022-10-20 12:26 UTC, nevimer commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
> +	priority_announce("The supermatter surge has dissipate d.", "Anomaly Cleared")
keyboard moment

2022-10-20 20:36 UTC, nevimer commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
> +	priority_announce("The supermatter surge has dissipate d.", "Anomaly Cleared")
fixed

2022-10-22 16:32 UTC, GoldenAlpharex requested changes, later dismissed
Good catch nonetheless!

2022-10-22 16:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
> +	var/obj/machinery/power/supermatter_crystal/our_main_engine
Document this variable please!

2022-10-22 16:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/supermatter_surge/code/supermatter_surge.dm
>  			return 1
Those numbers would all be better off as defines rather than just raw numbers.

2022-10-28 06:33 UTC, lessthnthree commented
Honestly the supermatter surge was tame before it broke, it was trivial to respond to by just an engineer or AI shutting off the emitters immediately.

I'd rather fix it and increase the impact instead of making it even weaker just for the sake of 'fixing' it.

2022-10-29 03:36 UTC, nevimer commented
> Honestly the supermatter surge was tame before it broke, it was trivial to respond to by just an engineer or AI shutting off the emitters immediately.
> 
> I'd rather fix it and increase the impact instead of making it even weaker just for the sake of 'fixing' it.

There wasn't really a gameplay dynamic in just turning off the emitters - no - I think surge should honestly HOLD the power high - making proper setups useful instead of just "turn the emitters off" to negate the guaranteed forced fires from ticks at impossibly high power levels. 

That is for a different PR, if it is made.

2022-11-01 19:15 UTC, nevimer commented
waiting on https://github.com/tgstation/tgstation/pull/70817 to convert this to a code improvement PR

2022-11-02 22:58 UTC, Tastyfish commented
> waiting on [tgstation/tgstation#70817](https://github.com/tgstation/tgstation/pull/70817) to convert this to a code improvement PR

Twas merged. #17309

2022-12-02 18:51 UTC, Tastyfish approved these changes
yolo

2022-12-02 19:11 UTC, nevimer commented
We can def bring the numbers back up to what they used to be now that the math issues upstream were fixed.

2022-12-02 20:32 UTC, tf-4 requested changes
Yeah the only reason I didn't merge this yet is that I was under the impression you were bringing the numbers back up and just hadn't got around to it. Do that, and we can work something out about the emitter thing

2022-12-05 20:35 UTC, nevimer commented
ok try now

2022-12-05 20:47 UTC, tf-4 approved these changes

2022-12-06 02:33 UTC, merged