Brings True Changeling code Closer to Quality Standards
Skyrat-SS13/Skyrat-TG pull request #17031
Opened 2022-10-20 03:19 UTC by nevimer

## About The Pull Request

Not a refactor but makes it use TGUI (cursed and laggy) lists instead of byond lists.

And cleans the code up a bit. 

## How This Contributes To The Skyrat Roleplay Experience

Makes it so the code is easier to follow and you lag more or less when you use devour.

## Changelog

:cl:
code: cleaned up true changeling code
/:cl:

2022-10-20 04:17 UTC, tf-4 requested changes
Nice job, just a couple things that you may as well grab while you're here.

2022-10-20 04:17 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> -		T << span_warning("We are already feasting on a human!")
WTF

2022-10-20 04:17 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("We do not have a form other than this!"))
Balloon alert with "no other form!" or something would work here

2022-10-20 04:17 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("Our human form is dead!"))
Balloon alert here

2022-10-20 04:17 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("We are still unable to change back at will! We need to wait [round(timeleft/600)+1] minutes."))
Balloon alert maybe if you can get the wording right

2022-10-20 04:17 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> -		T << span_warning("There are no humans nearby!")
God has left us

2022-10-20 04:17 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("There are no humans nearby!"))
Balloon alert

2022-10-20 04:19 UTC, nevimer commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("We do not have a form other than this!"))
I feel like that kinda desouls the whole "we" theme of changelings

2022-10-20 11:08 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("We do not have a form other than this!"))
I think there's still plenty of that even without this

2022-10-20 17:50 UTC, nevimer commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +		to_chat(horrorform, span_warning("Our human form is dead!"))
This actually makes no sense mechanically lol

2022-10-20 21:34 UTC, nevimer commented
all done

2022-10-21 01:33 UTC, tf-4 requested changes
Couple more bits then I think it'll be good to go.

2022-10-21 01:33 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
>  	if(!do_mob(usr, 50, target = lunch))
```suggestion
	if(!do_mob(usr, lunch, 5 SECONDS))
```

2022-10-21 01:33 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +			if(guts.name == "chest" || guts.name == "head")
```suggestion
			if(guts.body_part == CHEST || guts.body_part == HEAD)
```

2022-10-21 01:33 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
>  		if(prob(40) && !dismembered)
can early continue here

2022-10-21 03:51 UTC, nevimer commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
>  		if(prob(40) && !dismembered)
I don't understand how that would impact the code im sorry

2022-10-21 09:51 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
>  		if(prob(40) && !dismembered)
Well, it would be just the same as an early return except with a loop. It's a `continue`, so it won't stop it.

```
for(var/obj/item/bodypart/guts in lunch.bodyparts)
		if(prob(60) || dismembered)
			continue
		if(guts.body_part == CHEST || guts.body_part == HEAD)
			continue
		guts.dismember()
		dismembered = TRUE
```

2022-10-21 17:54 UTC, nevimer commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
>  		if(prob(40) && !dismembered)
done

2022-10-22 00:03 UTC, tf-4 commented on modular_skyrat/modules/horrorform/code/true_changeling.dm
> +			continue
```suggestion
		if(dismembered)
			break
		if(prob(60) || guts.body_part == CHEST || guts.body_part == HEAD)
			continue
```

2022-10-22 00:50 UTC, tf-4 approved these changes

2022-10-22 00:50 UTC, merged