Cleans up some of the code and balloon alerts for anvils, lets you drop them on people's heads
Skyrat-SS13/Skyrat-TG pull request #17045
Opened 2022-10-20 17:29 UTC by Paxilmaniac

## About The Pull Request
A lot of the balloon alerts in here were breaking the usual conventions, both of avoiding punctuation if possible, and of being short and concise, so I've gone and redone a few of those.
Some of the balloon alerts should've also been visible to more than just the user, just for feedback for other players.

An examine has been added giving some hints as to how to use the anvil, as well as telling players they now have the ability to unsecure and secure the anvil with right click.

Lastly, because you can now unanchor anvils, I thought it'd be funny to let players build some cartoon tier traps by making anvils dropped on people from above really hurt anyone they fall on.

## How This Contributes To The Skyrat Roleplay Experience

https://user-images.githubusercontent.com/82386923/197017513-a0c79335-5d4a-46e1-bc5c-8276aa263458.mp4

![image](https://user-images.githubusercontent.com/82386923/197017543-0142c368-c716-4b96-98cf-b3ada7fdc0b2.png)

## Changelog

:cl:
add: Dropping an anvil on someone from the z-level above may result in severe injury or death.
qol: Anvils will now tell you what's on them through examine, as well as the fact you can unanchor anvils.
code: Many of the balloon alerts in anvils have been tweaked or made visible to better fit with the standards for balloon alerts.
/:cl:

2022-10-20 17:31 UTC, PCPort commented
https://www.youtube.com/watch?v=iEiNkCJHs7Q

2022-10-20 17:32 UTC, Jolly-66 commented
What a smashing idea.

2022-10-20 17:33 UTC, RimiNosha commented
I'd say rename the anvil to "smithing anvil" instead, to make the memory grammatically correct without having to do non-modular edits.

2022-10-20 17:34 UTC, Paxilmaniac commented
not a terrible idea, I might repath it too

2022-10-20 17:43 UTC, dawsonkeyes commented
can you also make trapdoors easier to construct so I can reasonably use the icebox lower engineering area to drop an anvil on someone like it’s looney toons

2022-10-21 02:39 UTC, GoldenAlpharex requested changes
Sorry for the crushing review :)


(screw you Jolly for making me do a very shitty pun because you took the one I thought about 9 hours late 😔)

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +		return TRUE
```suggestion

	if(!do_after(user, 2 SECONDS, src))
		balloon_alert_to_viewers("stopped deconstructing")
		return TRUE

```

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +		return
```suggestion
	if(. == SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN)
		return

	if(!can_interact(user) || !user.canUseTopic(src, be_close = TRUE))
		return

```

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +	if(length(contents))
```suggestion

	if(length(contents))
```

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +		poor_target.take_bodypart_damage(40 * levels, wound_bonus = 5 * levels)
```suggestion

	if(istype(poor_target, /mob/living/carbon)) //If this mob is a carbon, break a few of their limbs
		poor_target.take_bodypart_damage(40 * levels, wound_bonus = 5 * levels)
		poor_target.take_bodypart_damage(40 * levels, wound_bonus = 5 * levels)

```

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +		return ..()
```suggestion

	if(!poor_target)
		return ..()

```

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +	poor_target.apply_damage(60 * levels, forced=TRUE)
```suggestion
	poor_target.apply_damage(60 * levels, forced = TRUE)
```

2022-10-21 02:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/reagent_forging/code/anvil.dm
> +		span_bolddanger("[src] falls on [poor_target], crushing them!"), \
```suggestion
		span_bolddanger("[src] falls on [poor_target], crushing them!"),
```

2022-10-21 13:12 UTC, Paxilmaniac commented
these reviews have crushed me

2022-10-21 14:57 UTC, GoldenAlpharex approved these changes
Looks good to me!

2022-10-22 16:35 UTC, merged