Resprites some of the Stirrup socks, adds digi variants to a few as well.
Skyrat-SS13/Skyrat-TG pull request #17058
Opened 2022-10-21 03:11 UTC by Ebin-Halcyon

## About The Pull Request

Tin, adds digitigrade variants to the socks where there weren't. Adds a new one, resprites them to use the updated GAGS palette.
Screenshots of the digitigrade variants
![image](https://user-images.githubusercontent.com/81479835/197102495-a49de0c9-cc49-498a-99cb-a7c53944911b.png)
![image](https://user-images.githubusercontent.com/81479835/197102546-8d172304-9c72-4079-b9f4-9b63e099b781.png)
![image](https://user-images.githubusercontent.com/81479835/197102569-95fe288a-a27b-452d-af4c-084ac6a01ad2.png)

## How This Contributes To The Skyrat Roleplay Experience

Updated sprites.

## Changelog

:cl:
imageadd: Thigh high and knee high stirrup socks have been resprited, and have had a digitigrade variants added.
/:cl:

2022-10-21 03:12 UTC, Ebin-Halcyon commented
Honestly forgot I added the leotard in this too lol.

2022-10-22 16:38 UTC, GoldenAlpharex requested changes
Is it normal that the side sprites for the stirrup socks (especially for digitigrades) are noticeably darker than the front and back sprites?

2022-10-22 16:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories.dm
> +	name = "Leggings - Stirrups black w/ stripe"
```suggestion
	name = "Leggings - Stirrups black with stripe"
```

2022-10-22 17:21 UTC, Ebin-Halcyon commented
> Is it normal that the side sprites for the stirrup socks (especially for digitigrades) are noticeably darker than the front and back sprites?

They're the same palette used on all dirs, It only differs on how and where the colors are used. I'll adjust them a bit to seem 'brighter'.

2022-10-22 21:42 UTC, GoldenAlpharex approved these changes
Alright seems good to me!

2022-10-22 21:42 UTC, merged