fixes broken marked one spin attack and proc and removes crusher from arena
Skyrat-SS13/Skyrat-TG pull request #17060
Opened 2022-10-21 05:47 UTC by dawsonkeyes

## About The Pull Request

This make’s the marked one’s spin attack actually work (sleep_check_death moment), makes the wendigo stomp proc indigenous to the marked one’s code (aka fixes #17055 linters), and removes the kinetic crusher from the lavaland arena

## How This Contributes To The Skyrat Roleplay Experience

The spin attack should work, the linters shouldn’t be broken, and the ash walkers shouldn’t have near-roundstart access to miner tech weaponry.

I didn’t PR these changes individually because that would only serve to farm gbp like a dickhead, and none of them are large enough to generally warrant individual pull requests.

## Changelog

:cl:
balance: kinetic crusher no longer spawns in the marked one’s arena 
fix: the marked one’s spin attack is no longer faulty, he is now a beyblade again  
/:cl:

2022-10-21 05:49 UTC, dawsonkeyes commented
> You currently have a negative Fix/Feature pull request delta of -8. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

AND THIS
IS TO GO
EVEN
FURTHER
BEYOND

2022-10-21 13:04 UTC, Paxilmaniac approved these changes
![image](https://user-images.githubusercontent.com/82386923/197202503-609053a5-efa0-4fb3-8be6-3333a25cdcf2.png)

2022-10-21 14:13 UTC, larentoun commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +/mob/living/simple_animal/hostile/megafauna/gladiator/proc/ctrl_c_ctrl_v(range, delay, throw_range) //copied and pasted wendigo slam attack, used for more slowly radiating AOE slams
`ctrl_c_ctrl_v` ???

2022-10-21 14:32 UTC, dawsonkeyes commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +/mob/living/simple_animal/hostile/megafauna/gladiator/proc/ctrl_c_ctrl_v(range, delay, throw_range) //copied and pasted wendigo slam attack, used for more slowly radiating AOE slams
see the comment
yes it’s a shit in-joke and I’ll change it

2022-10-22 21:48 UTC, GoldenAlpharex requested changes, later dismissed

2022-10-22 21:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	sleep(3)
I really don't like the usage of sleeps, I guess we won't have a choice here, eugh.

2022-10-22 21:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +				continue
```suggestion
				continue

```

2022-10-22 21:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +					continue
```suggestion
					continue

```

2022-10-22 21:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +		sleep(delay)
```suggestion

				shake_camera(target, 2, 1)

			all_turfs -= stomp_turf

		sleep(delay)
```

2022-10-22 21:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +/mob/living/simple_animal/hostile/megafauna/gladiator/proc/stomp() //short range slam with faster shockwave travel
documentation please (`/// documentation here` on the line before your proc (still keep at least one empty newline between each proc))

2022-10-28 19:18 UTC, Zonespace27 approved these changes

2022-10-29 14:30 UTC, tf-4 approved these changes

2022-10-29 14:31 UTC, merged