Converts Hawaiian Shirts to GAGS
Skyrat-SS13/Skyrat-TG pull request #17085
Opened 2022-10-21 22:41 UTC by Jureiia

## About The Pull Request
Removes the four current types of hawaiian shirt and replaces them with a single colour customisable GAGS item with two layers, one for the base shirt and one for the flowers, now the sky is the limit for your wretched colour combinations.

The changes to the 2nd centcomm map are due to hawaiian shirts being placed there so I had to replace them.

![2Yd7aomJAM](https://user-images.githubusercontent.com/53306684/197298588-1705f650-4c3d-42a5-8891-1bc01fcda908.png)

## How This Contributes To The Skyrat Roleplay Experience
GAGS Clothing is better than four different items of the same thing in different colours

## Changelog

:cl:
add: Added GAGS version of the hawaiian shirts.
/:cl:

2022-10-22 00:49 UTC, tf-4 requested changes
I'd had my eye on these, nice. Just two very small things

2022-10-22 00:49 UTC, tf-4 commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +	},
Could you make these subtypes rather than var edits?

2022-10-22 00:49 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/suits/misc.dm
> +	desc = "Strangely en vouge with aviator wearing shibas."
```suggestion
	desc = "Strangely en vogue with aviator wearing shibas."
```

2022-10-22 01:10 UTC, Jureiia commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +	},
I do not know enough about mapping to know what this means or how to do it ;(

2022-10-22 10:30 UTC, OrionTheFox commented
Sprites look good, but juuuust to double check, make sure this uses the GAGS palette 
![image](https://user-images.githubusercontent.com/76465278/197334365-87892d96-2e99-4b93-83b2-dcdf893b8c89.png)

It's slightly hue-shifted rather than pure black-to-white, helps colors pop better and look less muddy; especially important for a hawaiian shirt :b

2022-10-22 19:39 UTC, Ebin-Halcyon reviewed
Like Orion said, using the GAGS color palette looks alot better.

2022-10-25 14:54 UTC, tf-4 approved these changes

2022-10-25 22:10 UTC, GoldenAlpharex requested changes, later dismissed
Just something very minor, but it triggers my OCD.

2022-10-25 22:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/suits/misc.dm
> +/obj/item/clothing/suit/hawaiianshirt
```suggestion
/obj/item/clothing/suit/hawaiian_shirt
```

2022-10-25 22:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_suit.dm
> +	item_path = /obj/item/clothing/suit/hawaiianshirt
```suggestion
/datum/loadout_item/suit/hawaiian_gags
	name = "Colourable Hawaiian Shirt"
	item_path = /obj/item/clothing/suit/hawaiian_shirt
```

2022-10-25 22:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_vending/code/clothesmate.dm
> +				/obj/item/clothing/suit/hawaiianshirt = 5,
```suggestion
				/obj/item/clothing/suit/hawaiian_shirt = 5,
```

2022-10-25 22:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/GAGS/greyscale_configs.dm
> +/datum/greyscale_config/hawaiianshirt/worn
```suggestion
/datum/greyscale_config/hawaiian_shirt
	name = "Hawaiian Shirt"
	icon_file = 'modular_skyrat/modules/GAGS/icons/hawaiianshirt.dmi'
	json_config = 'modular_skyrat/modules/GAGS/json_configs/suits/hawaiianshirt/hawaiianshirt.json'

/datum/greyscale_config/hawaiian_shirt/worn
```

2022-10-25 22:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/suits/misc.dm
> +	greyscale_config_worn = /datum/greyscale_config/hawaiianshirt/worn
```suggestion
	greyscale_config = /datum/greyscale_config/hawaiian_shirt
	greyscale_config_worn = /datum/greyscale_config/hawaiian_shirt/worn
```

2022-10-28 01:57 UTC, tf-4 approved these changes

2022-10-28 01:58 UTC, tf-4 commented
@Ebin-Halcyon good sprite-wise?

2022-10-29 00:22 UTC, Ebin-Halcyon approved these changes
All gucci.

2022-11-01 05:32 UTC, Tastyfish approved these changes

2022-11-01 05:32 UTC, merged