Fixes Commandrobe issues. Added heads' cloaks and resupply unit.
Skyrat-SS13/Skyrat-TG pull request #17226
Opened 2022-10-29 11:23 UTC by SpaceLoveSs13

## About The Pull Request

Fixes #16749 
The Command Outfitting Station is now deconstructable and can be reconstructed with the given board.
The Resupply stocking unit for it has been added to cargo packs.
All Head of Departments cloaks can now also be vended from the Command vendor.

## How This Contributes To The Skyrat Roleplay Experience

As of right now, the command vendor, if gained brand intelligence during the event, can't be deconstructed, it has to be instead completely destroyed. This fixes that. 
The resupply unit is for those moments when a head has their items(cloaks etc) burnt or unfortunately lost or happens to have a previous head lost it/cryoed with it(nobody to retrieve)
The cloaks have always been a part of head of staffs' uniform and they do not even have any special armor, so I think it will be quite nice to have a replacement for them too.

## Proof of Testing

https://user-images.githubusercontent.com/68121607/198828518-09167140-9d7b-4ecb-9493-86ce5ab1af2c.mp4

<details>

- cloaks added
- vending unit deconstructable/reconstructable.
- orderable restocking unit.

  
</details>

## Changelog
:cl:SpaceLove
add: Central Command has decided to add restocking units for the Command Outfitting Station to reward the hardwork of Station Heads.
add: All heads can now get their nice cloaks from Command Outfitting Station!
fix: Command outfitting station can be deconstructed now.
/:cl:

2022-10-29 14:17 UTC, Zonespace27 requested changes, later dismissed

2022-10-29 14:17 UTC, Zonespace27 commented on code/modules/vending/wardrobes.dm
> +/obj/machinery/vending/access/command
modularize this

2022-10-29 15:10 UTC, SpaceLoveSs13 commented on code/modules/vending/wardrobes.dm
> +/obj/machinery/vending/access/command
done

2022-10-29 18:12 UTC, tf-4 commented on modular_skyrat/modules/command_vendor/code/vending.dm
> +/obj/item/vending_refill/wardrobe/comm_wardrobe
```suggestion
```
how did that even pass checks

2022-10-29 19:31 UTC, Zonespace27 commented on modular_skyrat/modules/sec_haul/code/misc/packs.dm
> +	contains = list(/obj/item/vending_refill/wardrobe/comm_wardrobe,)
```suggestion
	contains = list(
		/obj/item/vending_refill/wardrobe/comm_wardrobe,
	)
```

2022-10-30 02:58 UTC, SpaceLoveSs13 commented on modular_skyrat/modules/command_vendor/code/vending.dm
> +/obj/item/vending_refill/wardrobe/comm_wardrobe
This part is necessary to run. This is exactly how the restocking unit is defined in wardrobe code in upstream as well.

2022-10-30 03:00 UTC, tf-4 requested changes
Not sure why you've duplicated the definition of the vendor, exactly, directly atop one another. Just have one

2022-10-30 03:00 UTC, tf-4 commented on modular_skyrat/modules/command_vendor/code/vending.dm
> +/obj/item/vending_refill/wardrobe/comm_wardrobe
```suggestion

/obj/item/vending_refill/wardrobe/comm_wardrobe
```
I didn't read it properly.

2022-10-30 08:43 UTC, SpaceLoveSs13 commented
> Not sure why you've duplicated the definition of the vendor, exactly, directly atop one another. Just have one

fixed it

2022-10-31 14:41 UTC, tf-4 commented on modular_skyrat/modules/sec_haul/code/misc/packs.dm
> +/datum/supply_pack/vending/wardrobes/security
wrong typepath
```suggestion
/datum/supply_pack/vending/wardrobes/command
```

2022-10-31 14:42 UTC, tf-4 commented on modular_skyrat/modules/command_vendor/code/vending.dm
> +/obj/item/vending_refill/wardrobe/comm_wardrobe
still need this

2022-11-01 00:36 UTC, tf-4 approved these changes

2022-11-01 00:40 UTC, merged