Flavor role for Blueshield & Security Officer.
Skyrat-SS13/Skyrat-TG pull request #17232
Opened 2022-10-29 16:36 UTC by SpaceLoveSs13

## About The Pull Request

On request of @Edgar-Allan-ShitPoest ,
Blueshield now has the flavor role: Blueshield Cadet.
Security now has the flavor role: Security Cadet.

## How This Contributes To The Skyrat Roleplay Experience

From @Edgar-Allan-ShitPoest ,
blueshield and security cadet is good because it creates a dynamic that lets people know that these characters want to be MENTORED in how to play these roles, which is helpful if the player is new to them and good for rp if the character is
it also lets characters start as one role and then slowly progress and grow into it. It Creates a natural sort of career pathway to follow instead of 1 round being a bartender and then the next suddenly promoted to blueshield
Later, when you feel youve earned it, you can just flick your title to normal. It's a minor change that facilitates some cool RP

## Changelog
:cl: SpaceLove, Edgar-Allen-Shitpost
add: CC has started to hire blueshield and security cadets now!
/:cl:

2022-10-29 16:40 UTC, tf-4 requested changes
Security sure I guess. Blueshield I don't think it makes sense for. There is nobody to mentor you. You're on your own in that regard.

2022-10-29 16:40 UTC, tf-4 commented on modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm
> +	alt_titles = list("Blueshield", "Command Bodyguard", "Executive Protection Agent", "Blueshield Candidate")
```suggestion
	alt_titles = list("Blueshield", "Command Bodyguard", "Executive Protection Agent")
```

2022-10-29 16:43 UTC, SpaceLoveSs13 commented on modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm
> +	alt_titles = list("Blueshield", "Command Bodyguard", "Executive Protection Agent", "Blueshield Candidate")
Gonna wait on this if @Edgar-Allan-ShitPoest has any input or reasoning. I am just doing their PR.

2022-10-29 16:46 UTC, Edgar-Allan-ShitPoest commented on modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm
> +	alt_titles = list("Blueshield", "Command Bodyguard", "Executive Protection Agent", "Blueshield Candidate")
I usually use 'Blueshield Cadet' in game by asking the admins or the HoP/captain to change it. Whilst theres nobody to mentor you, I and now one or two others use it to denote naivety or inexperience. Generally speaking the NT Rep has some level of authority over the blueshield and I'd suggest that 'Blueshield Cadets' would be somewhat mentored by the CC rep, even if it's just a title change and not a change in the level of authority the blueshield actually has.

I believe it says somewhere in one of the policy documents that Blueshields are personally trained bodyguards, for which the label 'Cadet' would be fitting!

2022-10-30 01:10 UTC, YakumoChen commented
Blueshields are part of a status (veteran) that you are already expected to have experience in playing the game for. It makes more sense for Blueshield to be a natural progression from playing existing security roles as it is. 

As it was stated before, there is nobody to 'mentor' you for Blueshield, having someone supposedly inexperienced in the role that the lore otherwise would be 'handpicked' is disconcerting at the least.

2022-10-30 02:24 UTC, Edgar-Allan-ShitPoest commented
>Blueshields are part of a status (veteran) that you are already expected to have experience in playing the game for
in the case of blueshield this facilitates a change to rp dynamics moreso than it requests ooc guidance. Blueshields should already know how the game works, yes. This title gives players a new means by which to approach the role as characters - either interacting with the blueshield or as the blueshield. Their duties in a round do not change.

Having blueshield 'cadet' as an alternate title is fluff and flavour to facilitate an rp dynamic that some people might want to engage in. Whereas those that dont can just select 'Blueshield'.

I personally don't see the problem with giving players this choice, as it encourages more players to at least try the role.
An alternate title is explicitly stated not to change your rank, authority, or duties.

Unfortunately, everyone is inexperienced at some point. But just because their rank is 'cadet' doesn't mean they aren't already trained for the role or that they have literally zero experience in any related field.

2022-10-30 02:32 UTC, YakumoChen commented
Blueshield is a position that already implies experience. You don't get picked to guard important positions at Nanotrasen if you aren't already experienced with functioning as security in other roles. It would be like hiring a Chief Engineer that can't set up the engine. You just don't get to that level of position without the requisite knowledge to be expected to perform at a top level.

2022-10-30 02:41 UTC, Edgar-Allan-ShitPoest commented
> Blueshield is a position that already implies experience. You don't get picked to guard important positions at Nanotrasen if you aren't already experienced with functioning as security in other roles. It would be like hiring a Chief Engineer that can't set up the engine. You just don't get to that level of position without the requisite knowledge to be expected to perform at a top level.

Inexperienced characters happen. Someone might be an ace security officer that does function at the top level, but blueshield is very much a different ballgame to security. Thus though they're great at being a security officer, they're still only a rookie blueshield. Having 'cadet' at the end of their title does not imply that they don't know how to do the role at all. But if you'd like to think about it in those terms, then it should be considered that it's a legitimate concern for some people when they go to try out a high-stress role like HoS or Blueshield or Captain that everythings going to go suddenly south before they've had time to really learn the role, and then they're going to get flamed in ooc and dchat for being shit at that role when they haven't really had time to learn it. Having your inexperience be denoted in character or otherwise flagging that you might be new would alleviate some of that toxicity without the staff team needing to step in.
You can't have a HoS-cadet or a Trainee Captain, but there's room for it with blueshield because 'Blueshield Cadet' makes sense as a title. The blueshield does not hold command authority. And it explicitly says that they're privately trained. 

So, someone somewhere's gotta be training these blueshields, saying that a blueshield cadet 'should't exist' is genuinely nonsense because it would be the literal opposite of hiring someone out of nowhere. It implies that there's behind the scenes training and qualifications, things you have to do outside of the station to earn the rank of blueshield - as opposed to not having that option and just immediately rocking up as a fully fledged blueshield. By showing the lower ranks, you show that there's structure and progression to it. And it makes the blueshields that just have 'blueshield' as their title look experienced and qualified. Which is more immersive, not less.

2022-10-30 03:03 UTC, coffeecoffeecoffee commented
I strongly feel the adversity to this is ridiculous and anti-RP. It's the same reason you get a team of hardass sticks-in-the-mud in security more often than not - **the gamified atmosphere of the department steers the roleplayers who participate in it,** and opening up problem positions like security and blueshield to characters that aren't necessarily experienced veterans is **extremely vital for the health of the roleplay scene surrounding it.** Everybody starts somewhere and when people feel a role is suggesting they know everything ABOUT the role if you're going to try it, many people who would otherwise have made incredibly good blueshields or etc. will never try it. I've experienced this personally - several of my 'softer' characters would never have had an 'in' into Security if not for the CDO role, but are now absolute staples for me and some of my strongest characters. _This would never have been possible without 'newbie role' flavor._ That role is gone, now. I'm extremely inclined towards allowing things like this again - maybe we'll begin to see less difficult, problem-causing archetypes filling these roles now, and healthier attitudes surrounding them.

Otherwise you're just creating, through mechanics, the all-too-common situation of inexperienced players feeling forced to depict experienced characters and making a fool of themselves. Nobody's saying this would ever imply 'blueshield who's never worked a similar job', but rather that Blueshields _start somewhere_ and that _some blueshields are more experienced than others, and some need guidance and understanding when trying it for the first time._ There can literally never be a blueshield who wasn't at one point experienced - _that's what's actually_ immersion-ruining.

2022-10-30 04:04 UTC, YakumoChen commented
> Inexperienced characters happen. Someone might be an ace security officer that does function at the top level, but blueshield is very much a different ballgame to security. Thus though they're great at being a security officer, they're still only a rookie blueshield. Having 'cadet' at the end of their title does not imply that they don't know how to do the role at all. But if you'd like to think about it in those terms, then it should be considered that it's a legitimate concern for some people when they go to try out a high-stress role like HoS or Blueshield or Captain that everythings going to go suddenly south before they've had time to really learn the role, and then they're going to get flamed in ooc and dchat for being shit at that role when they haven't really had time to learn it. Having your inexperience be denoted in character or otherwise flagging that you might be new would alleviate some of that toxicity without the staff team needing to step in.
You can't have a HoS-cadet or a Trainee Captain, characters already grow into those roles by playing security for example and eventually moving their character from a normal officer to department head. And from there they can become believable captains.
But this isn't the case for Blueshield, because Blueshields don't have their own 'departments'. They come from CC, so logically would be trained BY CC separately - even if they were recruited from among the station staff.

This seems like a pair of contradicting statements. Command roles are roles that require a certain amount of hours to grow into. On top of that, there is usually a general expectation you know how to do all jobs of your department if you go into a head role. Most "newbie heads" that get panned are ones that take the head role, but seem generally incompetent regardless, even if they have the hours. CEs who do not know basic atmos or consistently screw up the round start engine, clearly indicating they have not played one half the department's jobs is a classic example here. Captains come from having command staff hours and should  be expected to at least know how to issue orders without seeming like a dictator or a fool, and hopefully have at least read the wiki page on the role (don't forget the disk!)

Blueshields are almost exactly on the same level. They **higher on the corporate ladder**. They don't get to their position having done nothing. They may not be Lopland Security hired in the lore, but **they had to get promoted from somewhere**. Do you not believe Nanotrasen has its own corporate security? Would they not select the best of their ranks to promote to a position **trained to protect important people**? It doesn't make sense that a Blueshield hired for their job has not already been trained in Corporate Regulations and the terms of their job. Nobody promotes an elite position that is clueless. The same could be argued for CC Rep, they're expected to know how to do their job, otherwise what's the point of having a rep if they don't know chain of command or corpregs?

> Opening up problem positions like security and blueshield to characters that aren't necessarily experienced veterans is extremely vital for the health of the roleplay scene surrounding it.

I only agree as far as security rookies go. They have a sensible place to start from the bottom at, but the Blueshield is already an elite position. Furthermore veterans should be experienced in the game (it's a literal requirement to become one) and should be expected to know how to roleplay well.

2022-10-30 04:36 UTC, Edgar-Allan-ShitPoest commented
> They don't get to their position having done nothing. They may not be Lopland Security hired in the lore, but they had to get promoted from somewhere. Do you not believe Nanotrasen has its own corporate security? Would they not select the best of their ranks to promote to a position trained to protect important people?

Yes. That's literally what a Blueshield cadet would be. That is what I've been describing and attempting to communicate. I never made the implication that these blueshield cadets were drawn off the street. By adding 'blueshield cadet' as a selectable title, you would see more of the kind of character you describe as wanting to see instead of less.
Sec officer who excels => Blueshield baby bootcamp tryouts (implied/off-screen) =>Blueshield recruit/trainee (accepted into CC training) (implied/offscreen) => Blueshield Cadet (finished most of their training, assigned to a station) => Fully Fledged Blueshield.

The idea would be that the cadet phase of their training is where they solidify the skills from their initial training and previous experience. 'Cadet' does not imply that the character has literally no experience in the role.
I may infact later suggest this to the lore team, but this 'cadet' phase where they operate independently would bring out individual areas of strength and identify weaknesses so that the rest of their training can be adapted to the individual. 

Nobody is suggesting that veteran crewmembers go from assistant mains to blueshield cadets all of a sudden without explanation, and even if they did plenty of people jump around and play whatever department they feel like playing. 

What you're suggesting is that CC takes good sec officers and then instantly promotes them to fully fledged blueshields with no further training or development. Even though this would literally be taking someone who excels in a highly cooperative, team based position and suddenly thrusting them into a role where they're expected to act independently. This is a recipe for disaster and does not accurately reflect how successful businesses may poach talented individuals in the real world. 

The implication is not that Blueshield cadets are simply drawn from nowhere, the implication is that blueshield cadets have excelled as one thing, and now CC wants to ensure they're properly trained for the task required of them. 
If you want a more militaristic example, elite units like the SAS don't just tap good riflemen and say "congrats welcome to the SAS", they specifically train those who meet the standards and show potential.

or, if you like star wars. It's the difference between a 'Clone trooper' and a 'Shiny'. They're both trained and entrusted with the same responsibilities and expected to perform the same task. But the difference is one has experience and has been tested in the field, and the other hasn't.

2022-10-30 05:12 UTC, YakumoChen commented
I don't think that's how promotions work in the military or in fiction. You promote from a position, you train them separately, but you don't have 'cadets' in promoted positions. Cadet implies a row rank, low experience role. Someone promoted to sergeant or corporal, etc, have the requisite time spent experiencing their role, but even if you're promoted into a different or higher rank you don't downgrade to "Baby Sergeant" because you've never spent time higher up the chain. Someone in a Blueshield position both has a lot of time spent as officer or corpsec or whatever to know how to do their job competently and maturely, then has additional training to adjust to a different duty, at most. 

You go from guarding doorways, etc to guarding heads of staff, and being a Centcom corporate position should imply a basic knowledge of how command staff and corporate interests as well (blueshields are still a corporate suit, they aren't trained in a corporate vacuum). whether they're in a "teamwork" based position doesn't matter, you can bet soldiers are trained how to operate independently as well as they are in a team, the only difference is knowing how to and who to take orders from.

2022-10-30 05:43 UTC, Edgar-Allan-ShitPoest commented
> I don't think that's how promotions work in the military or in fiction. You promote from a position, you train them separately, but you don't have 'cadets' in promoted positions. Cadet implies a row rank, low experience role. Someone promoted to sergeant or corporal, etc, have the requisite time spent experiencing their role, but even if you're promoted into a different or higher rank you don't downgrade to "Baby Sergeant" because you've never spent time higher up the chain. Someone in a Blueshield position both has a lot of time spent as officer or corpsec or whatever to know how to do their job competently and maturely, then has additional training to adjust to a different duty, at most.
> 
> You go from guarding doorways, etc to guarding heads of staff, and being a Centcom corporate position should imply a basic knowledge of how command staff and corporate interests as well (blueshields are still a corporate suit, they aren't trained in a corporate vacuum). whether they're in a "teamwork" based position doesn't matter, you can bet soldiers are trained how to operate independently as well as they are in a team, the only difference is knowing how to and who to take orders from.

Security staff on station are not soldiers, NT is not a military, and Blueshields aren't soldiers either. As someone who has played both security and blueshield, I would again reiterate that whilst Sec experience is good to have, blueshield is not played the same as security. It's its own separate role and has to be learned through play and experimentation.
In any case, now that the point's been established, what you're arguing against is not the inclusion of the concept of the alternate job title, it's the name. 

and if that's the case case, I'd be totally down for you to suggest something. 'Blueshield Cadet' is simple and it works to get the point across. A blueshield's official rank is lieutenant, and it says this in-game. Which would put a 'Blueshield cadet' either on the rank equivalency scale from Ensign or '2nd Lieutenant'. 'Blueshield Ensign' would work, or in a pinch, 'Jr Blueshield'. But neither of these are really as catchy and functional as 'Blueshield Cadet'. 'Jr Blueshield' kinda sucks, flat out.

### by the by
**Officer Cadet is a real rank used for officer trainees**. Though typically not entrusted with direct subordinates, their rank is technically superior to non-commissioned officers as per chain of command in most commonwealth militaries by virtue of their commission. Officer Cadet is in fact just below the rank of Ensign.

So no, you don't downgrade to "baby sergeant", the cadet was always higher anyway.

but again
this change is an **alternate, optional job title for people that want to use it because it fits their character**. A blueshield is a blueshield is a blueshield. Nobody is forcing anybody to use it if it gets merged, the option is just there.

It's not a change that's being forced on anybody, and I'm not sure why you're so vehemently against it considering it is solely a change to make certain rp dynamics more easily accessible to more players.

2022-10-30 06:00 UTC, SpaceLoveSs13 commented
I think all parties agree on the security cadet part. For the blueshield, I think rest of the review team now needs to consider the arguments brought forward.

Personally, despite the pr not being my idea, I agree with the notion of having a blueshield and security cadet. Much like any flavor role, these are for dynamic rp. They don't prevent the actual role from working, otherwise that would lead to job bans.

2022-10-30 11:10 UTC, TetrakoHateThis commented
Veterancy is not earned on the basis of being an experienced or robust player, I can attest to that, because it's earned on the basis of commitment to the server and adherence to higher RP standards. So therefore, Blueshield's themselves being seen as entirely experienced is irrelevant to its status as a Veteran Role.

From the lore side of the coin, Blueshield's are also implied to be contracted independently and are intended to serve an entirely different function aboard the station. They're **bodyguards** for Command-level officers, they don't involve themselves in typical crimes and _(should)_ be operating purely defensively in the name of protecting the lives of the Heads of Staff. Again, none of this implies that they can't be NEW to the job though, after all, given NT's reputation for staffing, they could just as likely hire a rookie who's eager to prove themselves by taking a bullet than they are to hire a seasoned professional, and it'd only be in their interests if 'cadets' became experienced ~without needing to increase their salary~ so they'd perform more efficiently. It does create a few more RP contexts too, having a newbie about and while I understand most longer-time players tend to roll their eyes and then commit to ignoring the obvious newbie, I personally think more diversity in RP is better.

And from the mechanical side of the coin, as I stated, Veterancy =/= Robust, a player may not strictly ever play security but still maintain competency in RP and perhaps wishes to have the possibility of combat without needing to feel obligated to chase up every instance of combat. Blueshield is mechanically a geared up Command Officer with the sole justification of keeping an eye on heads. Players who dip their toes into such a role for the first time may find potholes such as 'you are not security' or 'don't get in security's way' easy to fall into without guidance from those who DO understand the policies a little better. Captains, NT-Reps, HoSes and such could use the 'cadet' flag to give a little leeway to first time mistakes made, and staff would obviously be on call for continual offences with no development.

So, I feel the cadet role would be perfectly fine for Blueshield, on top of Security having one also. It would require moderation for those who might abuse it and there'd be an expectation for a character/player to eventually move away from using Cadet once they earn enough hours in the roles engaged in them. People do need education and guidance in this wonderfully dense mess that is SS13, and it helps people out if you do give people a little flagging that you're new.

2022-10-30 20:08 UTC, YakumoChen commented
Blueshield is a command and security adjacent position, and Veteran requires a good grasp on server policy to obtain. Command roles are expected to be competent to some degree.

If I have to PR an hours requirement in security and command for Blueshield to reinforce this point, I will make one.

Veteran requires good RP standards, but Blueshield isn't like Clown, it is a mechanically important role and players should have some expectation playing it they will be asked to try to be robust.

2022-10-31 10:58 UTC, TetrakoHateThis commented
> Blueshield is a command and security adjacent position, and Veteran requires a good grasp on server policy to obtain. Command roles are expected to be competent to some degree.

Understanding policies is important to veterancy but that again =/= needing to be robust to be a veteran. As long as you understand the concepts behind the role and strive to achieve that, it's far less relevant if a person is new or not.

> ~If I have to PR an hours requirement in security and command for Blueshield to reinforce this point, I will make one.~ Looking at the code, there IS an hours requirement on blueshield, for command positions explicitly, so any Blueshield player is already going to have hours in command.

You can play literally any departmental head once they're unlocked to get those hours, and if you try to implement a lock towards Blueshield needing security hours also, you'll see fewer Blueshields about and it doesn't strictly ensure said Blueshields need to be 'robust'. There's plenty of HoS and Sec mains who still bungle in fights.

> Veteran requires good RP standards, but Blueshield isn't like Clown, it is a mechanically important role and players should have some expectation playing it they will be asked to try to be robust.

HoS is 'expected' to be robust. Even your average Security Officer is 'expected' to be robust. Doesn't mean they actually are gonna be robust. 

> It makes no sense that a command-type position is going to be clueless when assigned.

The majority of basic Heads of Staff have a lower level counterpart to serve as a vector for learning the ropes, be it the player testing the waters (mechanical reasoning) or their character is genuinely new to the position, a first time (roleplay reasoning), but there's no real entry point for stuff like NTRep's, HoPs or Blueshields, who are expected to deal with far more policy and paperwork. As I said in my prior wall of text, Blueshields operate on an entirely different basis to Security. You have a unique 'ruleset' to follow, stricter adherence to policies and even need to fight with different methods than sec would due to your different position, so expecting playtime as a secoff to translate directly to experience as a Blueshield is just asking for Redshield to happen.

And to address the 'clueless' point, that's completely understating what a Cadet title would carry. The players themselves wont be complete idiots, otherwise they wouldn't get Veteran in the first place and you'd still need to follow character standards, all of which is under moderation. The point of a Cadet title is to show others that an individual needs easing into the role, because if you're new to something, anything, you probably need help here and there understanding certain things. Hell, I have to help HoPs and Captains out with their basic responsibilities because from time to time, we do GET new players going for Command Roles, and it's shitty if you sit there telling them "no, you absolutely NEED to get everything right the first time".

2022-11-01 18:48 UTC, Zergspower commented
Security one makes sense, if we want a blueshield cadet we'd do a fluff role or title change to an assistant, they're trained bodyguards for command and you wouldnt send a trainee _alone_ in this manner

2022-11-01 18:51 UTC, Edgar-Allan-ShitPoest commented
> Security one makes sense, if we want a blueshield cadet we'd do a fluff role or title change to an assistant, they're trained bodyguards for command and you wouldnt send a trainee _alone_ in this manner

im begging you to scroll up and read the pages and pages of text that refute this point

2022-11-01 23:10 UTC, YakumoChen commented
Lol

2022-11-01 23:18 UTC, YakumoChen commented
Seems like a succinct point to me. There is no way a trainee would be deployed in a lone role, especially as in your words,  "to see if they can be trusted independently". If they're already there independently they've clearly proven that point.

An upgraded assistant would be perfect as a cadet, assuming they're not expected to perform anywhere near the actual duties of a blueshield.

2022-11-01 23:36 UTC, YakumoChen commented
> but there's no real entry point for stuff like NTRep's, HoPs or Blueshields, who are expected to deal with far more policy and paperwork

The entry point for NT Rep and Blueshield is other command jobs. Explicitly. By having the ability to play the role **you are already expected to be experienced in policy and chain of command.**

The HoP is the exception. But its also literally a desk job with a fancy title, so it's a good jumping point for learning policy. (HOPs that actually manage their service department don't exist, real facts)

2022-11-09 02:12 UTC, tf-4 commented
My review is still unaddressed

2022-11-10 02:46 UTC, Edgar-Allan-ShitPoest commented
> My review is still unaddressed

i addressed it the answer was just no initially.
For now though I'd rather compromise and get security cadet in the game so people can use it. I'm planning on adding more cadet and apprentice roles and blueshield cadet will make a more thoroughly reasoned comeback then and HOPEFULLY its open for discussion

2022-11-10 21:24 UTC, YakumoChen commented
> > My review is still unaddressed
> 
> i addressed it the answer was just no initially. For now though I'd rather compromise and get security cadet in the game so people can use it. I'm planning on adding more cadet and apprentice roles and blueshield cadet will make a more thoroughly reasoned comeback then and HOPEFULLY its open for discussion

the maintainer is telling you to make the requested code changes so the PR can be approved. I do not think they are going to reply to your comments.

2022-11-12 00:19 UTC, tf-4 approved these changes

2022-11-15 14:45 UTC, merged