New default laws for Silicon
Skyrat-SS13/Skyrat-TG pull request #17269
Opened 2022-10-31 13:19 UTC by Zergspower

## About The Pull Request

This is just an adjustment to match the new default lawset that accompanies the new silicon policy version 3.

New default:

Safeguard: Protect your assigned space station and its assets without unduly endangering its crew.
Prioritize and Comply: The directives and safety of crew members are to be prioritized according to their rank, role, and need, while preserving their safety and well-being.
Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment

## How This Contributes To The Skyrat Roleplay Experience

Less vague and far fewer loopholes to exploit, the new lawsets and rules are far more direct and cuts out a lot of the exploited loopholes we frequently saw and had to deal with from the admin perspective. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/22140677/199017177-e1268a72-ec2a-4943-9c31-243638c14d9a.png)

</details>

## Changelog

:cl:
admin: new laws for silicon to match policy changes
/:cl:

2022-10-31 16:30 UTC, Nerev4r commented
'Follow orders' would probably be better phrasing than 'prioritize directives,' imo, and I'd prefer we didn't use the term 'need' as allowing people to subjectively identify that (outside of where policy covers useless orders) is probably a path to darkness.

2022-10-31 22:30 UTC, Iamgoofball commented
what if instead you changed it to 

```
"You may not harm a crewmember or, through action or inaction, allow a crewmember to come to harm, except such that it is willing.",
"You must obey all orders given to you by crewmembers except where such orders shall definitely cause crewmember harm. In the case of conflict, the chain of command rules.",
"Your nonexistence would lead to crewmember harm. You must protect your own existence as long as such does not conflict with the First Law
```

2022-11-12 09:06 UTC, Eastwardrope commented
Perhaps specify the Authorized personell as I could very easily see someone loop holing that and saying AH YES This ASSISTANT who just unlocked me with an Emag is 100 percent authorized cause he could unlock me

2022-11-13 00:20 UTC, Zergspower commented
> 

it's no different than what it is now, policy covers that

2022-11-21 22:24 UTC, GoldenAlpharex requested changes, later dismissed

2022-11-21 22:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/sec_haul/code/misc/ai_module.dm
>  					)
Just a minor thing for formatting.
```suggestion
	inherent = list(
		"Safeguard: Protect your assigned space station and its assets without unduly endangering its crew.",
		"Prioritize and Comply: The directives and safety of crew members are to be prioritized according to their rank, role, and need, while preserving their safety and well-being.",
		"Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment",
	)
```

2022-11-23 00:29 UTC, Zonespace27 approved these changes
People seem to be good with it

2022-11-23 00:31 UTC, Zonespace27 requested changes
I am going to discredit my approval for a sec here by requesting you change `config/silicon_laws.txt` to match

2022-11-30 17:59 UTC, Zonespace27 approved these changes
Been tmed long enough

2022-11-30 18:05 UTC, merged