Added a donator item.
Skyrat-SS13/Skyrat-TG pull request #17281
Opened 2022-10-31 22:50 UTC by Useroth

![image](https://user-images.githubusercontent.com/37159550/199124518-3888c015-8403-4a3d-8637-cfcb01cdaaa5.png)

:cl:
add: Added a donator item
refactor: Moved some GAGS config files that I stumbled upon, while adding the above, into a more logical location
/:cl:

2022-11-01 03:58 UTC, YakumoChen commented
I get that this is a donator item but it's just making an existing item into a GAGS item. Why not just make the existing heels available as GAGS?

2022-11-01 13:05 UTC, Draggeru commented
> I get that this is a donator item but it's just making an existing item into a GAGS item. Why not just make the existing heels available as GAGS?

I'm the donator in question, my request was the heels as gags AND to add the dominant heel step sound effect

2022-11-01 16:47 UTC, YakumoChen commented
Right. The correct move would be to replace the existing, public heels with this sprite (the lewd heels I think?), then make the donator item a child with the sound effect

Although I thought the existing heels also had the sound effect, which would make this less of a donator request and more of a code improvement request. 

Locking a code improvement behind donator status is not the way to go about this regardless.

2022-11-01 17:21 UTC, Draggeru commented
> Right. The correct move would be to replace the existing, public heels with this GAGs (the lewd heels I think?), then make the donator item a child with the sound effect
> 
> Although I thought the existing heels also had the sound effect, which would make this less of a donator request and more of a code improvement request.
> 
> Locking a code improvement behind donator status is not the way to go about this regardless.

I am 100% okay with this and encourage it as I do like to share!

2022-11-02 01:10 UTC, Useroth commented
Implemented the changes; made sure it still works
![image](https://user-images.githubusercontent.com/37159550/199371091-1f645015-f99a-4fce-8006-7e898ea87717.png)

2022-11-02 04:56 UTC, Zonespace27 approved these changes
Looks fine to me

2022-11-02 04:59 UTC, Tastyfish requested changes
I'm going to trust that the greyscale stuff renders correctly in-game.

However, you made it fancy_heels

2022-11-02 04:59 UTC, Tastyfish commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/shoes/fancyheels/drag
```suggestion
/obj/item/clothing/shoes/fancy_heels/drag
```

2022-11-02 04:59 UTC, Tastyfish commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/shoes/fancyheels/drag/Initialize(mapload)
```suggestion
/obj/item/clothing/shoes/fancy_heels/drag/Initialize(mapload)
```

2022-11-02 04:59 UTC, Tastyfish commented on modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
> +	item_path = /obj/item/clothing/shoes/fancyheels/drag
```suggestion
	item_path = /obj/item/clothing/shoes/fancy_heels/drag
```

2022-11-02 05:25 UTC, Tastyfish approved these changes

2022-11-02 17:04 UTC, merged