Fixes Sofa In Void Raptor Prison
Skyrat-SS13/Skyrat-TG pull request #17423
Opened 2022-11-07 23:33 UTC by BardTheBard

## About The Pull Request

This PR simply corrects an improperly places sofa in the Void Raptor prison, swapping the sides around so they fit together.

## How This Contributes To The Skyrat Roleplay Experience

Fixes a small issue in the map, but an issue nonetheless that was overlooked.

## Proof of Testing

- [ ] Tested on a private server.

<details>
<summary>Screenshot</summary>
  
![brigsofa](https://user-images.githubusercontent.com/94123167/200437424-224206c8-2930-4105-aef3-5fd452f2f2e7.png)

</details>

## Changelog
:cl:
fix: fixes an incorrectly placed sofa in prison.
/:cl:

2022-11-07 23:48 UTC, Jolly-66 requested changes
Please be more with specific with your CL. This is play facing, and having it be "fixes sofa in a prison" doesn't really help. Something like "[Void Raptor] Sofas in the prison were fixed" or "Sofas in Void Raptors prison were fixed" would be more suitable.

2022-11-17 00:09 UTC, BardTheBard commented
> Please be more with specific with your CL. This is play facing, and having it be "fixes sofa in a prison" doesn't really help. Something like "[Void Raptor] Sofas in the prison were fixed" or "Sofas in Void Raptors prison were fixed" would be more suitable.

I've changed it to specify that it is on Void Raptor.

2022-11-18 15:32 UTC, Jolly-66 approved these changes

2022-11-19 12:50 UTC, Paxilmaniac approved these changes
The couch fix from tg was a disaster for our modular maps

2022-11-19 12:50 UTC, merged