Makes the event voter low chaos event system obey the toggle random events off button, also changes event voter permissions to be the same as literally everything else event related
Skyrat-SS13/Skyrat-TG pull request #17466
Opened 2022-11-15 09:09 UTC by Paxilmaniac

## About The Pull Request

The event voter 'low' chaos event system completely bypassed the 

![image](https://user-images.githubusercontent.com/82386923/201875851-ccd3fd91-342a-4797-9d56-f3f3cca9cb85.png)

button. This is because it runs events completely outside of the normal event system and thus did not have a check for if this button was actually pressed. Extremely annoying for admins who want to turn that off!

OH but you could just edit when the next low chaos event happens! WRONG buddy! Why? Because everything in the event panel requires R_PERMISSIONS to use. What is that? That is the permissions level that I believe staff managers and above only have that gives them permissions to edit admin ranks and other related super high level activities.

Why? No goddamn clue.

So, I've taken to fixing both of these issues by adding a check to the low chaos system for the toggle random events button, and by changing the permissions required to use the menu to R_FUN, which is what we use for literally everything else event related.

## How This Contributes To The Skyrat Roleplay Experience

The system completely ignoring the toggle random events button was annoying enough, annoying that I've had several staff who tried to run events using it make a complaint that it doesn't work. That was easy enough to fix. Secondly the whole R_PERMISSIONS thing. I really don't understand why we felt the need to lock it behind the perms required to edit admin ranks, rather than the perms used for everything else event related. If the concern was people editing it to do things they shouldn't, guess what we've got something else in there to prevent that already, every edit made is admin logged and admin announced!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

There's not like much I could do to show these changes because one makes something NOT happen and the other, well I have every permission as a localhost so.

Here, have it compiling.

![image](https://user-images.githubusercontent.com/82386923/201877654-beed0bdf-c71d-4835-af5e-e2faa72edaa2.png)
  
</details>

## Changelog

None of these changes are player facing.

2022-11-15 21:56 UTC, GoldenAlpharex requested changes

2022-11-15 21:56 UTC, GoldenAlpharex commented on modular_skyrat/modules/event_vote/code/event_vote.dm
> +		return
```suggestion
		return

```

2022-11-15 21:56 UTC, GoldenAlpharex commented on modular_skyrat/modules/event_vote/code/event_vote.dm
>  				return
This should be moved right after the `if("reschedule_low_chaos")` line, to be in line with the other ones (and to not allow for more access to those that shouldn't have access to it).

Also just this portion as a whole feels like it should be slightly re-written to make more sense, that code looks _really_ weird to me.

2022-11-15 21:56 UTC, GoldenAlpharex commented on modular_skyrat/modules/event_vote/code/event_vote.dm
>  				return
At the very least, I want these four (so including the `start_player_vote_chaos`) to remain based on `R_PERMISSIONS`, as we specifically requested for those to be usable by Staff Managers and above only.

If you want that to be based on a config or whatever, sure, that's fine by me, but as it stands for Skyrat we want those permissions to be for SM+, as they shouldn't really ever be ran in the current state of things anyway.

2022-11-17 16:28 UTC, Paxilmaniac commented on modular_skyrat/modules/event_vote/code/event_vote.dm
>  				return
Nah these make sense to lock behind PERMISSIONS now that you say it, just that most of the other ones didn't

2022-11-19 16:40 UTC, GoldenAlpharex approved these changes
Looks good now.

2022-11-19 16:40 UTC, merged