Gets rid of both ballistic gun fowling* and ballistic emp fulnerability
Skyrat-SS13/Skyrat-TG pull request #17508
Opened 2022-11-16 16:33 UTC by Paxilmaniac

## About The Pull Request

Shrimple as the title, removes gun fowling and thus jamming from every gun except for some bolt actions, as those bolt actions can fowl and jam on tg so I've just reverted them to their standard behavior. Also gets rid of the whole thing with being able to emp certains guns to do... ???

## How This Contributes To The Skyrat Roleplay Experience

Both of these have reasons to go.

Guns getting dirty and jamming will either literally never be a problem, or will be such a problem that it makes a gun useless. It also really isn't all that engaging of a mechanic to go "you've fired your gun x times now its useless until you use a rag on muahahah!" nor does such a mechanic add anything meaningful to fights.

Guns being vulnerable to emps was definitely a ??? moment. The entire thing about guns is that emps don't do anything to them, so why we felt the need to have emps fuck with only certain guns but not others is just confusing and much like fowling, adds nothing meaningful to fights outside of the emp implant being usable against more than it should be.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Unbelievable batman I can shoot a gun for more than 2 seconds without it being unusable, and I can emp it because it has nothing electronic in it. Amazing!

![image](https://user-images.githubusercontent.com/82386923/202238206-fcd2dbd0-a6ed-4ce5-9717-fd4e38895a6b.png)

![image](https://user-images.githubusercontent.com/82386923/202238225-68db0338-de43-452e-a565-37457242ba3c.png)

  
</details>

## Changelog

:cl:
del: Guns getting dirty over time due to use has been reverted to tg behavior, that is to say literally only surplus mosins and maint muskets have it now.
del: Guns no longer have situational emp vulnerability/invulnerability. EMPing a ballistic gun won't do anything to it.
/:cl:

2022-11-16 16:34 UTC, Paxilmaniac commented
HOW BRO THIS IS ON MASTER FROM 15 MINUTES AGO

2022-11-16 16:37 UTC, RimiNosha commented
![image](https://user-images.githubusercontent.com/106692773/202239680-1909ef1a-ed1a-4100-a7cf-071f6225424e.png)

2022-11-16 21:07 UTC, Paxilmaniac commented
Its technically balance yes but literally what does gbp mean the bot can't touch me.

2022-11-16 23:09 UTC, OrionTheFox commented
Okay Im all for removing both but can I please be able to clean the guns even if it does nothing please I need to have mechanics to tie into my ocd roleplay 🥺

2022-11-17 06:00 UTC, RatFromTheJungle commented
remove it from everything, 'tg default' or not; rid us of the plague

(it will come in handy in the future)

2022-11-17 14:49 UTC, Paxilmaniac commented
Jungle the skyrat system for it is completely gone literally only the maint muskets and the shitty surplus mosins have 'dirt' anymore because they always have, all I did was reset the file back to just be 1:1 with tg

2022-11-17 23:36 UTC, RatFromTheJungle commented
![image](https://user-images.githubusercontent.com/62520989/202582338-4ba28d98-659e-4da2-aa02-a9239ca34ea9.png)
![image](https://user-images.githubusercontent.com/62520989/202582438-5e31b506-1ea8-4392-be99-224f72135800.png)
this is what forcing pax to touch gunsprites has done to them 😔 

(this PR adds it back to two guns that didn't have it before; while removing it from guns that that aren't available)

> Jungle the skyrat system for it is completely gone literally only the maint muskets and the shitty surplus mosins have 'dirt' anymore because they always have, all I did was reset the file back to just be 1:1 with tg

2022-11-18 02:07 UTC, Paxilmaniac commented
literally what are you talking about jungle, the mosins always had the cobalt gun dirt system, as well as a vast majority of the guns that guncargo sold

2022-11-18 02:11 UTC, Paxilmaniac commented
> this PR adds it back to two guns that didn't have it before;

![image](https://user-images.githubusercontent.com/82386923/202600643-7b5f56a7-3618-4209-a314-1fae01401014.png)

immeasurable cap bro you can just tell me you're upset about the mosin getting nerfed

2022-11-18 03:21 UTC, RatFromTheJungle commented
> literally what are you talking about jungle, the mosins always had the cobalt gun dirt system, as well as a vast majority of the guns that guncargo sold

as of right now, go on server and run like, ten stripper clips through it; I can assure you, it hasn't in ages, because 'realistic' never did anything for bolt-actions

2022-11-18 03:44 UTC, RatFromTheJungle commented
> literally what are you talking about jungle, the mosins always had the cobalt gun dirt system, as well as a vast majority of the guns that guncargo sold

as of right now, go on server and run like, ten stripper clips through it; I can assure you, it hasn't in ages, because 'realistic' never really did anything for bolt-actions; as compared to other guns, and, skimming the TG code, it's a 5% gain per shot; which, again:

> Guns getting dirty and jamming will either literally never be a problem, or will be such a problem that it makes a gun useless. It also really isn't all that engaging of a mechanic to go "you've fired your gun x times now its useless until you use a rag on muahahah!" nor does such a mechanic add anything meaningful to fights.

seems a bit off-mark for the given reasons; if you're taking it away from stuff (we don't really use at the minute), to be specifically returning a worse-off version of the exact problem, to two guns in specific, which we do use


https://www.youtube.com/watch?v=SYA6RLLZ-PA

2022-11-18 04:11 UTC, YakumoChen commented
guns being weak to EMPs is more a product on the proliferation of ballistics to keep EMPs being a valid way to stymie security, given on TG they only typically have energy weapons (weak to EMPs).

I'm kinda eh on this, since ballistics don't really _have_ a counter like energy guns do, so it's still almost always preferable to use a ballistic weapon.

2022-11-19 16:46 UTC, Paxilmaniac commented
i merged the pr that made this conflict

2022-11-23 06:19 UTC, Zonespace27 requested changes

2022-11-23 06:19 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/rifle.dm
> +	var/jamming_chance = 20
so like, was this just some undocumented SR removal in the first place

2022-11-23 06:29 UTC, Zonespace27 approved these changes
Way I see it, mosins and similar are intentionally shit (while still being obtainable ~~croon~~) and it's a "good enough" reason to either pack a rag, more mosins, or pray. Having it for every gun is pretty 🤷 considering how it'll only be a problem after hundreds of rounds, at which point it becomes a game-stopper if you weren't prepped

2022-11-23 06:29 UTC, merged