[ DONATOR ITEM ] Purple Outfit Set
Skyrat-SS13/Skyrat-TG pull request #17514
Opened 2022-11-16 22:33 UTC by Crumpaloo

## About The Pull Request

A Donator item requested by Thedragmeme, PR contains 3 new objects and their directionals/item states meant to act like one outfit broken up into several sprites:

- Caged Purple Dress
- Short Purple Coat
- Flower Neck Collar

![image](https://user-images.githubusercontent.com/104168339/202308161-f15e0baf-cc52-4f23-8d15-adfea7922b22.png)

## How This Contributes To The Skyrat Roleplay Experience

Allows Thedragmeme to use their donator item slot.

2022-11-16 22:42 UTC, Zonespace27 commented on modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
> +	ckeywhitelist = list("Thedragmeme")
no capitalization

2022-11-16 22:50 UTC, Crumpaloo commented on modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
> +	ckeywhitelist = list("Thedragmeme")
Took them out, should be good now.

2022-11-17 04:06 UTC, Ebin-Halcyon requested changes
Needs cut outs of the arms on the side state. Those don't overlay on clothing, only hands don't need a hole cut out for it.

2022-11-17 15:49 UTC, Crumpaloo commented
> Needs cut outs of the arms on the side state. Those don't overlay on clothing, only hands don't need a hole cut out for it.
Updated them so the side directionals have the cut-outs.
![image](https://user-images.githubusercontent.com/104168339/202492901-33ee7e3b-5fd4-4a8e-ab25-6b822e10bbf3.png)

2022-11-17 22:20 UTC, closed without merging