[MODULAR, I guess] Sloppily and incorrectly "fixes" Guards not having enough lockers to supply both roundstart guard slots because the proper fix was denied.
Skyrat-SS13/Skyrat-TG pull request #17582
Opened 2022-11-19 21:42 UTC by Iamgoofball

## About The Pull Request
Sloppily and incorrectly "fixes" Guards not having enough lockers to supply both roundstart guard slots because the proper fix was denied.

## How This Contributes To The Skyrat Roleplay Experience

I made a proper fix to this problem, #17171, but it was denied because it "wasn't needed" and added maintainability.
News flash, you're going to keep having this maintainability problem until you either quit using /tg/ maps. There's no way around that and giving me shit for trying to maintain my feature is really dumb.

This doesn't effectively contribute to the Skyrat experience because it makes my guards look like a sloppy hastily put together hackjob that doesn't even have it's own room and is instead squatting in the security outposts, but it needs done anyways because there's two guard slots and only 1 locker and their gear spawns in their locker.

This also doesn't fix:

1. Security being able to get inside the guard posts
2. Guard posts having security computers they can't use in them
3. Every guard post having space law inside of it when they don't enforce space law, leading to player misconceptions about what guards do

If maintaining automapper templates is a bridge too far for maintenance, then seriously consider maybe dropping the /tg/ maps from the rotation and switching over to original Skyrat maps. I mean it, it'll significantly remove the overhead you guys have to deal with and you can drop the automapper. I don't like having to do automapper stuff either, but I also really don't like my features going unmaintained because I was denied from maintaining them and this leaves Guards in an unmaintained state to players visually.

## Proof of Testing

You already know what it's going to look like, a locker randomly spawned in the guard posts in a random location because we have no control over it with this method.

## Changelog

:cl:
fix: Sloppily and incorrectly "fixes" Guards not having enough lockers to supply both roundstart guard slots because the proper fix was denied.
/:cl:

2022-11-19 21:46 UTC, Paxilmaniac requested changes
Show it working on at least one of the maps I don't care how simple you think it is.

2022-11-19 21:50 UTC, Iamgoofball commented
compiling now, prepare to be amazed by ugly locker placement

2022-11-19 21:59 UTC, Iamgoofball commented
## "nice interior decoration"
![dreamseeker_wRU1dhIASt](https://user-images.githubusercontent.com/4081722/202873054-8e9c3573-61a5-4994-a25c-2aa4a7f064af.png)

## this one just looks annoying
![dreamseeker_2ml2dfH3DC](https://user-images.githubusercontent.com/4081722/202873067-b88041d4-7346-4642-b1e6-8145353c22dd.png)

## blocks your door lmao
![dreamseeker_e7xaLb1ayJ](https://user-images.githubusercontent.com/4081722/202873072-340da578-7030-4e80-a379-41f8d9dcbf2b.png)

## Customs Agents are actually literally stuck in this configuration without hopping the table. This is so bad.
![dreamseeker_VokLF7RK6A](https://user-images.githubusercontent.com/4081722/202873077-0031d206-3534-44a0-a900-fa6922753448.png)

2022-11-19 22:03 UTC, Zenitheevee commented
... I feel like, considering neither _medical nor research_ have them, you might be able to just remove the filing cabinets to put engineer and cargo's other locker at.

2022-11-19 22:03 UTC, Iamgoofball commented
@Zenitheevee that would require an automapper template :)

2022-11-19 22:09 UTC, Iamgoofball commented
also, as predicted kilostation and deltastation lack the room for this method without modifications to the map
![chrome_UJt2MWY3Iy](https://user-images.githubusercontent.com/4081722/202873342-25405e7f-dcc4-4f93-b803-b6608cc19fa3.png)

2022-11-20 00:28 UTC, YakumoChen commented
Aren't the lockers modular as it is? Why not double fill them with supplies?

2022-11-20 05:46 UTC, Iamgoofball commented
@YakumoChen That'd run over the item cap for locker contents

#17589 doesn't actually fix the issue of the doors, the unusable computers, and the space law books, and also runs back into the original reason I put guard equipment in lockers, because certain developers are bending over backwards to avoid admitting I was right about anything ever because they dislike me personally.

#17589 will result in Guards with Loadouts not spawning with their gear due to bugs with how the loadout system works if they don't have the option to spawn gear in a briefcase selected.

2022-11-20 09:34 UTC, YakumoChen commented
>@YakumoChen That'd run over the item cap for locker contents

Their fix is still much better. If the equip thing is a problem, the cap won't run over with all the clothes in a garment bag.

2022-11-20 09:45 UTC, YakumoChen commented
you have to admit goof that even the title suggests this is a stupid fix and we know you're capable of much better. You could replace the locker with a vending machine or something else that works on access (like the command vendor) and nobody would complain.

Right now you just look like a baby. Take a step back and breathe, man.

2022-11-20 09:59 UTC, Iamgoofball commented
I made the correct fix the first time. Look what happened to that.

2022-11-21 06:10 UTC, closed without merging