[NON-MODULAR] Fixes custom stuff for uniform accessories on teshis, also some taur cleanup.
Skyrat-SS13/Skyrat-TG pull request #17637
Opened 2022-11-21 22:46 UTC by Tastyfish

## About The Pull Request

Note almost all of the non-modular code consists of pre-existing non-modular changes. This part of the code can't really be modularized much better than this anyway.

Fixes a couple of long-standing item-rendering regressions.

### Chickencode

A while ago, we forgot about `...species.custom_worn_icons[LOADOUT_ITEM_ACCESSORY` when that icon selection system was modernized and there was no support for it. We also lost support for `...species.offset_features[OFFSET_ACCESSORY]` at some point. Doesn't really matter when.

### Cruft

I also removed a some cruft that hasn't been used for a while, including an entire commented out file that had obsolete code.

### Some taur stuff

While perusing the related code, I saw cleaned up that taur bodytype code in human_update_icons.dm since it's mostly describing mutant_styles enums anyway, so now it'd be easier to pass other ones if we ever did that.
- It also bugged me that the same code was duplicated multiple times for determining a mob's taur mode --- and it made low level assumptions about how that was stored, so I added a new `get_taur_mode()` helper proc that just returns NONE if the mob is not a taur, doesn't have the taur accessory, or it's set to an invalid one.
- For that matter, `build_worn_icon()` was just getting TRUE or FALSE passed as the taur mode; now it gets the actual taur mode and treats it as an actual mutant style enum if you want to do something with that.

## How This Contributes To The Skyrat Roleplay Experience

This mainly fixes some regressions and code jank.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://user-images.githubusercontent.com/1185434/203173062-84b6014b-cb7d-4836-8e93-afce28851c14.png)

</details>

## Changelog

:cl:
fix: Teshari uniform accessory rendering now works as expected again.
/:cl:

2022-11-27 23:48 UTC, GoldenAlpharex requested changes
Looks good otherwise, I'll hook us up with a test-merge just to be sure since it deals with character visuals!

2022-11-27 23:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/emotes/code/additionalemotes/turf_emote.dm
>  				user.allowed_turfs += "constrict"
```suggestion
		if(taur_mode & STYLE_TAUR_SNAKE)
			user.allowed_turfs -= list("pawprint", "hoofprint", "clawprint")
			user.allowed_turfs += "constrict"
```

2022-11-28 17:09 UTC, Tastyfish commented on modular_skyrat/modules/emotes/code/additionalemotes/turf_emote.dm
>  				user.allowed_turfs += "constrict"
Oh yeah, that was left-over cruft.

2022-12-03 13:38 UTC, tf-4 commented
Has this been TM'd?

2022-12-03 21:05 UTC, Tastyfish commented
> Has this been TM'd?

Don't think so.

2023-01-03 17:36 UTC, tf-4 commented
@GoldenAlpharex

2023-01-12 18:40 UTC, GoldenAlpharex approved these changes
Thanks!

2023-01-12 19:00 UTC, Tastyfish commented
Recreated the old test images real quick

![image](https://user-images.githubusercontent.com/1185434/212153378-a12fc8e9-d0b0-4258-9b00-6f457f1c25dd.png)

Also curator pocket protector not being on top of tesh's face:
![image](https://user-images.githubusercontent.com/1185434/212153549-3be48704-13b3-4d70-a3af-494706b04792.png)

![image](https://user-images.githubusercontent.com/1185434/212157260-8121e34a-8cfc-4c62-b83c-c0be40998eca.png)

2023-01-14 00:15 UTC, GoldenAlpharex commented
Worked out fine!

2023-01-14 00:15 UTC, merged