[MODULAR] marked one fixes / more changes
Skyrat-SS13/Skyrat-TG pull request #17718
Opened 2022-11-24 02:05 UTC by dawsonkeyes

## About The Pull Request

This PR removes unused variables wthin the gladiator module var while adjusting the general balance of the marked one, buffing his movement speed and fixing dysfunctional charge attacks while also adding more obvious alerts to spin and charge attacks through voicelines rather than sounds or chat alerts.

In short:
-his third and fourth phases have faster movement speeds
-his charge speed is no longer a snail's pace
-his charge is no longer overridden by having another attack queued
-his charge and spin attacks make clang noises
-he talks when doing a spin or charge
-he has bubble alerts for things like blocking damage
-spin has more range
-shockwaves radiate faster
-his first stage block chance is now applied in his last stage
-he no longer floats as if he's in zero gravity
-unused variables in his equipment are gone :DD

## How This Contributes To The Skyrat Roleplay Experience

"roleplay" is a stretch, but this is more just me maintaining the things i added to the game, using player feedback and active round observation as a benchmark

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://user-images.githubusercontent.com/76002401/201243227-514b3cbd-5c20-4e1c-acf8-cb692be7083b.png)

</details>

## Changelog

:cl:
qol: marked one is now harder and makes clang noises and talks to signal attacks
fix: removed useless berserker armor vars
/:cl:

2022-11-26 03:08 UTC, Zonespace27 requested changes

2022-11-26 03:08 UTC, Zonespace27 commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	balloon_alert_to_viewers("THUD")
why

2022-11-26 03:08 UTC, Zonespace27 commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	balloon_alert_to_viewers("docile")
why

2022-12-02 19:26 UTC, dawsonkeyes commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	balloon_alert_to_viewers("docile")
good question

2022-12-02 19:26 UTC, dawsonkeyes commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	balloon_alert_to_viewers("THUD")
good question

2022-12-06 00:20 UTC, dawsonkeyes commented
since this is technically also balancing, a maintainer can edit tags so i'm not whoring GBP off of this xd

2023-01-03 11:04 UTC, dawsonkeyes commented
wake the fuck up samurai

2023-01-11 15:41 UTC, Zonespace27 approved these changes

2023-01-11 15:42 UTC, merged