[MIRROR] Small optimization for allowed lists [MDB IGNORE]
Skyrat-SS13/Skyrat-TG pull request #17798
Opened 2022-11-28 07:05 UTC by SkyratBot

Original PR: https://github.com/tgstation/tgstation/pull/71562
--------------------
## About The Pull Request

Removes typecaching from allowed lists. 

`allowed` uses `is_type_in_list`, it's not a typecache.
Making it a typecache makes it scale very poorly. 

Before: 488 `istype`s
![image](https://user-images.githubusercontent.com/51863163/204115121-725ea813-3369-4eb5-9bd8-fd6b80efb5ca.png)

After: 5 `istype`s
![image](https://user-images.githubusercontent.com/51863163/204115127-65c17653-8c1e-406f-baf5-0a78c604d4b6.png)

You may ask "Why not make allowed lists typecaches instead, it's also faster than is type in list"
Yes, but it's a lot more work than just getting this out of the way, and plus you need to account for stuff like adding allowed lists together and meh. This is just easier. 

## Why It's Good For The Game

Code goes faster

## Changelog

:cl: Melbert
code: Cuts some uses of allowed list as a typecache. Allowed lists are not typecaches, don't make them typecaches
/:cl:

2022-11-28 14:40 UTC, GoldenAlpharex requested changes

2022-11-28 14:40 UTC, GoldenAlpharex commented on code/__DEFINES/inventory.dm
> +>>>>>>> 928b902b9e2 (Small optimization for allowed lists (#71562))
```suggestion
	/obj/item/gun/microfusion, //SKYRAT EDIT ADDITION
))
```

2022-11-28 14:40 UTC, GoldenAlpharex commented on code/__DEFINES/inventory.dm
> +>>>>>>> 928b902b9e2 (Small optimization for allowed lists (#71562))
```suggestion
	/obj/item/gun/microfusion, //SKYRAT EDIT ADDITION
))
```

2022-11-28 14:40 UTC, GoldenAlpharex commented on code/__DEFINES/inventory.dm
> +>>>>>>> 928b902b9e2 (Small optimization for allowed lists (#71562))
```suggestion
	/obj/item/gun/microfusion, //SKYRAT EDIT ADDITION
))
```

2022-11-28 14:40 UTC, GoldenAlpharex approved these changes
Should be good to go now!

2022-12-01 00:51 UTC, tf-4 approved these changes

2022-12-01 01:00 UTC, merged