Removed cell component from health analyzer
Skyrat-SS13/Skyrat-TG pull request #17866
Opened 2022-12-01 21:24 UTC by YakumoChen

## About The Pull Request
Title
Health analyzers don't need power cells anymore

## How This Contributes To The Skyrat Roleplay Experience
Added nothing to the game but short-lived tedium when the cell ran out.
It was actually easier to just drop a spent one on the ground and print a new one than procure an upgraded cell for it
I shouldn't have to feel like I only have a limited number of health scans when I'm busy saving lives and tracking updates to patient health

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
qol: removed power cell nonsense from health analyzers
/:cl:

2022-12-01 21:43 UTC, Paxilmaniac commented
My question is does anything in the codebase still use cell component after this?

If the answer is no you can probably just remove cell component too.

2022-12-01 21:47 UTC, HoodMilk commented
I think flashlights still do

2022-12-01 21:55 UTC, YakumoChen commented
> My question is does anything in the codebase still use cell component after this?
> 
> If the answer is no you can probably just remove cell component too.

A lot of things including but not limited to flashlights, electric welders, decal painters, and radio jammers

2022-12-01 21:57 UTC, Paxilmaniac commented
Right, I should change that sometime

2022-12-01 22:05 UTC, YakumoChen commented
I'd love to remove it myself, maybe in a follow up pr
This was a dirty 15 minute pr though and a step in the right direction

2022-12-01 22:19 UTC, OzzyMcPseudonym commented
Based, making medical have to print more health analyzers was bad. I'm the kind of person who would get around the cell component by using their PDA and saving the analyzer itself for chem scans, so I appreciate this.

2022-12-01 23:59 UTC, tf-4 approved these changes

2022-12-01 23:59 UTC, tf-4 commented
Flashlights are the one well done implementation of the cell component

2022-12-03 00:20 UTC, softcerv commented
Thank god. Having to print out extra analyzers to recycle and harvest the cells from really sucked.

2022-12-03 02:06 UTC, tf-4 requested changes
Just want to see proof of testing. Especially as it's a webedit.

2022-12-03 13:20 UTC, tf-4 approved these changes

2022-12-03 13:21 UTC, merged