Adds three new ear sprites
Skyrat-SS13/Skyrat-TG pull request #17913
Opened 2022-12-04 19:58 UTC by 123Neok321

## About The Pull Request

Adds three new choices for ears, each habing four ears; A version of the teshari upright for regular body shapes, a version of the teshari mane for regular body shapes, and an original third sprite. 

## How This Contributes To The Skyrat Roleplay Experience

More options for ears, no longer will teshari hoard all the four-eared sprites.

## Proof of Testing

![dreamseeker_buRH4nNtX2](https://user-images.githubusercontent.com/73550491/205512340-3e94c842-6c3a-48c1-9387-9a550e2d39ce.gif)
![dreamseeker_ti9AZJtidn](https://user-images.githubusercontent.com/73550491/205512341-9bb2d54e-3452-4264-b01c-07977c276304.gif)
![dreamseeker_Zwgv2gkeSk](https://user-images.githubusercontent.com/73550491/205512342-7769e392-dce6-4460-96e6-d7dddb49a0f0.gif)

## Changelog

:cl:
add: Three new choices for ears, all of which have four ears.
/:cl:

2022-12-04 20:13 UTC, Zonespace27 submitted a review, later dismissed

2022-12-04 20:13 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +/datum/sprite_accessory/ears/mutant/big/temp3
Add spacing like is shown above this

2022-12-04 21:06 UTC, 123Neok321 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +/datum/sprite_accessory/ears/mutant/big/temp3
Should be done!

2022-12-04 21:41 UTC, BardTheBard commented
I like the look of these, I'm getting ideas for how these could be used just looking at them.

2022-12-05 00:56 UTC, tf-4 requested changes

2022-12-05 00:56 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +/datum/sprite_accessory/ears/mutant/big/temp2
temp...

2022-12-05 17:39 UTC, 123Neok321 commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/ears.dm
> +/datum/sprite_accessory/ears/mutant/big/temp2
Replaced with proper names now

2022-12-06 18:40 UTC, tf-4 approved these changes

2022-12-09 20:26 UTC, Ebin-Halcyon approved these changes

2022-12-15 06:53 UTC, merged