[PR to PR] NRI raider de-conflicting
Skyrat-SS13/Skyrat-TG pull request #17921
Opened 2022-12-05 10:36 UTC by Stalkeros2

## About The Pull Request
Should be merged into #17920 
Does what it says on the tin. That is, de-conflicting stuff as best as I could.

## How This Contributes To The Skyrat Roleplay Experience
Codebase will compile you know.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
I am literally localhosting this and it all works the way it should.

![image](https://user-images.githubusercontent.com/42087567/205616386-b12418db-1db8-4a45-b174-90fdfc21bc55.png)
  
</details>

## Changelog
Not important.
/:cl:

2022-12-05 10:42 UTC, Stalkeros2 commented
> You currently have a negative Fix/Feature pull request delta of -20. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

![image](https://user-images.githubusercontent.com/42087567/205617742-7901c71d-4f55-4b65-b06b-4a952752029d.png)

2022-12-05 15:04 UTC, Zonespace27 requested changes

2022-12-05 15:04 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/revolver.dm
> -	/// Used to avoid some redundancy on a revolver loaded with 357 regarding misfiring while being wrenched.
don't remove tg code

2022-12-05 15:10 UTC, Stalkeros2 commented on code/modules/projectiles/guns/ballistic/revolver.dm
> -	/// Used to avoid some redundancy on a revolver loaded with 357 regarding misfiring while being wrenched.
I'm fairly certain that I've quite literally just reverted it entirely to /tg/ code.

2022-12-05 15:12 UTC, Stalkeros2 commented on code/modules/projectiles/guns/ballistic/revolver.dm
> -	/// Used to avoid some redundancy on a revolver loaded with 357 regarding misfiring while being wrenched.
![image](https://user-images.githubusercontent.com/42087567/205672160-d1738b8d-3c80-48f1-aadd-336fe54a2275.png)
I am not wrong. This screenshot is upstream.

2022-12-06 00:08 UTC, Fikou commented on modular_skyrat/modules/encounters/code/nri_raiders.dm
> +	"Novaya Rossiyskaya Imperiya Civilian Port" = 5,
```suggestion
		"Nanotrasen Research Station" = 70,
		"Nanotrasen Refueling Outpost" = 5,
		"Interdyne Pharmaceuticals Chemical Factory" = 5,
		"Free Teshari League Engineering Station" = 5,
		"Agurkrral Military Base" = 5,
		"Sol Federation Embassy" = 5,
		"Novaya Rossiyskaya Imperiya Civilian Port" = 5,
```

2022-12-06 00:08 UTC, Fikou commented on modular_skyrat/modules/encounters/code/nri_raiders.dm
> +		ANY POSSIBLE INDENTURE HAS BEEN CLEARED. WE APOLOGIZE FOR THE INCONVENIENCE",
```suggestion
		"inadequate support of the local producer",
		"unregulated production of Gauss weaponry aboard this installation",
		"SolFed-backed stationary military formation on the surface of Indecipheres",
		"AUTOMATED REGULATORY VIOLATION DETECTION SYSTEM CRITICAL FAILURE. PLEASE CONTACT AND INFORM THE DISPATCHED AUTHORITIES TO RESOLVE THE ISSUE. \
		ANY POSSIBLE INDENTURE HAS BEEN CLEARED. WE APOLOGIZE FOR THE INCONVENIENCE",
```

2022-12-07 01:55 UTC, RimiNosha commented on code/modules/projectiles/guns/ballistic/revolver.dm
> -	/// Used to avoid some redundancy on a revolver loaded with 357 regarding misfiring while being wrenched.
Hmmm, yes, undocumented nonmodular edits.

2022-12-08 17:11 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/revolver.dm
> -	/// Used to avoid some redundancy on a revolver loaded with 357 regarding misfiring while being wrenched.
*incredibly* based

2022-12-08 17:12 UTC, Zonespace27 approved these changes

2022-12-08 17:12 UTC, merged