Removes side effects from sensitive snout.
Skyrat-SS13/Skyrat-TG pull request #18016
Opened 2022-12-09 06:36 UTC by nevimer

## About The Pull Request

Because Sensitive Snout no longer has any reason to take it, this removes the downsides of it and makes it more in line with being neutral. 

## How This Contributes To The Skyrat Roleplay Experience

Consistency. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  

https://user-images.githubusercontent.com/77420409/206640015-8d0b192e-26df-4c46-b382-0d2b831bbe75.mp4

</details>

## Changelog

:cl:
balance: removes the drawback of sensitive snout now that it is free
/:cl:

2022-12-09 06:41 UTC, Paxilmaniac reviewed
![image](https://user-images.githubusercontent.com/82386923/206640970-1b925f20-e6b9-4c72-9374-729caafd9dcd.png)
![image](https://user-images.githubusercontent.com/82386923/206640983-98580e02-2bad-46f8-9175-e6c3391f79b7.png)
![image](https://user-images.githubusercontent.com/82386923/206641028-fed1b426-cf02-41bb-b354-3c32870131cd.png)

2022-12-09 06:44 UTC, nevimer commented
> 



> ![image](https://user-images.githubusercontent.com/82386923/206640970-1b925f20-e6b9-4c72-9374-729caafd9dcd.png) ![image](https://user-images.githubusercontent.com/82386923/206640983-98580e02-2bad-46f8-9175-e6c3391f79b7.png) ![image](https://user-images.githubusercontent.com/82386923/206641028-fed1b426-cf02-41bb-b354-3c32870131cd.png)

If you're getting booped 25 times in a row you deserve to be stamcrit.

2022-12-09 06:45 UTC, softcerv commented
You should probably just turn this into a flavor mood debuff tbh

2022-12-09 06:59 UTC, YakumoChen commented
Just make it a flavour clone of bad touch if you're going to change it.

2022-12-13 21:04 UTC, Tastyfish requested changes

2022-12-13 21:04 UTC, Tastyfish commented on code/modules/mob/living/carbon/carbon_defense.dm
> -			src.apply_damage(30, STAMINA, BODY_ZONE_CHEST)
should be `adjustStaminaLoss(5)` now.

2022-12-29 07:20 UTC, Zonespace27 commented
you haven't touched this and I dunno about this change in the first place

2022-12-29 07:20 UTC, closed without merging