[Modular] Newbie pin
Skyrat-SS13/Skyrat-TG pull request #18050
Opened 2022-12-10 04:36 UTC by theOOZ

## About The Pull Request

It adds a per character preference toggle to spawn with a newbie pin, and is pre-enabled, you lose the pref past 100 living hours.
Its hooked into loadout code because that seemed like the best way to me.

## How This Contributes To The Skyrat Roleplay Experience
Skyrat is a hard server to get into if you're new to spacestation 13, yet people still do. This pin is for players like such, so others are more keen on helping them.

## Proof of Testing

![dreamseeker_T2FM0dKpfx](https://user-images.githubusercontent.com/77534246/206828944-6cc83f9e-85b3-4087-af56-cc030fc3190d.png)
  
</details>

## Changelog
:cl:
add: Players with less than 100 hours as living role get access to a pin indicating they are new.
/:cl:

2022-12-10 04:41 UTC, tf-4 requested changes
Cute idea

2022-12-10 04:41 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/under/accessories.dm
> +		. += span_nicegreen("It reads '[green_time_remaining] hours.'")
Check for it being 1 for the singular "hour"

2022-12-10 04:45 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/under/accessories.dm
> +		. += span_nicegreen("It reads '[green_time_remaining] hours.'")
aka `hour[green_time_remaining >= 2 ? "s" : ""].'`

2022-12-11 02:25 UTC, Iamgoofball commented
Did you guys not turn on the Intern feature in the config? This is that but on your ID card.

2022-12-11 02:26 UTC, Iamgoofball commented
https://github.com/Skyrat-SS13/Skyrat-tg/blob/41b21a967ab08cd07099853289c0b55773091bfa/config/config.txt

Just turn USE_LOW_LIVING_HOUR_INTERN on and set USE_LOW_LIVING_HOUR_INTERN_HOURS to 100 and you're set.

2022-12-14 18:00 UTC, theOOZ commented
> Did you guys not turn on the Intern feature in the config? This is that but on your ID card.

Heyo! only difference I think? is that this pin is a toggle. Is the intern ID a toggle for the player?

2022-12-17 03:41 UTC, tf-4 approved these changes

2022-12-19 07:35 UTC, GuiltyNeko commented
> https://github.com/Skyrat-SS13/Skyrat-tg/blob/41b21a967ab08cd07099853289c0b55773091bfa/config/config.txt
> 
> Just turn USE_LOW_LIVING_HOUR_INTERN on and set USE_LOW_LIVING_HOUR_INTERN_HOURS to 100 and you're set. The Intern feature even keeps track of who's wearing the ID, so if someone steals it and puts it on the Intern automatically comes off of it, or if an Intern puts someone's ID on it gets Intern appended to it.

This seems like it would an undesirable meta-indicator for impersonation.

2022-12-19 08:55 UTC, Iamgoofball commented
@GuiltyNeko this is what admins are for

2023-01-22 15:53 UTC, merged