Swaps the wardens Krav Maga gloves with a implant
Skyrat-SS13/Skyrat-TG pull request #18230
Opened 2022-12-20 00:03 UTC by SomeRandomOwl

## About The Pull Request

Try number two as my previous PR for this was a little dirty and had remenants of a previous PR i made that was already merged

This PR modifies `code\game\objects\structures\crates_lockers\closets\secure\security.dm` to and removes `new /obj/item/clothing/gloves/krav_maga/sec(src) ` and replaces it with `new /obj/item/implanter/krav_maga(src)`

## How This Contributes To The Skyrat Roleplay Experience

It replaces a relatively powerful item that can be easily stolen off of the warden with something not so easily stolen, and also from what I recall there was talk about doing this replacement, but it was never done, so I am simply doing it now with this PR. 

## Proof of Testing

<details>
<summary>Screenshots/Videos

![image](https://user-images.githubusercontent.com/2568378/208549379-bc4f3f22-95a6-475b-847d-258d6b1e2c66.png)

</summary>
  
</details>

## Changelog

:cl:
add: Replaced the the Wardens Krav Maga Gloves with a Krav Maga Implanter
/:cl:

2022-12-20 00:07 UTC, Paxilmaniac commented
![image](https://user-images.githubusercontent.com/82386923/208551612-dc5154c0-bae3-47eb-8caf-98b447bae176.png)

2022-12-20 00:10 UTC, SomeRandomOwl commented
> ![image](https://user-images.githubusercontent.com/82386923/208551612-dc5154c0-bae3-47eb-8caf-98b447bae176.png)

Why would that be the case? This PR is specifically made for SR as it was previously requested by the host

2022-12-20 00:16 UTC, tf-4 reviewed
It's a good thing to be able to steal the gloves.
Closing in 24h.

2022-12-20 00:20 UTC, PCPort commented
Isn't the gloves being able to be stolen kind of the point? If you don't want to lose them, quit getting into fights that you can't win as a warden.

2022-12-20 00:33 UTC, SomeRandomOwl commented
Honetly made this because I remember it was brought up a while ago and i talked about it again recently and someone mentioned it, i thought id try to do this PR but I didnt relly know if it would be accepted or not as it is kinda contraversal at best, though it could probally be done in a different method, but for now ill just manually close this myself

2022-12-20 00:52 UTC, hugmeorelse commented
I asked for this.

2022-12-20 00:55 UTC, SomeRandomOwl commented
i could change this to make the Warden start with the implant instead of having a implanter in the locker

2022-12-20 00:55 UTC, Zonespace27 requested changes
If you want to solve the problem that this was meant to solve, make it a skillchip auto-implanted in the warden by default

2022-12-20 00:56 UTC, hugmeorelse commented
> If you want to solve the problem that this was meant to solve, make it a skillchip auto-implanted in the warden by default

Is this something you can do possibly instead? @SomeRandomOwl

2022-12-20 01:00 UTC, SomeRandomOwl commented
> > If you want to solve the problem that this was meant to solve, make it a skillchip auto-implanted in the warden by default
> 
> Is this something you can do possibly instead? @SomeRandomOwl

looking into it right now

2022-12-20 04:10 UTC, Zonespace27 requested changes
overall, I *heavily* recommend looking at /obj/item/skillchip/job/chef and just copying how it grants/removes a martial art instead of what you have currently

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +/datum/action/Krav_Activate
don't capitalize paths

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	name = "Activates your Knowledge of Krav Maga"
add a period, also knowledge isn't a proper noun

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/datum/action/Krav_Activate/Krav_Activate = new/datum/action/Krav_Activate()
remove this on Destroy(), also path after new is implicit

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/mob/living/carbon/human/H = owner
one letter vars bad

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/datum/martial_art/krav_maga/style = new
if they already have it, don't make a `new` datum that has to be deleted post-proc

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	Krav_Activate.Trigger()
this doesn't account for them having it off

2022-12-20 04:10 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +
don't need all this whitespace after

2022-12-20 04:27 UTC, SomeRandomOwl commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/datum/action/Krav_Activate/Krav_Activate = new/datum/action/Krav_Activate()
I swapped it to just new, but im not certain what you mean to remove it on destroy

2022-12-20 04:27 UTC, SomeRandomOwl commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/datum/martial_art/krav_maga/style = new
I am not fully certain how to fix this

2022-12-20 04:54 UTC, SomeRandomOwl commented
@Zonespace27 Do you want the skillchip to be limited to just security Areas? thats how the chef skillchip works, this simply makes it work like the Krav maga implant

2022-12-20 05:28 UTC, Zonespace27 requested changes

2022-12-20 05:28 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/datum/martial_art/krav_maga/style = new
move this into the `else` clause on line 25-26

2022-12-20 05:28 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	var/datum/action/krav_activate/krav_activate = new
on `/obj/item/skillchip/job/warden/Destroy()`, QDEL_NULL this

2022-12-20 05:28 UTC, Zonespace27 commented on code/modules/jobs/job_types/warden.dm
> +	skillchips = list(/obj/item/skillchip/job/warden) //SKYRAT EDIT ADDITION
modularize this

2022-12-20 05:28 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	name = "Krav Maga skillchip"
```suggestion
	name = "\improper Krav Maga skillchip"
```

2022-12-20 06:21 UTC, SomeRandomOwl commented on modular_skyrat/modules/skillchips/warden.dm
> +	name = "Krav Maga skillchip"
I cam confused with this one? What change is needed here @Zonespace27

2022-12-20 10:48 UTC, Iamgoofball commented
:-1: to putting it in the warden's head roundstart, needs to be in the locker so that it's usable on a job changed warden

2022-12-20 15:33 UTC, Zonespace27 commented on modular_skyrat/modules/skillchips/warden.dm
> +	name = "Krav Maga skillchip"
add the `\improper` label to the name as a prefix

2022-12-20 17:46 UTC, SomeRandomOwl commented
> 👎 to putting it in the warden's head roundstart, needs to be in the locker or orderable via cargo somehow so that it's usable on a job changed warden, i added krav maga back in the day
> 
> making it a skill chip is fine i guess but i'd deactivate it if they've got chunky fingers, otherwise this is a massive buff to krav maga and a reduction in ability to job transfer people to positions and have the gear be available
> 
>     1. krav maga being a skillchip means you can't disarm it off of someone by literally disarming them or by forcefully removing their gloves, you gotta surgery it out now
> 
>     2. krav maga being a skillchip means you can stack it with insulated gloves now making it significantly more powerful than intended in combat situations, heavily advise making the krav maga moves not work if you've got chunky fingers to accomodate

I do agree with you on point 2, im looking at ways to prevent them using insulated gloves with the skillchip but this was specifically requested by the host to be in the warden outfit loadout instead of the locker that is the primary reason this PR was created

2022-12-20 18:02 UTC, Iamgoofball commented
have you tried asking for a reason before blindly doing things? you can easily miss potentially better solutions to a problem as a result if you never question an approach to something before implementing it

2022-12-20 20:28 UTC, Zergspower commented
That's a far reach in assumptions as sec getting insuls is something we rarely if ever see here. Also check your tone, you're being a complete ass for no reason.

> have you tried asking for a reason before blindly doing things? you can easily miss potentially better solutions to a problem as a result if you never question an approach to something before implementing it

2022-12-20 20:45 UTC, CliffracerX commented
> have you tried asking for a reason before blindly doing things? you can easily miss potentially better solutions to a problem as a result if you never question an approach to something before implementing it

Discussion around this PR and the rebalance of Krav Maga has been ongoing in the community for a good couple days now.  If you were actually a part of that community, you'd know this wasn't just "blindly doing things", and you'd have had even less of an excuse to come be a jerk to someone still learning the ropes of contributing.

2022-12-21 00:24 UTC, softcerv commented
> @Zonespace27 Do you want the skillchip to be limited to just security Areas? thats how the chef skillchip works, this simply makes it work like the Krav maga implant

I think this is a good idea. Otherwise it becomes a martial art that can be used anywhere on the station and can't easily be disarmed.

2022-12-21 00:27 UTC, Iamgoofball commented
i am not "being a jerk" by saying that it's okay to question the words "host request", especially given the fact that "How This Contributes To The Skyrat Roleplay Experience" does not match the actual reason for the request and that the fact it was a host request was only pulled out upon criticism of the PR, which per two separate maintainers is "the HoS keeps stealing it from the warden" which goes completely unmentioned in this PR, the PR description, and xyel's posts here

i am unsure as to why nobody wants to discuss that aspect of this, but given that it is the actual reason the PR is being made per two separate maintainers, i feel it's relevant to discuss and thus relevant to consider to the PR. 

xyel is not an child who's going to melt down at you if you question his opinions, dancing around his reasoning for the request simply makes it look like you think he's a baby who can't take criticism and you and I both know that's far, far more rude than me being blunt about the situation at hand here

it is not recommended to make big sweeping balance changes to things without documenting the reasoning for precisely this reasoning, important context behind a decision can easily get lost to those not privy to the internal discussions as a result, people should not have to be asking maintainers why a PR exists because the PR itself is devoid of any and all context and reasoning

xyel is correct that there's an issue if heads of security are stealing their subordinate's gear, but the solution to that is not to apply a massive buff to said gear, it is to change the conditions under which they're acquiring gear in the first place to the accepted standards for gear acquisition, such as cargo, thereby resolving this in a far more subtle way that lets admins do their job

overall, this PR is a massive, massive buff to krav maga and wardens by making them able to krav maga with insulated gloves, and unable to be disarmed of krav maga without surgery to remove their skill chip, to resolve a problem that isn't documented at all in the actual PR description, the comments before this, or the commit messages and comments in-code, this is a sledgehammer fix when we need a screwdriver fix

the codebase is not capable of nuance in situations where player behavior is subpar, we have a sledgehammer, the admins are the ones with the more subtle and nuanced tools to resolve this, so it should be up to them, we can only guide players towards good interactions with eachother, admins are the ones who enforce those good interactions if they ignore our guiding stones

2022-12-21 02:19 UTC, ChungusGamer666 commented
the host needs to make better requests

2022-12-21 02:43 UTC, SomeRandomOwl commented
> > @Zonespace27 Do you want the skillchip to be limited to just security Areas? thats how the chef skillchip works, this simply makes it work like the Krav maga implant
> 
> I think this is a good idea. Otherwise it becomes a martial art that can be used anywhere on the station and can't easily be disarmed.

I can also look into doing this as this technically would nerf it for wardens who like to walk out of brig when there is action going on

2022-12-21 02:46 UTC, Iamgoofball commented
it doesn't need a nerf if you aren't giving it a massive, unneeded buff in the first place

2022-12-21 03:44 UTC, YakumoChen commented
> That's a far reach in assumptions as sec getting insuls is something we rarely if ever see here. 

That's because literally none of security's weapons work with insuls
This provides a means to enable exactly that.

No wonder goof made the other PR

2022-12-21 04:42 UTC, hugmeorelse commented
Please keep comments pertinent to the PR. Thanks.

2022-12-21 04:45 UTC, hugmeorelse commented
Also, people are commenting on this without understand the problem, namely the fact that there is often conflict in regards to Head of Security stealing Krav Maga gloves from the warden frequently. It's a completely unnecessary problem which despite what some people here assert does not add much to the overall gameplay loop. My main concern right now is putting a stop to issues that staff simply should not have to deal with.

2022-12-21 05:25 UTC, hugmeorelse commented
Anyways, I mentioned this to the maintainers but if there are any alternative solutions out there, feel free to share. Either ways, I'll be talking to maintainers and staff about this. I hope to see new comments in regards to why this change was requested. However, please refrain from being a dick. This person spent the time to fulfill a request I made a long time ago, and they don't deserve to be dog-piled on for that. As someone said, they are a new contributor. Be nice. It's not their fault anyways that this PR exists.

2023-01-10 01:05 UTC, closed without merging