Void Raptor Security door access fix
Skyrat-SS13/Skyrat-TG pull request #18283
Opened 2022-12-23 07:37 UTC by SomeRandomOwl

## About The Pull Request

This fixes two minor issues with void raptors security area, it fixes a misplaces access helper on the wardens office which granted any sec officer access to the wardens office and also removed a detective spawn point as detectives where spawning in an area which they do not have access to open the doors in.

## How This Contributes To The Skyrat Roleplay Experience

This prevents people from getting unintended access to places they shouldn't have access to and prevents round start detectives from spawning trapped in security.

## Proof of Testing

<details>
<summary>

![image](https://user-images.githubusercontent.com/2568378/209291538-29fc0e72-4e9b-4289-a50a-aaf0f0738dc6.png)

</summary>
  
</details>

## Changelog

:cl:
fix: Fixed the rear door to the wardens office having the wrong access requirements set
fix: Fixed a detective spawn point which spawned the round-start detectives trapped within security
/:cl:

2022-12-23 07:38 UTC, SomeRandomOwl commented
This time the PR is without me accidentally forgetting to swap to the master branch first

2022-12-23 11:41 UTC, Jolly-66 submitted a review, later dismissed
Editor screenshots are not proof of testing.

2022-12-23 14:26 UTC, SomeRandomOwl commented
> Editor screenshots are not proof of testing.

I added a second screenshot showing the updated access

2022-12-29 20:23 UTC, Jolly-66 requested changes
You need to remove the lawyer landmark as well.
On `/datum/id_tim/job/lawyer`, Lawyers do not have brig access, only brig **entrance**.

![image](https://user-images.githubusercontent.com/70232195/210007647-cc671523-05fa-4ca5-a741-4176e920b2de.png)

2022-12-29 20:35 UTC, SomeRandomOwl commented
> You need to remove the lawyer landmark as well. On `/datum/id_tim/job/lawyer`, Lawyers do not have brig access, only brig **entrance**.
> 
> ![image](https://user-images.githubusercontent.com/70232195/210007647-cc671523-05fa-4ca5-a741-4176e920b2de.png)

Done, and image updated as well for the PR screenshots

2022-12-29 23:06 UTC, Jolly-66 approved these changes

2022-12-29 23:06 UTC, merged