[Modular] Donator stuff (DNM)
Skyrat-SS13/Skyrat-TG pull request #18324
Opened 2022-12-25 01:35 UTC by StrangeWeirdKitten

## About The Pull Request

Adds mine and Synthax's donator item.

Mine is another ring/hypno that flashes fancy text on a whisper, and Synthax is a bunny plush of their spritework.
Wehweh told me the idea sounded good but to check with the maintainers. So here's the PR.

![image](https://user-images.githubusercontent.com/95130227/209454365-573fe6ae-81ee-457f-8717-5f64b801b1e9.png)

## Proof of Testing

<details>
  
![image](https://user-images.githubusercontent.com/95130227/209454364-a1fdef6a-2081-4c0b-bbd4-7df7ebf61203.png)
https://i.gyazo.com/bcce4515a148655ce0f35729ae6b60e0.gif

</details>

2022-12-25 01:38 UTC, Zonespace27 requested changes, later dismissed

2022-12-25 01:38 UTC, Zonespace27 commented on modular_skyrat/modules/customization/game/objects/items/plushes.dm
> +	squeak_override = list('modular_skyrat/modules/customization/game/objects/items/sound/deerplush.ogg')
```suggestion
	squeak_override = list('modular_skyrat/modules/customization/game/objects/items/sound/deerplush.ogg' = 1)
```

2022-12-25 01:38 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_quirks.dm
> +
remove

2022-12-25 01:38 UTC, Zonespace27 commented on tgui/packages/tgui-panel/styles/goon/chat-dark.scss
> +.glossy {
add to lightmode too

2022-12-25 01:38 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/lewd_defines.dm
> +#define TRAIT_HYPNOTIC "hypnotic"
why

2022-12-25 01:38 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	name = "Suspiciously Glossy Ring"
lower case

2022-12-25 01:38 UTC, Zonespace27 commented on modular_skyrat/modules/customization/game/objects/items/plushes.dm
> +	name = "Lop Bunny Plushie"
lower case

2022-12-25 01:55 UTC, tf-4 requested changes

2022-12-25 01:55 UTC, tf-4 commented on modular_skyrat/modules/customization/game/objects/items/plushes.dm
> +	attack_verb_simple = list("nibble", "squeak", "nose twitch", "thump", "fall over")
"falls over" doesn't really make much sense here, doubly so for its simple form

2022-12-25 02:03 UTC, StrangeWeirdKitten commented
the pains of putting crap on your master branch and they're not even merged yet.

2022-12-28 06:01 UTC, tf-4 requested changes
Sorry for the delay on this one.

2022-12-28 06:01 UTC, tf-4 commented on modular_skyrat/modules/customization/game/objects/items/plushes.dm
> +	attack_verb_simple = list("nibble", "squeak", "nose twitch", "thump", "flop over")
It still doesn't make much sense. `"You flop over John Syndicate in the chest!"`?

2022-12-28 22:20 UTC, tf-4 commented on modular_skyrat/modules/customization/game/objects/items/plushes.dm
> +	name = "lop Bunny plushie"
```suggestion
	name = "lop bunny plushie"
```

2022-12-28 22:20 UTC, tf-4 approved these changes

2022-12-28 22:38 UTC, merged