Changed Syndi-Fox to be have the same basic Fox AI as other simple mob foxes
Skyrat-SS13/Skyrat-TG pull request #18332
Opened 2022-12-25 19:00 UTC by SomeRandomOwl

## About The Pull Request

Changes syndi-fox to be under the fox simple mob so its not just a lifeless statue that just sits on its bed and has a little more interaction with the crew of DS-2

## How This Contributes To The Skyrat Roleplay Experience

Syndi-Fox instead of just standing in one place will now instead walk around and have similar emotes to that of a normal fox would instead of just being a lifeless and dull, but fairly unique station pet. It will now actually interact with the crew a bit more and can be the cute addition it is to the syndicate base.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/2568378/209479211-964346fe-4aee-4fca-a17c-3f9db36dad04.png)

https://user-images.githubusercontent.com/2568378/209479264-ff95a7d3-7412-4a18-98ff-36ff7ea6a3a8.mp4

</details>

## Changelog

:cl:
fix: Gives the Syndi-Fox the same simplemob ai as other foxes
/:cl:

2022-12-25 20:08 UTC, SomeRandomOwl commented
Swapped it to the Dog AI as making a new simple mob is not allowed

2022-12-26 01:58 UTC, Zonespace27 requested changes
Needs UPDATED testing evidence

2022-12-26 02:08 UTC, SomeRandomOwl commented
> Needs UPDATED testing evidence

Done, new video showing it has dog AI

2022-12-26 03:23 UTC, Zonespace27 approved these changes

2022-12-26 03:23 UTC, merged