[EVIL CODE] [LATE MEOWY CHRISTMAS] Replaces the poorly fitting ashwalkers on icebox with significantly cooler catgirls
Skyrat-SS13/Skyrat-TG pull request #18364
Opened 2022-12-27 18:24 UTC by Paxilmaniac

## About The Pull Request

Ashwalkers on icebox was always kinda silly, what are these lizards doing here they'd freeze!

What would be better you ask? Catgirls of course! Catgirls are always the answer, especially primitive catgirls wearing this absolutely fire outfit:

![image](https://user-images.githubusercontent.com/82386923/209705732-21fef819-6c11-4244-866d-dbc215a9a3e9.png)

Now of course it felt like the old castle thing didn't quite fit anymore, so now they also get a new camp just for them!

![image](https://user-images.githubusercontent.com/82386923/209705805-618738ab-5ba3-47d1-9cae-bbdb798c917a.png)
![image](https://user-images.githubusercontent.com/82386923/209705811-81d57e55-50c1-4b82-961d-4093aa55dd76.png)

## How This Contributes To The Skyrat Roleplay Experience

As many people have said before, ashwalkers being on icebox is a silly prospect, lizards (renounced for not liking cold temperatures) living in my icy wasteland? Blasphemous I say. Now, catgirls dressed like god of war characters? Now we're talking.

## Proof of Testing

My proof of testing is in the about the pull request section, if you somehow missed it.

## Changelog

:cl:
add: To replace ashwalkers on icebox, a small band of primitive felinids and their new camp can now be found in the wastes
del: Ashwalkers (lizards) will no longer appear on icebox.
/:cl:

2022-12-27 18:25 UTC, Erol509 commented
Great idea, but ears could be bigger

2022-12-27 18:26 UTC, Paxilmaniac commented
You can pick bigger ears its not limited to just what's in that screenshot

2022-12-27 18:33 UTC, PCPort commented
This will be an ice addition fur all the people who complain about the lack of ghost roles on icebox. There snow way anyone could possibly object to such a feature.

2022-12-27 18:33 UTC, Stalkeros2 commented
This is too good to be true.

2022-12-27 18:34 UTC, Nerev4r commented
![tumblr_78010a30010de25d513e60ea6ea3abc3_56e53ec1_1280](https://user-images.githubusercontent.com/12636964/209708259-5ee7385d-c016-4b76-8cad-a5353b70363f.jpg)

2022-12-27 18:37 UTC, Stalkeros2 commented
wait
how do they repopulate tho
pic unrelated
![image](https://user-images.githubusercontent.com/42087567/209708530-198500af-2551-47c7-8c83-fbe48a853ca1.png)

2022-12-27 18:49 UTC, Paxilmaniac reviewed
![image](https://user-images.githubusercontent.com/82386923/209709727-7b267084-3e82-4f31-b33a-5de1da19f7fc.png)

2022-12-27 18:55 UTC, nikita-chekistov commented
God-tier PR
![shocked-shookt](https://user-images.githubusercontent.com/59139863/209710261-c2ca3933-9825-4c85-8257-deed8bbff124.gif)

2022-12-27 19:24 UTC, Zergspower commented
oh god

2022-12-27 19:26 UTC, Zergspower commented
at least make them Tajarans smh - i can already smell and hear them even though this isnt outside of git

2022-12-27 19:48 UTC, rosextango commented
> wait how do they repopulate tho pic unrelated ![image](https://user-images.githubusercontent.com/42087567/209708530-198500af-2551-47c7-8c83-fbe48a853ca1.png)

male catgirls??? duh

2022-12-27 19:57 UTC, PCPort commented
> wait how do they repopulate tho pic unrelated ![image](https://user-images.githubusercontent.com/42087567/209708530-198500af-2551-47c7-8c83-fbe48a853ca1.png)

![image](https://user-images.githubusercontent.com/62071287/209716419-0c1ccdad-b55f-46a9-9795-996c7b9df2d9.png)

2022-12-27 19:58 UTC, CandleJaxx commented
finally. a good pr

2022-12-27 20:04 UTC, Jolly-66 commented
![hlwjpj2v25k91](https://user-images.githubusercontent.com/70232195/209716958-a865b8da-fa8e-4905-8136-2d0149467b62.jpg)

2022-12-27 20:32 UTC, Paxilmaniac commented
Why accessibility tag what

2022-12-27 20:37 UTC, PCPort commented
> Why accessibility tag what

No more icebox ash walkers = no more icebox ash walkers dying to cold like fools

2022-12-27 21:13 UTC, tf-4 submitted a review, later dismissed

2022-12-27 21:13 UTC, tf-4 commented on modular_skyrat/modules/GAGS/greyscale_configs.dm
> +	name = "Primtive Body Wraps"
```suggestion
	name = "Primitive Body Wraps"
```

2022-12-27 21:13 UTC, tf-4 commented on modular_skyrat/modules/GAGS/greyscale_configs.dm
> +/datum/greyscale_config/icebox_catgirl_wraps
```suggestion
// Evil primitive catgirl clothing

/datum/greyscale_config/primitive_catgirl_wraps
```
Seeing as we're quite possibly going to lose icebox in favour of a new ice map from upstream soon(tm), it'd probably be prudent not to use its name directly. I won't go through making suggestions on everything, but you get the idea.

2022-12-27 21:13 UTC, tf-4 commented on modular_skyrat/modules/GAGS/greyscale_configs.dm
> +	name = "Primtive Body Wraps (Worn)"
```suggestion
	name = "Primitive Body Wraps (Worn)"
```

2022-12-27 21:13 UTC, tf-4 commented on modular_skyrat/modules/icebox_catgirls/code/species.dm
> +	spoken_languages = list(
They should speak neko

2022-12-27 21:45 UTC, GoldenAlpharex commented
> Why accessibility tag what

Because it makes primitive catgirls accessible, duh.

2022-12-27 21:46 UTC, Paxilmaniac commented
> > Why accessibility tag what
> 
> Because it makes primitive catgirls accessible, duh.

This makes so much more sense thank you

2022-12-27 21:56 UTC, Nerev4r commented on modular_skyrat/modules/icebox_catgirls/code/species.dm
> +	spoken_languages = list(
https://user-images.githubusercontent.com/12636964/209725873-904c1480-5098-41d5-aa41-d3eee85a93bc.mp4

2022-12-27 22:37 UTC, Stalkeros2 commented
Amazon snow leopard catgirls......

2022-12-27 22:43 UTC, Ebin-Halcyon commented
![image](https://user-images.githubusercontent.com/81479835/209731442-109776c4-934c-48e1-9208-81b5ca84255e.png)

2022-12-27 23:51 UTC, Elli-Skala commented
The two whetstones likely aren't a good idea both for balance but also being near unreplaceable gamer loot

2022-12-27 23:56 UTC, Higgin commented
if this is evil i dont want to be good

2022-12-28 01:29 UTC, press-mark commented
GOOD PR

![image](https://user-images.githubusercontent.com/6972764/209743211-2c364370-1e4b-4650-88b5-bd4461ffa206.gif)

2022-12-28 05:15 UTC, CliffracerX commented
This has to be the most effort I've seen put into a meme PR so far, but also- imagine not spending your meme PR efforts on buffing ashies & icewalkers to god-tier, smh.  New spawn castle is cool, though.

2022-12-28 12:08 UTC, Tailiik commented
Chad furred dragon icewalkers vs virgin anime catgirls

2022-12-28 12:10 UTC, HoodMilk commented
I didn't care about planetside ghost roles. 
Now I do.

2022-12-28 14:54 UTC, Pirill commented
I unironically like this and hope it's not gonna be just a meme PR. Please, I need them.

2022-12-28 19:04 UTC, Paxilmaniac commented
> Chad furred dragon icewalkers vs virgin anime catgirls

So called chad dragons when they don't fukken exist

2022-12-28 19:51 UTC, Plum-but-gayer commented
love this +1 +1 +1 felinids finally having some sort of skyrat specific lore to any degree that isn't just tg anime memestuff

2022-12-29 22:54 UTC, theselfish commented
They should be given nekomantic.

I know we removed it for some stupid, inane, asinine reason but a tribal race of cat people should have their own language.

2022-12-30 07:41 UTC, axietheaxolotl commented
i know why you made this PR, your motivation is well known to me
![Fj83bKmWQAAhDwG](https://user-images.githubusercontent.com/86872535/210046419-abbb7489-156f-4554-9f73-83a8501fd9b7.jpg)

2022-12-30 09:30 UTC, Goobler21 commented
![image](https://user-images.githubusercontent.com/121666517/210055160-dddfd606-88fe-4205-92b0-c7c2f735c0a7.png)

2022-12-30 17:10 UTC, Zergspower commented
@Paxilmaniac they have sensors that are showing up on the station btw

2022-12-30 17:54 UTC, Paxilmaniac commented
The issue was fixed in the latest commit it just hasn't been updated

2022-12-30 23:31 UTC, Paxilmaniac commented
fuvk you skyratbot

2022-12-31 09:15 UTC, Erol509 commented
Its the best thing that was ever created, when will be truly merged? And after this, we will have more felinids than the crew itself

2023-01-01 12:48 UTC, Erol509 commented
`
	bodytemp_normal = 286 // If a normal human gets hugged by one its gonna feel cold
	bodytemp_heat_damage_limit = T20C // To them normal station atmos would be sweltering
	bodytemp_cold_damage_limit = 213 // Man up bro its not even that cold out here
`

Max heat damage limit doesnt work...when you walk inside the station you can exist her like normal crew member 
 If a normal human gets hugged by one its gonna feel cold - this one doesnt work for some reason

2023-01-01 16:49 UTC, Paxilmaniac commented
> `
> 
> ```
> bodytemp_normal = 286 // If a normal human gets hugged by one its gonna feel cold
> 
> bodytemp_heat_damage_limit = T20C // To them normal station atmos would be sweltering
> 
> bodytemp_cold_damage_limit = 213 // Man up bro its not even that cold out here
> ```
> 
> `
> 
> Max heat damage limit doesnt work...when you walk inside the station you can exist her like normal crew member If a normal human gets hugged by one its gonna feel cold - this one doesnt work for some reason. But it worked when I hugged fellow tribe member, but not on the crew member
> 
> on station you you have like 16*C

Normally the station would be around like 21C but seeing as its icebox I guess it gets chilly indoors

2023-01-01 17:27 UTC, Erol509 commented
> > Normally the station would be around like 21C but seeing as its icebox I guess it gets chilly indoors

Ice box is quite special. Temps around 20-21*C are really hard to find there. Mostly you have 16-19*C

2023-01-01 17:27 UTC, Paxilmaniac commented
Surely I did not just say this.

2023-01-01 20:39 UTC, Zonespace27 requested changes, later dismissed
few quick things i noticed

2023-01-01 20:39 UTC, Zonespace27 commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +	var/datum/team/primitive_catgirls/feline_team
null (but don't delete) on destroy

2023-01-01 20:39 UTC, Zonespace27 commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +/obj/effect/mob_spawn/ghost_role/human/primitive_catgirl/Initialize(mapload)
put this at the top pls

2023-01-01 20:39 UTC, Zonespace27 commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +	var/datum/team/primitive_catgirls/team
null this out too

2023-01-01 20:39 UTC, Zonespace27 commented on modular_skyrat/modules/primitive_catgirls/code/smelling_salts.dm
> +	to_chat(carbon_target, "<span class='userdanger'>[CONFIG_GET(string/blackoutpolicy)]</span>")
can you use a span define here?

2023-01-01 20:39 UTC, Zonespace27 commented on modular_skyrat/modules/primitive_catgirls/code/clothing_vendor.dm
> +	/*product_categories = list(
L

2023-01-02 17:19 UTC, linnpap commented
why are they scantily clad felinids
they would probably die from hypothermia if this were realistic

2023-01-02 18:09 UTC, Erol509 commented
When you jump inside the fridge, you are no longer suffering from heat. After that you can live like a normal crew.

2023-01-02 19:30 UTC, ArdentSpark commented
I know this is still in progress, but can the newer additions that are still being pushed be edited into the changelog/PR body for transparancy when possible before it gets merged? I'd love to keep up with the changes but I don't feel like going through all the files

2023-01-10 22:28 UTC, press-mark commented on modular_skyrat/modules/primitive_catgirls/code/language.dm
> +	secret = TRUE
space AND tab indentation 👍

2023-01-10 22:51 UTC, Paxilmaniac commented on modular_skyrat/modules/primitive_catgirls/code/language.dm
> +	secret = TRUE
I ALREADY FIXED IT

2023-01-11 10:23 UTC, YakumoChen commented
for some reason icecats can't speak the new language now

2023-01-22 06:19 UTC, Paxilmaniac commented
I will return to this once its 'ready' to go again, there are good few issues in unrelated systems I need to fix first.

2023-02-13 20:28 UTC, Paxilmaniac commented
![image](https://user-images.githubusercontent.com/82386923/218567618-ac6063a5-7397-4c98-babb-aac7ff259f72.png)

2023-03-10 18:11 UTC, Gandalf2k15 approved these changes
LGTM

2023-03-17 22:32 UTC, GoldenAlpharex requested changes
I forgot to submit this review WEEKS ago, hopefully these comments are still valid. I didn't check them.

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/clothing_vendor.dm
> +		/obj/item/clothing/head/pelt/wolf/white = 5,
Could also be nice to use the vendor categories.

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/map_items.dm
> +/obj/structure/bonfire/oh_yeah_its_grilling_time/Initialize(mapload)
A more intuitive name for this subtype would be better, please.

The "funny" factor just makes looking up for it more complex in the future, and makes the typepath a lot longer for no reason.

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/smelling_salts.dm
> +	playsound(src, 'modular_skyrat/modules/emotes/sound/emotes/female/female_sniff.ogg', 50, FALSE)
Only female sniff? I'd have to hear it in-game but just seeing this feels really weird lol.

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +#define ICECAT_POLICY_LINK "https://wiki.skyrat13.tk/w/index.php/Ghost_Role_policy#Icewalkers"
This should be done via config, and not just a hardcoded define. Check how the corpregs stuff does it (and if it's not config-based I swear I'm not going to be happy)

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +	being reckless with the outsiders will not have the Gods be so kind."
```suggestion
		It's been the home of your ancestors, and their ancestors, and the ones before them. \
		Currently, you and your kin live in uneasy tension with your nearby human-and-otherwise \
		neighbors. Keep your village and your Kin safe, but bringing death on their heads from \
		being reckless with the outsiders will not have the Gods be so kind."
```

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/language.dm
> +	"bar", "dar", "akur", "jer", "bær", "múl", "fjörð", "jah", "dah", "dim", "din", "dir", "dur", "nya", "miau", "mjau", "ný", "kt", "hø",
```suggestion
		"al", "an", "ar", "að", "eg", "en", "er", "ha", "he", "il", "in", "ir", "ið", "ki", "le", "na", "nd", "ng", "nn", "og", "ra", "ri",
		"se", "st", "ta", "ur", "ði", "va", "ve", "sem", "sta", "til", "tur", "var", "ver", "við", "ður", "það", "þei", "með", "ega", "ann",
		"tur", "egr", "eda", "eva", "ada", "the", "tre", "tai", "thor", "thur", "ohd", "din", "gim", "per", "ger", "héð", "bur", "kóp", "vog",
		"bar", "dar", "akur", "jer", "bær", "múl", "fjörð", "jah", "dah", "dim", "din", "dir", "dur", "nya", "miau", "mjau", "ný", "kt", "hø",
```

2023-03-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +	var/datum/team/primitive_catgirls/team
Documentation here please.

2023-03-18 03:49 UTC, Paxilmaniac commented on modular_skyrat/modules/primitive_catgirls/code/clothing_vendor.dm
> +		/obj/item/clothing/head/pelt/wolf/white = 5,
I dunno all of the items fit on one screen that you don't have to scroll at all to see all of. I thought of doing categories before but it was pretty barren looking with them.

2023-03-18 03:51 UTC, Paxilmaniac commented on modular_skyrat/modules/primitive_catgirls/code/smelling_salts.dm
> +	playsound(src, 'modular_skyrat/modules/emotes/sound/emotes/female/female_sniff.ogg', 50, FALSE)
It looks weird but you can't like tell at all its supposed to be /female/, it just sounds like a sniff

2023-04-03 17:19 UTC, GoldenAlpharex requested changes

2023-04-03 17:19 UTC, GoldenAlpharex commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +	// Tracks the antag datum's 'team' for showing in the ghost orbit menu
```suggestion
	/// Tracks the antag datum's 'team' for showing in the ghost orbit menu
```

2023-04-03 17:21 UTC, GoldenAlpharex approved these changes

2023-04-04 17:35 UTC, Gandalf2k15 approved these changes
ok whatever

2023-04-04 17:36 UTC, merged