Void Raptor - Fixes for lighting mostly
Skyrat-SS13/Skyrat-TG pull request #18446
Opened 2023-01-01 07:44 UTC by Zergspower

## About The Pull Request

Fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/18312

saw this and decided to check out the rest of the station for any lighting things i found and corrected a number of them - mostly the ones sitting on glass but also a fair number that were doubled up.

<details>
<summary>Screenshots</summary>

Arrivals
![image](https://user-images.githubusercontent.com/22140677/210163833-1f4554d3-35a6-485d-899d-006344b250f3.png)
Brig 1 - missing 1
![image](https://user-images.githubusercontent.com/22140677/210163839-0898d20f-4564-4d11-8d5e-2f6e974394c8.png)
Sci 1 - glasslight
![image](https://user-images.githubusercontent.com/22140677/210163842-0d619b66-e369-46d1-a69a-4630506726bc.png)
Atmos 1 - glasslight(s)
![image](https://user-images.githubusercontent.com/22140677/210163854-3dfa13b2-b4dc-4cdd-ae71-891aede05f83.png)
Atmos 2 - glasslight
![image](https://user-images.githubusercontent.com/22140677/210163857-58052820-c231-40f8-841e-0cfa2938e307.png)
Brig 2 - double light
![image](https://user-images.githubusercontent.com/22140677/210163863-6d36e81d-36da-456b-b3a8-ac9011061019.png)
Cargo 1 - double light (and double stacked for double the fun!)
![image](https://user-images.githubusercontent.com/22140677/210163874-0bebe0a0-0dbd-44aa-9a0d-8ee148f05d66.png)
Sci 2 - Glasslight
![image](https://user-images.githubusercontent.com/22140677/210163885-165c5e2f-bcfe-47a2-b07a-f30f5a44b672.png)
Atmos 3 - glasslight(s)
![image](https://user-images.githubusercontent.com/22140677/210163897-1e58410a-5c16-4156-b711-1fba4803afcf.png)

</details>

## How This Contributes To The Skyrat Roleplay Experience

Bit more consistency aligned with our normal maps - the knife should act properly now as well

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Atmos

![image](https://user-images.githubusercontent.com/22140677/210163982-1f9b7b36-13b3-4c22-b824-5f4a89bd547c.png)

![image](https://user-images.githubusercontent.com/22140677/210163983-f9dd48d7-c5d4-44c9-bba2-389e024dcea4.png)

![image](https://user-images.githubusercontent.com/22140677/210163988-03f797ef-9730-490f-b1eb-9a6c94fbd598.png)

Brig

![image](https://user-images.githubusercontent.com/22140677/210163970-4efcc19c-fdfe-4e50-95f2-67c1cea92b4b.png)

Arrivals

![image](https://user-images.githubusercontent.com/22140677/210163968-0cba06b7-1e0b-44ca-a0b2-b3c5778ac775.png)

Science
  
![image](https://user-images.githubusercontent.com/22140677/210163965-1f1006e6-934c-43aa-be55-43eb2214135a.png)
![image](https://user-images.githubusercontent.com/22140677/210163966-79b81e3f-8e00-4b1a-aa7c-9f5777534e5c.png)

Kitchen knife is now the proper subtype

![image](https://user-images.githubusercontent.com/22140677/210164012-c3636fe6-4c77-4a21-94c2-e51bbdd53c00.png)

</details>

## Changelog

:cl:
fix: Void Raptor - Fixes for lights in Sci/Atmos/Brig/Arrivals
fix: Void Raptor - Spawns the correct chefs knife in the kitchen
/:cl:

2023-01-01 18:23 UTC, Paxilmaniac commented
As a wise PR template once said:

**To our mappers and spriters: Posting screenshots of content INSIDE EDITORS (aseprite, PDN, SDMM, ect) is NOT valid proof of testing. Please make sure that you COMPILE the game and provide PROOF you tested your edits.**

2023-01-01 20:35 UTC, Jolly-66 commented
I'm on mobile so I'm just adding my two cents,

1. Paxil you silly Billy, you're looking in the wrong section
2. I don't like the light insanity that's going on. This seems like it was done overly haphazardly and carelessly. I'll give my full sentiment when I can get around to properly review this and compare the lighting diff.

2023-01-01 20:37 UTC, Paxilmaniac commented
You are right I did look at the complete wrong section carry on.

2023-01-02 05:24 UTC, Zergspower commented
Woowwwwwwwwwwww i even made it easy to read

2023-01-02 05:25 UTC, Zergspower commented
> I'm on mobile so I'm just adding my two cents,
> 
> 1. Paxil you silly Billy, you're looking in the wrong section
> 2. I don't like the light insanity that's going on. This seems like it was done overly haphazardly and carelessly. I'll give my full sentiment when I can get around to properly review this and compare the lighting diff.

i mostly was making it sensical visually - and ofc getting rid of the glass and duplicate sitting ones

2023-01-04 16:06 UTC, Jolly-66 requested changes
I'm not sold on some of these changes, and I really don't like the lightsanity thats going on.

<details>
<summary> Review </summary>

I know you added a light here, but there's 0 reason to have all the lights in a row here, there's simply too many. Remove the light you had and move the lights around, they don't need to be jumbled up at all.
![image](https://user-images.githubusercontent.com/70232195/210595077-b968b573-c520-42b9-a8cc-5067bb829a63.png)

Move this light.
![image](https://user-images.githubusercontent.com/70232195/210595223-45895307-788f-4bdd-9584-71460a4b9762.png)

The lights in robotics was fine before. Revert that, with the exception of the light on glass.

Again with excessive lights at arrivals. Trim it.
![image](https://user-images.githubusercontent.com/70232195/210595910-bc8de1a4-aabd-43f8-920e-b16890b550da.png)

Extra light in amtos.
![image](https://user-images.githubusercontent.com/70232195/210596225-8cde676c-47e6-4526-914a-1109d8516e27.png)

</details>

2023-01-04 16:40 UTC, Zergspower commented
<details>
<summary>Quick changes</summary>

Brig part - since this section only had the lights above each cell how does this work in a weird-ass-triangle deal
![image](https://user-images.githubusercontent.com/22140677/210604442-bb93d9d0-43ff-4fac-9a11-d89917cda709.png)

Arrivals - cut them back and moved the leftside over one and the right over one, left the bench areas each with 1 light provided
![image](https://user-images.githubusercontent.com/22140677/210604564-3871a431-5134-48c1-b38f-9c777e1854fc.png)


Robotics did have a dark spot in it but i removed the 2nd lamp over the surgery area and moved the top middle over 1 slot
![image](https://user-images.githubusercontent.com/22140677/210604745-dec375c7-aebf-41b6-9f52-1ad7a8c7dc41.png)

whoops missed deleting that atmos one - there were runner lights for some reason underneath the connector ports so I deleted those and made one for each monitor
![image](https://user-images.githubusercontent.com/22140677/210604956-89e0a2ae-46cd-4e67-9ad4-1c59f663eba4.png)

</details>


if those look good i'll compile n update the section

2023-01-11 23:40 UTC, Jolly-66 requested changes, later dismissed
Conflicts.

2023-01-12 21:02 UTC, Zergspower commented
COME THE FUCK ON

2023-01-12 21:46 UTC, Zergspower commented
yeah those CI fails are completely unrelated to this PR

2023-01-19 19:30 UTC, GoldenAlpharex approved these changes
Looks good to me, I'm blaming Jolly if this wasn't ready to merge :)

2023-01-19 19:30 UTC, merged