[Modular] Alter Form hides locked parts
Skyrat-SS13/Skyrat-TG pull request #18465
Opened 2023-01-02 02:15 UTC by softcerv

## About The Pull Request
Alter Form hides parts that have the locked variable set to true.

## How This Contributes To The Skyrat Roleplay Experience
![image](https://user-images.githubusercontent.com/68373373/210188256-67bf997f-f88e-440c-88b1-0458dfc016d9.png)
People shouldn't be able to use blacklisted parts

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/68373373/210190880-f015ef1c-bba3-4b14-bbd5-e205038c3667.png)

</details>

## Changelog

:cl:
fix: Alter Form now longer shows parts that it shouldn't
/:cl:

2023-01-03 22:52 UTC, GoldenAlpharex requested changes, later dismissed

2023-01-03 22:52 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/roundstartslime.dm
> +	avalible_choices = parts_lists.Copy()
You should only run the whole "parts_list" part if `available_choices` is null, otherwise it defeats the point in having it as a static thing.

2023-01-03 22:52 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/roundstartslime.dm
> +	avalible_choices = parts_lists.Copy()
Also it's `available` not `avalible` :^)

2023-01-13 23:56 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/roundstartslime.dm
> +		for(var/parts as anything in parts_lists[parts_list])
unecessary as anything

2023-01-13 23:56 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/roundstartslime.dm
> +	available_choices = parts_lists.Copy()
why copy it

2023-01-14 06:47 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/roundstartslime.dm
> +	if(available_choices)
```suggestion
	if(length(available_choices))
```

2023-01-14 06:48 UTC, Zonespace27 approved these changes

2023-01-14 06:55 UTC, merged