this will be better
Skyrat-SS13/Skyrat-TG pull request #18595
Opened 2023-01-08 18:50 UTC by Zonespace27

## About The Pull Request
Allows nukeops to be non-human

## How This Contributes To The Skyrat Roleplay Experience
Asimov isn't the default lawset here, also with how we handle prefs, most mobs look awful when forced to be human

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/41448081/211213496-0c10b411-d8d2-4e05-9cd9-4b7fc642c853.png)

</details>

## Changelog

:cl:
qol: Nukeops can now be any species instead of just human
/:cl:

2023-01-09 03:55 UTC, tf-4 requested changes
It should have something in place for plasmamen, as unlikely as it is to ever be an issue

2023-01-10 00:03 UTC, Zonespace27 commented
> It should have something in place for plasmamen, as unlikely as it is to ever be an issue

Done

2023-01-10 01:13 UTC, tf-4 approved these changes
lgtm as long as you tested the plasmaman stuff

2023-01-10 05:03 UTC, vinylspiders commented
About the plasmaman thing-- I'm actually working on a less hacky solution for this in #18614 .

Instead of doing what you did, there is a (currently not 100% working) function intended for this very purpose, and you'd call it like this
:
`operative.dna.species.pre_equip_species_outfit(null, operative)`

Once my changes go through pre_equip_species_outfit() should work and take care of it, not only for plasmamen but for vox and any other future races that need it.

2023-01-15 13:48 UTC, tf-4 commented
We can adjust it later

2023-01-15 13:48 UTC, merged