[Semi-modular] Ports pouches, changes engi-vend prices, atmos techs get their access back
Skyrat-SS13/Skyrat-TG pull request #1860
Opened 2020-11-26 16:00 UTC by NotRanged

## About The Pull Request

Materials and ammo pouches ported from old skyrat, available in their respective vendors once again.
Atmospheric Technician access changed to how it is on skyrat - no secure storage or telecomms.
RCD made affordable to engineers again, scanner goggles stock increased.
Added *tilt emote.

## Why It's Good For The Game

Weird ass TG balance begone, also the pouches were great.

## Changelog
:cl:
add: Ported materials and ammo pouches
add: *tilt headtilt quick emote
tweak: Changed engi-vend RCD prices
tweak: Atmospheric Technicians can now actually access engineering again
/:cl:

2020-11-26 23:48 UTC, Gandalf2k15 requested changes

2020-11-26 23:48 UTC, Gandalf2k15 commented on code/modules/jobs/job_types/atmospheric_technician.dm
> +	minimal_access = list(ACCESS_ENGINE, ACCESS_ENGINE_EQUIP, ACCESS_MAINT_TUNNELS, ACCESS_MECH_ENGINE, ACCESS_AUX_BASE,	// Skyrat edit: additional engineering access
```suggestion
	//minimal_access = list(ACCESS_ATMOSPHERICS, ACCESS_MAINT_TUNNELS, ACCESS_AUX_BASE, ACCESS_CONSTRUCTION, ACCESS_MECH_ENGINE, ACCESS_MINERAL_STOREROOM) - SKRYAT EDIT ORIGINAL

	minimal_access = list(ACCESS_ENGINE, ACCESS_ENGINE_EQUIP, ACCESS_MAINT_TUNNELS, ACCESS_MECH_ENGINE, ACCESS_AUX_BASE,	// Skyrat edit: additional engineering access
```

2020-11-27 07:49 UTC, Gandalf2k15 approved these changes

2020-11-27 07:49 UTC, merged

2020-11-28 22:12 UTC, Sethnov commented
Can you add construction bags to the vendor? like it did on the old main server, and being able to put them in backpacks, satchels, and duffel bags, as in rebase they can only fit on your belt slot.