CRUCIAL workplace safety equipment: Recolorable overalls
Skyrat-SS13/Skyrat-TG pull request #18690
Opened 2023-01-13 19:18 UTC by Paxilmaniac

## About The Pull Request

It's not really that clamplicated, quite shrimple actually, it just adds recolorable overalls as a suit item to the loadout.

## How This Contributes To The Skyrat Roleplay Experience

We have a DISTINCT lack of bitches in overalls, I need this fixed NOW.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://user-images.githubusercontent.com/82386923/212400934-7e9271bc-aac2-4250-b494-66c315922965.png)
  
</details>

## Changelog

:cl:
add: A set of greyscale overalls has been added to the loadout menu in the suits section
/:cl:

2023-01-13 19:21 UTC, Ebin-Halcyon requested changes
Making them an oversuit layers them over hands and boots.
Make some cutouts for the hands, adjust the layer priority to have boots layer over them if you want that. Otherwise you can just make them a uniform.

2023-01-13 19:56 UTC, PCPort commented
I personally support the "make it a uniform" idea because being able to wear jackets over the overalls would be funny and possibly cute.

2023-01-15 03:18 UTC, Ebin-Halcyon approved these changes

2023-01-15 13:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/suits/misc.dm
> +		to_chat(user, span_warning("You must be holding [src] in order to adjust it!"))
Why?

2023-01-16 01:07 UTC, Paxilmaniac commented on modular_skyrat/modules/customization/modules/clothing/suits/misc.dm
> +		to_chat(user, span_warning("You must be holding [src] in order to adjust it!"))
source: its what bandanas do

2023-01-16 14:19 UTC, tf-4 approved these changes

2023-01-16 14:19 UTC, merged