[SEMI-MODULAR] Rave Cube
Skyrat-SS13/Skyrat-TG pull request #18737
Opened 2023-01-15 07:25 UTC by lessthnthree

## About The Pull Request
We can't use the jukebox on our server because it brings it to its knees with our population. That doesn't mean the crew should be depraved of party lights!

The rave cube has coloured spotlights and sparkles, but no jukebox component.

## How This Contributes To The Skyrat Roleplay Experience
Party lighting without killing the server with a jukebox.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://user-images.githubusercontent.com/83487515/212528328-09d97d36-3e57-4f47-821b-04d7e3af8d7d.mp4

</details>

## Changelog

:cl: LT3
add: RAVE CUBE
/:cl:

2023-01-15 07:45 UTC, Zergspower commented
![](https://media.giphy.com/media/2dK0W3oUksQk0Xz8OK/giphy.gif)

2023-01-15 12:49 UTC, tf-4 requested changes
Wrote the suggestions on my phone but you get the idea

2023-01-15 12:49 UTC, tf-4 commented on modular_skyrat/modules/rave_cube/code/rave_cube.dm
> +	to_chat(user, span_notice("You [anchored ? null : "un"]lock the rave cube."))
```suggestion
	balloon_alert(user, "[anchored ? null : "un"]anchored"))
```

2023-01-15 12:49 UTC, tf-4 commented on modular_skyrat/modules/rave_cube/code/rave_cube.dm
> +		. += span_notice("<b>Alt+Click</b> to unlock the rave cube for travel.")
```suggestion
	. += span_notice("<b>Alt+Click</b> to [anchored ? null : "un"]anchor [src].") 
```

2023-01-15 12:49 UTC, tf-4 commented on modular_skyrat/modules/rave_cube/code/rave_cube.dm
> +	var/turf/cen = get_turf(src)
```suggestion
	var/turf/centre = get_turf(src)
```

2023-01-15 12:49 UTC, tf-4 commented on modular_skyrat/modules/rave_cube/code/rave_cube.dm
> +	visible_message(span_info("Rave cube is initialising... Please wait."))
Could have the cube speak instead for something a little more flavourful

2023-01-16 04:19 UTC, Nerev4r commented
It would be preferable to lock the goofy-ass dances like spinning around in the air upside down and such, behind a skillchip or perhaps the Freerunning quirk.

2023-01-16 12:22 UTC, OrionTheFox commented
Is this sprite just the blackbox but... taller and more colorful..?

2023-01-16 18:20 UTC, lessthnthree commented
Yes.

2023-01-17 02:07 UTC, lessthnthree commented
Turns out the long ass helicopter flipping and such was my mistake. I severely reduced the length for each of them.

2023-01-31 03:48 UTC, closed without merging