[Modular probably?][DRAFT] Pain Component & Health System [DRAFT]
Skyrat-SS13/Skyrat-TG pull request #18749
Opened 2023-01-15 23:42 UTC by nevimer

## About The Pull Request
**NOT DONE YET NOT EVEN CLOSE**
This PR serves as a draft for the pain and shock based modular health system I have been kinda sitting on the idea of for a while now. Currently, the code is very far from done, and all it does at the moment of opening this PR is give you a heart attack disease. 

## How This Contributes To The Skyrat Roleplay Experience

What if we moved away from raw damage numbers and made things like wounds matter more? 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 https://cdn.discordapp.com/attachments/610319137012580383/1053184379351990383/dreamseeker_uocAVuSNBh.mp4
</details>

## Changelog

:cl:
add: Added pain and shock based health system. 
/:cl:

2023-01-16 00:03 UTC, softcerv commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +	UnregisterSignal(parent, COMSIG_LIVING_LIFE)
```suggestion
	UnregisterSignal(parent, COMSIG_LIVING_LIFE)
	
```

2023-01-16 00:03 UTC, softcerv commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +	RegisterSignal(parent, COMSIG_LIVING_LIFE, .proc/pain_tick)
```suggestion
	RegisterSignal(parent, COMSIG_LIVING_LIFE, .proc/pain_tick)
	
```

2023-01-16 00:03 UTC, softcerv commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +		return COMPONENT_INCOMPATIBLE
```suggestion
		return COMPONENT_INCOMPATIBLE
		
```

2023-01-16 00:03 UTC, softcerv commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +	var/list/last_wounds = list()
```suggestion
	var/list/last_wounds = list()
	
```

2023-01-16 00:03 UTC, softcerv commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +#define PAIN "pain"
```suggestion
#define PAIN "pain"

```

2023-01-16 00:50 UTC, softcerv commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +#define MAGIC_PAIN_DIVISOR 10
could you write a comment or change the variable name to better explain how this works?

2023-01-17 08:37 UTC, YakumoChen commented
I still have nightmares of BobMed...

2023-01-18 03:37 UTC, MrMelbert reviewed
suggestion (from someone who's made their own pain system): 

don't make this a component, especially not in your code base
people will want to read pain values and stuff, I 100% guarantee it. 

you can do this hella modularly with just a datum.

2023-01-18 03:37 UTC, MrMelbert commented on modular_skyrat/master_files/code/modules/health/health_mods.dm
> +	var/mob/living/carbon/human/pain_haver
don't bother, just typecast

2023-01-19 04:37 UTC, nevimer commented
> I still have nightmares of BobMed...
> 
> Can you make like, some kind of design document for this?

https://hackmd.io/c1owWVxhRvyYn8qli0FABw

Written a year ago, pretty out of date with my goals.

2023-01-19 07:04 UTC, YakumoChen commented
> > I still have nightmares of BobMed...
> > Can you make like, some kind of design document for this?
> 
> https://hackmd.io/c1owWVxhRvyYn8qli0FABw
> 
> Written a year ago, pretty out of date with my goals.

can you update it then? A feature that replaces one of the core game mechanics should really have a design document attached so we know whats going on.

2023-01-20 04:34 UTC, Zonespace27 requested changes
To save you the pain (badum tssh) later, please update your design doc to your current goals in addition to being more detailed

2023-01-28 01:36 UTC, nevimer commented
Sorry GitHub actions bot I'm too busy hunting undocumented diffs

2023-01-29 04:47 UTC, nevimer commented
Zero chance of this happening, sorry folks.

2023-01-29 04:47 UTC, closed without merging