Meteor early warning system / Engineering override controls
Skyrat-SS13/Skyrat-TG pull request #18807
Opened 2023-01-18 20:57 UTC by lessthnthree

## About The Pull Request
Reintroduces an early warning system for the meteors random event. The station receives 7-9 minutes notice before the meteor wave is going to hit. This gives staff time to order meteor shields from cargo (if required) and set them up in anticipation, and overall the station is more prepared for the incoming wave. Engineering override is triggered shortly before the wave hits, so that engineers can get into areas they may have had problems due to access, as well for repairing damage afterwards.

The captain, heads, and AI now have greater control over the engineering override access system. It can now be toggled on/off on any alert level from the communications console or the keycard auth device, it's no longer automatically bound to orange alert. There may be gameplay reasons to turn on/off the access that may not warrant orange alert, and since orange alert is on par with blue security wise, if the station is on amber, red, or higher the captain (or heads via keycard auth) can override the system and turn the access on or off.

## How This Contributes To The Skyrat Roleplay Experience
- Oldbase had a meteor warning which was lost with TG, but for the pace of our server it's appropriate to give the crew time to repair for a meteor wave, since we're on the station for 3 hours+ per shift.
- The station currently has no control over the engineering override system, this gives them that power to control and use it as they see fit.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl: LT3
add: New! Meteor wave early warning system. Prepare those meteor shields
qol: Engineering override access can now be manually controlled at the communications console and keycard auth devices
/:cl:

2023-01-18 23:10 UTC, Zonespace27 requested changes

2023-01-18 23:10 UTC, Zonespace27 commented on code/game/machinery/computer/communications.dm
> +				data["canToggleEngineeringOverride"] = FALSE
SR edit comment

2023-01-18 23:10 UTC, Zonespace27 commented on code/game/machinery/computer/communications.dm
> +					data["canToggleEngineeringOverride"] = TRUE
ditto

2023-01-18 23:10 UTC, Zonespace27 commented on modular_skyrat/modules/engineering_override/code/engineering_override.dm
> +#define COMSIG_GLOB_FORCE_ENG_OVERRIDE "force_engineering_override"
signal folder

2023-01-18 23:10 UTC, Zonespace27 commented on modular_skyrat/modules/engineering_override/code/engineering_override.dm
> +		return
```suggestion
		return
		
```

2023-01-18 23:10 UTC, Zonespace27 commented on modular_skyrat/modules/engineering_override/code/engineering_override.dm
> +	return
this return does nothing

2023-01-18 23:10 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/CommunicationsConsole.js
>      canSendToSectors,
none of these changes are documented with SR edit comments

2023-01-18 23:10 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                    <Button
neither is this

2023-01-18 23:10 UTC, Zonespace27 commented on modular_skyrat/modules/meteor_warning/code/meteor_warning.dm
> +/datum/round_event/meteor_wave/proc/orange_alert(datum/round_event/mv)
Let the station figure out if it needs orange or not, remove this

2023-01-18 23:10 UTC, Zonespace27 commented on modular_skyrat/modules/meteor_warning/code/meteor_warning.dm
> +	start_when = rand(210,240)
time defines

2023-01-18 23:10 UTC, Zonespace27 commented on modular_skyrat/modules/meteor_warning/code/meteor_warning.dm
> +	start_when = rand(210,240)
```suggestion
	start_when = rand(210, 240)
```

2023-01-19 01:47 UTC, OrionTheFox commented
Two things:
- This should likely be two separate PRs
- 7-9 minutes feels like a long time, THOUGH considering you didn't change meteors to be directional I can understand it. Personally, if you'd be fine cutting it from your PR, I'd prefer to reopen my Directional Meteors/Early Warning port from oldbase, especially with TG actually having a directional framework now (I closed it while TG implemented that)

2023-01-19 01:56 UTC, lessthnthree commented
> Two things:
> 
> * This should likely be two separate PRs
> * 7-9 minutes feels like a long time, THOUGH considering you didn't change meteors to be directional I can understand it. Personally, if you'd be fine cutting it from your PR, I'd prefer to reopen my Directional Meteors/Early Warning port from oldbase, especially with TG actually having a directional framework now (I closed it while TG implemented that)

Originally the two were tied together functionally, but now that orange alert isn't being fired by the event it can be split. How far away is your directional PR?

2023-01-19 02:09 UTC, ghost commented
> 
> Originally the two were tied together functionally, but now that orange alert isn't being fired by the event it can be split. How far away is your directional PR?

Makes sense yeayea
Directional PR has been sitting dead in the water for a while, but seeing as TG added their own, it might be something you can even add to your own PR; I'll go comment on that one with how you'd likely do it, since you've already made it

2023-02-03 19:31 UTC, GoldenAlpharex requested changes
I haven't checked the sprites yet, and it's probably something that'll be mostly for @Ebin-Halcyon to give his approval to.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
> +				pre_light_color = light_color_security
There's no reason to have it as a variable here.
```suggestion
				pre_light_color = AIRLOCK_SECURITY_LIGHT_COLOR
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
> +	var/light_color_security = AIRLOCK_SECURITY_LIGHT_COLOR
Refer to my previous comment.
```suggestion
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
>  //SKYRAT EDIT END
While you're here, please remove the Skyrat Edit comments, it's literally a modular file.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/autoairlock.dm
> +/obj/machinery/door/airlock/allowed(mob/user)
Rename this file (and module) to `auto_airlock` please, it's not something that would go in one word.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/engineering_override.dm
> +	engineering_override_eligible = TRUE
I feel like these aren't areas we'd want Engineers strolling about actually.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/engineering_override.dm
> +/proc/toggle_eng_override()
Also, add documentation to this proc.
```suggestion

/proc/toggle_eng_override()
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/engineering_override.dm
> +		return
This also just feels like it's a lot of repetition of code that could be done in more concise way.
```suggestion

	GLOB.force_eng_override = FALSE
	minor_announce("Expanded engineering access has been revoked.", "Engineering Emergency")
	var/level = SSsecurity_level.get_current_level_as_number()
	SSblackbox.record_feedback("nested tally", "keycard_auths", 1, list("engineer override access", "disabled"))
	if(level == SEC_LEVEL_ORANGE)
		return

	SEND_GLOBAL_SIGNAL(COMSIG_GLOB_FORCE_ENG_OVERRIDE, FALSE)
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/engineering_override.dm
> +/obj/machinery/door/airlock/proc/force_eng_override(datum/source, status)
Document this proc please.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/security_override.dm
> +/proc/toggle_sec_override()
Document this proc please.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/security_override.dm
> +// Manual override for when it's not red alert.
Also for these it's `/// ` not just `// `

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/security_override.dm
> +		return
```suggestion

	GLOB.force_sec_override = FALSE
	minor_announce("Expanded security access has been disabled.", "Security Emergency")
	var/level = SSsecurity_level.get_current_level_as_number()
	SSblackbox.record_feedback("nested tally", "keycard_auths", 1, list("security override access", "disabled"))
	if(level >= SEC_LEVEL_RED)
		return

	SEND_GLOBAL_SIGNAL(COMSIG_GLOB_FORCE_SEC_OVERRIDE, FALSE)
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/code/security_override.dm
> +	if(!GLOB.force_sec_override)
You should probably change the value of this before the `if()` so it's less confusing.

2023-02-03 19:31 UTC, GoldenAlpharex commented on modular_skyrat/modules/autoairlock_override/readme.md
> +MODULE ID: AUTOAIRLOCK_OVERRIDE
```suggestion
MODULE ID: AUTO_AIRLOCK_OVERRIDE
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/CommunicationsConsole.js
> +    engineeringOverride, // SKYRAT EDIT - Engineering Override
Wouldn't you want to have the security override stuff here too?

2023-02-03 19:31 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/CommunicationsConsole.js
> +              icon="wrench" // SKYRAT EDIT
Leave this one as it is and put the wrench on the engineering one, that makes a lot more sense.
```suggestion
              icon="id-card-o"
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/CommunicationsConsole.js
> +              icon="id-card-o"
```suggestion
              icon=""wrench"
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/CommunicationsConsole.js
> +          {/* SKYRAT EDIT ADDITION START */}
```suggestion
          {/* SKYRAT EDIT ADDITION START - Engineering Override */}
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                    {/* SKYRAT EDIT ADDITION EMD */}
```suggestion
                    {/* SKYRAT EDIT ADDITION END */}
```

2023-02-03 19:31 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/KeycardAuth.js
> +                    {/* SKYRAT EDIT ADDITION START */}
```suggestion
                    {/* SKYRAT EDIT ADDITION START - Permit Pins */}
```

2023-02-11 12:01 UTC, OrionTheFox commented
The icon changes in this are a bit of a mess, several airlock states are changed, the external one is partially recolored but not fully in the animation, and lots of the extra stripes feel redundant and, moreover, aren't shown in the PR.

I recommend the manual engineering override stay its own PR for your own sake, you're kind of over-extending. The security access being a separate PR will make it easier to review code-wise, icon-wise, and for you to keep changes documented

2023-02-18 03:07 UTC, lessthnthree commented
Yeah I'll split it in two.

2023-02-27 02:11 UTC, closed without merging