LT3 Donator Items
Skyrat-SS13/Skyrat-TG pull request #18859
Opened 2023-01-21 22:02 UTC by lessthnthree

## About The Pull Request
For the stylish HoP, a short cut black jacket with silver trim, black v-neck with silver jeans, and some matching charcoal gloves.

The three items are ckey locked to LT3

## Proof of Testing

![dreamseeker_ztNHtKtZEw](https://user-images.githubusercontent.com/83487515/213888606-8d60dcc8-8075-44a1-9b7a-a2b2f931ed27.gif)

2023-01-21 22:42 UTC, tf-4 requested changes

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	desc = "A synthetic fabric jacket enhanced with a special alloy for some extra protection and style for those with a commanding presence."
Feels like a bit of a run on sentence, perhaps something like
```suggestion
	desc = "A jacket for those with a commanding presence. Made of synthetic fabric, it's interwoven with a special alloy that provides extra protection and style."
```

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/gloves/combat/skyy
```suggestion
/obj/item/clothing/gloves/skyy
```
No. Those are insulated.

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	armor_type = /datum/armor/armor_hos
This will need to be removed, or the item locked to the HoS job.

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	armor_type = /datum/armor/under_syndicate
```suggestion
```

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	desc = "A shining, silver denim enhanced with a special alloy for some extra protection and style for those with a commanding presence."
```suggestion
	desc = "A pair of jeans for those with a commanding presence. Made of shining, silver denim, it's interwoven with a special alloy that provides extra protection and style."
```

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	desc = "More for style than function, barely covers more than the palm of your hand."
```suggestion
	desc = "Valuing form over function, these gloves barely cover more than the palm of your hand."
```

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/under/skyy
```suggestion
/obj/item/clothing/under/pants/skyy
```

2023-01-21 22:42 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/suit/armor/skyy
```suggestion
/obj/item/clothing/suit/jacket/skyy
```

2023-01-21 23:31 UTC, lessthnthree commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	armor_type = /datum/armor/armor_hos
nah, I don't want a HoS jacket, that armor_type doesn't need to be there.

2023-01-21 23:34 UTC, lessthnthree commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/suit/armor/skyy
Yeah just the standard coat type the NTR/HoP get.

2023-01-22 00:26 UTC, tf-4 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/suit/armor/skyy
You're welcome to keep it with a lock to those roles. You cannot get a free armoured vest as any role.

2023-01-22 00:34 UTC, lessthnthree commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/suit/armor/skyy
Okay

2023-01-22 01:00 UTC, tf-4 approved these changes

2023-01-22 21:27 UTC, Zonespace27 submitted a review, later dismissed

2023-01-22 21:27 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	supports_variations_flags = CLOTHING_DIGITIGRADE_VARIATION_NO_NEW_ICON
order goes name-desc-iconstuff-everything else, so move this to the bottom

2023-01-22 21:27 UTC, Zonespace27 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	supports_variations_flags = CLOTHING_DIGITIGRADE_VARIATION_NO_NEW_ICON
ditto

2023-01-23 00:21 UTC, lessthnthree commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	supports_variations_flags = CLOTHING_DIGITIGRADE_VARIATION_NO_NEW_ICON
okay

2023-01-25 04:31 UTC, merged