[MANUAL MIRROR] Fixes toilet bongs, and fixes a serious bug in the crafting system
Skyrat-SS13/Skyrat-TG pull request #18921
Opened 2023-01-23 21:05 UTC by vinylspiders

## ORIGINAL PR: https://github.com/tgstation/tgstation/pull/72893

Merge this PR first: https://github.com/Skyrat-SS13/Skyrat-tg/pull/18919.

Fixes #18732

## Changelog

:cl:
fix: toilet bongs crafting recipes
fix: fixed bug with crafting that led to unexpected behavior; e.g. recipe requirements not being consumed, machinery being consumed when they shouldn't be
refactor: cleaned up some old code in the recipes file, added support for structures in recipes
/:cl:

2023-01-23 21:55 UTC, nevimer commented
For manual mirrors, cherry pick the tg commit to have no issues and retain the metadata.

2023-01-23 21:56 UTC, nevimer commented
Additionally, credit the tg author in the changelog.

2023-01-23 22:04 UTC, vinylspiders commented
> For manual mirrors, cherry pick the tg commit to have no issues and retain the metadata.

Ah I thought that's what I did. Did I cherry pick the wrong commit? 

I did `git cherry-pick <commit>` with commit being the one that got merged.

2023-01-23 22:07 UTC, nevimer commented
> > For manual mirrors, cherry pick the tg commit to have no issues and retain the metadata.
> 
> Ah I thought that's what I did. Did I cherry pick the wrong commit? 
> 
> I did `git cherry-pick <commit>` with commit being the one that got merged.

Disregard, I saw that you were both the author and commiter on the commit and came to the conclusion of  a mishap before I noticed that it was accurate to upstream

2023-01-23 22:08 UTC, GoldenAlpharex commented
> > For manual mirrors, cherry pick the tg commit to have no issues and retain the metadata.
> 
> Ah I thought that's what I did. Did I cherry pick the wrong commit?
> 
> I did `git cherry-pick <commit>` with commit being the one that got merged.

What I usually do it `git cherry-pick -m 1 <commit hash>`, I don't know the difference but it usually preserves the author, in my case.

2023-01-23 22:08 UTC, vinylspiders commented
> > > For manual mirrors, cherry pick the tg commit to have no issues and retain the metadata.
> > 
> > 
> > Ah I thought that's what I did. Did I cherry pick the wrong commit?
> > I did `git cherry-pick <commit>` with commit being the one that got merged.
> 
> Disregard, I saw that you were both the author and commiter on the commit and came to the conclusion of a mishap before I noticed that it was accurate to upstream

Oh whew, I was worried for a second.

2023-01-23 22:18 UTC, GoldenAlpharex commented
I'd recommend just re-doing this now that the dependency was merged, or you can fix the conflicts yourself, up to you.

2023-01-23 22:26 UTC, vinylspiders commented
> I'd recommend just re-doing this now that the dependency was merged, or you can fix the conflicts yourself, up to you.

Yeah. In hindsight redoing it would probably have been faster. Fixed the conflicts though, should be good now.

2023-01-23 22:41 UTC, GoldenAlpharex requested changes
These two will cause linting problems I'm pretty sure, related to a merge skew that happened yesterday.

2023-01-23 22:41 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/PersonalCrafting.tsx
> +				{item.structures &&
```suggestion
                {item.structures &&
```

2023-01-23 22:41 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/PersonalCrafting.tsx
> +				 {item.structures && (
```suggestion
                {item.structures && (
```

2023-01-23 22:42 UTC, GoldenAlpharex commented
The suggestion seems to be weird, basically make sure that it's got the same code as in <https://github.com/tgstation/tgstation/pull/72908/files#>

2023-01-23 22:46 UTC, nevimer commented
some times reapplying the cherry pick on top again and can resolve issues too. I'm not certain of your scenario, but it tends to work for me.

2023-01-23 23:03 UTC, vinylspiders commented
> The suggestion seems to be weird, basically make sure that it's got the same code as in https://github.com/tgstation/tgstation/pull/72908/files# for the personal crafting file.

Makes sense to me! done.

2023-01-23 23:03 UTC, vinylspiders commented
> some times reapplying the cherry pick on top again and can resolve issues too. I'm not certain of your scenario, but it tends to work for me.

I'll try that next time, thanks for the suggestion.

2023-01-26 21:45 UTC, GoldenAlpharex approved these changes
Good, thank you!

2023-01-26 21:45 UTC, merged