[PROJECT] Interdiction Lens
Skyrat-SS13/Skyrat-TG pull request #18928
Opened 2023-01-24 02:59 UTC by Zonespace27

## About The Pull Request
Adds the interdiction lens, a passive-ish method of defense.
It uses a high amount of power passively (and uses even more if it affects someone) to damage mechs and apply heavy slow to players in a radius. It takes 3-4 cogged APCs to be equivalent to one turned on interdiction lens. 
Two things I'm iffy about here:

- The range being 4 on the lens
- The slowdown + forced walk might be a bit too heavy
If you have feedback please let me know, but as with other PRs, the balance is still up in the air until there's enough to go off of

Also touches up APC charge removal to remove far more charge, as the engine could just about keep up with its power loss before. (Doesn't affect how much power is gained)

## How This Contributes To The Skyrat Roleplay Experience
Another feature off the checklist

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/41448081/214203642-ea67db46-aac8-4d35-ad8e-d09fcb756447.png)

</details>

2023-01-24 03:01 UTC, Stalkeros2 commented
Zonespace felinid confirmed.

2023-01-24 03:15 UTC, xiangfei-chen commented
:coggers:

2023-02-08 02:39 UTC, tf-4 requested changes

2023-02-08 02:39 UTC, tf-4 commented on modular_skyrat/modules/clock_cult/code/structures/interdiction_lens.dm
> +		to_chat(user, span_warning("[src] needs to be fastened to the floor!"))
```suggestion
		balloon_alert(user, "not fastened!")
```

2023-02-08 02:39 UTC, tf-4 commented on modular_skyrat/modules/clock_cult/code/structures/interdiction_lens.dm
> +	to_chat(user, span_brass("You flick the switch on [src], turning it [enabled ? "on" : "off"]!"))
```suggestion
	balloon_alert(user, "turned [enabled ? "on" : "off"]")
```

2023-02-08 02:39 UTC, tf-4 commented on modular_skyrat/modules/clock_cult/code/structures/interdiction_lens.dm
> +		to_chat(user, span_warning("[src] does not have enough power!"))
```suggestion
		balloon_alert(user, "not enough power!")
```

2023-02-16 12:31 UTC, tf-4 approved these changes

2023-02-16 12:31 UTC, merged