Syndicate maid outfit + the unatomic Teshari eyepatch fix
Skyrat-SS13/Skyrat-TG pull request #18927
Opened 2023-01-24 01:21 UTC by Ebin-Halcyon

## About The Pull Request

Tin, adds a Syndicate maid outfit, find it in the premium section of the Syndivend.

## How This Contributes To The Skyrat Roleplay Experience

It probably doesn't but atleast 3 people asked me for it. Also eyepatches being fixed for birds is nice, y'know.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![maid spin](https://user-images.githubusercontent.com/81479835/214193445-a94613a0-5903-4263-a3ca-e7c50ed7efe3.gif)

</details>

## Changelog

:cl:
imageadd: The Syndicate has gotten a shipment of Maid outfits.
/:cl:

2023-01-24 02:08 UTC, Stalkeros2 commented
Oh Jod.

2023-01-24 02:20 UTC, Stalkeros2 commented
It should really be a buyable bundle in the uplink, along with a lot of soap/cleaning supplies, soap grenades, and that soap spawner syndie bomb. ~~And a Kitchen Gun™️.~~

2023-01-24 02:26 UTC, Paxilmaniac commented
mfer down bad enough that he posted two comments in a row

2023-01-24 02:45 UTC, Jolly-66 commented on modular_skyrat/modules/mapping/code/wardrobes.dm
> +					/obj/item/clothing/head/maidheadband/syndicate = 5)
>Become codeowner for thos module
>Check notifs
>Question why I'm tagged
>mfw

2023-01-24 03:05 UTC, Ebin-Halcyon commented on modular_skyrat/modules/mapping/code/wardrobes.dm
> +					/obj/item/clothing/head/maidheadband/syndicate = 5)
Mogged.

2023-01-24 03:10 UTC, Ebin-Halcyon commented
> It should really be a buyable bundle in the uplink, along with a lot of soap/cleaning supplies, soap grenades, and that soap spawner syndie bomb. ~And a Kitchen Gun™️.~

idk if you wanna do that, be my guest.

2023-01-26 21:58 UTC, GoldenAlpharex requested changes
Other than that, thank you for fixing the eyepatch bug for Tesharis, I didn't know they had a file for that, otherwise I would've done it myself when fixing that one refactor.

2023-01-26 21:58 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
> +					/obj/item/clothing/head/maidheadband/syndicate = 5)
Try to reduce the indentation of this whole list too, just, in general, formatting it like all the other lists with a ton of entries usually are. Hit me up on Discord if you're not sure.
```suggestion
					/obj/item/clothing/gloves/combat = 3,
					/obj/item/clothing/under/syndicate/skyrat/maid = 5,
					/obj/item/clothing/gloves/combat/maid = 5,
					/obj/item/clothing/head/maidheadband/syndicate = 5,
	)
```

2023-01-27 17:11 UTC, GoldenAlpharex requested changes
Should be the last things that need changed.

2023-01-27 17:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
>  	products = list(/obj/item/clothing/under/syndicate/skyrat/tactical = 3,
```suggestion
	products = list(
		/obj/item/clothing/under/syndicate/skyrat/tactical = 3,
```

2023-01-27 17:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
> +		/obj/item/clothing/head/beret/sec/syndicate = 3)
```suggestion
		/obj/item/clothing/head/beret/sec/syndicate = 3,
	)
```

2023-01-27 17:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
>  	contraband = list(/obj/item/knife/combat = 1,
```suggestion
	contraband = list(
		/obj/item/knife/combat = 1,
```

2023-01-27 17:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
> +
```suggestion
		/obj/item/clothing/shoes/combat/coldres = 2,
	)
```

2023-01-27 17:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
>  	premium = list(/obj/item/knife/combat/survival = 1,
```suggestion
	premium = list(
		/obj/item/knife/combat/survival = 1,
```

2023-01-27 17:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/wardrobes.dm
> +		/obj/item/clothing/head/maidheadband/syndicate = 5)
```suggestion
		/obj/item/clothing/head/maidheadband/syndicate = 5,
	)
```

2023-01-27 17:11 UTC, GoldenAlpharex approved these changes
Should hopefully be good to go now!

2023-01-27 18:31 UTC, merged