[READY] Makes PDA Messaging Visible
Skyrat-SS13/Skyrat-TG pull request #18950
Opened 2023-01-25 20:10 UTC by Nerev4r

## About The Pull Request
Essentially, this plays a visible message (and a balloon alert) when someone sends a PDA message. A revival of https://github.com/Skyrat-SS13/Skyrat-tg/pull/10206 for the modern age. Think of it like how in some countries you can't mute the camera shutter noise on your phone.

## How This Contributes To The Skyrat Roleplay Experience
To quote my reformed orthodox rabbi Bill Clinton, 
CI policy allows for antagonists to immediately engage upon hearing any indication that you called for backup.

Clever players were shutting the ringer off on their PDAs and just PDAing security or coworkers whenever they ran into antags for backup so that the antagonist wouldn't know and wouldn't be able to act on them calling backup.

Also, this makes for better negative social interactions which creates finer RP. If you want to text your hoes on the side at a romantic dinner, you must be prepared to pay the price.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/12636964/214678380-eaf2f42e-92a2-4520-ac4d-9c9868de59d5.png)
![image](https://user-images.githubusercontent.com/12636964/214678400-b63cb636-6c1d-4470-a198-0855c422727a.png)
![image](https://user-images.githubusercontent.com/12636964/214678408-a6607522-2b90-4fe7-81b6-1f294ef339da.png)
  
</details>

## Changelog
:cl:
add: PDAs now let nearby people know you're messaging someone.
/:cl:

2023-01-25 20:37 UTC, Nerev4r commented
the extra 'you sent a message' has been cut

2023-01-27 19:41 UTC, RatFromTheJungle commented
add a gun to this it should have a gun make the pda a gun

2023-01-27 22:35 UTC, GoldenAlpharex requested changes

2023-01-27 22:35 UTC, GoldenAlpharex commented on code/modules/modular_computers/file_system/programs/ntmessenger.dm
> +	user.balloon_alert_to_viewers("sent a PDA message")
I feel like it should be one or the other, but not both.

Also the argument about it being basically like talking in a radio makes sense too, I feel like that's something that should have a range of like, one or two tiles tops.

2023-01-28 00:11 UTC, Nerev4r commented
![image](https://user-images.githubusercontent.com/12636964/215228656-ffddb3f8-fd31-4f8f-bcef-a514677a4907.png)

ok

2023-01-31 23:48 UTC, GoldenAlpharex approved these changes
I really don't like this as a player, but I can't help but to agree on a conceptual level, as much as I hate people knowing that I'm typing on my PDA.

2023-01-31 23:52 UTC, merged