[Modular] Ghost Role Bank Accounts + freighter/BDM loadout
Skyrat-SS13/Skyrat-TG pull request #18959
Opened 2023-01-26 18:26 UTC by Zenitheevee

## About The Pull Request

DS-2, Interdyne, Tarkon, Freighter, Hotel and Black Market Dealer now have Bank Accounts, including memories for the account ID should they lose it.

Black Market Dealer and Freighter have Loadout (And quirks for freighter) Enabled

## How This Contributes To The Skyrat Roleplay Experience

[I mean we had centralized banking for years.](https://www.youtube.com/watch?v=Y16P3I0doEg)

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![bankies](https://user-images.githubusercontent.com/28457065/214917716-8fe28ee6-754d-4c6a-9bf3-bf1e023142a9.PNG)
![bmdbank](https://user-images.githubusercontent.com/28457065/214917724-3fb7b6c5-5c54-484b-9757-6a7573617ce9.png)
![hotelbank](https://user-images.githubusercontent.com/28457065/214917729-bad9cda4-7f49-483a-a1ad-209b9c93af89.PNG)
![syndiebank](https://user-images.githubusercontent.com/28457065/214917735-b9b1825f-83be-4d8f-9d68-a4acb7fb2d2a.PNG)
![tarkonbank](https://user-images.githubusercontent.com/28457065/214917744-dff70802-7251-4479-abe2-1b009daf6e7f.png)
![image](https://user-images.githubusercontent.com/28457065/214918678-c3fc579c-8d2f-4dd4-a1fd-7ca3f59eb538.png)
![image](https://user-images.githubusercontent.com/28457065/214918753-71a05b3d-390d-4063-9bec-3472975579a2.png)

</details>

## Changelog

:cl:
qol: Most ghost roles now have bank accounts + their account ID in memories
qol: Freighter + BDM now have loadout enabled
/:cl:

2023-01-26 22:58 UTC, Zergspower commented
i blinked for a moment when i saw BDM wondering why they needed an account as an NPC lol

2023-01-26 23:38 UTC, Zenitheevee commented
Hold up for a minute on this, I'm throwing errors atm on playing in testing.

2023-01-26 23:40 UTC, Zenitheevee commented
> i blinked for a moment when i saw BDM wondering why they needed an account as an NPC lol

come on he's worked hard for all that money. Especially HIS line of work.

2023-01-27 00:14 UTC, Zergspower commented
(Though funny aside the CL should be fixed to BMD)

2023-01-27 19:52 UTC, Zenitheevee commented
Also something to keep in mind: This system (for applying bank account) Is going to get a bit of a rework when i eventually go into giving ghost roles actual job datums. 

Like, I'm not sure this is going to go as far as alternate ghost role names but the most ambitious i'm aiming is ghost role department banks

2023-01-27 23:24 UTC, GoldenAlpharex requested changes
Good change though.

2023-01-27 23:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/mob_spawns.dm
> +	handlebank(crewman)
For all of these, please just put a space before the `handlebank()` call please <3
```suggestion

	handlebank(crewman)
```

2023-01-27 23:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/mob_spawns.dm
> +	handlebank(crewman)
```suggestion

	handlebank(crewman)
```

2023-01-27 23:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/mob_spawns.dm
> +	handlebank(staff)
```suggestion

	handlebank(staff)
```

2023-01-27 23:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/mapping/code/mob_spawns.dm
> +	handlebank(syndicate)
```suggestion

	handlebank(syndicate)
```

2023-01-30 00:21 UTC, GoldenAlpharex approved these changes
Should be good to go, thank you!

2023-01-30 00:21 UTC, merged