[Modular] Multi_sprite Magazines can now load any ammo while any subtype in Ammo Workbench
Skyrat-SS13/Skyrat-TG pull request #19203
Opened 2023-02-07 05:31 UTC by Zenitheevee

## About The Pull Request

Multi_sprite Magazines, Such as the CMG and the R-C Makarov Magazines, Will now be able to load any ammo at the ammo workbench.
Why did i bother doing this?
Because the Dangerous Research ruin spawns with 3 R-C Makarov rubber mags, 1 hollow point mag, and 1 normal mag.
2/5 of the mags that spawn here are useless for space tiding and ghost roles. 
And like
You can just take a lethal mag and recolor it anyways, so there's no point to make it exclusive

While also a Balance cha- actually i'm not deeming it a balance change. It feels like a bug. So i'm calling this a fix.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

 https://user-images.githubusercontent.com/28457065/217156545-c0b25388-07e1-4c7e-bacc-71b2489fdbfa.mp4

https://user-images.githubusercontent.com/28457065/217156540-47e547b3-2a45-4ccf-b542-f24907c8650e.mp4

</details>

## Changelog

:cl:
fix: multi_sprite magazine subtypes are no longer hardlocked to their starting ammo type 
/:cl:

2023-02-07 20:06 UTC, YakumoChen commented
Technically this is intended behavior according to some admincoders, but given the workarounds exist and this behavior in general is extremely dumb, I'd say its a consistency issue.

2023-02-08 02:24 UTC, tf-4 commented
this is not intended behaviour don't let the jannies fool you

2023-02-08 02:25 UTC, tf-4 requested changes

2023-02-08 02:25 UTC, tf-4 commented on modular_skyrat/modules/sec_haul/code/guns/ammo.dm
> +	var/subtype_ammo = null	//ammo for it to spawn with if it is a subtype. Leave null otherwise.
```suggestion
	///Is magazine using an ammo subtype?
	var/is_subtype = FALSE
	///ammo for it to spawn with if it is a subtype. Leave null otherwise.
	var/subtype_ammo = null
```
autodoc

2023-02-08 07:08 UTC, Zenitheevee commented on modular_skyrat/modules/sec_haul/code/guns/ammo.dm
> +	var/subtype_ammo = null	//ammo for it to spawn with if it is a subtype. Leave null otherwise.
Oh, neat. I'll get this shipped soon.

2023-02-08 07:16 UTC, Zenitheevee commented
> Technically this is intended behavior according to some admincoders, but given the workarounds exist and this behavior in general is extremely dumb, I'd say its a consistency issue.

If its intended thats some wack-ass intentions.

2023-02-10 22:19 UTC, HWSensum commented
I guess i had same idea there (https://github.com/Skyrat-SS13/Skyrat-tg/pull/19271). My realisation is kinda diffirent and also have fix for nonlethal ammo for weak 9mm guns.

2023-02-12 03:32 UTC, Zenitheevee commented
The above linked PR seems rather more agree-able in terms of kinda just fixing the issue rather than bandaiding over it.

Will keep PR up but would prefer any Maintainers/Keyholders to look at the other PR.

2023-02-22 18:04 UTC, Zenitheevee commented
Alternate PR has been atomized and posted.
Closing.

2023-02-22 18:04 UTC, closed without merging