Oil shamblers no longer cause runtimes when killed
Skyrat-SS13/Skyrat-TG pull request #19249
Opened 2023-02-09 22:01 UTC by Shadow-Quill

## About The Pull Request

Fixes runtimes due to a race condition when oil shamblers died.
Also should fix failing CI.

2023-02-09 22:56 UTC, GoldenAlpharex requested changes
Don't forget to follow the pull request template!

2023-02-09 22:56 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/biohazard_blob_mobs.dm
>  	visible_message(span_warning("The [src] evaporates!"))
We don't need to have the `The` here, so might as well remove it now.
```suggestion
	visible_message(span_warning("[src] evaporates!"))
```

2023-02-09 23:15 UTC, Shadow-Quill commented
> Don't forget to follow the pull request template!

This doesn't touch the Skyrat Roleplay Experience, the proof that it works is that CI on my pr is passing, and the changes are not player/admin facing, so a changelog isn't required ^^

2023-02-09 23:33 UTC, GoldenAlpharex approved these changes
Even better fix, nice!

2023-02-10 00:08 UTC, tf-4 approved these changes

2023-02-10 01:37 UTC, lessthnthree approved these changes

2023-02-14 02:27 UTC, merged