[NON-MODULAR] SR specific escape menu options
Skyrat-SS13/Skyrat-TG pull request #19291
Opened 2023-02-11 23:58 UTC by lessthnthree

## About The Pull Request
Modifies the new escape menu to fit SR.

- Removes suicide
- Adds OPFOR
- Adds ghost on main menu
- Adds respawn

## How This Contributes To The Skyrat Roleplay Experience
Puts those features in a more accessible place.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/83487515/218286104-f2470565-ce0f-426f-9384-dc42476e4e3d.png)

</details>

## Changelog

:cl: LT3
code: Escape menu now has SR specific line items
/:cl:

2023-02-12 01:37 UTC, tf-4 commented
IMO this is a feature, so it falls under the freeze

2023-02-12 01:40 UTC, lessthnthree commented
Okay, I'll just reopen it later.

2023-02-12 01:40 UTC, tf-4 commented
I would be happy with an atomised removal of the suicide stuff tho

2023-02-12 21:50 UTC, lessthnthree commented
> I would be happy with an atomised removal of the suicide stuff tho

I already removed suicide first merge, so any changes to the menu we can roll into one after freeze

2023-03-10 02:48 UTC, tf-4 requested changes

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/escape_menu.dm
> +//			show_leave_body_page() //SKYRAT EDIT REMOVAL
```suggestion
		//if (PAGE_LEAVE_BODY) //SKYRAT EDIT REMOVAL
			//show_leave_body_page() //SKYRAT EDIT REMOVAL
```

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/escape_menu.dm
> +
modular file

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/home_page.dm
> +// SKYRAT EDIT ADDITION START
this isn't purely an addition

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/home_page.dm
> +//SKYRAT EDIT ADDITION END
just put this in a modular file

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/home_page.dm
> +	//SKYRAT EDIT ADDITION END
should be able to modularise this

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/home_page.dm
> +// SKYRAT ADDITION END
modularrrrrr

2023-03-10 02:48 UTC, tf-4 commented on code/modules/escape_menu/leave_body.dm
> -/datum/escape_menu/proc/show_leave_body_page()
dont delete this file

2023-03-10 02:49 UTC, Gandalf2k15 commented on code/modules/escape_menu/leave_body.dm
> -/datum/escape_menu/proc/show_leave_body_page()
^

2023-03-10 19:49 UTC, Gandalf2k15 commented on tgstation.dme
> -#include "code\modules\escape_menu\leave_body.dm"
make sure to tick this file

2023-03-10 20:05 UTC, lessthnthree commented on tgstation.dme
> -#include "code\modules\escape_menu\leave_body.dm"
Done

2023-03-14 01:05 UTC, Gandalf2k15 approved these changes

2023-03-14 01:05 UTC, merged