[TM ONLY] Reverts Sideplane, Makes the Game Playable
Skyrat-SS13/Skyrat-TG pull request #19308
Opened 2023-02-13 00:30 UTC by RimiNosha

## About The Pull Request
Anyone who's played since december knows that sideplane was a mistake in it's current state.

Let's send it to the shadow realm, at least until botany and items are fixed.

This is an upstream issue, and I have no control over it, before I get someone commenting that I should fix it. I also do not know how sideplane works at all.

## How This Contributes To The Skyrat Roleplay Experience

I'd like to pick up my fucking items, thanks.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/106692773/218346595-876a1f29-2dd5-40d8-bc36-b4b5cd8d716f.png)
![image](https://user-images.githubusercontent.com/106692773/218346600-aac05f03-cd12-4685-8802-8049ff6c8fee.png)
![image](https://user-images.githubusercontent.com/106692773/218346606-5e637d57-b37e-481f-82ba-0fce090bf020.png)

# OH LOOK, I CAN SEE MY FUCKING ITEM

Sadly the new starlight values used planes extensively, I'm not converting them.
![image](https://user-images.githubusercontent.com/106692773/218346673-0f603948-0018-4669-9c79-ea1a7f24876d.png)

</details>

## Changelog

No CL, cause the only way this gets merged is if we fork.

Reverts:
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/18070
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/18427
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/18587
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/18590 (partially, tram signs might look slightly wonky, in order to avoid map conflicts)
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/18879
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/18930
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/19059
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/19217
- https://github.com/Skyrat-SS13/Skyrat-tg/pull/19060

2023-02-13 00:33 UTC, Iamgoofball commented
botany isn't broken upstream, whatever issue you've got with botany down here is almost assuredly not the fault of SIDEMAP and is the fault of skyrat specific code bugs

2023-02-13 00:37 UTC, RimiNosha commented
https://github.com/tgstation/tgstation/issues/72765
https://github.com/tgstation/tgstation/issues/72569

2023-02-13 00:40 UTC, Iamgoofball commented
these are incredibly minor cosmetic issues, i assumed you meant they were completely unplayable given the fact you're reverting a complete refactor of the render stack

2023-02-13 00:45 UTC, GoldenAlpharex commented
> these are incredibly minor cosmetic issues, i assumed you meant they were completely unplayable given the fact you're reverting a complete refactor of the render stack

It's not really minor considering it's a refactor of the render stack that made it so items and overlays start flickering like crazy, and there's like only two or three people that understand enough of it to even be able to maybe figure out a potential fix.

The main frustration that comes from things like these is that they get merged before some of the very obvious bugs get fixed, and now we're left to deal with them for months on end.

2023-02-13 00:49 UTC, Iamgoofball commented
that's understandable and i wish we could get more progress done on this front, but please keep in mind that we functionally cannot provide effective troubleshooting on rendering bugs involving planes upstream at /tg/ if sidemap is shut off since we're operating on sidemap unless wallening explodes

2023-02-13 00:52 UTC, GoldenAlpharex commented
> that's understandable and i wish we could get more progress done on this front, but please keep in mind that we functionally cannot provide effective troubleshooting on rendering bugs involving planes upstream at /tg/ if sidemap is shut off since we're operating on sidemap unless wallening explodes

I'm well aware, but it's also why stuff like this should have been fixed as a priority after the sidemap was introduced, if not being a reason to wait before merging the sidemap PR to begin with.

I love potato but this kind of bug is disheartening to see and/or hear about every single day.

2023-02-14 01:04 UTC, GoldenAlpharex requested changes

2023-02-14 01:04 UTC, GoldenAlpharex commented on code/world.dm
> +	//map_format = SIDE_MAP
```suggestion
	//map_format = SIDE_MAP // SKYRAT EDIT - Waiting for it to be fixed and ready for production
```

2023-04-03 01:54 UTC, Gandalf2k15 commented
Removing this from TM as it seems to have been fixed.

2023-04-03 04:54 UTC, Gandalf2k15 commented
This has been fixed.

2023-04-20 23:46 UTC, GoldenAlpharex commented
It's, in fact, still not fixed, as far as we could tell, unfortunately. I also know we're likely not going to be the ones that will fix it ourselves, so I think this is still relevant.

2023-04-21 01:18 UTC, Gandalf2k15 commented
You dont need prs open to tm them

2023-04-21 01:18 UTC, closed without merging