[99% NONMODULAR] Adds It/Its Pronouns
Skyrat-SS13/Skyrat-TG pull request #19610
Opened 2023-03-01 23:21 UTC by Nerev4r

## About The Pull Request
A port from https://github.com/Artea-Station/Artea-Station-Server/pull/49 (hi Rimi!) which is a port from Orbstation (hi Lexi!). This, simply, adds it/its pronouns to select, and renames the options from "Male", "Female", and "Other" to "He/Him", "She/Her", and "They/Them". To quote VioletN, 'A character who uses he/him pronouns isn't necessarily "male", so the button shouldn't be labeled that.'

## How This Contributes To The Skyrat Roleplay Experience
Further gender expression is cool as fuck.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
![image](https://user-images.githubusercontent.com/12636964/222288214-01b659e5-38ff-42b2-9fd3-7053627a6ec9.png)
![image](https://user-images.githubusercontent.com/12636964/222288246-9ac13934-eb0f-4a3f-bbfd-c96eaea50f29.png)
</details>

## Changelog
:cl:
add: You can now select it/its pronouns in setup.
/:cl:

2023-03-01 23:29 UTC, RimiNosha reviewed
Also, hi!

2023-03-01 23:29 UTC, RimiNosha commented on tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
> +	handleRotate: () => void;
Install the prettier plugin for VSC and re-save, please

2023-03-01 23:56 UTC, Ebin-Halcyon commented
Friendly reminder from me, add an extra new line to your details tab so images show up like so:

![image](https://user-images.githubusercontent.com/81479835/222294034-9b76f818-490b-4eec-adc9-cf8c850c9799.png)

2023-03-02 01:00 UTC, GoldenAlpharex requested changes
As stated on the Discord, I'd much rather have a pronouns pins instead of a solution like this, that would only affect the examine text (and leave you with `they`/`them` everywhere else because BYOND macros moment), as this is both highly non-modular, and relatively restricted in its appeal.

If people want to show their pronouns, so be it, but I would rather have it be more accessible than just hard-coding another option.

2023-03-02 01:03 UTC, Nerev4r commented
> As stated on the Discord, I'd much rather have a pronouns pins instead of a solution like this, that would only affect the examine text (and leave you with `they`/`them` everywhere else because BYOND macros moment), as this is both highly non-modular, and relatively restricted in its appeal.
> 
> If people want to show their pronouns, so be it, but I would rather have it be more accessible than just hard-coding another option.

We'll send this upstream and I'll do pronoun pins after that.

2023-03-02 01:03 UTC, closed without merging