Show DNR state for dead crew on crew monitor [SEMI-MODULAR] [READY]
Skyrat-SS13/Skyrat-TG pull request #19629
Opened 2023-03-03 18:50 UTC by tmyqlfpir

## About The Pull Request

This PR adds a DNR state if a crew member is dead (and has suit sensors enabled).

## How This Contributes To The Skyrat Roleplay Experience

This is so medic personnel are able to make a choice to rescue a DNR body, or ignore them.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
I have tested this on a local server and confirm that the DNR state only appears if the crew member in question is dead. These are all the suit sensor states with both dead and dnr shown.

Suit Sensors Living (1)
![suit state 1 dead](https://user-images.githubusercontent.com/80724828/227066961-2a3ab285-cfbf-4a58-9378-db06ce332519.png)
![suit state 1 dnr](https://user-images.githubusercontent.com/80724828/227066969-468772b5-abb5-4665-9c5f-4609808f7168.png)

Suit Sensors Vitals (2)
![suit state 2 dead](https://user-images.githubusercontent.com/80724828/227066971-8f3b2af8-6c16-47c1-909c-f79325929b4b.png)
![suit state 2 dnr](https://user-images.githubusercontent.com/80724828/227066975-91bc3238-7f3b-4843-9e08-51f696c5c920.png)

Suit Sensors All (3)
![suit state 3 dead](https://user-images.githubusercontent.com/80724828/227066979-ab001577-808a-4328-a729-eb2b52c7c658.png)
![suit state 3 dnr](https://user-images.githubusercontent.com/80724828/227066982-16877318-d7d6-46fc-ba94-e387678fdc99.png)
</details>

## Changelog

:cl:Kffred
fix: morgue incorrectly showing revivable state for dnr body
add: show dnr state to crew monitor for dead crew members
/:cl:

2023-03-10 08:22 UTC, Zergspower commented
I made a completely modular SR version of the crewmonitor.js - please update that one instead as it's designed for both SR's healthpool and robotic players

2023-03-12 23:06 UTC, tmyqlfpir commented
> I made a completely modular SR version of the crewmonitor.js - please update that one instead which would also remove the incompliant tag.It's designed for both SR's healthpool and robotic players

The crew monitor js this PR is adjusting is `CrewConsoleSkyrat.js`, what is the other js interface should I be changing instead?

2023-03-12 23:18 UTC, Zergspower commented
weiiiird when i first looked at it - it was the other way around hah

2023-03-13 20:41 UTC, BlueMemesauce commented
maybe it can have a different icon instead of being text?

2023-03-13 20:48 UTC, Zergspower commented
Potentially yeah, @Zonespace27 would need to clarify what made it incompliant so you could make changes there too

2023-03-13 23:13 UTC, Zonespace27 requested changes
In the future please don't force-push commits, it nukes old history

2023-03-13 23:13 UTC, Zonespace27 commented on code/game/machinery/computer/crew.dm
> +		if (sensor_mode >= SENSOR_LIVING)
move this into the SR edit block on 260

2023-03-14 03:24 UTC, tmyqlfpir commented
> In the future please don't force-push commits, it nukes old history

Thanks for the tip, I'll remember to do so for future PRs.

2023-03-23 00:23 UTC, tmyqlfpir commented
The crew monitor will use the ban icon for unrevivable crew members as inspired by the tgstation PR linked above. Images of the crew monitor for every suit sensor state are shown in the first comment.

2023-03-23 01:44 UTC, Zergspower commented
if i remember how i'll post how to fix the centering for the position, if not i'll be doing a  pass through that file in the next couple of weeks for an unrelated task to changing things and can make the update then

2023-03-27 14:35 UTC, Zonespace27 commented
https://github.com/tgstation/tgstation/pull/74006

2023-03-29 23:22 UTC, Gandalf2k15 commented
> [tgstation/tgstation#74006](https://github.com/tgstation/tgstation/pull/74006)

![image](https://user-images.githubusercontent.com/9026500/228689401-fcb7d141-35ad-4a06-bf25-769c3c634483.png)

I actually agree with these changes, implement these

2023-04-01 08:03 UTC, closed without merging

2023-04-01 08:13 UTC, tmyqlfpir commented
> I actually agree with these changes, implement these

This is outside the scope of this PR, I simply wanted the crew monitor to display if a body can be recovered or not. If this is too OP it can be limited to positional tracking (max suit sensors) instead. Having an optional filter for the crew monitor would likely go unused, and would not solve the issue which is medic crew rescuing husked bodies.

And second, I do not know enough about DM language to implement such a feature, and will close instead. Thanks for reviewing this PR.

2023-04-02 04:41 UTC, BlueMemesauce commented
Even if you made it, it wouldn't matter much anyway as you can already disable a body's suit sensors by just taking off their jumpsuit. Why make a new feature for something that can already be done?

2023-04-08 06:24 UTC, tmyqlfpir commented
My main issue is seeing med staff repeatedly try to revive my DNR character because the morgue reports them as revivable, despite the DNR flag. It's an anti-frustration mechanic at best as I've seen other players spend 15+ minutes repairing my character's organs, only to have a DNR state when attempting to defib.

Also, it would be best if revivable state is only reported for tracking sensors given that someone being revivable is only useful if their location is known.

2023-04-19 05:30 UTC, BlueMemesauce commented
I think you could probably add the morgue mechanic. It's separate from the balance of the crew monitor

2023-04-24 00:04 UTC, tmyqlfpir commented
I agree - feel free to do that upstream. This has been overall frustrating for my first PR over a simple 14 LoC change.

2023-04-24 01:17 UTC, BlueMemesauce commented
The DNR thing seems to already be a thing. If there's a ghost in the body, the light on the morgue slab is green. If there's no ghost in the body, the light is red. If you're DNR, you can't reenter your body so it has to be red. 
Perhaps it's not like that for bodies blacklisted at the end of a revolution, but that would be an exceptionally rare scenario.

2023-04-25 10:31 UTC, tmyqlfpir commented
>If you're DNR, you can't reenter your body so it has to be red.

It's a bug actually, if you have the DNR trait but don't set your body as DNR you can still reenter as the trait and state appear to be two different things. This extra check for morgue objects addresses it much like how if suicided will show red.

2023-04-25 11:46 UTC, BlueMemesauce commented
How can you have the DNR trait and not be DNR? I think that's the bug that should befixed. 
By the way, TG has no DNR trait.

2023-04-25 19:43 UTC, tmyqlfpir commented
By setting your character with the DNR trait then dying, you will still be able to reenter your body. Examine text shows the character as still twitching despite DNR, and it doesn't really kick in unless you manually click DNR under ghost tab.

I know nothing of the internals of SS13 nor DM coding, but ideally the correct solution would be to check DNR trait on death, then apply DNR state to character automatically instead of requiring the player to manually click it afterwards so new medic players don't waste their time.

But given that the maintainers have not weighted in for over a month - this PR should be labeled DNR. I'm not going to follow up readdressing other issues after this, but feel free to.

2023-05-03 08:02 UTC, Zergspower commented
> By setting your character with the DNR trait then dying, you will still be able to reenter your body. Examine text shows the character as still twitching despite DNR, and it doesn't really kick in unless you manually click DNR under ghost tab.
> 
> I know nothing of the internals of SS13 nor DM coding, but ideally the correct solution would be to check DNR trait on death, then apply DNR state to character automatically instead of requiring the player to manually click it afterwards so new medic players don't waste their time.
> 
> But given that the maintainers have not weighted in for over a month - this PR should be labeled DNR. I'm not going to follow up readdressing other issues after this, but feel free to.

Been trying to reach out to you but cant seem to do that - by chance is your account still open here?

2023-05-18 11:37 UTC, tmyqlfpir commented
I am not interested in discussing this PR any further, requesting lock.

Edit: This PR has been eclipsed since by various PRs such as #23669, and is no longer relevant.