[PROJECT] Outpost of Cogs
Skyrat-SS13/Skyrat-TG pull request #19696
Opened 2023-03-06 16:25 UTC by Zonespace27

## About The Pull Request
Adds new functionality when a blood cultist is drained at a vitality sigil.

When the cultist dies from the vitality sigil, a special message will be broadcasted to all clock cultists. Shortly after, a portal will open up where the cultist died. Only clock cultists are able to enter the portal.

![image](https://user-images.githubusercontent.com/41448081/223169624-8d5e96f9-5e47-48a5-8bdb-6c3cce03f9d7.png)

Going through the portal leads you to the "Outpost of Cogs", a far cry from the holy city of Reebe itself. Five minutes after the portal has been open, a centcomm announcement will play as the portal shifts colors, allowing anyone to enter.

To leave the Outpost, there's a portal opposite where you entered, on the north side.

![image](https://user-images.githubusercontent.com/41448081/223170182-d3f87e66-5edf-447f-a3ba-a7bdedab9ff3.png)

![image](https://user-images.githubusercontent.com/41448081/223170252-36e83ecd-ea04-427d-9544-79ba06fda54d.png)

Original map by dawson

## How This Contributes To The Skyrat Roleplay Experience
Adds depth to the clock cult vs blood cult interaction

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
See above

</details>

2023-03-07 00:55 UTC, MrMelbert commented on modular_skyrat/modules/clock_cult/code/outpost_of_cogs.dm
> +	GLOB.reebe_began_spawning = TRUE
Should really just be a static var if you don't use the global scope anywhere else

2023-03-07 00:55 UTC, MrMelbert commented on modular_skyrat/modules/clock_cult/code/outpost_of_cogs.dm
> +	sleep(2 SECONDS)
Sure are a lot of sleeps without sanity checks here...

2023-03-07 02:39 UTC, Zonespace27 commented on modular_skyrat/modules/clock_cult/code/outpost_of_cogs.dm
> +	GLOB.reebe_began_spawning = TRUE
Done

2023-03-07 02:39 UTC, Zonespace27 commented on modular_skyrat/modules/clock_cult/code/outpost_of_cogs.dm
> +	sleep(2 SECONDS)
Fixed

2023-03-09 21:49 UTC, Jolly-66 requested changes
Quick things to note.

<details>
<summary> Map review </summary>

I will strangle you. We HAVE bronze tables in code.
Don't like them? Honestly, not my concern or problem.

![image](https://user-images.githubusercontent.com/70232195/224167670-46bfecd2-cbea-49b3-8d4e-fa99ceffa203.png)

I also never really played much with Clockies, but the ruin? Area? Whatever, could use more environmental fluff. It feels empty.

![image](https://user-images.githubusercontent.com/70232195/224167892-a446009a-5642-4951-b0b4-045e65937961.png)


<details>

2023-03-10 10:00 UTC, Jolly-66 approved these changes
Map looks better.

Although, could use dirt cleanables for the more "old" vibe but I won't hold this PR for not having that.

2023-03-10 23:08 UTC, Zonespace27 commented
Dirtied up the place a bit, added some cult runes

2023-03-13 00:10 UTC, Paxilmaniac commented on modular_skyrat/modules/clock_cult/code/turf.dm
> +	desc = "A white, emptyw void, quite unlike anything you've seen before."
emptyw

2023-03-13 14:55 UTC, Zonespace27 commented on modular_skyrat/modules/clock_cult/code/turf.dm
> +	desc = "A white, emptyw void, quite unlike anything you've seen before."
```suggestion
	desc = "A white, empty void, quite unlike anything you've seen before."
```

2023-03-13 14:56 UTC, Zonespace27 commented on modular_skyrat/modules/clock_cult/code/turf.dm
> +	desc = "A white, emptyw void, quite unlike anything you've seen before."
Emptyw (fixed)

2023-03-14 01:14 UTC, Paxilmaniac approved these changes
looks good to me

2023-03-14 01:14 UTC, merged