[MODULAR] Cleans up the code for adult furniture.
Skyrat-SS13/Skyrat-TG pull request #19731
Opened 2023-03-08 22:45 UTC by softcerv

## About The Pull Request
This PR does a sweep through the adult furniture file, bringing the code closer to our standards. Aside from code improvements, the adult furniture can now be wrenched and unwrenched by wrench items that aren't the wrench, and unbuckling will only occur once the do_after time for the x-stand has completed.

## How This Contributes To The Skyrat Roleplay Experience
Paying off the technical debt from the organic interface update is good.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://user-images.githubusercontent.com/68373373/223867749-32a59042-0456-46a5-aeb4-b07d61da8f04.png)

I have tested this, but I do not think it would be wise to post pictures of my testing here.
</details>

## Changelog

:cl:
fix: the furniture added by the organic interface update can now be constructed by any wrench tool.
fix: unbuckling a mob from the X-Stand now only unbuckles after the do-after has completed.
code: cleans up the code for the organic interface furniture. 
/:cl:

2023-03-08 23:17 UTC, Zonespace27 requested changes

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	assembled_bed.loc = loc
forcemove

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	created_kit.loc = loc
forcemove

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	to_chat(user, span_notice("You begin unfastening the frame of bdsm bed and deflating the latex pillows..."))
use [src] instead of "bdsm bed"

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	var/mob/living/affected_mob = locate() in src.loc
is there a better way to do this?

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	if(stand_state == "close")
defines

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	to_chat(user, span_notice("You assemble the x-stand."))
[src] instead of x-stand

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	to_chat(user, span_notice("You disassemble the x-stand."))
ditto

2023-03-08 23:17 UTC, Zonespace27 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +	to_chat(user, span_notice("You begin unfastening the frame of x-stand..."))
ditto

2023-03-10 20:03 UTC, Gandalf2k15 approved these changes

2023-03-10 20:03 UTC, merged