[MODULAR] Poem of Communal Souls NIFSoft
Skyrat-SS13/Skyrat-TG pull request #19884
Opened 2023-03-15 07:31 UTC by softcerv

## About The Pull Request
Adds in the Poem of Communal Souls NIFSoft, a NIFSoft that comes preinstalled with all NIFs. The Poem of Communal Souls NIFSoft allows the user to send and receive and send virtual notes to any nearby NIF users that they may happen to cross that have the NIFSoft installed.

## How This Contributes To The Skyrat Roleplay Experience
This provides a good way for people that might not otherwise talk to each other to get to know a little bit more about each other, which in turn, could lead to more roleplay.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/68373373/215004270-590cb9bd-f4e8-42fc-aabf-59485cd72b95.png)

![image](https://user-images.githubusercontent.com/68373373/215004312-596e8f8c-6481-4b40-88d4-66f4bbaebc0d.png)

I will upload more images soon
</details>

## Changelog

:cl:
add: Adds in the Poem of Communal Souls NIFSoft, see ((https://github.com/Skyrat-SS13/Skyrat-tg/pull/18971)) for more details
/:cl:

2023-03-15 07:33 UTC, softcerv commented
Golden gave me permission to reopen this as a new PR.

2023-03-16 04:30 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsofts/soul_poem.dm
> +/datum/nifsoft/soul_poem/New()
Destroy(), not New()

2023-03-20 22:14 UTC, Zonespace27 requested changes

2023-03-20 22:14 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsofts/soul_poem.dm
> +	data["messages"] = list()
`data["messages"] = message_list` ?

2023-03-23 22:05 UTC, Zonespace27 approved these changes

2023-03-23 22:05 UTC, merged