Armor of the Imperiya : Giving some real life to the NRI surplus armor
Skyrat-SS13/Skyrat-TG pull request #19880
Opened 2023-03-15 04:24 UTC by Paxilmaniac

## About The Pull Request

![image](https://user-images.githubusercontent.com/82386923/225205179-20df1c05-ca8d-447a-aa94-87f5006b4157.png)

(The colors and looks in this image are not final, but take a peek anyways :3)

Today on how I learned to stop hating and start going "this could be cooler". (Currently a work in progress) Resprite and rework of the NRI surplus armor you can get from cargo.

So, what's new?

Aside from the updated looks, there's a bit more of a 'surplus' flair to the armor now. The current plans are that nri armor gotten through the imperial surplus crate will come as random variations of coloring and paint scheme, to give that feel of literally ordering whatever surplus stuff the NRI had on offer. Aside from just different colors, there are also smaller variations! Some helmets might come missing their glass visor, or their chin strap... And the vests might come missing some of their extra plates!

## How This Contributes To The Skyrat Roleplay Experience

It was a really funny idea that turned into something kinda cool actually. I think we could be doing something really funny and unique with ordering surplus NRI stuff, and overall I think the new sprites are more befitting of surplus armor that came from a border war happening in the interstellar age, don't you think?

## Proof of Testing

It's all up above baby, more to come as I finish more of this.

## Changelog

:cl:
imageadd: The NRI surplus armor is getting a pretty big resprite and reflavoring, ordering surplus armor in the surplus crates might give you a bunch of mismatched colors you know!
/:cl:

2023-03-15 04:32 UTC, Stalkeros2 commented
Wooo I won't have to commission a spriter now thank you so much unironically.

2023-03-15 04:36 UTC, Paxilmaniac commented on modular_skyrat/modules/novaya_ert/code/surplus_armor.dm
> +	var/static/list/extra_plates_yeah_or_nah = list(
shoutout to the variable of all time

2023-03-15 16:47 UTC, HoodMilk commented
Power Ranger Sec

It looks real nice though

2023-03-15 23:24 UTC, Zonespace27 requested changes

2023-03-15 23:24 UTC, Zonespace27 commented on modular_skyrat/modules/cargo/code/packs.dm
> +/datum/supply_pack/security/armory/russian/fill(obj/structure/closet/crate/C)
one letter var

2023-03-15 23:24 UTC, Zonespace27 commented on modular_skyrat/modules/novaya_ert/code/surplus_armor.dm
> +		"both" = 5,
defines

2023-03-15 23:24 UTC, Zonespace27 commented on modular_skyrat/modules/novaya_ert/code/surplus_armor.dm
> +	if(pick_weight(extra_plates_yeah_or_nah) == "has_da_plates")
can't this just be a prob(33) instead of needing the static list and all that

2023-03-15 23:29 UTC, Paxilmaniac commented on modular_skyrat/modules/cargo/code/packs.dm
> +/datum/supply_pack/security/armory/russian/fill(obj/structure/closet/crate/C)
i love copy and pasting cargo code :)

2023-03-16 01:12 UTC, Paxilmaniac commented on modular_skyrat/modules/novaya_ert/code/surplus_armor.dm
> +	var/static/list/extra_plates_yeah_or_nah = list(
there is no more variable of all time

2023-03-16 04:18 UTC, Ebin-Halcyon approved these changes
Looks fine.

2023-03-16 04:29 UTC, Zonespace27 approved these changes
lgtm

2023-03-16 04:29 UTC, merged

2023-03-20 15:20 UTC, masline147 commented
Now it is like bulletpruf armor, but it is worse. Whoooooooo, here's the update. Why didn't you say that this is how the protection of this armor will fall? She's useless now