Removes meat subtype from sheetifier
Skyrat-SS13/Skyrat-TG pull request #19890
Opened 2023-03-15 18:57 UTC by lessthnthree

## About The Pull Request

Removes meat subtype from the list of items the sheetifier accepts.

## How This Contributes To The Skyrat Roleplay Experience

You're not supposed to be able to do that on SR.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://user-images.githubusercontent.com/83487515/225414521-744ecc55-7aa9-4cfd-a538-20aada068091.png)

</details>

## Changelog

:cl: LT3
code: Sheetifier no longer accepts meat products
/:cl:

2023-03-16 14:06 UTC, tf-4 requested changes
not really any reason to move this whole proc to a new file, just comment out the addcomponent and add a new, modified one with a `//skyrat edit` comment.

2023-03-16 17:07 UTC, lessthnthree commented
> not really any reason to move this whole proc to a new file, just comment out the addcomponent and add a new, modified one with a `//skyrat edit` comment.
Okay

2023-03-16 17:11 UTC, tf-4 commented on code/game/machinery/sheetifier.dm
> +	AddComponent(/datum/component/material_container, list(/datum/material/hauntium), MINERAL_MATERIAL_AMOUNT * MAX_STACK_SIZE * 2, MATCONTAINER_EXAMINE|BREAKDOWN_FLAGS_SHEETIFIER, /datum/material/haunt
```suggestion
	AddComponent(/datum/component/material_container, list(/datum/material/hauntium), MINERAL_MATERIAL_AMOUNT * MAX_STACK_SIZE * 2, MATCONTAINER_EXAMINE|BREAKDOWN_FLAGS_SHEETIFIER, /datum/material/hauntium, list(/obj/item/photo), null, CALLBACK(src, PROC_REF(CanInsertMaterials)), CALLBACK(src, PROC_REF(AfterInsertMaterials))) // SKYRAT EDIT CHANGE - REMOVES MEAT FROM SHEETIFIER
```

2023-03-17 04:45 UTC, Iamgoofball commented
>You're not supposed to be able to do that on SR.

Why?

2023-03-18 01:28 UTC, tf-4 approved these changes
restoring an older edit that got overwritten

2023-03-18 01:57 UTC, merged

2023-03-18 05:55 UTC, Iamgoofball commented
I know that, but like, why?