[MODULAR] NIF Rewards Points
Skyrat-SS13/Skyrat-TG pull request #19900
Opened 2023-03-16 02:46 UTC by softcerv

## About The Pull Request
Adds rewards points to NIFs, a system that aims to make rebuying NIFSofts every shift less of a pain. 

When buying an eligible NIFSoft from the NIFSoft catalog, a fraction of the buy price will be reimbursed as reward points, these rewards points can be used to purchase additional NIFSofts in place of credits. These rewards points carry between rounds.

The default conversion rate is 50% of the NIFSofts cost. Additionally, any NIFSofts installed from disks do not give rewards points.

## How This Contributes To The Skyrat Roleplay Experience
Buying NIFSofts each round is a pain, especially with the more expensive NIFSofts like Hivemind. This should hopefully make that cycle less of a pain.

## Proof of Testing

I will soon.

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: added reward points to NIFs, an alternative currency given from buying NIFSofts that can be used to buy more NIFSofts.
/:cl:

2023-03-16 02:47 UTC, softcerv commented
going to keep this on a draft while I fix weakrefs

2023-03-16 04:01 UTC, Zonespace27 requested changes
Make it clear that these are cross-round; currently there's no indication as such

2023-03-16 04:01 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsoft_catalog.dm
> +	var/obj/item/organ/internal/cyberimp/brain/nif/buyer_nif = target_nif
```suggestion
	var/obj/item/organ/internal/cyberimp/brain/nif/buyer_nif = target_nif.resolve()
```

2023-03-16 04:01 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsoft_catalog.dm
> +		target_nif = user_nif
```suggestion
		target_nif = weakref(user_nif)
```
I *think* that's the syntax?

2023-03-16 04:01 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsoft_catalog.dm
> +			var/obj/item/organ/internal/cyberimp/brain/nif/buyer_nif = target_nif
```suggestion
			var/obj/item/organ/internal/cyberimp/brain/nif/buyer_nif = target_nif.resolve()
```

2023-03-16 04:01 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsofts.dm
> +	/// How much of the NIFSoft's purchase price is payed out as reward points, if any?
```suggestion
	/// How much of the NIFSoft's purchase price is paid out as reward points, if any?
```

2023-03-17 01:31 UTC, YakumoChen commented
What's the point of giving some of these a price beyond "roundstart buyable" if you're going to add a system that makes them feasibly roundstart buyable?

2023-03-17 01:32 UTC, YakumoChen commented
Are points used in the purchase or is it just a flat scaling discount with purchases?

2023-03-17 01:34 UTC, YakumoChen commented
Is the 50% conversion for gaining points or spending them? Are they 1:1 with credits?

2023-03-17 01:36 UTC, YakumoChen commented
If you buy using points does the catalogue still try and give you points for the purchase? It should be made clear only credit purchases reward points.

2023-03-17 02:01 UTC, softcerv commented
> What's the point of giving some of these a price beyond "roundstart buyable" if you're going to add a system that makes them feasibly roundstart buyable?

This is only 50% of the money that you spend. You would be able to buy the same NIFSoft with the points roundstart once every three rounds assuming you bought the same NIFSoft the previous two rounds. The price is still important here, this just makes it somewhat less of an issue.

> Are points used in the purchase or is it just a flat scaling discount with purchases?

As shown by the screenshots I posted under the proof of testing section, they are an alternate way to pay.

> If you buy using points does the catalogue still try and give you points for the purchase? It should be made clear only credit purchases reward points.

No.

Next time it would help if you posted all of these as one single comment.

2023-03-17 02:47 UTC, YakumoChen commented
Is this exploitable in any way? If I came across 20,000 credits and bought and deleted NIF softs until I had 10,000 points, I'd be set for weeks.

Since this is persistent, there should probably be a pretty low cap on points to prevent abuse.

2023-03-17 03:49 UTC, softcerv commented
> Is this exploitable in any way? If I came across 20,000 credits and bought and deleted NIF softs until I had 10,000 points, I'd be set for weeks.
> 
> Since this is persistent, there should probably be a pretty low cap on points to prevent abuse and encourage people to use the points. Something like 2000.

You would need to repeatedly uninstall and install NIFSofts for a mind numbing amount of time to do that. I am honestly not sure of how real of an issue this is going to be.

2023-03-17 03:54 UTC, YakumoChen commented
Mind numbing, but better safe than sorry. If someone is hitting the cap and not spending the points, they don't really have a reason to complain

2023-04-03 01:11 UTC, Gandalf2k15 approved these changes

2023-04-03 01:11 UTC, merged