[MODULAR, PROBABLY-ISH] fixes funny grab interactions (headslams/suplexes/dislocations)
Skyrat-SS13/Skyrat-TG pull request #19960
Opened 2023-03-18 02:22 UTC by Hatterhat

## About The Pull Request
fixes funny grab interactions

puts all grab interactions on RMB, pretty much, keeping LMBs free for kicking people in the face or whatever

## How This Contributes To The Skyrat Roleplay Experience
i love hurting people

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/31829017/226078124-e1509d0d-49c2-4c37-b5cf-8d72427a2685.png)

</details>

## Changelog

:cl:
fix: Grab interactions (slamming heads into floors, suplexes(??), dislocations) are fixed and are all now on RMB when aggressive grabbing (or above) someone.
/:cl:

2023-03-18 02:29 UTC, PCPort commented
SPEEDMERGE

2023-03-18 15:12 UTC, Zonespace27 requested changes
Few small nits, thanks for fixing this!

2023-03-18 15:12 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +/datum/species/proc/try_headslam(mob/living/carbon/human/user, mob/living/carbon/human/target, obj/item/bodypart/affecting)
codedoc

2023-03-18 15:12 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +		return
return does nothing

2023-03-18 15:12 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +	if(do_after(user, time_doing, target))
early return

2023-03-18 15:12 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +		target.visible_message(span_danger("[user.name] holds [target.name]'s head tightly..."), ignored_mobs=user)
`.name` is implicit when doing [ref to atom]

2023-03-18 15:12 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +		target.visible_message(span_danger("[user.name] holds [target.name]'s head tightly..."), ignored_mobs=user)
```suggestion
		target.visible_message(span_danger("[user.name] holds [target.name]'s head tightly..."), ignored_mobs = user)
```

2023-03-18 15:12 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +			span_userdanger("You struggle as [user.name] holds your head and tries to overpower you!"), ignored_mobs=user)
```suggestion
			span_userdanger("You struggle as [user.name] holds your head and tries to overpower you!"), ignored_mobs = user)
```

2023-03-19 03:46 UTC, Zonespace27 commented on code/__DEFINES/~skyrat_defines/combat.dm
> +		span_userdanger("[user.name] slams your head against the floor!"), ignored_mobs=user)
```suggestion
		span_userdanger("[user.name] slams your head against the floor!"), ignored_mobs = user)
```

2023-03-19 03:50 UTC, Zonespace27 approved these changes

2023-03-19 03:58 UTC, merged