[MODULAR] Blueshield minor equipment changes and refactoring
Skyrat-SS13/Skyrat-TG pull request #20110
Opened 2023-03-27 17:52 UTC by Gyrandola

## About The Pull Request

This PR is a mini-rearrangement of Blueshield equipment, with the only actual addition being the unused Blueshield medkit (I say unused but you could actually only find it on Void Raptor) and comes together with a basic refactoring.

I also removed a bunch of duplicate items: 
-the crew pinpointer in the locker (now found in the medkit)
-the extra baton the Blueshield spawned with (already present in the secbelt)
-the medkit and empty guncase that already spawned on Void Raptor. 

The briefcase in the locker has also been replaced with a secure briefcase (because why not).

## How This Contributes To The Skyrat Roleplay Experience

Gives the Blueshield a very barebones medkit that could potentially save theirs or a head of staff's life if used in the right situation, without really increasing their threat level/firepower and keeping things balanced. It also gives some consistency to the Blueshield job equipment across all our maps.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![Screenshot 2023-03-27 190619](https://user-images.githubusercontent.com/62253058/228023705-152208e0-bdfb-4b30-9e9f-941e5afa525d.png)
_Content of the medkit (unchanged but for reference)._

![Screenshot 2023-03-27 190528](https://user-images.githubusercontent.com/62253058/228023978-ba7f1f4b-b142-4b60-9a9e-500096260642.png)
_Content of the Blueshield locker._

</details>

## Changelog

:cl: Gyran
add: Re-added the unused combat medkit to the Blueshield locker and changed the briefcase to a secure one
del: Removed some duplicate items from Void Raptor so the Blueshield doesn't have 2 crew pinpointers
refactor: refactored Blueshield code
/:cl:

2023-03-30 21:31 UTC, Zonespace27 requested changes

2023-03-30 21:31 UTC, Zonespace27 commented on modular_skyrat/modules/blueshield/code/blueshield.dm
> +		/obj/item/storage/box/gunset/blueshield = 1,)
```suggestion
		/obj/item/storage/box/gunset/blueshield = 1,
	)
```

2023-03-30 21:46 UTC, Jolly-66 approved these changes
Yeah okay Void Raptor is fine its just moving into the locker for real.

2023-04-01 20:47 UTC, Gandalf2k15 approved these changes

2023-04-01 20:47 UTC, merged