[MODULAR][REFACTOR] Refactors creature fluid extraction apparatus
Skyrat-SS13/Skyrat-TG pull request #20279
Opened 2023-04-02 22:41 UTC by softcerv

## About The Pull Request
This PR refactors the creature fluid extraction apparatus.

## How This Contributes To The Skyrat Roleplay Experience
Less technical debt is beneficial to our server.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

I will when I undraft  

</details>

## Changelog

:cl:
refactor: refactors the milking machine
/:cl:

2023-04-06 01:30 UTC, tf-4 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/milking_machine.dm
> +	var/obj/item/organ/external/genital/vagina/current_vagina = null
deal with this on destroy

2023-04-06 01:43 UTC, softcerv commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/milking_machine.dm
> +	var/obj/item/organ/external/genital/vagina/current_vagina = null
They have been dealt with.

2023-04-14 13:37 UTC, tf-4 requested changes

2023-04-14 13:37 UTC, tf-4 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/milking_machine.dm
> -	return
![huh](https://user-images.githubusercontent.com/8881105/232057730-c41995cc-7f6f-4690-a12b-2deea879f7e8.png)

2023-04-14 13:37 UTC, tf-4 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/milking_machine.dm
> +
could do something like
```
if(beaker && new_beaker)
	try_put_in_hand(beaker, user)
	beaker = new_beaker
	to_chat(user, span_notice("You remove the existing beaker and put in a new one in one fluid motion! What a pro.")
	return TRUE
```
rather than having two `to_chat`s

2023-04-14 13:37 UTC, tf-4 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/milking_machine.dm
>  /obj/structure/chair/milking_machine/proc/adjust_item_drop_location(atom/movable/AM)
AM bad

2023-04-14 22:55 UTC, Gandalf2k15 approved these changes

2023-04-14 22:55 UTC, merged