Gubman II Part 2 - Sniper Rifles & Co.
Skyrat-SS13/Skyrat-TG pull request #2028
Opened 2020-12-03 16:37 UTC by Investigator77

## About The Pull Request

This is part 2 of Gubman II, it contains some new content and remakes sniper rifles visually (audio too). Also tweaks and rebalances some stuff

## Why It's Good For The Game

More stuff to match the aesthetic overhaul as well as variety.

## Changelog
:cl: Investigator77
tweak: "Sniper Rifle" renamed to "AUS-107 anti-materiel rifle"
tweak: "Syndicate Sniper Rifle" renamed to "'Caracal' anti-materiel rifle"
tweak: "NT-ARG 'Boarder'" renamed to "ARG-63 infantry rifle"
add: Added "SA-107 anti-materiel rifle"
add: Added "MCRS-5B combat rifle", for SolFed.
balance: Syndicate Sniper Rifle now has less recoil and half the firing delay of a normal sniper rifle.
soundadd: New sniper rifle sound
soundadd: New suppressed sniper rifle sound
/:cl:

2020-12-03 16:38 UTC, Investigator77 commented
Yes the fact that the new syndicate sniper is nicknamed "Caracal" is because the real life counterpart of the sprite is the GM6 "Lynx"

2020-12-03 16:40 UTC, Investigator77 commented
wait i fucked up

2020-12-03 16:46 UTC, Investigator77 commented
I BEG YOU

2020-12-03 17:13 UTC, Gandalf2k15 commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
> +/obj/item/gun/ballistic/automatic/sniper_rifle/syndicate
```suggestion

/obj/item/gun/ballistic/automatic/sniper_rifle/syndicate
```

2020-12-03 17:14 UTC, Gandalf2k15 commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
> +/obj/item/gun/ballistic/automatic/sniper_rifle/blackmarket  //New variant of the sniper rifle, adminspawn only for now
```suggestion

/obj/item/gun/ballistic/automatic/sniper_rifle/blackmarket  //New variant of the sniper rifle, adminspawn only for now
```

2020-12-03 17:14 UTC, Gandalf2k15 requested changes
See above changes.

2020-12-03 17:34 UTC, Investigator77 commented
There we go

2020-12-06 03:39 UTC, Investigator77 commented
Everything tested on localhost, works fine

2020-12-08 01:06 UTC, merged