[SEMI-MODULAR] APC/Air Alarm lighting and functionality
Skyrat-SS13/Skyrat-TG pull request #20323
Opened 2023-04-04 20:44 UTC by lessthnthree

## About The Pull Request

Now that we have new lighting, lets put the new low power mode to work! This modifies the thresholds to trigger low power lighting and shutting off equipment on APCs. Slight change to the balance of it, now low power lighting will trigger before equipment shuts off. In exchange, the total amount of time you get low power lighting/equipment usage is reduced.

This also adjusts the light colours for APCs and Air Alarms to match our modular edits, as well as the upstream fire alarm lighting. Now all three will have consistent lighting colours to create a more steady ambience. (Particularly ours use blue, not green to indicate power is fine.)

## How This Contributes To The Skyrat Roleplay Experience

- With lighting and equipment taking roughly 50/50 in their power drain, crew would rather lights go into low power mode instead of their console dying. They can bask in the cold glow of said console with the new lighting, just like you're really living in a windowless basement. It won't last as long, though. Engineering can focus on fixing the power instead of flipping APCs for people.
- Having the APCs, air alarms, and fire alarms with inconsistent RGB lighting makes my OCD sad.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://user-images.githubusercontent.com/83487515/229915395-cfcd8c12-d0aa-4ffd-b6ec-4ef7136bed7c.png)

</details>

## Changelog

:cl: LT3
balance: APCs will now trigger low power lighting mode before shutting off equipment. You get slightly less total time in equipment/low power lighting mode.
code: APCs, air alarms, and fire alarms all use the same RGB lighting values for consistency
/:cl:

2023-04-05 03:30 UTC, softcerv commented on modular_skyrat/modules/aesthetics/airalarm/code/airalarm.dm
> +		color = LIGHT_COLOR_ELECTRIC_CYAN
```suggestion
	var/color = LIGHT_COLOR_ELECTRIC_CYAN
	if(danger_level == AIR_ALARM_ALERT_HAZARD)
		color = LIGHT_COLOR_INTENSE_RED
	else if(danger_level == AIR_ALARM_ALERT_WARNING || my_area.active_alarms[ALARM_ATMOS])
		color = LIGHT_COLOR_ORANGE
```

2023-04-05 03:30 UTC, softcerv commented on modular_skyrat/modules/aesthetics/airalarm/code/airalarm.dm
> +		return
```suggestion
		return FALSE
```

2023-04-05 03:30 UTC, softcerv commented on modular_skyrat/modules/aesthetics/apc/code/apc.dm
> +		return
```suggestion
		return FALSE
```

2023-04-05 03:30 UTC, softcerv commented on modular_skyrat/modules/aesthetics/apc/code/apc.dm
> +		return
```suggestion
		return TRUE
```

2023-04-05 03:30 UTC, softcerv commented on modular_skyrat/modules/aesthetics/apc/code/apc.dm
> +		return
```suggestion
		return TRUE
```

2023-04-09 00:01 UTC, Zonespace27 requested changes

2023-04-09 00:01 UTC, Zonespace27 commented on modular_skyrat/modules/aesthetics/apc/code/apc.dm
> +/obj/machinery/power/apc/update_appearance(updates=check_updates())
```suggestion
/obj/machinery/power/apc/update_appearance(updates = check_updates())
```

2023-04-14 22:49 UTC, Gandalf2k15 approved these changes

2023-04-14 22:49 UTC, merged