fix: Removes lewd nifsoft if config is set to remove lewd
Skyrat-SS13/Skyrat-TG pull request #20376
Opened 2023-04-06 18:36 UTC by larentoun

## About The Pull Request

Removes lewd nifsoft if config is set to remove lewd. It makes it impossible to buy and to spawn a disk installer.

## Changelog

:cl:
fix: Removes lewd nifsoft if config is set to remove lewd
/:cl:

2023-04-06 18:52 UTC, Zonespace27 requested changes

2023-04-06 18:52 UTC, Zonespace27 commented on modular_skyrat/modules/modular_implants/code/nifsoft_catalog.dm
> +		if(ispath(buyable_nifsoft, /datum/nifsoft/summoner/dorms) && CONFIG_GET(flag/disable_lewd_items))
Have this be a var or flag on the nifsoft

2023-04-06 20:02 UTC, softcerv commented
nice catch

2023-04-07 00:42 UTC, Gandalf2k15 approved these changes

2023-04-07 00:42 UTC, merged