Peacekeepers Episode Two: Return of the Civil Disputes Officer
Skyrat-SS13/Skyrat-TG pull request #20762
Opened 2023-04-25 04:22 UTC by Gandalf2k15

## About The Pull Request

After great deliberation, we have decided to readd the CDO! 

Key facts:
They do not get access to lockers.
They do not get a proper gun.
They do not get much armor at all.
They have a pepperball gun.
They do not have a bowman.

Their basic loadout:
1x pepperball gunset
1x imrpovised gripper gloves
1x flash
2x cableties

Due to all of the above, this role is severely limited in ways it can deal with threats, which, is great for roleplay purposes. Antags that come across a poor Civil Dispute Officer will always have the upperhand, unless they dont. But generally this means Civil Dispute Officer will be compelled to run away and call for help, giving the antag time to react and actually put em down, or run away as well.

As stated above, this should replace 50% of the security jobslots meaning 2 Civil Dispute Officer and 6 full seccies.

![image](https://user-images.githubusercontent.com/9026500/111402648-797e5800-86c3-11eb-8732-70f39745e0b4.png)

They report to the HoS, sergeant, and any officers.

## Changelog

:cl:
add: The civil disputes officer has made an ultimate comeback!
/:cl:

2023-04-25 04:26 UTC, Nerev4r commented
So, 3 officers, 2 CDOs?

If so, that's okay numbers. If it's 2 CDOs and an apparent 6th seccie, that's a problem; we run 5 officer slots now.

2023-04-25 04:31 UTC, YakumoChen commented
Isn't the new security policy already entirely centered around civil disputes? I actually don't feel we need Security Minus now, we've already moved away from sec being only unga baton and brig man.

2023-04-25 04:32 UTC, GoldenAlpharex requested changes
They should be getting their sec HUD icon back, no empty sec HUD icons please.

2023-04-25 04:37 UTC, theOOZ commented
pr description doesn't convince me at all this is going to result in improved roleplaying.

2023-04-25 04:52 UTC, Iamgoofball commented
CDOs really would be better off as some form of auto-militia method the HOS can enact that lets him quickly deputize people, not as it's own proper job slot. I had a draft for this at some point but never deployed it. Maybe I should do goofsec 3.

2023-04-25 04:54 UTC, SpaceVampire commented
>As stated above, this should replace 50% of the security jobslots meaning 2 Civil Dispute Officer and 5 full seccies.

We are currently running five security officers, so what exactly does this replace?
I'm a little confused by your math here.
Don't department guards more-or-less fill this role already anyway?

2023-04-25 04:58 UTC, Gandalf2k15 commented
> > As stated above, this should replace 50% of the security jobslots meaning 2 Civil Dispute Officer and 5 full seccies.
> 
> We are currently running five security officers, so what exactly does this replace? I'm a little confused by your math here. Don't department guards more-or-less fill this role already anyway?

the PR body was a copy/paste of the original

2023-04-25 05:04 UTC, Gandalf2k15 commented
> They should be getting their sec HUD icon back, no empty sec HUD icons please.

oops fixed

2023-04-25 06:03 UTC, Ebin-Halcyon requested changes
Use the black softcap as a base for the hat sprites, obj and mob.

Everything else needs to be improved as well but i'll go into that at a later date.

2023-04-25 15:48 UTC, Gandalf2k15 commented
> Use the black softcap as a base for the hat sprites, obj and mob.
> 
> Everything else needs to be improved as well but i'll go into that at a later date.

After discussion, we've replaced the uniform with the police variant.

2023-04-25 15:49 UTC, theOOZ commented
Are you rewriting the 'How This Contributes To The Skyrat Roleplay Experience' header? Its missing from the description right now

2023-04-25 16:52 UTC, YakumoChen commented on modular_skyrat/modules/junior_officer/junior_officer.dm
> +		/obj/item/paper = 2,
Two single sheets of paper?
Why not just give them a clipboard or a full paper sheaf

2023-04-25 16:53 UTC, YakumoChen commented on modular_skyrat/modules/junior_officer/junior_officer.dm
> +		/obj/item/pen,
There is a pen in their PDA already

2023-04-25 17:20 UTC, dawsonkeyes commented
I don’t see how this contributes to a more amicable roleplay experience on the server. Shouldn’t the PR at least try to make a point on that matter?

2023-04-25 17:35 UTC, Gandalf2k15 commented
> I don’t see how this contributes to a more amicable roleplay experience on the server. Shouldn’t the PR at least try to make a point on that matter?

Github is for technical review only, please see discord.

2023-04-25 21:28 UTC, softcerv commented
> > I don’t see how this contributes to a more amicable roleplay experience on the server. Shouldn’t the PR at least try to make a point on that matter?
> 
> Github is for technical review only, please see discord.

Don't pull requests on this repository require an explanation as to how they contribute to the Skyrat roleplaying experience?

2023-04-25 21:38 UTC, GoldenAlpharex commented
> > They should be getting their sec HUD icon back, no empty sec HUD icons please.
> 
> oops fixed

The Sec HUD icon still doesn't seem to appear in-game, is it named properly?

2023-04-25 21:39 UTC, GoldenAlpharex commented
Unless the server wasn't updated since, which I don't think it was, actually.

2023-04-25 22:03 UTC, GoldenAlpharex commented
CDO isn't in the proper category in the Crew Monitor (and possibly the Crew Manifest too)

2023-04-25 23:56 UTC, Kepteyn commented
The server usually lacks enough high-level and low-level crime to justify splitting the role into two parts. This division limits the already limited tasks a security officer can do further. If antagonists frequently provided any sort of challenge that required more than five minutes attention to resolve, or the OPFOR system was an effective method of producing sufficient levels of conflict - which, while neither inherently a good or a bad thing, has resulted far, far fewer opposing forces to security - the addition of a role to focus on low-level crime while other officers are dealing with threats might be useful. As it stands, security officers are lacking things to do as is and reducing it by splitting roles is not helpful in my consideration.

2023-04-26 00:02 UTC, Gandalf2k15 commented
> CDO isn't in the proper category in the Crew Monitor (and possibly the Crew Manifest too)

will address

2023-04-26 00:03 UTC, QuacksQ commented
ID and Sechud overlay are missing both missing Icons, image hof the PR also shows it missing.

2023-04-26 00:10 UTC, Gandalf2k15 commented
> ID and Sechud overlay are missing both missing Icons, image hof the PR also shows it missing.

both are definitely there but the server hasnt been updated

2023-04-26 02:07 UTC, Ebin-Halcyon commented
> > Use the black softcap as a base for the hat sprites, obj and mob.
> > Everything else needs to be improved as well but i'll go into that at a later date.
> 
> After discussion, we've replaced the uniform with the police variant.

Remove the unused hats and uniform then.

2023-04-28 16:13 UTC, QuacksQ commented
![image](https://user-images.githubusercontent.com/79924768/235199643-8cf5c3df-0010-487a-8666-1222e24d695c.png)

Low level crimes already existed in corp regs prior to this role but nobody was committing them, I dont think that adding a role is going to make people commit more crime lol

2023-04-28 20:55 UTC, QuacksQ commented
![image](https://user-images.githubusercontent.com/79924768/235252553-e6d94265-4a68-4287-a361-3546f1d96d4d.png)

Missing Icon

2023-05-08 00:08 UTC, YakumoChen commented
still seems to be missing ingame icons

2023-05-24 01:01 UTC, closed without merging