Re-adds MCR cell swapping
Skyrat-SS13/Skyrat-TG pull request #20792
Opened 2023-04-26 17:53 UTC by Gandalf2k15

## About The Pull Request

This simply reads MCR cell swapping and all of the relevant pieces of equipment required to enable this. Most of the changes in the PR-removing cells have also been reverted.

Also reverts the annoying change to the company name which is Micron Control Systems.

P.s. these guns are no longer made by micro star international -.-

## How This Contributes To The Skyrat Roleplay Experience

This change was made without much thought to the **entire purpose of MCRs** which at the time was **specifically to have a reloadable energy gun**. By removing the fundamental design of MCRs you have essentially removed the part that made them unique. This degraded the weapon back to a state of "worse energy gun" when energy guns were replaced. The upgrades are absolutely a great thing, however, they were balanced around having the gun be reloadable. This offered a somewhat unique experience.

While there may have absolutely been some relevant balance indecisions behind swappable cells, they were specifically balanced around not being infinite. This was somehow brought back in a different gun down the line. But wasn't really at all balanced.

The fact that many people have told me that MCR's are just worse laserguns makes sense. I am quite upset by this, as these took a lot of effort to make and are one of the few truly unique guns we have. Seeing them be shoved aside is quite saddening. I also understand that the balance of the server is not the same as it was back when these were added, which is why I'm happy to continue balancing them till they're back in their former glory.

**IMPORTANT:** TEST MERGE THIS UNTIL I CAN ASSESS THE STATE OF BALANCE WITH SWAPPABLE CELLS.

After important testing, I will make any required changes to the guns that address the aforementioned concerns. 

## Proof of Testing
![image](https://user-images.githubusercontent.com/9026500/234659923-360678c7-0741-43cc-8a78-ae8bb8fef6d5.png)
![image](https://user-images.githubusercontent.com/9026500/234659958-8cbdc988-1b1e-468c-96a3-4ae12ae04250.png)

## Changelog

:cl:
balance: MCR's are now reloadable once again.
/:cl:

2023-04-26 17:59 UTC, RatFromTheJungle commented on modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
> +	var/reload_time_slow = 2 SECONDS
are these two backwards?

2023-04-26 18:00 UTC, Gandalf2k15 commented on modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
> +	var/reload_time_slow = 2 SECONDS
looks like it lmao

2023-04-26 18:01 UTC, Gandalf2k15 commented on modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
> +	var/reload_time_slow = 2 SECONDS
oh wait, no, it's manual reloading

2023-04-26 18:01 UTC, Gandalf2k15 commented on modular_skyrat/modules/microfusion/code/microfusion_energy_master.dm
> +	var/reload_time_slow = 2 SECONDS
ill add better var naming lol

2023-04-26 18:02 UTC, Nerev4r commented
I'd probably take a look at https://github.com/Skyrat-SS13/Skyrat-tg/pull/20479 first. Reloadable energy guns are a problem unless the cells are so big you have to ditch the rest of your bag.

2023-04-26 18:03 UTC, Gandalf2k15 commented
> I'd probably take a look at #20479 first. Reloadable energy guns are a problem unless the cells are so big you have to ditch the rest of your bag.

I mentioned this in my PR, what's ironic is the person removed cells from this and then added them to another thing that wasn't balanced. It's fine, these were already balanced around having a lot of em, they have little charge unless upgraded, but I also want to see how current balance fairs with no real changes to the cells made.

2023-04-27 20:34 UTC, YakumoChen commented
Consider the main points of both systems:

-magazines let you take one gun and turn it into several in smaller packages
-reloading magazines is resource intensive and is extremely limited by location

-energy guns are one and done, and bulky
-there are locations to recharge them all over the map, and rechargers are portable
-recharges are resource free
-self-recharging guns exist

MCRs unfortunately have the best features of both systems here, with the main limiter being heat management . Not a bad tradeoff. Self charging cells negate the need to even locate a recharger and are standard if you want to use an MCR.

If you are going to bring back reloads, loading the cell needs an appropriate counterbalance, such as removing the self charge.

I would also consider nerfing how fast you can reload cells in a charger, make it take 5-10 times as long to put a cell back into service.

2023-04-28 08:33 UTC, Stalkeros2 commented
dont consider anything thats tg design add cool new shit thats out of the norm be based

2023-04-29 04:26 UTC, chemistrymain2 commented
> dont consider anything thats tg design add cool new shit thats out of the norm be based

It'd be cooler if it wasn't just another ballistic gun clone.

2023-04-29 10:08 UTC, OrionTheFox commented on code/__DEFINES/~skyrat_defines/cargo_import_companies.dm
> +#define CARGO_COMPANY_MICRON (1<<8)
This wasn't just "an annoying change", MicroStar was a company combination introduced in https://github.com/Skyrat-SS13/Skyrat-tg/pull/17326, a project between Micron and AllStar to sell their weapons in one easy to reach place. It wasn't _just_ a rename, it was a way to combine Energy Guns into one single company for the imports system.

This PR not only reverts that, but seems to have entirely removed all other energy weapons from purchase. Removing the other energy guns from the system is not in the scope of this PR.

2023-04-29 10:09 UTC, OrionTheFox commented on modular_skyrat/modules/company_imports/code/company_datums.dm
>  // Micron control systems and allstar's weapons together, all your energy guns in one place!
The comment is even still there, come on man.

2023-04-29 12:20 UTC, tf-4 requested changes

2023-04-29 12:20 UTC, tf-4 commented on modular_skyrat/modules/company_imports/code/armament_datums/microstar_energy.dm
> -	upper_cost = CARGO_CRATE_VALUE * PRICE_MEDIUMENERGYGUN_HIGH
All of these need to be available

2023-04-29 15:56 UTC, Gandalf2k15 commented on modular_skyrat/modules/company_imports/code/armament_datums/microstar_energy.dm
> -	upper_cost = CARGO_CRATE_VALUE * PRICE_MEDIUMENERGYGUN_HIGH
Oops, cherry pick moment

2023-04-30 00:20 UTC, Gandalf2k15 commented
> Consider the main points of both systems:
> 
> -magazines let you take one gun and turn it into several in smaller packages -reloading magazines is resource intensive and is extremely limited by location
> 
> -energy guns are one and done, and bulky -there are locations to recharge them all over the map, and rechargers are portable -recharges are resource free -self-recharging guns exist
> 
> MCRs unfortunately have the best features of both systems here, with the main limiter being heat management . Not a bad tradeoff. Self charging cells negate the need to even locate a recharger and are standard if you want to use an MCR.
> 
> If you are going to bring back reloads, loading the cell needs an appropriate counterbalance, such as removing the self charge.
> 
> I would also consider nerfing how fast you can reload cells in a charger, make it take 5-10 times as long to put a cell back into service.

The self-charging upgrade should be pretty hard to get, and I'll make the recharger charge rate worse.

2023-04-30 06:49 UTC, YakumoChen commented
> The self-charging upgrade should be pretty hard to get, and I'll make the recharger charge rate worse

It's not, it just requires a little bit of investment in the energy gun company and they're relatively cheap
I buy them in bulk as HoS every shift with budget because they're essential to running MCRs.

2023-04-30 07:29 UTC, Gandalf2k15 commented
> > The self-charging upgrade should be pretty hard to get, and I'll make the recharger charge rate worse
> 
> It's not, it just requires a little bit of investment in the energy gun company and they're relatively cheap I buy them in bulk as HoS every shift with budget because they're essential to running MCRs. There's almost no downside to doing so, save preferring tier 3 equipment for the stabiliser in the other slot (which is also standard on mcr crates anyway)

Hmm, too accessible.  I'll review the availability accordingly.

2023-04-30 08:35 UTC, OrionTheFox commented on modular_skyrat/modules/company_imports/code/armament_datums/allstar.dm
> +
The disabler is still missing.
```suggestion

/datum/armament_entry/company_import/microstar/basic_energy_weapons/disabler
	item_type = /obj/item/gun/energy/disabler
	lower_cost = CARGO_CRATE_VALUE * PRICE_CHEAPENERGYGUN_LOW
	upper_cost = CARGO_CRATE_VALUE * PRICE_CHEAPENERGYGUN_HIGH / 1.5
	stock_mult = 2
```

2023-05-01 11:00 UTC, Paxilmaniac commented
wow batman that's a lot of changes that should be documented in the changelog that aren't

2023-05-03 05:30 UTC, YakumoChen commented on modular_skyrat/modules/microfusion/code/cargo_stuff.dm
> +		/obj/item/microfusion_cell_attachment/rechargeable,
This crate was changed when I removed the excess cells (you only needed one) so you might want to replace the single cells with bulk packs again.

2023-05-03 05:33 UTC, YakumoChen commented on modular_skyrat/modules/microfusion/code/microfusion_cell.dm
> +	desc = "A fourth generation microfusion cell, employing bluespace technology to store power in a medium that's bigger on the inside. This has the highest capacity of any man-portable cell, and has f
three attachments

2023-05-03 05:37 UTC, YakumoChen commented
There are some significant buffs to the shot types, I'm not really sure how wise that is to be buffing that on top of making cells swappable again.

2023-05-03 05:45 UTC, Nerev4r commented
Many undocumented changes here.

2023-05-04 17:34 UTC, chemistrymain2 commented on modular_skyrat/modules/microfusion/code/microfusion_cell.dm
> -	empty = TRUE //MF cells should start empty
You did not document this in the changelog.

2023-05-04 17:35 UTC, chemistrymain2 commented on modular_skyrat/modules/microfusion/code/projectiles.dm
> +	damage = 25 // Basically a hellfire beam
Undocumented change.

2023-05-04 17:35 UTC, chemistrymain2 commented on modular_skyrat/modules/microfusion/code/projectiles.dm
> +	damage = 45 // This damage is split into pellet amount
These are also undocumented.

2023-05-04 17:36 UTC, chemistrymain2 commented
If you want to change the damage the gun does, at least put that in the changelog.

2023-05-05 19:09 UTC, Gandalf2k15 commented
> If you want to change the damage the gun does, at least put that in the changelog.

it was a cherry-pick revert of the cell removal

2023-06-02 20:15 UTC, Nerev4r commented
What's the status on this?

2023-06-07 20:02 UTC, out-of-phaze commented
Friendly reminder that this PR still has unaddressed comments from a month ago and shouldn't be merged as-is.

2023-06-20 21:44 UTC, GoldenAlpharex commented
Re-open this once you're back to address the concerns, and to update the PR in general.

2023-12-25 22:18 UTC, Gandalf2k15 commented
noty dead

2023-12-26 02:53 UTC, SpaceLoveSs13 commented
I knew this would be revived. @Gandalf2k15 I do recommend looking to balance this out a bit since a lot of stuff has been re-added since then.

2023-12-26 04:43 UTC, YakumoChen commented
I still recommend you take my comment above into account but skyrat fucked the balance of guns beyond salvage anyway so its pretty hard to care

2024-01-04 19:39 UTC, closed without merging