Gold Burst (adds extra microbombs to the contractor rep shop)
Skyrat-SS13/Skyrat-TG pull request #20915
Opened 2023-05-03 07:37 UTC by Hatterhat

## About The Pull Request
![funny totsugeki girl doing a burst](https://dustloop.com/wiki/images/f/fd/GGST_Gold_Psych_Burst.png)
- adds some nerfed limited extra microbombs to the contractor rep uplink
    - cannot be implanted into others
    - max 2, for 1 rep each
    - stacking both of them + the standard DC microbomb = minibomb blast radius (1, 2, 4)
## How This Contributes To The Skyrat Roleplay Experience
one-time hard counter to getting dogpiled (you still die but whoever's in your personal space is gonna feel it too)

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![outdated rep shop image](https://user-images.githubusercontent.com/31829017/235856461-f0b799ff-7c08-4cf6-ab02-f3908700f574.png)
![I HAVE BURST](https://user-images.githubusercontent.com/31829017/235856477-a3bd6c6d-aec3-426e-927d-ba0f21fd094e.png)
![gibs funny](https://user-images.githubusercontent.com/31829017/235856488-1f99c238-d151-4d1b-b2f2-998bc5a426bf.png)

</details>

## Changelog

:cl:
add: The Syndicate is now distributing additional reduced-yield microbombs to their Contractors, to be used in tandem with their own microbombs. Lopland and/or Nanotrasen advises relevant crewmembers to avoid sticking too close to baton-wielding kidnapping maniacs.
/:cl:

2023-05-03 14:49 UTC, RatFromTheJungle commented
This would just be another step away from 'atleast they're non-lethal' and closer to 'we might as well just make them a PMS antag.'
I really don't feel that ontop of their standard implant, they need to explode bigger, especially in their current state of balance and tendency to immediately start the implant if they might lose a fight.

2023-05-03 14:49 UTC, Zonespace27 requested changes

2023-05-03 14:49 UTC, Zonespace27 commented on modular_skyrat/modules/contractor/code/datums/contractor_items.dm
> +	give you the same detonating force as a microbomb. Don't give hugs. Or do. Caveat emptor."
"Two of these and a standard microbomb give you the same detonating force as a microbomb" doesn't make grammatical sense

2023-05-03 14:49 UTC, Zonespace27 commented on modular_skyrat/modules/contractor/code/items/misc.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-05-03 14:54 UTC, Zonespace27 commented
Overall, will want to think on the idea first before approving

2023-05-04 09:18 UTC, tf-4 reviewed
Yeah I'm gonna go with no on this one. The point of the explosion is to destroy your gear, not for some call of duty style revenge kill.

2023-05-04 09:18 UTC, closed without merging