[modular] longarm jumpscare: mild CMG damage buff in return for making the stock actually collapse
Skyrat-SS13/Skyrat-TG pull request #20914
Opened 2023-05-03 03:45 UTC by Hatterhat

## About The Pull Request
CMG buff:
- damage multiplier nudged from 0.5x to 0.7x, per-shot raw damage calculated in comments
CMG nerfs:
- base size increased to bulky
- can have its stock collapsed with altclick + 1 second of standing still + holding it to return it to normal size
- collapsed-stock CMGs have 20 spread, up from 0
- extended-stock CMGs have 0 spread

fun bug: did you know that autofire ignores a gun's safety
## How This Contributes To The Skyrat Roleplay Experience
making the CMG slightly better for shooting people with. unfortunately the WT-550 now continues to leave something to be desired

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
![image](https://user-images.githubusercontent.com/31829017/235828888-845998af-70d0-4b61-83bd-470b5e7df987.png)
</details>

## Changelog

:cl:
balance: Thanks to further developments from Nanotrasen Arms' R&D Division, the CMG-2's rounds now carry slightly more stopping power than before (0.5x -> 0.7x damage multiplier).
balance: Unfortunately, adjustments to the CMG's internals now make its folding stock actually adjustable, and also matter for use. Alt-click to toggle its' stock. Users are warned that improper handling will lead to decreased accuracy.
/:cl:

2023-05-03 20:22 UTC, kittysmooch commented
does extendo stock fit on suit slots?

2023-05-04 09:12 UTC, tf-4 requested changes

2023-05-04 09:12 UTC, tf-4 commented on modular_skyrat/modules/sec_haul/code/guns/cmg.dm
> +	. += span_notice("<b>Alt-click</b> to [folded ? "extend" : "collapse"] the stock. This takes a moment.")
```suggestion
	. += span_notice("<b>Alt-click</b> to [folded ? "extend" : "collapse"] the stock.")
```
How does the alt click interaction play with silencers?

2023-05-04 09:12 UTC, tf-4 commented on modular_skyrat/modules/sec_haul/code/guns/cmg.dm
> +		balloon_alert(user, "failed!")
```suggestion
		balloon_alert(user, "interrupted!")
```
Just a consistency thing

2023-05-04 09:12 UTC, tf-4 commented on modular_skyrat/modules/sec_haul/code/guns/cmg.dm
> +	balloon_alert(user, "stock [folded ? "collapsed" : "extended"]!")
```suggestion
	balloon_alert(user, "stock [folded ? "collapsed" : "extended"]")
```
`!`s are for fail states

2023-05-06 16:56 UTC, Gandalf2k15 approved these changes
Ideally this should be a component but out of scope. Someday maybe it will be.

2023-05-06 16:56 UTC, merged