[MODULAR] Prevents organ spilling from dropping genitalia
Skyrat-SS13/Skyrat-TG pull request #21008
Opened 2023-05-08 00:49 UTC by vinylspiders

## About The Pull Request

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/20978

The genitalia will no longer spill out when you get ~~gibbed or~~ disemboweled.

This is accomplished by doing a modular override of the parent `spill_organs()` proc, removing the genitalia from the `organs` list temporarily, calling the parent, and then putting them back in the mob's `organs` afterwards.

Why do it this way? Well, corpses that had their organs spilled will not be inexplicably missing their genitalia this way. To achieve that effect otherwise would require some sloppy skyrat edits and this solution is more elegant and less prone to breakage in my opinion. We are essentially just pretending the genitalia do not exist as far as the `spill_organs` proc knows.

## How This Contributes To The Skyrat Roleplay Experience

It didn't make sense and potentially broke prefs.

## Proof of Testing

<details>
<summary>Organs before calling spill_organs</summary>
  
![dreamseeker_SujonfiHWg](https://user-images.githubusercontent.com/13398309/236711586-5f6d3995-4c7e-4bd0-91da-d94a7e181475.png)

![dreamseeker_fp8gwqVmpo](https://user-images.githubusercontent.com/13398309/236711587-1f8428ff-aac5-496f-9594-e77df0ae352a.png)

</details>

<details>
<summary>Organs after calling spill_organs</summary>
  
![dreamseeker_SujonfiHWg](https://user-images.githubusercontent.com/13398309/236711586-5f6d3995-4c7e-4bd0-91da-d94a7e181475.png)

![dreamseeker_fp8gwqVmpo](https://user-images.githubusercontent.com/13398309/236711587-1f8428ff-aac5-496f-9594-e77df0ae352a.png)

</details>

## Changelog

:cl:
fix: sex organs can no longer spill out when a mob is gibbed or disemboweled
/:cl:

2023-05-08 02:08 UTC, Gandalf2k15 approved these changes

2023-05-08 02:11 UTC, Gandalf2k15 requested changes
Good catch, but can you make sure they still get dispersed on gib? I think that's alright.

2023-05-08 02:55 UTC, vinylspiders commented
> Good catch, but can you make sure they still get dispersed on gib? I think that's alright.

Sure. Done

2023-05-08 03:07 UTC, softcerv commented on tgstation.dme
> +#include "modular_skyrat\master_files\code\modules\mob\living\carbon\death.dm.dm"
```suggestion
#include "modular_skyrat\master_files\code\modules\mob\living\carbon\death.dm"
```
You might also want to change the file name

2023-05-09 03:39 UTC, Gandalf2k15 approved these changes

2023-05-09 03:40 UTC, merged