[LIKE, MOSTLY MODULAR, BUT IT SHOULD BE FINE] Bow Consolidation vol. 1
Skyrat-SS13/Skyrat-TG pull request #21052
Opened 2023-05-10 01:46 UTC by Nerev4r

## About The Pull Request
𝕿𝖍𝖊 𝖆𝖗𝖈𝖍𝖊𝖗 𝖎𝖘 𝖙𝖍𝖊 𝖙𝖗𝖚𝖊 𝖜𝖊𝖆𝖕𝖔𝖓; 𝖙𝖍𝖊 𝖇𝖔𝖜 𝖎𝖘 𝖏𝖚𝖘𝖙 𝖆 𝖑𝖔𝖓𝖌 𝖕𝖎𝖊𝖈𝖊 𝖔𝖋 𝖜𝖔𝖔𝖉.

Welcome to the PR, how are you?
I noticed awhile ago, around the time the last bow improvement came through, that, uh. Shit kinda sucks right now for our modular bows, since time eventually caught up to them.

A /tg/ quiver is a sub type of bag that can pick stuff up from the floor 
A skyrat quiver (crafted) is a belt that doesn't do that.
/tg/ arrows do more damage and are uncraftable.
Skyrat arrows do less, and are craftable.
Forged arrows are a sub type of Skyrat arrows that only are gotten from the forge which are identical in every way but you can use sinew to make them ashen arrows
Note, in game, they're all called wooden arrows.
The /tg/ bows, acquirable from the Renfaire crate or from being a Medieval Reality Simulation, are instant; the Skyrat bows take a bit to draw back. They are coded almost entirely differently.

Are you confused yet? Because I sure was. Would it help you if I told you that we have /tg/ quivers and arrows spawning for Ashwalkers, too?

This PR slims things down drastically. 

For quivers, our quivers are dead. I have overridden the crafting recipe to produce a proper /tg/ quiver instead, and made them use the proper backsprite, because the default belt is one is uggo. They now properly fit on the belt. Nonmodular.

For arrows, the regular /tg/ arrow is now the default. They do 50 damage, and that's that; no wound bonus, no AP. Comparable, if not weaker, than a Mosin shot, wholly comparable to a shotgun slug. The crafting recipe, and forges, now make those, still necessitating cloth, rods, and planks otherwise.

I have not touched the ashen, bone, and bronze arrows; I believe their balance to be mostly fine, as they're essentially specialty trick shots. The ashen for hunting, the bronze for.. bigger hunting, I guess, and the bone for PVP. If anything, I may buff the ashen arrow to 20 in the future.

As for the bows, the longbow is now the default. It fits properly in the back slot, and has sprites and everything. You can make this, get it from the renfaire crate, etc. Nonmodular change there for the sprite, but I promise it's worth it. I have touched the force on the pipe and bone bows to be in mind with the fact that the regular wood one does 15 damage. I expect this will severely impact my GBP. They no longer have draw time, due to the default /tg/ behavior

## How This Contributes To The Skyrat Roleplay Experience
It's terrible to have two kinds of bow, two kinds of arrow, two kinds of quiver, with almost nothing in common.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/17e0e2c4-a0a6-4117-8320-b30e21b7b640)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/cd10ba9d-3ddf-40c1-849b-36d61b47fa41)
This could be you, but we playin'.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

 ![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/17e0e2c4-a0a6-4117-8320-b30e21b7b640)
 ![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/17e0e2c4-a0a6-4117-8320-b30e21b7b640)
 ![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/119a2ba2-7594-4b25-b589-dcc69db8264d)

</details>

## Changelog
:cl:
refactor: Bows now have the default /tg/ behavior, Skyrat-exclusive wooden bows and arrows and quivers are dead.
balance: Bone and pipe bow force up to twenty and ten respectively.
image: Longbows now have the proper back sprite, and quivers now have a more proper belt sprite.
sound: Longbows and others now have draw sound.
/:cl:

2023-05-10 01:50 UTC, Nerev4r commented
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/a326c6f3-d41f-492e-b206-e512fbf1c4c0)
Look how fucking nice that quiver is, by the way. I could bust. A nut, that is.

2023-05-10 09:08 UTC, press-mark reviewed
minor comments, idk if im being too nitpicky lol.

otherwise looks GOOD :)

2023-05-10 09:08 UTC, press-mark commented on code/modules/projectiles/guns/ballistic/bows/_bow.dm
> +		playsound(src, 'modular_skyrat/modules/tribal_extended/sound/sound_weapons_bowdraw.ogg', 75, 0) //SKYRAT EDIT - Bow Consolidation - gets way too high pitched if the freq varies
```suggestion
		playsound(src, 'modular_skyrat/modules/tribal_extended/sound/sound_weapons_bowdraw.ogg', 75, 0) //SKYRAT EDIT - Bow Consolidation
```

don't think this needs needs a comment idk ¯\_(ツ)_/¯

2023-05-10 09:08 UTC, press-mark commented on code/modules/projectiles/guns/ballistic/bows/bow_types.dm
> +	slot_flags = ITEM_SLOT_BACK //SKYRAT EDIT BEGIN - Bow Consolidation
```suggestion
	worn_icon = 'modular_skyrat/modules/tribal_extended/icons/back.dmi' //SKYRAT EDIT BEGIN - Bow Consolidation
	slot_flags = ITEM_SLOT_BACK //SKYRAT EDIT - Bow Consolidation
```

2023-05-10 18:29 UTC, Zonespace27 requested changes, later dismissed
not a full review

2023-05-10 18:29 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/bows/_bow.dm
> +	item_flags = NEEDS_PERMIT //SKYRAT EDIT - Bow Consolidation
why

2023-05-10 18:29 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/bows/_bow.dm
> +	trigger_guard = TRIGGER_GUARD_ALLOW_ALL //SKYRAT EDIT - Bow Consolidation - So Ashwalkers Can Use It
can be modularized

2023-05-10 18:29 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/bows/bow_quivers.dm
> +	slot_flags = ITEM_SLOT_BELT //SKYRAT EDIT - Bow Consolidation
ditto

2023-05-10 18:29 UTC, Zonespace27 commented on code/modules/projectiles/guns/ballistic/bows/bow_types.dm
> +	worn_icon_state = "bow" //SKYRAT EDIT END - Bow Consolidation
ditto

2023-05-11 18:13 UTC, larentoun commented on code/modules/projectiles/guns/ballistic/bows/_bow.dm
> +		playsound(src, 'modular_skyrat/modules/tribal_extended/sound/sound_weapons_bowdraw.ogg', 75, 0) //SKYRAT EDIT - Bow Consolidation
Well, it could be easily be modular with just checking for `chambered` and calling `..()`, AFAIK, but I don't think that's critical?

2023-05-15 16:06 UTC, tf-4 requested changes

2023-05-15 16:06 UTC, tf-4 commented on code/modules/projectiles/guns/ballistic/bows/_bow.dm
> +		playsound(src, 'modular_skyrat/modules/tribal_extended/sound/sound_weapons_bowdraw.ogg', 75, 0) //SKYRAT EDIT - Bow Consolidation
yeah this can be modularised easily

2023-05-15 16:06 UTC, tf-4 commented on modular_skyrat/master_files/code/modules/projectiles/guns/ballistic/bows/bow_quivers.dm
> +/obj/item/gun/ballistic/bow
is this not meant to be a quiver

2023-05-20 22:09 UTC, tf-4 approved these changes

2023-05-20 22:10 UTC, merged