[MODULAR] Ghost Cafe Autolathe
Skyrat-SS13/Skyrat-TG pull request #21058
Opened 2023-05-10 05:04 UTC by softcerv

## About The Pull Request
Adds the autolathe back to the ghost cafe, this time with a special variant that completely lacks any kind of radio.

## How This Contributes To The Skyrat Roleplay Experience
The autolathe from the ghost cafe in https://github.com/Skyrat-SS13/Skyrat-tg/pull/16192 solely because it could be used to print radios and the author of the PR didn't want to create a seperate autolathe type to address this issue. Due to having a variant of the autolathe that is no longer able to print radios, this should no longer be problematic to have. 

Additionally, having an autolathe in the ghost cafe provides a way to teach newer players about game mechanics that would otherwise be stressed out by learning under the pressure of a normal round.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/127e2939-58a6-4072-a216-108e8d9a8b3a)

</details>

## Changelog

:cl:
add: the ghost cafe now has their autolathe back, this time without the ability to print radios.
/:cl:

2023-05-10 11:25 UTC, YakumoChen commented
Explain how your 'why this is good for roleplay' doesn't conflict with #3280 ? Ghost Cafe is explicitly not for 'learning the game', it is a hangout zone.

I'm not even sure what the autolathe meaningfully provides that isn't already somewhere in the same room?

2023-05-10 11:36 UTC, Jolly-66 requested changes
I'm not entirely sold on giving the ghost Cafe an ahtolathe even if radios are taken out.

There should be sufficient tools and materials around if people want to build something.

Also, the ghost Cafe isn't the place to learn about things. Its a place for people to relax, enjoy and RP without the fears of the ongoing round interrupting them.

2023-05-10 11:45 UTC, softcerv commented
>I'm not entirely sold on giving the ghost Cafe an ahtolathe even if radios are taken out.

The PR that removed the autolathe was merged under the premise that it was problematic by granting ghost-cafe users access to radio. Nowhere inside of the discussion of the PR were the other (de)merits of having the autolathe discuessed.

>There should be sufficient tools and materials around if people want to build something.

I'm sure that there are things that are present in the autolathe that aren't present inside of the ghost cafe in it's current state. If you'd like I'm sure I could compile a list for you to look over.

> Also, the ghost Cafe isn't the place to learn about things. Its a place for people to relax, enjoy and RP without the fears of the ongoing round interrupting them.

Not everyone has the knowledge to make a test server, this is the closest thing we have to an ooc way to teach people in-game.  
Could you please explain to me what we gain from forbidding this use case of the ghost cafe?

2023-05-10 12:02 UTC, YakumoChen commented
I did remove the autolathe yes but it wasn't really needed in the first place, you can see in the PR that every effort made to justify the machine being in there was pointed out to already be present in the room in other places.

I can't really think of anything you would want to print from there that isn't probably harmful to the cafe, or already found, aside from maybe a chisel or something?

2023-05-10 12:10 UTC, softcerv commented
> I can't really think of anything you would want to print from there that isn't probably harmful to the cafe, or already found, aside from maybe a chisel or something?

Spray can, Airlock painter, stock parts, construction parts, circuit tiles, extra silverware and cutlery, fishing rods, various plastic toys, and a bunch of miscellaneous stuff.

((While some of these are already present, they are in limited quantity.))

2023-05-10 12:27 UTC, YakumoChen commented
Silverware is the only thing I can think of from that list, maybe spray cans that would be useful (and you can just add a few spray cans to the room, ez)

But silverware should be in the kitchen vendor, so that shouldn't be an issue.

Most of the items you listed aren't realistically useful in the cafe - most of it is nobuild regardless, if I recall.

2023-05-10 13:57 UTC, hugmeorelse commented
While I understand this comes with good intentions, the server is not meant to be a "testing ground" for staff and players alike. In fact, I have already begun discouraging staff from experimenting on the server, and I am looking to setup a separate server for staff for that. The problem is that we have seen the problems that happen from players that treat the Ghost Cafe as a testing area, and staff has enough on their plate to contend with.

2023-05-11 12:45 UTC, Jolly-66 commented
None of the other maintainers have interest and neither do I.

2023-05-11 12:45 UTC, closed without merging