The rightful return of the HOS's non-ballistic big iron.
Skyrat-SS13/Skyrat-TG pull request #21110
Opened 2023-05-12 09:46 UTC by UntoldTactics

## About The Pull Request
Removes the glock box from HOS's loadout.
Reduces the energy consumption of the X-01's lethal option from 120 down to 60
Reduces the energy consumption of the X-01's disable option from 60 to 50
The X-01 now fires a laser projectile that has 0 wound bonus whereas previously it fired a regular laser beam. This makes it as powerful as the MCRs hellfire attachment. (Which does 25 damage- the same as a regular laser gun.)

## How This Contributes To The Skyrat Roleplay Experience
The X-01 in its current state is utterly abysmal comparative to literally every other weapon that exists. It has the damage of a regular laser weapon, yet uses an unheard of amount of energy per shot. It's disable option is fine, although for no real reason worse than both the SC-2 and a regular disabler. Ion makes it unique and was previously the only reason why any sane person wouldn't just ditch it for an SC-2 if the opportunity presented itself.

This seeks to alleviate all those issues. No more ballistic goofy aah glock that kinda just doesn't fit in and is basically a worse CMG thats pistol sized. Instead, the HOS now has a energy weapon that can keep its ground as their trusty companion through times of trouble.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/47285532/720b61eb-109c-4053-bd49-0ec059bfd087)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/47285532/8fa4c43c-668f-4c18-89fc-891065a7f248)

https://github.com/Skyrat-SS13/Skyrat-tg/assets/47285532/cd07bd61-07a8-4b43-95a6-65e0800f4e28

</details>

## Changelog

:cl:
del: The Head of Security lost their glock in the depths of Interlink.
balance: In better news, the Head of Security's X-01 multi-phase energy gun has been refurbished! It now has similiar energy consumption per shot as an SC-2, alongside it's lethal option now having the same wounding power of a hellfire weapon.
/:cl:

2023-05-12 13:48 UTC, Zonespace27 requested changes
This PR is non-modular, please see https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md

2023-05-12 15:51 UTC, UntoldTactics commented
> This PR is non-modular, please see https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md

woops

2023-05-12 18:00 UTC, YakumoChen commented
How does this compare to #21088
Not really keen on them losing a whole gun at cost of making the other gun only halfway better.

2023-05-15 16:19 UTC, tf-4 commented
Ask for a re-open when modularised

2023-05-15 16:19 UTC, closed without merging