Convert LOOC/whisper to TGUI
Skyrat-SS13/Skyrat-TG pull request #21174
Opened 2023-05-14 21:50 UTC by lessthnthree

## About The Pull Request

Finishes off the conversion of our say features to TGUI, the last two holdouts LOOC and whisper.

## How This Contributes To The Skyrat Roleplay Experience

Consistent 'say' UI experience.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/83487515/fdb828d7-0647-4c40-b1e5-9e4dc20a1eee

</details>

## Changelog

:cl: LT3
refactor: LOOC and whisper channels converted to TGUI
/:cl:

2023-05-14 21:54 UTC, distributivgesetz commented
whisper purple is barely visible or is it video compression? also meow

2023-05-14 22:14 UTC, tf-4 requested changes

2023-05-14 22:14 UTC, tf-4 commented on tgui/packages/tgui-say/styles/colors.scss
> +$whis: #300098; // SKYRAT EDIT ADDITION - CUSTOMIZATION
yeahhh this isn't really visible in the provided video

2023-05-14 22:24 UTC, lessthnthree commented on tgui/packages/tgui-say/styles/colors.scss
> +$whis: #300098; // SKYRAT EDIT ADDITION - CUSTOMIZATION
looked lighter in the vsc preview, turns out TGUI puts a filter or something

2023-05-14 22:26 UTC, lessthnthree commented
lightened it up

2023-05-15 12:56 UTC, tf-4 approved these changes

2023-05-15 17:04 UTC, merged