Arcade machines dispense ebow as a prize
Skyrat-SS13/Skyrat-TG pull request #21260
Opened 2023-05-17 06:28 UTC by lessthnthree

## About The Pull Request

Changes the prize for winning against an emagged arcade machine to be an ebow.

## How This Contributes To The Skyrat Roleplay Experience

Requested we not hand out the plasma TTV.

## Changelog

:cl: LT3
balance: emagged arcade machines now provide ebow as a prize
/:cl:

2023-05-17 13:47 UTC, Zonespace27 commented
Heavily against for how silly strong the ebows are, being able to get what is basically an infinite amount for a few TC is pretty broken

2023-05-17 14:28 UTC, SomeRandomOwl commented
Yea i agree with zone here, Ebows are just a one hit knockdown and about a two hit stam crit? I think? (might be three i forget) 

This would be almost too strong of a reward comparatively with how easy it is to beat even a emagged Orion trail, even if the Orion trail has a chance to gib you (or even RR not sure, it can make the the localized short live singularity) this reward is fairly achievable

2023-05-17 17:35 UTC, lessthnthree commented
We'll take the discussion to discord on an alternative item, it doesn't **have** to be an ebow.

2023-05-18 16:21 UTC, Iamgoofball commented on code/game/machinery/computer/arcade/arcade.dm
> +				new /obj/item/gun/energy/recharge/ebow(loc) // SKYRAT EDIT CHANGE - Weapon instead of bomb
Swap it for a minibomb instead, it's far more fitting for winning against this arcade.

2023-05-18 16:22 UTC, Iamgoofball commented on code/game/machinery/computer/arcade/orion.dm
> +		new /obj/item/gun/energy/recharge/ebow(loc) //SKYRAT EDIT CHANGE - Weapon instead of bomb
Make it give like, idk, some rare modsuit part. Maybe Kinesis?

2023-05-20 22:08 UTC, tf-4 requested changes
gonna just make it more official that an ebow is not gonna work here. I don't think other suggestions I've seen of eswords, or other weapons are a good idea for the same reasons.

2023-05-22 07:25 UTC, lessthnthree commented
> gonna just make it more official that an ebow is not gonna work here. I don't think other suggestions I've seen of eswords, or other weapons are a good idea for the same reasons.

Then I'll adjust the PR to be simply the host request to reduce the bomb size.

2023-06-06 01:10 UTC, closed without merging