Astrum refactor
Skyrat-SS13/Skyrat-TG pull request #21319
Opened 2023-05-21 15:53 UTC by tf-4

## About The Pull Request

Reorganises Astrum file structure and code layout, as well as refactoring the abductor mobs into basic mobs.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/8881105/62cddf07-3e67-4793-a1e9-76b00e331425)

</details>

## Changelog
:cl:
refactor: Abductor mobs in the Astrum gateway (not the antagonist) have better AI.
/:cl:

2023-05-21 18:56 UTC, RatFromTheJungle commented
add atleast one gun

2023-05-21 22:32 UTC, Jolly-66 approved these changes
maps fine

2023-05-22 02:31 UTC, Zonespace27 approved these changes
Step 1 of making astrum not completely awful to play through

2023-05-22 02:41 UTC, Zonespace27 requested changes
Actually just a few small things w/ old astrum code that i noticed

2023-05-22 02:41 UTC, Zonespace27 commented on modular_skyrat/modules/awaymissions_skyrat/mothership_astrum/gear.dm
> +	selfcharge = 1
is selfcharge an int or a bool?

2023-05-22 02:41 UTC, Zonespace27 commented on modular_skyrat/modules/awaymissions_skyrat/mothership_astrum/mob.dm
> +	var/loot = list(/obj/effect/gibspawner/generic, /obj/effect/spawner/random/astrum/sci_loot)
typecast to a list and (maybe) static, will want to check how it works w/ subtypes just to be safe

2023-05-22 02:41 UTC, Zonespace27 commented on modular_skyrat/modules/awaymissions_skyrat/mothership_astrum/mob.dm
> +	if(LAZYLEN(loot))
this isn't a lazylist

2023-05-22 02:41 UTC, Zonespace27 commented on modular_skyrat/modules/awaymissions_skyrat/mothership_astrum/mob.dm
> +	return // no more reduction
```suggestion
```

2023-05-22 11:47 UTC, tf-4 commented on modular_skyrat/modules/awaymissions_skyrat/mothership_astrum/mob.dm
> +	var/loot = list(/obj/effect/gibspawner/generic, /obj/effect/spawner/random/astrum/sci_loot)
doesn't work with static but typecasts to a list fine

2023-05-22 16:25 UTC, Zonespace27 approved these changes
cool

2023-05-22 16:25 UTC, merged