Converts mold mobs to basic mobs
Skyrat-SS13/Skyrat-TG pull request #21317
Opened 2023-05-21 13:13 UTC by tf-4

## About The Pull Request

As the title says. Behaviour should be almost entirely preserved, though it's now with the addition of better AI.
Some of this stuff might need some nerfs as a result in the future, but I think it's fine for now.

Also fixes that the oil shamblers would just infinitely stack fire stacks on you but never actually ignite you

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/8881105/fa391abc-ae7d-4de9-a8eb-270070e9c4a5)

</details>

## Changelog
:cl:
refactor: Mold-spawned mobs have been refactored. Expect improved AI behaviours.
fix: Oil shamblers will now actually set you on fire rather than just infinitely stacking fire stacks without igniting them.
/:cl:

2023-05-24 18:37 UTC, lessthnthree approved these changes

2023-06-01 20:07 UTC, RatFromTheJungle commented
@tf-4 add gun mold mob then mayb

2023-06-01 21:12 UTC, GoldenAlpharex requested changes

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +
```suggestion
```

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +
```suggestion
```

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +
```suggestion
```

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +	SSvis_overlays.add_vis_overlay(src, icon, "oil_shambler_overlay", 0, EMISSIVE_PLANE, dir, alpha)
Could these strings be defines, and that `0` a define as well?

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +
```suggestion
```

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +	chem_splash(loc, null, 5, list(reagent_spawn))
These two numbers should be defines.

2023-06-01 21:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +		radiation_pulse(radiation_target, 300, 1, FALSE, TRUE)
Same deal here.

2023-06-10 14:46 UTC, GoldenAlpharex requested changes
Just needs to address the other comments about string defines, and then it would be good to merge.

2023-06-15 20:50 UTC, GoldenAlpharex approved these changes
Just this to fix and then we good.

2023-06-15 20:50 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +		ignite_target.ignite_mob()
```suggestion
	if(!isliving(target))
		return

	var/mob/living/ignite_target = target
	if(prob(oil_shambler.ignite_chance))
		ignite_target.adjust_fire_stacks(oil_shambler.additional_fire_stacks)

	if(ignite_target.fire_stacks)
		ignite_target.ignite_mob()
```

2023-06-15 20:50 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +		return
```suggestion
	if(!isliving(target))
		return

```

2023-06-15 20:50 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +		return
```suggestion
		return

```

2023-06-15 20:50 UTC, GoldenAlpharex commented on modular_skyrat/modules/biohazard_blob/code/mold_mobs.dm
> +		return
```suggestion
		return

```

2023-06-15 23:51 UTC, GoldenAlpharex approved these changes

2023-06-17 18:37 UTC, merged