[MODULAR] Fixes issue with VV Stop All Animations resetting a mob's size
Skyrat-SS13/Skyrat-TG pull request #21362
Opened 2023-05-22 20:44 UTC by vinylspiders

## About The Pull Request

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/21311

The `Stop All Animations` VV menu option was nulling the mob's transform. This PR makes sure that we update any custom body scaling afterwards so the mob does not have its size permanently reset to the default.

## How This Contributes To The Skyrat Roleplay Experience

Bugfix

## Proof of Testing

<details>
<summary>The mob's body size is preserved</summary>
  
![dreamseeker_ukoMp10Vf7](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/ee7289b6-2bb5-4366-9cef-08283d257bf7)

</details>

## Changelog

:cl:
fix: 'Stop All Animations' from the VV menu will no longer cause the mob's size to get permanently reset to the default
/:cl:

2023-05-22 21:17 UTC, Zonespace27 requested changes

2023-05-22 21:17 UTC, Zonespace27 commented on modular_skyrat/master_files/code/game/atoms.dm
> +/// Stop All Animations nulls the mob's transform, so we have to call update_body_size to ensure that it gets scaled properly again
Shouldnt be a code doc so it doesn't override any potential doc of this proc from tg

2023-05-22 21:24 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/atoms.dm
> +/// Stop All Animations nulls the mob's transform, so we have to call update_body_size to ensure that it gets scaled properly again
Fair enough

2023-05-23 01:32 UTC, softcerv commented on modular_skyrat/master_files/code/game/atoms.dm
> +			human_mob.dna.update_body_size()
I think it would be beneficial if you refactored this to use early returns.

2023-05-23 03:51 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/atoms.dm
> +			human_mob.dna.update_body_size()
OK

2023-05-31 14:19 UTC, Zonespace27 approved these changes

2023-05-31 14:19 UTC, merged