[why did i end up changing 15 different files] Ammo Bench Hell: Adjusts A Lot Of Ammobench Stuff
Skyrat-SS13/Skyrat-TG pull request #21383
Opened 2023-05-23 23:42 UTC by Hatterhat

## About The Pull Request
this has been a horrible experience.
- replaces the "lethal ammo disk" with an "advanced ammo disk" which enables lethal ammo AND "advanced" ammo
- gates "advanced" ammo (AP/incen/phasic/etc) behind an advanced ammo disk, still buyable through the usual sources (imports, research)
- makes regular lethals + hollowpoints available just through hacking the ammobench
- makes the parts in the ammobench actually matter in regards to material efficiency + print speeds
### huge big thing:
- ammo bench now requires titanium for AP, plasma for incendiaries, bluespace for phasic (only applicable for 5.56)
## How This Contributes To The Skyrat Roleplay Experience
bullets i guess
## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/5f512f83-b9f3-40e6-8feb-94d4b411eb95)
hacked bench no disk:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/0bbf4f7a-7ccb-485c-adfc-9ac431015db6)
hacked bench printing lethals successfully:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/259f4708-4a4f-426c-bf67-df3f1a7c241e)
hacked bench nonlethals:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/be6dc221-e5de-4ae4-87c4-47d018556590)
unhacked bench w/ disk:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/7fbf9598-9e2b-4790-99b0-f8cf60f846b4)
</details>

## Changelog

:cl:
balance: The ammo workbench can now be hacked to unlock basic lethals (standard/hollowpoint).
balance: The ammo workbench now requires an advanced disk (replaces the old lethal disk) for advanced ammotypes, e.g. incendiary/armor-piercing.
balance: Armor-piercing rounds from the ammobench now require titanium. Incendiary rounds from the ammobench require plasma.
balance: In return for all this, upgraded stock parts now actually matter much more in regards to material consumption efficiency and time efficiency.
/:cl:

2023-05-24 04:20 UTC, Paxilmaniac commented
No gbp???? Oh maintainers!

2023-05-24 07:15 UTC, Hatterhat commented
> No gbp???? Oh maintainers!

no please you cant do this to me i suffered so much putting this together

2023-05-24 11:20 UTC, tf-4 commented
This is the last PR I will let you put through before I will start making you raise your GBP >:)

2023-05-24 14:53 UTC, Hatterhat commented
> This is the last PR I will let you put through before I will start making you raise your GBP >:)

YAMERO

2023-05-24 18:51 UTC, tf-4 commented
The github-actions vs SkyratBot civil war rages on...

2023-05-24 21:04 UTC, Zonespace27 requested changes
Make sure to also change the assop shuttle's ammo bench

2023-05-24 21:04 UTC, Zonespace27 requested changes
Make sure to also change the assop shuttle's ammo bench

2023-05-25 01:37 UTC, Stonetear commented
> and bronze for 12g RIP shells (but you probably don't have a way to access that so)
https://tgstation13.org/wiki/Guide_to_chemistry#Active_Pure_Chemicals
> Copper: Can be splashed on metal sheets to create bronze sheets.
Just needs chemisty, but more inter-department interaction is good.

2023-05-25 01:40 UTC, Hatterhat commented
> > and bronze for 12g RIP shells (but you probably don't have a way to access that so)
> 
> https://tgstation13.org/wiki/Guide_to_chemistry#Active_Pure_Chemicals
> 
> > Copper: Can be splashed on metal sheets to create bronze sheets.
> 
> Just needs chemisty, but more inter-department interaction is good.

honestly i only made RIP shells bronze because, apparently, real RIP shells use solid brass projectiles. thought it'd be a neat detail

2023-05-25 01:43 UTC, Hatterhat commented
> Make sure to also change the assop shuttle's ammo bench

apparently those guys (and others, e.g. tarkon, crashed freighter/cargodise lost) use the same unlocked subtype as well? flagged it to allow funny ammo.

2023-06-01 22:35 UTC, Zonespace27 requested changes

2023-06-01 22:35 UTC, Zonespace27 commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +/obj/machinery/ammo_workbench/proc/toggleTurboBoost(forced = FALSE)
code doc this and please turn it to snake_case

2023-06-01 22:35 UTC, Zonespace27 commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +	if(forced)
make the forced argument's name more clear in *what* it forces

2023-06-01 22:35 UTC, Zonespace27 commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +	loaded_datadisks += loaded_datadisk.type // THIS CAUSES HARD DELS IF THE SOURCE DISK IS DELETED BY THE WAY.
how?

2023-06-01 22:35 UTC, Zonespace27 commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +	toggleTurboBoost(TRUE) // forces turbo off
named argument please, since this arg doesn't really tell me what it does

2023-06-01 22:35 UTC, Zonespace27 commented on modular_skyrat/modules/ammo_workbench/code/design_disks.dm
> +/obj/item/disk/ammo_workbench/proc/set_vars(obj/machinery/ammo_workbench/ammobench)
code doc and make this proc name better, maybe `imprint_disk` or something?

2023-06-07 19:20 UTC, Zonespace27 requested changes
Please make it apparent in the UI what materials each round will consume, and how much

2023-06-12 14:33 UTC, Zonespace27 approved these changes

2023-06-12 14:35 UTC, merged