fixes some locker overlays
Skyrat-SS13/Skyrat-TG pull request #21408
Opened 2023-05-24 20:06 UTC by tf-4

## About the Pull Request

closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/21389
closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/21409

From that PR,
"https://github.com/Skyrat-SS13/Skyrat-tg/commit/fae04f1fb6674a39cb350d0dfdb422a14a3bba7a made it so that lockers use their base_icon_state instead of icon_state for door overlay if none is explicitly set. As seen below.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/8881105/8dab6a4b-39f9-4fef-9f52-15da38862e42)

The lockers on the DS2 are base `/obj/structure/closet/secure_closet` with varedited icon_state so they now need to have their `icon_door` varedited as well to explicitly set the door overlay. Otherwise they will use the grey base secure closet sprites."

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/8881105/38e14928-6fd8-4ff1-9689-a0a487c59cfc)

:cl:
fix: DS-2 lockers will no longer have mismatched doors.
/:cl:

2023-05-24 20:19 UTC, Jolly-66 commented
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/70232195/4bab6d37-7d77-4d54-94e1-a884bf65f3ea)


my pr is better cause i tested it AND have proof

2023-05-24 21:03 UTC, GoldenAlpharex requested changes
Also PR body isn't meeting the PR template, and doesn't show proof of testing.

2023-05-24 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/Syndie_edits/code/secure_closets.dm
> +	name = "\proper station admiral's locker"
My only question is, why is it labelled with `\proper`, if `Station Admiral` is just the Syndicate's version of `Captain`, which isn't a proper word?

2023-05-24 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/Syndie_edits/code/secure_closets.dm
> +	name = "\proper corporate liaison's locker"
Same here.

2023-05-24 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/Syndie_edits/code/secure_closets.dm
> +	name = "MODsuit module locker"
```suggestion
	name = "\improper MODsuit module locker"
```

2023-05-25 21:46 UTC, tf-4 commented on modular_skyrat/modules/Syndie_edits/code/secure_closets.dm
> +	name = "\proper station admiral's locker"
idk thats just how it was before

2023-06-05 06:09 UTC, closed without merging