[SEMI MODULAR] Toggle for Ghost Visiblity of Subtle and Whispers
Skyrat-SS13/Skyrat-TG pull request #21621
Opened 2023-06-05 02:04 UTC by softcerv

## About The Pull Request
Adds in a verb that allows the parent mob to toggle whether or not their subtle and whisper messages are visible to ghosts.

## How This Contributes To The Skyrat Roleplay Experience
This makes it easier to hide messages relating to adult roleplay, which is beneficial for both ghosts and participants in adult roleplay. 

While this does somewhat fill the same niche as subtler, subtler requires the user to do additional typing to mimic a whisper. This also should make it less likely for people to send a message with subtle that they thought would be hidden from ghosts.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
The verb disabled:

User PoV:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/a3971a85-f37e-40c3-a95f-a5f71b502a8b)

Ghost PoV:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/6d35358c-0f85-47d6-bd7b-586287c5110a)

The verb enabled:

User PoV:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/025e3d37-5f0f-4f3e-9ad6-65ce1aeb9de7)

Ghost PoV:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/e988be09-ff27-49db-b9ca-ae215678f690)

</details>

## Changelog

:cl:
qol: Introduces a verb that toggles whether or not whisper and subtle messages are sent to dead chat.
/:cl:

2023-06-05 17:14 UTC, SomeRandomOwl commented
Adding a extra button for this and keeping the subtler button seems kinda redundant, this should honestly remove the subtler button if it is going to add this button that makes subtle do the exact same thing as subtler otherwise its just a redundancy

2023-06-05 18:03 UTC, softcerv commented
> Adding a extra button for this and keeping the subtler button seems kinda redundant, this should honestly remove the subtler button if it is going to add this button that makes subtle do the exact same thing as subtler otherwise its just a redundancy

Subtler does not do the same thing as this button. Subtler allows for the user to choose a specific target or range to send their message to in addition to not having it sent to deadchat. Subtle doesn't provide those same options.

2023-06-05 22:42 UTC, SpaceVampire commented
> Subtler does not do the same thing as this button. Subtler allows for the user to choose a specific target or range to send their message to in addition to not having it sent to deadchat. Subtle doesn't provide those same options.

Then you should just move both of those options to subtle.
Because this makes the whole "Anti-Ghost" part of it redundant.
That seems like the best way to handle it.

2023-06-06 23:06 UTC, YakumoChen commented
I'm worried that preventing ghosts from hearing whispers will have implications with a much farther reach than is realised, considering whispers are almost as common of speech as regular say (given every radio message is whispered)

2023-06-06 23:12 UTC, SomeRandomOwl commented
actually chen has a decent point, whats preventing people from using this on radios? and such?

2023-06-06 23:45 UTC, softcerv commented
> > Subtler does not do the same thing as this button. Subtler allows for the user to choose a specific target or range to send their message to in addition to not having it sent to deadchat. Subtle doesn't provide those same options.
> 
> Then you should just move both of those options to subtle. Because this makes the whole "Anti-Ghost" part of it redundant. That seems like the best way to handle it.

I'd argue that there is still merit in keeping subtler though. 

> actually chen has a decent point, whats preventing people from using this on radios? and such?

Using a radio while whispering does this:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/c38f6193-0350-45dd-bfc2-117bc8314ba9)

I don't think this is a tangible issue.

2023-06-06 23:47 UTC, softcerv commented
> I'm worried that preventing ghosts from hearing whispers will have implications with a much farther reach than is realised, considering whispers are almost as common of speech as regular say (given every radio message is whispered)

Admins are now able to hear ghost muted whispers. This is now fine from an admin perspective.

2023-06-07 00:57 UTC, YakumoChen commented
> > actually chen has a decent point, whats preventing people from using this on radios? and such?
> 
> Using a radio while whispering does this: ![image](https://user-images.githubusercontent.com/68373373/243861542-c38f6193-0350-45dd-bfc2-117bc8314ba9.png)
> 
> I don't think this is a tangible issue.

If you ;say into radios it forces your character to whisper, is the difference

2023-06-07 00:58 UTC, softcerv commented
> > > actually chen has a decent point, whats preventing people from using this on radios? and such?
> > 
> > 
> > Using a radio while whispering does this: ![image](https://user-images.githubusercontent.com/68373373/243861542-c38f6193-0350-45dd-bfc2-117bc8314ba9.png)
> > I don't think this is a tangible issue.
> 
> If you ;say into radios it forces your character to whisper, is the difference

But if you do that, it'll also say the message over radio, which ghosts can listen into. In the rare case that nothing ends up going through, I don't think anything of value would be lost.

2023-06-07 18:49 UTC, lessthnthree commented
If we're going this path I would like to see the subtler's directional function be folded into subtle, and remove the subtler verb.

2023-06-08 01:50 UTC, lessthnthree approved these changes

2023-06-09 09:40 UTC, tf-4 requested changes
I don't think whispers should be hideable

2023-06-09 18:00 UTC, YakumoChen commented
I still stand by "non modular say code is not worth the maintainability cost"

I also think there should be a clear and defined separation between gameplay and ERP, that subtler subtly provided, perhaps the toggle should make a visible indicator for "bedroom combat"

2023-06-09 19:35 UTC, SomeRandomOwl commented
CI required to ERP l, as funny as that sounds it's not practical

2023-06-17 05:34 UTC, SpaceVampire commented
So we are going to remove the whisper part here, right?
It seems better then adding a bunch of non-modular code and weird edge cases.
So that people don't have to press the subtle button sometimes.
The toggle verb option is a great idea, but the rest is overkill for Skyrat.

2023-06-17 06:48 UTC, softcerv commented
>So we are going to remove the whisper part here, right?
>It seems better then adding a bunch of non-modular code and weird edge cases.
>So that people don't have to press the subtle button sometimes.
>The toggle verb option is a great idea, but the rest is overkill for Skyrat.
No. I am willing to modify it to ensure that people don't leave it on by accident 24/7, but I feel like this is something that is worthwhile to have in the game.

2023-06-18 04:00 UTC, GoldenAlpharex requested changes
I'm also still not 100% convinced on the whisper part of this. Whispers are still only usable with the same effective range as subtles, it's just that rather than a hard cutoff, it's all garbled. I'm not sure that a slight convenience, with the opportunity for administrative headaches (no matter how we try to avoid them, they'll still be present) and some more overhead on an otherwise rather hot part of the code (due to the sheer amount of people talking at once on the server).

I know that the main reason for whispers to be included was their usage in TTS, but for now I don't believe that the overhead is worth the potential of using it for a feature that we currently can't use due to its atrocious performance. We can find a better, modular way of enabling that later if that's still something we want to do.

2023-06-18 04:00 UTC, GoldenAlpharex commented on code/modules/mob/living/living_say.dm
> +		if(is_speaker_whispering && isobserver(listening_movable) && !listener?.client?.holder && HAS_TRAIT(src, TRAIT_NO_GHOST_MESSAGES))
This should probably be moved up, where there's already an `is_speaker_whispering` check, as that would make this change far less intrusive and potentially hot.

2023-06-18 04:00 UTC, GoldenAlpharex commented on modular_skyrat/modules/verbs/code/disable_ghost_viewing.dm
> +	to_chat(src, span_notice("You will no longer send whipsers and subtles to dead chat."))
```suggestion
		to_chat(src, span_notice("You will now send whispers and subtles to dead chat."))
		return TRUE

	AddComponent(/datum/component/no_ghost_messages)
	to_chat(src, span_notice("You will no longer send whispers and subtles to dead chat."))
```

2023-06-18 04:00 UTC, GoldenAlpharex commented on modular_skyrat/modules/verbs/code/disable_ghost_viewing.dm
> +	to_chat(parent_mob, span_boldwarning("Due to leaving an area, your whispers and subtles will be sent to dead-chat. To re-disable sending, use the Toggle Ghost Viewing verb."))
```suggestion
	to_chat(parent_mob, span_boldwarning("Due to leaving an area, your whispers and subtles will once again be sent to dead-chat. To re-disable sending, use the Toggle Ghost Viewing verb."))
```

2023-06-18 04:56 UTC, SomeRandomOwl commented
I still 100% disagree with the hide whispers part, it seems like an unnecessary part that has the potential to cause issues from the administrative side of the things.

2023-06-18 12:28 UTC, tf-4 requested changes
There are no maintainers interested in whispers being hidden. Please remove that part.

2023-06-18 17:55 UTC, softcerv commented
> There are no maintainers interested in whispers being hidden. Please remove that part.

This is something that people very clearly can't easily keep on 24/7 because it automatically disables itself when people change their area. The actual effects on normal gameplay would be negligible at best.

Anyways, if whispers aren't hidden, there isn't really a point in having this PR open.

2023-06-18 17:55 UTC, closed without merging