[MODULAR] Remove multi_type var in favor of istype
Skyrat-SS13/Skyrat-TG pull request #21649
Opened 2023-06-05 06:20 UTC by out-of-phaze

## About The Pull Request
Removes the multi_type magazine var and replaces it with just an istype checking if it's the type that defined that var to begin with. Much cleaner!

## How This Contributes To The Skyrat Roleplay Experience
Cleaning up the code in the modular Skyrat folder. I'm serious here, this kind of code should be outright forbidden. `foo:bar` and `in vars` are both terrible patterns.

## Proof of Testing
`multi_type` was only ever defined/set on the one type anyway.

2023-06-05 21:11 UTC, Zonespace27 requested changes

2023-06-05 21:11 UTC, Zonespace27 commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +	if(istype(loaded_magazine, /obj/item/ammo_box/magazine/multi_sprite) && ammo_caliber == initial(ammo_parent_type.caliber) && ammo_caliber != null)
```suggestion
	if(istype(loaded_magazine, /obj/item/ammo_box/magazine/multi_sprite) && ammo_caliber == initial(ammo_parent_type.caliber) && !isnull(ammo_caliber))
```

2023-06-07 19:24 UTC, Zonespace27 approved these changes

2023-06-07 19:41 UTC, merged

2023-06-07 20:15 UTC, Hatterhat commented
tragically there was another really niche usecase in regards to the 7.62 surplus clips but also i agree that this was a Really Bad Pattern