New stamp for NRI
Skyrat-SS13/Skyrat-TG pull request #21676
Opened 2023-06-05 23:47 UTC by VastKilleroOm

## About The Pull Request

Add a new stamp for NRI docks and paperworks

Stamp with text "Флотилия Её Величества". In translation "Her Majesty's Fleet"

## How This Contributes To The Skyrat Roleplay Experience

After that, there will be no more "interesting" moments when the same NRI pirates "Diplomats" playing RP will not be able to show the station command documents about the "duty"

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![Screenshot_1237](https://github.com/Skyrat-SS13/Skyrat-tg/assets/74047915/9d32171e-7c4a-46c4-b5e0-a39a54c8cbbe)

</details>

## Changelog

:cl: Vlada Frolova
image: added icons for stamp andicon for stamp sign
code: add a new stamp
/:cl:

2023-06-06 00:10 UTC, VastKilleroOm commented
10 failing, 10 successful, and 2 skipped checks
Good work. I think

2023-06-06 06:12 UTC, Zonespace27 requested changes, later dismissed
Review does not touch sprites/images

2023-06-06 06:12 UTC, Zonespace27 commented on modular_skyrat/master_files/code/modules/paperwork/stamps.dm
> +	name = "Novaya Rossiyskaya Imperia Stamp"
```suggestion
	name = "/improper Novaya Rossiyskaya Imperia stamp"
```

2023-06-06 06:12 UTC, Zonespace27 commented on code/modules/asset_cache/assets/paper.dm
> +		"stamp-nri" = "modular_skyrat/master_files/icons/stamp_icons/large_stamp-nri.png",
```suggestion
		"stamp-nri" = 'modular_skyrat/master_files/icons/stamp_icons/large_stamp-nri.png',
```

2023-06-07 13:55 UTC, theOOZ approved these changes

2023-06-08 17:31 UTC, merged