block parry dodge - marked one now has a parry visual
Skyrat-SS13/Skyrat-TG pull request #21875
Opened 2023-06-16 12:33 UTC by Hatterhat

## About The Pull Request
replaces the "damage blocked!" balloon alert with a parry sound + visual, like on capsabre and whatnot

## How This Contributes To The Skyrat Roleplay Experience
megafauna fights arent roleplay but it was a fun little thing i thought would be applicable

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/d5532190-3466-4b8c-995b-aa301e0a4ed7)  
</details>

## Changelog

:cl:
qol: The Marked One now displays a funny little parry indicator and sound instead of a big floating "damage blocked!" balloon alert.
/:cl:

2023-06-16 13:52 UTC, Iamgoofball commented
this one can probably be upstreamed

2023-06-16 16:31 UTC, tf-4 commented
that's a skyrat megafauna

2023-06-16 16:32 UTC, tf-4 requested changes

2023-06-16 16:32 UTC, tf-4 commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +		// balloon_alert_to_viewers("damage blocked!") // not sure if this should be a visible message in the chatlog, remain as a balloon alert, or be dropped tbh
```suggestion
```
doesnt need to stay

2023-06-18 12:26 UTC, tf-4 approved these changes

2023-06-18 12:26 UTC, merged