Remove frog
Skyrat-SS13/Skyrat-TG pull request #2193
Opened 2020-12-16 06:26 UTC by Armyguy

Just remove it

## About The Pull Request

I removed the frog

## Why It's Good For The Game

It removes the frog

## Changelog
:cl:
Removed the frog
/:cl:

2020-12-16 06:30 UTC, Armyguy commented
Ok Im going to need to remove the mob from the maps its on.
THAT i will do later so for now DNM.

2020-12-16 07:54 UTC, KasparoVy commented
:-1::frog:

2020-12-16 18:53 UTC, Avunia commented
You could've just commented out the line that plays the annoying sound, _**if**_ that is the reason for the removal, without invoking a ton of other issues.

PS: GitHub has a "draft PR" feature if your PR is not ready to be merged.
Top right:
![image](https://user-images.githubusercontent.com/6952402/102393162-4bac4900-3fd8-11eb-80dd-c8a91e3037fc.png)

2020-12-16 21:25 UTC, Armyguy commented
> You could've just commented out the line that plays the annoying sound, _**if**_ that is the reason for the removal, without invoking a ton of other issues.
> 
> PS: GitHub has a "draft PR" feature if your PR is not ready to be merged.
> Top right:
> ![image](https://user-images.githubusercontent.com/6952402/102393162-4bac4900-3fd8-11eb-80dd-c8a91e3037fc.png)

Yea but i forgot that its just ON a map

2020-12-16 21:26 UTC, Armyguy commented
There we go sound removed

2020-12-16 22:22 UTC, Armyguy commented
There we go, it just removes the sound now making it 1000% better.

2020-12-17 00:01 UTC, NotRanged commented
Bad PR, keep frog

2020-12-17 02:42 UTC, Avunia requested changes
@Armyguy By the way we have a [modularisation guide](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md).
See [this part on how to add/remove/change non-modular code](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md#non-modular-changes-to-the-core-code---important).

This time I've gone ahead and commented the appropiate additions to make it conform, so if you're fine with the changes you did, just apply them! Aside of that this looks fine!

2020-12-17 02:42 UTC, Avunia commented on code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
> +	//attack_sound = 'sound/effects/reee.ogg'
```suggestion
//SKYRAT EDIT REMOVAL BEGIN
/*
	attack_sound = 'sound/effects/reee.ogg'
*/
//SKYRAT EDIT REMOVAL END
```

2020-12-17 02:42 UTC, Avunia commented on code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
> +	//var/stepped_sound = 'sound/effects/huuu.ogg'
```suggestion
//SKYRAT EDIT REMOVAL BEGIN
/*
	var/stepped_sound = 'sound/effects/huuu.ogg'
*/
//SKYRAT EDIT REMOVAL END
```

2020-12-17 02:42 UTC, Avunia commented on code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
> +/*
```suggestion

//SKYRAT EDIT REMOVAL BEGIN
/*
```

2020-12-17 02:42 UTC, Avunia commented on code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
> +*/
```suggestion
*/
//SKYRAT EDIT REMOVAL END
```

2020-12-17 17:41 UTC, Avunia commented
@Armyguy The first two var removals also have to be marked with the skyrat comment, I've updated my suggestion to be more streamlined.

2020-12-17 23:14 UTC, Avunia approved these changes

2020-12-18 01:42 UTC, merged