these are some REAL tentative numbers trust me - ammo material rebalance (mainly for the ammobench)
Skyrat-SS13/Skyrat-TG pull request #21934
Opened 2023-06-19 11:05 UTC by Hatterhat

## About The Pull Request
reduces ammo costs across the board so that the ammo bench isn't so greedy in regards to material when printing ammo. still, please don't lock in turbo unless necessary.

ammo costs:
- reduced from base `SMALL_MATERIAL_COST * 5` to `SMALL_MATERIAL_COST * 1`
(this is because the old small cost was 5% of a sheet. the new small cost is 10% of a sheet. with the old multiplier a single casing was literally 25% a sheet (bad) and now it's just 10% a sheet (maybe arguably worse))
- adjusts all material costs of ammo to be in that same ballpark (all totals up to 1 total `SMALL_MATERIAL_COST`)
- shotgun ammo base material total nudged to `SMALL_MATERIAL_COST * 4` (mild decrease from literally half a sheet per shell. i don't know if i want to decrease this considering how shotguns are but idk)

## How This Contributes To The Skyrat Roleplay Experience
does shooting people still count as roleplay? makes a single bullet no longer cost HALF AN ENTIRE METAL SHEET

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

off a t4 bench:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/459a94b4-1a93-4eb9-87ce-11164ddd7c63)
off a t1 bench:
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/a92bd209-acb3-46ff-a295-e032e3876d25)

</details>

## Changelog

:cl:
balance: Base material costs for ammunition have been sharply reduced across the board, because a single 9mm casing or equivalent costing half a sheet was egregious. This mainly only applies to the ammo bench; lathe recipes are their own system and remain untouched.
/:cl:

2023-06-19 18:55 UTC, YakumoChen commented
Ammo has always has a very high material cost, like many printable combat items (see: autolathe costs)

I'm not against a high material cost for ammo, especially for the ammo bench which can just have the parts upgraded to lower it.

2023-06-20 00:29 UTC, HoodMilk commented
With the TG mineral rebalance ammo is actually pretty cheap from lathes, I think a 357 speedloader was only 360 cm3 iron, and that's including the speedloader.

More consistency with ammo costs is always good.

2023-07-08 16:47 UTC, YakumoChen commented
> With the TG mineral rebalance ammo is actually pretty cheap from lathes, I think a 357 speedloader was only 360 cm3 iron, and that's including the speedloader.
> 
> More consistency with ammo costs is always good.

https://github.com/Skyrat-SS13/Skyrat-tg/blob/ca066b1b2832477a839e86c0f4e5dbb3dba70471/code/modules/research/designs/autolathe/security_designs.dm#L23

I'm pretty sure that's false? It still takes 30 sheets for a box of ammo in the tg autolathe

2023-07-19 22:07 UTC, GoldenAlpharex requested changes
Just a minor thing, otherwise it seems good to me. I'd probably just test-merge it first, just in case anything was to suddenly go wrong, but I doubt it'll be the case.

2023-07-19 22:07 UTC, GoldenAlpharex commented on modular_skyrat/modules/shotgunrebalance/code/shotgun.dm
> +	// ...you know what if you're confident you can get up in there, you might as well get to use it if you're able to print Weird Shells.
```suggestion
	// ...you know what if you're confident you can get up in there, you might as well get to use it if you're able to print Weird Shells.

```

2023-07-21 20:58 UTC, GoldenAlpharex approved these changes
Should be good for a test-merge.

2023-07-24 20:58 UTC, GoldenAlpharex commented
Haven't heard any complaints, or really much feedback at all, I doubt anyone's actually got an issue with this. Let's go ahead and merge it now then.

2023-07-24 20:58 UTC, merged