[MODULAR] Marked One Changes Part 5: bargain bin edition no. 2
Skyrat-SS13/Skyrat-TG pull request #21998
Opened 2023-06-22 22:59 UTC by dawsonkeyes

## About The Pull Request

This PR slightly changes up how the marked one’s charge attack works, while making it less common and hopefully ensuring that it doesn’t create constant superspeed. It also adds semi-rare spoken lines during teleport attacks, and rebalances the final phase in lieu of having random charges.

## How This Contributes To The Skyrat Roleplay Experience

Doesn’t! This guy’s a megafauna, you can’t really roleplay with him. Wish ya could. Miners gave me general feedback on his balancing, and through testing I’m gonna keep making more changes like this.

## Changelog

:cl:
balance: the Marked One has reduced attack cooldowns and rebalanced attack strategies in his final phase 
fix: charge attacks no longer grant John Marked One infinite superspeed
/:cl:

2023-06-22 23:00 UTC, dawsonkeyes commented
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

nuh uh

2023-07-04 07:19 UTC, dawsonkeyes commented
nuh uh

2023-07-25 21:08 UTC, GoldenAlpharex requested changes

2023-07-25 21:08 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	move_to_delay = (pre_charge_delay - 0.4)
Make this value into a define, please.
```suggestion
	move_to_delay -= 0.4
```

2023-07-25 21:08 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +	move_to_delay = (post_charge_delay + 0.4)
Ditto on this one (same define)
```suggestion
	move_to_delay += 0.4
```

2023-07-25 21:08 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +						)
```suggestion
			var/static/list/tele_messages = list(
				"Hi.",
				"Hello there.",
				"Hello.",
				"Hey.",
				"Yo.",
				"Boo.",
				"Sup.",
			)

```

2023-07-25 21:08 UTC, GoldenAlpharex commented on modular_skyrat/modules/gladiator/code/modules/mob/living/simple_animal/hostile/megafauna/markedone.dm
> +			if(prob(20))
Make that `20` into a define, please.

2023-08-02 00:47 UTC, GoldenAlpharex approved these changes
Looks good, thanks!

2023-08-02 00:47 UTC, merged