The Illusive Language Re-Flavor PR
Skyrat-SS13/Skyrat-TG pull request #22113
Opened 2023-06-28 07:38 UTC by Draganfrukts

## About The Pull Request

This PR focuses on re-writing a good chunk of our custom languages to better suit the universe around them and increase the quality in which they're presented.

## How This Contributes To The Skyrat Roleplay Experience

Currently, a portion of these languages are badly written and lack both substance and justification. Why the hell would people be casually speaking in pure Japanese in the 26th century? Why is there a dedicated language for poor citizens?
It also broadens the character possibilities by mechanically expanding the pool that you can choose from for cultures and tongues. You /could/ do it before this PR, but this makes things easier.

## Changelog

:cl:
spellcheck: Reflavored and/or expanded most custom languages.
image: Improved the quality of several language icons.
/:cl:

2023-06-28 07:40 UTC, Nerev4r commented
I like this. These hit a lot better than the previous versions.

2023-06-28 07:45 UTC, Paxilmaniac commented
Chinese catgirls will become real

2023-06-28 09:33 UTC, Gyrandola commented
I don't like that you made ALL those languages  specifically tied to a planet or a culture. You are leaving no lorefriendly choice for custom lore characters that come from outside known nations/systems and who could, at least, pick Spacer or Gutter to symbolize their "outsider" background.

Don't get me wrong, I do like how you characterized Sol etcetera but ultimately the removal of all "generic" languages hurts player freedom in a subtle way.

2023-06-28 10:38 UTC, tf-4 commented
GOOD PR

2023-06-28 11:08 UTC, OrionTheFox commented on modular_skyrat/modules/customization/modules/language/piratespeak.dm
> +	name = "Spatial Sea-talk"
```suggestion
	name = "Spatial Sea-tongue"
```
Sea-talk sounds weird in my personal opinion; tongue may not be better tho so its up for debate.
Also worth considering, "Spacial" as a synonym which may fit better to emphasize solar-space vs material-space (https://thesaurus.plus/related/spacial/spatial)

2023-06-28 11:12 UTC, OrionTheFox commented on modular_skyrat/modules/customization/modules/language/spacer.dm
> +	desc = "A rough, informal tongue originally used by a rogue Tajaran crew in a trading post as a last resort when attempts to establish dialogue in more proper languages fail and no automatic transla
```suggestion
	desc = "A rough, informal tongue originally used by a rogue Tajaran crew in a trading post as a last resort when attempts to establish dialogue in more proper languages failed and no automatic translators are available. It relies heavily on tone, body language, signing, and a multitude of creole loanwords. While its use has fallen severely over the years, it's still practiced by a quantity of Frontier crews and favored by the Free Trade Union."
```
Not quite sure on this one tbh. This description makes it seem like it was a 'use once, never really again' when the current interpretation places it as a 'still in use fallback communication'

2023-06-28 11:15 UTC, OrionTheFox commented
Icon states check out, the new ones look real clean ❤️ 
Not going to debate the pan-slavic flag change since I have no say in that lore but it's worth noting the drastic change for other reviewers

2023-06-28 14:29 UTC, Draganfrukts commented
> I don't like that you made ALL those languages specifically tied to a planet or a culture. You are leaving no lorefriendly choice for custom lore characters that come from outside known nations/systems and who could, at least, pick Spacer or Gutter to symbolize their "outsider" background.
> 
> Don't get me wrong, I do like how you characterized Sol etcetera but ultimately the removal of all "generic" languages hurts player freedom in a subtle way.

You don't need to belong to a State nor a culture to speak a specific language. IE, I don't have a drop of Anglo blood or history in me yet I speak English.
Spacer is also very much still a generic language.

2023-06-28 20:11 UTC, Nerev4r commented on modular_skyrat/modules/customization/modules/language/yangyu.dm
> +	name = "Spacial Sino-Tibetan"
use Orbital Sino-Tibetan it goes hard
tie it into east asian orbital habitats around mars or smth

2023-06-28 21:51 UTC, YakumoChen commented
It was mentioned with the akula language (iirc zone supported this) but descriptions need to have a more UI friendly presentation like a drop down or scroll bar to not clutter the language UI needlessly with lots of paragraphs of text.

2023-06-28 22:19 UTC, Draganfrukts commented
> It was mentioned with the akula language (iirc zone supported this) but descriptions need to have a more UI friendly presentation like a drop down or scroll bar to not clutter the language UI needlessly with lots of paragraphs of text.

Not within the scope of this PR. In comparison to the Akulan language, they're about the right length.

2023-07-01 20:44 UTC, GoldenAlpharex requested changes
Just a reminder that Xyel requested that the changes to Yangyu would be moved over to Uncommon instead, and to have Yangyu left as-is for now.

2023-07-02 18:14 UTC, Draganfrukts commented
> Just a reminder that Xyel requested that the changes to Yangyu would be moved over to Uncommon instead, and to have Yangyu left as-is for now.

Talking this out currently

2023-07-02 18:38 UTC, Draganfrukts commented
> Just a reminder that Xyel requested that the changes to Yangyu would be moved over to Uncommon instead, and to have Yangyu left as-is for now.

Reached an agreement and changed accordingly. It should be good to go now.

2023-07-02 19:23 UTC, Draganfrukts commented
More discussion happening, possible changes abroad 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/51841793/f312c5ef-6bd9-4599-8d72-1e2e9bddc7d0)

2023-07-02 23:09 UTC, GoldenAlpharex approved these changes
After a bunch of back and forth, I'm satisfied with where it's at now. Good work.

2023-07-14 21:55 UTC, GoldenAlpharex commented
Haven't heard much in terms of complaints about this, so I'll go ahead and merge it.

2023-07-14 21:56 UTC, merged