Tramstation Barber Remake
Skyrat-SS13/Skyrat-TG pull request #22143
Opened 2023-06-29 22:01 UTC by Lunar248

## About The Pull Request
Replaces the default TG barber on Tramstation with something closer to what other stations have available. Also includes a modification to the automapping configuration to allow it to spawn correctly. This also remakes the backroom into a small massage room, alongside mechanical curtains that can be closed via buttons.

## How This Contributes To The Skyrat Roleplay Experience
While the barbershop isn't exactly the most integral area of the station, this will hopefully make Tram's barbershop feel a little less disappointing, and give the barber role a bit more room and opportunity for RP. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/134661012/d8f10d01-dec2-4f19-91d2-c734a48c74e0)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/134661012/f0f7d5d1-1f20-4982-b92e-956c15ee7919)

</details>

## Changelog

:cl:
qol: Remapped the barbershop on tramstation to make it a bit more RP-friendly, and visually appealing.
/:cl:

2023-06-30 17:28 UTC, HoodMilk commented
Rest in peace stupid mario costume backroom

2023-07-04 12:40 UTC, Jolly-66 requested changes
These two doors have an unnecessary id tag on them. Please remove them.

Minor nitpick but the top maintenance door doesn't need to be named.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/70232195/b9469baa-2265-43d8-a5d7-bb432d802384)

2023-07-04 18:40 UTC, Lunar248 commented
Made those changes and added bolts for the backroom. Quickly took things into testing, and they work!
<img width="285" alt="barberbackroom" src="https://github.com/Skyrat-SS13/Skyrat-tg/assets/134661012/3cc615d8-086b-4f4a-95f2-a60ef3e86970">

2023-07-05 12:59 UTC, Jolly-66 approved these changes
Undraft your PRs after you make changes next time bottom.

2023-07-05 12:59 UTC, merged