[Modular] Revert borg language changes
Skyrat-SS13/Skyrat-TG pull request #22192
Opened 2023-07-02 07:43 UTC by Stalkeros2

## About The Pull Request
Good morning pepol; woke up and saw this.
Reverts #22169's changes to modular files.

## How This Contributes To The Skyrat Roleplay Experience
The PR's changes are entirely opposed to Skyrat's design of silicons and the crew, and is completely detrimental to player interactions. I'd write more but I didn't have my breakfast so can't write a lot and why would you need a lot of text the first sentence is effectively the tl;dr of the whole reasoning.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/42087567/4dc93f5f-6fae-41d4-8af9-f37b61fd9113)

</details>

## Changelog

:cl: Stalkeros
add: Borg languages are back.
/:cl:

2023-07-02 09:48 UTC, Iamgoofball commented
It hasn't even hit live yet, why don't we see how it goes first?

2023-07-02 09:52 UTC, Stalkeros2 commented
> It hasn't even hit live yet, why don't we see how it goes first?

I'm fairly certain that there's no need for "seeing how it goes" when that was a solution for the upstream's issue and not the downstream's.

2023-07-02 09:57 UTC, Iamgoofball commented
it's an issue down here as well since we restrict the number of languages you can have active at once here too, cyborgs and encryption keys let people bypass that limit

2023-07-03 09:05 UTC, HoodMilk commented
There's usually 2-3 borgs a round, on top of an AI (except for lowpop) and they're the easiest option for translation by far. Taking away this ability lets some of the lesser used ways to translate shine, like curators or PAI. I think the language restriction creates more interesting RP scenarios rather than taking them away. Even if there's some people cyborgs can't understand (The only situation of this now would be people intentionally speaking in an alternate language or ashwalkers), you can still communicate using emotes anyway.

2023-07-03 22:24 UTC, chemistrymain2 commented
> There's usually 2-3 borgs a round, on top of an AI (except for lowpop) and they're the easiest option for translation by far. Taking away this ability lets some of the lesser used ways to translate shine, like curators or PAI. I think the language restriction creates more interesting RP scenarios rather than taking them away. Even if there's some people cyborgs can't understand (The only situation of this now would be people intentionally speaking in an alternate language or ashwalkers), you can still communicate using emotes anyway.

No, it's just unfun. Sometimes I enjoy having private conversations with other species in their preferred language, and it creates RP that way.

Viewing languages this way like 'the ways to translate' is for ashwalkers or icewalkers. Most of the time, languages aren't used for this, because that sort of mechanical focus is more TG's thing. Instead, languages are used for RP.

The curator and pAi can speak in ashwalker and icecat and pirate and all the other important antag languages by default-there's no reason to lock borgs out of being able to speak chitinclick or draconic if they want to talk to a mothman or a lizardperson.

It's actually creating the opposite of interesting RP scenarios. It's just boring and unfun, speaking as a borg.

2023-07-03 22:27 UTC, chemistrymain2 commented
> It hasn't even hit live yet, why don't we see how it goes first?

It's hit live.

It sucks.

2023-07-04 11:04 UTC, HoodMilk commented
Fair enough I don't play cyborgs, but borgs should probably only know languages you can actually pick roundstart currently. After the language change happened they still know some of the old languages that crew can't even pick like shadowtongue, mushroom, or nekomimetic (Tbh not sure whey they're even in the code anymore they aren't used).

2023-07-04 12:37 UTC, Iamgoofball commented
>The curator and pAi can speak in ashwalker and icecat and pirate and all the other important antag languages by default-there's no reason to lock borgs out of being able to speak chitinclick or draconic if they want to talk to a mothman or a lizardperson.

We're actually removing that from pAI upstream already, pAIs are going to inherit their current holder's languages.
Curators get to know every language because they're the librarian, aka massive nerd. They're also a one slot role and potentially an antagonist.

2023-07-04 14:56 UTC, SarmentiCampbell commented
It is horrible, hope this get merged pretty fast

2023-07-04 21:08 UTC, PhonyName commented
This needs to get merged ASAP, this reeks of "Antag run ruined, time to remove" salt PR. I fail to see the rationale for this PR being added, and it should be reverted.

Wanna have a private conversation with a silicon in the room? Law 2, fuck off borg.
Wanna use the curator? Ask the curator.
All this does is diminish the already limited silicon RP capacity.

Pls retire again.

2023-07-04 23:35 UTC, GoldenAlpharex requested changes

2023-07-04 23:35 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/language/language_holder.dm
> +							)
Please format these lists properly, so they aren't so much of an eyesore, and incredibly indented for no reason.

2023-07-04 23:36 UTC, SarmentiCampbell commented
On another note, You also forgot to do a removal on the original language holder

2023-07-04 23:36 UTC, GoldenAlpharex commented
> On another note, You also forgot to do a removal on the original language holder

That isn't necessary, this is an override.

2023-07-04 23:39 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/language/language_holder.dm
> +							)
Fixed it myself.

2023-07-04 23:39 UTC, GoldenAlpharex approved these changes
Should be good to go now.

2023-07-05 00:14 UTC, GoldenAlpharex commented
For reference, merging this because it's an override we had in the code on our side, which means it was intentional, so it has to be removed intentionally in its own PR.

2023-07-05 00:14 UTC, merged