[MODULAR] Anti-Gravity Harness
Skyrat-SS13/Skyrat-TG pull request #22518
Opened 2023-07-16 23:36 UTC by Nerev4r

## About The Pull Request
_Gravity, is a harness... and I have harnessed the harness._

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/23a916ff-eb91-4211-b7fc-8af1987e2990)

PR is a WIP (Work In Progress for those unfamiliar) rn, but this will add a gravity-harness that can be purchased from Cargo as a goodie. Modes right now are anti-gravity and guaranteed gravity™ like magboots. Storage is TBD, currently doesn't have any. Bugs need to be ironed out first. Yes, this has support for nu-digi.

For balance, it is back-mounted and requires power cells to function.

## How This Contributes To The Skyrat Roleplay Experience
Given the upcoming existence of the Spacer Born quirk as well as paraplegic characters (and I would like, eventually, to add support for people with the Bad Back quirk), having a futuristic disability aid that can also function as a technology upgrade for miners/moths/anyone that benefits from anti-gravity, I thought it would be prudent to add in something for those crowds.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl:
add: Purchasable gravity harness in the Cargo goodies section.
/:cl:

2023-07-16 23:40 UTC, Paxilmaniac commented
> guaranteed gravity™

Using this mode in space should banish you to the void like using the atrocinator on lavaland does.

2023-07-16 23:57 UTC, W4rd3nn commented
> > guaranteed gravity™
> 
> Using this mode in space should banish you to the void like using the atrocinator on lavaland does.

this as hell.

also very good pr maintainers speedmerge this NOW

2023-07-17 01:34 UTC, Elli-Skala commented
Doesn't this undermind a mod suit module that requires a anomaly core and its whole tech just to make?

2023-07-17 01:53 UTC, softcerv commented
> Doesn't this undermind a mod suit module that requires a anomaly core and its whole tech just to make?

This prevents you from using a MODSuit or backpack though. I feel like that is a reasonable enough trade-off.

2023-07-17 03:42 UTC, softcerv reviewed
some stuff I noticed, there will probably be more later.

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	var/modeswitch_sound = 'sound/effects/pop.ogg'
we need autodoc comments for these variables.

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +			return MODE_GRAVOFF
We don't need to have this. You can modify to the `switch` to have it change the mode variable. PM me on discord if you need help.

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +		return MODE_GRAVOFF
what does this do?

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	var/extragravity_state = "gravityharness-extra"
These can probably be converted into defines

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	var/off_state = "gravityharness-off"
This can be converted into a define too

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +			gravity_on = FALSE
```suggestion
	switch(mode)
		if(MODE_ANTIGRAVITY)
			if(user.has_gravity())
				new /obj/effect/temp_visual/mook_dust(get_turf(src))
			user.AddElement(/datum/element/forced_gravity, 0)
			playsound(src, 'sound/effects/gravhit.ogg', 50)
			to_chat(user, span_notice("Your harness releases a metallic hum, projecting a local anti-gravity field."))
			gravity_on = TRUE
			icon_state = antigravity_state
			worn_icon_state = antigravity_state
			
		if(MODE_EXTRAGRAVITY)
			if(!user.has_gravity())
				new /obj/effect/temp_visual/mook_dust/robot(get_turf(src))
			user.RemoveElement(/datum/element/forced_gravity, 0)
			ADD_TRAIT(user, TRAIT_NEGATES_GRAVITY)
			playsound(src, 'modular_skyrat/master_files/sound/effects/robot_sit.ogg', 25)
			to_chat(user, span_notice("Your harness shudders and hisses, projecting a local extra-gravity field."))
			gravity_on = TRUE
			worn_icon_state = extragravity_state
			
		if(MODE_GRAVOFF)
			if(!user.has_gravity())
				new /obj/effect/temp_visual/mook_dust/robot(get_turf(src))
				playsound(src, 'modular_skyrat/master_files/sound/effects/robot_sit.ogg', 25)
				to_chat(user, span_notice("Your harness lets out a soft whine as your gravity field dissipates, your body free-floating once again."))
			
			else
				if(user.has_gravity())
					new /obj/effect/temp_visual/mook_dust(get_turf(src))
					playsound(src, 'sound/effects/gravhit.ogg', 50)
					to_chat(user, span_notice("Your harness lets out a soft whine as your gravity field dissipates, leaving your body grounded once again."))
			user.RemoveElement(/datum/element/forced_gravity, 0)
			REMOVE_TRAIT(user, TRAIT_NEGATES_GRAVITY)
			icon_state = off_state
			worn_icon_state = off_state
			gravity_on = FALSE
```

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +				. += "\The [cell] is firmly in place."
```suggestion
	if(in_range(src,user) || isobserver(user))
		. += "The gravity harness is [gravity_on ? "on" : "off"] and the field is set to [mode]"
		. += "The power meter shows [cell ? "[round(cell.percent(), 0.1)]%" : "!invalid!"] charge remaining."
		if(cell_cover_open)
			. += "The cell cover is open, exposing the battery."
			if(!cell)
				. += "The cell slot is empty, showing bare connectors."
			else
				. += "\The [cell] is firmly in place."
		
	return .
```

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +		return
You could probably refactor this into being an early return.

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	return ..()
same here

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	return ..()
```suggestion
		return TRUE
		
	return ..()
```

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +		return cell
```suggestion
```

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	return cell
You have two of the same proc, I am not sure if you want to use this version of the proc or the one before.

2023-07-17 03:42 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +		QDEL_NULL(cell)
```suggestion
		QDEL_NULL(cell)
		
```

2023-07-18 01:44 UTC, softcerv commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	return ..()
```suggestion
	return
```

2023-07-20 05:48 UTC, Nerev4r commented
undrafting tmrw in anticipation of spritework

2023-07-28 18:28 UTC, GoldenAlpharex requested changes
I like this thing.

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +
Document this proc, pretty please.
```suggestion
/obj/item/gravityharness/proc/toggle_mode(mob/user, voluntary)
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +///Changes the mode to `target_mode`, returns False if the mode cannot be changed
```suggestion
///Changes the mode to `target_mode`, returns `FALSE` if the mode cannot be changed
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +				new /obj/effect/temp_visual/mook_dust(get_turf(src))
```suggestion

			if(user.has_gravity())
				new /obj/effect/temp_visual/mook_dust(get_turf(src))

```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +			if(!user.has_gravity())
```suggestion

			if(!user.has_gravity())
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +				to_chat(user, span_notice("Your harness lets out a soft whine as your suspension field dissipates, gravity around you normalizing."))
```suggestion
				to_chat(user, span_notice("[src] lets out a soft whine as your suspension field dissipates, gravity around you normalizing."))
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +					to_chat(user, span_notice("Your harness lets out a soft whine as your suspension field dissipates, gravity around you normalizing."))
```suggestion
					to_chat(user, span_notice("[src] lets out a soft whine as your suspension field dissipates, gravity around you normalizing."))
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +/obj/item/gravityharness/proc/get_status_tab_item(mob/living/source, list/items)
Document this please.

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +/obj/item/gravityharness/Initialize(mapload)
Try to change the typepath into this everywhere, so it follows the `snake_case` conventions.
```suggestion
/obj/item/gravity_harness/Initialize(mapload)
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +/obj/item/gravityharness/Destroy()
By convention, we try to have the `Destroy()` proc at the start of the proc definitions of a new class, after `Initialize()`, so it's easy to validate.

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	if(harnesscell == current_cell)
```suggestion
/obj/item/gravity_harness/handle_atom_del(atom/harness_cell)
	if(harness_cell == current_cell)
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +		change_mode(MODE_GRAVOFF)
You also probably want to do `current_cell = null` here after the `change_mode` call, so we avoid hard-deletions.

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +	if(in_range(src,user) || isobserver(user))
```suggestion
	if(in_range(src, user) || isobserver(user))
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +				. += "The cell slot is empty, showing bare connectors."
It could be cool to have this using `span_warning()`.

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
> +		. += "The power meter shows [current_cell ? "[round(current_cell.percent(), 0.1)]%" : "!invalid!"] charge remaining."
```suggestion
		. += "The power meter shows [current_cell ? "<b>[round(current_cell.percent(), 0.1)]%</b> charge remaining." : "[span_warning("\"MISSING CELL\"")]"]"
```

2023-07-28 18:28 UTC, GoldenAlpharex commented on modular_skyrat/modules/cargo/code/goodies.dm
> +	While it's a pretty cheap bootleg of the personal gravitic engines in-use by the Skrell, this one's been fitted with straps and a basic storage module."
```suggestion
		While it's a pretty cheap bootleg of the personal gravitic engines used by the Skrell, this one's been fitted with straps and a basic storage module."
```

2023-07-29 19:42 UTC, GoldenAlpharex requested changes
Just one tiny change, also you've got merge conflicts now it seems.

2023-07-29 19:42 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/back/antigravityharness.dm
>  		mode = MODE_GRAVOFF
```suggestion
		mode = MODE_GRAVOFF

```

2023-07-29 20:10 UTC, GoldenAlpharex approved these changes
I reckon this should be good to go if the tests pass.

We can always change the price later if we feel like it's too cheap at the moment.

2023-07-29 20:24 UTC, merged