once more, as a joke - re-ports the proto-kinetic glaive
Skyrat-SS13/Skyrat-TG pull request #22626
Opened 2023-07-22 02:10 UTC by Hatterhat

## About The Pull Request
adds the proto-kinetic glaive to the mining vendor at 2250 points. has no performance changes compared to the regular crusher. looks cool.

original concept Citadel-Station-13/Citadel-Station-13#13003 (there i am, gary!)
resprite from Citadel-Station-13/Citadel-Station-13#15773

## How This Contributes To The Skyrat Roleplay Experience
it doesn't but hey at least it looks neat
## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/07034bb3-9601-4213-91c2-1a6d0f0ab432)

</details>

## Changelog

:cl:
add: A shipment of proto-kinetic glaives has found its way into the warehouses that feed the mining vendors. Prospective users are advised that these glaives have no differences in performance compared to their more axe-slash-club-like companions.
/:cl:

2023-07-23 12:40 UTC, kittysmooch commented
can it pretty please be a roundstart alt or reskin of the crusher :face_holding_back_tears:

2023-07-23 14:56 UTC, SpaceVampire commented
If it is going to be exactly the same as a crusher in function, having work as a reskin option seems like it would make more sense.

2023-07-25 21:55 UTC, GoldenAlpharex requested changes
I'm cool with a reskin, but I'd rather have it be using the actual reskin system that we already have in-game, rather than something obscure like hitting a vendor with it.

2023-07-26 10:01 UTC, Iamgoofball commented
👎 
needs to include an option to backflip into chasms during megafauna fights

2023-07-28 18:35 UTC, GoldenAlpharex requested changes
Only change I have left.

2023-07-28 18:35 UTC, GoldenAlpharex commented on modular_skyrat/modules/mining_vendor_additions/code/order_mining.dm
> +		into a high-tech knife on a stick with a handguard and goliath-leather grip. While equally as effective as its unmodified compatriots, \
```suggestion
			into a high-tech knife on a stick with a handguard and goliath-leather grip. While equally as effective as its unmodified compatriots, \
```

2023-07-28 19:56 UTC, GoldenAlpharex approved these changes
Should be good to go!

2023-07-29 19:35 UTC, merged