Allows PAI range restrictions to be toggled on/off
Skyrat-SS13/Skyrat-TG pull request #22624
Opened 2023-07-21 20:15 UTC by vinylspiders

## About The Pull Request

New setting to enable or disable the 'leash' on the PAI. It starts disabled, allowing PAI's to roam freely by default as they were previously able to. The leash can be activated at will and will yoink the holoform back to you once enabled if the PAI is outside its specified range.

## How This Contributes To The Skyrat Roleplay Experience

Leaves whether or not to leash their PAIs up to the player.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![firefox_48qvNvriKQ](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/e540fc95-bb21-42b1-83e7-53fdc08bc35d)

</details>

## Changelog

:cl:
qol: made whether or not to leash your PAI a toggle in the PAI card menu, off by default. the leash can be toggled on or off at will, giving an option to allow PAIs to roam freely or stick within a specified range.
qol: also bumps the max range for the leash up to 25 (from 9 previously)
/:cl:

2023-07-21 20:21 UTC, GoldenAlpharex requested changes
Minor nitpicks.

2023-07-21 20:21 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/pai/card.dm
> +		return TRUE
```suggestion

	if(pai && action == "toggle_leash")
		pai.toggle_leash()
		return TRUE

```

2023-07-21 20:21 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/pai/pai.dm
> +	to_chat(src, span_warning("Your leash has been [leashed ? "activated" : "deactivated"]!"))
```suggestion
	to_chat(src, span_warning("Your virtual leash has been [leashed ? "activated" : "deactivated"]!"))
```

2023-07-22 05:32 UTC, Gandalf2k15 approved these changes
Ok

2023-07-22 05:32 UTC, merged