[MODULAR] Fixes custom tongues not getting the right food preferences/hemophage abilities
Skyrat-SS13/Skyrat-TG pull request #22664
Opened 2023-07-24 20:46 UTC by vinylspiders

## About The Pull Request

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/22487

Augmented tongues will now inherit traits (like hemophage blood drain, species-specific foot preferences) from the original tongue. This fixes a bug where you could be unable to blood drain as a hemophage with a custom tongue, as well as other issues from the organs not being marked as 'corrupted'.

## How This Contributes To The Skyrat Roleplay Experience

Fixes a bug/oversight.

## Proof of Testing

<details>
<summary>Hemophage with a forked tongue can now function again</summary>
  
![dreamseeker_E7snyLacuq](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/84416e8a-d5d8-4a28-8904-325bd62368c9)

</details>

## Changelog

:cl:
fix: fixes food preferences not applying correctly to augmented and quirk-granted tongues.
/:cl:

2023-07-24 21:02 UTC, GoldenAlpharex commented on modular_skyrat/modules/organs/code/organs.dm
> +		organ_flags |= ORGAN_TUMOR_CORRUPTED
This shouldn't be needed, and will only conflict with my Hemophage refactor that's currently up, addressing this issue in particular.

Feel free to give it a glance and leave a review if you feel like it, however. https://github.com/Skyrat-SS13/Skyrat-tg/pull/22625

2023-07-24 21:03 UTC, GoldenAlpharex requested changes

2023-07-24 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/organs/code/tongue.dm
> +	liked_foodtypes = old_tongue.liked_foodtypes
```suggestion
	liked_foodtypes = old_tongue.liked_foodtypes
	disliked_foodtypes = old_tongue.disliked_foodtypes
	toxic_foodtypes = old_tongue.toxic_foodtypes
```

2023-07-24 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm
> -#undef ORGAN_TUMOR_CORRUPTED
Leave that there, it's only going to cause conflicts otherwise, I reckon.

2023-07-24 21:14 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/hemophage.dm
> -#undef ORGAN_TUMOR_CORRUPTED
Gotcha

2023-07-24 21:14 UTC, vinylspiders commented on modular_skyrat/modules/organs/code/organs.dm
> +		organ_flags |= ORGAN_TUMOR_CORRUPTED
Sounds good to me--I will remove this bit then.

2023-07-25 21:44 UTC, GoldenAlpharex requested changes

2023-07-25 21:44 UTC, GoldenAlpharex commented on modular_skyrat/modules/organs/code/organs.dm
> +		add_item_action(action.type)
This might not be necessary, and might actually cause issues with Hemophage's tongues, once my refactor goes through.

2023-07-25 21:46 UTC, vinylspiders commented on modular_skyrat/modules/organs/code/organs.dm
> +		add_item_action(action.type)
Alright, I'll make it something that can be toggled if necessary then

2023-07-28 20:15 UTC, GoldenAlpharex requested changes

2023-07-28 20:15 UTC, GoldenAlpharex commented on modular_skyrat/modules/organs/code/tongue.dm
> +/obj/item/organ/internal/tongue/copy_traits_from(obj/item/organ/internal/tongue/old_tongue)
```suggestion
/obj/item/organ/internal/tongue/copy_traits_from(obj/item/organ/internal/tongue/old_tongue, copy_actions = FALSE)
```

2023-07-29 19:34 UTC, GoldenAlpharex approved these changes
Looking good!

2023-07-29 19:35 UTC, merged