A tail of Australian Shepherd tails and Harpy Wings (new sprites)
Skyrat-SS13/Skyrat-TG pull request #22712
Opened 2023-07-27 00:31 UTC by MortoSasye

## About The Pull Request

Adds a new canid tail, inspired by Australian Shepherds with theirs still on them, with a wagging tail animation.

Adds a new set of harpy wings, with a top overlay, that's been modified to allow most clothes to show on the arms without removing the feathers overlay.

## How This Contributes To The Skyrat Roleplay Experience

There was no similar canid tail in the options, and none of the harpy wings had a similar design to the one provided.

## Proof of Testing

<details>
<summary>Australian Shepherd Tail:

https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/e56ef8d8-beb0-4051-83e7-94e066185f32
![Screenshot 2023-07-26 195058](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/726fbd0b-b299-48e7-96c5-b029ef157d0a)
![Screenshot 2023-07-26 195107](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/7028318d-8a45-4f98-81a4-3a52b42fc2ae)
![Screenshot 2023-07-26 195112](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/fb7b550a-8f91-47b0-9696-9cb360d7dcde)

Arfel Harpy Wings:
![Screenshot 2023-07-26 192959](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/1a497c77-3195-4f25-b439-dd66dbec1c15)
![Screenshot 2023-07-26 193005](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/ae41321e-210a-4fb8-bb80-25fdb2eb90c6)
![Screenshot 2023-07-26 193014](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/1ab9ef85-a8a5-44d9-8dbf-37f8ab9b54c5)

With clothes:
![Screenshot 2023-07-26 193054](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/f6363e2a-60b3-4d06-82e0-36dbb085cd84)
![Screenshot 2023-07-26 193059](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/a077d8cc-ce30-4012-838b-223ae06653b8)
![Screenshot 2023-07-26 193105](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/a8073f03-8eab-4563-92e0-8033f14caa20)

With markings plain in arms and hands:
![Screenshot 2023-07-26 193259](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/bebb3952-4f1a-4c3f-9c69-58e37438c8bb)
![Screenshot 2023-07-26 193304](https://github.com/Skyrat-SS13/Skyrat-tg/assets/38175176/4f1ad28b-25bf-49a1-a4b5-9f6f624aece8)

</summary>
  
</details>

## Changelog

:cl:MortoSasye (Mystral Mom)
add: Two new sets of cosmetic sprites are now available: Arfel Harpy Wings and Australian Shepherd tail. Enjoy, new harpies and canids players.
/:cl:

2023-07-28 19:27 UTC, GoldenAlpharex requested changes

2023-07-28 19:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
> +/datum/sprite_accessory/tails/mammal/wagging/australianshepherd
```suggestion
/datum/sprite_accessory/tails/mammal/wagging/australian_shepherd
```

2023-07-28 19:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/wings.dm
> +/datum/sprite_accessory/wings/mammal/top/arfelharpy
```suggestion
/datum/sprite_accessory/wings/mammal/top/arfel_harpy
```

2023-07-28 19:27 UTC, GoldenAlpharex commented on modular_skyrat/master_files/icons/mob/sprite_accessory/tails.dmi
For this, the wag animation on the side views is far longer than the one from the front or the back. It also has a weird frame jump when it goes "behind" the character, where it goes from like, 45° to 90° in one frame, as opposed to being smoother like the rest.

As much as possible, animations should correspond between directions, _especially_ when it comes to the length/number of frames of the animation.

2023-07-28 19:44 UTC, MortoSasye commented on modular_skyrat/master_files/icons/mob/sprite_accessory/tails.dmi
Got it, will fix it one of these days!

2023-08-03 23:27 UTC, MortoSasye commented on modular_skyrat/master_files/icons/mob/sprite_accessory/tails.dmi
Changes done! I also took advantage of the situation and adjusted the shading of everything.

2023-08-11 13:30 UTC, vinylspiders submitted a review, later dismissed
Couple things:

1) Make sure you doc the Shark tail changes and Akula tail removal. And speaking of the second, if you are removing the sprites you'll want to get rid of this too (or else the 'Akula' tail selection in char prefs will lead to an invisible tail).

https://github.com/Skyrat-SS13/Skyrat-tg/blob/78795c33c7417d3268b307fe3c5b0271472640e2/modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm#L312-L314

2) The sprites look good to me but with

`m_waggingtail_shark_BEHIND_primary` and `m_waggingtail_sharknofin_BEHIND_primary`

the modified shark tail sprites still have some abrupt frame shifts. edit: I realize those were there with the originals too so if you can't fix it that's okay. But if you want to:

See what I mean <details><summary> here (you can see the skipping -- 1st and 3rd ones down)</summary> 

![firefox_wUuVSQZGMC](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/2912e2c9-82ed-42ef-85c9-b77a2b64ded3) 

</details>

Definitely address 1) though, and if you know how to fix the screenshot test that'd be great as well but if not I'll take care of it.

2023-08-11 23:02 UTC, MortoSasye commented
> Couple things:
> 
> 1. Make sure you doc the Shark tail changes and Akula tail removal. And speaking of the second, if you are removing the sprites you'll want to get rid of this too (or else the 'Akula' tail selection in char prefs will lead to an invisible tail).
> 
> https://github.com/Skyrat-SS13/Skyrat-tg/blob/78795c33c7417d3268b307fe3c5b0271472640e2/modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm#L312-L314
> 
> 2. The sprites look good to me but with
> 
> `m_waggingtail_shark_BEHIND_primary` and `m_waggingtail_sharknofin_BEHIND_primary`
> 
> the modified shark tail sprites still have some abrupt frame shifts. edit: I realize those were there with the originals too so if you can't fix it that's okay. But if you want to:
> 
> See what I mean
> 
> here (you can see the skipping -- 1st and 3rd ones down)
> Definitely address 1) though, and if you know how to fix the screenshot test that'd be great as well but if not I'll take care of it.

I didn't even notice I removed anything...

2023-08-11 23:30 UTC, vinylspiders commented
> > Couple things:
> > 
> > 1. Make sure you doc the Shark tail changes and Akula tail removal. And speaking of the second, if you are removing the sprites you'll want to get rid of this too (or else the 'Akula' tail selection in char prefs will lead to an invisible tail).
> > 
> > https://github.com/Skyrat-SS13/Skyrat-tg/blob/78795c33c7417d3268b307fe3c5b0271472640e2/modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm#L312-L314
> > 
> > 
> > 2. The sprites look good to me but with
> > 
> > `m_waggingtail_shark_BEHIND_primary` and `m_waggingtail_sharknofin_BEHIND_primary`
> > the modified shark tail sprites still have some abrupt frame shifts. edit: I realize those were there with the originals too so if you can't fix it that's okay. But if you want to:
> > See what I mean
> > here (you can see the skipping -- 1st and 3rd ones down)
> > Definitely address 1) though, and if you know how to fix the screenshot test that'd be great as well but if not I'll take care of it.
> 
> I didn't even notice I removed anything...
> 
> Edit: I don't see the changes at all myself, nor did my husband. I'm very new to this whole coding business though so maybe I didn't even find out I did the edit in a wrong file? I asked for help over at the discord channel too.

Ah was a misunderstanding then! We spoke on discord, but to reiterate all you have to do is update your tails.dmi to have the missing Akula tail sprites that got added after this PR was started and this should be good to go as far as I can tell.

2023-08-12 13:39 UTC, GoldenAlpharex approved these changes
Yeah sure, looks good to me now.

2023-08-12 13:39 UTC, merged