Adds a new crutch item to the loadout menu and medbay vendor.
Skyrat-SS13/Skyrat-TG pull request #22788
Opened 2023-07-30 20:38 UTC by Jfrost6

## About The Pull Request
adds a new medical crutch item as a subtype of cane which is obtainable through the loadout inhand slot, the medbay vendor, and crafting. It has no function beyond RP unless the cane gets some use

## How This Contributes To The Skyrat Roleplay Experience
With [this PR](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22097#issue-1777456271l) crew can now start without a leg but the only items that stop them from hopping around on one leg are the cane and white cane, both of which aren't meant for it unlike a crutch.

## Proof of Testing

<details>
https://imgur.com/a/l4JhODW
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl: Divibee
add: Crutch sprites and item.
/:cl:

2023-07-30 21:04 UTC, lessthnthree approved these changes

2023-07-30 21:09 UTC, softcerv requested changes
This adds some nice flavor, but there are some technical issues we need to resolve before we can look into getting this merged.

2023-07-30 21:09 UTC, softcerv commented on code/game/objects/items/weaponry.dm
> +	w_class = WEIGHT_CLASS_SMALL
```suggestion
```
We don't need this because these stats are already inherited from the cane. (Unless you planned on changing them.)

2023-07-30 21:09 UTC, softcerv commented on code/modules/vending/medical.dm
> +		/obj/item/cane/crutch = 4,
There's a non-modular way that you can do this. Move this change to the `modular_skyrat\modules\modular_vending\code\medical.dm` file and have it be a skyrat product,

2023-07-30 21:09 UTC, softcerv commented on code/modules/vending/medical.dm
> +		/obj/item/cane/crutch = 4,
Same with this. Please ask in `#development-code` if you need help figuring it out.

2023-07-30 21:09 UTC, softcerv commented on code/game/objects/items/stacks/rods.dm
> +	new/datum/stack_recipe("crutch", /obj/item/cane/crutch, 3, time = 10, one_per_turf = FALSE, category = CAT_TOOLS), \
Please move this over to the `skyrat_rod_recipes` list in  `modular_skyrat\master_files\code\game\objects\items\stacks\sheets\sheet_types.dm`

2023-07-30 21:09 UTC, softcerv commented on code/game/objects/items/weaponry.dm
> +
You are going to want to move this to a modular file. I'd recommend creating a new file for the crutch at `modular_skyrat\modules\customization\game\objects\items\devices` and have the code moved there

2023-07-30 21:09 UTC, softcerv commented on icons/obj/weapons/staff.dmi
You are going to want to move the icons from these to a modular icon file, you could probably make one at `modular_skyrat\master_files\icons\obj` and have it be named `staff.dmi`

2023-07-30 21:09 UTC, softcerv commented on icons/mob/inhands/weapons/melee_lefthand.dmi
Again, you are going to want to move the sprites you added in this and `melee_righthand.dmi`, into modular icon files, `modular_skyrat\master_files\icons\mob\inhands` would be a good directory for the new `melee_lefthand` and `melee_righthand` files you are going to make.

2023-07-30 21:46 UTC, Jfrost6 commented on icons/mob/inhands/weapons/melee_lefthand.dmi
Make a new file for each hand and the ground sprite?

2023-07-30 22:30 UTC, Jfrost6 commented
getting errors due to the path not being correct anymore, and i need to test it still.

2023-07-30 22:32 UTC, lessthnthree commented
> getting errors due to the path not being correct anymore, and i need to test it still.

[modular_skyrat/modules/customization/game/objects/items/devices/crutch](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22788/files#diff-7a3a170678bc59114d150b7be3a4970529bf0169e8ad1536cabf7d458493cb3c) is missing a .dm extension and not added to tgstation.dme

2023-07-30 23:12 UTC, Jfrost6 commented
[Proof](https://imgur.com/a/Q49zVsE) that I've tested it after modularizing everything.

2023-07-31 03:11 UTC, Nerev4r commented
add it to the prop summoner NIFsoft :joker:

2023-07-31 16:25 UTC, softcerv reviewed
I can't give approval, but this looks good from a code perspective now.

2023-07-31 16:25 UTC, softcerv commented on modular_skyrat/modules/customization/game/objects/items/devices/crutch.dm
> +	attack_verb_simple = list("bludgeon", "whack", "thrash")
```suggestion
/obj/item/cane/crutch
	name = "crutch"
	desc = "A crutch usually employed by those recovering from a leg injury."
	icon = 'modular_skyrat/master_files/icons/obj/staff.dmi'
	icon_state = "crutch"
	inhand_icon_state = "crutch"
	lefthand_file = 'modular_skyrat/master_files/icons/mob/inhands/melee_lefthand.dmi'
	righthand_file = 'modular_skyrat/master_files/icons/mob/inhands/melee_righthand.dmi'
	custom_materials = list(/datum/material/iron = SMALL_MATERIAL_AMOUNT * 6)
	attack_verb_continuous = list("bludgeons", "whacks", "thrashes")
	attack_verb_simple = list("bludgeon", "whack", "thrash")
	
```

2023-08-01 15:44 UTC, lessthnthree approved these changes

2023-08-01 19:34 UTC, softcerv approved these changes

2023-08-01 19:46 UTC, merged