Ghost Cafe Unradioing Vol. 4
Skyrat-SS13/Skyrat-TG pull request #22822
Opened 2023-08-01 21:32 UTC by YakumoChen

## About The Pull Request

Removes the radio stock from the ghost cafe vendors. Again.

## How This Contributes To The Skyrat Roleplay Experience

blah blah blah

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/10399117/8f637830-2c1d-49e8-884f-990be78611db)

</details>

## Changelog

:cl:
fix: Once more, ghosts in the cafe cannot use vendor radios to communicate with the living.
/:cl:

2023-08-01 22:54 UTC, vinylspiders requested changes

2023-08-01 22:54 UTC, vinylspiders commented on _maps/map_files/generic/CentCom_skyrat_z2.dmm
> +/obj/machinery/vending/wardrobe/chap_wardrobe/ghost_cafe,
```suggestion
/obj/machinery/vending/wardrobe/chap_wardrobe/unholy/ghost_cafe,
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
```suggestion
/obj/machinery/vending/wardrobe/chap_wardrobe/unholy/ghost_cafe/Initialize(mapload)
	for(var/typepath as anything in products)
		if(ispath(typepath, /obj/item/radio/headset))
			products.Remove(typepath)
	return ..()
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
```suggestion
/obj/machinery/vending/wardrobe/gene_wardrobe/ghost_cafe/Initialize(mapload)
	for(var/typepath as anything in products)
		if(ispath(typepath, /obj/item/radio/headset))
			products.Remove(typepath)
	return ..()
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
```suggestion
/obj/machinery/vending/wardrobe/chem_wardrobe/ghost_cafe/Initialize(mapload)
	for(var/typepath as anything in products)
		if(ispath(typepath, /obj/item/radio/headset))
			products.Remove(typepath)
	return ..()
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
```suggestion
/obj/machinery/vending/wardrobe/viro_wardrobe/ghost_cafe/Initialize(mapload)
	for(var/typepath as anything in products)
		if(ispath(typepath, /obj/item/radio/headset))
			products.Remove(typepath)
	return ..()
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
```suggestion
/obj/machinery/vending/wardrobe/robo_wardrobe/ghost_cafe/Initialize(mapload)
	for(var/typepath as anything in products)
		if(ispath(typepath, /obj/item/radio/headset))
			products.Remove(typepath)
	return ..()
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
```suggestion
/obj/machinery/vending/wardrobe/hydro_wardrobe/ghost_cafe/Initialize(mapload)
	for(var/typepath as anything in products)
		if(ispath(typepath, /obj/item/radio/headset))
			products.Remove(typepath)
	return ..()
```

2023-08-01 22:54 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	)
I am really not a fan of the copy pasted hardcoded products lists. Whenever upstream changes something these will be out of date.

A better way would be to just remove headsets and their subtypes programmatically like this.

2023-08-02 06:01 UTC, YakumoChen commented
I guess I'll just do that for every vendor in the cafe

2023-08-02 06:58 UTC, vinylspiders requested changes

2023-08-02 06:58 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	return ..()
```suggestion
/// Removes given list of products. Must be called before build_inventory() to actually prevent the records from being created.
/obj/machinery/vending/proc/remove_products(list/paths_to_remove)
	if(!length(paths_to_remove))
		return
	for(var/typepath as anything in products)
		for(var/to_remove as anything in paths_to_remove)
			if(ispath(typepath, to_remove))
				products.Remove(typepath)

/obj/machinery/vending/
	/// list of products to exclude when building the vending machine's inventory
	var/list/excluded_products

/obj/machinery/vending/Initialize(mapload)
	remove_products(excluded_products)
	return ..()

/obj/machinery/vending/wardrobe/science_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/bar_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/chef_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/medi_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/engi_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/law_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/jani_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/coroner_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/curator_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)
/obj/machinery/vending/wardrobe/chap_wardrobe/unholy/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/gene_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/chem_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/viro_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/robo_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

/obj/machinery/vending/wardrobe/hydro_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)
```

2023-08-02 06:58 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
> +	return ..()
Sorry-one more thing. Looking at this again, might as well make a proc to do this while we're at it. That way anyone who wants to do this in the future can just add a path to the `excluded_products` list and it will just be taken care of for them.

2023-08-02 07:16 UTC, vinylspiders commented
> I guess I'll just do that for every vendor in the cafe

Yeah due to the way inheritance works unfortunately there's no real good way around it in this case. There's nowhere to really insert a ghost_cafe vending machine subtype without it losing all the properties of its parent vending machine, which means inevitabe copy pasta. But I think it's been mitigated as best as it can be at least.

2023-08-02 07:17 UTC, vinylspiders approved these changes

2023-08-02 07:26 UTC, vinylspiders requested changes
Pff forgot one.

2023-08-02 07:26 UTC, vinylspiders commented on modular_skyrat/modules/modular_vending/code/wardrobes.dm
```suggestion

/obj/machinery/vending/wardrobe/cargo_wardrobe/ghost_cafe
	excluded_products = list(
		/obj/item/radio/headset,
	)

```

2023-08-02 07:27 UTC, vinylspiders approved these changes

2023-08-02 08:09 UTC, lessthnthree approved these changes

2023-08-02 08:09 UTC, merged