[MIRROR] pAIs can be inserted into a MODsuit [MDB IGNORE]
Skyrat-SS13/Skyrat-TG pull request #22852
Opened 2023-08-03 09:01 UTC by SkyratBot

Original PR: https://github.com/tgstation/tgstation/pull/77212
--------------------
## About The Pull Request

Ressurects this old concept from (#64530), if we're making pAIs conform to being personal assistants more often then they should be better at assisting your person.

You can insert a pAI into a MODsuit simply by using the card on a MODsuit with an open panel. You can eject it again from the MODsuit control panel UI (though the maintenance panel still needs to be unscrewed).

Inserted pAIs can:
- Deploy and undeploy suit parts.
- Turn the suit on and off.
- Monitor any stats on the MODsuit panel.
- Activate any of your suit actions.

Inserted pAIs cannot:
- Move the suit.

This does not remove the ability to place AIs into your suit. AIs can do all of the above but can _also_ move the suit around while you are critically injured.
You can't have _both_ an AI and a pAI in your suit at the same time.

Additionally I had to mess around with the backend for pinning actions a little bit.
AIs who tried to pin MODsuit actions to their screen would pin them to the UI of the person wearing the suit instead, because it passed through `grant_item_action`. We _want_ to use that interface for the other stuff it does, but we need to catch and override who is _actually_ being granted the action so it goes to the person who pinned it rather than the person wearing the suit.

## Why It's Good For The Game

Gives more things for your pAI to do, now you can delegate manging some suit functions to your little buddy.

## Changelog

:cl:
add: pAIs can be inserted into MODsuits and can control suit modules (but are not capable of moving the suit).
fix: AIs/pAIs in MODsuits can properly pin actions
/:cl:

2023-08-05 21:26 UTC, GoldenAlpharex approved these changes
Should _hopefully_ be good to go!

2023-08-06 07:26 UTC, vinylspiders requested changes
~~Unrelated to the other suggestions~~ (see final review comment) the pai is not getting the actions for some reason. They were being granted before the last two commits. 

Not sure if it's broken upstream or if it's something here.

2023-08-06 07:26 UTC, vinylspiders commented on code/modules/mod/mod_control.dm
> +		// SKYRAT EDIT END
```suggestion
```

2023-08-06 07:26 UTC, vinylspiders commented on code/modules/mod/mod_control.dm
>  			. += span_notice("You could install a pAI with a <b>pAI card</b>.")
```suggestion
		if(isnull(ai_assistant))
			. += span_notice("You could install a pAI with a <b>pAI card</b>.") // SKYRAT EDIT CHANGE - ORIGINAL: . += span_notice("You could install an AI or pAI using their <b>storage card</b>.")
		else if(isAI(ai_assistant))
			. += span_notice("You could remove [ai_assistant] with an <b>intellicard</b>.")
```

2023-08-06 07:26 UTC, vinylspiders commented on code/game/gamemodes/objective_items.dm
>  		var/obj/item/mod/control/suit = potential_storage
```suggestion
	else if(istype(potential_storage, /obj/item/mod/control))
		var/obj/item/mod/control/suit = potential_storage
```

2023-08-06 07:26 UTC, vinylspiders commented on code/game/gamemodes/objective_items.dm
>  	*/ // SKYRAT REMOVAL END
```suggestion
```

2023-08-06 07:28 UTC, vinylspiders commented on code/modules/mod/mod_control.dm
> +		// SKYRAT EDIT END
Don't need this anymore

2023-08-06 07:28 UTC, vinylspiders commented on code/modules/mod/mod_control.dm
>  			. += span_notice("You could install a pAI with a <b>pAI card</b>.")
<details><summary>This is a dupe </summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/cf4baf01-03b2-4c85-a8c9-4883a602d7ff)

</details>

2023-08-06 07:29 UTC, vinylspiders commented on code/game/gamemodes/objective_items.dm
>  		var/obj/item/mod/control/suit = potential_storage
Don't need this anymore, either since we are now potentially allowing AIs.

2023-08-06 07:30 UTC, vinylspiders commented on code/game/gamemodes/objective_items.dm
>  	*/ // SKYRAT REMOVAL END
See above

2023-08-06 07:38 UTC, vinylspiders submitted a review, later dismissed

2023-08-06 07:38 UTC, vinylspiders commented on code/modules/mod/mod_control.dm
>  	)
```suggestion
		/datum/action/item_action/mod/deploy/ai,
		/datum/action/item_action/mod/activate/ai,
		/datum/action/item_action/mod/panel/ai,
		/datum/action/item_action/mod/module/ai,
	)
```

2023-08-06 07:38 UTC, vinylspiders commented on code/modules/mod/mod_control.dm
>  	)
Ah here's why the actions weren't being granted. They were removed.

2023-08-07 21:07 UTC, GoldenAlpharex commented on code/modules/mod/mod_control.dm
> +		// SKYRAT EDIT END
This was kept because I purposefully tried to keep it so that AIs still can't be inserted in MODsuits down here, for now at least.

2023-08-07 21:08 UTC, GoldenAlpharex commented on code/modules/mod/mod_control.dm
>  	)
Ah whoops, yeah that'd be why.

2023-08-07 21:10 UTC, GoldenAlpharex approved these changes
Should be good for a test-merge now.

2023-08-08 03:05 UTC, Krypandenej commented
Hasn't this already a thing for the longest time? You can just unscrew your suit and slap that card in.

2023-08-08 14:55 UTC, CandleJaxx commented
does this add back in ais being able to be in modsuits?

2023-08-08 22:14 UTC, GoldenAlpharex commented
> does this add back in ais being able to be in modsuits?

For now, no. I didn't want to make a change to that in a mirror PR, as it'd otherwise be basically a stealth balance change.

2023-08-08 22:23 UTC, GoldenAlpharex approved these changes
Haven't heard of anything, so let's get it rolling.

2023-08-08 22:24 UTC, merged