Acrador snouts and ears
Skyrat-SS13/Skyrat-TG pull request #22942
Opened 2023-08-08 13:47 UTC by ReezeBL

## About The Pull Request

Added sprites for snouts and ears of Acradors and opportunity to choose them in character editor. Ref: https://media.discordapp.net/attachments/1109178981720264839/1136290629895327805/image-259.png

## How This Contributes To The Skyrat Roleplay Experience

Players will have better variety of snouts and ears to choose from. And Acradors are cool too.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6696374/fab1c639-f5a7-45fb-8f0e-649fb3c79c92)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6696374/614f35a1-04a2-458f-9ea7-37bf65dfd3b2)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6696374/8eeb668b-b230-4390-b5de-33453aad9d8e)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6696374/bc0a1c34-038d-4ca9-aae8-cf8c78590464)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6696374/73a4a5f1-4c6e-4aae-a8e6-17650ee91814)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6696374/c1ba67c1-0b94-413a-936a-d355a8c98f1a)

</details>

## Changelog

:cl:
image: added 2 ear's sprites and 1 snout's sprite
/:cl:

2023-08-09 14:03 UTC, EerieDream commented
Genuinely surprised to see Acradors get some love. This looks VERY good!

2023-08-10 17:52 UTC, vinylspiders requested changes
This will fix the linters failure

2023-08-10 17:52 UTC, vinylspiders commented on tgstation.dme
> +#include "interface\skin.dmf"
```suggestion
```

2023-08-10 17:52 UTC, vinylspiders commented on tgstation.dme
>  #include "interface\fonts\vcr_osd_mono.dm"
```suggestion
#include "interface\fonts\vcr_osd_mono.dm"
#include "interface\skin.dmf"
```

2023-08-10 17:53 UTC, vinylspiders requested changes

2023-08-10 17:53 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/acradors.dm
> +
```suggestion
```

2023-08-11 06:50 UTC, ReezeBL commented
> This will fix the linters failure

It was very nice, I should have checked the changes in dme file :3

2023-08-11 12:04 UTC, vinylspiders approved these changes

2023-08-11 18:54 UTC, GoldenAlpharex requested changes

2023-08-11 18:54 UTC, GoldenAlpharex commented on modular_skyrat/master_files/icons/mob/sprite_accessory/acrador_snout_ears.dmi
You left an "angled" version of these ears in the dmi, would you mind taking that out of the DMI if it's unused?

2023-08-11 18:54 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/acradors.dm
Please put the snout in `snout.dm` and the ears in `ears.dm`, in the same folder you created this file into.

Your first snout (the one without the `/short`) might also be missing an icon_state, no need to make a `/short` subtype if you don't have a non-short version. Just merge the subtype into its parent.

2023-08-17 17:22 UTC, GoldenAlpharex requested changes

2023-08-17 17:22 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/acradors.dm
You still haven't moved the contents of this file (the code, not the sprites) into the proper code files, as outlined in my previous requested changes.

2023-08-17 19:25 UTC, ReezeBL commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/sprite_accessories/acradors.dm
ah, i see. didnt understand this first time

2023-08-18 06:32 UTC, ReezeBL commented
i wont ever work with git right after waking up  =(

2023-08-25 21:45 UTC, GoldenAlpharex approved these changes
Should be good now, I'd say.

2023-08-25 21:48 UTC, GoldenAlpharex commented
Just had to update to make sure your DMI wasn't broken, we seem to be good.

2023-08-30 20:20 UTC, merged