Fix airlock lighting
Skyrat-SS13/Skyrat-TG pull request #22977
Opened 2023-08-10 07:06 UTC by lessthnthree

## About The Pull Request

Fixes airlock lighting. Name your args!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/83487515/42d17f7c-2da0-4a8c-b8c9-3775bb69b3a7

</details>

## Changelog

:cl: LT3
fix: Airlock lighting works again
/:cl:

2023-08-10 07:11 UTC, softcerv reviewed
Yeah, this looks fine.

2023-08-10 10:34 UTC, vinylspiders requested changes

2023-08-10 10:34 UTC, vinylspiders commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
> +				filler.set_light(l_range = pre_light_range, l_power = pre_light_power, l_color = pre_light_color, l_on = TRUE)
```suggestion
				filler.set_light(l_range = pre_light_range, l_power = pre_light_power, l_color = pre_light_color, l_on = TRUE)
		else
			set_light(0)
```

2023-08-10 10:34 UTC, vinylspiders commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
> +				filler.set_light(l_range = pre_light_range, l_power = pre_light_power, l_color = pre_light_color, l_on = TRUE)
I don't see the light being turned off anywhere, shouldn't we add this too?

2023-08-10 10:37 UTC, vinylspiders commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
>  		lights_overlay = ""
```suggestion
		set_light(0)
		lights_overlay = ""
```

2023-08-10 10:37 UTC, vinylspiders commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
>  		lights_overlay = ""
Same thing here

2023-08-10 12:05 UTC, GoldenAlpharex requested changes

2023-08-10 12:05 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/airlock/code/airlock.dm
> +				filler.set_light(l_range = pre_light_range, l_power = pre_light_power, l_color = pre_light_color, l_on = TRUE)
I'd think so yeah.

2023-08-10 17:40 UTC, vinylspiders approved these changes

2023-08-11 18:06 UTC, GoldenAlpharex approved these changes
Amazing work, thank you!

2023-08-11 18:06 UTC, merged