Fixes .416 Stabilis tranquilizer bullets. They put you to sleep once again [MDB IGNORE]
Skyrat-SS13/Skyrat-TG pull request #22993
Opened 2023-08-10 12:27 UTC by Erol509

## About The Pull Request

They were being overriden somewhere with normal bullets, thats why they didnt work. I made another override in the folder called bulletbalance and hard codded their projectile. And thoes two simple things fixed it, the only problem remains with the description, but I dont know how to change it. 

## How This Contributes To The Skyrat Roleplay Experience

Fixes something that worked and stopped for some reason. 

## Proof of Testing

I will add it in a second

## Changelog

:cl:
fix: Fixes .416 stabilis tranquilizer bullets, they no longer kill you, but put you into sleep like they suposed to work.
/:cl:

2023-08-10 17:36 UTC, vinylspiders requested changes

2023-08-10 17:36 UTC, vinylspiders commented on modular_skyrat/modules/bulletrebalance/code/sniper.dm
> +	paralyze = 0
```suggestion
```

2023-08-10 17:36 UTC, vinylspiders commented on modular_skyrat/modules/bulletrebalance/code/sniper.dm
> +	paralyze = 0
You can just get rid of this since its the same as the parent type's

2023-08-10 17:46 UTC, vinylspiders approved these changes

2023-08-16 07:14 UTC, Tailiik commented
It was pretty funny to see someone test one of these and watch it blow an arm off instead of put them to sleep

2023-08-16 07:17 UTC, lessthnthree approved these changes

2023-08-16 07:18 UTC, merged