DS-2 QoL / Interdyne light fix
Skyrat-SS13/Skyrat-TG pull request #23006
Opened 2023-08-10 20:47 UTC by LovliestPlant

## About The Pull Request

This PR scoots the tube light in Interdyne's (both lavaland and icebox) cafeteria up by a tile. It is no longer floating above the kitchen counter. Additionally it replaces the sheet of plastitanium and plastitanium glass in DS-2's engine room with a stack of 20 plasteel sheets for use in upgrading DS-2's turbine rotor. Lastly it adds a packet of korta seeds to DS-2's permabrig, as a treat.

## How This Contributes To The Skyrat Roleplay Experience

The floating light looked a bit wonky, sits nicer on the wall.

DS-2 is currently unable to power itself, even under idle load, with it's roundstart turbine. Adding some plasteel will allow players to upgrade the area's turbine to T2, which is sufficient to meet base power needs.

Food options for lizards, moths, and other diet restricted species are pretty scarce in DS-2's permabrig. Average population being what it is there, it's not a given to have a chef to make food for prisoners. Adding some korta nuts to the mix will open up a wide range of possibilities for players who sign on as DS-2 hostages, and should make life a bit less frustrating.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Interdyne Lights
Before
![ID_before](https://github.com/Skyrat-SS13/Skyrat-tg/assets/107971606/1a4ade93-7627-4be1-b300-0000771e40a3)

After
![ID_Light](https://github.com/Skyrat-SS13/Skyrat-tg/assets/107971606/02bebf71-6723-4296-b36a-0409577370da)

DS-2 Engine Room
![DS_2-Plasteel](https://github.com/Skyrat-SS13/Skyrat-tg/assets/107971606/76715ff1-dee7-4edd-9d69-61ddba7a5fc6)

DS-2 Permabrig
![DS_2-Korta](https://github.com/Skyrat-SS13/Skyrat-tg/assets/107971606/fcdbc00f-cad2-4915-b07a-38b61729514e)

</details>

## Changelog

:cl:
qol: [DS-2] Replaces the pair of plastitatinum sheets with a small stack of plasteel in the engine room.
qol: [DS-2] Adds a korta seed packet to the botany box in the permabrig.
fix: [Interdyne] Fixes the floating tube light above the kitchen counter in the cafeteria.
/:cl:

2023-08-17 18:47 UTC, GoldenAlpharex requested changes
Outside of my one requested change, good changes!

2023-08-17 18:47 UTC, GoldenAlpharex commented on _maps/RandomRuins/SpaceRuins/skyrat/interdynefob.dmm
> +	atmos_chambers = list("syndieincinerator"="DS-2  Incinerator  Chamber");
I don't think this change is needed.
```suggestion
	atmos_chambers = list("syndieincinerator"="DS-2 Incinerator Chamber");
```

2023-08-18 17:08 UTC, LovliestPlant commented
After a bit more tinkering I've found that the turbine outlet also needs to be upgraded to reliably meet power needs. Added a stack of 20 titanium next to the plasteel for that task.

2023-08-31 08:05 UTC, vinylspiders commented
@GoldenAlpharex  good to go?

2023-09-06 01:52 UTC, GoldenAlpharex approved these changes

2023-09-06 01:52 UTC, merged