oh no it's a gun pr - adds the Scarborough Arms Enforcer-TEN, a 10mm handgun
Skyrat-SS13/Skyrat-TG pull request #23052
Opened 2023-08-13 14:41 UTC by Hatterhat

## About The Pull Request

Adds the Scarborough Arms `Enforcer-TEN` handgun to... uh, nowhere, at the time of writing. I'll probably put it in the OPFOR menu/uplink eventually. It has a cool animated empty indicator *and* a visibly changing safety indicator!

As It Stands:
- 40 damage per shot (c10mm base damage) (4 shots to down unarmored)
- 8 (+1) capacity (literally just uses the Ansem `(pistol/clandestine)`'s magazines)
- 12 force
- normal size

Tentative Uplink Stats Subject To Change When I Put It There:
- 10 TC for the gun itself
- 2 TC for any magazine (standard/AP/incendiary/hollowpoint)...?

## How This Contributes To The Skyrat Roleplay Experience
probably doesnt b/c shooting people isnt roleplay

## Why It's Good For The Game
adds a layer of force between the makarov (small 1911, 30 base damage) and the revolver (the designated "i am no longer role playing" handcannon, 60 damage)

makarov (30 damage) (5 shots to down raw)
This Gun (40 damage) (4 shots to down raw)
revolver (60 damage) (3 shots to down raw)

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![dreamseeker_2023-08-13_09-07-50-AM-Sunday](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/65895ece-c7da-4ed2-9cec-5e9b9ecc2ab0)

</details>

## Changelog

:cl:
add: Scarborough Arms is proud to announce that they're finally re-exporting the Enforcer-TEN 10mm handgun to their customers in the frontier; which is to say, not Nanotrasen. In the event that you see it, you should probably reconsider being in its general vicinity.
/:cl:

2023-08-14 22:56 UTC, Paxilmaniac commented
No GBP? Maintainers close this pr this instant.

2023-08-23 01:41 UTC, GoldenAlpharex requested changes
The color palette and the shading of the gun strike me as a little odd compared to what we already have in the game, no?

2023-08-23 01:41 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/pistol.dm
> +			. += "[icon_state]_safety-off"
```suggestion

	// safety indicator
	if(safety_indicator_overlay)
		var/datum/component/gun_safety/our_safety = GetComponent(/datum/component/gun_safety)
		. += "[icon_state]_safety-[our_safety.safety_currently_on ? "on" : "off"]"
```

2023-08-23 02:03 UTC, Hatterhat commented
> The color palette and the shading of the gun strike me as a little odd compared to what we already have in the game, no?

yeah that's fair i just couldn't think of anywhere else to steal a Big Chunky Handgun sprite from that... wasn't eris

2023-08-30 20:42 UTC, closed without merging