[WORK IN PROGRESS] [MODULAR] Razor Claws Augment
Skyrat-SS13/Skyrat-TG pull request #23050
Opened 2023-08-13 05:18 UTC by Nerev4r

## About The Pull Request
SOON:tm:

## How This Contributes To The Skyrat Roleplay Experience

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-08-14 08:22 UTC, tf-4 commented
In the loadout??? What

2023-08-14 08:44 UTC, tf-4 commented
This should be under illegal tech or something, and should like dismember your arm if you get emp'd

2023-08-14 16:10 UTC, Nerev4r commented
> This should be under illegal tech or something, and should like dismember your arm if you get emp'd

https://hackmd.io/cWFT8VmURrK_ro_dwPD4Iw

2023-08-15 00:48 UTC, RatFromTheJungle commented
> This should be under illegal tech or something, and should like dismember your arm if you get emp'd

that's very-extreme for something you can beat with an igniter, a battery, a rod, and some cable

2023-08-15 19:12 UTC, W4rd3nn commented
gimme more these r epic

2023-08-15 19:21 UTC, CandleJaxx commented
this design doc is incredible and i'd love to see more horizontal progression instead of straight upgrades, like this is allowing for, it's very fun

2023-08-17 16:54 UTC, SpaceLoveSs13 commented
The cyberimplant is fine, but I dont think the augments should be readily available from roundstart. It is supposed to give meaingful items to spend one's quirck balance according to your doc, but handing them over an actual weapon seems a bit much in my opinion.

2023-08-17 18:10 UTC, Nerev4r commented
> The cyberimplant is fine, but I dont think the augments should be readily available from roundstart. It is supposed to give meaingful items to spend one's quirck balance according to your doc, but handing them over an actual weapon seems a bit much in my opinion.

Its equivalent to a kitchen knife, which you can print literal hundreds of within minutes of roundstart.

2023-08-17 21:09 UTC, CandleJaxx commented
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ Valve, ░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

2023-08-17 22:32 UTC, GoldenAlpharex requested changes
I feel like the sharpened ones will probably need to be made contraband, one way or the other, since they're just so easy to conceal and all, and end up being quite nasty, all things considered, even if mostly against unarmed civilians.

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/game/objects/items/scratchingstone.dm
> +/obj/item/scratchingstone
```suggestion
/obj/item/scratching_stone
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/limbs_and_markings.dm
> +		"Right Arm implant" = "Right Arm implant"
```suggestion
		"Right Arm implant" = "Right Arm implant",
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/cargo/code/goodies.dm
> +	desc = "You dunno what this is chummer? Little scrap here sharpens your razorclaws. Preem, arctic shit if you're a metalhead type. Catch is, whatever bakebrain catgirls we got it from already used i
The description here feels a bit too memey for my taste, like, it feels like *far* too obvious of a Cyberpunk reference.

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/cargo/code/goodies.dm
> +/datum/supply_pack/goody/scratchingstone
```suggestion
/datum/supply_pack/goody/scratching_stone
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +	var/knife_bare_wound_bonus = 15
Of all of these, only `knife_force` and `knife_wound_bonus` seem like they have any use being actual variables. The rest should be defines.

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +		attack_verb_simple = list("bash", "batter", "bludgeon", "thrash", "whack")
These should be defines.

The `usesound` is also not being reset to the knife sound for butchering (since I assume it otherwise might not sound like a knife when butchering).

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +/obj/item/melee/knife/razorclaws
I'm not entirely sure what you were trying to do by using this subtype, but that's not actually the `knife`'s typepath, this would be how it's meant to be done:
```suggestion
/obj/item/knife/razorclaws
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +		toolspeed = 1
Toolspeed should probably be set on class declaration if it's not actually going to change.

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +	var/knife_bare_wound_bonus = 15
The remaining ones should get documented, too.

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +	desc = "[desc] These have undergone a special honing process; they'll kill people even faster than they used to."
```suggestion
	desc += span_warning("\n\nThese have undergone a special honing process; they'll kill people even faster than they used to.")
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +	user.visible_message(span_notice("[user] sharpens [src], the stone disintegrating!"), span_notice("You sharpen [src], making it much more deadly than before; but the stone disintegrates under the st
```suggestion
	user.visible_message(span_warning("[user] sharpens [src], [stone] disintegrating!"), span_warning("You sharpen [src], making it much more deadly than before, but [stone] disintegrates under the stress."))
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +/obj/item/organ/internal/cyberimp/arm/razorclaws
`snake_case` please! This is valid for everywhere else, I just don't want to do it for every single instance in this PR.
```suggestion
/obj/item/organ/internal/cyberimp/arm/razor_claws
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +/datum/action/item_action/organ_action/toggle/razorclaws
```suggestion
/datum/action/item_action/organ_action/toggle/razor_claws
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/medical_designs.dm
> +	materials = list (/datum/material/iron = SHEET_MATERIAL_AMOUNT, /datum/material/glass = HALF_SHEET_MATERIAL_AMOUNT, /datum/material/silver = HALF_SHEET_MATERIAL_AMOUNT)
```suggestion
	materials = list (
		/datum/material/iron = SHEET_MATERIAL_AMOUNT,
		/datum/material/glass = HALF_SHEET_MATERIAL_AMOUNT,
		/datum/material/silver = HALF_SHEET_MATERIAL_AMOUNT,
	)
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/medical_nodes.dm
> +	design_ids = list("ci-nutriment", "ci-scanner", "ci-breather", "ci-gloweyes", "ci-welding", "ci-medhud", "ci-sechud", "ci-diaghud", "ci-botany", "ci-janitor", "ci-lighter", "ci-razor")
```suggestion
	design_ids = list(
		"ci-nutriment",
		"ci-scanner",
		"ci-breather",
		"ci-gloweyes",
		"ci-welding",
		"ci-medhud",
		"ci-sechud",
		"ci-diaghud",
		"ci-botany",
		"ci-janitor",
		"ci-lighter",
		"ci-razor",
	)
```

2023-08-17 22:32 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +	armour_penetration = 10 //Let's give them some AP for the trouble.
These should be defines.

2023-08-19 02:20 UTC, Nerev4r commented
Less Shadowrun-esque desc. has been implemented.

2023-08-21 03:38 UTC, CandleJaxx commented
PUT IT INNNNNN

2023-08-22 17:31 UTC, kittysmooch commented
reiterating what i said on the gun quirk PR, this is a great way to both better define and differentiate characters beyond the merely cosmetic, doesn't give a person anything they couldn't get anyway within minutes of roundstart, doesn't compare favorably to anything that requires more effort to receive, and helps squash the ludonarrative ridiculousness of getting the same implants every single shift forever. we love flavor.

2023-08-22 18:51 UTC, Plum-but-gayer commented
puh-LEASE!!! 

actually though, if we do wanna move skratperks to something new and different from TG, let's throw it in. 10 to down is already weaker than the skateboard, which is 8.7 to down and a loadout item. Excellent flavor and no balance concerns. Maybe make sure prisoners can't take it.

2023-08-23 01:43 UTC, GoldenAlpharex requested changes

2023-08-23 01:43 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/medical_designs.dm
>  	construction_time = 200
```suggestion
	construction_time = 20 SECONDS
```

2023-08-23 01:43 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/medical_nodes.dm
> +		)
```suggestion
	design_ids = list(
		"ci-nutriment",
		"ci-scanner",
		"ci-breather",
		"ci-gloweyes",
		"ci-welding",
		"ci-medhud",
		"ci-sechud",
		"ci-diaghud",
		"ci-botany",
		"ci-janitor",
		"ci-lighter",
		"ci-razor",
	)
```

2023-08-23 02:48 UTC, GoldenAlpharex approved these changes
Eh. Let's give it a shot, I guess.

2023-08-23 17:18 UTC, sqnztb commented
Scratching stone doesn't seem to work. Not getting any sort of feedback when using the stone on the claws.

2023-08-23 17:44 UTC, kittysmooch commented
> 

other way around; use the claws on the stone

2023-08-23 17:52 UTC, sqnztb commented
Ah, should've clarified. I tried both ways. Round 9232.

2023-08-23 18:04 UTC, Nerev4r commented
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/994176bb-6ffd-4fca-9d5c-3e2773fc3205)

2023-08-23 20:24 UTC, Nerev4r commented
fresh testing reveals 'idk dude' so i'll have someone check the runtime logs of that round later, but it worked just fine this round

2023-08-24 04:42 UTC, SylvetteSylph commented
Honestly - I think I'm of the opinion that additions like this are bad for the game. Quirks have always primarily been a flavor thing for me, the primary reason I choose them is because I design characters around the combinations. I'm not sure I agree much with turning the quirk system into something more beyond flavor.

Though if this is the direction we must go, I think any roundstart addition of this caliber should be a bare minimum of 6 points. It's too easy to get up to this with just filler negative quirks.

2023-08-25 10:39 UTC, chemistrymain2 commented
> Honestly - I think I'm of the opinion that additions like this are bad for the game. Quirks have always primarily been a flavor thing for me, the primary reason I choose them is because I design characters around the combinations. I'm not sure I agree much with turning the quirk system into something more beyond flavor.
> 
> Though if this is the direction we must go, I think any roundstart addition of this caliber should be a bare minimum of 6 points. It's too easy to get up to this with just filler negative quirks.

On the contrary, the quirk 'points' system is stupid and toxic and should probably be disposed of entirely. Downsides should be inherent (and logical) to the quirk taken rather than obligating you to take like, being an awful drinker and having allergies to be able to be a netrunner razorgirl.

Quirks don't and shouldn't be useless flavor points because that's TG's thing in regards to 'roundstart balance' and that really doesn't affect us. They can and should fundamentally change how you play the game and how the game is played, as goon's do.

2023-08-27 01:06 UTC, Calial4 commented
There is an issue using the scratching stone on the Razorclaws to sharpen them, Both modes.

2023-08-27 02:21 UTC, neri-ventado commented
See above. It simply doesn't work, although the above remedy was tested. 

If it was any worth, the implant was on the left arm.

2023-08-28 16:20 UTC, CliffracerX commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +	armour_penetration = ENHANCED_KNIFE_ARMOR_PENETRATION //Let's give them some AP for the trouble.
This should check if the claws are currently in knife mode to set ``force = knife_force`` and ``wound_bonus = knife_wound_bonus`` after they've been set.

2023-08-28 19:29 UTC, Nerev4r commented
This latest push should help resolve issues whenever testmerges are updated.

2023-08-30 20:12 UTC, GoldenAlpharex requested changes
Last quick formatting stuff before it should be good to go.

2023-08-30 20:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +		wound_bonus = knife_wound_bonus
```suggestion

	if(tool_behaviour == TOOL_KNIFE)
		force = knife_force
		wound_bonus = knife_wound_bonus

```

2023-08-30 20:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/implants/code/augments_arms.dm
> +    slot = ORGAN_SLOT_LEFT_ARM_AUG
```suggestion
/obj/item/organ/internal/cyberimp/arm/razor_claws/right_arm
    zone = BODY_ZONE_R_ARM
    slot = ORGAN_SLOT_RIGHT_ARM_AUG

/obj/item/organ/internal/cyberimp/arm/razor_claws/left_arm
    zone = BODY_ZONE_L_ARM
    slot = ORGAN_SLOT_LEFT_ARM_AUG
```

2023-08-30 20:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/client/augment/implants.dm
> +    path = /obj/item/organ/internal/cyberimp/arm/razor_claws/lefthand
```suggestion
    path = /obj/item/organ/internal/cyberimp/arm/razor_claws/left_arm
```

2023-08-30 20:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/client/augment/implants.dm
> +    path = /obj/item/organ/internal/cyberimp/arm/razor_claws/righthand
```suggestion
    path = /obj/item/organ/internal/cyberimp/arm/razor_claws/right_arm
```

2023-08-30 21:03 UTC, GoldenAlpharex approved these changes
Should be good to go once CI passes.

2023-09-02 00:48 UTC, merged