another day another ammo-related pr: RMB ejects, killing off a runtime, fixing an ammo issue
Skyrat-SS13/Skyrat-TG pull request #23072
Opened 2023-08-14 08:06 UTC by Hatterhat

## About The Pull Request
- "fixes" .277 Aestus being, uh, weird. preemptively. i assume the rename of a556 to a223 (upstream) caused issues, which had an attempted resolution by renaming our a556 to a277 which left an unused caliber or - something? look what matters is that a223 (formerly a556 upstream) is fixed again. if this doesn't make sense i can explain better later
- .357 heartseeker and .357 phasic were given appropriate material costs and flags for the ammo bench
- renames the oldarms 223 ammo define to something different. honestly it goes unused i'm this close to gutting it
- also you can rmb ammo benches to eject their mag now

## How This Contributes To The Skyrat Roleplay Experience
...uh, guns working is probably a good thing?
one of these days we really ought to just kill off the oldarms stuff
## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/abe2ab6e-f375-4a9c-84dd-ea62fc54125c)
  
</details>

## Changelog
:cl:
fix: The ammo workbench no longer runtime errors when inserting material.
fix: .277 Aestus (renamed a223, formerly a556), uh, works properly in guns, again, or something.
qol: Right-clicking on an ammo workbench that has a magazine loaded now ejects it. Into your hand, presumably.
/:cl:

2023-08-15 01:21 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/projectiles.dm
> +#define CALIBER_223_BAD ".223 Stinger"
It's very confusing indeed. I think it's because the `a277` was just a renamed `a556` ammo, which led to the confusion of accidentally making it its own separate caliber and thus making it incompatible with the other guns that previously took a556. It does currently work, but only with the m16s I think.

Why the `_BAD` at the end? lol

I get the sentiment but we probably shouldn't add to the confusion. `CALIBER_223S` or something similarly descriptive would probably be a lil bit better for now.

2023-08-16 06:13 UTC, vinylspiders reviewed
Everything seems fine to me apart from that one question

2023-08-16 06:13 UTC, vinylspiders commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> -
What's up with getting rid of the animation here? I'm guessing it's what was causing the runtime, but is there no way to keep that part of it while fixing the runtime? (I genuinely don't know what the runtime was, just wondering).

2023-08-16 12:38 UTC, Hatterhat commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> -
the runtime was for checking if the inserted material was glass or not to play the appropriate animation

but the animation also never actually worked, i think, because it never had appropriate overlays sprites and put into its file so i decided i'd just get rid of all of it

2023-08-16 13:47 UTC, vinylspiders commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> -
Ah interesting. Must have been some kinda copy paste thing then.

2023-08-16 13:47 UTC, vinylspiders approved these changes

2023-08-17 19:12 UTC, GoldenAlpharex requested changes

2023-08-17 19:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
> +							/datum/material/bluespace = SMALL_MATERIAL_AMOUNT * 0.2,)
I know it's not this PR that caused this, but man the formatting on these defines is awful, think you could fix that?

2023-08-17 19:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
> +							/datum/material/glass = SMALL_MATERIAL_AMOUNT * 0.4,)
Not sure you need to add a trailing comma if it's got a parenthesis right afterwards, otherwise it looks weird.

2023-08-17 19:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +			try_put_in_hand(loaded_magazine, user)
```suggestion

		if(user)
			try_put_in_hand(loaded_magazine, user)

```

2023-08-17 19:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> -
Yeah, pretty sure that's a copy-paste moment.

2023-08-17 19:12 UTC, GoldenAlpharex commented on modular_skyrat/modules/ammo_workbench/code/ammo_workbench.dm
> +	return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN
```suggestion

	if(. == SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN)
		return

	if(!can_interact(user) || !user.can_perform_action(src, ALLOW_SILICON_REACH | FORBID_TELEKINESIS_REACH))
		return

	ejectItem(user)
	return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN
```

2023-08-23 01:29 UTC, GoldenAlpharex requested changes

2023-08-23 01:29 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
>  #define AMMO_MATS_AP list(/datum/material/iron = SMALL_MATERIAL_AMOUNT * 1.6,\
I'd do them more like this:
```
#define AMMO_MATS_TEMP list( \
	/datum/material/iron = SMALL_MATERIAL_AMOUNT * 1.6, \
	/datum/material/plasma = SMALL_MATERIAL_AMOUNT * 0.4, \
)
```

I couldn't make the suggestion properly.

2023-08-23 02:01 UTC, GoldenAlpharex requested changes

2023-08-23 02:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
>  			)
No, no, like this.
```suggestion
#define AMMO_MATS_AP list( \
	/datum/material/iron = SMALL_MATERIAL_AMOUNT * 1.6, \
	/datum/material/titanium = SMALL_MATERIAL_AMOUNT * 0.4, \
)
```

2023-08-24 21:57 UTC, GoldenAlpharex approved these changes
Finally, we can go through with this.

2023-08-24 22:01 UTC, merged