Reebe touchups
Skyrat-SS13/Skyrat-TG pull request #23104
Opened 2023-08-16 00:10 UTC by destrucktoid

## About The Pull Request

This change updates Reebe, making it easier for a clockwork cultist to initially defend as well as adding tools to help them get started with re-fortifying it.

## Why It's Good For The Game

In order for a clockwork cultist to be able to get to reebe they must sacrifice a blood cultist. However, in a round with a blood cult the blood cultists are easily able to teleport to Reebe thanks to the teleport runes that are there by default. That, along with the lack of any form of cover for what is typically a solo clockwork cultist vs the entire blood cult is crippling as it means the entire blood cult can actually get to reebe before you as the solo clockwork cultist. This is so bad because the clockwork cult revolves around being on the defensive, almost all of your sigils and structures revolve around having a defender's advantage.

This PR makes it so that there is cover for the clockwork cultist from lasers and sight as well as a single of each structure, thus making it easier for them to use their natural defenders advantage to offset the potential attack from the blood cult.
There is also added some bronze and a replica fabricator to the armory section of Reebe, making it easier for a clockwork cultist to begin reinforcing and rebuilding Reebe.

## Changelog

:cl:
add: Adds a Replica Fabricator and some sheets of bronze to fill it to the Reebe armory
add: Adds a set of doors to the Armory of Reebe
balance: Changes Reebe's central room doors to be opaque
balance: Changes Reebe's central room window's to be walls
balance: Removes one of the 2 teleport runes at Reebe
tweak: Minor decorative changes to Reebe
/:cl:

2023-08-16 06:02 UTC, Zonespace27 commented
> the blood cultists are easily able to teleport to Reebe thanks to the teleport runes that are there by default.
Reebe wasn't made with an actual blood cult being on station in mind, just remove the runes if it's an issue

2023-08-16 15:34 UTC, destrucktoid commented
> > the blood cultists are easily able to teleport to Reebe thanks to the teleport runes that are there by default.
> 
> Reebe wasn't made with an actual blood cult being on station in mind, just remove the runes if it's an issue

I've removed one of the teleport runes but i elected to keep the second. I do think that having the blood cult have an easy way to Reebe in order to have a showdown there is good. It allows for good Ratvar vs Nar'Sie RP and can result in some fun combat. I just don't think that it should be as one sided for the blood cult as it currently is. Hence the decision to make Reebe better capable of being initially defended.

2023-08-25 23:03 UTC, GoldenAlpharex requested changes, later dismissed
The PR isn't following our PR template, it's following /tg/'s, please follow our own PR template, namely, the "Proof of Testing" section.

2023-08-27 01:42 UTC, destrucktoid commented
> The PR isn't following our PR template, it's following /tg/'s, please follow our own PR template, namely, the "Proof of Testing" section.

I've updated the original post with what i believe to be sufficient evidence for the proof of testing. If it's insufficient or i've done it wrong, please let me know and i'll updated with other forms of evidence.

2023-09-11 17:07 UTC, vinylspiders commented
I don't see any issues with this and it's been open for a while now so here we go!

2023-09-11 17:07 UTC, vinylspiders approved these changes

2023-09-11 17:50 UTC, merged