makes all suit-slot items e.g. jackets able to fit guns and holsters in their suit storage
Skyrat-SS13/Skyrat-TG pull request #23115
Opened 2023-08-16 05:48 UTC by Hatterhat

## About The Pull Request
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/31829017/9e48dd16-08ea-4afc-8096-041919416f30)
(note: doesn't work for chaplain stuff. if this is blocking the pr's merge i guess i can finagle it)

## How This Contributes To The Skyrat Roleplay Experience
does shooting people/open-carry as deterrence count as roleplay

## Proof of Testing
its right there

## Changelog

:cl:
balance: Every oversuit slot item, e.g. jackets/winter coats/etc. is now capable of holding a gun or a holster.
/:cl:

2023-08-16 18:27 UTC, Paxilmaniac commented on modular_skyrat/master_files/code/modules/clothing/suits/_suits.dm
> +						/obj/item/storage/belt/holster,)
holy tabs batman

2023-08-16 18:27 UTC, Paxilmaniac commented on modular_skyrat/modules/goofsec/code/sec_clothing_overrides.dm
> +/obj/item/storage/belt/holster/chameleon
did you know that syndicate holsters in suit slots probably can break really bad due to the fact that not every belt has a belt_mirror sprite, which suit slot items use. I'm pretty sure I blocked syndie holsters from fitting in normal armor vests for this reason.

2023-08-16 19:18 UTC, YakumoChen commented on modular_skyrat/master_files/code/modules/clothing/suits/_suits.dm
> +		allowed += list(/obj/item/gun,
This needs to be a list similar to what fits on security armour at minimum, item/gun is far too broad

2023-08-16 19:20 UTC, YakumoChen commented
While I largely disagree with this PR in general (we have a belt slot for open carry regardless of clothing) I think this should be limited to handguns at most, I can't see civilian jackets being standard to holster a shotgun or longarm.

2023-08-17 11:47 UTC, kittysmooch commented
let me hold a sword on that bad boy >:)

2023-08-17 21:03 UTC, GoldenAlpharex requested changes
I'm overall not entirely convinced about this change, really.

Furthermore, I feel like holsters fitting in every single suit storage is a bit much as well, I think that it's a fine balance as-is to have to go for more armor-oriented suits in order to have the ability to wear holsters on suit storages instead of the belt slot.

2023-08-17 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/goofsec/code/sec_clothing_overrides.dm
> +/obj/item/storage/belt/holster/chameleon
I think that's a very valid point to bring up and consider.

2023-08-17 21:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/goofsec/code/sec_clothing_overrides.dm
I feel like these changes should be made in a separate PR.

2023-08-17 21:03 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/modules/clothing/suits/_suits.dm
> +		allowed += list(/obj/item/gun,
I'm going to have to agree with Chen here, this is far too broad.

2023-08-23 01:12 UTC, Hatterhat commented
lack of interest from maintainers so let's not

2023-08-23 01:12 UTC, closed without merging