Adds the Emergency Tether to the Engineering Modsuit
Skyrat-SS13/Skyrat-TG pull request #23279
Opened 2023-08-23 19:52 UTC by TheSS13Melon

## About The Pull Request

Adds Emergency Tethers to the engineering modsuit.

## How This Contributes To The Skyrat Roleplay Experience

Tethers are pretty much unused because they're quickly phased out by the jetpack. This adds them to engineering suits as engineering uses their modsuits in EVA more often than other groups (notably for solars at the start) so they have at least a little bit of use before they're replaced by jetpacks.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
https://gyazo.com/3fe5a8adda57da5349e9c111bcbe418e
</details>

## Changelog

:cl:
qol: Adds the Emergency Tether to Engineering Modsuits
/:cl:

2023-08-24 05:02 UTC, Plum-but-gayer commented
As a longtime engineer player/modsuit enjoyer 100% agree with this, tethers never have a use case outside of a very small 20 minute window and the fuss to install them is rarely worth it. Engineers having some extra EVA mobility roundstart (as they are the only people who really enter EVA roundstart) makes sense and is good. +1

2023-08-24 08:27 UTC, OrionTheFox commented
Proof of Testing image is broken: make sure you put Whitespace between it and any surrounding text

2023-08-24 22:57 UTC, lessthnthree approved these changes

2023-08-24 23:00 UTC, lessthnthree requested changes

2023-08-24 23:00 UTC, lessthnthree commented on code/modules/mod/mod_types.dm
> +		/obj/item/mod/module/tether,
Need to mark your Skyrat edits on non-modular PRs.

2023-08-25 22:51 UTC, GoldenAlpharex approved these changes
I approve of this change.

2023-08-25 22:51 UTC, GoldenAlpharex commented on code/modules/mod/mod_types.dm
> +		/obj/item/mod/module/tether,
```suggestion
		/obj/item/mod/module/tether, // SKYRAT EDIT ADDITION - Adds the Emergency Tether to the roundstart engineering MODsuits
		/obj/item/mod/module/magboot,
	)
	default_pins = list(
		/obj/item/mod/module/magboot,
		/obj/item/mod/module/tether, // SKYRAT EDIT ADDITION - Adds the Emergency Tether to the roundstart engineering MODsuits
```

2023-08-26 09:03 UTC, OrionTheFox commented
Would TG accept this? It's a pretty simple QoL change

2023-08-26 17:49 UTC, lessthnthree approved these changes

2023-08-26 17:49 UTC, merged

2023-08-26 17:58 UTC, Paxilmaniac commented
> Would TG accept this? It's a pretty simple QoL change

This certainly seems like something that should have been tried upstream first.