[MODULAR] Adds the scryer to the loadout attempt 2
Skyrat-SS13/Skyrat-TG pull request #23303
Opened 2023-08-24 23:18 UTC by W4rd3nn

## About The Pull Request
This adds the new modlink scryer to the loadout

## How This Contributes To The Skyrat Roleplay Experience
It adds no more mechanical functionality over a PDA message. It really shouldn't be locked behind advanced modsuit research. This lets people get the silly lil necklace in the loadout.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12723348/31518242-b2cf-4ed0-b04f-a32fe49c714e)

</details>

## Changelog

:cl:Motho
add: MODLink Scryer necklaces are now available in the loadout.
/:cl:

2023-08-24 23:19 UTC, W4rd3nn commented
OKAY!!! It's fixed. I have no idea what the issue was

2023-08-24 23:22 UTC, lessthnthree approved these changes

2023-08-25 22:56 UTC, GoldenAlpharex requested changes
My only issue with this is that the MODlink system is currently independent of telecommunications, so it works literally all the time, no matter what happens in the round.

I'd appreciate if we had it depend on telecomms like other telecommunications-related forms of communication, before having it available at round-start for everyone, because it's kind of a bit too strong otherwise, imo.

Think of it as an incentive to fix an issue for a feature to be allowed through. :)

2023-08-25 22:56 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_neck.dm
> +	name = "MODlink scryer"
```suggestion
	name = "MODlink Scryer"
```

2023-08-25 23:27 UTC, W4rd3nn commented
I mean, I can kinda see it but also station-bounced radios which are printable from the autolathe at the beginning of the round defeat any telecomms tampering.

Regardless, making it dependent on telecomms is out of my skillset, so if that's a dealbreaker, then I'll just wait for someone else to do it.

2023-08-25 23:27 UTC, Nerev4r commented
> My only issue with this is that the MODlink system is currently independent of telecommunications, so it works literally all the time, no matter what happens in the round.
> 
> I'd appreciate if we had it depend on telecomms like other telecommunications-related forms of communication, before having it available at round-start for everyone, because it's kind of a bit too strong otherwise, imo.
> 
> Think of it as an incentive to fix an issue for a feature to be allowed through. :)

Not to be a balancejak, but we already had that in the form of the NIF Hivemind, no? I think it's neat if space explorers w/ this feature for instance can phone home to their partner at the bar or w/e.

2023-08-26 04:46 UTC, Paxilmaniac commented
> 

This is literally the entire purpose of the modlink system. There are so so SO many ways to communicate directly with one other person or with a small group of other people without tcomms that this does not make sense to me as an argument. Comms being down prevents MASS communication of information for example screaming HELP NUKIES DORMS over common radio. You can't do that with a modlink. You're calling one guy who also happens to have one, and that one guy can only call one other guy at a time. And, again, as juniper said, if communication with literally anyone was a problem then surely NIF hiveminds must cease to exist too. Surely we must remove the emergency toolboxes on the interlink shuttle because they have radios that work regardless of tcomms in them.

2023-08-28 21:31 UTC, CandleJaxx commented
yeah, linking this to telecomms seems a bit of a stretch esp. when, as stated, one autolathe can immediately allow you access to common, which everyone can hear due to the intercoms

2023-08-29 23:49 UTC, YakumoChen commented
> This is literally the entire purpose of the modlink system. There are so so SO many ways to communicate directly with one other person or with a small group of other people without tcomms

Counterpoint: the link is cross-Z and requires no advance setup beyond owning the modlink in loadout

Most options I can think of that bypass tcomms are:
- very public (bounced radios)
- same z only (bounced radios)
- require mutual foreknowledge and setup (custom freq bounced radios)
- require intentionally acquiring/buying the equipment beforehand (all)
- User knows where recipient is (holocalls)

Even the hivemind you have to at least remember to buy in the round, modlink is a comms-free PDA you can click a loadout button and forget you have it until you need it

2023-08-29 23:58 UTC, YakumoChen commented
Ultimately this begs the question of "why is this needed in loadout if everyone who gets one also has a PDA?"

2023-08-29 23:59 UTC, YakumoChen commented
Also this will bypass ghost cafe protection which will make me mad because I keep removing radios from ghosts

2023-08-30 04:47 UTC, W4rd3nn commented
It's worth mentioning the scryers arent technically usable from roundstart. They still need a battery and I believe they also need their frequency set. This just means that people dont have to wait the 40-60 minute time period before advanced modsuit modules are researched

2023-08-30 07:58 UTC, YakumoChen commented
> It's worth mentioning the scryers arent technically usable from roundstart. They still need a battery and I believe they also need their frequency set. This just means that people dont have to wait the 40-60 minute time period before advanced modsuit modules are researched

https://github.com/tgstation/tgstation/pull/77957

It is usable from roundstart, and power cells are widely available everywhere (all flashlights contain one, for example)

2023-08-30 18:58 UTC, CandleJaxx commented
> Also this will bypass ghost cafe protection which will make me mad because I keep removing radios from ghosts

this feels more like a policy issue, if people are actively trying to find ways to contact the station in the ghost cafe, they should be looking at an ahelp

> > It's worth mentioning the scryers arent technically usable from roundstart. They still need a battery and I believe they also need their frequency set. This just means that people dont have to wait the 40-60 minute time period before advanced modsuit modules are researched
> 
> [tgstation/tgstation#77957](https://github.com/tgstation/tgstation/pull/77957)
> 
> It is usable from roundstart, and power cells are widely available everywhere (all flashlights contain one, for example)
> 
> I don't think a technicality refutes any of the points here.
> 
> It _does_ add more mechanical functionality than a PDA message, so the Why isn't accurate.

as for this, it seems to me that this adds the same level of difficulty as acquiring a station-bound radio to communicate does, since you either have to print + charge a battery, or find one in maint

2023-08-30 19:05 UTC, YakumoChen commented
> as for this, it seems to me that this adds the same level of difficulty as acquiring a station-bound radio to communicate does, since you either have to print + charge a battery, or find one in maint

A station bounced radio does not provide private, untappable, cross-Z, one-way-setup (both do not have to mutually agree on a frequency via other method of communication beforehand), telecomms-ignoring, discreet communication

2023-08-30 20:46 UTC, GoldenAlpharex approved these changes
Considering you still have to add a cell and set the frequency manually, I'm not as opposed to this as I was initially.

I'm hoping this won't become an issue with ghost roles (including the cafe), as we'll have to put in additional restrictions if that's the case.

2023-08-30 20:46 UTC, merged