[SEMI-MODULAR] NIFSoft Scryer
Skyrat-SS13/Skyrat-TG pull request #23482
Opened 2023-09-03 04:15 UTC by softcerv

## About The Pull Request
Adds in a version of the MODSuit Scryer to the game that works as a NIFSoft, allowing the user to summon a physical Scryer necklace that functions similarly to the Scryer in the loadout.

The NIFSoft requires the user's neck slot to be empty and the user's hands to be uncuffed to activate. Additionally, if the item is pulled from the user's neck, the NIFSoft will deactivate.  

## How This Contributes To The Skyrat Roleplay Experience
This gives NIF users a neat way to roleplay with other NIF users, MODSuit users, or anyone that has the Scryer loadout item.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
It activates and works
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/e294948c-eb75-4450-8994-01cee6356bd4)

Special examine text
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/438ecdae-0f4a-4016-9fd5-9a425cd5787a)

NIFSoft catalog
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/a4bc956a-ccd9-42cf-b131-34b407fe72df)

</details>

## Changelog

:cl:
add: Adds in the NIFSoft Scryer, a NIFSoft that gives the user a Scryer they can use to communicate with other Scryer users.
/:cl:

2023-09-03 04:15 UTC, softcerv commented
drafting while we figure out some cool flavor text

2023-09-04 20:32 UTC, YakumoChen commented
I'd rather have this than scryers in loadouts 100%, since it's a pretty sideways alternative to hivemind

2023-09-04 20:47 UTC, Nerev4r commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	name = "Scryer"
NIFLink Holocaller

program_desc "This ubiquitous NIFSoft adds Scryer functionality similar to MODSuits to the user's NIF; allowing for real-time communication through AR hologlass screens from a hardlight projector sat around the wearer's neck."

2023-09-04 20:47 UTC, Nerev4r commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	name = "\improper NIFSoft scryer"
NIFLink Holocaller

desc = "A nanomachine construct working as a modified version of the MODlink scryer, conjured using a NIF; functionally the same, but able to carry out holocalls in a more portable format."

2023-09-04 20:47 UTC, Nerev4r commented
🗿

2023-09-30 07:35 UTC, vinylspiders requested changes

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	var/obj/item/clothing/neck/link_scryer/loaded/nifsoft/linked_scyer
You'd probably want this to be a `datum/weakref` wouldn't you?

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scyer = new (parent_nif.resolve())
```suggestion
	var/parent_resolved = parent_nif.resolve()
	if(parent_resolved)
		linked_scyer = new (parent_resolved)
	if(!linked_scryer)
		return
```
When you are using weakrefs you always want to be checking that they resolved to something before using them.

That said though I don't really understand what's going on here--- why the `new`? Isn't parent_nif already initialized and pointing to something?

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +			linked_mob.transferItemToLoc(linked_scyer, parent_nif.resolve(), TRUE)
```suggestion
			var/parent_resolved = parent_nif.resolve()
			if(parent_resolved)
				linked_mob.transferItemToLoc(linked_scyer, parent_resolved, TRUE)
```

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +		cell = null
```suggestion
		QDEL_NULL(cell)
```

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	. += span_notice("The MODlink ID is [mod_link.id], frequency is [mod_link.frequency || "unset"]. <b>Right-click</b> with multitool to copy/imprint frequency.")
```suggestion
	. += span_notice("The MODlink ID is [mod_link.id], frequency is [mod_link.frequency || "unset"]. <b>Right-click</b> with a multitool to copy/imprint the frequency.")
```

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	balloon_alert(user, "cell non-removable")
```suggestion
	balloon_alert(user, "cell non-removable!")
```

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	balloon_alert(user, "name set")
```suggestion
	balloon_alert(user, "name set!")
```

2023-09-30 07:35 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +		linked_scyer = null
```suggestion
		QDEL_NULL(linked_scyer)
```

2023-09-30 07:40 UTC, softcerv commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scyer = new (parent_nif.resolve())
So, for this code when I call ` new (parent_nif)`, it is basically creating a new scryer and then setting the parent of that scryer to `parent_nif`

2023-09-30 07:42 UTC, softcerv commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	var/obj/item/clothing/neck/link_scryer/loaded/nifsoft/linked_scyer
I am not sure that it makes sense in this usecase for it to be assigned to a weakref. The scryer belongs to the NIF and we don't really want the scryer to exist without the NIFSoft also existing.

2023-09-30 07:51 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scyer = new (parent_nif.resolve())
Oh I see, in your constructor. You don't see people using those too often in DM. Yeah OK that's fine then. You may still want to check it first though if you aren't doing that in your constructor. I've edited the suggestion.

2023-09-30 07:52 UTC, softcerv commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scyer = new (parent_nif.resolve())
It's weird, but yeah, it does work and is more concise.

2023-09-30 07:55 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	var/obj/item/clothing/neck/link_scryer/loaded/nifsoft/linked_scyer
Sure--in that case just remember to null the `/datum/nifsoft/scryer`'s `linked_scryer` var in your `Destroy()` for `/obj/item/clothing/neck/link_scryer/` so you aren't left with a hanging ref/a harddel.

2023-09-30 07:59 UTC, softcerv commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	var/obj/item/clothing/neck/link_scryer/loaded/nifsoft/linked_scyer
The deed is done

2023-09-30 08:00 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	var/obj/item/clothing/neck/link_scryer/loaded/nifsoft/linked_scyer
> The deed is done

Mutually assured Destruction() accomplished !

2023-09-30 23:03 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	if(linked_scyer)
```suggestion
	if(!QDELETED(linked_scryer))
```

2023-09-30 23:03 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	return ..()
```suggestion
/obj/item/clothing/neck/link_scryer/loaded/nifsoft/Destroy()
	if(parent_nifsoft)
		var/datum/nifsoft/scryer/resolved_nifsoft = parent_nifsoft.resolve()
		if(!QDELETED(resolved_nifsoft))
			resolved_nifsoft.linked_scyer = null

	return ..()
```

2023-09-30 23:07 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +		linked_scyer = new (parent_resolved)
```suggestion
	linked_scyer = new (parent_nif.resolve())
```

2023-10-01 01:06 UTC, vinylspiders requested changes

2023-10-01 01:06 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +		return TRUE
```suggestion
				return linked_mob.transferItemToLoc(linked_scryer, parent_resolved, TRUE)
```
Just giving this a final look over, small detail

2023-10-01 01:25 UTC, vinylspiders requested changes

2023-10-01 01:25 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scryer.label = linked_mob.name
```suggestion
	var/obj/item/organ/internal/cyberimp/brain/nif/parent_resolved = parent_nif.resolve()
	if(!istype(parent_resolved))
		stack_trace("[src] ([REF(src)]) tried to create a linked scryer but it had no parent_nif!")
	if(!linked_scryer)
		stack_trace("[src] ([REF(src)]) created with no linked scryer!")
	linked_scyer = new (parent_resolved)
	linked_scryer.parent_nifsoft = WEAKREF(src)
```
Going back to this you probably wouldn't want to pass a null `parent_nif` into the constructor, right? Wouldn't it be preferable to stack_trace in that instance?

2023-10-01 01:25 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +/obj/item/clothing/neck/link_scryer/loaded/nifsoft/Initialize(mapload)
Also where is that constructor actually being utilized? I'm not seeing the part where you said it sets the `parent_nif` to the passed ref.

2023-10-01 01:25 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scryer.parent_nifsoft = WEAKREF(src)
I think that I misunderstood what you were saying--you set the parent_nifsoft here, not in the constructor.
In which case you don't want those parenthesis.

You're just trying to set the `loc` of the created `linked_scryer` to the `parent_nif` by passing that arg to the constructor, correct?

2023-10-01 01:53 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +	linked_scyer = new (parent_resolved)
```suggestion
	linked_scryer = new (parent_resolved)
```
goddamnit

2023-10-01 02:14 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +				return linked_mob.transferItemToLoc(linked_scryer, parent_resolved, TRUE)
```suggestion
		if(linked_scryer)
			var/parent_resolved = parent_nif.resolve()
			if(parent_resolved)
				return linked_mob.transferItemToLoc(linked_scryer, parent_resolved, TRUE)
				
		return FALSE
```

2023-10-01 02:14 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/scryer.dm
> +
```suggestion
```

2023-10-01 02:14 UTC, vinylspiders approved these changes

2023-10-01 02:30 UTC, merged