[Semi-non-modular] Service Borg Tweaks
Skyrat-SS13/Skyrat-TG pull request #23549
Opened 2023-09-06 02:01 UTC by IgiariValkyr

## About The Pull Request

Service borgs have had duplicate tools and obsolete tools for a while. This pull fixes those. This pull also adds a fifth shaker for condiments, that actually adds proper condiments instead of whatever the Condiment Synthesizer gives. I am unsure how to comment out the Condiment Synthesizer from the research nodes without messing with more core files.

The following two changes affect core files as I'm unsure how to modularize them:
- Adds a fifth shaker, Condiments, to the Service Model.
- Removes duplicate items from the Service Model loadout:
-- Two droppers
-- One tray
-- The original cyborg shaker (it was literally commented out the line before then added back in again. Come on guys.)

These two changes _are_ modular and won't be affected by future updates.
- Adds Kortara to the alcohol shaker.
- Reagents from all shakers are alphabeticalized and moved about to respective locations (things considered "condiments" are in the new condiment shaker; ie, sugar moved from Soda to Condiment)

## How This Contributes To The Skyrat Roleplay Experience

Service borgs can now adhere to all needs of the crew with proper condiments, have a less bulky inventory by three items technically, and can much easier find reagents.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![2023-09-05_20-58-45](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5521322/0fa5ce26-6d2f-49df-822d-663ecb30f5cb)
![2023-09-05_20-58-55](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5521322/846df4d0-dbc4-4833-aa6c-4ef9662f117a)
![2023-09-05_20-59-04](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5521322/52250ed6-1273-4be9-af22-7071d26437d7)
![2023-09-05_20-59-24](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5521322/55c3efdd-897b-49f1-8505-5e52a11160d0)
![2023-09-05_20-59-39](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5521322/848c994f-83fd-4f18-a4df-235a2b15a288)
![dreamseeker_2023-09-05_20-59-58](https://github.com/Skyrat-SS13/Skyrat-tg/assets/5521322/b56a82b4-6506-4cd9-9da5-f681d8cc36ca)

</details>

## Changelog

:cl:
add: Added a new shaker for service borgs all about condiments
add: Added kortara to the borg alcohol shaker
del: Removed duplicated items from service borgs
qol: All service borg shakers are now alphabetically sorted.
/:cl:

2023-09-08 00:54 UTC, GoldenAlpharex requested changes

2023-09-08 00:54 UTC, GoldenAlpharex commented on code/modules/mob/living/silicon/robot/robot_model.dm
> -		/obj/item/reagent_containers/borghypo/borgshaker,
This needs to be commented out and labelled with a Skyrat Edit comment, rather than flat-out deleted.

2023-09-08 00:54 UTC, GoldenAlpharex commented on code/modules/mob/living/silicon/robot/robot_model.dm
> -		/obj/item/reagent_containers/dropper,
Wow, there was THREE of them?!?

2023-09-08 00:54 UTC, GoldenAlpharex commented on code/modules/mob/living/silicon/robot/robot_model.dm
> -		/obj/item/lighter,
At this point, I'd like to see what the difference with the tg file is, just so we can properly label what's a Skyrat Edit and what isn't, because it's very unclear.

2023-09-08 00:54 UTC, GoldenAlpharex commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +		/datum/reagent/consumable/nothing\
```suggestion
		/datum/reagent/consumable/nothing,\
```

2023-09-08 00:54 UTC, GoldenAlpharex commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +		/datum/reagent/consumable/space_up\
```suggestion
		/datum/reagent/consumable/space_up,\
```

2023-09-08 00:54 UTC, GoldenAlpharex commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +		/datum/reagent/consumable/watermelonjuice\
This all just helps reducing the size of diffs in future PRs affecting these lists.
```suggestion
		/datum/reagent/consumable/watermelonjuice,\
```

2023-09-08 00:54 UTC, GoldenAlpharex commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +		/datum/reagent/water\
```suggestion
		/datum/reagent/water,\
```

2023-09-08 00:54 UTC, GoldenAlpharex commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +	/datum/reagent/consumable/frostoil\
```suggestion
	/datum/reagent/consumable/frostoil,\
```

2023-09-08 10:03 UTC, IgiariValkyr commented on code/modules/mob/living/silicon/robot/robot_model.dm
> -		/obj/item/reagent_containers/borghypo/borgshaker,
It is commented out. Look at the bottom of the list. It was already commented, but then readded again at some point

2023-09-08 10:03 UTC, IgiariValkyr commented on code/modules/mob/living/silicon/robot/robot_model.dm
> -		/obj/item/reagent_containers/dropper,
Somehow!

2023-09-09 01:06 UTC, IgiariValkyr commented
I’ll re-open this later tonight. I can’t seem to fix the original file from my phone, which means i’ll likely need to redo it entirely for the pull

2023-09-09 01:06 UTC, closed without merging