Void Raptor cargo door buttons
Skyrat-SS13/Skyrat-TG pull request #23634
Opened 2023-09-11 15:37 UTC by lessthnthree

## About The Pull Request

Fixes label for the unloading side, sets door IDs as numericals so you quit locking yourself out when trying to change it with a multitool.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl: LT3
fix: Fixed Void Raptor cargo door labels and IDs
/:cl:

2023-09-11 17:17 UTC, vinylspiders requested changes

2023-09-11 17:17 UTC, vinylspiders commented on _maps/map_files/VoidRaptor/VoidRaptor.dmm
> +	id = 68;
Not sure which is which, but why not something more descriptive like `"cargounload_north"` and `"cargounload_south"` instead? 

So you can tell more easily at a glance which door the button goes to.

2023-09-11 17:18 UTC, vinylspiders commented on _maps/map_files/VoidRaptor/VoidRaptor.dmm
> +	id = 68;
though 69 gave me a chuckle

2023-09-11 18:28 UTC, lessthnthree commented on _maps/map_files/VoidRaptor/VoidRaptor.dmm
> +	id = 68;
The multitool can only set numeric IDs on blast door controllers.

2023-09-12 00:10 UTC, vinylspiders commented on _maps/map_files/VoidRaptor/VoidRaptor.dmm
> +	id = 68;
Ah good to know!

2023-09-12 00:11 UTC, vinylspiders approved these changes

2023-09-12 00:11 UTC, merged