medical tongue bounty text tweak
Skyrat-SS13/Skyrat-TG pull request #23631
Opened 2023-09-11 06:01 UTC by Literallynotpickles

## About The Pull Request
pr from downstream after realizing cyber tongues came from here

i missed out on some money-making efficiency in bounties not knowing you can just use any of the cybernetic ones for these, grrr

## How This Contributes To The Skyrat Roleplay Experience
money go up

## Proof of Testing
it's a one line description text

## Changelog

:cl:
qol: Adjusted medical tongue bounties to mention that cybernetic ones _do_ work for them.
/:cl:

2023-09-11 16:12 UTC, softcerv commented on code/modules/cargo/bounties/medical.dm
> +	description = "A recent attack by Mime extremists has left staff at Station 23 speechless. Ship some spare tongues. We'll accept cybernetic variants if need be."
```suggestion
	description = "A recent attack by Mime extremists has left staff at Station 23 speechless. Ship some spare tongues. We'll accept cybernetic variants if need be." // SKYRAT EDIT - ORIGINAL description = "A recent attack by Mime extremists has left staff at Station 23 speechless. Ship some spare tongues."
```
Because this touches TG code, you need to mark that this change is a Skyrat edit and include the original code as a comment

2023-09-12 07:16 UTC, lessthnthree commented
Given modular_skyrat/master_files/code/modules/cargo already exists in the folder structure, you can make this change modular.

2023-09-12 07:16 UTC, lessthnthree requested changes

2023-09-12 07:16 UTC, lessthnthree commented on code/modules/cargo/bounties/medical.dm
> +	description = "A recent attack by Mime extremists has left staff at Station 23 speechless. Ship some spare tongues. We'll accept cybernetic variants if need be." // SKYRAT EDIT - ORIGINAL descriptio
Modularize this.

2023-09-12 17:21 UTC, lessthnthree approved these changes

2023-09-12 17:22 UTC, merged