[MODULAR] Wiki-Book NIFSoft
Skyrat-SS13/Skyrat-TG pull request #23648
Opened 2023-09-12 03:23 UTC by softcerv

## About The Pull Request
This PR adds a version of the summoner NIFSoft that allows the user to summon all of the available wiki books in the game. 
The NIFSoft is free and can be purchased through the NIFSoft catalog.

## How This Contributes To The Skyrat Roleplay Experience
I think it's important to give players more IC access to information about how to properly do their jobs without needing to resorting to out of game means such as the wiki. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/dd14ad68-7704-4a6f-bac1-8b59142b5a57)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/6f8f598d-dedc-44a7-84d4-89bd00470b66)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/7cf7e553-3e6f-4205-ac83-049922c5f5af)

</details>

## Changelog

:cl:
add: Adds in a wiki-book NIFSoft, allowing the user to access various wiki books.
/:cl:

2023-09-12 03:24 UTC, softcerv commented
Drafting while I figure out a better name and also think about extra books to add in

2023-09-12 12:24 UTC, burgerenergy commented
I feel this could just be a PDA app if you wanted to go route, don't need to actually poof the books into existence.

2023-09-12 14:51 UTC, softcerv commented
> I feel this could just be a PDA app if you wanted to go route, don't need to actually poof the books into existence. 

Possibly, although I might also end up adding extra instructional books to this too.

2023-09-13 21:48 UTC, W4rd3nn commented
Akashic something maybe? https://en.wikipedia.org/wiki/Akashic_records

2023-09-27 06:04 UTC, vinylspiders requested changes
Looks good to me otherwise!

2023-09-27 06:04 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/book_summoner.dm
> +	program_desc = "Grimoire Akasha is a fork of the Grimoire Caeruleam NIFSoft, that is designed around giving the user access to various educational hardlight books. Due to it's educational nature and
```suggestion
	program_desc = "Grimoire Akasha is a fork of the Grimoire Caeruleam NIFSoft that is designed around giving the user access to various educational hardlight books. \
	Due to its educational nature and miniscule size, Grimoire Akasha is typically provided for free at most NIFSoft marketplaces."
```
Found a couple grammar issues + Can break these longer strings up into multiline to make them easier to read at once.

2023-09-27 06:04 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/book_summoner.dm
> +	if(!can_be_carved)
```suggestion
	if(cannot_carve)
```

2023-09-27 06:04 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/book_summoner.dm
> +	generated_book.can_be_carved = FALSE
```suggestion
	generated_book.cannot_carve = TRUE
```

2023-09-27 06:04 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/book_summoner.dm
> +	var/can_be_carved = TRUE
```suggestion
	/// Is the parent book unable to be carved? TRUE prevents carving. By default this is unset
	var/cannot_carve
```
Vars that haven't been set actually have less overhead in DM so might as well save some memory there by only setting it when needed.

2023-09-27 06:04 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/book_summoner.dm
> +	loaded_nifsoft = /datum/nifsoft/summoner/book
https://github.com/Skyrat-SS13/Skyrat-tg/blob/978fcd3f786e9d2c58dfc9d088d86721bd5071e5/modular_skyrat/modules/modular_implants/code/nifsofts/prop_summoner.dm#L4-L6

This is actually being overridden here, so it will give you the base type of program `/datum/nifsoft/summoner` until you fix that

2023-09-27 18:08 UTC, softcerv commented on modular_skyrat/modules/modular_implants/code/nifsofts/book_summoner.dm
> +	loaded_nifsoft = /datum/nifsoft/summoner/book
d'oh!

2023-09-27 20:45 UTC, vinylspiders approved these changes

2023-09-27 20:45 UTC, merged