[MODULAR] Reduces the Blueshield and NT Consultant's IDs to Silver to reduce the number of all-access-compatible IDs on the station back down to the intended 2
Skyrat-SS13/Skyrat-TG pull request #23684
Opened 2023-09-14 08:41 UTC by Iamgoofball

## About The Pull Request

Reduces the Blueshield and NT Consultant's IDs to Silver to reduce the number of all-access-compatible IDs on the station back down to the intended 2

## How This Contributes To The Skyrat Roleplay Experience

Please consult the design document for the ID card trim system as designed at https://hackmd.io/@tgstation/HkS-z64NP#High-Access-Jobs-and-Low-Pop-Access and all relevant discussion on https://github.com/tgstation/tgstation/pull/56910 as to why all access compatible ID cards should only be available in 2 possible locations at maximum without admin intervention via events or spawning people with higher-tier cards, one on a spawned Captain and the other on the spare golden ID card in the spare safe.

Pairs well with https://github.com/Skyrat-SS13/Skyrat-tg/pull/23683 but can be merged without.

## Proof of Testing

This is battle tested code.

## Changelog
:cl:
balance: Reduces the Blueshield and NT Consultant's IDs to Silver to reduce the number of all-access-compatible IDs on the station back down to the intended 2
/:cl:

2023-09-14 08:54 UTC, ghost commented
Yeah this is valid.
However, "Battle Tested Code" isn't proof of testing. You have to ensure that all the accesses still work, especially to the cards' respective unique rooms.

2023-09-14 11:59 UTC, burgerenergy commented
Keep it aesthetically Centcom, imo.

2023-09-14 13:54 UTC, desertmote commented
Good PR but being too lazy to test and add it to the PR is a flaw.

2023-09-14 17:56 UTC, lessthnthree commented
Yes, please have their cards use the blue icon_state until it's decided what's going on with ID cards going forward.

2023-09-14 19:04 UTC, Iamgoofball commented
I am not doing that, that defeats the purpose of the ID trims being recognizable at a glance. We can make the back-color on their job icon green for central command instead.

2023-09-19 14:47 UTC, Iamgoofball commented
stale b gone

2023-09-22 16:45 UTC, lessthnthree approved these changes

2023-09-22 16:48 UTC, lessthnthree requested changes

2023-09-22 16:48 UTC, lessthnthree commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
>  	id_trim = /datum/id_trim/job/nanotrasen_consultant
This doesn't work.

2023-09-22 16:48 UTC, lessthnthree commented
## WARNING: Unable to apply trim /datum/id_trim/job/nanotrasen_consultant to the silver identification card () in outfit Nanotrasen Consultant. in code/datums/outfit.dm at line 208 src: Nanotrasen Consultant usr: LT3.

Battle tested code my ass.

2023-09-22 17:43 UTC, lessthnthree commented
> I am not doing that, that defeats the purpose of the ID cards being recognizable at a glance when it comes to what access the ID card can hold. We can make the back-color on their job icon green for central command instead to communicate that they work for Nanotrasen.

The request is for a unique looking ID. Until that requirement is met this won't be merged.

2023-09-22 18:16 UTC, Iamgoofball commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
>  	id_trim = /datum/id_trim/job/nanotrasen_consultant
im gonna destroy id trim code i swear

2023-10-04 10:20 UTC, lessthnthree commented
I'll approve this once https://github.com/tgstation/tgstation/pull/78761 hits (and you've fixed it to be working.)

Get someone to make a hologram icon for the positions

2023-10-04 12:14 UTC, EricZilla commented
> > I am not doing that, that defeats the purpose of the ID cards being recognizable at a glance when it comes to what access the ID card can hold. We can make the back-color on their job icon green for central command instead to communicate that they work for Nanotrasen.
> 
> The request is for a unique looking ID. Until that requirement is met this won't be merged.

Yalls got my attention so
What about making a lower access varient of centcom IDs?
![Helpful I hope](https://github.com/Skyrat-SS13/Skyrat-tg/assets/81941674/205a4657-7679-485c-97c2-818944c54b4a)
Also here are the new ID stuff in convenient skyrat format, I already added the new centcom ID too if yalls want it
[skyrat ID stuff.zip](https://github.com/Skyrat-SS13/Skyrat-tg/files/12803146/skyrat.ID.stuff.zip)

2023-10-04 22:56 UTC, lessthnthree commented
> > > I am not doing that, that defeats the purpose of the ID cards being recognizable at a glance when it comes to what access the ID card can hold. We can make the back-color on their job icon green for central command instead to communicate that they work for Nanotrasen.
> > 
> > 
> > The request is for a unique looking ID. Until that requirement is met this won't be merged.
> 
> Yalls got my attention so What about making a lower access varient of centcom IDs? ![Helpful I hope](https://user-images.githubusercontent.com/81941674/272569174-205a4657-7679-485c-97c2-818944c54b4a.png) Also here are the new ID stuff in convenient skyrat format, I already added the new centcom ID too if yalls want it [skyrat ID stuff.zip](https://github.com/Skyrat-SS13/Skyrat-tg/files/12803146/skyrat.ID.stuff.zip)

Oh, sweet. Well that solves that. Thanks much!

2023-10-10 21:51 UTC, HWSensum commented
I find that PR stupid. What the point of having bodyguard that has 6+ heads of staff, that he can not save due not having access.

CMO getting ripped appart, mangled and slowly gibbed?

- "Ples, open dor somon'e 😢 😭 "

Blueshield is not a part of sec, his goal is not to catch/kill antags, his goal is to protect the heads of staff and valuable personnel, so i see no reason for him having an AA.

2023-10-10 21:59 UTC, lessthnthree commented
I can't tell if you're arguing for the current access or against it.

2023-10-10 22:09 UTC, HWSensum commented
I am mad because it makes no sense. The idea of bodyguard is that he is someone who can protect you against any sorts of attacks or at least try to cover you with his body. Blueshield without access is an cuckold (sadly i have no other words to describe it). He will just look how his head of staff gets slaughtered and all what he can do - pray to gods that someone will open him a damn door.

2023-10-10 22:11 UTC, HWSensum commented
I'd rather have SOP's and weapon cary policy, because i rather be armed with an disabler, but atleast with direct access to any head of staff, than have a automatic lethal gun at any code but without access to VIP that i must protect.

2023-10-20 00:51 UTC, closed without merging