NRI Police Outfit Redesign
Skyrat-SS13/Skyrat-TG pull request #23709
Opened 2023-09-15 14:28 UTC by Stalkeros2

## About The Pull Request
Starting with the less important stuff, the old NRI police uniform is now gone, getting rid of another Flavrius sprite that didn't fit with the entirety of the codebase.
"NRI ERT" module has been renamed into, simply "NRI" module to better reflect its purpose, as it's no longer used by the NRI ERT only (Which I'll probably remove at a later date).
Now for the cool part: NRI Inspectors midround as well as the loadout have been given an entirely new outfit shamelessly copied from Disco Elysium's Revachol Citizens'/Citizen's Militia, -just like the colonial outfit-. Said outfits are, obviously, worn by the NRI police midround, among the new NRI Police armor set that's currently replacing that ancient as hell terribly green Z army Ratnik armor set, same for the NRI police gas mask.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/42087567/72c26ee0-759b-4fca-a149-52d5285d2089)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/42087567/41c9441c-7dfb-47f8-93ee-bc11b47a51ae)

## How This Contributes To The Skyrat Roleplay Experience
For the "boring" part: NRI module now actually represents what it does; unfitting sprites suck.
For the more interesting part:
Well, really though, unfitting sprites suck, since the previous NRI police uniform was overly militaristic. Ideally, this new outfit should make them feel themselves less aggressive ~~and less looking like weirdly shaded mess~~ and better represents their purpose as diplomats and inspectors instead of an actual combat personnel.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/42087567/72c26ee0-759b-4fca-a149-52d5285d2089)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/42087567/41c9441c-7dfb-47f8-93ee-bc11b47a51ae)
</details>

## Changelog

:cl: Stalkeros
add: NRI Police outfit full redesign. Sunrise, Parabellum.
imageadd: NRI MODsuit palette swapped.
/:cl:

2023-09-17 19:28 UTC, vinylspiders reviewed
As far as the code side of things are concerned, this looks good to me other than those nitpicks

2023-09-17 19:28 UTC, vinylspiders commented on modular_skyrat/modules/encounters/code/nri_raiders.dm
> +	department_color = "#1f3347"
```suggestion
	department_color = "#1f3347"
```

Could you make these colors defines like how it's done in `code/_DEFINES/colors.dm`?

You could make a new file for it e.g. `code/_DEFINES/~skyrat_defines/colors.dm`.

2023-09-17 19:28 UTC, vinylspiders commented on modular_skyrat/modules/encounters/code/nri_raiders.dm
> +	subdepartment_color = "#c0c0c0"
```suggestion
	subdepartment_color = "#c0c0c0"
```
Same thing here

2023-09-17 19:28 UTC, vinylspiders commented on modular_skyrat/modules/encounters/code/nri_raiders.dm
> +	backpack_contents = list(/obj/item/storage/box/nri_survival_pack/raider = 1, /obj/item/ammo_box/magazine/m9mm_aps = 3, /obj/item/gun/ballistic/automatic/pistol/ladon/nri = 1, /obj/item/crucifix = 1,
```suggestion
	backpack_contents = list(
		/obj/item/storage/box/nri_survival_pack/raider = 1,
		/obj/item/ammo_box/magazine/m9mm_aps = 3,
		/obj/item/gun/ballistic/automatic/pistol/ladon/nri = 1,
		/obj/item/crucifix = 1,
		/obj/item/clothing/mask/gas/nri_police = 1,
		/obj/item/modular_computer/pda/nri_police = 1,
	)
```

2023-09-18 18:58 UTC, vinylspiders approved these changes

2023-09-18 19:02 UTC, vinylspiders commented
Just have to wait for spritetainer approval now, code is 👍

2023-09-18 21:01 UTC, GoldenAlpharex requested changes
Other than these few comments, this should be good to go. The sprites are nice.

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_heads.dm
> +/datum/loadout_item/head/rcm
```suggestion
/datum/loadout_item/head/imperial_police_cap
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_masks.dm
> +/datum/loadout_item/mask/rcm
```suggestion
/datum/loadout_item/mask/imperial_police_gas_mask
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_neck.dm
> +/datum/loadout_item/neck/rcm
```suggestion
/datum/loadout_item/neck/imperial_police_boatcloak
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_shoes.dm
> +/datum/loadout_item/shoes/rcm
```suggestion
/datum/loadout_item/shoes/imperial_police_half_boots
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/loadout_datum_suit.dm
> +/datum/loadout_item/suit/rcm
```suggestion
/datum/loadout_item/suit/imperial_police_plate_carrier
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/loadouts/loadout_items/under/loadout_datum_under.dm
> +/datum/loadout_item/under/jumpsuit/rcm
```suggestion
/datum/loadout_item/under/jumpsuit/imperial_police_uniform
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/new_russian_empire/code/police_outfit.dm
> +	Silver NRI police insignia is woven right above its visor."
```suggestion
		Silver NRI police insignia is woven right above its visor."
```

2023-09-18 21:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/encounters/icons/pda.dmi
Why did you have to duplicate basically all of the PDA sprites into this file? Can't you just make your PDA frame point to here and the other overlays to the base file?

2023-09-20 04:07 UTC, Stalkeros2 commented on modular_skyrat/modules/encounters/icons/pda.dmi
Answered in Discord; PDAs call for initial icon file instead of the main one for their overlays.
I'll probably change it upstream at a later date; was meant to reply to this yesterday but oh well.

2023-10-11 15:04 UTC, Stalkeros2 commented
Screw this, not feeling like it at all.

2023-10-11 15:04 UTC, closed without merging