[MODULAR] Re-enables the Detective's Replacement Revolver(ID-locked) Goodie Crate being purchasable since all NT guns are being removed from imports and the Detective's revolver is job gear that needs to be able to be replaced by Cargo
Skyrat-SS13/Skyrat-TG pull request #23701
Opened 2023-09-15 04:27 UTC by Iamgoofball

## About The Pull Request

Re-enables the Detective's Replacement Revolver(ID-locked) Goodie Crate being purchasable since all NT guns are being removed from imports and the Detective's revolver is job gear that needs to be able to be replaced by Cargo.

Waiting on #23424 to go through first

## How This Contributes To The Skyrat Roleplay Experience

Job equipment should always be replaceable via cargo, we disabled the goodie pack for this when the .38 was put into Imports for the crew to access but since all NT guns are being removed from imports, the revolver needs to be replacable again. This goodie is locked to the Detective's access already so the only way to get it is to have a Detective straw buy it for you if you aren't a detective.

## Proof of Testing

this is just removing a single override

## Changelog
:cl:
fix: Re-enables the Detective's Replacement Revolver(ID-locked) Goodie Crate being purchasable since all NT guns are being removed from imports and the Detective's revolver is job gear that needs to be able to be replaced by Cargo
/:cl:

2023-09-19 14:47 UTC, Iamgoofball commented
stale b gone

2023-09-27 03:34 UTC, Iamgoofball commented
.

2023-09-27 07:08 UTC, vinylspiders requested changes
This should probably be re-added to company imports with the other guns rather than being in a goodies crate.

2023-09-27 07:44 UTC, Iamgoofball commented
@vinylspiders that prevents the access lock from applying to it

2023-09-27 12:06 UTC, vinylspiders commented
> @vinylspiders that prevents the access lock from applying to it

Yeah, I've been told by other staff members that this is intentional.

LMGs or SC-2 E-gun aren't accessed locked, and it'd be odd to have the detective's revolver be the one exception.

2023-09-27 15:31 UTC, Iamgoofball commented
@vinylspiders to be clear, @paxilmaniac is intentionally removing the import entry for it as part of their new gun overhaul; this is a bugfix for the oversight created by that in that detectives cannot replace their revolver, which is job equipment

2023-09-27 21:01 UTC, vinylspiders commented
> @vinylspiders to be clear, @Paxilmaniac is intentionally removing the import entry for it as part of their new gun overhaul; this is a bugfix for the oversight created by that in that detectives cannot replace their revolver, which is job equipment

Yep I am aware, hence why I used the word 're-added'.

2023-10-23 18:47 UTC, projectkepler-ru commented
are you still working on this @Iamgoofball

2023-12-25 12:37 UTC, Gandalf2k15 commented
honestly thinking about going back through that massive nuke PR and adjusting it, not sure if this will be valid then

2024-01-01 16:48 UTC, merged