More Freighter Fixes
Skyrat-SS13/Skyrat-TG pull request #23847
Opened 2023-09-21 23:04 UTC by Lunar248

## About The Pull Request
Fixes the MOD cores on the freighter ghost role not functioning, replacing them with the correct object.

## How This Contributes To The Skyrat Roleplay Experience
This just fixes the already existing MOD cores, and provides the freighter with the ability to make a couple of MOD suits on their own.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/134661012/911eadf9-d6e7-4d4f-a13a-8ab4af819155)

</details>

## Changelog

:cl:
fix: Replaces the incorrect MOD cores with working ones.
/:cl:

2023-09-21 23:16 UTC, vinylspiders approved these changes

2023-09-21 23:45 UTC, vinylspiders requested changes

2023-09-21 23:45 UTC, vinylspiders commented on _maps/RandomRuins/SpaceRuins/skyrat/cargodiselost.dmm
> +/obj/item/mod/core/standard,
```suggestion
```
I think you may have accidentally added an extra one here. (Or if it was on purpose make sure you doc it in the changelog as qol)

2023-09-22 19:36 UTC, Lunar248 commented on _maps/RandomRuins/SpaceRuins/skyrat/cargodiselost.dmm
> +/obj/item/mod/core/standard,
Oh- yeah, I think that was unintentional! I'll quickly change that.

2023-09-22 23:50 UTC, vinylspiders approved these changes

2023-09-22 23:51 UTC, merged