mold mob fixes
Skyrat-SS13/Skyrat-TG pull request #23871
Opened 2023-09-23 19:53 UTC by tf-4

## About The Pull Request

Fixes a few issues with mould mobs. It was a combination of my misunderstanding of how basic mob AI attacks work and forgetting about a component.

It also deletes the mobs on death because there tend to be loads of them and it's annoying to clear up.

Also removes the centaur mutagen splash on death as it did nothing but make a massive mess which is not fun.

### Opening as a draft because I didn't bother testing this yet.

## Changelog
:cl:
fix: Fixed some weirdness with mould mob attacks.
qol: Mold mobs delete themselves on death.
/:cl:

2023-09-24 18:28 UTC, RatFromTheJungle commented
u should make the mobs explode and drop guns like pinatas

2023-10-04 08:01 UTC, vinylspiders requested changes
Looks good to me though otherwise, assuming this is all good to go now

2023-10-04 08:01 UTC, vinylspiders commented on modular_skyrat/modules/mold/code/mold_mobs.dm
> +		ignite_target.ignite_mob()
```suggestion
	ignite_target.ignite_mob()
```
`ignite_mob()` checks for this right away so you should be good with just calling the proc

https://github.com/Skyrat-SS13/Skyrat-tg/blob/f3e8e852f80ce9e6f33773abdd532bcbb7114887/code/modules/mob/living/living.dm#L1594-L1596

2023-10-04 16:56 UTC, vinylspiders approved these changes

2023-10-04 17:01 UTC, merged