[SEMI-MODULAR] Makes defibs work badly on synths, moving the perferred method of synth revival to the revival surgery, also makes said surgery a lot faster
Skyrat-SS13/Skyrat-TG pull request #23923
Opened 2023-09-26 01:26 UTC by nikothedude

## About The Pull Request

Title. Defibs now EMP the synth lightly and cause a temporary brain trauma for ~90 seconds, but also, notably, _give the user a giant warning telling them how bad of an idea using a defib is_.

## How This Contributes To The Skyrat Roleplay Experience

Robotics is already the synth medical place. Synths go there for repairs, my wounds are specifically set up to be best treated in robo (mostly), robo can order synth meds, however theres one thing that still remains that sends synths to medical sometimes: defibs.

I can't really blame it. The revival surgery SUCKED and took SUPER long to do. However, with this PR, the length of the surgery was reduced by something like 80% and a lot of steps were removed. With this change, I hope to finally mark robotics as the synth medical place.

I still kept defibs as a method for reviving synths, since TG balance basically depends on the assumption that defibs can revive someone. There may be places in the game where removing the ability to defib entirely would be unfair to synths.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
balance: Defibrilators now EMP synths and apply a temporary brain trauma for 90 seconds to them
balance: Synth revival surgery time and steps vastly reduced/streamlined
/:cl:

2023-09-26 01:26 UTC, nikothedude commented
Drafted because I need to make a few more changes, also because I'm not sure of the balance implications just yet

I think it's fine in quotation marks, but Im gonna wait a bit regardless

2023-10-08 16:28 UTC, GoldenAlpharex requested changes, later dismissed

2023-10-08 16:28 UTC, GoldenAlpharex commented on code/game/objects/items/defib.dm
> +// SKYRAT EDIT ADDITION END - SYNTH REVIVAL
Make this modular, since it's a whole new proc. And document it, please.

2023-10-09 18:40 UTC, vinylspiders requested changes

2023-10-09 18:40 UTC, vinylspiders commented on code/game/objects/items/defib.dm
> +						to_chat(H, span_userdanger("[user]'s defibrilator fires a powerful jolt of electricity into your vulnerable circuitry, overloading it!"))
```suggestion
						to_chat(H, span_userdanger("[user]'s defibrillator fires a powerful jolt of electricity into your vulnerable circuitry, overloading it!"))
```

2023-10-09 18:40 UTC, vinylspiders commented on code/game/objects/items/defib.dm
> +							if (trauma)
```suggestion
							if (!QDELETED(trauma))
```
Just to be safe

2023-10-09 18:40 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/defib.dm
> +	qdel(trauma)
```suggestion
	QDEL_NULL(trauma)
```

2023-10-09 18:40 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/surgery/robot_chassis_restoration.dm
> +// Should be a very quick surgery, its meant to replace defibs (mostly!)
```suggestion
// Should be a very quick surgery, it's meant to replace defibs (mostly!)
```

2023-10-09 18:40 UTC, vinylspiders commented on code/game/objects/items/defib.dm
> +		to_chat(user, span_boldwarning("[H] is a synthetic lifeform! This defibrilator probably isn't calibrated to revive [H.p_them()] properly and could have some serious consequences! \
```suggestion
		to_chat(user, span_boldwarning("[H] is a synthetic lifeform! This defibrillator probably isn't calibrated to revive [H.p_them()] properly and could have some serious consequences! \
```

2023-10-09 19:15 UTC, nikothedude commented on modular_skyrat/modules/synths/code/defib.dm
> +	qdel(trauma)
may I ask why? QDELETED already nullchecks, and the argument isnt saved into memory

2023-10-09 19:34 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/defib.dm
> +	qdel(trauma)
EDIT: my eyes were looking at the wrong thing. This is fine yes.

2023-10-09 19:41 UTC, vinylspiders approved these changes

2023-10-09 20:00 UTC, merged