[MODULAR] Puts waterbreathing on the species quirks page, adds a waterbreathing quirk
Skyrat-SS13/Skyrat-TG pull request #23989
Opened 2023-09-28 13:31 UTC by nikothedude

## About The Pull Request

Title. 

## How This Contributes To The Skyrat Roleplay Experience

1. It was undocumented before, so while it  could be inferred, it wasn't actually stated that aquatics could breathe underwater.

2. Waterbreathing is sufficiently generic of a thing to be given to anything. You can breathe water for a lot of reasons, and it is hardly an impactful effect whatsoever. The only times it comes into play is when you're, well, under water, which is very rare.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/59709059/325b7aba-c735-46f3-bc31-c363b76922e3)

Its scary how good of a coder I am
  
</details>

## Changelog

:cl:
add: A waterbreathing quirk
qol: Waterbreathing is now documented on species pages of the species that have it
/:cl:

2023-09-28 13:39 UTC, Jolly-66 commented
I don't know why I thought this said "waterbathing"

2023-09-29 00:35 UTC, vinylspiders requested changes
Otherwise looks good to me. A good addition!

2023-09-29 00:35 UTC, vinylspiders commented on modular_skyrat/master_files/code/datums/traits/good.dm
> +	medical_record_text = "Patient possesses biology compatable with aquatic respiration."
```suggestion
	medical_record_text = "Patient possesses biology compatible with aquatic respiration."
```

2023-09-29 00:35 UTC, vinylspiders commented on modular_skyrat/master_files/code/datums/traits/good.dm
> +	gain_text = span_notice("You feel the moisture of the air in your lungs.")
Maybe you could tweak this to make it clearer that it's a positive, satisfactory feeling. So it's a lil clearer what's going on.

2023-09-29 00:35 UTC, vinylspiders commented on modular_skyrat/master_files/code/datums/traits/good.dm
> +	lose_text = span_danger("You feel normally wary around large bodies of water!")
For symmetry, might be better if you kept the description along the same theme as the `gain_text` (aka, something along the lines of no longer feeling satisfaction from breathing moisture).

2023-09-29 02:19 UTC, nikothedude commented on modular_skyrat/master_files/code/datums/traits/good.dm
> +	lose_text = span_danger("You feel normally wary around large bodies of water!")
fair

2023-09-29 05:23 UTC, vinylspiders approved these changes

2023-09-29 05:24 UTC, merged