fixes the tendril blessing (respawning)
Skyrat-SS13/Skyrat-TG pull request #24028
Opened 2023-09-29 23:36 UTC by jjpark-kb

## About The Pull Request
fixes the tendril blessing (respawning) that has been broken for... some amount of time.
fixes the sacrifice counter at the round end

## How This Contributes To The Skyrat Roleplay Experience
bugs aren't fun, and when a feature gets broken its nice to have it fixed.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/bd9cc988-3f84-4540-99e4-794a308c19d0)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/91d98c81-05fd-45e2-b457-f7579b6dbd86)

</details>

## Changelog

:cl:
fix: the ashwalker tendril will allow you to respawn again (the tendril blessing)
fix: the round end report will accurately report ashwalker sacrifices
/:cl:

2023-09-29 23:56 UTC, vinylspiders commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	if(!(user.ckey in team.players_spawned))//one per person unless you get a bonus spawn SKYRAT EDIT: Original: if(!(user.key in team.players_spawned))
Weird, what's the difference in use between `key` and `ckey` anyway? I wonder if this should be changed upstream too?

2023-09-29 23:56 UTC, vinylspiders reviewed
Looks good though

2023-09-29 23:57 UTC, vinylspiders approved these changes

2023-09-30 00:04 UTC, jjpark-kb commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	if(!(user.ckey in team.players_spawned))//one per person unless you get a bonus spawn SKYRAT EDIT: Original: if(!(user.key in team.players_spawned))
I think the main difference is capitalization lol... some of the other team spawn ones use ckey as well.

2023-09-30 00:25 UTC, lessthnthree commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	if(!(user.ckey in team.players_spawned))//one per person unless you get a bonus spawn SKYRAT EDIT: Original: if(!(user.key in team.players_spawned))
I'd just like to know why SR needs it and TG doesn't, yeah.

2023-09-30 00:43 UTC, vinylspiders commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	if(!(user.ckey in team.players_spawned))//one per person unless you get a bonus spawn SKYRAT EDIT: Original: if(!(user.key in team.players_spawned))
Yeah--looked into it and apparently, ckey = your byond username decapitalized and with spaces removed. I didn't even know byond usernames could have spaces.

This should probably be fixed upstream but I don't really see an issue with fixing it here first.

2023-09-30 01:05 UTC, vinylspiders requested changes

2023-09-30 01:05 UTC, vinylspiders commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	team.players_spawned += (spawned_human.ckey) //SKYRAT EDIT: Original: team.players_spawned += (spawned_human.key)
Okay, I've looked into this a little deeper now.

There actually -is- a problem with this.

It looks like for some reason the `key` is stored `team.players_spawned` from the start.

In modular it also uses key here, so that should to be changed as well:

https://github.com/Skyrat-SS13/Skyrat-tg/blob/ebebe387d956d9e8ad07f123706116220239bfcd/modular_skyrat/modules/ashwalkers/code/buildings/ash_tendril.dm#L102

2023-09-30 01:12 UTC, vinylspiders commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	team.players_spawned += (spawned_human.ckey) //SKYRAT EDIT: Original: team.players_spawned += (spawned_human.key)
I've taken the liberty of changing that.  For now this can go through for a hotfix but I did make an upstream PR to replace the skyrat edits eventually.

2023-09-30 01:13 UTC, vinylspiders approved these changes

2023-09-30 01:14 UTC, merged