[MANUAL MIRROR Moves gauze removal signals to gauze destroy, removing weird seep_gauze usages + misc improvements
Skyrat-SS13/Skyrat-TG pull request #24027
Opened 2023-09-29 22:03 UTC by nikothedude

## About The Pull Request

Mirror of https://github.com/Skyrat-SS13/Skyrat-tg/pull/24023

Title.

## How This Contributes To The Skyrat Roleplay Experience

Gauze removal was handled by using seep_gauze(9999) instead of just deleting it, which was really fucking weird??

This makes behavior more sensical and modular (you can remove gauze without using seep_gauze now).

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/59709059/e27c44cc-264c-4075-b01a-ae13f2a835ed)

</details>

## Changelog

:cl:
code: Gauze removal is now handled by the gauze's destroy instead of seep_gauze
/:cl:

2023-09-29 22:04 UTC, lessthnthree commented
Do you want https://github.com/Skyrat-SS13/Skyrat-tg/pull/24023 closed?

2023-09-29 22:04 UTC, nikothedude commented
WHY DID IT SQUASH THE FUCKING COMMITS GITHUB I FUCKING HATE YOU

2023-09-29 22:05 UTC, nikothedude commented
> Do you want #24023 closed?

sure

2023-09-29 22:49 UTC, vinylspiders commented
> WHY DID IT SQUASH THE FUCKING COMMITS GITHUB I FUCKING HATE YOU

At least this one is shorter than the last one...

For future reference, my process for making manual mirrors is using git bash:
If you haven't already, create a remote for tgstation on your repo.
`git remote add tgstation https://github.com/tgstation/tgstation`
Then whenever you need to update it to get new commits:
`git fetch tgstation` 
Then do a cherry pick:
`git cherry-pick -m 1 2bdadebbadab0de472efd9993d4b1595daee16e9` 
(that last arg is the merge commit for this mirror, but obviously you'd just swap that out with whatever one you want to cherry pick.

And then your commits should just be there, no squashing.

2023-09-29 23:17 UTC, vinylspiders requested changes
Looks good to me otherwise!

2023-09-29 23:17 UTC, vinylspiders commented on modular_skyrat/modules/medical/code/wounds/medical.dm
> +	var/mob/living/carbon/cached_owner = gauzed_bodypart?.owner
```suggestion
	var/mob/living/carbon/previously_gauzed = gauzed_bodypart?.owner
```
This is just a clarity thing, it's not actually being cached here this is just a local var that only exists in the frame of this proc. Caching implies it's committed to memory.

Just changing it to be less misleading.

2023-09-29 23:17 UTC, vinylspiders commented on modular_skyrat/modules/medical/code/wounds/medical.dm
> +	cached_owner?.update_bandage_overlays()
```suggestion
	previously_gauzed?.update_bandage_overlays()
```

2023-09-29 23:17 UTC, vinylspiders commented on modular_skyrat/modules/medical/code/wounds/medical.dm
>  		var/mob/living/carbon/C = usr
```suggestion
		var/mob/living/carbon/carbon_user = usr
```
I know you didn't write this to begin with but just getting rid of the single letter vars while we're in here

2023-09-29 23:17 UTC, vinylspiders commented on modular_skyrat/modules/medical/code/wounds/medical.dm
> +		if(!do_after(C, (self ? SELF_AID_REMOVE_DELAY : OTHER_AID_REMOVE_DELAY), target = gauzed_bodypart.owner))
```suggestion
		var/self = (carbon_user == gauzed_bodypart.owner)
		carbon_user.visible_message(span_notice("[carbon_user] begins removing [name] from [self ? "[gauzed_bodypart.owner.p_Their()]" : "[gauzed_bodypart.owner]'s" ] [gauzed_bodypart.name]..."), span_notice("You begin to remove [name] from [self ? "your" : "[gauzed_bodypart.owner]'s"] [gauzed_bodypart.name]..."))
		if(!do_after(carbon_user, (self ? SELF_AID_REMOVE_DELAY : OTHER_AID_REMOVE_DELAY), target = gauzed_bodypart.owner))
```

2023-09-29 23:17 UTC, vinylspiders commented on modular_skyrat/modules/medical/code/wounds/medical.dm
> +		C.visible_message(span_notice("[C] removes [name] from [self ? "[gauzed_bodypart.owner.p_Their()]" : "[gauzed_bodypart.owner]'s" ] [gauzed_bodypart.name]."), span_notice("You remove [name] from [se
```suggestion
		carbon_user.visible_message(span_notice("[carbon_user] removes [name] from [self ? "[gauzed_bodypart.owner.p_Their()]" : "[gauzed_bodypart.owner]'s" ] [gauzed_bodypart.name]."), span_notice("You remove [name] from [self ? "your" : "[gauzed_bodypart.owner]'s" ] [gauzed_bodypart.name]."))
```

2023-09-29 23:17 UTC, vinylspiders commented on modular_skyrat/modules/medical/code/wounds/medical.dm
>  			gotten.forceMove(get_turf(C))
```suggestion
		if(gotten && !carbon_user.put_in_hands(gotten))
			gotten.forceMove(get_turf(carbon_user))
```

2023-09-30 01:42 UTC, vinylspiders approved these changes

2023-09-30 01:42 UTC, merged