[MODULAR] NIFSofts with TGUI now match the TGUI theme of the NIF
Skyrat-SS13/Skyrat-TG pull request #24036
Opened 2023-09-30 06:53 UTC by softcerv

## About The Pull Request
This PR makes it so that the two NIFSofts that have TGUI, soulcatcher and poem of communal souls, both share the same TGUI as their parent NIF.

## How This Contributes To The Skyrat Roleplay Experience
This is adds a nice little bit of consistency, helping better tie NIFSofts to the NIF they belong to. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/68373373/7f6c99a7-1a22-4bcb-860c-d1f2d08a4bac)

</details>

## Changelog

:cl:
qol: NIFSofts now use the same TGUI as their parent NIF.
/:cl:

2023-09-30 08:56 UTC, Elli-Skala commented
We couldn't make a sub type for a syndicate nif theme could we?

2023-10-04 06:16 UTC, vinylspiders requested changes

2023-10-04 06:16 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/nifsofts/soulcatcher.dm
> +	current_soulcatcher.ui_theme = ui_theme
```suggestion
	if(!istype(current_soulcatcher))
		stack_trace("[src] ([REF(src)]) tried to update its theme when it was missing a linked_soulcatcher component!")
		return FALSE
	current_soulcatcher.ui_theme = ui_theme
```

2023-10-04 06:19 UTC, vinylspiders approved these changes

2023-10-04 06:34 UTC, merged