[MODULAR] Allows individuals within the SAD to reject the treatment, ejecting them with no changes made
Skyrat-SS13/Skyrat-TG pull request #24047
Opened 2023-09-30 22:32 UTC by nikothedude

## About The Pull Request

Title. At the end of a SAD cycle it queries the occupant, asking if their genes reject the treatment. If yes, they are ejected with no changes. This works even if they're unconscious.

## How This Contributes To The Skyrat Roleplay Experience

Honestly, fuck the SAD. Hate this thing. Makes it impossible to take body transformation seriously when everyone just says "you can just use the SAD". Well now I have a rational IC reason as to why I can't baby.

1. I really don't like having to justify, as my hyper-rational character, why I don't want to use the SAD.
2. Unconscious people can be forced into the SAD against their will, without the option of saying no. And yes, you could just call medical malpractice, but it doesn't revert what the SAD did, the other person at max gets arrested (and keeps doing it), etc.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Will open when I have some
</details>

## Changelog

:cl:
qol: SAD patients can now reject the treatment at the last step, preventing any changes from being made
/:cl:

2023-09-30 22:32 UTC, nikothedude commented
maybe a balance change instead, but honestly i dont know what to label this

2023-09-30 22:42 UTC, softcerv commented
> maybe a balance change instead, but honestly i dont know what to label this

QoL is fine, because it makes the item easier to deal with from the perspective of a user (patient)

2023-10-01 12:42 UTC, tf-4 commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +	var/failure = (tgui_alert(occupant, "The SAD you are within is about to rejuvinate you. Do your genes accept or reject this?", "Rejuvinate", list("Yes", "No"), timeout = 10 SECONDS) == "No")
```suggestion
	var/failure = (tgui_alert(occupant, "The SAD you are within is about to rejuvenate you. Do your genes accept or reject this?", "Rejuvenate", list("Accept", "Reject"), timeout = 10 SECONDS) == "Reject")
```

2023-10-09 14:12 UTC, vinylspiders requested changes

2023-10-09 14:12 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +/// Ejects the occupant after asking them if they want to accept the rejuvination. If yes, they exit as their preferences character.
```suggestion
/// Ejects the occupant after asking them if they want to accept the rejuvenation. If yes, they exit as their preferences character.
```

2023-10-09 14:12 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +	// Allows unconcious people to reject unconsentual stuff
```suggestion
	// Allows unconscious people to reject non-consensual stuff
```

2023-10-09 14:12 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +		say("ERROR: Occupant genes have rejected the procedure. Please try again later.")
```suggestion
		say("ERROR: Occupant genes have willfully rejected the procedure. You may try again if you think this was an error.")
```
I think it's good to make it clearer that a user is answering a prompt here so they don't keep trying and spamming the user with prompts.

2023-10-09 14:12 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +	var/failure = (tgui_alert(occupant, "The SAD you are within is about to rejuvenate you. Do your genes accept or reject this?", "Rejuvenate", list("Accept", "Reject"), timeout = 10 SECONDS) == "Rejec
Also this has the effect of making it so that if the prompt times out, it acts as if the user accepted. Not sure if that's what you were going for or not but just pointing it out!

2023-10-09 14:41 UTC, nikothedude commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +	var/failure = (tgui_alert(occupant, "The SAD you are within is about to rejuvenate you. Do your genes accept or reject this?", "Rejuvenate", list("Accept", "Reject"), timeout = 10 SECONDS) == "Rejec
that was the intent, yeah, though come to think of it i might switch it around

2023-10-09 14:44 UTC, nikothedude commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +	var/failure = (tgui_alert(occupant, "The SAD you are within is about to rejuvenate you. Do your genes accept or reject this?", "Rejuvenate", list("Accept", "Reject"), timeout = 10 SECONDS) == "Rejec
reason being: if the intent is to prevent non-consensual SAD-ing, it shouldnt work if no consent can be given period (if the person is AFK)

2023-10-09 16:01 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +	var/failure = (tgui_alert(occupant, "The SAD you are within is about to rejuvenate you. Do your genes accept or reject this?", "Rejuvenate", list("Accept", "Reject"), timeout = 10 SECONDS) == "Rejec
Mm well in that case I'll wait for you to update it then. Though it's fine by me if you want to leave it this way

2023-10-09 19:53 UTC, vinylspiders requested changes

2023-10-09 19:53 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +		failure_text = "ERROR: Treatment illicited no response from occupant genes. Subject may be suffering from Sudden Sleep Disorder."
```suggestion
		failure_text = "ERROR: Treatment elicited no response from occupant genes. Subject may be suffering from Sudden Sleep Disorder."
```

2023-10-09 19:53 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +		failure_text = "ERROR: Occupant genes have willfully rejected the procedure. You may try again if you think this was an error."
I don't know if you'd want to add a different message for the timeout (could be useful to tell if they're just afk vs actively refusing). If you had interest in doing that I believe null is returned by `tgui_alert()` in that case

2023-10-09 19:55 UTC, vinylspiders commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +		failure_text = "ERROR: Occupant genes have willfully rejected the procedure. You may try again if you think this was an error."
You could just save tgui_alert()'s return value to a var and check for no, then yes, and else do the timeout message. But this is only a suggestion, I'm fine with it being as it is now if you are.

2023-10-09 20:01 UTC, nikothedude commented on modular_skyrat/modules/self_actualization_device/code/self_actualization_device.dm
> +		failure_text = "ERROR: Occupant genes have willfully rejected the procedure. You may try again if you think this was an error."
im fine with how it is rn tbh

2023-10-09 20:08 UTC, vinylspiders approved these changes

2023-10-09 20:20 UTC, merged