Removes more cases of the round end report telling on people's ckeys
Skyrat-SS13/Skyrat-TG pull request #24094
Opened 2023-10-03 17:55 UTC by GoldenAlpharex

## About The Pull Request
What is says on the tin, really.

## How This Contributes To The Skyrat Roleplay Experience
We made the decision that ckeys shouldn't appear in the round end reports, so this ensures that consistency and allows people to remain properly anonymous if that is their choice.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/58045821/a013761b-e06e-4833-83c9-afd55027ea78)

Don't have achievements enabled on my local for a lack of a database, so hard to prove, but I know it'll work right.

</details>

## Changelog

:cl: GoldenAlpharex
fix: The round end report will no longer expose people's ckeys for the achievements they obtained through the round, nor when they're contractor support agents.
/:cl:

2023-10-04 05:04 UTC, lessthnthree approved these changes

2023-10-04 08:21 UTC, vinylspiders requested changes

2023-10-04 08:21 UTC, vinylspiders commented on modular_skyrat/modules/contractor/code/datums/contractor_datum.dm
> +			contractor_support_unit += "<br><b>[partner.partner_mind.current.name]</b> was their contractor support unit."
```suggestion
			var/mob/living/carbon/human/partner_mob = partner_mind.current
			contractor_support_unit += "<br><b>[partner_mob.name]</b> was [partner_mob.p_their()] contractor support unit."
```

2023-10-05 21:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/contractor/code/datums/contractor_datum.dm
> +			var/mob/living/carbon/human/partner_mob = partner_mind.current
```suggestion
			var/mob/living/carbon/human/partner_mob = partner.partner_mind.current
```

2023-10-06 00:51 UTC, vinylspiders approved these changes

2023-10-06 00:52 UTC, merged