replaces interdynes .50 cal with the sidano gunset
Skyrat-SS13/Skyrat-TG pull request #24098
Opened 2023-10-03 20:18 UTC by RatFromTheJungle

## About The Pull Request

as promised, now that the Sol-guns PR is merged, interdyne's McFifty is sent to the shadowrealm, may it rest in fishies

## How This Contributes To The Skyrat Roleplay Experience

they prolly shouldn't show up with an entire barret .50 cal in their bag, when they're supposed to be 'subtle'

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  Mmmmmmmm Fish!
</details>

## Changelog

:cl:
balance: Interdyne now spawns with Sidano SMG's, instead of .50 snipers

/:cl:

2023-10-03 20:23 UTC, Paxilmaniac commented
Make a new gun case subtype that gives them the /evil subtype of the sindano

2023-10-04 07:47 UTC, vinylspiders requested changes

2023-10-04 07:47 UTC, vinylspiders commented on code/modules/mob_spawn/ghost_roles/mining_roles.dm
> +	r_hand = /obj/item/storage/toolbox/guncase/skyrat/carwo_large_case/sindano // SKYRAT EDIT Original: /obj/item/gun/ballistic/rifle/sniper_rifle
```suggestion
	r_hand = /obj/item/storage/toolbox/guncase/skyrat/carwo_large_case/sindano // SKYRAT EDIT - Original: /obj/item/gun/ballistic/rifle/sniper_rifle
```

2023-10-04 07:48 UTC, vinylspiders approved these changes

2023-10-04 17:07 UTC, vinylspiders commented
If you wanted to follow Paxil's suggestion you could put a new type `/obj/item/storage/toolbox/guncase/skyrat/carwo_large_case/sindano/evil` where `weapon_to_spawn = /obj/item/gun/ballistic/automatic/sol_smg/evil/no_mag` 
https://github.com/Skyrat-SS13/Skyrat-tg/blob/2d8200eb21ffe181f69dbe8e3e52dda93dc5da0b/modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/carwo_defense_systems/gunsets.dm#L24-L38

right below the base one.

2023-10-05 08:51 UTC, vinylspiders approved these changes

2023-10-05 08:56 UTC, merged