[MODULAR] Ports & Enhances Paper Masks
Skyrat-SS13/Skyrat-TG pull request #24180
Opened 2023-10-07 19:07 UTC by Nerev4r

## About The Pull Request
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/3f54eecd-0162-43d0-86ee-c6ae23d3a2c6)
I ported some paper masks from Virgo, and my pals Motho and Sheets did a fantastic job of respriting them.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/8294d41b-711d-4eb1-9014-1ea97be44cb1)
These do not hide your face, and can be swapped at any time.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/47cf31a4-812c-4cf3-8456-2d98dac1e977)
They do function as internals.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/0d8a4938-7701-4c22-a733-ed2573e7ea67)
And thanks to some code from @vinylspiders, they can be layered under your hair if you really want.

## How This Contributes To The Skyrat Roleplay Experience
I think these look cool and have a wide array of uses.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/d545a5f5-d19d-4bd6-abe7-1cba86708fba)
Especially if you're a mime.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
 The above screencaps.
</details>

## Changelog
:cl:
image: The crew's knowledge of origami and papercrafting has been extended to making paper masks. Find them in the loadout, or just make them!
/:cl:

2023-10-07 19:27 UTC, W4rd3nn commented
omg they look way better in game than i expected yippeeee

2023-10-07 19:49 UTC, HoodMilk commented
Finally we can smile like :3

2023-10-07 19:54 UTC, nikothedude commented
SQUID GAME ‼️

2023-10-07 21:14 UTC, vinylspiders requested changes
Can you please move this code out of `modular_skyrat/master_files/code/modules/clothing/masks/_masks.dm` and into a new file in `modular_skyrat\modules\customization\modules\clothing\masks` instead?  

`master_files` is for when you want to override existing TG code.

2023-10-07 21:14 UTC, vinylspiders commented on modular_skyrat/master_files/code/modules/clothing/masks/_masks.dm
> +	alternate_worn_layer = FACEMASK_LAYER
```suggestion
```
It should already be `FACEMASK_LAYER` so we should be able to just leave this null by default.

2023-10-07 21:20 UTC, vinylspiders requested changes

2023-10-07 21:20 UTC, vinylspiders commented on modular_skyrat/master_files/code/modules/clothing/masks/_masks.dm
> +	var/wear_over_hair = TRUE
```suggestion
	/// Whether or not the mask is currently being layered over hair
	var/wear_over_hair = TRUE
```

2023-10-07 21:20 UTC, vinylspiders commented on modular_skyrat/master_files/code/modules/clothing/masks/_masks.dm
> +	register_context()
```suggestion
	register_context()
	if(wear_over_hair)
		alternate_worn_layer = BACK_LAYER
```

2023-10-07 22:47 UTC, vinylspiders approved these changes

2023-10-08 11:59 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/code/tailoring.dm
> +	reqs = list(/obj/item/paper = 2, /obj/item/pen = 1)
Only complaint would be that the pen should be a tool_behavior so it doesn't get consumed on each craft.

But that's something you'd have to add upstream because a pen tool_behavior doesn't exist.

Alternatively you could have it so that it only takes paper to craft a 'blank' one and then you can change the style by attacking it with a pen. Just an idea, I don't really mind if you keep it this way.

2023-10-08 20:05 UTC, merged

2023-10-09 02:52 UTC, Sheits commented
I didnt do any work on these btw