[MODULAR] Table flipping now throws anything on it in the direction it was flipped
Skyrat-SS13/Skyrat-TG pull request #24232
Opened 2023-10-09 21:29 UTC by nikothedude

## About The Pull Request

Title. Had this idea while fixing table flipping.

## How This Contributes To The Skyrat Roleplay Experience

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/59709059/4fd7a88f-8679-4953-84d8-c57db7d7997a

</details>

## Changelog

:cl:
add: Table flipping now throws everything on the table
/:cl:

2023-10-09 22:03 UTC, W4rd3nn commented
speedmerge NOW

2023-10-10 00:06 UTC, vinylspiders requested changes

2023-10-10 00:06 UTC, vinylspiders commented on modular_skyrat/modules/tableflip/code/flipped_table.dm
> +			movable_entity.safe_throw_at(throw_target, range = 1, speed = 1, force = MOVE_FORCE_NORMAL, gentle = TRUE)
```suggestion
			if(!ismob(movable_entity) && !isobj(movable_entity))
				continue
			if(movable_entity.throwing || (movable_entity.movement_type & (FLOATING|FLYING)))
				continue
			movable_entity.safe_throw_at(throw_target, range = 1, speed = 1, force = MOVE_FORCE_NORMAL, gentle = TRUE)
```
Love this but I worry that we might accidentally move some things that are not meant to see the light of day. Best add some additional protections. Also there is floaty stuff.

2023-10-10 01:23 UTC, vinylspiders commented
This is optional obviously but it might be funny to add a little description of the pacifist gently turning the table over (and either not playing the sound or making it low volume) lol

2023-10-10 01:24 UTC, vinylspiders approved these changes

2023-10-10 02:23 UTC, nikothedude commented
sure

2023-10-10 04:07 UTC, merged