[MODULAR] [NO GBP] Adds alien/standard surgery tools + bonesetter to robo exofab
Skyrat-SS13/Skyrat-TG pull request #24248
Opened 2023-10-10 15:17 UTC by nikothedude

## About The Pull Request

I just kinda forgot to do this in my last PR.

## How This Contributes To The Skyrat Roleplay Experience

There really isnt any reason they should be locked to adv. tools only.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/59709059/d5774547-fade-4e02-b576-1b1ec94af648)

</details>

## Changelog

:cl:
add: Robo can now print standard and alien surgical tools
/:cl:

2023-10-10 23:35 UTC, vinylspiders requested changes
Just to make it clearer that we're looking at overrides here, if it wasn't obvious at first glance.

Usually they live in master_files so it's useful to mark them as such when you are putting them in a module.

2023-10-10 23:35 UTC, vinylspiders commented on modular_skyrat/modules/science_tools/medical_tool_designs.dm
> +// Standard tools
```suggestion
// Standard tool overrides
```

2023-10-10 23:35 UTC, vinylspiders commented on modular_skyrat/modules/science_tools/medical_tool_designs.dm
> +// Alien tools
```suggestion
// Alien tool overrides
```

2023-10-10 23:35 UTC, vinylspiders commented on modular_skyrat/modules/science_tools/medical_tool_designs.dm
> +// Advanced tools
```suggestion
// Advanced tool overrides
```

2023-10-10 23:43 UTC, nikothedude commented
gotcha

2023-10-11 14:41 UTC, vinylspiders approved these changes

2023-10-11 14:42 UTC, merged