Sindano Inhand Sprite that were previously missing
Skyrat-SS13/Skyrat-TG pull request #24362
Opened 2023-10-16 13:25 UTC by projectkepler-ru

## About The Pull Request
sindano inhand sprite that were previously missing

## How This Contributes To The Skyrat Roleplay Experience
without this it has a jarring yellow dot when you look to the north because we're using the c20r as a base inhand icon 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  Inhand icon

</details>

## Changelog

:cl:
image: gave the sindano  proper inhand icon for both variant
/:cl:

2023-10-16 13:28 UTC, projectkepler-ru commented
Worried it may not look very good rn, waiting on feedback

2023-10-16 16:36 UTC, vinylspiders requested changes
Thanks for doing this--love to see inhand sprites. The colors look good. But there are a couple things which I think you picked up on in your worries:

1) There is a gap here and here between the mob and the gun with the East/West sprites, and it's also pushed up too far into the mob so it looks like part of the gun is just sawed straight off. The borders of the hidden bits need to conform to the mob's shape.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/314784f5-bf18-4aae-864b-0df40ac9ccf7)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/2cb1e55f-5cfd-43cb-ae2a-8aacceb90cff)

2) North/South is too lateral, it doesn't quite look right with how these guns are meant to be held.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/84e950fd-da36-4a33-b211-bb179bf77f85)

3) The back of it is a bit long and skinny, it kinda looks like it's floating on certain backdrops.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/b9ca4bd2-97e8-4cb7-8816-06e28206cff2)


The overall size and the way it's being held makes it read as more like a shotgun I think?

I think if you just sort of recolored the c20 sprite a bit and got rid of the yellow it'd look less 'off' and more like a SMG. 

![dreamseeker_jrs7pKlLvc](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/211bba61-c6cc-4774-ac7d-596f32e194dd)

That's what I would do, anyway.

2023-10-16 16:36 UTC, vinylspiders commented on modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/carwo_defense_systems/submachinegun.dm
> +	inhand_icon_state = "cindano"
How come the `icon_state`s are spelled with a 'c'?

2023-10-16 17:17 UTC, projectkepler-ru commented on modular_skyrat/modules/modular_weapons/code/company_and_or_faction_based/carwo_defense_systems/submachinegun.dm
> +	inhand_icon_state = "cindano"
I'll get change that, must've been my brain damage

2023-10-16 17:18 UTC, projectkepler-ru commented
@vinylspiders  Willl make a patch now and see whats wrong
it looked fine on my end- might just be im using a much more squished monitor

2023-10-16 17:19 UTC, projectkepler-ru commented
The other reason why I wanted this inhand sprites was because the gun needs two hand to fire vs the c20r one handedness so recoloring the c20r wont do it for me

2023-10-16 17:54 UTC, Paxilmaniac commented
> The other reason why I wanted this inhand sprites was because the gun needs two hand to fire vs the c20r one handedness so recoloring the c20r wont do it for me

This is not correct, the reason i made it use the one hand c20 sprite to begin with was to show that it did not need two hands.

2023-10-16 19:26 UTC, projectkepler-ru commented
> > The other reason why I wanted this inhand sprites was because the gun needs two hand to fire vs the c20r one handedness so recoloring the c20r wont do it for me
> 
> This is not correct, the reason i made it use the one hand c20 sprite to begin with was to show that it did not need two hands.

weird? let me check again

2023-10-27 08:36 UTC, vinylspiders approved these changes

2023-10-27 08:40 UTC, vinylspiders commented
Pinged @GoldenAlpharex to take a final look, looks good to me though

2023-10-27 11:37 UTC, GoldenAlpharex approved these changes
Good work on this, and thank you @vinylspiders for the good sprite reviews too, very thorough!

2023-10-27 11:37 UTC, merged