NTC Skild/Takbok choice
Skyrat-SS13/Skyrat-TG pull request #24527
Opened 2023-10-23 17:57 UTC by projectkepler-ru

## About The Pull Request
gives  you the option to pick between skild and takbok as NTC. Should work fine

## How This Contributes To The Skyrat Roleplay Experience
Because what if my NTC is a revolver person and not a handgun person? I might just prefer one over the other. It's a small differences but I've actually ask myself and everyone alot in game and off game during playing as hos/captain "Am I a revolver or a handgun person" and while people often replied humerously like "get a grenade launcher" or "use a lush wish whip" I really want people to be able to make that choice and have that same question I did. So, revolver or handgun?

## Proof of Testing
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/99981766/1caf98c2-c556-43a4-ab3e-e2ea815dbace)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/99981766/e0bfb16d-5545-4f04-b3d9-70984d5c483a)
compiled and ran just fine on my end during testing so it should be fine

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/99981766/0a754b8c-8513-4cfc-ab65-16658a0a36d6)

</details>

## Changelog

:cl:
add: a gun beacon option for the NTC to pick between two of his magnum pistol choices, fully modular and can be messed with by anyone in the future if more guns are added.
/:cl:

2023-10-23 18:32 UTC, Plum-but-gayer commented
This is a fun little flavor deal, I'd love to see more stuff like this giving people round start gear choices (like how miners get to pick their first item, etc.) Bring back sec gun tickets :)

2023-10-23 18:37 UTC, projectkepler-ru commented
@Plum-but-gayer 
the thing I wrote on why it's good for RP isn't some weird shitpost either, I genuinely didn't know if I preferred revolver or a handgun so now I'm forcing you all to suffer the same philosophy

2023-10-23 20:04 UTC, desertmote commented
Not a fan. I play this role too and can buy my weapon of choice 10 minutes in without bounties. (wespe)
gun beacons returning seems like a slippery slope to me. You mention bubber in your comment, why not PR this there?

~~NTC is often supposed to be a non-combatant paper pusher. It makes sense their gun is an awful to use gun from Sol. Giving them an NRI/CIN(forgot if they were separate) gun that is actually pretty meta mechanically doesnt click right.~~

2023-10-23 20:09 UTC, Paxilmaniac commented
> Giving them an NRI/CIN(forgot if they were separate) gun that is actually pretty meta mechanically doesnt click right.

The Takbok is still a Sol gun, its just a revolver version of the pistol they spawn with

2023-10-23 20:14 UTC, desertmote commented
> > Giving them an NRI/CIN(forgot if they were separate) gun that is actually pretty meta mechanically doesnt click right.
> 
> The Takbok is still a Sol gun, its just a revolver version of the pistol they spawn with

My bad, I confused it for the shotgun shell revolver, disregard that part of my comment.

2023-10-23 21:30 UTC, projectkepler-ru commented
> Not a fan. I play this role too and can buy my weapon of choice 10 minutes in without bounties. (wespe) gun beacons returning seems like a slippery slope to me. You mention bubber in your comment, why not PR this there?
> 
> NTC is often supposed to be a non-combatant paper pusher. It makes sense their gun is an awful to use gun from Sol. Giving them an NRI/CIN(forgot if they were separate) gun that is actually pretty meta mechanically doesnt click right.

I mean that's your choice if you want to use wespe I'm just giving them the pick between the two magnum pistol options

2023-11-04 18:10 UTC, GoldenAlpharex requested changes

2023-11-04 18:10 UTC, GoldenAlpharex commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +	new /obj/item/storage/fancy/cigarettes/cigars/havana(src)
Why not just spawn in the gun boxes instead? No need to do things like this, just spawn the guncase.

2023-11-04 21:20 UTC, projectkepler-ru commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +	new /obj/item/storage/fancy/cigarettes/cigars/havana(src)
Oh sure

2023-11-05 04:19 UTC, GoldenAlpharex requested changes

2023-11-05 04:19 UTC, GoldenAlpharex commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +	company_message = span_bold("Supply Pod incoming please standby") //Did I?
```suggestion
	company_message = span_bold("Supply Pod incoming, please stand by") //Did I?
```

2023-11-05 05:14 UTC, projectkepler-ru commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +	company_message = span_bold("Supply Pod incoming please standby")
```suggestion
	company_message = span_bold("Supply Pod incoming please stand by")
```
Nvm should've changed it to that

2023-11-07 04:01 UTC, GoldenAlpharex requested changes

2023-11-07 04:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +		selectable_gun_types = list("Takbok" = /obj/item/storage/toolbox/guncase/skyrat/pistol/trappiste_small_case/takbok, "Skild" = /obj/item/storage/toolbox/guncase/skyrat/pistol/trappiste_small_case/sk
```suggestion
	var/static/list/selectable_gun_types = list(
		"Takbok" = /obj/item/storage/toolbox/guncase/skyrat/pistol/trappiste_small_case/takbok,
		"Skild" = /obj/item/storage/toolbox/guncase/skyrat/pistol/trappiste_small_case/skild,
	)
```

2023-11-07 04:01 UTC, GoldenAlpharex commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_consultant.dm
> +/obj/item/choice_beacon/ntc //I promise you, this will solve everything
Also, maybe chill out with the weird commentary on the sides of this, it just adds more commentary that doesn't serve any purpose.

2023-11-09 18:56 UTC, GoldenAlpharex approved these changes
Looks good now!

2023-11-09 18:56 UTC, merged