[MODULAR] Good Assistant Points: Help the station, get credits and chicken nuggets!
Skyrat-SS13/Skyrat-TG pull request #24576
Opened 2023-10-25 01:46 UTC by Iamgoofball

## About The Pull Request

https://github.com/Skyrat-SS13/Skyrat-tg/assets/4081722/8c403edd-4b56-45b8-a968-851040239471

Assistants now spawn with Good Assistant Points Punchcards in lieu of money.
The punchcards can be punched by heads of staff, who spawn with punchers.
A punchcard can have six punches at maximum.
Turning in a punchcard gives 50 credits for each punch directly to your ID card's bank account, a box of chicken nuggets, and a new fresh punchcard.
Don't lose your punchcard, or you can't replace it.

## How This Contributes To The Skyrat Roleplay Experience

1. Nobody enjoys doing bounties.
2. A punchcard system managed by heads of staff rewards interacting with the station and crew at large in an RP fashion, instead of hustling away at bounties or grinding out exportables.
3. Everyone loves chicken nuggets!

## Proof of Testing

See About The Pull Request

## Changelog

:cl:
add: Assistants now spawn with Good Assistant Points Punchcards in lieu of money.
add: The punchcards can be punched by heads of staff, who spawn with punchers.
add: A punchcard can have six punches at maximum.
add: Turning in a punchcard gives 50 credits for each punch directly to your ID card's bank account, a box of chicken nuggets, add: and a new fresh punchcard.
add: Don't lose your punchcard, or you can't replace it.
/:ck:

2023-10-25 01:56 UTC, jjpark-kb commented
I really, really enjoy this PR lmao

2023-10-25 01:59 UTC, lessthnthree requested changes
Add the card to the wallet allowed items

2023-10-25 02:00 UTC, lessthnthree commented on code/modules/jobs/job_types/assistant.dm
> +	paycheck = 0 // Get a job. Job reassignment changes your paycheck now. Get over it. // SKYRAT EDIT - Punchcards, original is PAYCHECK_LOWER
You can do paycheck and backpack_contents in a modular file.

2023-10-25 02:01 UTC, lessthnthree commented
Good idea, adds some flavor and roleplay opportunities for assistants who are bored and don't know what to do to kill time.

2023-10-25 02:27 UTC, GoldenAlpharex commented
I don't like the fact that it makes it so assistants _have_ to work to get money. This is just worse than bounty cubes, because now you HAVE to work if you want to make money, it's no longer optional, and that just makes it all the more tedious when you want to roleplay.

I'm blocking this until assistants are paid again.

2023-10-25 02:40 UTC, ChillyLobster commented
Speedmerge this ASAP?

2023-10-25 02:57 UTC, chemistrymain2 commented
> I don't like the fact that it makes it so assistants _have_ to work to get money. This is just worse than bounty cubes, because now you HAVE to work if you want to make money, it's no longer optional, and that just makes it all the more tedious when you want to roleplay.
> 
> I'm blocking this until assistants are paid again.

Should you not, conventionally, have to work to get money? Especially as an assistant, so you don't just mill around and accrue it without contributing in any way.

Unlike bounties, this actually has you helping out in some meaningful way, and offers opportunities for 'actually being an assistant', and not something like 'collect 20 bear asses and whine at cargo to send your cubes.'

If you, like...don't want to work, you can just ask for money from someone else.

2023-10-25 02:58 UTC, Iamgoofball commented
@chemistrymain2 golden requested assistant paychecks be re-added in full so they've been re-added in full

2023-10-25 02:59 UTC, chemistrymain2 commented
> @chemistrymain2 golden requested assistant paychecks be re-added in full so they've been re-added in full

ok

2023-10-25 04:46 UTC, SomeRandomOwl commented
another question i have, what is preventing heads of staff from just punching the whole card and giving people (especially their friends) free and infinite money?

2023-10-25 14:01 UTC, Iamgoofball commented
honor system at the moment, i had a fever dream about how to prevent it last night but i need to remember what it was

2023-10-25 14:48 UTC, lessthnthree commented
> honor system at the moment, i had a fever dream about how to prevent it last night but i need to remember what it was

Cooldown stored on the card, puncher can punch as it sees fit, card can't be instantly filled

2023-10-25 14:55 UTC, lessthnthree commented on modular_skyrat/modules/cargo/code/items/gbp_punchcard.dm
> +/datum/outfit/job/cmo
```
/datum/outfit/job/cmo/pre_equip(mob/living/carbon/human/H, visualsOnly)
    . = ..()
    backpack_contents += list(/obj/item/gbp_puncher = 1)
```
You don't need to override the whole list, then we'd have to update it every time TG changes. Just add to it in pre_equip

2023-10-25 15:17 UTC, lessthnthree commented on code/__DEFINES/~skyrat_defines/economy.dm
> +#define PAYCHECK_ASSISTANT 10
Don't believe this is needed since you are no longer modifying paycheque

2023-10-25 15:19 UTC, lessthnthree commented on modular_skyrat/modules/automapper/code/area_spawn_entries.dm
> +	target_areas = list(/area/station/cargo/lobby, /area/station/construction/storage_wing) // lmao imagine map standardization
```suggestion
	target_areas = list(/area/station/cargo/lobby, /area/station/cargo/boutique, /area/station/construction/storage_wing) // lmao imagine map standardization
```

2023-10-25 20:59 UTC, SomeRandomOwl commented
Also one thing i think should be included is logging for when a card is punched or redeemed into the admin log so we can see if people are trying to abuse it

2023-10-25 23:59 UTC, YakumoChen commented
Its a funny idea but falls flat because of how tedious item interaction is, and very annoying for heads of staff. 

Maybe the HoP would like it, but heads already have a department of underlings to boss around to get things done.

Also having a new item I might never use to bloat my bag as a Head sounds annoying. Can't you tie this into stamps or something?

2023-10-26 00:06 UTC, YakumoChen commented
The money also needs to come from somewhere, namely departmental budget accounts

2023-10-26 04:34 UTC, lessthnthree approved these changes

2023-10-26 05:34 UTC, merged