laser carbines for everyone* - disabler/laser carbines now for sale by microstar
Skyrat-SS13/Skyrat-TG pull request #24597
Opened 2023-10-26 05:18 UTC by Hatterhat

## About The Pull Request
- adds disabler SMGs and laser carbines to microstar at the same price points of their semi-auto variants
- uncomments the egun/lasergun crates

## How This Contributes To The Skyrat Roleplay Experience
- disabler SMGs and laser carbines makes them more available without having to jump through hoops (buying a crate and cracking it or something idk)
- uncommenting the energy/laser gun crates makes it so there's a dichotomy for sec: do you want to buy the gun crates off the dep budget to keep the armory topped up? or do you just want to leave buying guns as an issue for yourselves? either way, the option is now yours

## Changelog

:cl:
balance: Disabler SMGs and laser carbines (the full-auto sidegrades to the disabler and laser gun, respectively) are now available for purchase through Microstar.
balance: Energy and laser gun crates are now available through Cargo again.
/:cl:

2023-10-26 05:33 UTC, Stalkeros2 commented
add tasers too pls? :pleading_face:

2023-10-26 16:54 UTC, GoldenAlpharex requested changes
What good does this do to the game? I'm not really convinced by the PR body.

2023-10-26 18:12 UTC, Plum-but-gayer commented
I think adding carbines/smgs to microstar at like a slightly increased cost (+50/100 creds) might work a lil better. Historically I've been a big fan of bringing laser crates back but now that there's no stock limit of how much we can order from corporate orders there's do difference in the HoS buying 3 allstars with corpo vs buying 3 allstars with crates.

imo just add the two new guns with a small price bump, leave the crates. Keeps our gun buying mechanics consistent.

2023-10-26 19:09 UTC, Iamgoofball commented
@GoldenAlpharex its guncargo, the justification for guncargo is the same as it's always been

2023-10-27 01:46 UTC, chemistrymain2 commented
> What good does this do to the game? I'm not really convinced by the PR body.

These are guns conventionally available in crates and instead they should be available through guncargo for the same reason we allow high-power ballistics to be purchasable through guncargo.

The laser carbines and disabler smgs are simply tg guns instead of our custom ballistics, but they're balanced (if not weaker than) our current available guns.

2023-10-27 02:29 UTC, Hatterhat commented
> What good does this do to the game? I'm not really convinced by the PR body.

As it stands, the laser carbines and disabler SMGs are available through crates - and nothing else. This is in contrast to the energy gun and laser gun, which are mainly available through the imports system (guncargo).

The uncommenting of the crates for the laser guns and eguns, and the addition of the disabler SMG and laser carbine to the imports system, unifies the two, so that they are both available through both sources; I'm open to killing off the crates and including the carbine/SMG crates in that, and leaving them in the imports.

As above, they're intended to have the same overall damage output as their semi-auto counterparts; double battery, but half damage. I suppose I could also bump up the price as well, to reflect the increased ease of use autofire grants them.

2023-11-05 16:09 UTC, Plum-but-gayer commented
So what's the word on this? Is it an issue of bringing egun/laser crates back or is there something else that's an issue?

2023-11-07 03:59 UTC, projectkepler-ru commented
> So what's the word on this? Is it an issue of bringing egun/laser crates back or is there something else that's an issue?

golden is busy me think

2023-11-09 19:08 UTC, GoldenAlpharex requested changes

2023-11-09 19:08 UTC, GoldenAlpharex commented on modular_skyrat/modules/company_imports/code/armament_datums/microstar_energy.dm
> +	cost = PAYCHECK_CREW * 5
I feel like they could probably be just a tad bit more expensive than the non-automatic variant, as I suspect they're likely stronger than said non-automatic variants. Maybe just a `PAYCHECK_CREW * 6` could be enough, for now at least.

2023-11-15 16:31 UTC, GoldenAlpharex approved these changes
Looks good, let's try it out!

2023-11-15 16:32 UTC, merged