[Modular QOL] Service Borg reagent shakers alphabetized
Skyrat-SS13/Skyrat-TG pull request #24604
Opened 2023-10-26 20:33 UTC by Zergspower

## About The Pull Request

Does as it says, makes the list of reagents be alphabetical intead of a mixmash of chaos

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/22140677/80dc6e2b-4052-4fdc-b35f-f5518679223b)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/22140677/c1206ee3-274e-4126-88c5-e744b3668992)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/22140677/45435e74-b957-4bf5-b833-92b66504b1f3)

I had planned on working on a new tgui but since we're using TG's i'll try it upstream instead first, same with the mining borg losing its ability to butcher when they get a diamond drill.

## How This Contributes To The Skyrat Roleplay Experience

lowering that time to make a drink

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:Zergspower
qol: Service Borg reagent mixers alphabetized
/:cl:

2023-10-27 08:29 UTC, vinylspiders requested changes
Otherwise looks good!

2023-10-27 08:29 UTC, vinylspiders commented on modular_skyrat/modules/ghostcafe/code/hilbertshotel_ghost.dm
> +	return promptAndCheckIn(user, user)
```suggestion
	attack_hand(user)
```
No need to dupe, right? attack_hand() has that adjacent check inbuilt in its call chain (we just need to add one more thing for it to work, see below).

2023-10-27 08:29 UTC, vinylspiders commented on modular_skyrat/modules/ghostcafe/code/hilbertshotel_ghost.dm
> +// borgos need love too
Also in the line after `anchored = TRUE` in this file add `interaction_flags_atom = INTERACT_ATOM_ATTACK_HAND`. This will enable `attack_hand()` to check for adjacent, incapacitated, etc by calling `_try_interact()`

It currently is not doing this, which it should be.

2023-10-27 08:29 UTC, vinylspiders commented on modular_skyrat/modules/ghostcafe/code/hilbertshotel_ghost.dm
> +// borgos need love too
```suggestion

// borgos need love too
```

2023-10-27 22:08 UTC, vinylspiders approved these changes

2023-10-28 01:28 UTC, merged

2023-10-28 01:55 UTC, Zergspower commented
oh - lmao i hadnt logged into GIT yet to check