Add: Forked Cybernetic Tongue & Lizard Voicebox
Skyrat-SS13/Skyrat-TG pull request #24616
Opened 2023-10-27 16:37 UTC by Floofies

## About The Pull Request

This PR adds two new synth tongues: the **forked cybernetic tongue** and the **robotic lizard voicebox**.

They are both made available in the Augments+ tab of the character preferences window.

- The **forked cybernetic tongue** is a subclassed version of the forked tongue. Has realistic-sounding hissing/lizard speech without monospace text.

- The **robotic lizard voicebox** is also a subclassed version of the forked tongue. Has synthetic-sounding hissing/lizard speech with monospace text, a new unique say-verb called "hizzing", and is also available as contraband in the RoboDrobe vendor.

## How This Contributes To The Skyrat Roleplay Experience

![cybertongue-lizard-3-preview](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/48053ff0-0558-4720-aa6b-8e706d8f747d) ![Screenshot 2023-10-27 121807](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/99cf389d-b895-4821-abf5-d0348dd3c3bd)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/d4a87ed4-e825-4bed-95bd-97a874abc1a2)

There are a lot of synthetic lizards on Skyrat! If you play as a synthlizard and you want to talk like a lizard, currently you need to put in an organic forked tongue. This PR adds the robotic lizard voicebox and forked cybernetic tongue, which can both fill the customization gap for a whole lot of players and allow them to have a 100% synthetic character.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![Screenshot 2023-10-27 122511](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/5777fe73-55e0-4fac-8e23-a0cc4d5803b7)
![Screenshot 2023-10-27 123511](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/19795bb0-3a95-490b-9e74-3d8592758519) ![Screenshot 2023-10-27 122253](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/b0e6b163-5db2-4f3e-bf54-d7d6ad35137d)
![Screenshot 2023-10-27 121920](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/8049ae9a-2407-4a5d-b68f-cac89cef23e6)
![Screenshot 2023-10-27 100400](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/cdcee8cd-fbbb-44c7-8230-3d9da821753c) ![Screenshot 2023-10-27 100312](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/d0780851-470e-41c0-97c7-73894d3b61d1) ![Screenshot 2023-10-27 091339](https://github.com/Skyrat-SS13/Skyrat-tg/assets/17753498/2a9bdd00-2b43-44c7-86e0-225e2eeac20b)

</details>

## Changelog

:cl: A.C.M.O.
add: Added the forked cybernetic tongue to Augments+.
add: Added the robotic lizard voicebox to Augments+ and the RoboDrobe vendor.
/:cl:

2023-11-04 23:16 UTC, GoldenAlpharex requested changes

2023-11-04 23:16 UTC, GoldenAlpharex commented on modular_skyrat/modules/organs/icons/cyber_tongue.dmi
For the sprite itself, could you try to follow the shape of the forked tongue a bit more? That way, it would give it a bit more of a smoother curve, because as it is, it kind of looks like it's just going down in a 45° angle.
The palette and such is perfectly fine, however, really just that nitpick- Basically, slap the forked tongue on the base robotic bit, and swap the colors around to be yours instead, and you should be good to go.

2023-11-19 20:42 UTC, Floofies commented
I have sat on this for a week. Oops! I will be changing the sprite soon

2023-12-20 17:18 UTC, Floofies commented
Visiting my mom's for christmas so I will probably have a lot of time to work on this in a day or two!

2023-12-25 12:17 UTC, Gandalf2k15 approved these changes
overly picky, I'm happy with this, LGTM.

2023-12-25 20:42 UTC, merged