buffs my reward item
Skyrat-SS13/Skyrat-TG pull request #24653
Opened 2023-10-30 00:41 UTC by honkpocket

## About The Pull Request
Muahaha, I will no longer be peppersprayed while wearing a face covering mask!
Also adds TTS flavor and that new `unique_death` sfx var.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![Code_djwvwTpcJU](https://github.com/Skyrat-SS13/Skyrat-tg/assets/77534246/307ee01c-5f03-422c-b7d5-688b872a813a)

</details>

## Changelog

N/a

2023-10-31 06:37 UTC, vinylspiders requested changes

2023-10-31 06:37 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	voice_filter = @{"[0:a] asetrate=%SAMPLE_RATE%*0.7,aresample=16000,atempo=1/0.7,lowshelf=g=-20:f=500,highpass=f=500,aphaser=in_gain=1:out_gain=1:delay=3.0:decay=0.4:speed=0.5:type=t [out]; [out]atem
```suggestion
```

Same thing with the xeno tongue PR--just makes it more maintainable and also clearer what kind of effect is being applied.

2023-10-31 06:37 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	use_radio_beeps_tts = TRUE
```suggestion

/obj/item/clothing/mask/animal/wolf/Initialize(mapload)
	. = ..()
	var/obj/item/clothing/mask/gas/sechailer/sechailer_type = /obj/item/clothing/mask/gas/sechailer
	voice_filter = initial(sechailer_type.voice_filter)
```

2023-10-31 22:33 UTC, vinylspiders approved these changes

2023-10-31 22:33 UTC, vinylspiders commented
Looks good to me. @GoldenAlpharex ?

2023-11-01 18:18 UTC, Iamgoofball commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	var/obj/item/clothing/mask/gas/sechailer/sechailer_type = /obj/item/clothing/mask/gas/sechailer
just make it a sechailer subtype instead of copying everything over from sec hailers in the vars and init

2023-11-01 18:19 UTC, desertmote commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	var/obj/item/clothing/mask/gas/sechailer/sechailer_type = /obj/item/clothing/mask/gas/sechailer
I tried that, but I don't want the compli-o-nator.

2023-11-01 23:31 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	var/obj/item/clothing/mask/gas/sechailer/sechailer_type = /obj/item/clothing/mask/gas/sechailer
^

You don't always want something to inherit every aspect of a thing.

2023-11-02 18:58 UTC, Iamgoofball commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	var/obj/item/clothing/mask/gas/sechailer/sechailer_type = /obj/item/clothing/mask/gas/sechailer
i forgot we put the compli-o-nator in the hailer and thought this thing had everything from it already lmao

2023-11-04 23:17 UTC, GoldenAlpharex approved these changes
I guess I've got nothing against this, yeah.

2023-11-04 23:17 UTC, merged