[MODULAR] Refactors Soulcatcher Souls into a Component
Skyrat-SS13/Skyrat-TG pull request #24717
Opened 2023-11-01 06:27 UTC by softcerv

## About The Pull Request
This PR refactors soulcatcher souls to have a majority of the things that let them interface with soulcatchers into a component that can be applied to living mobs.

## How This Contributes To The Skyrat Roleplay Experience
I don't have anything for this server planned just yet, but in general I want the soulcatcher code to be more flexible when potentially dealing with mobs that aren't soulcatcher souls. This _should_ also help improve the code quality of soulcatchers.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
soon, very soon :)

</details>

## Changelog

:cl:
refactor: refactors a majority of the code behind soulcatcher souls to be a component.
/:cl:

2023-11-01 06:27 UTC, softcerv commented
d'oh! meant to draft this while I do some testing.

2023-11-28 08:38 UTC, vinylspiders requested changes
I started reviewing this but haven't quite finished yet. Just remember to check those weakrefs when you resolve them, and null them if they resolve to a falsey value.

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +	return ..()
```suggestion
	return ..()
	
/datum/component/soulcatcher_user/UnregisterFromParent()
	UnregisterSignal(parent, list(
		COMSIG_SOULCATCHER_TOGGLE_SENSE,
		COMSIG_SOULCATCHER_SOUL_RENAME,
		COMSIG_SOULCATCHER_SOUL_RESET_NAME,
		COMSIG_SOULCATCHER_SOUL_CHANGE_ROOM,
		COMSIG_SOULCATCHER_SOUL_CHECK_INTERNAL_SENSES,
		COMSIG_SOULCATCHER_SOUL_REFRESH_APPEARANCE,
	))
```
Use this proc, which gets called by `/datum/component/Destroy()`. You can actually do these in a list like this. The proc name is not a typo, it's the same as the one you use on a singular signal for some reason.

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +	return TRUE
```suggestion
	return TRUE
	
/datum/component/soulcatcher_user/RegisterWithParent()
	RegisterSignal(parent, COMSIG_SOULCATCHER_TOGGLE_SENSE, PROC_REF(toggle_sense))
	RegisterSignal(parent, COMSIG_SOULCATCHER_SOUL_RENAME, PROC_REF(change_name))
	RegisterSignal(parent, COMSIG_SOULCATCHER_SOUL_RESET_NAME, PROC_REF(reset_name))
	RegisterSignal(parent, COMSIG_SOULCATCHER_SOUL_CHANGE_ROOM, PROC_REF(set_room))
	RegisterSignal(parent, COMSIG_SOULCATCHER_SOUL_CHECK_INTERNAL_SENSES, PROC_REF(check_internal_senses))
	RegisterSignal(parent, COMSIG_SOULCATCHER_SOUL_REFRESH_APPEARANCE, PROC_REF(refresh_soul_appearance))
```
Same as with the `UnregisterFromParent()`, this proc will get called by `/datum/component/New()`

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +	refresh_soul_apperance()
```suggestion
	refresh_soul_appearance()
```

2023-11-28 08:38 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/signals.dm
> +#define COMSIG_SOULCATCHER_SOUL_REFRESH_APPERANCE "soulcatcher_soul_refresh_apperance"
```suggestion
/// Whenever we need to refresh the internal appearance of a soulcatcher soul.area
#define COMSIG_SOULCATCHER_SOUL_REFRESH_APPEARANCE "soulcatcher_soul_refresh_appearance"
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_body_component.dm
> +	SEND_SIGNAL(soulcatcher_soul, COMSIG_SOULCATCHER_SOUL_REFRESH_APPERANCE)
```suggestion
	SEND_SIGNAL(soulcatcher_soul, COMSIG_SOULCATCHER_SOUL_REFRESH_APPEARANCE)
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +/datum/component/soulcatcher_user/proc/refresh_soul_apperance(datum/source)
```suggestion
/datum/component/soulcatcher_user/proc/refresh_soul_appearance(datum/source)
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +	var/mob/living/parent_mob = parent
```suggestion
	SIGNAL_HANDLER

	var/mob/living/parent_mob = parent
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +	if(!parent_mob?.mind || !istype(parent_mob.mind))
```suggestion
	if(istype(parent_mob) || isnull(parent_mob.mind))
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +		return FALSE
```suggestion
		current_room = null
		return FALSE
```
Don't forget to null your weakrefs if you find them to be falsey

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +		return FALSE
```suggestion
		current_room = null
		return FALSE
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +		return FALSE
```suggestion
		soulcatcher_user_component = null
		return FALSE
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_component.dm
> +		target_soul.forceMove(target_master_soulcatcher.parent)
```suggestion
	if(!target_master_soulcatcher)
		target_room.master_soulcatcher = null
	else if(target_master_soulcatcher != src)
		target_soul.forceMove(target_master_soulcatcher.parent)
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_component.dm
> +		original_room.current_souls -= target_soul
```suggestion
		original_room.current_souls -= target_soul
	else
		soul_component?.current_room = null
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_component.dm
> +	if(!parent_soulcatcher || !parent_soulcatcher.parent)
```suggestion
	if(!parent_soulcatcher)
		master_soulcatcher = null
		return FALSE
	else if(!parent_soulcatcher.parent)
		return FALSE
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_component.dm
> +		return FALSE
```suggestion
		master_soulcatcher = null
		return FALSE
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_tgui.dm
> +		return FALSE
```suggestion
		current_room = null
		return FALSE
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_tgui.dm
>  	data["communicate_as_parent"] = master_soulcatcher.communicate_as_parent
```suggestion
	if(!master_soulcatcher)
		current_soulcatcher_room.master_soulcatcher = null
	data["communicate_as_parent"] = master_soulcatcher?.communicate_as_parent
```
Should be false this way, otherwise it would runtime if that weakref didn't resolve to anything

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_tgui.dm
>  				if(soulcatcher_nifsoft && (parent != soulcatcher_nifsoft.parent_nif.resolve()))
```suggestion
				var/obj/item/organ/internal/cyberimp/brain/nif/installed_nif = soulcatcher_nifsoft.parent_nif.resolve()))
				if(!installed_nif)
					parent_nif = null
				if(soulcatcher_nifsoft && parent != installed_nif)
```

2023-11-28 08:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_tgui.dm
> +						available_rooms += nifsoft_soulcatcher.get_open_rooms()
```suggestion
						available_rooms += nifsoft_soulcatcher.get_open_rooms()
					else
						linked_soulcatcher = null
```

2023-11-28 08:47 UTC, vinylspiders requested changes

2023-11-28 08:47 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_tgui.dm
> +						linked_soulcatcher = null
```suggestion
						soulcatcher_nifsoft.linked_soulcatcher = null
```
Whoops, my bad here

2023-11-28 08:50 UTC, vinylspiders requested changes

2023-11-28 08:50 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_component.dm
> +		return FALSE
```suggestion
```

2023-11-28 08:55 UTC, vinylspiders requested changes

2023-11-28 08:55 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +		qdel(soulcatcher_action)
```suggestion
		QDEL_NULL(soulcatcher_action)
```

2023-11-28 08:55 UTC, vinylspiders commented on modular_skyrat/modules/modular_implants/code/soulcatcher/soulcatcher_user_component.dm
> +		qdel(leave_action)
```suggestion
		QDEL_NULL(leave_action)
```
Also want to make sure to null these

2024-01-11 00:51 UTC, softcerv commented
I be working on this again now (probably)

2024-01-14 07:51 UTC, softcerv commented
The time is now :3

2024-02-08 23:27 UTC, Useroth approved these changes
Very impressive work

2024-02-23 04:28 UTC, merged