Making notepad usable on laptops and consoles
Skyrat-SS13/Skyrat-TG pull request #24735
Opened 2023-11-02 08:21 UTC by NeonNik2245

## About The Pull Request
Makes it so that notepad can be used on consoles and laptops

## How This Contributes To The Skyrat Roleplay Experience
Now everyone have more places to write important information. Also someone who doesn't have PDA (ghost-role for example) will be able to use laptop's notepad.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
![laptop-notepad](https://github.com/Skyrat-SS13/Skyrat-tg/assets/106491639/693d6137-44c8-4787-8ea2-d1593906f145)

</details>

## Changelog

:cl:
qol: Make notepad available for everyone, who has only laptop or console.
/:cl:

2023-11-02 12:05 UTC, vinylspiders requested changes

2023-11-02 12:05 UTC, vinylspiders commented on code/modules/modular_computers/file_system/programs/notepad.dm
> +	usage_flags = PROGRAM_ALL //SKYRAT EDIT
Could you please make this modular?

If you're unsure how to do this, refer to the [modularization guide](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md)

(You just have to make a new file `modular_skyrat/master_files/code/modules/modular_computers/file_system/programs/notepad.dm` and override the `usage_flags` var with your changes there instead.)

2023-11-03 11:00 UTC, OrionTheFox commented
Is there any reason TG wouldn't want this? It's just a notepad app, having it run for any device seems like good QoL

2023-11-06 16:48 UTC, closed without merging

2023-11-06 16:48 UTC, vinylspiders commented
https://github.com/Skyrat-SS13/Skyrat-tg/pull/24820 Closing as you have taken it upstream 👍