Ports over the CM13 Zippo lighter sounds
Skyrat-SS13/Skyrat-TG pull request #24796
Opened 2023-11-05 05:56 UTC by ChickyRooster

## About The Pull Request
This adds in sounds for the zippo lighter for all those smokers on station! Sound ported from CM13

## How This Contributes To The Skyrat Roleplay Experience
More sounds for more immersion is always a good thing, and having sound play for the lighter adds to the overal atmosphere of the game.

## Proof of Testing

<details>
<summary>Screenshots/Videos

https://github.com/Skyrat-SS13/Skyrat-tg/assets/56152010/c05dc922-6d7e-4bcd-9d2e-1f0796b8cf1c

</summary>

</details>

## Changelog

:cl: AvianAviator, nauticall
Add: Added sounds to the Zippo lighter from CM13. Attributed to nauticall. 
/:cl:

2023-11-05 07:08 UTC, vinylspiders requested changes
The 'zippo_close' sound is good but I'm not a big fan of the ending flame noises for the 'zippo_open' sound, do you think you could trim the audio to just the initial strike/click? 

It sounds almost like someone is blowing into a mic at the end to me which is the opposite of immersive.

Could do this in Audacity if you are unsure of where to start. It's pretty straightforward to do.

2023-11-05 07:08 UTC, vinylspiders commented on code/game/objects/items/cigs_lighters.dm
> +		playsound(src, 'sound/items/zippo_close.ogg', 50, TRUE)
```suggestion
		playsound(src, 'sound/items/zippo_close.ogg', 50, TRUE) // SKYRAT EDIT ADDITION
```
These are nonmodular edits to core files so you need to mark them as such

2023-11-05 07:08 UTC, vinylspiders commented on code/game/objects/items/cigs_lighters.dm
> +	playsound(src, 'sound/items/zippo_open.ogg', 50, TRUE)
```suggestion
	playsound(src, 'sound/items/zippo_open.ogg', 50, TRUE) // SKYRAT EDIT ADDITION
```

2023-11-05 14:22 UTC, ChickyRooster commented
> It sounds almost like someone is blowing into a mic at the end to me which is the opposite of immersive.

I think you are mistaken by the cigarette being removed from the cigarette pack producing the bag ruffle sound, I 
should have made it more obvious or only foused on the lighter instead, 

Here's a video showcasing just the lighter, is this the sound you wanted changed?

https://github.com/Skyrat-SS13/Skyrat-tg/assets/56152010/86e50911-dad7-4ac4-882b-e13e000dc63a

2023-11-05 14:31 UTC, vinylspiders commented
> > It sounds almost like someone is blowing into a mic at the end to me which is the opposite of immersive.
> 
> I think you are mistaken by the cigarette being removed from the cigarette pack producing the bag ruffle sound, I should have made it more obvious or only foused on the lighter instead,
> 
> Here's a video showcasing just the lighter, is this the sound you wanted changed?
> Communist.Garden.Bravo.2023-11-05.15-17-18.mp4

You are absolutely correct. I just checked the sound files and they are in fact, fine. The first video threw me off with whatever that noise was.  No need to change anything, disregard the comment about that.

That said, one last thing I am noticing: you will want to put the sound files in `modular_skyrat/master_files/sound/items` instead of the TG folder they are in currently (and change the filepath in the code accordingly).

2023-11-05 14:48 UTC, ChickyRooster commented
Tested and changed, file paths should be all in order now :)

2023-11-05 14:48 UTC, vinylspiders approved these changes

2023-11-05 17:38 UTC, YakumoChen commented
Please give proper attribution by linking the PR adding this to cm13

Also consider this would benefit upstream (and us by extension)

2023-11-05 19:47 UTC, ChickyRooster commented
> Please give proper attribution by linking the PR adding this to cm13
> 
> Also consider if this would benefit upstream (and us and all other downstreams by extension)

While I could not find a PR, original commit has been linked, considered it as well.

2023-11-06 01:19 UTC, merged

2023-11-06 01:20 UTC, vinylspiders commented
> > Please give proper attribution by linking the PR adding this to cm13
> > Also consider if this would benefit upstream (and us and all other downstreams by extension)
> 
> While I could not find a PR, original commit has been linked, considered it as well.

All good. In this case since it's not really possible to find that and because it's a port it is fine.

2023-11-06 18:04 UTC, desertmote commented
This sfx was added to all lighters instead of just the zippo.

2023-11-08 10:03 UTC, OrionTheFox commented
> This sfx was added to all lighters instead of just the zippo.

love to see it.

2023-11-08 11:04 UTC, vinylspiders commented
> > This sfx was added to all lighters instead of just the zippo.
> 
> love to see it.

That is because for some reason, the zippo lighter is the basetype and all the other kinds of lighters are subtypes of it. Not how you'd expect it to be. https://github.com/Skyrat-SS13/Skyrat-tg/pull/24854

It is not a big deal in the grand scheme of things. With only two active maintainers for the whole repo we are bound to sometimes miss little things like this every now and then.