Adds the gifted "negative" quirk
Skyrat-SS13/Skyrat-TG pull request #24967
Opened 2023-11-13 01:45 UTC by TheSS13Melon

## About The Pull Request

JungleRat wanted a quirk that gave some freebie points. This perk, gifted, gives the player 6 free negative points to use on positive quirk points.

## How This Contributes To The Skyrat Roleplay Experience

Ultimately this allows more player expression without taking debilitating quirks.

## Proof of Testing

<details>
<summary>
<img src='https://cdn.discordapp.com/attachments/1116542480272347156/1173393009728045096/image.png?ex=6563ca66&is=65515566&hm=bb55aa0355e379ba20fa6bee3d559b601eceed0cb3e2d7d6d4983b9ca1c6a96a&'>
<img src='https://cdn.discordapp.com/attachments/1116542480272347156/1173392628264476713/image.png?ex=6563ca0b&is=6551550b&hm=3ae04db3ef688342fa8389bd165cf359e1ada9790ae0ffef838ded8b774913bd&'>

</summary>
  
</details>

## Changelog

:cl:
add: Adds a "negative" perk called gifted which gives 6 free points.
/:cl:

2023-11-13 02:19 UTC, burgerenergy commented
could

we not just non-modular edit in 4-6 more points

that said it should be obvious in the blurb that it doesn't do anything

2023-11-13 02:40 UTC, Stalkeros2 commented
Wtf based???

2023-11-13 02:57 UTC, W4rd3nn commented
time to be a med doc and scan and bully everyone who took this

2023-11-13 09:14 UTC, Iamgoofball commented
just add some freebie points OP this is a bad way to do it

2023-11-13 12:20 UTC, vinylspiders requested changes
Good otherwise, refer to the modularization guide [here](https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md) if you're not sure what I'm talking about with these comments.

We try to keep the Skyrat code separate from TG code is the short of it.

2023-11-13 12:20 UTC, vinylspiders commented on code/_globalvars/traits.dm
> +		"TRAIT_GIFTED" = TRAIT_GIFTED,
```suggestion
		"TRAIT_GIFTED" = TRAIT_GIFTED, // SKYRAT EDIT ADDITION
```

2023-11-13 12:20 UTC, vinylspiders commented on code/datums/quirks/negative_quirks/gifted.dm
> +	hardcore_value = 0
Move this to modular_skyrat\master_files\code\datums\quirks\negative.dm

2023-11-13 12:22 UTC, vinylspiders commented
All said though, if you are able to, as others have said it would be better to just add 6 points to the starting balance. But I think it might be slightly tricky due to the very odd way that quirk points are coded. 

You will likely have to make some tgui edits in addition to modifying `getQuirkBalance()` to start at -6 points (yes -6, the sign gets flipped after being passed to tgui...)

You can probably get some help from the contributor chat if you need it.

2023-11-13 17:52 UTC, HoodMilk commented
We should just make all quirks have 0 cost, you can still only take 6 positive ones anyway. Would allow people to take negative quirks for roleplaying reasons rather than "I need to tg balance my character".

2023-11-15 22:49 UTC, TheSS13Melon commented
> All said though, if you are able to, as others have said it would be better to just add 6 points to the starting balance. But I think it might be slightly tricky due to the very odd way that quirk points are coded.
> 
> You will likely have to make some tgui edits in addition to modifying `getQuirkBalance()` to start at -6 points (yes -6, the sign gets flipped after being passed to tgui...)
> 
> You can probably get some help from the contributor chat if you need it.

This is how junglerat wanted it done and iirc this is what was approved by the maintainers he got to sign off on it. I'd bring it up with him and the maintainers if we want to have it done like this.

2023-11-16 00:16 UTC, lessthnthree commented
> > All said though, if you are able to, as others have said it would be better to just add 6 points to the starting balance. But I think it might be slightly tricky due to the very odd way that quirk points are coded.
> > You will likely have to make some tgui edits in addition to modifying `getQuirkBalance()` to start at -6 points (yes -6, the sign gets flipped after being passed to tgui...)
> > You can probably get some help from the contributor chat if you need it.
> 
> This is how junglerat wanted it done and iirc this is what was approved by the maintainers he got to sign off on it. I'd bring it up with him and the maintainers if we want to have it done like this.

That... is the maintainer.

2023-11-16 00:18 UTC, TheSS13Melon commented
> > > All said though, if you are able to, as others have said it would be better to just add 6 points to the starting balance. But I think it might be slightly tricky due to the very odd way that quirk points are coded.
> > > You will likely have to make some tgui edits in addition to modifying `getQuirkBalance()` to start at -6 points (yes -6, the sign gets flipped after being passed to tgui...)
> > > You can probably get some help from the contributor chat if you need it.
> > 
> > 
> > This is how junglerat wanted it done and iirc this is what was approved by the maintainers he got to sign off on it. I'd bring it up with him and the maintainers if we want to have it done like this.
> 
> That... is the maintainer.

He didn't specify who signed off on it. Just that two maintainers signed off.

2023-11-16 00:26 UTC, lessthnthree commented
> > > > All said though, if you are able to, as others have said it would be better to just add 6 points to the starting balance. But I think it might be slightly tricky due to the very odd way that quirk points are coded.
> > > > You will likely have to make some tgui edits in addition to modifying `getQuirkBalance()` to start at -6 points (yes -6, the sign gets flipped after being passed to tgui...)
> > > > You can probably get some help from the contributor chat if you need it.
> > > 
> > > 
> > > This is how junglerat wanted it done and iirc this is what was approved by the maintainers he got to sign off on it. I'd bring it up with him and the maintainers if we want to have it done like this.
> > 
> > 
> > That... is the maintainer.
> 
> He didn't specify who signed off on it. Just that two maintainers signed off.

I'm the other one. So I suggest you take [vinylspiders](https://github.com/vinylspiders)'s suggestion.

2023-11-16 00:36 UTC, vinylspiders commented
> > > > All said though, if you are able to, as others have said it would be better to just add 6 points to the starting balance. But I think it might be slightly tricky due to the very odd way that quirk points are coded.
> > > > You will likely have to make some tgui edits in addition to modifying `getQuirkBalance()` to start at -6 points (yes -6, the sign gets flipped after being passed to tgui...)
> > > > You can probably get some help from the contributor chat if you need it.
> > > 
> > > 
> > > This is how junglerat wanted it done and iirc this is what was approved by the maintainers he got to sign off on it. I'd bring it up with him and the maintainers if we want to have it done like this.
> > 
> > 
> > That... is the maintainer.
> 
> He didn't specify who signed off on it. Just that two maintainers signed off.

We never really 'signed off' on this specific way of doing it, just kind of a general agreement that having more quirk points to play with would be a good idea. 

I think this way is a bit cumbersome and one of the concerns I had was people being grandfathered into having an extra 6 points worth of quirks should we ever remove this.

I will say, if you don't feel confident in being able to come up with a cleaner way then I'll accept this I guess. Still not a fan though.

2023-11-16 02:20 UTC, vinylspiders requested changes

2023-11-16 02:20 UTC, vinylspiders commented on code/_globalvars/traits.dm
> +		"TRAIT_GIFTED" = TRAIT_GIFTED, // skyrat edit addition
```suggestion
		"TRAIT_GIFTED" = TRAIT_GIFTED, // SKYRAT EDIT - ADDITION
```

2023-11-16 02:47 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/traits.dm
> +#define TRAIT_GIFTED "gifted" // adds -6 quirk to negative quirks for free points.
```suggestion
/// adds -6 quirk to negative quirks for free points.
#define TRAIT_GIFTED "gifted"
```
autodoc

2023-11-16 02:52 UTC, vinylspiders approved these changes
After speaking on discord, I'm ok with this solution given the circumstances. 

If anyone wants to do a cleaner solution that modifies tgui they're welcome to do so at any point.

2023-11-16 03:14 UTC, vinylspiders commented on modular_skyrat/master_files/code/datums/quirks/negative.dm
> +	value = -6
```suggestion
	quirk_flags = QUIRK_HUMAN_ONLY|QUIRK_HIDE_FROM_SCAN
	value = -6
```
One more thing, this probably shouldn't show up on scans.

2023-11-16 03:36 UTC, merged