[MODULAR] Crate-b-gone
Skyrat-SS13/Skyrat-TG pull request #24990
Opened 2023-11-14 00:28 UTC by W4rd3nn

## About The Pull Request
This edits our aesthetic override module to pull crate icons from TG. This is in anticipation of #24988 and will be drafted until it is merged.

## How This Contributes To The Skyrat Roleplay Experience
These new visuals will maintain consistency, and these in general have much more depth and character than our current sprites.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  Will add when #24988 is merged
</details>

## Changelog

:cl:Motho
image: The FTU has replaced their aging fleet of advanced shipping containers. Sector 13 is among the first few localities to enjoy them.
/:cl:

2023-11-14 00:31 UTC, RatFromTheJungle commented
the new ones are much better, the previous were major yucky

2023-11-14 00:36 UTC, W4rd3nn commented
i was and still am an oldcrate head, but these will do....

2023-11-14 04:13 UTC, vinylspiders commented
Actually this one will have to come before https://github.com/Skyrat-SS13/Skyrat-tg/pull/24988 because it adds new icon states that aren't in our modular files and is failing CI due to that. Thanks for doing this

2023-11-14 04:34 UTC, vinylspiders requested changes
Should be good to undraft once that is done

2023-11-14 04:34 UTC, vinylspiders commented on modular_skyrat/modules/aesthetics/crates/code/crates.dm
>  /obj/structure/closet/crate
You can just remove this entire file and the `modular_skyrat/modules/aesthetics/crates/icons/crates.dmi` file as well as the 'crates' folder they're in.

2023-11-14 07:50 UTC, OrionTheFox commented on modular_skyrat/modules/aesthetics/crates/code/crates.dm
>  /obj/structure/closet/crate
DO check that we don't have 100% custom crates in there first, though. If we have a modular crate with the icon in there we don't want it losing its icon entirely.

2023-11-14 11:00 UTC, vinylspiders commented on modular_skyrat/modules/aesthetics/crates/code/crates.dm
>  /obj/structure/closet/crate
As far as I can tell there aren't any that are in use. There are some metal crate sprites that aren't being used for anything currently but I'm unsure if those are old TG sprites or if they're ours.

2023-11-15 03:21 UTC, W4rd3nn commented
OKAY MERGE IT NOOOOOOW!!!!!

2023-11-15 04:11 UTC, vinylspiders approved these changes

2023-11-15 04:19 UTC, merged