Adjusts BS Miner with a new updated overlay, slightly better code, and less annoying buzzing/beeping
Skyrat-SS13/Skyrat-TG pull request #25008
Opened 2023-11-14 18:26 UTC by Majkl-J

## About The Pull Request

Mechanically, nothing has changed. It works exactly the same as before, except now it also has lights to show you why it's not working. And the sound is no longer obnoxiously loud with a range of 17 and passing walls

The first light lights up red when something is wrong.
The second and third light signal if atmos is not working, being either crimson (Pressure high) or teal (Pressure low)
Fourth light lights up orange when temp is high
All lights will light up red when too close to another miner

## How This Contributes To The Skyrat Roleplay Experience

You will no longer have to hear an earpiercing buzz when standing near engineering or atmos.

## Proof of Testing

Have tested this already to prove that mechanically nothing has changed, but managed to close the debugger before taking screenshots, TBD

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
qol: Bluespace miner now has visual indication to its status and problem
sound: The sound on the bluespace miner is no longer earpiercingly loud
image: Added lights to the bluespace miner
refactor: Refactored bluespace miner code
/:cl:

2023-11-14 23:38 UTC, vinylspiders requested changes
Looks good to me otherwise

2023-11-14 23:38 UTC, vinylspiders commented on modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm
>  	add_overlay("miner_on")
```suggestion
	else
		add_overlay("miner_on")
```
Just in case this proc ever gets added onto by someone else, makes it a little clearer that this overlay should be exclusive to no error codes.

2023-11-14 23:38 UTC, vinylspiders commented on modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm
> +		if(mining_stat & BLUESPACE_MINER_HIGH_PRESSURE)
```suggestion
		else if(mining_stat & BLUESPACE_MINER_HIGH_PRESSURE)
```
Same idea

2023-11-14 23:38 UTC, vinylspiders commented on modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm
> +		if(mining_stat & BLUESPACE_MINER_HIGH_PRESSURE)
```suggestion
		else if(mining_stat & BLUESPACE_MINER_HIGH_PRESSURE)
```
Same as above, else implies this without a need for further comment

2023-11-14 23:38 UTC, vinylspiders commented on modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm
> +	update_appearance()
```suggestion
	var/previous_mining_stat = mining_stat
	// Generates the mining_stat to use for overlays and checks
	update_mining_stat()
	// Updates the overlays, if it is needed
	if(mining_stat != previous_mining_stat)
		update_appearance()
```
This ultimately ends up cutting and re-adding all the overlays each process() tick, which is expensive. Can we instead only do it as needed?

2023-11-14 23:38 UTC, vinylspiders commented on modular_skyrat/modules/bluespace_miner/code/bluespace_miner.dm
>  	if(environment.return_pressure() >= (ONE_ATMOSPHERE * 1.5))
```suggestion
	else if(environment.return_pressure() >= (ONE_ATMOSPHERE * 1.5))
```
This shouldn't be able to be both, right?

2023-11-15 05:03 UTC, Majkl-J commented
I'll run some checks to see if it still works (Which it should), and request review afterward

2023-11-15 12:26 UTC, Majkl-J commented
Still seems to work exactly the same as before

2023-11-15 13:21 UTC, vinylspiders approved these changes

2023-11-15 13:21 UTC, merged