The Bird Is The Word: Avian Traits quirk for tweeting, chirping, and shrieking
Skyrat-SS13/Skyrat-TG pull request #25063
Opened 2023-11-17 07:21 UTC by Ephemeralis

## About The Pull Request

Adds a simple traits quirk for no cost that allows avian demihumans and other bird-like characters to speak as befitting their chosen identity.

## How This Contributes To The Skyrat Roleplay Experience

Lets people with bird-like characters lean into their identity more, and finally frees them from being third-class citizens in terms of conversational flavour.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
![YkARP5PuFJ](https://github.com/Skyrat-SS13/Skyrat-tg/assets/966289/53efdfcf-547c-4b9d-b54b-6907696b1f4c)

![dreamseeker_4NbCuOw8SV](https://github.com/Skyrat-SS13/Skyrat-tg/assets/966289/7331c884-3a7e-40c5-81f5-3c9a26784f5c)
</details>

## Changelog

:cl: yooriss
add: The 'Avian Traits' quirk is now available for all those of a bird-like persuasion (be they extraplanar visitors or otherwise) to peep, squawk, murmur and shriek their lungs out.
/:cl:

2023-11-17 19:20 UTC, desertmote commented
There are odds you will get the request for this PR to be modified in the same vain as this PR: https://github.com/Skyrat-SS13/Skyrat-tg/pull/13295.

PRs like this have been made before and denied because the addition of extra tongues was found to be bad implementation, good luck!

2023-11-17 20:47 UTC, SomeRandomOwl commented
Honkpocket is correct, it'd be best to implement this without changing peoples internal organs and modifying their tongue.

2023-11-18 05:26 UTC, Ephemeralis commented
This would break congruency with how canine traits are handled, and previous commit history indicates the current tongue-based solution is what was arrived at over pushing trait-linked overrides inside things like say procs. Which way is best to proceed?

2023-11-18 06:09 UTC, Ephemeralis commented
Testing with dual canine & avian traits quirks revealed some weirdness, which I've addressed by allowing selection of only one racial speech quirk at a time, which probably should've been the case to begin with.

2023-11-18 06:36 UTC, vinylspiders requested changes

2023-11-18 06:36 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/traits.dm
> +#define TRAIT_CANINE "canine_aspect"
You forgot to get rid of the old define, line 70

2023-11-18 06:36 UTC, vinylspiders commented on modular_skyrat/modules/organs/code/tongue.dm
> +	..()
```suggestion
	. = ..()
```

2023-11-18 06:36 UTC, vinylspiders commented on modular_skyrat/modules/organs/code/tongue.dm
> +
I think it's fine to do it like this, although is there really no 'say_mod' equivalent for the other verbs? Feels like that should be added upstream (not asking you to, just thinking aloud).

I have no problems with this given there is no other way far as I can tell...The canine tongue does it the same way.

2023-11-18 06:48 UTC, vinylspiders commented
> There are odds you will get the request for this PR to be modified in the same vain as this PR: #13295.
> 
> PRs like this have been made before and denied because the addition of extra tongues was found to be bad implementation, good luck!

The issue back then with the hemophage abilities being lost when choosing an augmented organ was fixed a few months back, so adding new tongues isn't as big a deal nowadays so long as they are making sure to call `copy_traits_from()` (which they are doing).

2023-11-18 06:48 UTC, vinylspiders approved these changes

2023-11-18 15:39 UTC, merged