[MODULAR] Grants Hearthkin Transcendent Olfaction (& One Other Thing)
Skyrat-SS13/Skyrat-TG pull request #25067
Opened 2023-11-17 18:53 UTC by Nerev4r

## About The Pull Request
This gives them that mutation that allows you to track people by scent.
I heavily recommend you have all the kindred nuzzle something at roundstart so you can track them later.
I was going to get a meme done for this PR body but this'll do instead.
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/480f5237-6b25-4352-aac8-fc11ed8f7bba)

This also gives them some brown bear pelts.

Thanks to @vinylspiders for helping me with the code.

## How This Contributes To The Skyrat Roleplay Experience
Easier allows them to track people for all kinds of purposes, and the brown bear pelt is kinda drip.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/4765afdb-bd1f-4d52-8915-27ef5f1f13df)

</details>

## Changelog
:cl:
add: Hearthkin have discovered a new herbal remedy to clear the sinuses, and now enjoy bloodhound-level scent tracking as they did long ago.
add: Hearthkin have discovered a population of grizzly bears on the ice moon, and have appropriately skinned some of them.
/:cl:

2023-11-17 20:33 UTC, Nerev4r commented
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/22a760be-5e10-4ce5-85cc-541c01fd57da)

i'm just going to post every meme ppl make for this PR until it's merged

2023-11-17 21:58 UTC, SpringSkipper commented
icecats aren't allowed to have snouts by server policy. This is FailRP. :neckbeard:
/veryserious

2023-11-17 23:04 UTC, vinylspiders requested changes

2023-11-17 23:04 UTC, vinylspiders commented on modular_skyrat/modules/primitive_catgirls/code/species.dm
> +	hearthkin.dna.add_mutation(/datum/mutation/human/olfaction)
```suggestion
	hearthkin.dna.add_mutation(/datum/mutation/human/olfaction, MUT_NORMAL)
```
Might fix the CI issues?

2023-11-17 23:04 UTC, vinylspiders commented on modular_skyrat/modules/primitive_catgirls/code/species.dm
> +    // >mfw I take mutadone and my nose clogs
```suggestion
    	// >mfw I take mutadone and my nose clogs
```

2023-11-18 07:32 UTC, Ephemeralis commented
I think it might be better to do this via `inert_mutation` on `/datum/species` and then activate it on species gain instead. This also has the added bonus of having the base `on_species_loss` proc handle swapping this out appropriately if an icewalker loses their species somehow.

2023-11-18 08:44 UTC, Ephemeralis commented
Bizarre CI issues notiwithstanding, I've had some limited success with this implementation locally:

```dm

/datum/mutation/human/olfaction/primitive
	mutadone_proof = TRUE
	instability = 0

/datum/species/human/felinid/primitive/on_species_gain(mob/living/carbon/hearthkin, datum/species/old_species, pref_load)
	. = ..()
	hearthkin.dna.add_mutation(/datum/mutation/human/olfaction/primitive, MUT_EXTRA)

/datum/species/human/felinid/primitive/on_species_loss(mob/living/carbon/human/hearthkin, datum/species/new_species, pref_load)
	. = ..()
	// if we have icecat transcendent olfaction (and we should, but check to be sure), lose it
	if(hearthkin.dna.mutation_in_sequence(/datum/mutation/human/olfaction/primitive))
		hearthkin.dna.remove_mutation(/datum/mutation/human/olfaction/primitive)
```

Whether this'll fare better in CI, I can't really say, but we do have a few problems:

- Attempting to change the dna for mutadone immunity causes a `modify()` runtime, maybe due to species_gain being called before the power stuff is initiated? Not fully sure. It doesn't seem to break anything immediate.
- Transcendent olfaction itself seems to stop working almost immediately due to miasma/cleanliness in the icemoon atmos. If you tap olfaction *twice* in an unclean area, you're disgusted for a seriously long period of time and puke everywhere, making it even harder to use olfaction again.

2023-11-18 08:59 UTC, Stalkeros2 commented
> ![image](https://user-images.githubusercontent.com/12636964/283925999-22a760be-5e10-4ce5-85cc-541c01fd57da.png)

this image proves that they need muskets

2023-11-18 15:45 UTC, vinylspiders commented
> Bizarre CI issues notiwithstanding, I've had some limited success with this implementation locally:
> 
> ```dm
> /datum/mutation/human/olfaction/primitive
> 	mutadone_proof = TRUE
> 	instability = 0
> 
> /datum/species/human/felinid/primitive/on_species_gain(mob/living/carbon/hearthkin, datum/species/old_species, pref_load)
> 	. = ..()
> 	hearthkin.dna.add_mutation(/datum/mutation/human/olfaction/primitive, MUT_EXTRA)
> 
> /datum/species/human/felinid/primitive/on_species_loss(mob/living/carbon/human/hearthkin, datum/species/new_species, pref_load)
> 	. = ..()
> 	// if we have icecat transcendent olfaction (and we should, but check to be sure), lose it
> 	if(hearthkin.dna.mutation_in_sequence(/datum/mutation/human/olfaction/primitive))
> 		hearthkin.dna.remove_mutation(/datum/mutation/human/olfaction/primitive)
> ```
> 
> Whether this'll fare better in CI, I can't really say, but we do have a few problems:
> 
>     * Attempting to change the dna for mutadone immunity causes a `modify()` runtime, maybe due to species_gain being called before the power stuff is initiated? Not fully sure. It doesn't seem to break anything immediate.
> 
>     * Transcendent olfaction itself seems to stop working almost immediately due to miasma/cleanliness in the icemoon atmos. If you tap olfaction _twice_ in an unclean area, you're disgusted for a seriously long period of time and puke everywhere, making it even harder to use olfaction again.

I have a fix for the modify() issue in the works upstream, it's a race condition with the timer that calls that proc basically calling it after the mob has been qdeleted. 

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/7750f076-90c1-4695-b44d-6a0a38f50418)

I am having trouble finding the source of the hard del though. It's really odd...

Wonder if the mutation itself is just bugged.

2023-12-03 23:25 UTC, vinylspiders commented
Testing this revealed an upstream bug that we now have to wait for the PR I made to come to us, but it should fix the ci issues

2023-12-07 05:45 UTC, vinylspiders approved these changes
The fix from upstream has arrived, at last this should be good to go now.

2023-12-07 05:54 UTC, merged