Bring Your Pet to Work Day (Veteran Quirk)
Skyrat-SS13/Skyrat-TG pull request #25142
Opened 2023-11-20 09:10 UTC by Thlumyn

## About The Pull Request

It's 2 am and I'm coding so I expect a lot of bugs, please yell them at me so I can fix :3

Veteran players can now choose a quirk that spawns them with a pet carrier in their hand, containing a simplemob/basic animal.

They can choose their pet from the quirks menu. 

Some of the animals are TOO BIG to fit in the carriers and can't be put back in once taken out, but I really like the idea of some cowboy spaceman riding their horse into work, so I left in the big animals for the time being. 

## How This Contributes To The Skyrat Roleplay Experience

Who doesn't love pets? A lot of roleplay opportunities show up from pets, such as: hunting down and suing somebody because their pet duct spider killed your pet chinchilla (rest in peace to the chinchillas that died in testing this PR). There was a lot of discussion about more veteran perks in the discord and this seemed to be the most popular one. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/102194057/06fa5784-70a0-4f85-8147-eb183679a7cc)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/102194057/b4880cef-10fd-4f97-a7bd-bf21c0c68d58)
(And upon discovering that horses reasonably aggro on you if you try to shove them back into a carrier, here is me getting beat to death on the Interlink by a pony)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/102194057/343d60fa-af84-4715-b2a4-e3acddcfe35b)

</details>

## Changelog

:cl:
add: Added pet owner quirk to spawn with a pet in a pet carrier.
/:cl:

2023-11-20 16:06 UTC, nikothedude commented
how did you read my mind i literally thought of this 3 hours before this pr was made

2023-11-20 16:07 UTC, nikothedude commented
also vetlocking things to vetlock them is bad form, the only things that are vetlocked are things with reason to be vetlocked (like we cant trust everyone with it)

2023-11-20 16:07 UTC, nikothedude commented
oh and ALSO this could probably be upstreamed, i think tg would love it

2023-11-20 16:15 UTC, Thlumyn commented
> also vetlocking things to vetlock them is bad form, the only things that are vetlocked are things with reason to be vetlocked (like we cant trust everyone with it)

Honestly, I really don't trust everyone with spawning in with a pet; but largely, this quirk was discussed a while ago in https://discord.com/channels/596783386295795713/1150923274839146586 as an idea for a veteran quirk

2023-11-20 16:31 UTC, vinylspiders requested changes
Looks good to me otherwise (codewise)

2023-11-20 16:31 UTC, vinylspiders commented on modular_skyrat/modules/pet_owner/pet_owner.dm
> +	"Kiwi" = /mob/living/basic/kiwi,
It is not a big deal, but you could alphabetize this

2023-11-20 16:31 UTC, vinylspiders commented on modular_skyrat/modules/pet_owner/pet_owner.dm
> +	var/obj/item/pet_carrier/carrier = new /obj/item/pet_carrier
```suggestion
	var/obj/item/pet_carrier/carrier = new /obj/item/pet_carrier(get_turf(quirk_holder))
```

2023-11-20 16:35 UTC, Thlumyn commented on modular_skyrat/modules/pet_owner/pet_owner.dm
> +	var/obj/item/pet_carrier/carrier = new /obj/item/pet_carrier
oops, I made some edits right before you sent this trying to figure how to do this thing right here, this is a much better way, let me edit it to fix that

2023-11-20 16:52 UTC, nikothedude commented
> > also vetlocking things to vetlock them is bad form, the only things that are vetlocked are things with reason to be vetlocked (like we cant trust everyone with it)
> 
> Honestly, I really don't trust everyone with spawning in with a pet; but largely, this quirk was discussed a while ago in https://discord.com/channels/596783386295795713/1150923274839146586 as an idea for a veteran quirk

A. that link doesnt seem to work
B. why dont you trust them with this? its literally just a simplemob, how can this possibly be abused? if the concern is that certain mobs give buffs, you can lock those animals behind being vetlocked, but something like a corgi is harmless

2023-11-20 16:58 UTC, Thlumyn commented
> > > also vetlocking things to vetlock them is bad form, the only things that are vetlocked are things with reason to be vetlocked (like we cant trust everyone with it)
> > 
> > 
> > Honestly, I really don't trust everyone with spawning in with a pet; but largely, this quirk was discussed a while ago in https://discord.com/channels/596783386295795713/1150923274839146586 as an idea for a veteran quirk
> 
> A. that link doesnt seem to work B. why dont you trust them with this? its literally just a simplemob, how can this possibly be abused? if the concern is that certain mobs give buffs, you can lock those animals behind being vetlocked, but something like a corgi is harmless

Ah, sorry, that link is from the veteran channel discussion about this. 

I don't so much expect it to be abused for mechanical advantage as much so as: pets provide more RP possibilities but also some more opportunity for things to go LRP and I don't want to see the Interlink flooded with 30 abandoned pets roundstart.

2023-11-20 17:03 UTC, Thlumyn commented
Heck, somebody refactored parrots while this was up and now its failing, let me fix that

2023-11-20 17:15 UTC, Thlumyn commented
That being said: personally I don't have very strong opinions either way on this being a veteran quirk or not, but because the idea for it came from the discussion there, that's what I'm putting it as for now.

2023-11-20 20:05 UTC, HoodMilk commented
See how it goes as vet only for a little while, if it's not a problem then maybe it could be opened up for everyone.

2023-11-20 20:45 UTC, vinylspiders approved these changes

2023-11-20 21:22 UTC, GoldenAlpharex requested changes

2023-11-20 21:22 UTC, GoldenAlpharex commented on modular_skyrat/modules/pet_owner/pet_owner.dm
> +	"Space carp" = /mob/living/basic/carp/pet,
I feel like the carp might be a bit too much, they can do a decent amount of damage around the place. Admittedly, I'm not home right now, so I can't tell what its stats are.

2023-11-20 21:22 UTC, GoldenAlpharex commented on modular_skyrat/modules/pet_owner/pet_owner.dm
> +	"Space cat" = /mob/living/simple_animal/pet/cat/space,
The space animals are kinda meant to be rare/unique animals, same goes with the void puppy, the cake cat and the bread cat, amd I feel like that kinda makes them lose a bit of what makes them unique/interesting, i.e. the fact that they're rare.

2023-11-20 23:45 UTC, desertmote commented
I notice you removed the parrot as part of the remove rare/dangerous animals commit, but I don't think parrots are either! Those should be cool to add, I think. 👍

2023-11-20 23:52 UTC, Thlumyn commented
> I notice you removed the parrot as part of the remove rare/dangerous animals commit, but I don't think parrots are either! Those should be cool to add, I think. 👍

A parrot can beat a space carp in 1 v 1

Also, on further thought - the ability for anybody to get a parrot and put a headset on it with almost no effort, just... seems like it would get old pretty fast. But, heck, I do love parrots myself.

2023-11-21 00:29 UTC, YakumoChen commented
Would be easy to just make a parrot child that has less HP and is not as annoying for the purposes of this PR

2023-11-21 03:54 UTC, SpringSkipper commented
I hate vetlocking in general. The idea that we should have more vetlocked perks just to have more vetlocked perks is deeply flawed.

2023-11-21 14:50 UTC, burgerenergy commented
No, it should be vetlocked if only to drip feed the amount of random ass pets added to the station. It's a good quirk, mind, but the server where 80 people can have pets and drop them about as a meme versus the one with 15~ is very different.

2023-11-21 15:41 UTC, CandleJaxx commented
> No, it should be vetlocked if only to drip feed the amount of random ass pets added to the station. It's a good quirk, mind, but the server where 80 people can have pets and drop them about as a meme versus the one with 15~ is very different.

easy fix to this is making it a higher-point quirk, honestly; make it like six points or something stupid, and zero for vets

2023-11-21 23:16 UTC, Thlumyn commented
> Would be easy to just make a parrot child that has less HP and is not as annoying for the purposes of this PR

That'd be real cool; some other animals like carp I think we could have a nerfed version that'd work well as pets. But I don't want to add too much content like new animal subtypes to this at the moment, maybe something to be added in the future if this works out without being too problematic though.

2023-11-22 04:01 UTC, burgerenergy commented
> > No, it should be vetlocked if only to drip feed the amount of random ass pets added to the station. It's a good quirk, mind, but the server where 80 people can have pets and drop them about as a meme versus the one with 15~ is very different.
> 
> easy fix to this is making it a higher-point quirk, honestly; make it like six points or something stupid, and zero for vets

(We're) making motions moving away from quirk costs and opening that up, so that wouldn't really work.

2023-11-24 03:52 UTC, YakumoChen commented
can you make sure all the pets are neutered? On top of having 20 animals show up a shift, I don't think we need to add dozens of puppies and kittens on top.

2023-11-26 19:21 UTC, GoldenAlpharex approved these changes
Seems good to me!

2023-11-26 19:38 UTC, GoldenAlpharex commented
Should be good for a quick like 1-day test-merge, just to make sure there isn't any glaring issues with this.

2023-11-26 23:06 UTC, FieryMorty commented
I don't think that this should be locked behind Veteran status.

2023-11-27 21:54 UTC, GoldenAlpharex commented
It's been test-merged, there doesn't seem to have been any issues, let's get this merged!

2023-11-27 21:54 UTC, merged