icecats now can "cryo"
Skyrat-SS13/Skyrat-TG pull request #25141
Opened 2023-11-20 04:56 UTC by jjpark-kb

## About The Pull Request
This PR allows icecats to "cryo," which opens up a new slot for the role.
This PR is NOT introducing mechanics to gain more slots.

## How This Contributes To The Skyrat Roleplay Experience
If someone has to deal with something IRL (sleep, or other situations), it would be nice to allow people to leave the game in a roleplay manner and allowing others to play the role.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/063f9e1e-5333-42d6-9635-99f7d3f6c766)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/40752862-f35b-4e4a-8d83-eb56ae20fa62)

</details>

## Changelog

:cl:
add: icecats can now "cryo" and open up another slot (ctrl+ click)
add: you can see if you are allowed to use the icecat spawner by examining it
/:cl:

2023-11-20 16:11 UTC, vinylspiders requested changes

2023-11-20 16:11 UTC, vinylspiders commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +
This doesn't handle all the other round removal stuff, does it? Like removing them from GLOB.joined_player_list, ghost records, handling objectives...

May be a good idea to atomize that out of the cryopod and into a component to allow for cryopod-like behavior on other objects. But for now if you don't feel like doing that just make sure it happens here, as well.

2023-11-20 22:02 UTC, jjpark-kb commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +
oh god, its gonna be so much more than I thought lmao

2023-11-21 16:23 UTC, vinylspiders commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +
Isn't that always how it goes? lol

2023-11-21 20:21 UTC, jjpark-kb commented on modular_skyrat/modules/primitive_catgirls/code/spawner.dm
> +
very true

2023-11-22 08:16 UTC, jjpark-kb commented
Hmm, didn't work. I'll need to keep working on it.

2023-12-01 21:44 UTC, jjpark-kb commented
ill have to handle this at a later date

2023-12-01 21:44 UTC, closed without merging