[FIX] Chameleon Is Toggleable Again
Skyrat-SS13/Skyrat-TG pull request #25154
Opened 2023-11-20 20:04 UTC by Nerev4r

## About The Pull Request
I have plans that I cannot share with you right now, because the haters will sabotage me.

## How This Contributes To The Skyrat Roleplay Experience
This was working a long time ago, but got lost in a random code audit. This mutation is hardly usable without it.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/db320b0e-f83c-4824-9504-d61ca1474c41)

</details>

## Changelog
:cl:
fix: Chameleon mutation is toggleable again.
/:cl:

2023-11-20 23:33 UTC, Namwty commented
Frankly should be mainstream ( imo )

From skyrat point, it's good, cause you can deactivate it to have to RP immersion ( I love chameleon, it's niche and fun ), but god it's annoying to go invisible during convos

From balance point, it's still good, **as in most cases it will increase instability** ( and no, I don't think rerolling DNA constantly for it is exactly a concern )
Increased instability means it won't be stackable with other mutations + makes chromosomes slightly more useful if someone wants to work with those. ( Instability matters so you can't stack it with stuff powergamey stuff like fiery sweat )

2023-11-23 01:08 UTC, vinylspiders requested changes

2023-11-23 01:08 UTC, vinylspiders commented on code/datums/mutations/chameleon.dm
> +	power_path = /datum/action/cooldown/spell/chameleon_skin_activate //SKYRAT EDIT
Would you mind putting this in master_files as an override? You already have the file made
```suggestion
```

2023-11-23 01:08 UTC, vinylspiders commented on modular_skyrat/master_files/code/datums/mutations/chameleon.dm
> +/datum/action/cooldown/spell/chameleon_skin_activate
```suggestion
// toggleable chameleon skin
/datum/mutation/human/chameleon
	power_path = /datum/action/cooldown/spell/chameleon_skin_activate

/datum/action/cooldown/spell/chameleon_skin_activate
```

2023-11-23 02:42 UTC, vinylspiders approved these changes

2023-11-23 02:42 UTC, merged