hammerable glass shards (for sand)
Skyrat-SS13/Skyrat-TG pull request #25157
Opened 2023-11-21 00:53 UTC by jjpark-kb

## About The Pull Request
pound... sand?
You can now use any tool that has the hammer behavior on it (xenoarch hammer, forging hammer) to break shards back into sand.

## How This Contributes To The Skyrat Roleplay Experience
sand is really just fine pieces of glass, shells, etc. so this makes sense in that way. Also, if you accidentally smelt a piece of sand rather than turning it into clay for ceramics, this allows you to at least undo that mistake.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/d4529872-1134-4ab1-8d34-235c400f2e75)

</details>

## Changelog

:cl:
add: you can hammer glass shards to get back sand
/:cl:

2023-11-21 05:41 UTC, Elli-Skala commented
Infinite mining point exploit

2023-11-21 19:53 UTC, jjpark-kb commented
> Infinite mining point exploit

addressed.

2023-11-22 20:19 UTC, vinylspiders requested changes

2023-11-22 20:19 UTC, vinylspiders commented on modular_skyrat/modules/primitive_production/code/misc.dm
> +		return
```suggestion
		return TRUE
```

2023-11-22 20:24 UTC, vinylspiders approved these changes
Might also want to add a desc to indicate the sand produced this way is worthless/ gives no mining points

2023-11-23 01:00 UTC, vinylspiders approved these changes

2023-11-23 01:00 UTC, merged