[MIRROR] New closets [MDB IGNORE]
Skyrat-SS13/Skyrat-TG pull request #25167
Opened 2023-11-21 04:51 UTC by SkyratBot

Original PR: https://github.com/tgstation/tgstation/pull/79774
--------------------
![closets_flat](https://github.com/tgstation/tgstation/assets/3625094/aa27979b-68a6-4d54-9ab5-5646281dd1fd)

![closets_flat_1](https://github.com/tgstation/tgstation/assets/3625094/04719e51-f8c8-479b-bebd-7aa8714682a8)

<details>
  <summary>In-game look</summary>

![image](https://github.com/tgstation/tgstation/assets/3625094/786f7c16-61c4-4670-bec8-3457076f58a9)

</details>

## About The Pull Request

Resprites the existing closets and adds new ones.

TODO:

- [x] Resprite cabinets
- [x] Split wardrobe cabinets into unique closets
- [x] Add new sprites for some closets that use generic style as a fallback
- [x] Update the cursed closets and fridges for the new dimensions
- [x] Bio closet for medbay
- [x] Re-map some locker icons like chemistry, anasthetic...

## Why It's Good For The Game

Making them in the same style as the crates.

## Changelog

:cl:
fix: Emag overlay on lockers fixed
image: New locker sprites
image: Added new lockers
/:cl:

2023-11-21 07:00 UTC, HoodMilk commented
Tall, they look good.

2023-11-22 09:59 UTC, OrionTheFox commented
our modular lockers will need touching up... gimme a bit

2023-11-22 19:15 UTC, vinylspiders commented
> our modular lockers will need touching up... gimme a bit
> 
> Edit: this might be a **long** "bit". Feel free to merge without ours matching sprite-wise if it takes too long. Just for the love of god make sure any of the code changes don't brick our icons entirely. ![image](https://user-images.githubusercontent.com/76465278/284942572-1a6af50b-ae2b-4b49-9ea8-9352917ded6e.png) It's happening though.

I can wait. I was just going to separate out the actually modular lockers from the base tg ones because we kind of have them all in one big overridden copy pasted override dmi right now.

2023-11-23 09:30 UTC, ghost commented
> I can wait. I was just going to separate out the actually modular lockers from the base tg ones because we kind of have them all in one big overridden copy pasted override dmi right now.

Looking in the code, the overrides don't ACTUALLY override any TG closets. It's just a ton of duplicate, unused icons in the file used for fully modular lockers. Feel free to merge it if it works as-is, my PR will cull the modular .dmi of all but needed icons.

2023-11-24 22:27 UTC, vinylspiders requested changes

2023-11-24 22:27 UTC, vinylspiders commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	icon_state = "tac"
```suggestion
	icon_state = "tac"
	icon_door = "armory_shotgun"
```
Make sure this matches tg completely

2023-11-24 22:27 UTC, vinylspiders commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
>  	req_access = list(ACCESS_ARMORY)
```suggestion
	icon_state = "tac"
	icon_door = "armory_energy"
	req_access = list(ACCESS_ARMORY)
```
Same here

2023-11-24 22:27 UTC, vinylspiders commented on modular_skyrat/modules/sec_haul/code/peacekeeper/peacekeeper_lockers.dm
> +	icon_state = "armory"
```suggestion
	icon_state = "armory"
	icon_door = null
```

2023-11-24 23:13 UTC, vinylspiders commented
> > I can wait. I was just going to separate out the actually modular lockers from the base tg ones because we kind of have them all in one big overridden copy pasted override dmi right now.
> 
> Looking in the code, the overrides don't ACTUALLY override any TG closets. It's just a ton of duplicate, unused icons in the file used for fully modular lockers. Feel free to merge it if it works as-is, my PR will cull the modular .dmi of all but needed icons.

@OrionTheFox This will ship with the modular .dmi culled, so just import your new sprites into there once this gets merged!

2023-11-25 00:30 UTC, vinylspiders approved these changes
Looks good, nice work!

2023-11-25 00:30 UTC, merged