[PORT] Gives Synths Internal Computers (& One Other Thing)
Skyrat-SS13/Skyrat-TG pull request #25168
Opened 2023-11-21 07:04 UTC by Nerev4r

## About The Pull Request
A port of https://github.com/Bubberstation/Bubberstation/pull/585, except slightly better.
This introduces the _emulated persocom_ to synthetic brains; or, more simply, an internal 'PDA.'
This bad boy has half the hard drive of a PDA because the rest of it's full of your firmware (and embarrassing memories,) but can still download programs, has a longer range compared to your PDA, and counts as a laptop (as your big ass is easily the size of a laptop, if not larger.)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/dc0819a8-e28f-41f9-a0e0-bc0377e36857)

Other people can interface with it at will (after a 5-second delay) by aiming their PDA at your eyes at a melee range (so you can play Outbomb Cuban Pete on your girlfriend), and they (and you!) can insert IDs into it by, again, shoving them in your eyes.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/417351aa-e7b7-4c2d-b6a0-8c741aee093c)

Special thanks to the guy who coded this originally, and special thanks to my brain for being willing to put up with making this PR.

Lastly, this PR allows you to download the messenger program, so you can sext from your brain.

## How This Contributes To The Skyrat Roleplay Experience
Diversification of races and expansion of mechanics is neat. I have had a few users tell me that they have evil or sexual plans for this, and being evil and sexual is what we're all about here.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/c915d9cc-62a5-4b0c-9078-c8e9af15f051)

</details>

## Changelog
:cl:
add: Certain firmware updates rolled out, finally, in Sector 13 have allowed machines to emulate personal computers within their brains.
qol: NanoTrasen has rolled out versions of its messenger programs for other devices.
/:cl:

2023-11-21 07:06 UTC, HoodMilk commented
How does this work with that one emag program that shuts down other computers?

2023-11-21 07:08 UTC, Nerev4r commented
> How does this work with that one emag program that shuts down other computers?

same as your PDA likely

2023-11-21 15:50 UTC, AstraFarera commented
Yas!

2023-11-21 19:05 UTC, trefoils commented
I just have to wonder can others take out your id? how would this work if the person is being demoted and refuses to hand over the id?

2023-11-21 19:09 UTC, Nerev4r commented
> I just have to wonder can others take out your id? how would this work if the person is being demoted and refuses to hand over the id?

Yes, by interfacing with it by using their PDA on your eyes.

2023-11-21 19:12 UTC, Nerev4r commented
Also having it in your brain PDA doesn't have it count as in your ID slot, so it won't open doors or anything.

2023-11-22 00:28 UTC, ChickyRooster commented
> Also having it in your brain PDA doesn't have it count as in your ID slot, so it won't open doors or anything.

A shame!

2023-11-22 02:30 UTC, YakumoChen commented
> and counts as a laptop

Most of the more powerful programs are laptop-friendly, notably the _Security Cameras_ program. You might want to blacklist it? It shouldn't have something like an Intellicard slot either.

2023-11-22 20:06 UTC, Nerev4r commented
ok it's a tablet now

2023-11-22 20:38 UTC, Majkl-J commented
Ok so firstly, add this:
https://github.com/Bubberstation/Bubberstation/pull/748

(this fixed a major issue with you being to able to abuse it from the safety of the interlink/cafe, and whilst kinda an admin issue still a bad thing to have (Until I add proper filters to all programs))

Mind you the code is generally terrible and a lot of programs don't work as intended. This is vastly an issue with how these computers are coded (See the actual machine computer for a reference of just how terrible code has to be to make them work outside of direct usage). I plan on fixing it by reworking the whole of tg modular computers to use the physical var for all computer proximity and other checks, but until that is done you can't expect stuff like the atmos scan to run on your gf

2023-11-22 20:39 UTC, Majkl-J commented
> Also having it in your brain PDA doesn't have it count as in your ID slot, so it won't open doors or anything.

Also I am trying to figure out how to make it use your actual ID slot for its own so do watch out for that

2023-11-22 21:24 UTC, jjpark-kb commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +	I.internal_computer.interact(owner)
we try to stay away from single letter vars

2023-11-22 21:24 UTC, jjpark-kb commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	var/obj/item/organ/internal/brain/synth/owner_brain
vars need to have documentation (the three forward slashs [///])

2023-11-23 00:43 UTC, YakumoChen commented
> Lastly, this PR allows you to download the messenger program, so you can sext from your brain.

This needs to be in the title explicitly or atomised

Also is there going to be a seperate visible message for sending messages as a synth (since you wouldn't be actually typing)

2023-11-23 02:14 UTC, Nerev4r commented
Blackpilled once again.
Due to how PDAs track 'you are next to the PDA when you use it,' the messenger program won't work.
Hence, been sliced.

2023-11-23 02:15 UTC, Nerev4r commented
> > Lastly, this PR allows you to download the messenger program, so you can sext from your brain.
> 
> This needs to be in the title explicitly or atomised, it is a balance change

It is, was, in the description, Ms. Maintainer.

2023-11-23 02:27 UTC, vinylspiders requested changes

2023-11-23 02:27 UTC, vinylspiders commented on code/modules/modular_computers/file_system/programs/messenger/messenger_program.dm
> +	available_on_ntnet = TRUE //SKYRAT EDIT CHANGE - Actually, it can.
Make it a modular override in master_files please along with a reason for it in a comment! (two slashes (//) for this, so you don't change the documentation)

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +	var/obj/item/modular_computer/pda/synth/internal_computer = new /obj/item/modular_computer/pda/synth
```suggestion
	var/obj/item/modular_computer/pda/synth/internal_computer = new /obj/item/modular_computer/pda/synth(src)
```
Otherwise it ends up in nullspace, not in the brain.

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +		internal_computer.physical = owner
```suggestion
```
These should be weakrefs, but since computer's `loc` should always be the brain, we can use that as our reference instead.

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +		internal_computer.physical = src
```suggestion
```

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	var/obj/item/organ/internal/brain/synth/owner_brain
```suggestion
```
Same as above, should be a weakref but we are going to use loc

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	if(!computer_id_slot)
```suggestion
	var/obj/item/organ/internal/brain/synth/brain_loc = loc
	if(!istype(brain_loc))
		return ..()

	if(!computer_id_slot)
```

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	if(user && !issilicon(user) && in_range(physical, user))
```suggestion
	if(user && !issilicon(user) && in_range(brain_loc.owner || brain_loc, user))
```

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	if(!find_functional_ntnet_relay() || !owner_brain.owner)
```suggestion
	var/obj/item/organ/internal/brain/synth/brain_loc = loc
	if(!istype(brain_loc))
		return NTNET_NO_SIGNAL

	if(!find_functional_ntnet_relay() || isnull(brain_loc.owner))
```

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	var/turf/current_turf = get_turf(physical)
```suggestion
	var/turf/current_turf = get_turf(brain_loc.owner || brain_loc)
```

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +			. = TRUE
```suggestion
	var/obj/item/modular_computer/pda/synth/robotbrain = machine
	if(!istype(robotbrain))
		return
	
	var/obj/item/organ/internal/brain/synth/brain_loc = loc
	if(!istype(brain_loc))
		return

	if(Adjacent(robotbrain.brain_loc.owner))
		. = TRUE
```
There has to be a better way of doing this however, instead of overriding this proc for all humans.

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +
Same here--this isn't quite as bad as the previous example but still.

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +		computer_id_slot.forceMove(physical.loc) //We actually update the physical on brain removal/insert
```suggestion
		computer_id_slot.forceMove(brain_loc.owner ? brain_loc.owner.drop_location() : brain_loc.drop_location()) //We actually update the physical on brain removal/insert
```
I'm not sure what that comment means. What is supposed to be happening here exactly? The code I wrote just tries to drop it at the synth's or the brain's location (if brain is detached)

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	return ..()
```suggestion
```

2023-11-23 02:27 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +/obj/item/modular_computer/pda/synth/RemoveID(mob/user)
```suggestion
/obj/item/modular_computer/pda/synth/Initialize(mapload)
	. = ..()
	
	// prevent these from being created outside of synth brains
	if(!istype(loc, /obj/item/organ/internal/brain/synth))
		return INITIALIZE_HINT_QDEL

/obj/item/modular_computer/pda/synth/RemoveID(mob/user)
```

2023-11-23 02:47 UTC, vinylspiders requested changes

2023-11-23 02:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +	var/obj/item/modular_computer/pda/synth/internal_computer = new /obj/item/modular_computer/pda/synth(src)
```suggestion
	var/obj/item/modular_computer/pda/synth/internal_computer
```

2023-11-23 02:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +
```suggestion
```

2023-11-23 02:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/brain.dm
> +/datum/action/item_action/synth/open_internal_computer
```suggestion
/obj/item/organ/internal/brain/synth/Initialize(mapload)
	. = ..()
	internal_computer = new(src)

/datum/action/item_action/synth/open_internal_computer
```

2023-11-23 02:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	if(Adjacent(robotbrain.brain_loc.owner))
```suggestion
	if(Adjacent(robotbrain.owner))
```

2023-11-23 02:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +		return
```suggestion
```

2023-11-23 03:08 UTC, vinylspiders requested changes
The robotbrain var name confused me

2023-11-23 03:08 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	if(Adjacent(robotbrain.owner))
```suggestion
	var/obj/item/organ/internal/brain/synth/robot_brain = internal_computer.brain_loc
	if(!istype(robot_brain))
		return

	if(Adjacent(robot_brain.owner))
```

2023-11-23 03:08 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	var/obj/item/modular_computer/pda/synth/robotbrain = machine
```suggestion
	var/obj/item/modular_computer/pda/synth/internal_computer = machine
```

2023-11-23 03:08 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	if(!istype(robotbrain))
```suggestion
	if(!istype(internal_computer))
```

2023-11-23 03:12 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	var/obj/item/organ/internal/brain/synth/robot_brain = internal_computer.brain_loc
```suggestion
	var/obj/item/organ/internal/brain/synth/robot_brain = internal_computer.loc
```

2023-11-23 04:20 UTC, Majkl-J commented
I would just like to point out that using the physical var is actually preferable with what I am trying to do on tg, that being making it the standard for proximity checks. It is commented as such but never actually used in that way and is meant to represent the object you use to interact with the computer.

2023-11-23 05:29 UTC, vinylspiders commented
> I would just like to point out that using the physical var is actually preferable with what I am trying to do on tg, that being making it the standard for proximity checks. It is commented as such but never actually used in that way and is meant to represent the object you use to interact with the computer.
> 
> (Basically by not using it you cut some future compatibility)

In this case, the computer itself is going to be inside the brain, which exists in nullspace. Proximity checks don't really work for objects like that when it comes to tgui.

You ought to make it a weakref if you intend to give it the sort of functionality that you describe. It should also be designed in such a way that it's an optional var. The computer should be able to exist and operate independently.

2023-11-23 05:47 UTC, vinylspiders requested changes

2023-11-23 05:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	return NTNET_NO_SIGNAL
```suggestion
	. = NTNET_NO_SIGNAL
	// NTNet is down and we are not connected via wired connection. The synth is no more
	var/obj/item/organ/internal/brain/synth/brain_loc = loc
	if(!istype(brain_loc))
		return
	if(!find_functional_ntnet_relay() || isnull(brain_loc.owner))
		return

	var/turf/current_turf = get_turf(brain_loc.owner || brain_loc)
	if(is_station_level(current_turf.z))
		return NTNET_GOOD_SIGNAL
	else if(long_ranged && !is_centcom_level(current_turf.z)) // Centcom is excluded because cafe
		return NTNET_LOW_SIGNAL
```

2023-11-23 05:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +		return ..()
```suggestion
		return ..()

```

2023-11-23 05:47 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +		return ..()
```suggestion
		return ..()

```

2023-11-23 05:48 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +
```suggestion
```

2023-11-23 05:49 UTC, vinylspiders requested changes

2023-11-23 05:49 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/internal_computer/internal_computer.dm
> +	long_ranged = TRUE //Synths have good antenae
```suggestion
	long_ranged = TRUE //Synths have good antennae
```

2023-11-23 06:23 UTC, vinylspiders approved these changes

2023-11-23 06:43 UTC, vinylspiders commented
> I plan on fixing it by reworking the whole of tg modular computers to use the physical var for all computer proximity and other checks, but until that is done you can't expect stuff like the atmos scan and messenger to run on your gf

@Majkl-J I'll stay on the lookout for this when it comes to us! Thanks! You should also take a look at the changes we made to how the tgui proximity is checked. The `can_interact` override you were doing before was unnecessary, you can just use the ui state system that comes with tgui.

2023-11-23 06:51 UTC, vinylspiders commented
@Majkl-J also instead of the 'physical' idea, which would involve a messy ref that would have to be managed and cleaned, what you could do instead is just make a proc, get_physical_location() or something. Which by default returns the src.loc. Then you can override that proc to return the brain mob's location for all your subtypes. Just replace any in-app checks for location (atmos scanner, etc) to use that proc.

2023-11-23 13:32 UTC, Majkl-J commented
> @Majkl-J also instead of the 'physical' idea, which would involve a messy ref that would have to be managed and cleaned, what you could do instead is just make a proc, get_physical_location() or something. Which by default returns the src.loc. Then you can override that proc to return the brain mob's location for all your subtypes. Just replace any in-app checks for location (atmos scanner, etc) to use that proc.

This is actually a great idea, I'll probably also converse with some of the tg maintainers on how to tackle this. Hopefully I'll gather to motivation to actually do it, but if I were to do it I will make the relevant rework on this feature on skyrat aswell.

2023-11-23 17:13 UTC, vinylspiders commented
I guess this is fine as is, just note that apps with location checks for the time being might not function properly.

2023-11-23 17:13 UTC, merged