Zcrow donator item
Skyrat-SS13/Skyrat-TG pull request #25175
Opened 2023-11-21 21:13 UTC by scrcr0

## About The Pull Request

Adds the custom track pants to the game, locked as a donator item for Zcrow.

## How This Contributes To The Skyrat Roleplay Experience

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/8256657/06f6a5d2-96cf-41a7-915e-31e532849359)

</details>

## Changelog

:cl:
add: donator item for Zcrow
/:cl:

2023-11-21 23:51 UTC, CandleJaxx commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	name = "Tarin's custom sweatpants"
oh yay i can help with this actually; names for items should be all lowercase, except for when in the loadout dm files for naming structure :)

2023-11-21 23:59 UTC, scrcr0 commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	name = "Tarin's custom sweatpants"
Gotcha, will update.

2023-11-23 16:23 UTC, vinylspiders requested changes

2023-11-23 16:23 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	body_parts_covered = CHEST|GROIN|LEGS
```suggestion
	body_parts_covered = GROIN|LEGS
```

2023-11-23 17:06 UTC, vinylspiders approved these changes
@GoldenAlpharex

2023-11-27 23:47 UTC, GoldenAlpharex requested changes
You haven't yet met the threshold of $15 in donations required in order to get a donator item. Feel free to contact me on Discord to discuss of any details.

2023-12-01 21:53 UTC, scrcr0 commented
> You haven't yet met the threshold of $15 in donations required in order to get a donator item. Feel free to contact me on Discord to discuss of any details.

Ah my mistake. I thought I'd hit that at the time of submission. It should be correct as of Dec 1.

2023-12-01 21:54 UTC, jjpark-kb commented
I was just about to close this PR-- glad I saw you commented :)

2023-12-01 21:57 UTC, jjpark-kb commented
I will be closing the PR-- please contact Golden!

2023-12-01 21:57 UTC, closed without merging