Donator Item, Smol42
Skyrat-SS13/Skyrat-TG pull request #25196
Opened 2023-11-22 22:58 UTC by Smol42

## About The Pull Request

Adds donator item for Smol42 sprited from scratch by Smol42.

<details>
<summary>Proof of Testing</summary>

![-=q](https://github.com/Skyrat-SS13/Skyrat-tg/assets/111681347/e87d6314-ffc6-414f-85f0-3fd6e678b13a)
</details>

## Changelog

:cl: Smol42
add: Added custom donator item.
/:cl:

2023-11-23 16:07 UTC, vinylspiders requested changes
Otherwise looks good

2023-11-23 16:07 UTC, vinylspiders commented on modular_skyrat/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	icon_state = "trenchcoat"
```suggestion
	icon_state = "trenchcoat"
	body_parts_covered = CHEST|GROIN|LEGS|ARMS
```
Same ones as for cloaks

2023-11-25 14:50 UTC, Smol42 commented
> Otherwise looks good

👍🏻

2023-11-25 20:49 UTC, vinylspiders approved these changes

2023-11-27 23:23 UTC, GoldenAlpharex approved these changes
Looks good to me.

2023-11-27 23:23 UTC, merged