Adds Affection Aversion quirk
Skyrat-SS13/Skyrat-TG pull request #25194
Opened 2023-11-22 20:50 UTC by DBGit42

## About The Pull Request
Adds the Affection Aversion quirk. Its sole purpose is to stop the affection module from working on anyone with said quirk.

## How This Contributes To The Skyrat Roleplay Experience
Gives players the option to disable affection modules from affecting them. Yes. You're welcome.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/149782698/010a57d5-0441-4b32-8a3e-cf1b880d6d46)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/149782698/b6142bf6-e7bd-4530-9d0a-5350ce45dada)
</details>

## Changelog
:cl: Danny Boy
add: Added Affection Aversion quirk which stops affection modules
/:cl:

2023-11-22 21:10 UTC, vinylspiders requested changes

2023-11-22 21:10 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/traits.dm
> +
You'll have to remove this and put your new trait in the `code/__DEFINES/~skyrat_defines/traits/declarations.dm` file, as well as add it to the global traits list (and admin tooling one)

2023-11-22 21:11 UTC, DBGit42 commented on code/__DEFINES/~skyrat_defines/traits.dm
> +
Thanks, I found these in the process of trying to figure out why this file is completely different on my end (???) which caused a merge conflict. I'm working on it.

2023-11-22 21:25 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/traits.dm
> +
Yeah https://github.com/Skyrat-SS13/Skyrat-tg/pull/25134 moved all the traits declarations to a central location, that's where the conflict came from

2023-11-22 21:27 UTC, DBGit42 commented on code/__DEFINES/~skyrat_defines/traits.dm
> +
Case of really bad timing? Okay, that makes more sense. Almost done fixing this mess / testing.

2023-11-22 21:38 UTC, DBGit42 commented
Re-tested, case of amazing timing repaired, working properly.

2023-11-23 00:53 UTC, vinylspiders approved these changes

2023-11-23 01:01 UTC, merged