Lopland holobadges in the loadout & security vendor! Also fixes them for detectives!
Skyrat-SS13/Skyrat-TG pull request #25198
Opened 2023-11-22 23:41 UTC by Plum-but-gayer

## About The Pull Request
Adds both types of holobadge (normal and with lanyard) to the neck slot loadout menu, locked for security jobs only. Also changes the access you need to swipe your ID on them from brig to general sec, allowing detectives to finally use their holobadges. Resprites the non-lanyard holobadge to be an appropriate Lopland blue rather than red. Finally, a box of holobadges can be purchased from the Armadyne vendor in security. 

## How This Contributes To The Skyrat Roleplay Experience

Holobadges have always been a cool little flavor item that has disappeared over time for one reason or another. Keeping them around and easy to access is a low-cost way of giving security more ways to RP and drag Lopland lore in from the realm of google documents into the world of actual inround stuff. Also detectives should be able to use their own badges. :)

## Proof of Testing

Runs fine when I run it on my machine. 

<details>
<summary>Screenshots/Videos</summary>
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/4c5e98a6-3c79-4825-8ade-53c7db0df480)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/d6e96584-c170-46ff-bb61-5b3d4183e941)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/88918fdd-4d8d-4815-a44b-fdd61f7133e6)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/215d6741-ce30-4728-943f-c6c2b0d2aacc)

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/6d73fcb2-7e92-471f-8ac7-0ef046c14f56)

</details>

## Changelog

:cl:
add: Overbearing authority figures rejoice! Holobadges are now available in the neck loadout slot and the Armadyne peacekeeper vendor, now in a pleasant Lopland blue.
fix: Detectives can now actually swipe their ID on their holobadges.
/:cl:

2023-11-23 04:55 UTC, Namwty commented
Can't wait to wake up in a bar as a detective and lie to my lopland buddies that I did not lose my badge ( or gun, for that matter )

2023-11-23 16:04 UTC, theselfish commented on modular_skyrat/modules/customization/modules/clothing/under/accessories.dm
> +		if(ACCESS_SECURITY in id_card.access || (obj_flags & EMAGGED))
Correct me if I'm wrong, I haven't memorized access requirements for every job, but wouldn't this mean theoretically Dept. Guards could use them?

2023-11-23 16:04 UTC, theselfish commented
Thoughts on adding a box or two of them to the Equipment Vendor?

2023-11-24 21:54 UTC, Plum-but-gayer commented on modular_skyrat/modules/customization/modules/clothing/under/accessories.dm
> +		if(ACCESS_SECURITY in id_card.access || (obj_flags & EMAGGED))
extremely possible, idk if that would be a good thing or bad thing tbh. I'm not sure what access detectives have that dept. guards don't, though

2023-11-24 21:54 UTC, Plum-but-gayer commented
> Thoughts on adding a box or two of them to the Equipment Vendor?

good idea, happy to add

2023-11-25 21:57 UTC, theselfish commented on modular_skyrat/modules/customization/modules/clothing/under/accessories.dm
> +		if(ACCESS_SECURITY in id_card.access || (obj_flags & EMAGGED))
Very fair point.
Not exactly a major, PR breaking bug. The worst that'll happen is a departmental guard gets one and...can flash it?

2023-12-04 16:55 UTC, GoldenAlpharex requested changes
That was the only nitpick I had about this, should be good to merge once fixed!

2023-12-04 16:55 UTC, GoldenAlpharex commented on modular_skyrat/master_files/icons/mob/clothing/accessories.dmi
One of the dirs of the lopland badge here is still red.

2023-12-04 20:24 UTC, Plum-but-gayer commented on modular_skyrat/master_files/icons/mob/clothing/accessories.dmi
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/50682821/95f7f645-41f9-4e1f-9a13-6b45cbea7c6e)

Maybe I don't know how dirs work, but this one has been changed to blue! Is there something I'm missing?

2023-12-04 20:36 UTC, Plum-but-gayer commented on modular_skyrat/master_files/icons/mob/clothing/accessories.dmi
OH i found it. so tiny lol

2023-12-04 20:46 UTC, Plum-but-gayer commented
not sure why I'm failing the PR labeller test

2023-12-05 00:11 UTC, vinylspiders commented
> not sure why I'm failing the PR labeller test

PR labeler action got an update and had to be updated on our end.

2023-12-05 01:35 UTC, Plum-but-gayer commented
should be good to merge now btw 👍

2023-12-06 06:15 UTC, vinylspiders approved these changes
Looks fine to me, @GoldenAlpharex sprites look ok to you?

2023-12-06 18:36 UTC, GoldenAlpharex approved these changes
Looks good to me!

2023-12-06 18:37 UTC, GoldenAlpharex commented
Just fixed the conflict, ready to merge once CI passes again.

2023-12-06 19:02 UTC, merged