Removes irrelevant quirk restriction of a nonexistant quirk
Skyrat-SS13/Skyrat-TG pull request #25252
Opened 2023-11-25 20:59 UTC by nikothedude

## About The Pull Request

Title.

## How This Contributes To The Skyrat Roleplay Experience

Chunky fingers doesnt exist anymore.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
it compiles
</details>

## Changelog

:cl:
del: Removes a irrelevant quirk restriction of a nonexistant quirk
/:cl:

2023-11-25 22:23 UTC, vinylspiders requested changes
Nice catch, could you also remove the other lingering references to this quirk while you're at it?

`var/allow_chunky` and `var/chunky_finger_usable`

2023-11-25 22:23 UTC, vinylspiders commented on code/__DEFINES/~skyrat_defines/jobs.dm
> +#define TECH_RESTRICTED_QUIRKS
```suggestion
```
This is nothing now, just get rid of it (as well as any references to it).

2023-11-25 22:49 UTC, nikothedude commented
> `allow_chunky`

No, the trait still exists and is obtainable via ashies and shit, therfore its relevant

2023-11-26 00:46 UTC, vinylspiders commented
> > `allow_chunky`
> 
> No, the trait still exists and is obtainable via ashies and shit, therfore its relevant

That is confusing. I see.

2023-11-26 00:47 UTC, vinylspiders approved these changes

2023-11-26 00:47 UTC, merged