Synths can now charge from borg chargers + synth bodies are now printable
Skyrat-SS13/Skyrat-TG pull request #25260
Opened 2023-11-26 09:36 UTC by Majkl-J

## About The Pull Request

Ports:
https://github.com/Bubberstation/Bubberstation/pull/726
https://github.com/Bubberstation/Bubberstation/pull/716

Because someone asked me nicely

## How This Contributes To The Skyrat Roleplay Experience

Robot charge in robot charger, good, yes?

Getting gibbed as synth means you are basically RR currently. Maaybe you could get borged, but that's about it. So I fixed that, and you can now print the synth bodies at robotics

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/49160555/f2f1e12a-5fe4-4e45-af2f-d406f9118d44)

You will have to trust me that the charger works because I can't grab video

</details>

## Changelog

:cl:
qol: Synths can now recharge in borg chargers
qol: Empty synth bodies can now be printed
/:cl:

2023-11-26 11:56 UTC, Majkl-J commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +	var/old_death_sound = death_sound // You can't do this with initial() as the death sound is set after by the species datum
Technically, they don't have a deathsound, but this is still futureproofed just in case

2023-11-26 19:33 UTC, vinylspiders requested changes

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +	SIGNAL_HANDLER
```suggestion
```
You only need this in `on_borg_charge()` (that said, this whole proc can just be gotten rid of)

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +	SIGNAL_HANDLER
```suggestion
```
Likewise

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +	add_synth_signals(receiver)
```suggestion
	RegisterSignal(stomach_owner, COMSIG_PROCESS_BORGCHARGER_OCCUPANT, PROC_REF(on_borg_charge))
```
You don't really need a proc for this here

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +	remove_synth_signals(stomach_owner)
```suggestion
	UnregisterSignal(stomach_owner, COMSIG_PROCESS_BORGCHARGER_OCCUPANT)
```
Same here

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/designs/exofab_designs.dm
> +					/datum/material/gold = SHEET_MATERIAL_AMOUNT * 0.25)
```suggestion
	materials = list(/datum/material/iron = SHEET_MATERIAL_AMOUNT * 20,
		/datum/material/glass = SHEET_MATERIAL_AMOUNT * 10,
		/datum/material/silver = SHEET_MATERIAL_AMOUNT * 0.5,
		/datum/material/gold = SHEET_MATERIAL_AMOUNT * 0.25
	)
```

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +	var/obj/item/organ/internal/brain/B = get_organ_slot(ORGAN_SLOT_BRAIN)
```suggestion
	var/obj/item/organ/internal/brain/synth_brain = get_organ_slot(ORGAN_SLOT_BRAIN)
```

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +		QDEL_NULL(B)
```suggestion
	if(synth_brain)
		QDEL_NULL(synth_brain)
```
`Remove()` will get called automatically in `/obj/item/organ/internal/Destroy()`

2023-11-26 19:33 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +/mob/living/carbon/human/species/synth/empty
I'm not sure about this--seems like it could be exploitable to just be able to print unlimited human bodies.

Maybe instead we can have it take a synth brain and build a body using the prefs of that instead of the mass-production option?

2023-11-26 19:36 UTC, Maia-J commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +/mob/living/carbon/human/species/synth/empty
Printing unlimited humans is already an easy enough task (Monkeys), I could look into this more but I am really not too experienced in prefcode so I am unsure on how to make this work

2023-11-26 20:55 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +/mob/living/carbon/human/species/synth/empty
It just feels like it should be limited in some way is all.

Having some option to customize the created bodies would be cool as well.

As for the prefs thing you could look at `/obj/effect/mob_spawn/ghost_role/create(mob/mob_possessor, newname)` or the magic mirror for an idea on how prefs can be transferred to a mob.

You could even have it give a choice to either use a custom design, one based off the brain mob, or the generic model.

Edit: the prefs thing is by no means a blocking request. Just an idea for you to add to this if you are so inclined

2023-11-26 21:41 UTC, vinylspiders requested changes

2023-11-26 21:41 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +	RegisterSignal(owner, COMSIG_PROCESS_BORGCHARGER_OCCUPANT, PROC_REF(on_borg_charge))
```suggestion
	RegisterSignal(receiver, COMSIG_PROCESS_BORGCHARGER_OCCUPANT, PROC_REF(on_borg_charge))
```
Has to be the mob passed in through args because `owner` is not set yet

2023-11-26 21:41 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +	UnregisterSignal(owner, COMSIG_PROCESS_BORGCHARGER_OCCUPANT)
```suggestion
	UnregisterSignal(stomach_owner, COMSIG_PROCESS_BORGCHARGER_OCCUPANT)
```

2023-11-27 02:04 UTC, Zergspower commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +/mob/living/carbon/human/species/synth/empty
i'd make it so it's a 'smack brain onto and suddenly Johnny-5 is alive' rather than a static body

2023-11-27 06:23 UTC, vinylspiders requested changes

2023-11-27 06:23 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +			owner.nutrition = NUTRITION_LEVEL_ALMOST_FULL
```suggestion
	if(owner.nutrition >= NUTRITION_LEVEL_ALMOST_FULL)
		return

	amount /= 50 // Lowers the charging amount so it isn't instant
	owner.nutrition = min((owner.nutrition + amount), NUTRITION_LEVEL_ALMOST_FULL) // Makes sure we don't make the synth too full, which would apply the overweight slowdown
```
I would just cap this at one value to keep it simple. That said I'm not sure what the exact number is for triggering the overweight slowdown here, so if you can get it closer that would be ideal.

Also, why do synths even get that in the first place?? Seems a bit silly

2023-11-27 11:58 UTC, projectkepler-ru commented on modular_skyrat/modules/synths/code/species/synth_prefab.dm
> +/mob/living/carbon/human/species/synth/empty
> Printing unlimited humans is already an easy enough task (Monkeys), I could look into this more but I am really not too experienced in prefcode so I am unsure on how to make this work

Yes but a humonkey body has a drawback being that they all take more effort to resist out of grip so it is a punishment for dying

2023-11-27 14:27 UTC, Majkl-J commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +			owner.nutrition = NUTRITION_LEVEL_ALMOST_FULL
NUTRITION_LEVEL_ALMOST_FULL is described as the maximum for any species that gets nutrition passively, like podpeople, so I went with that.

Why synths get all fat is beyond me, but ultimately out of scope, for this PR at least, I will look into it

2023-11-27 16:02 UTC, GoldenAlpharex submitted a review, later dismissed
I don't agree with Synth bodies being printable, for performance concerns, as that's basically just printing mobs that are some of the most expensive we have. I'd rather have a different solution that would allow us to not have to concern ourselves with that, such as something that basically pretends to be a synthetic body, and only properly turns into a mob once you insert the "brain" in it.

2023-11-27 20:18 UTC, Majkl-J commented
> I don't agree with Synth bodies being printable, for performance concerns, as that's basically just printing mobs that are some of the most expensive we have. I'd rather have a different solution that would allow us to not have to concern ourselves with that, such as something that basically pretends to be a synthetic body, and only properly turns into a mob once you insert the "brain" in it.

Sure, will do

2023-11-27 20:20 UTC, vinylspiders commented on modular_skyrat/modules/synths/code/bodyparts/stomach.dm
> +			owner.nutrition = NUTRITION_LEVEL_ALMOST_FULL
> NUTRITION_LEVEL_ALMOST_FULL is described as the maximum for any species that gets nutrition passively, like podpeople, so I went with that.
> 
> Why synths get all fat is beyond me, but ultimately out of scope, for this PR at least, I will look into it

Right, I was not asking you to change it here. Just thought it was odd lol.

2023-11-27 20:25 UTC, vinylspiders commented
> I don't agree with Synth bodies being printable, for performance concerns, as that's basically just printing mobs that are some of the most expensive we have. I'd rather have a different solution that would allow us to not have to concern ourselves with that, such as something that basically pretends to be a synthetic body, and only properly turns into a mob once you insert the "brain" in it.

To tack onto this, when considering the costs of production I would also make sure that the material cost ends up being at least equal to whatever the combined costs of printing the individual synth organs would be, as well as making sure it can't be produced before the appropriate research for those is acquired.

2023-11-28 11:52 UTC, Majkl-J commented
> > I don't agree with Synth bodies being printable, for performance concerns, as that's basically just printing mobs that are some of the most expensive we have. I'd rather have a different solution that would allow us to not have to concern ourselves with that, such as something that basically pretends to be a synthetic body, and only properly turns into a mob once you insert the "brain" in it.
> 
> To tack onto this, when considering the costs of production I would also make sure that the material cost ends up being at least equal to whatever the combined costs of printing the individual synth organs would be, as well as making sure it can't be produced before the appropriate research for those is acquired.

Decided to split that into another PR not because it's exactly TOO complicated but it will make it easier for me to work on as I find it easier to work on smaller split up tasks and the other half of this PR is fine.

2023-11-28 20:59 UTC, vinylspiders approved these changes

2023-11-28 21:00 UTC, merged