Plant Tank
Skyrat-SS13/Skyrat-TG pull request #25328
Opened 2023-11-29 03:58 UTC by jjpark-kb

## About The Pull Request
This PR adds the plant tank-- a structure that when five sand is placed inside, allows the use of simple farming. That is not all that it can do. If you take grown food (produce) or worm fertilizer and place it inside the plant tank while it has a plant growing, it will slowly produce nitrogen and convert carbon dioxide to oxygen.

There are a few other changes beyond just adding the plant tank. Some changes include that the simple farm will set its glide size to whatever its parent atom is-- which means that if you plant stuff in minecarts or in the plant tank, the simple farm plant will actually move with the parent rather than doing a weird glitchy motion. Another thing that was added was that if the parent item (minecarts, plant tanks, etc. ) are deleted/removed, it will also remove the farm (which I don't know why I didn't add this earlier).

## How This Contributes To The Skyrat Roleplay Experience
Realistically, plants do participate in the nitrogen cycle, as well as the oxygen cycle through photosynthesis. I think this is a nice way to allow another production of nitrogen and oxygen beyond the other methods (HFR for nitrogen and SM for oxygen).

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/4dd1525b-7e65-4caa-b5b9-38431e0c767c)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/55967837/b6ddf475-e511-4feb-8929-5e58185625bc)

</details>

## Changelog

:cl:
add: added the plant tank-- allows simple farm growing and production of nitrogen and oxygen
fix: simple farms will now destroy themselves if their parent atom is destroyed
/:cl:

2023-12-02 16:39 UTC, GoldenAlpharex requested changes
I do need to say, out of all the sprites you've made so far Jake, I think these are your best!

2023-12-02 16:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/ashwalkers/code/buildings/ash_farming.dm
> +/datum/component/simple_farm/proc/delete_farm()
Document this please!

2023-12-02 16:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +	. += span_notice("<br>Use food or worm fertilizer to allow nitrogen production and carbon dioxide processing!")
I think it would be nice if it was displaying how many operation cycles it has left when you examine it, instead of just having to guess.

2023-12-02 16:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +		src_mixture.gases[/datum/gas/oxygen][MOLES] += proportion
So, how many moles does this actually produce?

2023-12-02 16:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +	new /obj/item/stack/rods(get_turf(src))
Also, just saying, this right now only deconstructs in 1 glass sheet and 1 rod, unless I'm mistaken.
```suggestion
	var/target_turf = get_turf(src)
	new /obj/item/stack/sheet/glass(target_turf)
	new /obj/item/forging/complete/plate(target_turf)
	new /obj/item/stack/rods(target_turf)
```

2023-12-02 16:49 UTC, jjpark-kb commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +	new /obj/item/stack/rods(get_turf(src))
this is on purpose so that people can't just deconstruct it and place it elsewhere

2023-12-02 16:50 UTC, jjpark-kb commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +		src_mixture.gases[/datum/gas/oxygen][MOLES] += proportion
around 20 of oxygen (when co2 is present) and 20 of nitrogen

2023-12-02 16:51 UTC, jjpark-kb commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +	new /obj/item/stack/rods(get_turf(src))
I'll change it-- I understand the frustration

2023-12-02 19:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/ashwalkers/code/buildings/planttank.dm
> +	if(operation_number == 0) //we require "fuel" to actually produce stuff
```suggestion
	if(operation_number <= 0) //we require "fuel" to actually produce stuff
```

2023-12-02 19:03 UTC, GoldenAlpharex approved these changes
Should be good for a test-merge.

2023-12-04 16:52 UTC, comrade-dagmar commented
I love the sprites! Immediately reminded me of those algae tanks used for pollution. A simple green watery version that cant hold plants, but *does* use the oxygen generation feature, (maybe the maints fishing list too) would be cool as well!

2023-12-17 20:14 UTC, GoldenAlpharex approved these changes
Been test-merged for a while, haven't really heard any complaints or bug reports on it, should be fine to merge. Don't think too many people actually touched it, but hey, we'll find issues as they arise.

2023-12-17 20:14 UTC, merged