[MIRROR] Removes context from tgui [MDB IGNORE]
Skyrat-SS13/Skyrat-TG pull request #25332
Opened 2023-11-29 08:48 UTC by SkyratBot

Original PR: https://github.com/tgstation/tgstation/pull/80003
--------------------

## About The Pull Request
*Most context
This is a precursor PR for moving to React. Newer React (>16) does not have the `context` parameter, so it needs removed. I want to make converting to React look slightly less intimidating, so this is just short-circuiting context here. 

This shouldn't be considered a long term solution.
## Why It's Good For The Game
Moving to react is good actually
## Changelog
N/A hopefully no noticeable change

2023-12-03 18:14 UTC, SomeRandomOwl commented
#25094

2023-12-03 23:18 UTC, vinylspiders requested changes

2023-12-03 23:18 UTC, vinylspiders commented on tgui/packages/tgui/interfaces/NtosCrewManifest.jsx
> +export const NtosCrewManifest = (props) => {
This got accidentally moved up I think? It used to be below the skyrat edit

2023-12-04 03:52 UTC, vinylspiders approved these changes

2023-12-04 03:52 UTC, merged