Reworks, resprites, or in a few cases deletes, shotgun shells including but not limited to skyrat shotgun shells
Skyrat-SS13/Skyrat-TG pull request #25352
Opened 2023-11-30 18:52 UTC by Paxilmaniac

## About The Pull Request

Its funny how many shotgun shells we have that you either can't use or that simply outperform the others in every task ever.

So, lets get straight to it and talk changes:

As a guideline, any lethal shell should be aiming for about 50 damage total, where non-lethal shells should be aiming for about 60 stamina damage.

Buckshot, magnum, and express, all do the same total damage (48), with their differences being number of pellets and damage per pellet.

Rubbershot damage was reduced by one (1) per pellet.

Flechettes are back and no longer penetrate armor, think of them like .35 sol's ripper rounds but for a shotgun.

Hunter shells are back, except not as buckshot and simply a slug that should do 80 damage to any mob typed as "MOB_BEAST"

Beehive and antitide are now like the magnum and express shot for less-lethals. Beehives (now hornet's nests) still bounce off walls toward targets, and antitide (now stardust) still embeds and causes pain damage on movement.

Importantly, there are **no** armor piercing shotgun ammos anymore. Every projectile either is weak to armor or simply lacks armor penetration.

## How This Contributes To The Skyrat Roleplay Experience

As I said before, we have a lot of shotgun shell variety but can't use a lot of it because shells will randomly be either insane or have no reason to be used over the other shells. This also results in witless mappers putting what is accidentally the strongest shotgun shell ever on a map without thinking of it.

Ideally now, every shell has a purpose, people can have preferences based on what **they** want rather than what the meta shell is. Looking at you magnum buckshot.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

These files are too big for github ok just trust me on this one

  https://cdn.discordapp.com/attachments/640744619302453316/1179855783308046356/shotguns_hell_first_half.mp4?ex=657b4d53&is=6568d853&hm=1e32641af5b19e3684fa567b34bec3107d171bf706b65fe1170c4e2986c6d00d&

https://cdn.discordapp.com/attachments/640744619302453316/1179855805592371230/shotguns_hell_second_half.mp4?ex=657b4d58&is=6568d858&hm=c82a692c035270eec2daffb919f42354a94d5603f6823e3f720f1efe4844579c&

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/ab0de9cb-356c-450c-acc6-2872aa9898a2)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/b64f9d5d-a91b-49de-9125-02911b18799d)

</details>

## Changelog

:cl:
balance: Shotgun shells, ESPECIALLY skyrat's shotgun shells, have been rebalanced to not either be useless or insane in every situation, see pr for details.
image: New sprites for some projectiles, like flechettes and whatnot
/:cl:

2023-11-30 18:55 UTC, desertmote commented
Looks good! Could test the confetti shells, I'm pretty sure those are broken right now. (No confetti at all)

2023-12-01 01:10 UTC, Namwty commented
Flechette are only my concern

Yes I know IRL they are dog at penetrating armors.

But in games, like tarkov ( thanks tarkov and bless MP-43 ) and such, they are known to be hard anti-armor with less dmg shotgun round. Even in the past we had flacchete ( which were anti armor ) and RIP rounds ( aka aim for legs rounds ) on SR.

For consistency and to prevent misleading people ( especially newish players ), I would suggest having those "RIP slugs" or whatever instead of flacchete, even if it's just a rename.

Or have a really good description for said rounds, that CLEARLY mentions that they are BAD at penetrating armors.


But in short, I think shotgun shells generally need tweaking, so this might imrpove the situation, so good stuff.

2023-12-02 17:08 UTC, nikothedude commented
why would you rename the antitide that is the best name ever for a shotgun shell that stems the greytide

you are sucking soul out of the game....

2023-12-02 17:19 UTC, Paxilmaniac commented
> why would you rename the antitide that is the best name ever for a shotgun shell that stems the greytide
> 
> you are sucking soul out of the game....

it had numbers in the name it must be sent to hell

2023-12-03 10:48 UTC, vinylspiders commented
> > why would you rename the antitide that is the best name ever for a shotgun shell that stems the greytide
> > you are sucking soul out of the game....
> 
> it had numbers in the name it must be sent to hell

You could always still work it into the desc as part of the flavor

2023-12-20 15:20 UTC, vinylspiders requested changes
Code looks good, just some minor spelling/grammar type nits.

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/shotgun.dm
> -	SpinAnimation()
What was even going on over here? lol

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
>  /obj/item/ammo_box/advanced/s12gauge/beehive
Still think it'd be cute to do a callback to the 'behave' pun somehow in the desc or something, but this is optional.

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 flechette shells, a small group of tumbling blades that excell at causing terrible wounds."
```suggestion
	desc = "A box of 15 flechette shells. Each shell contains a small group of tumbling blades that excel at causing terrible wounds."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 slug shells, large singular shots that pack a punch."
```suggestion
	desc = "A box of 15 slug shells. Large, singular shots that pack a punch."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 buckshot shells, a modest spread of weaker projectiles."
```suggestion
	desc = "A box of 15 buckshot shells. These have a modest spread of weaker projectiles."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 express pelletshot shells, smaller, but more in total, pellets."
```suggestion
	desc = "A box of 15 express pelletshot shells. The size of the pellet is smaller in diameter than the typical shot, but there are more of them inside each shell."
```
I'm not a shotgun expert by any means but this can be a little clearer I think

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 magnum blockshot shells, larger, but less total, pellets."
```suggestion
	desc = "A box of 15 magnum blockshot shells. The size of the pellet is larger in diameter than the typical shot, but there are less of them inside each shell."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 rubbershot shells, a modest spread of weaker less-lethal projectiles."
```suggestion
	desc = "A box of 15 rubbershot shells. These have a modest spread of weaker, less-lethal projectiles."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 beanbag slug shells, large singular beanbags that pack a less-lethal punch."
```suggestion
	desc = "A box of 15 beanbag slug shells. These are large, singular beanbags that pack a less-lethal punch."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 hunter slug shells, shotgun slugs that excell at damaging the local fauna."
```suggestion
	desc = "A box of 15 hunter slug shells. These shotgun slugs excel at damaging the local fauna."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 hornet's nest shells, less-lethal shells that will bounce off walls and direct themselves toward nearby targets."
```suggestion
	desc = "A box of 15 hornet's nest shells. These are less-lethal shells that will bounce off walls and direct themselves toward nearby targets."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 express pelletshot shells, less-lethal shells that will embed in targets and cause pain on movement."
```suggestion
	desc = "A box of 15 express pelletshot shells. These are less-lethal and will embed in targets, causing pain on movement."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 15 incendiary slug shells, projectiles that ignite targets and leave a trail of fire behind them."
```suggestion
	desc = "A box of 15 incendiary slug shells. These will ignite targets and leave a trail of fire behind them."
```

2023-12-20 15:20 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
> +	desc = "A box of 35 confetti shells, firing a spread of harmless confetti everywhere, yippie!"
```suggestion
	desc = "A box of 35 shotgun shells. These ones contain harmless confetti, yippie!"
```

2023-12-20 15:28 UTC, Paxilmaniac commented on modular_skyrat/modules/shotgunrebalance/code/shotgun.dm
> -	SpinAnimation()
I have no idea

2023-12-20 15:29 UTC, Paxilmaniac commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
>  /obj/item/ammo_box/advanced/s12gauge/beehive
The shells that replaced beehives are called something like hornet or hornet's nest or something of the sort, I think that's fitting enough.

2023-12-20 15:30 UTC, vinylspiders commented on modular_skyrat/modules/shotgunrebalance/code/ammobox.dm
>  /obj/item/ammo_box/advanced/s12gauge/beehive
Fair nuff! Like I said it's up to you

2023-12-20 15:36 UTC, vinylspiders approved these changes

2023-12-20 15:37 UTC, vinylspiders commented
Just needs double checking on the sprites.

2023-12-20 15:45 UTC, GoldenAlpharex approved these changes
Sprites seem fine to me!

2023-12-20 16:11 UTC, merged