Primitive storage 2: food and flower boogaloo
Skyrat-SS13/Skyrat-TG pull request #25377
Opened 2023-12-01 22:56 UTC by xXPawnStarrXx

## About The Pull Request
Okay. I'm going to keep this fairly brief. This adds two primitive storages for both edible items (including bowls of soup) and produce such as inedible flowers, logs and corncobs/peels.
I also added a recipe to craft wooden bowls, as a tribal QoL because mushroom shavings constantly bubbling drives me up the wall.

## How This Contributes To The Skyrat Roleplay Experience
Food/flower storage means less items on tables for better performances on the server and looks nicer than clutter everywhere.
Wooden bowls mean you don't need to find mushrooms on icebox to get easy access to bowls.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/53197594/dac0a5a9-2c3b-4fed-91c2-ab5fd1980e53)

</details>

## Changelog

:cl:
add: Added new storages for tribals/greytiders.
add: Added wooden bowls.
/:cl:

2023-12-01 23:03 UTC, Elli-Skala commented
> because mushroom shavings constantly bubbling drives me up the wall.

Actually a skyrat bug! The default chem mixture of the plant creates a skyrat exclusive synth drink apon harvest

2023-12-01 23:12 UTC, xXPawnStarrXx commented
> > because mushroom shavings constantly bubbling drives me up the wall.
> 
> Actually a skyrat bug! The default chem mixture of the plant creates a skyrat exclusive synth drink apon harvest

I know, I just can't be asked fixing it yet. I'll get around to it later when I wake up.

2023-12-06 06:43 UTC, vinylspiders requested changes

2023-12-06 06:43 UTC, vinylspiders commented on modular_skyrat/modules/primitive_structures/code/storage_structures.dm
> +	return (IS_EDIBLE(weapon) || (istype(weapon,/obj/item/reagent_containers/cup/bowl) && length(weapon.reagents?.reagent_list)))
`length(weapon.reagents?.reagent_list)`

Is there a reason you're not just doing a typecheck for `/obj/item/reagent_containers/` instead? This might end up letting some weird stuff in there, because lots of things have reagents.

2023-12-06 06:43 UTC, vinylspiders commented
Sprites look cute though! Rest of it seems fine

2023-12-06 12:59 UTC, xXPawnStarrXx commented on modular_skyrat/modules/primitive_structures/code/storage_structures.dm
> +	return (IS_EDIBLE(weapon) || (istype(weapon,/obj/item/reagent_containers/cup/bowl) && length(weapon.reagents?.reagent_list)))
It's using reagents because it allows bowls of soup.

2023-12-06 12:59 UTC, xXPawnStarrXx commented on modular_skyrat/modules/primitive_structures/code/storage_structures.dm
> +	return (IS_EDIBLE(weapon) || (istype(weapon,/obj/item/reagent_containers/cup/bowl) && length(weapon.reagents?.reagent_list)))
It's mirrored from the standard smart fridge.

2023-12-06 13:56 UTC, vinylspiders commented on modular_skyrat/modules/primitive_structures/code/storage_structures.dm
> +	return (IS_EDIBLE(weapon) || (istype(weapon,/obj/item/reagent_containers/cup/bowl) && length(weapon.reagents?.reagent_list)))
> It's mirrored from the standard smart fridge.

Ahh it was late I didn't see that it was paired with the bowl istype. That's fine

2023-12-06 13:57 UTC, vinylspiders approved these changes

2023-12-06 13:58 UTC, merged

2023-12-06 14:01 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/stacks/sheets/sheet_types.dm
> -	new/datum/stack_recipe("gutlunch trough", /obj/structure/ore_container/gutlunch_trough, 5, time = 2 SECONDS, one_per_turf = TRUE, on_solid_ground = TRUE, category = CAT_STRUCTURE),
Grrr I just noticed this immediately after it got merged. This recipe got accidentally removed

2023-12-06 17:30 UTC, xXPawnStarrXx commented on modular_skyrat/master_files/code/game/objects/items/stacks/sheets/sheet_types.dm
> -	new/datum/stack_recipe("gutlunch trough", /obj/structure/ore_container/gutlunch_trough, 5, time = 2 SECONDS, one_per_turf = TRUE, on_solid_ground = TRUE, category = CAT_STRUCTURE),
I'll post it as a no GBP fix, I didn't remove anything from that list.

2023-12-06 18:48 UTC, comrade-dagmar commented
yay!