Gives Security The Correct Tackle Gloves
Skyrat-SS13/Skyrat-TG pull request #25386
Opened 2023-12-02 17:23 UTC by Nerev4r

## About The Pull Request
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/59d68dbc-cb20-4892-b2aa-a5419f92b581)

You get the outfit-fitting blue ones instead.

## How This Contributes To The Skyrat Roleplay Experience
Red's dead.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
 
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/12636964/824c191c-7dd7-43b0-bdec-2b8dd9c00ed8)
 
</details>

## Changelog
:cl:
fix: Lopland Security has finally negotiated an order of blue tackle gloves with the FTU, abandoning the red NanoTrasen models.
/:cl:

2023-12-02 21:00 UTC, Plum-but-gayer commented
THANK you god this was bugging me

2023-12-02 23:47 UTC, Hatterhat commented
lmao oops i thought i fixed that sorry

2023-12-03 06:13 UTC, vinylspiders requested changes

2023-12-03 06:13 UTC, vinylspiders commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/gloves/tackler/security(src) //SKYRAT EDIT CHANGE - Gives Them The Blue Ones
```suggestion
	new /obj/item/clothing/gloves/tackler/security(src) // SKYRAT EDIT CHANGE - Gives Them The Blue Ones - ORIGINAL: new /obj/item/clothing/gloves/tackler(src)
```
Dont forget the original code when doing a change

2023-12-03 06:35 UTC, vinylspiders approved these changes

2023-12-03 08:53 UTC, merged