Puts an extra set of gear into the Detective Locker. Yippee!
Skyrat-SS13/Skyrat-TG pull request #25436
Opened 2023-12-05 02:23 UTC by MrDerpi

## About The Pull Request

It's finally been done. What detectives have been awaiting, maybe even the admins that have to spawn in an extra Det locker every few rounds. This PR _should_ add a second set of gear into det lockers on all maps, and replace the second det locker on Blueshift with a filing cabinet, since that would mean there'd be 4 sets of det gear.

However, this does not prevent greytiders from stealing. Sorry!

## How This Contributes To The Skyrat Roleplay Experience

Roleplay wise? Detectives don't have to fight anymore on who gets the flak vest
Quality of Life wise? It makes sense for 2 sets to exist, since there are 2 det slots

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![temp](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/c6a2d462-1f60-46c9-aa94-8c7047b73b0c)
![temp2](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/5c44f228-d137-4fbd-89bf-414b68ec2218)
</details>

## Changelog

:cl: KannaLisvern
del: removes a detective cabinet from blueshift
qol: puts an extra set of gear into the det locker on all maps
/:cl:

2023-12-05 02:23 UTC, MrDerpi commented
Just a note: The reason that liver commit is in there, is because my dumbass forgot to make a new branch. Woops!

2023-12-05 02:54 UTC, SomeRandomOwl commented
You forgot to tick the file in the .dme but i poked you on the discord in #devolopment-code with a quick guide on how to fix the CI failure

2023-12-05 10:04 UTC, Jolly-66 commented
I fear this is going to create the issue of the locker contents failing a unit test later down the line if more crap gets added.

2023-12-05 16:53 UTC, MrDerpi commented
NOOOOOOOOOOOOOOO NOT AGAIN
I DID A BAD, give me two moments

2023-12-05 17:10 UTC, MrDerpi commented
ok, everything should be fine, this is completely fine, i totally didn't accidentally burn everything up just a few minutes ago, nothing happened

2023-12-06 06:58 UTC, vinylspiders requested changes

2023-12-06 06:58 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/structures/crates_lockers/secure/security.dm
> +	..()
```suggestion
	..() // Spawn the full set of gear, twice
```
I hate this but it makes more sense than copy pasting the whole proc from tg and doubling it. At least put a comment so people don't think it's a mistake.

Did you try just going to TG and seeing if they'd accept a double-gear PR there? That would be the ideal solution here...but if not this is probably the next best thing.

2023-12-06 12:47 UTC, dis-integrates-the-integration-tests commented on modular_skyrat/master_files/code/game/objects/structures/crates_lockers/secure/security.dm
> +	..()
I have not tried going to TG, but if you want me to I'll try!

2023-12-06 14:12 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/structures/crates_lockers/secure/security.dm
> +	..()
At the very least it would be something you can ask in discord whether they'd be into. If not, we can just do this

2023-12-06 17:18 UTC, MrDerpi commented on modular_skyrat/master_files/code/game/objects/structures/crates_lockers/secure/security.dm
> +	..()
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/d7ab3f03-9953-4f36-b3ee-c8d1e4ecfe7e)

2023-12-06 23:09 UTC, vinylspiders approved these changes

2023-12-06 23:09 UTC, merged