Bluespace Crystals-less emergency beds.
Skyrat-SS13/Skyrat-TG pull request #25488
Opened 2023-12-07 22:32 UTC by dis-integrates-the-integration-tests

## About The Pull Request

This PR _should_ remove the bluespace crystals from the medical emergency roller bed's recipe.
Yeah, that's about it.

## How This Contributes To The Skyrat Roleplay Experience

I've asked people what their opinions were on bluespace crystals being used in the recipe, and pretty much 90% of them said it doesn't make sense. There's no bluespace technology that can be seen being used in roller beds, hence there's no reason for them to be used, besides: Roller beds are **already** locked behind scientific research.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/54a2a121-54ac-409f-a62a-97bc17ea68e8)

</details>

## Changelog

:cl: KannaLisvern
balance: Removed Bluespace Crystals from roller bed's recipe.
/:cl:

2023-12-08 00:19 UTC, fabelsascha commented
Based

2023-12-08 01:47 UTC, vinylspiders requested changes

2023-12-08 01:47 UTC, vinylspiders commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/titanium = SHEET_MATERIAL_AMOUNT * 2.7, /datum/material/plastic = SHEET_MATERIAL_AMOUNT * 1.7, /datum/material/diamond = SMALL_MATERIAL_AMOUNT * 5) // SKYRAT EDIT CH
Upstream would probably take this. The rational when it was added was probably something like they fold in on themselves extradimensionally to take up less space but it is a bit overkill if you ask me.

If not just make sure you add to the comment the full line of original code and not just the part that was removed

2023-12-08 02:46 UTC, dis-integrates-the-integration-tests commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/titanium = SHEET_MATERIAL_AMOUNT * 2.7, /datum/material/plastic = SHEET_MATERIAL_AMOUNT * 1.7, /datum/material/diamond = SMALL_MATERIAL_AMOUNT * 5) // SKYRAT EDIT CH
I'll ask TG if they need this 👍

2023-12-08 02:58 UTC, dis-integrates-the-integration-tests commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/titanium = SHEET_MATERIAL_AMOUNT * 2.7, /datum/material/plastic = SHEET_MATERIAL_AMOUNT * 1.7, /datum/material/diamond = SMALL_MATERIAL_AMOUNT * 5) // SKYRAT EDIT CH
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/474b4989-98ba-4510-94a1-e41a762bfc22)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/9494d4a8-fce4-4b0e-a985-275be019e57e)

2023-12-08 02:58 UTC, dis-integrates-the-integration-tests commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/titanium = SHEET_MATERIAL_AMOUNT * 2.7, /datum/material/plastic = SHEET_MATERIAL_AMOUNT * 1.7, /datum/material/diamond = SMALL_MATERIAL_AMOUNT * 5) // SKYRAT EDIT CH
a

im gonna make a PR on tg later, it's like 5 am here

2023-12-08 02:59 UTC, vinylspiders commented on code/modules/research/designs/medical_designs.dm
> +	materials = list(/datum/material/titanium = SHEET_MATERIAL_AMOUNT * 2.7, /datum/material/plastic = SHEET_MATERIAL_AMOUNT * 1.7, /datum/material/diamond = SMALL_MATERIAL_AMOUNT * 5) // SKYRAT EDIT CH
Cool, go ahead and make it upstream then! You might be able to bill it as a fix/qol rather than balance as well since it seems so odd that it would require them in the first place.

2023-12-20 05:42 UTC, vinylspiders commented
Closing this in favor of https://github.com/tgstation/tgstation/pull/80190, whenever it reaches us

2023-12-20 05:42 UTC, closed without merging