PR of the day, a day late | I HATE THE ANTICHRIST!! | Upgrades the SolFed response outfits (except the engineering one)
Skyrat-SS13/Skyrat-TG pull request #25490
Opened 2023-12-07 23:31 UTC by Paxilmaniac

## About The Pull Request

As the title says, the SolFed emergency call outfits have been updated with some of the new stuff we have, and some new items I'm adding for them.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/4a07ff0a-dfe3-4a48-976b-050fb45cb030)

Marshalls no longer look like wild west larpers, instead wearing a solfed-blue flak jacket alongside their uniform.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/27045536-c5bf-4382-b45e-23e103464f70)

SWAT is now some proper SolFed peacekeepers, sporting blue helmets and all.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/dd5bda10-c57c-4970-a4e9-d0a1396ccfb9)

The military is now no longer just dressed as the HECU, and no longer uses the m16 (amen).

Note that the gas mask is the wrong one here, I just forgot to set it to the right one.

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/3a452a8f-8be6-49dd-a127-bb5b60c63e00)

EMTs are now equipped like some real deal galactic EMTs, instead of just station paramedics

Of course, the new clothing items can also be found in cargo, because I'm fun like that.

## How This Contributes To The Skyrat Roleplay Experience

It's hard to take the SolFed call guys seriously when they are all either larping as wild west cowboys, or when they're dressed like the fucking hecu from half life. Now that we have actual thematic armor and clothing for SolFed, its only right that their response teams are dressed with them.

## Proof of Testing

See screenshots above for more

![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/06d07d5e-9a2a-4bfd-9257-d71cb973042f)
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/82386923/af4a801a-e59b-4645-aa96-8ef8f5a0c615)

## Changelog

:cl:
balance: SolFed response team equipment has been changed around a bit with the new armor and whatnot.
image: SolFed response teams (and cargo imports) can now see a new set of SolFed uniforms, one for peacekeepers and one for EMTs. No longer do they have to dress as wild west larpers, or half life HECU.
/:cl:

2023-12-15 18:09 UTC, projectkepler-ru commented
Finally

I can really hate the anti christ

2023-12-17 19:57 UTC, GoldenAlpharex requested changes
Tiny nitpicks that I'll commit myself.

2023-12-17 19:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/goofsec/code/sol_fed.dm
> +		/obj/item/beamout_tool = 1
```suggestion
		/obj/item/beamout_tool = 1,
```

2023-12-17 19:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/goofsec/code/sol_fed.dm
> +		/obj/item/ammo_box/magazine/c40sol_rifle/standard = 4
```suggestion
		/obj/item/ammo_box/magazine/c40sol_rifle/standard = 4,
```

2023-12-17 19:59 UTC, GoldenAlpharex approved these changes
Okay, this should be good to go now.

2023-12-20 15:23 UTC, merged