Suppressorsweep 2023
Skyrat-SS13/Skyrat-TG pull request #25512
Opened 2023-12-09 02:42 UTC by Paxilmaniac

## About The Pull Request

Two things:

Suppressors no longer change the w_class of guns.

The lanca and miecz can have suppressors attached now.

## How This Contributes To The Skyrat Roleplay Experience

Suppressors don't provide too much of an advantage at all, and yet increase the size of any gun they are put on by an entire w_class, which while fine enough for pistols and whatnot, means that rifles with suppressors can't be stored literally anywhere except on your back, maybe. A pretty big tradeoff for something you don't gain much from, don't you say?

The lanca and miecz not being suppressable before was a simple matter of me being too lazy to make suppressor sprites for them before, but now they have them, woe.

## Proof of Testing

I can't test anything rn because master fails compile.

## Changelog

:cl:
qol: The lanca and miecz can be suppressed.
qol: Suppressors no longer increase the weight class of a gun they're attached to.
image: New sprites for lanca and miecz suppressors done by me.
/:cl:

2023-12-09 05:09 UTC, Plum-but-gayer commented
shhhhmaxxing

2023-12-09 06:32 UTC, SomeRandomOwl commented
You say you fail to compile, are you on the beta branch of byond (515) we pushed a update that requires you to be on version 515 in order to compile

2023-12-09 20:38 UTC, Paxilmaniac commented
> You say you fail to compile, are you on the beta branch of byond (515) we pushed a update that requires you to be on version 515 in order to compile

I was on the beta, I just had to pull from master and it seems fixed now

2023-12-14 15:38 UTC, vinylspiders requested changes
Seems fine to me otherwise

2023-12-14 15:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_weapons/code/suppressor_size_change_override.dm
> +	update_appearance()
```suggestion
	. = ..()
	w_class -= added_suppressor.w_class // we do not want suppressors to change the w_class of ballistic weapons
```
Might as well just piggyback on the parent proc in case they add anything upstream there. You can get rid of the added weight class from calling parent by doing the inverse

2023-12-14 15:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_weapons/code/suppressor_size_change_override.dm
> +	return ..()
```suggestion
	if(isitem(suppressed))
		var/obj/item/removed_suppressor = suppressed
		w_class += removed_suppressor.w_class // so we don't end up with a lower w_class than what we started with
	return ..()
```
This is kind of screwy but calling the parent is going to subtract the w_class so we need to add it here in order to preserve the no change behavior.

2023-12-14 15:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_weapons/code/suppressor_size_change_override.dm
> +/obj/item/gun/ballistic/install_suppressor(obj/item/suppressor/added_suppressor)
```suggestion
// suppressors do not change w_class
/obj/item/gun/ballistic/install_suppressor(obj/item/suppressor/added_suppressor)
```

2023-12-14 15:38 UTC, vinylspiders commented on modular_skyrat/modules/modular_weapons/code/suppressor_size_change_override.dm
> +/obj/item/gun/ballistic/clear_suppressor()
```suggestion
// suppressors do not change w_class
/obj/item/gun/ballistic/clear_suppressor()
```

2023-12-16 15:17 UTC, vinylspiders approved these changes

2023-12-16 15:17 UTC, merged