Adds Horn Option: Palmated Antlers
Skyrat-SS13/Skyrat-TG pull request #25536
Opened 2023-12-10 01:48 UTC by Jonnatonne

## About The Pull Request
Adds a new horn type, based on the wide palmated antlers of moose and elk!

## How This Contributes To The Skyrat Roleplay Experience
Helps cervid anthro players express their characters appearance better in-game. And allows intended character appearances to be better illustrated using in-game sprites.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/148730169/a1065876-ee4b-4544-a252-2025ffa7c702)
</details>

## Changelog

:cl:
add: Adds new palmated antler horn type.
/:cl:

2023-12-10 03:55 UTC, vinylspiders approved these changes
Looks good to me, @GoldenAlpharex ?

2023-12-12 22:50 UTC, GoldenAlpharex requested changes, later dismissed
Outside of that, looks great to me!

2023-12-12 22:50 UTC, GoldenAlpharex commented on modular_skyrat/master_files/icons/mob/sprite_accessory/horns_big.dmi
If you don't have a use for the _BEHIND version, then it shouldn't be there as an empty icon state.

2023-12-13 03:03 UTC, Jonnatonne commented on modular_skyrat/master_files/icons/mob/sprite_accessory/horns_big.dmi
Sorry, first time spriting with this system, it's fixed! Good catch.

2023-12-14 15:08 UTC, merged