*moan but a little more exciting. For mature, rugged souls!
Skyrat-SS13/Skyrat-TG pull request #25559
Opened 2023-12-11 21:28 UTC by dis-integrates-the-integration-tests

## About The Pull Request

This PR _should_ add a new *lewdmoan emote. It's actually just the climax verb moans but put into a usable emote.
Note: This is an ERP emote, with ERP preferences.

Further clarification: This emote is designed **SOLELY** for ERP purposes, meaning: If people start for some reason *lewdmoan'ing at random and for reasons that don't require it, **that would be a player issue, not a feature one.**

This PR also adds a framework for lewd emotes, if any are made in the future. It makes it so that lewd emotes are completely invisible to people with ERP prefs turned off, even the emote popup. 

## How This Contributes To The Skyrat Roleplay Experience

I've always wondered why there isn't a way to moan that isn't using the Climax verb, so I fixed that.
Skyrat roleplay experience-wise? Uhh.. Erotic roleplay. You moan... Or you just tease a friend because you feel like it. I don't know how you roleplay but this is something you can use for roleplay reasons!

Furthermore, it's a fully manual emote, meaning there isn't a way to accidentally moan unless you somehow click everything in the emote panel. So there won't be any cases of "Bro I did not mean to do THAT"

Furthestmore, I feel like it's a waste to have no emotes that use the moan .ogg(s), since people barely actually use the Climax verb. I think people will make good use of it. 

## Proof of Testing, UPDATED.

<details>
<summary>Screenshots/Videos</summary> 

## VOLUME WARNING. 00:18 for turned off ERP prefs.
[https://cdn.discordapp.com/attachments/640760727489085450/1183875882742468751/SPOILER_VmyDQWi.mp4?ex=6589ed55&is=65777855&hm=d00f69de6fa3b2fb9f96b81016b96cba5961c0aadb59b74a48289997c91359e0&](https://discord.com/channels/596783386295795713/640760727489085450/1186475238964342874)
</details>

## Changelog

:cl: KannaLisvern
add: Added a new ERP emote. *lewdmoan
/:cl:

2023-12-12 21:40 UTC, dis-integrates-the-integration-tests commented
me when
it took 3 attempts to get no ci failures
I LOVE integration tests

2023-12-17 17:44 UTC, vinylspiders requested changes

2023-12-17 17:44 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +		return FALSE
```suggestion
	if(!.)
		return
	if(!ishuman(user))
		return
	var/mob/living/carbon/human/human_user = user
```
Need to be checking the return value here to make sure the user is actually able to emote, otherwise it'll let them moan while dead and such. Miming check not needed (see below)

2023-12-17 17:44 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +										'modular_skyrat/modules/modular_items/lewd_items/sounds/final_m3.ogg'), 50, TRUE, pref_to_check = /datum/preference/toggle/erp/sounds)
```suggestion

/datum/emote/living/lewdmoan/get_sound(mob/living/carbon/user)
	if(!istype(user))
		return

	if(user.gender == MALE)
		return pick('modular_skyrat/modules/modular_items/lewd_items/sounds/final_m1.ogg',
					'modular_skyrat/modules/modular_items/lewd_items/sounds/final_m2.ogg',
					'modular_skyrat/modules/modular_items/lewd_items/sounds/final_m3.ogg',

		)
	else
		return pick('modular_skyrat/modules/modular_items/lewd_items/sounds/final_f1.ogg',
					'modular_skyrat/modules/modular_items/lewd_items/sounds/final_f2.ogg',
					'modular_skyrat/modules/modular_items/lewd_items/sounds/final_f3.ogg',
		)
```
You shouldn't be doing it hardcoded like this, use `get_sound()` instead when playing conditional emote sounds. This should also removes the need for the miming check as it will be handled by `should_play_sound()` (it also handles mute, muzzled, etc).

2023-12-17 17:44 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +
```suggestion
	emote_type = EMOTE_VISIBLE | EMOTE_AUDIBLE
	vary = TRUE

```
You may or may not want this to randomize the pitch. Also, if you want to modify the volume from the default of 25 (you had it at 50 before)? here's the spot to set it with `sound_volume = whatever`

2023-12-17 18:27 UTC, dis-integrates-the-integration-tests commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +										'modular_skyrat/modules/modular_items/lewd_items/sounds/final_m3.ogg'), 50, TRUE, pref_to_check = /datum/preference/toggle/erp/sounds)
butbutbut
By using `get_sound()`, I can no longer use `play_lewd_sound`, which means I can't have the erp pref checks, no?

2023-12-17 18:29 UTC, dis-integrates-the-integration-tests commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +										'modular_skyrat/modules/modular_items/lewd_items/sounds/final_m3.ogg'), 50, TRUE, pref_to_check = /datum/preference/toggle/erp/sounds)
Actually. Fuck the erp sound checks altogether
It's a manual emote, I'll just trust non-ERP'ers not to type in *lewdmoan
I was using `get_sound` before, but it kind of doesn't work with `play_lewd_sound` of course, so that's why I changed it

2023-12-17 19:08 UTC, dis-integrates-the-integration-tests commented
now to uh, test it
when i get on my laptop hopefully

2023-12-18 22:39 UTC, dis-integrates-the-integration-tests commented
this error's gonna make me lose my mind lol
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/109750345/dedb558f-0a8c-40f2-ad66-9de2fda1ec11)
gimme a few

2023-12-18 23:44 UTC, dis-integrates-the-integration-tests commented
pending new testing footage :tm:

2023-12-19 00:54 UTC, dis-integrates-the-integration-tests commented
ok uh
in the future, if this gets merged
/datum/emote/living/lewd will be the path for lewd emotes
because pref checks and stuff

2023-12-19 01:12 UTC, dis-integrates-the-integration-tests commented
updated proof of testing thingy

2023-12-19 12:06 UTC, vinylspiders requested changes

2023-12-19 12:06 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +/datum/emote/living/lewd/lewdmoan
```suggestion
/datum/emote/living/lewd
	var/pref_to_check = /datum/preference/toggle/erp/sounds

/datum/emote/living/lewd/can_run_emote(mob/living/carbon/user, status_check = TRUE, intentional)
	return ..() && user.client?.prefs?.read_preference(/datum/preference/toggle/erp)

/datum/emote/living/lewd/lewdmoan
```
You can move this from master files to the module since it's not overriding anything. Also make sure we are checking prefs for actually being able to use the emote in the first place.

2023-12-19 12:06 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	message = "moans lewdly!"
```suggestion
	message = "moans!"
```
It might be a good idea to make this a bit more generic, so that people who have erp prefs off can't distinguish it from the tg emote.

Alternatively, what you could do if you really want to keep it labeled 'lewdly' you can add a check for prefs where the emote gets displayed and just not show it to anyone without erp prefs toggled if it's a lewd emote.

https://github.com/Skyrat-SS13/Skyrat-tg/blob/686569101b779fc089142a1faeae91773db60bc6/code/datums/emotes.dm#L131-L139

2023-12-19 12:08 UTC, vinylspiders requested changes

2023-12-19 12:08 UTC, vinylspiders commented on modular_skyrat/master_files/code/datums/emotes.dm
> +	var/pref_to_check = /datum/preference/toggle/erp/sounds
```suggestion
```

2023-12-19 22:39 UTC, dis-integrates-the-integration-tests commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	message = "moans lewdly!"
sir yes sir

2023-12-19 23:51 UTC, vinylspiders requested changes

2023-12-19 23:51 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +
```suggestion

// Can we play this emote to viewers?
/datum/emote/proc/pref_check_emote(mob/user)
	return TRUE

/datum/emote/living/lewd/pref_check_emote(mob/user)
	. = ..()
	if(!user.client?.prefs.read_preference(/datum/preference/toggle/erp))
		return FALSE

```

2023-12-19 23:55 UTC, dis-integrates-the-integration-tests commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +
SIR YES SIR

2023-12-20 01:20 UTC, vinylspiders requested changes

2023-12-20 01:20 UTC, vinylspiders commented on code/datums/emotes.dm
> +			user.audible_message(msg, deaf_message = "<span class='emote'>You see how <b>[user]</b>[space][msg]</span>", audible_message_flags = EMOTE_MESSAGE, separation = space) // SKYRAT EDIT - Better emot
```suggestion
		user.audible_message(msg, deaf_message = "<span class='emote'>You see how <b>[user]</b>[space][msg]</span>", audible_message_flags = EMOTE_MESSAGE, separation = space, pref_to_check = pref_to_check) // SKYRAT EDIT - Better emotes - ORIGINAL: user.audible_message(msg, deaf_message = "<span class='emote'>You see how <b>[user]</b> [msg]</span>", audible_message_flags = EMOTE_MESSAGE)
```

2023-12-20 01:20 UTC, vinylspiders commented on code/datums/emotes.dm
> +			user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE, separation = space) // SKYRAT EDIT - Better emotes - ORIGINAL: user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE)
```suggestion
		user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE, separation = space, pref_to_check = pref_to_check)) // SKYRAT EDIT - Better emotes - ORIGINAL: user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE)
```

2023-12-20 01:27 UTC, vinylspiders requested changes

2023-12-20 01:27 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	var/pref_to_check = /datum/preference/toggle/erp/sounds
```suggestion
/datum/emote
	/// If we should check a preference for this emote
	var/pref_to_check

/datum/emote/living/lewd
	pref_to_check = /datum/preference/toggle/erp/sounds
```

2023-12-20 01:27 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	return TRUE
```suggestion
/datum/emote/proc/pref_check_emote(mob/user)
	if(isnull(pref_to_check))
		return TRUE
	if(!user.client?.prefs.read_preference(pref_to_check))
		return FALSE
```
Might as well generalize this

2023-12-20 01:27 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +		return FALSE
```suggestion
```

2023-12-20 01:30 UTC, vinylspiders requested changes

2023-12-20 01:30 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	return ..() && user.client?.prefs?.read_preference(/datum/preference/toggle/erp)
```suggestion
	return ..() && user.client?.prefs?.read_preference(pref_to_check)
```

2023-12-20 01:31 UTC, vinylspiders requested changes

2023-12-20 01:31 UTC, vinylspiders commented on code/datums/emotes.dm
> +		user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE, separation = space, pref_to_check = pref_to_check)) // SKYRAT EDIT - Better emotes - ORIGINAL: user.visible_message(msg, visible_mes
```suggestion
		user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE, separation = space, pref_to_check = pref_to_check) // SKYRAT EDIT - Better emotes - ORIGINAL: user.visible_message(msg, visible_message_flags = EMOTE_MESSAGE)
```

2023-12-20 01:35 UTC, vinylspiders requested changes

2023-12-20 01:35 UTC, vinylspiders commented on code/modules/mob/mob.dm
> +/atom/proc/audible_message(message, deaf_message, hearing_distance = DEFAULT_MESSAGE_RANGE, self_message, audible_message_flags = NONE, separation = " ", pref_to_check =) // SKYRAT EDIT ADDITION - Be
```suggestion
/atom/proc/audible_message(message, deaf_message, hearing_distance = DEFAULT_MESSAGE_RANGE, self_message, audible_message_flags = NONE, separation = " ", pref_to_check) // SKYRAT EDIT ADDITION - Better emotes, pref checks
```

2023-12-20 01:35 UTC, vinylspiders commented on code/modules/mob/mob.dm
> +/atom/proc/visible_message(message, self_message, blind_message, vision_distance = DEFAULT_MESSAGE_RANGE, list/ignored_mobs, visible_message_flags = NONE, separation = " ", pref_to_check =) // SKYRAT
```suggestion
/atom/proc/visible_message(message, self_message, blind_message, vision_distance = DEFAULT_MESSAGE_RANGE, list/ignored_mobs, visible_message_flags = NONE, separation = " ", pref_to_check) // SKYRAT EDIT ADDITION - separation, pref checks
```

2023-12-20 01:50 UTC, vinylspiders requested changes

2023-12-20 01:50 UTC, vinylspiders commented on code/modules/mob/mob.dm
> +		if(prefs_to_check && !user.client?.prefs.read_preference(prefs_to_check))
```suggestion
		if(pref_to_check && !user.client?.prefs.read_preference(pref_to_check))
```

2023-12-20 01:50 UTC, vinylspiders commented on code/modules/mob/mob.dm
> +		if(prefs_to_check && !user.client?.prefs.read_preference(prefs_to_check))
```suggestion
		if(pref_to_check && !user.client?.prefs.read_preference(pref_to_check))
```

2023-12-20 02:24 UTC, vinylspiders requested changes

2023-12-20 02:24 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +var/pref_to_check
```suggestion
	/// If we should check a preference for this emote
	var/pref_to_check
```

2023-12-20 02:28 UTC, vinylspiders requested changes

2023-12-20 02:28 UTC, vinylspiders commented on code/modules/mob/mob.dm
> +		if(pref_to_check && !user.client?.prefs.read_preference(pref_to_check))
```suggestion
		if(pref_to_check && !M.client?.prefs.read_preference(pref_to_check))
```

2023-12-20 02:28 UTC, vinylspiders commented on code/modules/mob/mob.dm
> +		if(pref_to_check && !user.client?.prefs.read_preference(pref_to_check))
```suggestion
		if(pref_to_check && !M.client?.prefs.read_preference(pref_to_check))
```

2023-12-20 02:28 UTC, vinylspiders commented on code/datums/emotes.dm
> +			play_lewd_sound(user, tmp_sound, sound_volume, vary, pref_to_check = lewd_emote.pref_to_check)
```suggestion
		if(istype(src, /datum/emote/living/lewd))
			play_lewd_sound(user, tmp_sound, sound_volume, vary, pref_to_check = pref_to_check)
```
You can get rid of the casting to a lewd emote here now that the var is on the base emote datum

2023-12-20 03:06 UTC, vinylspiders requested changes

2023-12-20 03:06 UTC, vinylspiders commented on code/datums/emotes.dm
> +			play_lewd_sound(user, tmp_sound, sound_volume, vary, pref_to_check = pref_to_check)
```suggestion
			play_lewd_sound(user, tmp_sound, sound_volume, vary, pref_to_check = /datum/preference/toggle/erp/sounds)
```

2023-12-20 03:06 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	pref_to_check = /datum/preference/toggle/erp/sounds
```suggestion
	pref_to_check = /datum/preference/toggle/master_erp_preferences
```

2023-12-20 03:09 UTC, vinylspiders approved these changes

2023-12-20 03:11 UTC, vinylspiders reviewed
These were already inside of a skyrat edit

2023-12-20 03:11 UTC, vinylspiders commented on code/datums/emotes.dm
> +					if(pref_check_emote(viewer)) // SKYRAT EDIT ADDITION - Pref checked emotes
```suggestion
					if(pref_check_emote(viewer))
```

2023-12-20 03:11 UTC, vinylspiders commented on code/datums/emotes.dm
> +			hologram.visible_message(msg, visible_message_flags = EMOTE_MESSAGE, pref_to_check = pref_to_check) // SKYRAT EDIT CHANGE - added pref_to_check
```suggestion
			hologram.visible_message(msg, visible_message_flags = EMOTE_MESSAGE, pref_to_check = pref_to_check)
```

2023-12-20 03:11 UTC, vinylspiders commented on code/datums/emotes.dm
> +			hologram.audible_message(msg, deaf_message = span_emote("You see how <b>[user]</b> [msg]"), audible_message_flags = EMOTE_MESSAGE, pref_to_check = pref_to_check) // SKYRAT EDIT CHANGE - added pref
```suggestion
			hologram.audible_message(msg, deaf_message = span_emote("You see how <b>[user]</b> [msg]"), audible_message_flags = EMOTE_MESSAGE, pref_to_check = pref_to_check)
```

2023-12-20 03:50 UTC, vinylspiders commented on modular_skyrat/modules/modular_items/lewd_items/code/emote.dm
> +	pref_to_check = /datum/preference/toggle/master_erp_preferences
```suggestion
	pref_to_check = /datum/preference/toggle/erp
```

2023-12-20 04:01 UTC, merged