Laser pointer fixes: remove felinid forced movement, chat notificatio…
Skyrat-SS13/Skyrat-TG pull request #25588
Opened 2023-12-13 01:37 UTC by Ephemeralis

## About The Pull Request

Since laser pointers are loadout-available as of https://github.com/Skyrat-SS13/Skyrat-tg/pull/25532, this PR does a little bit of balancejakking on them to make the prospect not pure misery for cyborgs and felinid players. It does the following:

- A new limited laser-pointer type that cannot receive any upgrades or have its micro laser removed (locked to t1, essentially)
- Proper `visible_message` signalling to show nearby players who is pointing a laser pointer, and at what. Includes `span_danger` colouring if the person is trying to do something hostile with said action.
- Removes the forced felinid movement on laser pointers. Not only is this lame on a roleplay server, it could also be used in a few circumstances on certain maps to allow felinids to bend time and space and skidoodle themselves through diagonal windoors to get into departments, *apparently*. Felinids still turn to look at laser pointers and keep the same messaging as before, though.

## How This Contributes To The Skyrat Roleplay Experience

This should help make a sudden glut of laser pointers via loadout availability not *quite* as miserable as they could've been. The camera EMP thing is still going to make AI players pretty miserable, as is the ranged stun/flash on cyborgs, but we can address that as we go, I guess.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![dreamseeker_HJZAX3nIYe](https://github.com/Skyrat-SS13/Skyrat-tg/assets/966289/7fdaa77c-3044-4c61-8734-a7bccbb49dfb)

https://github.com/Skyrat-SS13/Skyrat-tg/assets/966289/7aa05d28-8777-4c55-a24e-36de263a9739

</details>

## Changelog

:cl: yooriss
fix: Laser pointers now show appropriate messaging to nearby players when someone is using them for both benign and hostile actions.
fix: Due to budget cuts and petitioning from protesting silicons, the FTU has replaced all full-power laser pointers available in crew loadouts with limited promotional versions that can't have their diodes repaired or upgraded on the field.
fix: Extensive lobbying by the Felinid Rights Association has forced the FTU to replace all laser pointer diodes with special low 'radiationyan' variants that no longer trigger felinids to compulsively leap. They're still super distracting though...
/:cl:

2023-12-13 02:09 UTC, vinylspiders requested changes
The three skyrat edit changes at the bottom of the file are fine to keep, but everything else can be made a modular override quite easily. Could you please do that in `modular_skyrat/master_files/code/game/objects/items/devices/laserpointer.dm`?

2023-12-13 02:09 UTC, vinylspiders commented on code/game/objects/items/devices/laserpointer.dm
> +			target_felinid.visible_message(span_notice("[target_felinid] looks briefly distracted by the light."), span_warning("You're briefly tempted by the shiny light...")) //SKYRAT EDIT: indent this bloc
```suggestion
			target_felinid.visible_message(span_notice("[target_felinid] looks briefly distracted by the light."), span_warning("You're briefly tempted by the shiny light...")) //SKYRAT EDIT CHANGE : indent this block if re-enabling above
```

2023-12-13 02:09 UTC, vinylspiders commented on code/game/objects/items/devices/laserpointer.dm
> +			else */
```suggestion
			else 
			SKYRAT EDIT REMOVAL END */
```

2023-12-13 02:09 UTC, vinylspiders commented on code/game/objects/items/devices/laserpointer.dm
> +		user.visible_message(span_notice("[user] points [src] at [target]."), span_notice("You point [src] at [target].")) //SKYRAT EDIT
```suggestion
		user.visible_message(span_notice("[user] points [src] at [target]."), span_notice("You point [src] at [target].")) //SKYRAT EDIT CHANGE - ORIGINAL: to_chat(user, span_info("You point [src] at [target]."))
```

2023-12-13 02:09 UTC, vinylspiders commented on code/game/objects/items/devices/laserpointer.dm
> +		user.visible_message(span_danger("[user] points [src] at [target]!"), outmsg) //SKYRAT EDIT
```suggestion
		user.visible_message(span_danger("[user] points [src] at [target]!"), outmsg) //SKYRAT EDIT CHANGE - ORIGINAL: to_chat(user, outmsg)
```

2023-12-13 04:34 UTC, dis-integrates-the-integration-tests commented
Damn, a balancejak change that I actually like?
This is for the best, probably.

2023-12-13 04:42 UTC, dis-integrates-the-integration-tests commented
I think you may or may not have forgotten something, though.
I also added the laser to the Good Clean Fun vendor. Should probably change the laser type there.

2023-12-13 04:48 UTC, Ephemeralis commented
> I think you may or may not have forgotten something, though. I also added the laser to the Good Clean Fun vendor. Should probably change the laser type there.

Changed this, thanks!

> The three skyrat edit changes at the bottom of the file are fine to keep, but everything else can be made a modular override quite easily. Could you please do that in `modular_skyrat/master_files/code/game/objects/items/devices/laserpointer.dm`?

I've given this a swing and it seems to work on preliminary testing. @vinylspiders

2023-12-13 10:20 UTC, OrionTheFox commented
> radiatio"nyan"
You're an evil, evil person...

Either way though, great PR, good solutions to the problem while still giving players the ability to play with the funny light pointer thingies. 👍  from me

2023-12-17 09:18 UTC, Plum-but-gayer commented
praise fucking be. good pr, felinid stamp of approval

2023-12-17 16:53 UTC, vinylspiders requested changes

2023-12-17 16:53 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/laserpointer.dm
> +	. = ..()
```suggestion
	return ..()
```
I'm just gonna go ahead and change these for you, we don't need to do the `. = ..()` at the end of the proc since we are just going to be exiting the proc anyway.

2023-12-17 16:53 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/laserpointer.dm
> +	. = ..()
```suggestion

/obj/item/laser_pointer/attackby(obj/item/attack_item, mob/user, params)
	if(istype(attack_item, /obj/item/stock_parts/micro_laser) || istype(attack_item, /obj/item/stack/ore/bluespace_crystal))
		if(!upgradable)
			balloon_alert(user, "can't upgrade integrated parts!")
			return
	return ..()
```

2023-12-17 16:55 UTC, vinylspiders approved these changes
Looks good, nice work!

2023-12-17 17:23 UTC, merged