Use preloaded MODsuit scryers in loadout & exosuit fabs
Skyrat-SS13/Skyrat-TG pull request #25604
Opened 2023-12-13 22:52 UTC by Ephemeralis

## About The Pull Request

Adjusts loadout and exosuit fabs to use the "loaded" MODsuit scryer object, allowing them to actually be functional at roundstart/when printed with minimal setup.

The base type that was previously given via loadout had no frequency set, and the only way you could get it set was to hope robotics had a MOD crate lying around with pre-loaded scryers that have the NT frequency prebaked, then pestering them to copy the frequency across via multitool for you. 

Very annoying and almost certainly not intended. No more!

## How This Contributes To The Skyrat Roleplay Experience

This makes MODsuit scryers an actually usable loadout choice, and a viable alternative to holocalling that doesn't consume all of your bodily fluids like the NIF version does.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![dreamseeker_MGEMXyPdJQ](https://github.com/Skyrat-SS13/Skyrat-tg/assets/966289/e03e9ff0-9e40-4ba8-9e35-5ce575e727ee)

</details>

## Changelog

:cl: yooriss
fix: Loadout MODsuit scryers now come with the NT frequency by default, allowing them to actually be used without requiring complicated setup. Try them out again and holocall all your friends!
/:cl:

2023-12-14 00:39 UTC, SomeRandomOwl commented
They where originally edited this way in loadout because cafe cant and shouldn't be able to call station. That should be fixed first and formost

2023-12-14 07:03 UTC, Ephemeralis commented
> They where originally edited this way in loadout because cafe cant and shouldn't be able to call station. That should be fixed first and formost

I've added a modular overload to address this:

![dreamseeker_EtK73TqFKN](https://github.com/Skyrat-SS13/Skyrat-tg/assets/966289/a8553968-da4d-4c16-853d-1af4e5e17fcf)

2023-12-14 14:52 UTC, vinylspiders requested changes
Otherwise, looks good to me.

2023-12-14 14:52 UTC, vinylspiders commented on code/modules/research/designs/mechfabricator_designs.dm
> +	build_path = /obj/item/clothing/neck/link_scryer/loaded //SKYRAT EDIT
Could you please make this varedit a master files override instead of a skyrat edit? With simple varedits like this it's always preferred to do it that way.

You will have to create the `modular_skyrat\master_files\code\modules\research\designsmechfabricator_designs.dm`

2023-12-14 14:52 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +	return .
```suggestion
```
No need for this, that will happen automatically

2023-12-14 14:52 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +		var/area/user_area = get_area(user_turf)
```suggestion
		var/area/user_area = get_area(user)
```
That proc works on atoms as well as turfs so I think you can just directly pass user and it should work.

2023-12-14 14:54 UTC, vinylspiders requested changes

2023-12-14 14:54 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +	if(istype(user))
You could also make this an early return to reduce the amount of indentation in the code.

2023-12-14 16:40 UTC, Ephemeralis commented on code/modules/research/designs/mechfabricator_designs.dm
> +	build_path = /obj/item/clothing/neck/link_scryer/loaded //SKYRAT EDIT
All done, and good to know!

2023-12-14 16:45 UTC, Ephemeralis commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +	if(istype(user))
not quite sure i follow here - you mean inverting the `istype(user)` check and just continuing on base indent underneath it? is this strictly a code format thing or

2023-12-15 17:13 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +	if(istype(user))
Exactly--strictly code style to make it ever so slightly more readable.

2023-12-15 17:14 UTC, vinylspiders requested changes

2023-12-15 17:14 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +			return FALSE
```suggestion
	if(!istype(user))
		return FALSE
		
	var/area/user_area = get_area(user)

	// if we're in a ghost-cafe, we can't call or be called.
	// this will still work on the interlink (/area/centcom/interlink)
	if(istype(user_area, /area/centcom/holding))
		return FALSE
```

2023-12-15 17:14 UTC, vinylspiders commented on modular_skyrat/master_files/code/game/objects/items/devices/mod_link.dm
> +			return FALSE
This is all I meant

2023-12-16 15:44 UTC, vinylspiders approved these changes
Looking good!

2023-12-16 15:44 UTC, merged

2024-02-09 01:35 UTC, lectronyx commented
Oversight: This also messed up modlink scryers for DS-2 and Interdyne characters.