Armadyne Anti Trust Act Part 2: Return of The Ballistic Security
Skyrat-SS13/Skyrat-TG pull request #27409
Opened 2024-04-21 04:34 UTC by projectkepler-ru

## About The Pull Request
Work in progress please wait

## How This Contributes To The Skyrat Roleplay Experience
Having less antag dies horribly in 1-2 hours of the round and balistic sec being something they can tangibly keep track off of if they are paying attention to science or paying attention to radio massively improve the experience, vs the silent cargo buying a ton of guns, sec getting even just one make it nearly unplayable

Details later

## Proof of Testing
Work in progress

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/Skyrat-SS13/Skyrat-tg/assets/99981766/53c82f6e-8d46-479f-a55b-dc0de22dfd4a)

</details>

## Changelog

:cl:
add: Conversion kit for guns, alongside the blueshield/NTC getting m45a5
add: Research for the new technode, military grade weaponry 1 & 2
balance: Due to the on-going Sol Conflict not reflected in  C-3 Sector. skild, takbok, bogseo, AMR, LMG are no longer obtainable, cargo took a very heavy hit due to embargo
balance: made laser much easier to get while ballistic are abit more rare and more expensive
balance: massively overhauled how ballistic security work, being they are now a mid-late game researchable tech
balance: 90% of ammo are no longer purchasable, instead they are available as tech, see above.
image: added new sprites for the gun
/:cl:

2024-07-02 18:08 UTC, projectkepler-ru commented
This will be finished by 7/7

2024-07-07 11:16 UTC, projectkepler-ru commented
@SpaceLoveSs13  I don't have the screenshot up but it's ready now

2024-07-09 14:17 UTC, SpaceLoveSs13 requested changes, later dismissed

2024-07-09 14:17 UTC, SpaceLoveSs13 commented on modular_skyrat/modules/company_imports/code/armament_datums/akh_frontier.dm
> +/*
Why was this done? You havent documented it.

2024-07-09 14:17 UTC, SpaceLoveSs13 commented on modular_skyrat/modules/company_imports/code/armament_datums/akh_frontier.dm
> +/*
This as well

2024-08-06 18:07 UTC, projectkepler-ru commented
No further update. this is ready

2024-08-07 18:09 UTC, projectkepler-ru commented
actually hold on i need to finish up something, it'll be ready proper by sat

2024-08-08 14:44 UTC, projectkepler-ru commented
barring any further issues, this is final

2024-08-12 09:25 UTC, projectkepler-ru commented
sprite broke

2024-08-20 23:47 UTC, merged