Makes Quad-Sec only work inside /area/security
Skyrat-SS13/Skyrat-TG pull request #3223
Opened 2021-02-09 05:50 UTC by MLGTASTICa

## About The Pull Request
Makes quad-sec only have its healing effects apply in security areas
## Why It's Good For The Game
Security uses quad-sec to powergame mid-combat because it has no downsides that other cobbychems have to prevent powergaming.

## Changelog
:cl:
balance: Quadruple Security now only heals inside security areas
/:cl:

2021-02-09 08:26 UTC, KathrinBailey commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +		if(istype(get_area(M), /area/security)) // Skyrat edit , it checks for area now - Start
```suggestion
		if(istype(get_area(M), /area/security)) // SKYRAT EDIT : Checks for area.
```

2021-02-09 08:26 UTC, KathrinBailey commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +		return ..() // Skyrat edit - end
```suggestion
		return ..()
```

2021-02-09 08:29 UTC, KathrinBailey requested changes
The comments are a tad confusing on this, you haven't changed the code below in any way other than indentation, which you should clarify. If you do this it's an EZMERGE

2021-02-09 09:44 UTC, MLGTASTICa commented
> The comments are a tad confusing on this, you haven't changed the code below in any way other than indentation, which you should clarify. If you do this it's an EZMERGE. It's just that the way you did it implies there may be value changes to the healing effects.

Commited your suggestion to the comments, should be enough right?

2021-02-09 23:24 UTC, Investigator77 commented
I think it should have an effect in the bar too, I mean, kinda nullifies anything social about asking it to get it done for you

2021-02-10 06:12 UTC, MLGTASTICa commented
> I think it should have an effect in the bar too, I mean, kinda nullifies anything social about asking it to get it done for you

Bar is usually too central to the station and there is no reason to have it heal in the bar , if you are there to RP you don't need the healing , otherwise seccies will just sprint or fight in the bar because they know they can heal.

2021-02-12 00:07 UTC, Gandalf2k15 commented
I'll accept.

2021-02-12 00:07 UTC, merged