[Modular] Adds Hypnotic Stupor back as neutral trait
Skyrat-SS13/Skyrat-TG pull request #3466
Opened 2021-02-17 21:36 UTC by Guidesu

## About The Pull Request
This trait was pre-rebase so.
Good to have it back

## Why It's Good For The Game
Your mind is obsessed  with "You want sex"
Jokes aside more traits more goods

## Changelog
:cl: Adds Hypnotic Stupor back in neutral trait selection
add: Added new things
/:cl:

2021-02-17 22:11 UTC, Swiftfeather commented on modular_skyrat/modules/customization/datums/traits/neutral.dm
> +	desc = "Your prone to episodes of extreme stupor that leaves you extremely suggestible."
Grammar

2021-02-17 22:12 UTC, NotRanged commented
Meh, this was self-antag the trait

2021-02-17 22:12 UTC, Swiftfeather requested changes
Just the one grammar fix.

2021-02-17 22:13 UTC, tf-4 reviewed
Make your variable names more clear and descriptive in accordance with: https://github.com/tgstation/tgstation/pull/56872

2021-02-17 22:13 UTC, tf-4 commented on modular_skyrat/modules/customization/datums/traits/neutral.dm
> +	var/datum/brain_trauma/severe/hypnotic_stupor/T = new()
Make this more obvious

2021-02-17 22:13 UTC, tf-4 commented on modular_skyrat/modules/customization/datums/traits/neutral.dm
> +	var/mob/living/carbon/human/H = quirk_holder
Also this

2021-02-17 22:16 UTC, SpaceVampire commented
Please do not add this.
It was poorly thought out and implemented on old base.
Either just roleplay it out, or put actual effort into coding it.
Instead of just giving people a really annoying trauma that fucks with stuff.
That people then ask to be removed, because that didn't understand what it was going to be.
Because you are really just supposed to get it cured.

2021-02-17 22:42 UTC, Guidesu commented
Gona work and makes the desc more descriptive and do the suggested kinds of stuff tomorrow

2021-02-26 14:01 UTC, Guidesu commented
Meh i dont wanna really work on this anyways.

2021-02-26 14:01 UTC, closed without merging