[Semi-Modular] Ports SEVA suit from oldbase.
Skyrat-SS13/Skyrat-TG pull request #3573
Opened 2021-02-22 00:11 UTC by Swiftfeather

## About The Pull Request

Nanotrasen's mining division would like to (re)introduce our latest and greatest product! The SEVA suit! With this excellent new suit miners will be able to mine for extended periods, never needing to worry about things of the past like ash storms! And if they are the clumsy type even being on fire won't hurt them! This is proven to decrease miner fatality rates due to burning and storms!

<img width="162" alt="5bca99c20d840b842d53f288c09fb28a" src="https://user-images.githubusercontent.com/26744576/108643335-c88fef00-746f-11eb-999e-838e6f5b3872.png">

- The miners now start with one additional voucher in their bag, a suit voucher, this voucher can be redeemed at mining vendors for just SEVA suits, for now. 

- The suits support digi, muzzled, and normal sprites.

- New vouchers are also purchasable from the mining vendor for 2,000 points.

- Please note that the SEVA suit cannot be upgraded with goliath plates, making it not ideal for combat. It is, however, very ideal for mining.

## Why It's Good For The Game

More mining suits is nice, also this sets the framework for additional suit voucher suits, perhaps even the explorer suit can be added so we always have them in stock for miners.

It also allows miners to mine the whole time! No storm can stop them!

## Changelog
:cl:
add: Added SEVA suit, purchasable with suit vouchers.
/:cl:

2021-02-22 00:15 UTC, GoldenAlpharex commented
I like this, but I also wonder how it's going to feel like.

2021-02-22 02:59 UTC, YakumoChen commented
> This suit is very much geared towards miners who are just mining, not those who are hunting.
It also allows miners to mine the whole time! No storm can stop them!

As someone who has spent nearly as much time as a Miner as they have in Security, I can DEFINITIVELY tell you that the SEVA suit is absolutely the _best_ suit for hunting if you know what you're doing. This in no way is a suit best suited for passive mining - it's the powergamer's choice.

SEVA's weaknesses (low armor, weakness to goliath grabs) mean extremely little. Good miners don't get caught, and don't take many hits. 

To compound this, the upside to SEVA is HUGE. It makes you fireproof, which makes the Drake mostly trivial to fight (being lit on fire is the biggest threat of Ash Drake), which in turn makes it extremely easy to get Drake Armor, and Drake Armor is more or less just a straight upgrade of SEVA.

2021-02-22 23:53 UTC, Gandalf2k15 requested changes
Redundant in cold environments, it'll do.

2021-02-22 23:53 UTC, Gandalf2k15 commented on modular_skyrat/modules/SEVA_suit/seva_obj.dm
> +	armor = list("melee" = 10, "bullet" = 10, "laser" = 10, "energy" = 10, "bomb" = 35, "bio" = 50, "rad" = 25, "fire" = 100, "acid" = 25, "wound" = 5)
```suggestion
	armor = list(MELEE = 10, BULLET = 10, LASER = 10, ENERGY = 10, BOMB = 35, BIO = 50, RAD = 25, FIRE= 100, ACID = 25, WOUND = 5)
```

2021-02-22 23:53 UTC, Gandalf2k15 commented on modular_skyrat/modules/SEVA_suit/seva_obj.dm
> +	armor = list("melee" = 15, "bullet" = 10, "laser" = 10, "energy" = 10, "bomb" = 35, "bio" = 50, "rad" = 25, "fire" = 100, "acid" = 25, "wound" = 5)
```suggestion
	armor = list(MELEE = 15, BULLET = 10, LASER = 10, ENERGY = 10, BOMB = 35, BIO = 50, RAD = 25, FIRE = 100, ACID = 25, WOUND = 5)
```

2021-02-22 23:53 UTC, Gandalf2k15 commented on modular_skyrat/modules/SEVA_suit/suit_voucher.dm
> +	var/items = list("SEVA suit" = image(icon = 'modular_skyrat/modules/SEVA_suit/icons/seva_suit.dmi', icon_state = "seva"))
Seems just a tad redundant for only having one suit. But it does mean we can add more in future I suppose.

2021-02-23 13:59 UTC, Gandalf2k15 approved these changes

2021-02-23 13:59 UTC, merged