Sepia/lightpink
Skyrat-SS13/Skyrat-TG pull request #3689
Opened 2021-02-27 03:36 UTC by Swiftfeather

## About The Pull Request

REMAKE OF https://github.com/Skyrat-SS13/Skyrat-tg/pull/3612

lightpink down to 25% speed buff from 50%, sepia speed buff down to 20% from 50%, wth a possible slowdown of 10%

I totally FUCKERED my last PR https://github.com/Skyrat-SS13/Skyrat-tg/pull/3612 of this, like, utterly annihilated it. All that's left is a smoldering crater. Don't go there.

- Lightpink speed buff reduced from 50% to 25%
- Sepia speedbuff reduced 50% to 20%
- Sepia, instead of doing nothing if it doesn't roll the speedbuff, now applies a 10% slowdown.

## Why It's Good For The Game

No lightspeed sec, or other people. 

## Changelog
:cl:
balance: Balanced stabilized Light pink and sepia extracts to not create lightspeed characters
/:cl:

2021-02-27 04:41 UTC, SpaceVampire commented
Shouldn't the max speed of Sepia be higher then the guaranteed speed that you get from pink? Otherwise it seems like its just strictly worse.

2021-02-27 04:47 UTC, RatFromTheJungle commented
> 
> 
> Shouldn't the max speed of Sepia be higher then the guaranteed speed that you get from pink? Otherwise it seems like its just strictly worse. You don't ever get the free healing chem on crit people thing. I would like to see you make it special in a way that wouldn't just make people Pick every single time over it, only maybe bothering if they wanted to stack em.

stacking them is the meta, sepia is rarely if ever used alone

2021-02-27 06:41 UTC, Swiftfeather commented
> Shouldn't the max speed of Sepia be higher then the guaranteed speed that you get from pink? Otherwise it seems like its just strictly worse. You don't ever get the free healing chem on crit people thing. I would like to see you make it special in a way that wouldn't just make people Pick every single time over it, only maybe bothering if they wanted to stack em.

The reason the max speed is still at that is that they can still be stacked, coming out to a pretty solid speed buff, still making it _worthwhile_ to do, just a bit more tricky.

2021-02-27 19:20 UTC, SpaceVampire commented
> The reason the max speed is still at that is that they can still be stacked, coming out to a pretty solid speed buff, still making it _worthwhile_ to do, just a bit more tricky.

I'm just saying that the Max-Speed for the Sepia should be higher then the speed of the Lightpink. Given that you won't have it active all of the time. I just don't want it to be strictly worse, like it is at the moment.

2021-02-28 02:19 UTC, Yawet330 requested changes
change title to [NONMODULAR]Sepia/Light Pink Speed Rebalance

2021-02-28 05:05 UTC, YakumoChen commented
> 
> 
> > The reason the max speed is still at that is that they can still be stacked, coming out to a pretty solid speed buff, still making it _worthwhile_ to do, just a bit more tricky.
> 
> I'm just saying that the Max-Speed for the Sepia should be higher then the speed of the Lightpink. Given that you won't have it active all of the time. I just don't want it to be strictly worse, like it is at the moment.

That's exactly what I pointed out in the last PR. There's no reason to use Sepia by itself since regardless of how it's used it's always strictly worse than light pink.

I still think you should just remove light pink's speed boost and give it some other buff, like stamina regen.

2021-02-28 05:07 UTC, YakumoChen commented
If nothing else, switch the lightpink buff to 10 or 20% and the Sepia buff to 25%

2021-03-01 18:13 UTC, Gandalf2k15 commented
I'm happy with this after checking it over. We need to do SOMETHING about them. If this invalidates sepias then we can change them again.

2021-03-01 18:14 UTC, Gandalf2k15 approved these changes

2021-03-01 18:14 UTC, merged