[MODULAR] CQC+ Changes and fixed chokehold
Skyrat-SS13/Skyrat-TG pull request #3944
Opened 2021-03-06 22:19 UTC by SarmentiCampbell

## About The Pull Request
Instead of deflecting bullets with your bare fists, You will now avoid them but you will have a chance to still get hit by it.  The CQC+ can't be discounted and the cost has been increased. You can now use chokehold while restraining someone, at the cost of being unable to suplex.

## Why It's Good For The Game
Somewhat deal with #3621 and nerf the CQC+ a bit seeing as peoples were complaining about it being too overpowered.

## Changelog
:cl:
balance: CQC+ Users will now avoid projectiles rather than deflect them, They will also have a chance to be hit by a projectile despite being on throw mode.
fix: fixed CQC Chokehold, You won't be able to use suplex if you know how to use CQC.
/:cl:

2021-03-06 23:30 UTC, SpaceVampire commented
I don't like making it RNG based honestly.
I feel like it should be 100%, because otherwise you can't plan around using it.
Having it be liked to throw-mode means you can already toggle it just by tossing stuff at em.
Along with it only really being able to be used defensively.
I feel like making it cost more is already enough of a nerf.

2021-03-07 00:15 UTC, Gandalf2k15 approved these changes

2021-03-07 00:16 UTC, Gandalf2k15 commented
Actually, can you remove the other balance changes and just leave in the chokehold fix?

2021-03-07 00:16 UTC, Gandalf2k15 requested changes
Actually, can you remove the other balance changes and just leave in the chokehold fix?

2021-03-07 00:40 UTC, merged