GUBMAN 2 & 2.5 REVISITED: REMASTERED HD
Skyrat-SS13/Skyrat-TG pull request #4267
Opened 2021-03-20 02:42 UTC by Investigator77

## About The Pull Request

This PR revisits aspects of Gubman 2 and Gubman 2.5.

## Why It's Good For The Game

Sprite updates, less useless stuff in code.

## Changelog
:cl:
imageadd: Sniper rifle sprite resolution changed to 48x32 from 40x32
tweak: Hardlight scopes were deemed too expensive to produce. Sniper rifles are once again fit with common optics. Some may still have electronic assistance...
tweak: All old sniper rifle models were phased out of the market. New designs will be used, regardless of manufacturer.
tweak: Super & Hyper kinetic accelerators have custom shapes instead of being recolors.
imageadd: MCRS-5B and ARG-63 have been re-sprited.
imageadd: AUS-107, SA-107 and Caracal AMR have been re-sprited.
/:cl:

2021-03-20 02:45 UTC, Investigator77 commented
Conflict fixed. Das Rite!

2021-03-20 02:55 UTC, Investigator77 commented
fuck

2021-03-20 03:41 UTC, Investigator77 commented
**AAAAAAAAAAGH STUPID FUCKING MONKEY!!!!!!!**

2021-03-20 04:23 UTC, Investigator77 commented
i'M THE GREATEST PROGRAMMER THAT HAS EVER LIVED.
![imagen](https://user-images.githubusercontent.com/51841793/111858836-c90a9100-891a-11eb-83c9-f8cf517a77b6.png)

2021-03-21 14:59 UTC, Gandalf2k15 requested changes

2021-03-21 14:59 UTC, Gandalf2k15 commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +/obj/item/borg/upgrade/modkit/chassis_mod/orange                   /////ICON OVERRIDE IN modular_skyrat/modules/aesthetics/guns/icons/energy.dmi
```suggestion
/obj/item/borg/upgrade/modkit/chassis_mod/orange /////ICON OVERRIDE IN modular_skyrat/modules/aesthetics/guns/icons/energy.dmi
```

2021-03-21 14:59 UTC, Gandalf2k15 commented on code/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +/obj/item/borg/upgrade/modkit/chassis_mod                   /////ICON OVERRIDE IN modular_skyrat/modules/aesthetics/guns/icons/energy.dmi
```suggestion
/obj/item/borg/upgrade/modkit/chassis_mod /////ICON OVERRIDE IN modular_skyrat/modules/aesthetics/guns/icons/energy.dmi
```

2021-03-21 15:20 UTC, Investigator77 commented
See Gandalf you broke it

2021-03-21 15:21 UTC, Gandalf2k15 commented
FIX IT

2021-03-21 15:28 UTC, Investigator77 commented
YOU COULD'VE MERGED THIS BEFORE FUCKING BREAKING IT IT'S FULL AUTO'S FAULT, YOU FIX IT

2021-03-21 15:55 UTC, Gandalf2k15 approved these changes

2021-03-21 15:55 UTC, merged