[WIP] Replaces security batons with breaching hammers
Skyrat-SS13/Skyrat-TG pull request #4492
Opened 2021-03-28 21:33 UTC by MLGTASTICa

## About The Pull Request
Replaces unoriginal and unfunny baton with a far interesting tool
Still got to add sprites and fix a runtime.
## Why It's Good For The Game
1.Lets security coordinate to breach doors , lets them cuck door spam.
2.Removes knockdown from batons , but provides a viable combat option when used in numbers , but not alone against CQC,  Martial arts , e-sword , etc.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-03-28 21:36 UTC, dominuslucian commented
good fucking meme

2021-03-29 07:59 UTC, softcerv commented
I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.

2021-03-29 08:05 UTC, MLGTASTICa commented
> I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.

Security is expected to only use these when needed, and well , if they needlessly break doors , the HOS can and should punish them , so can sergeants. It also needs 2 people to do it .

2021-03-29 09:46 UTC, softcerv commented
> 
> 
> > I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.
> 
> Security is expected to only use these when needed, and well , if they needlessly break doors , the HOS can and should punish them , so can sergeants. It also needs 2 people to do it .

Letting sec bulldoze through departmental doors sounds incredibly painful for both antags and whoever is working in a department. Maybe the door breaching function could be treated the same way as lethals or it might require HoS/Captain permission.  Having some way to check what officers used the tool or another other form of accountability would help a lot.

2021-03-29 09:55 UTC, MLGTASTICa commented
> > > I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.
> > 
> > 
> > Security is expected to only use these when needed, and well , if they needlessly break doors , the HOS can and should punish them , so can sergeants. It also needs 2 people to do it .
> 
> Letting sec bulldoze through departmental doors sounds incredibly painful for both antags and whoever is working in a department. Maybe the door breaching function could be treated the same way as lethals or it might require HoS/Captain permission. Having some way to check what officers used the tool or another other form of accountability would help a lot.



> > > I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.
> > 
> > 
> > Security is expected to only use these when needed, and well , if they needlessly break doors , the HOS can and should punish them , so can sergeants. It also needs 2 people to do it .
> 
> Letting sec bulldoze through departmental doors sounds incredibly painful for both antags and whoever is working in a department. Maybe the door breaching function could be treated the same way as lethals or it might require HoS/Captain permission. Having some way to check what officers used the tool or another other form of accountability would help a lot.

Witnesses exist.

2021-03-29 10:20 UTC, softcerv commented
> 
> 
> > > > I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.
> > > 
> > > 
> > > Security is expected to only use these when needed, and well , if they needlessly break doors , the HOS can and should punish them , so can sergeants. It also needs 2 people to do it .
> > 
> > 
> > Letting sec bulldoze through departmental doors sounds incredibly painful for both antags and whoever is working in a department. Maybe the door breaching function could be treated the same way as lethals or it might require HoS/Captain permission. Having some way to check what officers used the tool or another other form of accountability would help a lot.
> 
> Witnesses exist.

Yes, they do, but they aren't always present or willing to talk. Even having something minor, like metal debris on the hammer to show that it was used to breach, would go a long way.

2021-03-29 10:32 UTC, MLGTASTICa commented
> > > > > I think that they could be neat as like a late round research locked weapon, but I feel that giving sec officers a tool to destroy doors as part of their standard kit could create a massive headache for engineering staff along with other potential issues.
> > > > 
> > > > 
> > > > Security is expected to only use these when needed, and well , if they needlessly break doors , the HOS can and should punish them , so can sergeants. It also needs 2 people to do it .
> > > 
> > > 
> > > Letting sec bulldoze through departmental doors sounds incredibly painful for both antags and whoever is working in a department. Maybe the door breaching function could be treated the same way as lethals or it might require HoS/Captain permission. Having some way to check what officers used the tool or another other form of accountability would help a lot.
> > 
> > 
> > Witnesses exist.
> 
> Yes, they do, but they aren't always present or willing to talk. Even having something minor, like metal debris on the hammer to show that it was used to breach, would go a long way.

That a IC issue , im not going to add hard evidence for somehing that theres already plenty for. If you want this done do another PR that adds onto this if this gets merged.

2021-03-30 06:08 UTC, YakumoChen commented
This makes it useless for security to apprehend people in melee. What are they supposed to do, spam flash people? Riddle them with rubber bullets? This creates far more problems than it solves (and fabricates a problem that doesn't need a solution)

2021-03-30 06:11 UTC, MLGTASTICa commented
> This makes it useless for security to apprehend people in melee. What are they supposed to do, spam flash people? Riddle them with rubber bullets? This creates far more problems than it solves (and fabricates a problem that doesn't need a solution)
> 
> blockchance on a standard issue weapon is incredibly cringe by the way, especially since it stacks with riot shields.

Riot shields will break. Also yes you should be using rubbers, pepper , shoves and flashes to appherend people , not just spamming a baton and insta winning.

2021-03-30 06:13 UTC, YakumoChen commented
Literally all of those things you just listed can be completely mitigated with a gas mask and sunglasses.

Shoving doesn't actually do anything on Skyrat other than annoy people.

2021-03-30 06:15 UTC, MLGTASTICa commented
> Literally all of those things you just listed can be completely mitigated with a gas mask and sunglasses.
> 
> Shoving doesn't actually do anything on Skyrat other than annoy people.

Shoving hardstuns them for 6 seconds if they are on the ground. Also the hammer will stamcrit someone in 3 hits.

2021-03-30 06:17 UTC, YakumoChen commented
I have literally never seen a shove stun work on Skyrat. Shove fights are endless.

15 seconds to hardstun a single person is frankly absurd. You're making the only option for security to even do their most basic job of arresting people for non-antag crimes an absurd chore or forcing them to just shoot everyone with rubbers (which will cause extreme problems with the crew)

2021-03-30 06:19 UTC, MLGTASTICa commented
> I have literally never seen a shove stun work on Skyrat. Shove fights are endless.
> 
> 15 seconds to hardstun a single person is frankly absurd. You're making the only option for security to even do their most basic job of arresting people for non-antag crimes an absurd chore or forcing them to just shoot everyone with rubbers (which will cause extreme problems with the crew)

You get an absurb amount of spare ammo anyway , i don't really see an issue with that.

2021-03-30 06:19 UTC, YakumoChen commented
This also more or less fucks over half the reason to use CQC, which specifically has a special interaction with security batons.

2021-03-30 06:22 UTC, MLGTASTICa commented
> This also more or less fucks over half the reason to use CQC, which specifically has a special interaction with security batons.

CQC has its special interaction with all melee weapons , it also does the opposite , trying to solo a CQC user with a hammer is going to severely hamper the officer , unless the antag is very incapable.

2021-03-30 06:25 UTC, YakumoChen commented
These damage values are insane. 15 force? _35_ throw force?

We only _just_ got rid of the forced brute damage on batons and now you want to replace them with something worse that forces "less than lethal security" again.

2021-04-02 17:09 UTC, KathrinBailey commented on modular_skyrat/modules/sec_haul/code/peacekeeper/peacekeeper_hammer.dm
> +	attack_verb_simple = list("breache","hammer","whack","slap","thwach","fling")
```suggestion
	attack_verb_simple = list("breach","hammer","whack","slap","thwach","fling")
```

2021-04-02 17:17 UTC, KathrinBailey requested changes
1. Your branch is hecked. Check files changed.
2. I'm fine with this existing but I'd rather you keep this in the armoury and not given to every officer. Up to three in the armoury is fine.
3. Please post a video of the breaching or post a .gif of it. Kinda need to see how this performs in-game.
4. Lower block chance significantly and make bullets not be blocked at all, or just have 2% block chance or something.
5. Consider making this something you wield as a requirement to smash the doors, it'll also make having high stamina damage okay if you are required to wield the hammer to use it effectively. Wielded can have higher block chance for melee attacks, considering you're holding a bar in front of you with two hands, as opposed to limply holding a huge hammer with one hand.

Overall very good PR, just needs tweaking.

2021-04-03 02:27 UTC, Gandalf2k15 commented
Given that you've put effort into this, let's give it a TM, make sure you actually replace the batongs.

2021-04-03 02:28 UTC, Gandalf2k15 commented on code/modules/unit_tests/rcd.dm
> +	TEST_ASSERT_EQUAL(frame_count, 1, "Expected no density machine deconstruction frame stacking test to end up with exactly 1 machine frame.")
why

2021-04-03 07:05 UTC, MLGTASTICa commented
> 1. Your branch is hecked. Check files changed.
> 2. I'm fine with this existing but I'd rather you keep this in the armoury and not given to every officer. Up to three in the armoury is fine.
> 3. Please post a video of the breaching or post a .gif of it. Kinda need to see how this performs in-game.
> 4. Lower block chance significantly and make bullets not be blocked at all, or just have 2% block chance or something.
> 5. Consider making this something you wield as a requirement to smash the doors, it'll also make having high stamina damage okay if you are required to wield the hammer to use it effectively. Wielded can have higher block chance for melee attacks, considering you're holding a bar in front of you with two hands, as opposed to limply holding a huge hammer with one hand.
> 
> Overall very good PR, just needs tweaking.

Fixed the random file changes , gandalf said later to make sure to actually replace batongs so im confused on  the armoury. Video is here https://youtu.be/b3JdXguov_M ,  lowered block chance from 45% to 25% , 15%  > 5% . As for the last part , i'd actually add wielding for all items in another PR and apply it to the hammer later.

2021-04-03 07:06 UTC, MLGTASTICa commented on code/modules/unit_tests/rcd.dm
> +	TEST_ASSERT_EQUAL(frame_count, 1, "Expected no density machine deconstruction frame stacking test to end up with exactly 1 machine frame.")
No idea why but i fixed it.

2021-04-03 18:55 UTC, PCPort commented
> I have literally never seen a shove stun work on Skyrat. Shove fights are endless.
> 
> 15 seconds to hardstun a single person is frankly absurd. You're making the only option for security to even do their most basic job of arresting people for non-antag crimes an absurd chore or forcing them to just shoot everyone with rubbers (which will cause extreme problems with the crew)

As someone who has shovestunned many, *many* people on this server, I can attest that they do work.

2021-04-04 04:07 UTC, Ironnhawk commented
This is something that should be in the armory, not standard issue.

2021-04-04 15:09 UTC, Gandalf2k15 commented
Fix the code issues and github issues eeeee

2021-04-04 15:28 UTC, Mithrun commented
If this was in the armory as on optional tool, less of a weapon, this would be great. i'd love this. 

But as a weapon? especially as a main weapon? i really don't like this idea. 
First off, just imagining security officers swinging those big things around is pretty funny and ridiculous, makes me think of monster hunter, really.
On top of that, i think the nightstick is actually in a pretty good spot now, having the option to upgrade to a stunprod later on (though if it were me, i'd lock that behind research or have the upgrades in the armory). 

Overall, good idea but.. rough around the edges?

2021-04-05 14:24 UTC, Gandalf2k15 commented
After trialing this, it's best if these go in the armory, leave the officers with the normal batons.

2021-04-05 15:46 UTC, MLGTASTICa commented
> After trialing this, it's best if these go in the armory, leave the officers with the normal batons.

This was originally meant to get rid of batons because they force knockdown , but eh , whatever.

2021-04-06 10:49 UTC, Gandalf2k15 commented
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695

2021-04-06 10:50 UTC, Gandalf2k15 commented
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695

2021-04-10 17:37 UTC, Gandalf2k15 commented on html/changelog.html
> +
```suggestion
```

2021-04-10 17:37 UTC, Gandalf2k15 commented on html/changelog.html
> +
```suggestion
```

2021-04-10 17:37 UTC, Gandalf2k15 commented on code/modules/unit_tests/rcd.dm
> +
```suggestion
```

2021-04-10 17:38 UTC, Gandalf2k15 commented on code/modules/unit_tests/rcd.dm
> +
```suggestion
```

2021-04-10 17:44 UTC, merged