[NONMODULAR] Nanotrasen News Bulletin: Paramedic pay increased. Paramedics rejoice!
Skyrat-SS13/Skyrat-TG pull request #4905
Opened 2021-04-14 17:55 UTC by Swiftfeather

## About The Pull Request

Increases pay class for paramedics from medium to hard, so paycheck is changed from 75 to 100 cr, meaning they'll also start with 175 more credits at shift start, allowing them to purchase one expensive item out of the med vendor, and not have to ask the CMO or a doctor for a chip in.

## Why It's Good For The Game

Almost every shift I play paramed I ask the CMO or a doctor for a bit of money so I can purchase the better crew pinpointer or an advanced kit, and I see other paramedics do the same thing. We might as well give them the ability to purchase it themselves since to get them you just have to wait for your paychecks to roll in and that's no fun.

## Changelog
:cl:
qol: Paramedics have gotten a raise!
/:cl:

2021-04-14 18:03 UTC, tf-4 commented
Not sure how I feel about them getting that stuff round start. May as well just put it in their inventory if that's the case.

2021-04-14 18:11 UTC, Swiftfeather commented
> Not sure how I feel about them getting that stuff round start. May as well just put it in their inventory if that's the case.

I did it this way because I think it's better if they have to choose between the advanced medkit or the good crew pinpointer or a bunch of misc med supplies, and with this change the CMO/doctors on site shouldn't have to chip in to equip the paramedics. Also half the shifts I take paramed I end up having to do surgeries and shit anyway which makes me basically a doctor-lite. Also parameds are expected to go to lavaland or space walks to get people, may as well give them hazard pay since it's often dangerous to go collect dead bodies.

2021-04-14 20:25 UTC, KathrinBailey requested changes
This would be inconsistent, as the rest of medical will receive medium paychecks.
![image](https://user-images.githubusercontent.com/53862927/114773763-5b118800-9d67-11eb-85d0-3c93576a4861.png)
![image](https://user-images.githubusercontent.com/53862927/114773833-7086b200-9d67-11eb-8a1e-4ff9b5d534dc.png)
![image](https://user-images.githubusercontent.com/53862927/114773945-92803480-9d67-11eb-8de0-d6ea6520f07d.png)
```
//Experimental change: These are subject to tweaking based on the /tg/ economy overhaul.
//Current design direction: Higher paying jobs are vastly outnumbered by lower paying jobs, so anything above medium hurts inflation, common jobs help inflation
#define PAYCHECK_PRISONER 25
#define PAYCHECK_ASSISTANT 50
#define PAYCHECK_MINIMAL 55
#define PAYCHECK_EASY 60
#define PAYCHECK_MEDIUM 75
#define PAYCHECK_HARD 100
#define PAYCHECK_COMMAND 200
```

Here's the value of the defines.
Please up all of medical to have hard paychecks for consistently. This isn't saying that this will grant you approval though, I'm unsure on if this is good or not, or the issue you're having that you're trying to remedy with this PR can be solved in another way.

2021-04-14 20:53 UTC, Gandalf2k15 commented
Honestly we need to change those defines so people actually get money

2021-04-14 21:29 UTC, Swiftfeather commented
> Honestly we need to change those defines so people actually get money

I'll look into it when I get home, then. Hopefully we add more (useful) things to purchase. I've been looking into increasing the numbers of items in vendors to better suit our pop as well. That comes later

2021-04-15 02:26 UTC, GoldenAlpharex commented
> Honestly we need to change those defines so people actually get money

You're right, heads deserve more money, assistants get too much. :^)

In all seriousness, we probably should just remove the fact that shit gets pulled out of the departmental funds, at least for Assistants, because the Service funds are always at 0 due to the insane amount of people there is in Service.

2021-04-15 02:29 UTC, GoldenAlpharex commented
Oh, and, uh, we should fix the pay for the Blueshield, while we're at it.

2021-04-16 00:11 UTC, SpaceVampire commented
I really don't think people need more money for doing nothing at all. If you want cash, there are already systems you can interact with to get it. The current paychecks are fine imo. This makes bribes less of a thing.

2021-04-16 01:50 UTC, Owai-Seek commented
I don't think this is strictly necessary, considering how stupid crazy easy medical bounties are.

2021-04-16 12:02 UTC, Gandalf2k15 approved these changes

2021-04-16 12:03 UTC, merged

2021-04-17 12:48 UTC, hugmeorelse commented
@Owai-Seek Please see the announcement I made. I am not going to touch any comments made before the announcements here, though I don't see as much of an issue with them so to speak anyhow.

2021-04-20 01:11 UTC, ChungusGamer666 commented
i love free money for absolutely no effort this is great for the economy more stimulus checks please