[Semi-Modular?] More narcotics
Skyrat-SS13/Skyrat-TG pull request #4943
Opened 2021-04-16 01:17 UTC by linnpap

## About The Pull Request
Hey, the Big Man's back! W W W, dot, the kid from Brooklyn, dot com.
![image](https://user-images.githubusercontent.com/77863456/114957381-87d8a480-9e26-11eb-8b58-33d68e7d57e0.png)

## Why It's Good For The Game
Because the Big Man said so.

## Changelog
:cl:
add: Added quaaludes
add: Added cocaine
add: Added crack cocaine, along with crack pipes
/:cl:

2021-04-16 01:20 UTC, tf-4 commented
The big man would walk twenny miles for a QUAALUDE lemme tell ya

2021-04-16 01:21 UTC, Yawet330 commented
`file ./modular_skyrat/modules/morenarcotics/chemistry/reagents/cocaine.dm is missing a trailing newline
file ./modular_skyrat/modules/morenarcotics/chemistry/reagents/quaalude.dm is missing a trailing newline
file ./modular_skyrat/modules/morenarcotics/chemistry/recipes/quaalude.dm is missing a trailing newline
file ./modular_skyrat/modules/morenarcotics/items/crackpipe.dm is missing a trailing newline`


Add newlines and this should be good.

2021-04-16 01:23 UTC, linnpap commented
> 
> 
> The big man would walk twenny miles for a QUAALUDE lemme tell ya

BRING BACK THE FUCKING QUAALUUUDEEEESSSS

2021-04-16 01:29 UTC, Investigator77 commented
Add heroin from Opium and make it black tar heroin if you get it low purity, no balls

2021-04-16 01:39 UTC, Snakebittenn commented
Humble (actual) suggestion, but please give crack bricks export value (maybe if you hack the console like how you can export organs?) I'd like to see some cartel RP or something.

2021-04-16 01:42 UTC, gummardgumphrey commented
THE FUCKIN' LUUDES

2021-04-16 01:47 UTC, Sababall commented
Will we be able to check out how pure the cocaine is by putting it on our tongues?

2021-04-16 02:05 UTC, Snakebittenn commented
'If you eat harvested coca it should reduce drowsiness.'

2021-04-16 02:18 UTC, linnpap commented
i think that somebody is going to die

2021-04-16 02:30 UTC, linnpap commented
should be ready to be test merged, ill probably start working on heroin tomorrow

2021-04-16 02:38 UTC, Gandalf2k15 requested changes

2021-04-16 02:38 UTC, Gandalf2k15 commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	M.drowsyness += 2 * REM * normalise_creation_purity() * delta_time
Modular comments

2021-04-16 14:22 UTC, Gandalf2k15 approved these changes

2021-04-17 01:28 UTC, hugmeorelse commented
Friendly reminder to stay on topic. The Github is for technical analysis and code review. A joke here and there is fine, as long as it's good natured.

2021-04-17 06:11 UTC, thestubborn commented
jessie where is the cocainer

2021-04-17 12:55 UTC, tf-4 commented on modular_skyrat/modules/morenarcotics/chemistry/reagents/cocaine.dm
> +/datum/reagent/drug/cocaine/on_mob_metabolize(mob/living/L)
Use actual variable names, not random letters

2021-04-18 21:52 UTC, Gandalf2k15 commented
Once this is ready for merge, tell me

2021-04-18 23:27 UTC, linnpap commented
> 
> 
> Once this is ready for merge, tell me

honestly i think it should be ready to be merged now

2021-04-19 00:00 UTC, linnpap commented
actually hold up export values are fucked

2021-04-19 02:52 UTC, merged