Readd Death Ripley's clamps for scott only.
Skyrat-SS13/Skyrat-TG pull request #5031
Opened 2021-04-20 01:35 UTC by SarmentiCampbell

## About The Pull Request
Scott has a tendency to try and kill himself, with this pr, we can finally pacify him by rendering him harmless

## Why It's Good For The Game
It's hrp, trust me

## Changelog
:cl:
/:cl:

2021-04-20 01:56 UTC, tf-4 commented on code/modules/vehicles/mecha/equipment/tools/work_tools.dm
> +		else if(LAZYACCESS(modifiers, RIGHT_CLICK) && iscarbon(M) && M.real_name == "Scott Waverly")//meme clamp here //SKYRAT EDIT - Original : else if(LAZYACCESS(modifiers, RIGHT_CLICK) && iscarbon(M))
downvoted

2021-04-20 01:56 UTC, tf-4 requested changes
bad change

2021-04-20 02:10 UTC, RatFromTheJungle approved these changes
LGTM

2021-04-20 05:52 UTC, SarmentiCampbell commented on code/modules/vehicles/mecha/equipment/tools/work_tools.dm
> +		else if(LAZYACCESS(modifiers, RIGHT_CLICK) && iscarbon(M) && M.real_name == "Scott Waverly")//meme clamp here //SKYRAT EDIT - Original : else if(LAZYACCESS(modifiers, RIGHT_CLICK) && iscarbon(M))
:)

2021-04-20 09:58 UTC, NotRanged commented
Good PR

2021-04-21 18:21 UTC, Gandalf2k15 commented
no memes ngtm

2021-04-21 18:22 UTC, closed without merging