Makes mold a random event + changes how spacevines spawn.
Skyrat-SS13/Skyrat-TG pull request #5277
Opened 2021-04-28 02:03 UTC by Gandalf2k15

## About The Pull Request

This basically makes it so that a random event can occur which will spawn up to 3 molds at random locations.

Mold has also received a buff so that it's actually a threat.

Spacevines now spawn in maintenance instead of the fucking central hallways and will be spawned with two maneaters.

## Changelog
:cl:
add: Mold is now a random event.
balance: Spacevines have been rebalanced.
/:cl:

2021-05-03 03:07 UTC, Cheshify commented
So, in my personal experience with these space vines, they grow far too rapidly, the monsters they spawn are too plentiful (15+ of them zerging into crowds of people). The damage the monsters do downs people in 1/2 hits, and since stamina damage has this insane slow attached, there's basically no way a station of people can handle the insane greentide, as well as fight off all the ridiculously-fast growing vines that have way too much health (using a full welder to clear a few randomly spawned vines?). 

Right now, this is basically a round-ending event in proportion to the Crystal Invasion, but at least everyone on station is aware of the massive yellow skeletons before they steamroll your department. This would fit well on tg's LRP servers, but not a HRP server where people aren't expected to powergame and be constantly armed to kill space vines that hit harder than a desword.

2021-05-03 03:27 UTC, Seris02 commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +	sight = SEE_SELF|SEE_MOBS|SEE_OBJS|SEE_TURFS // SKYRAT EDIT ADDITION
why is this here when it's already there on line 121

2021-05-03 03:33 UTC, Gandalf2k15 commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +	sight = SEE_SELF|SEE_MOBS|SEE_OBJS|SEE_TURFS // SKYRAT EDIT ADDITION
```suggestion
```

2021-05-03 03:44 UTC, EverothB commented
Hi, just my personal experience with this plants. So as a normal scientist with no gear but bothany gear to deal against them this was my experience. 
I reached to try and get 1 guy out of 3 plants biting someone. 1 hit me, and i was down stamcrit, unable to do anything and constantly being eaten by then once i was defenseless. 1 hit, down and dead. And i was not even fighting or with the combat hud on at full life and good stam. 
I went back trying to help get bodies, but i cant, the range on the vine toss is too big and they just hide over with the glass, we have no gear. The plants killed all sec, all the crew, all the mechs, all the borgs and all the ert. I try to use plant begone, nothing works, use a scyte, does not matter, they hit or drop you down with a vine, and its over, they gang up on you and toss you into the snow or space. How is that not abusing from meta knowledge? They are dragging the bodies away into unreachable space, and no one was able to reach them. (Not sure if this was ok, since this seem way off rping as an antag and seems clearly meta)
So plants, win, they are unkillable with all that much life steal, they instantly heal when they go into vines, and are so strong 1 hit downs you and killed all sec, any ert, people of the strongest mecs, crew just passing by, and the borgs.

2021-05-03 03:48 UTC, Swiftfeather requested changes
A few changes, I'm a couple drinks past beer-o-clock so I probably missed some stuff

2021-05-03 03:48 UTC, Swiftfeather commented on modular_skyrat/master_files/code/modules/events/spacevine.dm
> +	if(istype(AM, /mob/living/simple_animal/hostile/venus_human_trap)) //skyrat change: vines heal flytraps 10% on cross
This isn't needed, they heal when attacking living people. This just lets them fullheal then go back and fight some more, and makes them far more difficult to kill when they are already not an easy target.

2021-05-03 03:48 UTC, Swiftfeather commented on modular_skyrat/master_files/code/modules/events/spacevine.dm
> +/datum/spacevine_controller/proc/VineDestroyed(obj/structure/spacevine/S)
#3355

2021-05-03 03:48 UTC, Swiftfeather commented on modular_skyrat/master_files/code/modules/events/spacevine.dm
> +/obj/structure/spacevine/proc/entangle(mob/living/V)
#3355

2021-05-03 03:48 UTC, Swiftfeather commented on modular_skyrat/master_files/code/modules/events/spacevine.dm
> +/proc/isvineimmune(atom/A)
#3355

2021-05-03 03:48 UTC, Swiftfeather commented on modular_skyrat/master_files/code/modules/events/spacevine.dm
> +/obj/structure/spacevine/proc/on_chem_effect(datum/reagent/R)
#3355

2021-05-03 03:48 UTC, Swiftfeather commented on modular_skyrat/master_files/code/modules/events/spacevine.dm
> +/datum/spacevine_mutation/aggressive_spread/aggrospread_act(obj/structure/spacevine/S, mob/living/M)
#3355

2021-05-03 22:11 UTC, Gandalf2k15 commented
Maneaters have been rebalanced and oil mold no longer spawns plasma.

2021-05-04 02:53 UTC, merged

2021-05-05 11:54 UTC, Low3 commented
Is it possible to move man eater spawns and mold chance/cores amount to config? They are kinda too epic and tend to kill off rounds 1 hour in.