[DNM] Adds an new Race which is a Organic Synthetic Person. STILL NEED TESTING ON MY PART.
Skyrat-SS13/Skyrat-TG pull request #5539
Opened 2021-05-08 00:30 UTC by Guidesu

## About The Pull Request
This adds a new race which is a mix of organic/synthetic.
They can be affected by chems/EMPs/IONs, suffer wounds and bleed.
But can be easily revived by vial field repair plus using sutures and mesh.
There's a lot of good things and bad things on this "new" species.

## Why It's Good For The Game
More customization plus race is always good.

## Changelog
:cl:
add: Added a new species which is an Mixed of Synthetic And Organic
/:cl:

2021-05-08 01:01 UTC, Stalkeros2 commented
What the fuck.
No like really what.
Uh.

2021-05-08 01:03 UTC, Guidesu commented
> What the fuck.
> No like really what.
> Uh.

Funny.

To clarify: Talking about balance on the Github in a purely objective way counts as technical analysis. Furthermore, if the person behind the PR invites discussion, it is fine as long as it does not fall into a series of comments mimicking an editorial. Keep it clean, technical, and objective.

Please refrain from using Github as an editorial. It is not meant for expressing your opinion on gameplay. Unless it is for code review or technical analysis, please refrain from commenting, as we have seen multitudes of people abusing the Github and creating unncessary drama and hate against other players, not to mention it makes it harder to find relevant comments that are pertinent to what Github is for. In fact, please be aware that people outside of our community often participate in the comments to drive a wedge between players. Not everyone has good intentions.

2021-05-08 01:04 UTC, Guidesu commented
> What the fuck.
> No like really what.
> Uh.

So or your shut up or you suggest something useful.
If not go to discord dumbass i am not into your bullshit.

2021-05-08 16:45 UTC, Guidesu commented
Bleh this sound annoying i will just make synth antro to be able to pick organs and use this PR to adds new organs

2021-05-14 23:23 UTC, Guidesu commented
> Would you mind actually filling out the fields for the PR so we know what this is?
Yes my laziness mind

2021-05-16 20:08 UTC, YakumoChen commented
Extreme no from me.

Combat advantage quirks are _explicitly_ disallowed by the system, powergaming is the only result from adding the positive quirks.

2021-05-16 20:10 UTC, Guidesu commented
> Extreme no from me.
> 
> Combat advantage quirks are _explicitly_ disallowed by the system, powergaming is the only result from adding the positive quirks.

Explain how resisting more in crit is powergaming my friend

2021-05-16 20:10 UTC, Guidesu commented
Powergaming in SS13 is basically trying to get power in the forms of weapons, gear, items and access over all else including RP(if applicable) and the enjoyment of others(always applicable). What's considered powergaming can vary from server to server but is generally more frowned upon the higher the

2021-05-16 20:13 UTC, Guidesu commented
Powergaming is defined as: going out of your way to give yourself an extreme mechanical edge over the rest of the crew. Do not give yourself all-access, a combat hardsuit, several laser weapons, and a squad of E-Magged borgs when facing off against a skeleton crew as Traitor. This goes against the aims and goals of the server which is to provide a roleplaying environment where action and conflict is plentiful.

2021-05-16 20:13 UTC, Guidesu commented
Did you even saw Skyrat rules about power gaming?

2021-05-16 20:15 UTC, Guidesu commented
**_holy macaroni please read the rules before talking with me about powergaming. _**

2021-05-16 20:17 UTC, YakumoChen commented
Yea
Powergaming with quirks is not allowed. The system is not designed for quirks that give (mostly invisible to other players) combat advantages

Furthermore some of these traits are covered by the Skillchip system and should not overlap

2021-05-16 20:19 UTC, Guidesu commented
> Yea
> Powergaming with quirks is not allowed. The system is not designed for quirks that give (mostly invisible to other players) combat advantages
> 
> Furthermore some of these traits are covered by the Skillchip system and should not overlap

wtf are you even talking.
Did you saw what POWERGAMING MEANS??

2021-05-16 20:21 UTC, YakumoChen commented
Yes. Players will simply take quirks that give minor disadvantages to take the quirks with the best possible advantages. 

Positive quirks should only be flavor or minor, non-combat benefits.

Negative quirks are disadvantages of any kind because they're designed to be taken as a challenge

2021-05-16 20:21 UTC, Guidesu commented
> Yes. Players will simply take quirks that give minor disadvantages to take the quirks with the best possible advantages.
> 
> Positive quirks should only be flavor or minor, non-combat benefits.
> 
> Negative quirks are disadvantages of any kind because they're designed to be taken as a challenge

e

2021-05-16 20:27 UTC, Guidesu commented
I kinda knew it someone would talk about power gaming and shit.
So I don't care I will wait for an maintainer official word

2021-05-16 21:30 UTC, hugmeorelse commented
This conversation is closed due to toxicity from multiple parties. Punishments will be dished out.

2021-05-20 22:38 UTC, Funce requested changes
You've got an extra file `organs` for some reason. Easy to miss.

Some of these descriptions need to be checked over for grammar, get someone to help you with that. 

Otherwise, code's fine, excepting the below issues. It's just balance here that needs to be checked. @hugmeorelse

2021-05-20 22:38 UTC, Funce commented on code/modules/mob/living/blood.dm
> +//skyrat edit - hemophilia quirk
Indent your comment

2021-05-20 22:38 UTC, Funce commented on code/__DEFINES/traits.dm
> +//skyrat_traits
Skyrat traits go in file `code\__DEFINES\~skyrat_defines\traits.dm`

2021-05-23 03:27 UTC, Gandalf2k15 commented
Hello. Please address the issues with this PR and consider reopening later.

2021-05-23 03:27 UTC, closed without merging