[MODULAR] Supermatter Surge Event.
Skyrat-SS13/Skyrat-TG pull request #5862
Opened 2021-05-22 14:06 UTC by SpaceVampire

## About The Pull Request

Ports Citadel-Station-13/Citadel-Station-13#14307, all credit to them. I just saw it, and thought it was neat.
Adds an event that makes the supermatter power up a good deal for a short time. That's it. Only happens if there is a supermatter and it has been turned on, otherwise it won't try.

## Why It's Good For The Game

Fun stress-test for the Supermatter, gives engineering some stuff to do.
It seemed fairly mild during my local testing of it, can always tweak numbers if needed.

## Changelog
:cl:
add:  "Supermatter surge" event, which might cause problems if the supermatter is not sufficiently cooled (i.e. the setup is messed up in some way)
/:cl:

2021-05-22 14:24 UTC, DuffCreeper commented
Now this tickles me fancy in a good way as someone whos an engineering main

2021-05-22 16:00 UTC, Gandalf2k15 requested changes
Make the magic numbers defines

2021-05-22 16:42 UTC, NotRanged commented
Adding some mater power really doesn't do that much afaik

if you add a check in canspawn() for the presence of a CE or like, at least 3 engineers, you could add some more 'fun' interactions. Have it release a range 5 heavy EMP for example that fucks with all the vents and settings. Or make it spawn a couple hundred moles of plasma/oxy/trit suddenly, after like a minute warning.

2021-05-23 02:35 UTC, FlamingLily commented
> 
> 
> Adding some mater power really doesn't do that much afaik
> 
> if you add a check in canspawn() for the presence of a CE or like, at least 3 engineers, you could add some more 'fun' interactions. Have it release a range 5 heavy EMP for example that fucks with all the vents and settings. Or make it spawn a couple hundred moles of plasma/oxy/trit suddenly, after like a minute warning.

This might be fun! Bundle them all in as "Supermatter Destabilization" events, with text that's like

"Supermatter Destabilization imminent, projected time ## seconds. Expected Effects: [Electromagnetic Pulse/Gaseous Release/Radiation Surge]"

2021-05-23 03:33 UTC, Gandalf2k15 commented
Yeah, once you've redone the magic values and such, reopen this or PR it upstream.

2021-05-23 03:33 UTC, closed without merging