[NON MODULAR] Vape carts + THC tweaks
Skyrat-SS13/Skyrat-TG pull request #6056
Opened 2021-05-31 06:35 UTC by linnpap

## About The Pull Request
Adds a variety of vape carts, which are now the only way to refill vapes. Also removes lipolicide from cannabis, and adds increased hunger as an effect of THC.

## Why It's Good For The Game
If I Do Not Have Dr Breens Blue Kush Reserve In Skyrat I Am Going To FUcking Kill Myself

## Changelog
:cl:
add: Added vape carts
del: Removed lipolicide from cannabis
add: Adds increased hunger as an effect of THC
/:cl:

2021-05-31 06:51 UTC, FlamingLily commented
Good change, but I do have to qualms. First, feature freeze, this should really wait until the codebase isn't dying

Two: https://github.com/tgstation/tgstation/pull/59360 you've been beaten too the punch on the weed tweaks

2021-05-31 06:54 UTC, linnpap commented
> Two: [tgstation/tgstation#59360](https://github.com/tgstation/tgstation/pull/59360) you've been beaten too the punch on the weed tweaks
yeah i know, its just that its a separate reagent thats getting added

2021-05-31 09:01 UTC, Sonic121x commented
I don't like the idea about haveing CUM inside a vape cart
atleast make it sell from kinkmate instead?

2021-05-31 10:47 UTC, StarHorder commented
I've seen Duboris do crazy antag things with their vape, would this still allow those things to be done?

2021-05-31 10:56 UTC, tf-4 requested changes

2021-05-31 10:56 UTC, tf-4 commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +/obj/item/reagent_containers/vapecart/empty/attackby(obj/item/I, mob/user, params)
No single letter variables

2021-05-31 10:56 UTC, tf-4 commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +	list_reagents = list(/datum/reagent/drug/thc = 20, /datum/reagent/consumable/pwr_game = 10, /datum/reagent/cum = 5 , /datum/reagent/toxin = 5) //pwr game literally is cum lets get real
Let's not even go there.

```suggestion
	list_reagents = list(/datum/reagent/drug/thc = 20, /datum/reagent/consumable/pwr_game = 10, /datum/reagent/drug/cocaine = 5 , /datum/reagent/toxin = 5) //pwr game literally is crack lets get real
```

2021-05-31 13:23 UTC, YakumoChen commented
Don't like this one at all..
Toxin in a smokable doesnt make sense. Taking toxins from drugs is generally limited to raw plants (like ambrosia) or hard drugs. Save taking toxins for addiction or overdose effects please. 

It also does a lot of damage quickly so no sane person would smoke the carts since they're fairly lethal.

On top of that, vaping makes clouds which means you multiply the reagents from smoking AND you're poisoning everyone around you with just a vendor available cart.

Cum in something smokable is a huge NO please dont even. You're going to immediately pref break everyone around you. Someone is going to buy one not knowing what's in it and be pref broke immediately. This is such a hugely bad idea.

2021-06-01 04:21 UTC, Funce commented
Feature Freeze

2021-06-01 12:52 UTC, FlamingLily commented
> Cum in something smokable is a huge NO please dont even. You're going to immediately pref break everyone around you. Someone is going to buy one not knowing what's in it and be pref broke immediately. This is such a hugely bad idea.

I didn't even see the cum cart, that's such a bad idea, holy crap. Like, I'm a _supporter_ of mechancial erp and goddamn, just, no...

2021-06-01 22:07 UTC, linnpap commented
> 
> 
> I've seen Duboris do crazy antag things with their vape, would this still allow those things to be done?

you can get empty vape carts that you can fill with reagents, so yeah

2021-06-10 23:11 UTC, Gandalf2k15 commented
Reopen after FF

2021-06-10 23:11 UTC, closed without merging