[NON-MODULAR] Making windows is no longer instant
Skyrat-SS13/Skyrat-TG pull request #6113
Opened 2021-06-03 22:23 UTC by ZephyrTFA

## About The Pull Request

Making windows is no longer instant.
They take four seconds to build now and are in line with making walls.
Directional windows take half as long.
All values are set via defines for ease of balance.

## Why It's Good For The Game

Admins said people were abusing windows being made instantly; this is no longer possible.

## Changelog
:cl:
fix: Making windows is now inline with making walls in that its not magically instant
/:cl:

2021-06-03 22:58 UTC, RatFromTheJungle commented
directional windows taking two seconds, means that assembly, with the three more seconds to screw them down, and the 7(?) to crowbar them in, ends out at twelve seconds per directional window, with a tidi of 20-30% that goes up 16-17 seconds, making it legitimately equal to building an entire airlock, A single 1/4 directional window. For something that wasn't even particularly abuseable to begin with. (they could be altclicked out of the way)

2021-06-03 23:30 UTC, YakumoChen commented
Make regular glass windows take half as long

>with a tidi of 20-30% that goes up 16-17 seconds, making it legitimately equal to building an entire airlock

Windows had three steps to construct before so the time isnt much lower. Walls take about as long to build as well.

2021-06-03 23:33 UTC, Funce requested changes
Can this be modularized please? Move the new defines, undefines and list inits under `modular_skyrat`

2021-06-03 23:47 UTC, ZephyrTFA commented
> 
> 
> directional windows taking two seconds, means that assembly, with the three more seconds to screw them down, and the 7(?) to crowbar them in(reinforced), ends out at twelve seconds per directional window, with a tidi of 20-30% that goes up 16-17 seconds, making it legitimately equal to building an entire airlock, A single 1/4 directional window. For something that wasn't even particularly abuseable to begin with. (they could be altclicked out of the way)

It's why they are defines that can be easily changed as needed; lets see how it works in practice before adjusting it

2021-06-03 23:57 UTC, Funce approved these changes
Bit more than I was thinking, but its probably the more ideal system. Probably. I'll eat it though.

2021-06-04 06:43 UTC, FlamingLily commented
Remember that we've got 
https://github.com/Skyrat-SS13/Skyrat-tg/tree/master/code/__DEFINES/%7Eskyrat_defines
https://github.com/Skyrat-SS13/Skyrat-tg/tree/master/code/__HELPERS/%7Eskyrat_helpers
and could probably do with a ~skyrat_vars or ~skyrat_llists in https://github.com/Skyrat-SS13/Skyrat-tg/tree/master/code/_globalvars

2021-06-05 05:20 UTC, merged