[WIP][SEMI-MODULAR]Synthetic wounds
Skyrat-SS13/Skyrat-TG pull request #6359
Opened 2021-06-17 03:40 UTC by Yawet330

## About The Pull Request
title

## Why It's Good For The Game
balance

## Changelog
:cl:
refactor: oh god oh fuck merge conflict time
/:cl:

2021-06-17 03:43 UTC, Snakebittenn commented
Early to ask but I figured I might as well, will this come with making synths not ridiculously fragile any longer?

2021-06-17 03:43 UTC, KasparoVy commented
> 
> 
> Early to ask but I figured I might as well, will this come with making synths not ridiculously fragile any longer?

I hope so but wouldn't hold out too much hope on it

2021-06-17 03:44 UTC, Yawet330 commented
> Early to ask but I figured I might as well, will this come with making synths not ridiculously fragile any longer?

synths will no longer die to a snowflake

2021-06-17 03:44 UTC, KasparoVy commented
GOD BLESS

2021-06-17 05:10 UTC, ZephyrTFA requested changes

2021-06-17 05:10 UTC, ZephyrTFA commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/burn.dm
> +		if(0 to WOUND_INFECTION_MODERATE)
```suggestion
```

2021-06-17 05:11 UTC, ZephyrTFA commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/burn.dm
> +		if(0 to WOUND_INFECTION_MODERATE)
Why does this exist if you dont do anything with it and there is also no else statement

2021-06-17 05:11 UTC, Yawet330 commented
PR is literally on-fucking-hold until Lummox sorts their shit out and allocates more memory to the compiler.

2021-06-17 10:49 UTC, Yawet330 commented
time to manually fix errors by using CI as a method of code reviewing.

2021-06-17 10:53 UTC, ZephyrTFA commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/pierce.dm
> +		tape(I, user)
```suggestion
	tape(I, user)
```

2021-06-17 11:06 UTC, Yawet330 commented
ok we may actually have a compiling code here

2021-06-17 11:11 UTC, Yawet330 commented
![image](https://user-images.githubusercontent.com/65188584/122385864-30110380-cf65-11eb-8e23-1fb40bebe20d.png)

2021-06-17 11:25 UTC, Yawet330 commented
currently runtimes when trying to create wounds, due to the list being fucky.

2021-06-17 14:23 UTC, Yawet330 commented
ok its probably ready this has been barely tested please speedmerge maintainers

2021-06-17 15:02 UTC, Yawet330 commented
this compiled fine, we just have monkey runtime 2.0 involving blood splatters.

2021-06-17 17:29 UTC, Yawet330 commented
ok it seems to work

2021-06-17 18:41 UTC, Yawet330 commented
Okay, everything actually works, lets FUCKING GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2021-06-17 20:30 UTC, Gandalf2k15 commented
Thank the lord. As a synth main, this is a god send. Finally.

2021-06-17 21:27 UTC, SpaceVampire commented
I really don't think that synths need cold resistance.
This wound thing is just trying to put em more on level with everyone else.
They still have a lot of major upsides left.
Oh also, leave the payday_modifier alone.
If you actually look, you would see that the other custom races.
Have a reduced one as well.

2021-06-17 21:29 UTC, hugmeorelse commented
Synths must suffer too

2021-06-17 21:43 UTC, Yawet330 commented
> I really don't think that synths need cold resistance.
> This wound thing is just trying to put em more on level with everyone else.
> They still have a lot of major upsides left.
> Oh also, leave the payday_modifier alone.
> If you actually look, you would see that the other custom races.
> Have a reduced one as well.
> EDIT: You also lowered the heat vulnerability at the same time. It was like. Three before.

you have absolutely no clue what this PR does to synths and I'm loving it

2021-06-17 21:51 UTC, SpaceVampire commented
> you have absolutely no clue what this PR does to synths and I'm loving it

I mean. You made the comment in the code.
//We removed this. Stop touching payday modifiers.
Which is factually incorrect if you look at the other races like I said.
So really, it would have been nice to get an actual reply or explanation.
Because I did take the time to read over all of the code, to try and get a feel for it.
And you really didn't offer anything in your documentation above.

2021-06-17 21:58 UTC, Yawet330 commented
> > you have absolutely no clue what this PR does to synths and I'm loving it
> 
> I mean. You made the comment in the code.
> //We removed this. Stop touching payday modifiers.
> Which is factually incorrect if you look at the other races like I said.
> So really, it would have been nice to get an actual reply or explanation.
> Because I did take the time to read over all of the code, to try and get a feel for it.
> And you really didn't offer anything in your documentation above.

yes its why its testmerged, it is still le WIP, and will be changed.

Wait until you see gameplay. Then you will regret.

2021-06-17 23:31 UTC, tf-4 reviewed
Mostly just variable naming and spelling/grammar.

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +		*/
```suggestion
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +		//SKYRAT EDIT CHANGE END
```suggestion
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +		if(blood_flow < minimum_flow)
this can be shifted around with a ! but I'm too tired to figure it out rn

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +/datum/wound/synthetic/slash/check_grab_treatments(obj/item/I, mob/user)
I

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +/datum/wound/synthetic/slash/treat(obj/item/I, mob/user)
I

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +/datum/wound/synthetic/slash/on_xadone(power)
maybe I'm an idiot but what is xadone

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	var/self_penalty_mult = (user == victim ? 1.25 : 1)
```suggestion
	var/self_penalty_multiplier = (user == victim ? 1.25 : 1)
```

don't really lose anything from writing it out fully here

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +/datum/wound/synthetic/slash/proc/tool_cauterize(obj/item/I, mob/user)
I

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	user.visible_message("<span class='danger'>[user] begins welding over [victim]'s [limb.name] with [I]...</span>", "<span class='warning'>You begin welding over [user == victim ? "your" : "[victim]'s
```suggestion
	user.visible_message("<span class='danger'>[user] begins welding over [user == victim ? "[user.p_their]" : "[victim]'s"] [limb.name] with [I]...</span>", "<span class='warning'>You begin welding over [user == victim ? "your" : "[victim]'s"] [limb.name] with [I]...</span>")
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	user.visible_message("<span class='green'>[user] welds over some of the leaking on [victim].</span>", "<span class='green'>You weld over some of the leaking on [victim].</span>")
```suggestion
	user.visible_message("<span class='green'>[user] welds over some of the leaking on [user == victim ? "[user.p_their]" : "[victim]'s"] [limb.name].</span>", "<span class='green'>You weld over some of the leaking on [user == victim ? "[user.p_their]" : "[victim]'s"] [limb.name].</span>")
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +/datum/wound/synthetic/slash/proc/slashtape(obj/item/stack/sticky_tape/surgical/B, mob/user)
B

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	desc = "Patients metallic coating has been sheared, causing internal leaking."
```suggestion
	desc = "Patient's metallic coating has been sheared, causing internal leaking."
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	treat_text = "Application of srugical tape and welding"
```suggestion
	treat_text = "Liberal application of surgical tape and welding"
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	examine_desc = "has a torn panel; slowly leaking"
```suggestion
	examine_desc = "has a torn panel, oil leaking out slowly."
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	desc = "Patients metallic outer coating has been entirely ripped open; exposing sensitive hydraulics."
```suggestion
	desc = "Patient's metallic outer coating has been entirely ripped open, exposing sensitive hydraulics."
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	treat_text = "Speedy application of surgical tape to stem the initial bleeding, then welding"
```suggestion
	treat_text = "Speedy application of surgical tape to stem the initial bleeding, followed by welding over the affected area"
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	examine_desc = "has severe damage to their limb, leaking oil heavily"
```suggestion
	examine_desc = "has severe damage to their limb, oil leaking heavily"
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	occur_text = "is ripped open, panel sparking and hydraulics leaking oil"
```suggestion
	occur_text = "is ripped open, its panel sparking and its hydraulics leaking oil"
```

2021-06-17 23:31 UTC, tf-4 commented on modular_skyrat/modules/syntheticwound/code/datums/wounds/slash.dm
> +	examine_desc = "has been absolutely destroyed, sparking electronics popped from the sides of their limb"
```suggestion
	examine_desc = "has been absolutely destroyed, sparking electronics protruding from their limb"
```

2021-06-17 23:33 UTC, Yawet330 commented on code/datums/wounds/_wounds.dm
> +		if(((wound_flags & BONE_WOUND) && !(HAS_BONE in H.dna.species.species_traits)) || ((wound_flags & FLESH_WOUND) && !(HAS_FLESH in H.dna.species.species_traits))) //Skyrat edit
originally the wound flags were adjusted, remnants. Will be removed before final merge

2021-06-17 23:33 UTC, Yawet330 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/robotic.dm
> +	heatmod = 1.4 //But slightly more from burn
it was only raised to 3 to nerf them in SEEK's PR

2021-06-17 23:34 UTC, Yawet330 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/robotic.dm
> +	payday_modifier = 1 //We removed this. Stop touching payday modifiers.
fair but this is also entirely deprecated as per Azarak's PR and should be set to 1 either way.

2021-06-17 23:34 UTC, Yawet330 commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/robotic.dm
> +/datum/species/robotic/spec_life(mob/living/carbon/human/H)
this was only moved, and was how the code was before. Not in the scope of the PR

2021-06-17 23:35 UTC, Yawet330 commented
thank you :)

2021-06-17 23:39 UTC, Yawet330 commented on code/datums/wounds/_wounds.dm
> +	if(!istype(L) || !L.owner || !(L.body_zone in viable_zones) || HAS_TRAIT(L.owner, TRAIT_NEVER_WOUNDED))
ok thats fair but i'll wait until final merge :)

2021-06-18 01:35 UTC, Yawet330 commented
No longer involved with this server. Feel free to mirror this branch and fix it up later.

2021-06-18 02:38 UTC, Gandalf2k15 commented
Noo, i gotta do this

2021-06-18 02:39 UTC, closed without merging

2021-06-18 02:39 UTC, Yawet330 commented
n o