[modular][ready]imperial uniforms for command
Skyrat-SS13/Skyrat-TG pull request #6396
Opened 2021-06-19 23:52 UTC by thestubborn

## About The Pull Request

![image](https://user-images.githubusercontent.com/58394696/122658130-89458680-d161-11eb-9eeb-e9c9bae5f373.png)
![image](https://user-images.githubusercontent.com/58394696/122658145-ae39f980-d161-11eb-984d-6a7505e28d07.png)
![image](https://user-images.githubusercontent.com/58394696/122658147-b6923480-d161-11eb-90e2-02e0e1ff745c.png)

## Why It's Good For The Game

flavour good, and gandalf wanted em
from star-wars-13-yog

## Changelog
:cl:
expansion: imperial clothing for command staff, a goggle helmet, and some more boots
/:cl:

2021-06-19 23:53 UTC, tf-4 commented
I don't want more meta-humour. And these clothes don't really fit regardless.

2021-06-19 23:57 UTC, thestubborn commented
> 
> 
> I don't want more meta-humour. And these clothes don't really fit regardless.

gandalf said ages back to add imperial clothing
I said I would

2021-06-20 00:15 UTC, MessoDepresso commented
Ngl the CE one specifically is too on-the-nose. Having that one for the Imperial Enclave or just events might be fitting, but having CEs with it might just cause le funny 'deathstar cannon BSA operator'

2021-06-20 00:29 UTC, MessoDepresso requested changes
Navel is the bellybutton, Naval is the military branch. Fix them typos :b

2021-06-20 00:39 UTC, Gandalf2k15 approved these changes

2021-06-20 00:42 UTC, ZephyrTFA requested changes

2021-06-20 00:42 UTC, ZephyrTFA commented on modular_skyrat/modules/customization/modules/client/loadout/head.dm
> +	name = "Captain's Naval Cap."
```suggestion
	name = "Captain's Naval Cap"
```

2021-06-20 00:42 UTC, ZephyrTFA commented on modular_skyrat/modules/customization/modules/client/loadout/head.dm
> +	name = "Head of Personnel's Naval Cap."
```suggestion
	name = "Head of Personnel's Naval Cap"
```

2021-06-20 00:42 UTC, ZephyrTFA commented on modular_skyrat/modules/customization/modules/client/loadout/head.dm
> +	name = "General Helmet"
```suggestion
	name = "General's Helmet"
```

2021-06-20 00:42 UTC, ZephyrTFA commented on modular_skyrat/modules/customization/modules/client/loadout/head.dm
> +	name = "Head of security's Naval Cap"
```suggestion
	name = "Head of Security's Naval Cap"
```

2021-06-20 00:42 UTC, ZephyrTFA commented on modular_skyrat/modules/customization/modules/client/loadout/uniform.dm
> + 	name = "Head of Security's naval uniform"
```suggestion
 	name = "Head of Security's Naval Uniform"
```

2021-06-20 00:42 UTC, ZephyrTFA commented on modular_skyrat/modules/customization/modules/clothing/head/head.dm
> +
```suggestion

```

2021-06-20 00:50 UTC, OrionTheFox commented
https://gyazo.com/f09529eb26faceaeabfce7eae14f22c8
The Imperial Engineer might be better with black gloves/boots/plating rather than a full black uniform

2021-06-20 00:52 UTC, thestubborn commented
> 
> 
> https://gyazo.com/f09529eb26faceaeabfce7eae14f22c8
> The Imperial Engineer might be better with black gloves/boots/plating rather than a full black uniform

i like that!

2021-06-20 00:54 UTC, OrionTheFox commented
also unironically make the wedge helmet function as a crowbar 🤣

2021-06-20 01:01 UTC, merged

2021-06-20 01:05 UTC, OrionTheFox commented
:cry: gandalf we werent done it needed the re-spriteeee

2021-06-20 01:09 UTC, Gandalf2k15 commented
Do it after :)

2021-06-20 01:12 UTC, OrionTheFox commented
that thirsty for your imperial uniforms, i see 😏