[MODULAR]Adios round killer
Skyrat-SS13/Skyrat-TG pull request #7124
Opened 2021-07-25 18:32 UTC by Yawet330

## About The Pull Request
goodbye cordyceps mold

## Why It's Good For The Game
buggy mess that ignores armor constantly despite repeated attempts to fix it

## Changelog
:cl:
del: Disables cordyceps mold from ebent
/:cl:

2021-07-25 18:35 UTC, ZephyrTFA commented
Needs a more descriptive title, but 💯

2021-07-25 18:35 UTC, ZephyrTFA requested changes

2021-07-25 18:35 UTC, ZephyrTFA commented on modular_skyrat/modules/biohazard_blob/code/biohazard_blob_structures.dm
> +	// AddComponent(/datum/component/slippery, 80) Adios
Changelog this

2021-07-25 18:49 UTC, ZephyrTFA approved these changes

2021-07-28 22:41 UTC, Gandalf2k15 commented
Instead of disabling it, find a way to make it work, don't just remove it and make someone else do it.

2021-07-28 22:41 UTC, closed without merging