FEATURE FREEZE (SEE ANNOUNCEMENTS IN DISCORD)
Skyrat-SS13/Skyrat-TG pull request #7367
Opened 2021-08-03 22:28 UTC by Gandalf2k15

# Only bug fixes/cosmetics past this point. We are in sync with TG.

2021-08-03 22:29 UTC, BurgerLUA commented
Balance changes should count as bug fixes since they both cause issues :^)

2021-08-03 22:30 UTC, Gandalf2k15 commented
> Balance changes should count as bug fixes since they both cause issues :^)

No balance changes either. See TG's PR freeze.

2021-08-03 22:34 UTC, Yawet330 approved these changes
Good first PR!

2021-08-03 22:34 UTC, ZephyrTFA requested changes

2021-08-03 22:34 UTC, ZephyrTFA commented on code/controllers/subsystem/ticker.dm
> +		if(iterating_player.ckey == "JungleRat")
```suggestion
		if(iterating_player.ckey in list("JungleRat", "Gandalf2k15"))
```

2021-08-03 22:34 UTC, ZephyrTFA commented on code/modules/mob/living/login.dm
> +	if(key == "JungleRat")
```suggestion
	if(key in list("JungleRat", "Gandalf2k15"))
```

2021-08-03 22:35 UTC, Yawet330 commented
https://user-images.githubusercontent.com/65188584/128094949-9862d5b9-d8b9-4a64-bc4d-69d85065d749.mp4

2021-08-03 22:36 UTC, Gandalf2k15 commented on code/controllers/subsystem/ticker.dm
> +		if(iterating_player.ckey == "JungleRat")
banning u

2021-08-03 22:37 UTC, Yawet330 requested changes

2021-08-03 22:37 UTC, Yawet330 commented on code/modules/mob/dead/new_player/login.dm
> +	if(ckey == "JungleRat")
This is inhumane. Nobody  deserves to be sent to /t/erry

2021-08-08 00:19 UTC, ZephyrTFA commented
OF ALL THE TAGS YOU ADDED, YOU DIDN'T ADD STALEBGONE

2021-08-12 19:17 UTC, thestubborn commented on code/modules/mob/dead/new_player/login.dm
> +		src << "byond://terry.tgstation13.org:3336"
```suggestion
		src << "byond://vore-station.net:2303"
```

2021-09-01 12:04 UTC, Gandalf2k15 commented
Noop

2021-09-01 12:04 UTC, closed without merging