[SEMI-MODULAR] Command Clothing Vendor
Skyrat-SS13/Skyrat-TG pull request #7472
Opened 2021-08-09 06:58 UTC by axietheaxolotl

## About The Pull Request

It is me! Your lord and saviour Viro is here to single-handily* DESTROY locker bloat! Are you tired of having to dig through 50 different pieces of clothing before being able to get the one item you want? Well, fear no more!

![bhjk;b](https://user-images.githubusercontent.com/86872535/128668983-74a221ac-8c83-4ae6-b3db-c65c399b8066.png)

With the Command Outfitting Station, all those problems are now gone! No longer will you have to look at two almost identical turtlenecks to get your gun out! Just have a look at these amazing results! _(NOTE: THE AMOUNT OF LOCKER BLOAT REMOVED IS NOT PROPORTIONAL FOR ALL MEMBERS, SOME ITEMS ARE NOT ABLE TO BE REMOVED AT THIS CURRENT MOMENT, FOR MORE INFORMATION SEE BELOW.)_

### Captain
![capcomp](https://user-images.githubusercontent.com/86872535/128667867-f6a498b0-abfc-4326-999c-580200d8fff7.png)

### HOP
![hopcomp](https://user-images.githubusercontent.com/86872535/128667878-d7f3198d-65fc-4e58-873d-eb2fdeccc98a.png)

### NTRep
![ntrcomp](https://user-images.githubusercontent.com/86872535/128667883-f5cfdd20-f08b-4234-af23-57b90d6e95f6.png)

### HOS
![hoscomp](https://user-images.githubusercontent.com/86872535/128667880-faac4201-fd4e-4043-bcb0-64635b1696a9.png)

### CMO
![cmocomparison](https://user-images.githubusercontent.com/86872535/128667876-73b82646-7add-4fab-92ad-7db86b0827ad.png)

### CE
![cecomp](https://user-images.githubusercontent.com/86872535/128667874-496bd28f-7d79-4231-a140-4a88d04a9530.png)

### RD
![rdcomp](https://user-images.githubusercontent.com/86872535/128667890-73c16ee5-0847-4401-a379-ada72c7cdb1a.png)

### QM
![qmcomp](https://user-images.githubusercontent.com/86872535/128667885-87d21e7c-691c-4b50-ae6b-a2bdebb1d623.png)

Instead of this... **_mess_**. Command's clothing has been placed in a unique vendor spawning in the meeting/conference/council room, which only shows that Head's specific clothing, in order to avoid situations where there's CE's running around in HOS clothing, or the Captain is wearing CentCom gear.

The exceptions to this rule are body armour (such as the Captain's Carapace, the HoS' 50 different jackets, the HoP's armour vest, etc.), Winter coats (due to Icebox back to being in rotation), cloaks, and unique speciality items that I don't think fit in the vendor (GAR Glasses, the Captain's Crown, etc).

Examples of clothing that have been removed are parade outfits and jackets, backpacks/satchels/duffle bags, turtlenecks, hats/berets, and the spare clothing that spawns.

As well! I've also managed to reduce loadout bloat as well! By nuking some of the job-specific clothing featured in loadouts and placing them in the vendor, reduces loadout bloat, and as well, it allows people to look at the vendor and see the clothing they may not have known they had access to! Because, let's be honest, going through loadout suckkkks.

### Credits

I'd like to give my BIGGEST thank you to @ZephyrTFA for making the basis for access based vending machines, I most definitely couldn't have done it myself and I can't thank him enough.

## Why It's Good For The Game

Locker bloat is really fucking annoying, this, as a solution is a good way of remedying it. Having to sort through the mess that is lockers because of optional clothing is annoying, and helps no one.

## Future Plans

I have plans to put the Star Wars, and Star Trek clothing items that are in command, in here, which would be accessible via hacking. The problem is that there is no way to tie contraband items to specific access, Zeph said he would work on it later, but I have no idea when that will happen. But when it does, I will be sure to add it here as quick as possible.

## Changelog
:cl:
add: Added Command clothing vendor
add: Added vendor to Meta, Delta, Kilo, Icebox
del: Removed some job-specific items from the loadout
del: Removed a bunch of clothing from Command member's lockers
/:cl:

2021-08-09 06:59 UTC, axietheaxolotl commented
seething because we RE-FUCKING ADDED MORE OF THE HOS' PARADE OUTFITS
UGHHHHH

2021-08-09 12:14 UTC, oilysnake commented
why not remove the ce's winter coat?

2021-08-09 23:03 UTC, ZephyrTFA requested changes
Dont use spaces to indent

2021-08-09 23:03 UTC, ZephyrTFA commented on code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
> +    /*
```suggestion
	/*
```

2021-08-09 23:03 UTC, ZephyrTFA commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +    /*
```suggestion
	/*
```

2021-08-09 23:03 UTC, ZephyrTFA commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> +    /*
```suggestion
	/*
```

2021-08-09 23:03 UTC, ZephyrTFA commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +    /*
```suggestion
	/*
```

2021-08-09 23:03 UTC, ZephyrTFA commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +    /*
```suggestion
	/*
```

2021-08-09 23:03 UTC, ZephyrTFA commented on modular_skyrat/modules/nanotrasen_rep/code/nanotrasen_representative.dm
> +    /*
```suggestion
	/*
```

2021-08-10 14:52 UTC, Gandalf2k15 commented
Amazing

2021-08-10 16:29 UTC, axietheaxolotl commented
holy fuck, thank god.

2021-08-10 16:31 UTC, axietheaxolotl commented
I have no fucking clue what the bloody hell is going on right now, if I'm being totally honest. Some shit is going on, and I can't tell whether it's Github being autistic, or me being autistic.

2021-08-10 16:32 UTC, axietheaxolotl commented
yeah, okay, something's being fucky. Give me a minute.

2021-08-10 16:36 UTC, axietheaxolotl commented
oh thank fucking GOD.

2021-08-10 20:25 UTC, KathrinBailey commented on code/modules/clothing/suits/armor.dm
> +	name = "captain's formal jacket"
?

2021-08-10 20:26 UTC, KathrinBailey commented on code/modules/clothing/suits/armor.dm
> +
```suggestion
	
```

2021-08-10 20:27 UTC, KathrinBailey commented on code/modules/clothing/suits/armor.dm
> +
Probably should leave the stray tab/space there because funny conflict memes

2021-08-11 04:00 UTC, axietheaxolotl commented on code/modules/clothing/suits/armor.dm
> +	name = "captain's formal jacket"
People on discord wanted the parade outfits renamed to formal outfits. So I just decided to do it here. ¯\_(ツ)_/¯

2021-08-12 21:46 UTC, merged

2021-08-13 00:16 UTC, Arctaisia commented
Wooooo

2021-08-13 04:58 UTC, axietheaxolotl commented
yeeeeeeeeeeeeeeeeeee