cyborg buff
Skyrat-SS13/Skyrat-TG pull request #7560
Opened 2021-08-14 17:34 UTC by jjpark-kb

## About The Pull Request
splits serviceborg's shaker into four separate ones; additional reagents to work with.
adds the cooking multitool to serviceborg.
adds electric welder as upgrade for all borgs.

## Why It's Good For The Game

## Changelog
:cl:
add: splits serviceborg's shaker into four separate ones; additional reagents to work with.
add: adds the cooking multitool to serviceborg.
add: adds electric welder as upgrade for all borgs.
/:cl:

2021-08-14 17:37 UTC, tf-4 commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +		to_chat(user, "<span class='notice'>You attach the rolling pin bit to [src].</span>")
```suggestion
		to_chat(user, span_notice("You attach the rolling pin bit to [src].")) 
```

2021-08-14 17:37 UTC, tf-4 commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +		to_chat(user, "<span class='notice'>You attach the knife bit to [src].</span>")
```suggestion
		to_chat(user, span_notice("You attach the knife bit to [src].")) 
```

2021-08-14 19:52 UTC, SpaceVampire commented
I really think that adding the electric welder as upgrade for all borgs is too much of a major buff.
Isn't that just giving every single cyborg fast self-healing? Why would anything but an Engi-Borg even have it?

2021-08-14 23:19 UTC, GoldenAlpharex commented
> I really think that adding the electric welder as upgrade for all borgs is too much of a major buff.
> Isn't that just giving every single cyborg fast self-healing? Why would anything but an Engi-Borg even have it?

At first I was agreeing with that PR, but uh, yeah, I agree with this, that's very likely going to absolutely yeet the cyborg balance out of the window.

2021-08-15 00:30 UTC, ZephyrTFA commented
Just gonna step in and say that being able to self repair as a borg is very powerful. Giving all models the ability to self repair like the engineering borg, but also do it twice as fast, seems like an absurd buff

2021-08-15 01:49 UTC, SpaceVampire commented
I would maybe just keep the stuff for the serviceborg in this one, and uh.
Move the welder changes into another PR, if you still want to go ahead with it.
Given that people generally seem to be cool with the first part, but not the second part.

2021-08-24 03:29 UTC, GoldenAlpharex requested changes
So close from being done.

2021-08-24 03:29 UTC, GoldenAlpharex commented on modular_skyrat/modules/borg_buffs/code/robot.dm
> +	. += " It's fitted with a [tool_behaviour == TOOL_KNIFE ? "screw" : "bolt"] head."
This isn't a powerdrill 😔 
```suggestion
	. += " It's fitted with a [tool_behaviour == TOOL_KNIFE ? "knife" : "rolling pin"] head."
```

2021-08-25 23:56 UTC, GoldenAlpharex approved these changes

2021-08-25 23:57 UTC, merged