[NON-MODULAR] Command and Central Command Budgets
Skyrat-SS13/Skyrat-TG pull request #7599
Opened 2021-08-16 18:18 UTC by axietheaxolotl

## About The Pull Request

I mean, you can read the title can you not?

Adds Command and Central Command budgets. Captain, NT Rep, and Blueshield no longer drain Security for their paychecks, and the glorified Cargo Decks at the Titan now have a budget so they don't drain the actual Station's budget.

## Why It's Good For The Game

Security can now actually have a budget.

## Changelog
:cl:
add: Added Command and CC budgets
add: Added NT Rep, Captain and Blueshield to Command Budget
add: Added NT Admiral to CC budget.
/:cl:

2021-08-16 18:23 UTC, axietheaxolotl commented
MY CHECKS NOOOOOOOOOOOOOO

2021-08-16 18:27 UTC, GoldenAlpharex requested changes
Just add a little comment here to say that it was an edit.

On another note, we should probably do something with the proc that decides the price of an item so that people with the appropriate access get the appropriate price, because having to put all the Heads in the Command budget would feel a bit weird, just to fix one minor inconvenience, and would many more.

2021-08-16 18:27 UTC, GoldenAlpharex commented on code/modules/jobs/job_types/captain.dm
> +	paycheck_department = ACCOUNT_CMD
```suggestion
	paycheck_department = ACCOUNT_CMD // SKYRAT EDIT - Original: paycheck_department = ACCOUNT_SEC
```

2021-08-17 00:41 UTC, FlamingLily commented on modular_skyrat/modules/blueshield/code/modules/jobs/job_types/blueshield.dm
> +	paycheck_department = ACCOUNT_CMD
Personally, I would have the blueshield as a CC paycheck as well

2021-08-17 18:37 UTC, axietheaxolotl commented
This got fucky with the shitty NTF merge, so I'm gonna close and re-open this to make my life infinitely easier.

2021-08-17 18:37 UTC, closed without merging