[SEMI-MODULAR] (mostly) fixes AI improvement PR code
Skyrat-SS13/Skyrat-TG pull request #7621
Opened 2021-08-18 06:13 UTC by Seris02

## About The Pull Request

#7066 made it so all AIs could hear all emotes from all ai_eye objects, as well as some other assorted bugs

the code was utter shit too, whoever wrote that code, please, make sure you look for variables to see if it can be done in a better way other than massive for loops

### testmerge this and make sure it works, I can't test it locally because it requires two clients

## Why It's Good For The Game

bug fix, code improvement

## Changelog
:cl:
fix: AIs will no longer hear all emotes from all ai_eye cameras
/:cl:

2021-08-18 06:20 UTC, FlamingLily commented
Multikey when testing is easy, first join the server, then close the pager, then join the server again, you'll join as a guest

2021-08-18 06:27 UTC, FlamingLily requested changes
Shiz broke, this should fix, but no promises, is webedit after all

2021-08-18 06:27 UTC, FlamingLily commented on modular_skyrat/modules/verbs/code/modules/client/verbs/looc.dm
>  	if(istype(mob,/mob/living/silicon/ai))
```suggestion
	if(istype(mob,/mob/living/silicon/ai))
	    var/mob/living/silicon/ai/ai = mob
```

2021-08-18 06:27 UTC, FlamingLily commented on modular_skyrat/modules/verbs/code/modules/client/verbs/looc.dm
> +	for(var/mob/ai in GLOB.ai_list)
```suggestion
	for(var/mob/living/silicon/ai/ai as anything in GLOB.ai_list)
```

2021-08-18 06:27 UTC, FlamingLily commented on code/datums/emotes.dm
>  	for(var/mob/ai in GLOB.ai_list)
```suggestion
	for(var/mob/living/silicon/ai/ai as anything in GLOB.ai_list)
```

2021-08-18 06:27 UTC, FlamingLily commented on modular_skyrat/modules/verbs/code/modules/client/verbs/looc.dm
>  	if(istype(mob,/mob/living/silicon/ai))
Beware indentation, I had to use spaces

2021-08-18 06:30 UTC, FlamingLily commented on code/datums/emotes.dm
>  	for(var/mob/ai in GLOB.ai_list)
I'ma be real I actually don't know the difference between using as anything or not but the last time I had to do smth like this I was told to use as anything so there

2021-08-18 07:47 UTC, SpaceVampire commented
Wasn't it #7063 that did that? I think you might have mentioned the wrong PR up above.

2021-08-18 12:47 UTC, tf-4 commented on code/datums/emotes.dm
> +	for(var/mob/living/silicon/ai/ai in GLOB.ai_list)
```suggestion
	for(var/mob/living/silicon/ai/ai as anything in GLOB.ai_list)
```
Shouldn't be able to be any other type here AFAIK.

2021-08-18 12:47 UTC, tf-4 commented on modular_skyrat/modules/verbs/code/modules/client/verbs/looc.dm
> +	for(var/mob/living/silicon/ai/ai in GLOB.ai_list)
```suggestion
	for(var/mob/living/silicon/ai/ai as anything in GLOB.ai_list)
```

2021-08-18 13:06 UTC, Gandalf2k15 commented
anythinng

2021-08-18 13:38 UTC, FlamingLily requested changes

2021-08-18 13:38 UTC, FlamingLily commented on code/datums/emotes.dm
> +	for(var/mob/living/silicon/ai/ai as anythinng in GLOB.ai_list)
```suggestion
	for(var/mob/living/silicon/ai/ai as anything in GLOB.ai_list)
```
anythinng

2021-08-18 13:38 UTC, FlamingLily commented on modular_skyrat/modules/verbs/code/modules/client/verbs/looc.dm
>  	if(istype(mob,/mob/living/silicon/ai))
```suggestion
	if(istype(mob,/mob/living/silicon/ai))
	    var/mob/living/silicon/ai/ai = mob
```
you marked this as resolved but didn't actually do anything and is still throwing errors

2021-08-18 13:38 UTC, FlamingLily commented on modular_skyrat/modules/verbs/code/modules/client/verbs/looc.dm
> +		if(ai.client && !(ai in heard) && ai.eyeobj in heard)
```suggestion
		if(ai.client && !(ai in heard) && (ai.eyeobj in heard))
```

2021-08-19 09:20 UTC, Seris02 commented
my brain has just
completely died for this PR

2021-08-21 19:20 UTC, tf-4 commented
link issue https://github.com/Skyrat-SS13/Skyrat-tg/issues/7250

2021-08-21 21:27 UTC, merged