venus changes
Skyrat-SS13/Skyrat-TG pull request #7692
Opened 2021-08-22 01:46 UTC by jjpark-kb

## About The Pull Request
many changes to venus human traps:
they can hide under the vines now, rather than being right above them
they can help a singular vine grow a second
if they are not on vines, they lose health
if they are on vines, they slowly gain back health
they no longer gain health upon moving on turf with vines
they cannot pull living mobs

## Why It's Good For The Game
vines are getting absolutely decimated by the scythe changes
perhaps it could be attributed to the vines being discovered when they havent grown enough

## Changelog
:cl:
balance: venus human traps no longer heal upon moving on vines
balance: venus human traps will lose health if not on vines
balance: venus human traps will gain health slowly if on vines
balance: venus human traps cannot pull living mobs
balance: venus human traps are set down a layer, right below vines
balance: venus human traps can help vines grow every second
/:cl:

2021-08-22 04:53 UTC, GoldenAlpharex requested changes

2021-08-22 04:53 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +			attacked_spacevine.spread()
Use the COOLDOWN defines to handles your cooldown, instead of doing it manually.

2021-08-22 04:53 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +			UnarmedAttack(check_contents)
Should hopefully be faster with a typecache.
```suggestion
	var/break_list = typecacheof(list(
		/obj/machinery/door,
		/obj/structure/table,
		/obj/structure/window,
		/obj/structure/girder,
		/obj/structure/grille,
		/obj/structure/rack,
		/obj/structure/door_assembly,
		/obj/structure/closet
	))
	for(var/check_contents in vine_turf.contents)
		if(isliving(check_contents) && !istype(check_contents, /mob/living/simple_animal/hostile/venus_human_trap))
			UnarmedAttack(check_contents)
		if(break_list[check_contents.type])
			UnarmedAttack(check_contents)
```

2021-08-22 04:53 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +			UnarmedAttack(check_contents)
Should be more efficient using a static typecache, it seems.
Please test this to make sure it works, I haven't actually tested to make sure the syntax was entirely correct.
```suggestion
	var/static/list/break_list = typecacheof(list(
		/obj/machinery/door,
		/obj/structure/table,
		/obj/structure/window,
		/obj/structure/girder,
		/obj/structure/grille,
		/obj/structure/rack,
		/obj/structure/door_assembly,
		/obj/structure/closet
	))
	for(var/check_contents in vine_turf.contents)
		if(isliving(check_contents) && !istype(check_contents, /mob/living/simple_animal/hostile/venus_human_trap))
			UnarmedAttack(check_contents)
		if(is_type_in_typecache(check_contents, break_list))
			UnarmedAttack(check_contents)
```

2021-08-25 02:03 UTC, YakumoChen commented
These are pretty substantial nerfs following an already crippling nerf to vines. Changing the healing to over time decimates their resiliency, the mob already has very low health.

Venus needs a way to attack crew standing under vines without damaging the vines as well.

2021-08-28 01:11 UTC, merged