[MODULAR] Readds Peacekeeper lockers with animation
Skyrat-SS13/Skyrat-TG pull request #7704
Opened 2021-08-22 21:56 UTC by axietheaxolotl

## About The Pull Request

See title.

Also adds animations to the CC locker.

## Why It's Good For The Game

The current red sec lockers give me an aneurysm, and the new sec_haul lockers were only removed because they weren't animated, which they now are.

## Changelog
:cl:
add: Readds Peacekeeper lockers with animation
add: adds animation for cc locker
/:cl:

2021-08-22 21:57 UTC, axietheaxolotl commented
CONFLICTS
REEEE

2021-08-23 04:27 UTC, FlamingLily commented on modular_skyrat/modules/sec_haul/code/peacekeeper/peacekeeper_lockers.dm
> +	icon = 'modular_skyrat/modules/sec_haul/icons/lockers/closet.dmi'
```suggestion
	icon = 'modular_skyrat/modules/sec_haul/icons/lockers/closet.dmi'
	
```

2021-08-23 04:27 UTC, FlamingLily requested changes

2021-08-23 04:27 UTC, FlamingLily commented on modular_skyrat/modules/sec_haul/code/peacekeeper/peacekeeper_lockers.dm
> +	icon = 'modular_skyrat/modules/sec_haul/icons/lockers/closet.dmi'
dm gets angy w/ no newlines at end of file

2021-08-23 15:15 UTC, Gandalf2k15 commented
You will need to update the actual code for some lockers with the angry comment next to them.

2021-08-28 01:08 UTC, merged