[MODULAR] Medicell Safety
Skyrat-SS13/Skyrat-TG pull request #7734
Opened 2021-08-24 02:48 UTC by softcerv

## About The Pull Request
Gives the Medicells an option to toggle the safety on them by using them in hand. Toggling the safety means that they are unable to heal damage if it will cause any kind of clone damage to the patient.  This should make it that healing someone at high damage thresholds with medigun will be much more of an intentional choice. By default, cells have safety on.

## Why It's Good For The Game
Prevents doctors from accidentally doing clone damage when using the brute/burn cells on the medigun. 

## Changelog
:cl:
expansion: Medicells now have a safety toggle, preventing them from healing brute/burn when it would do clone damage.
/:cl:

2021-08-24 02:55 UTC, tf-4 commented on modular_skyrat/modules/modular_weapons/code/modules/projectiles/guns/energy/medgun/medguns.dm
> +	if(on_safety ==  1)
```suggestion
	if(on_safety)
```
Tiny tweak.

2021-08-24 03:01 UTC, softcerv commented on modular_skyrat/modules/modular_weapons/code/modules/projectiles/guns/energy/medgun/medguns.dm
> +	if(on_safety ==  1)
ah, thank you!

2021-08-24 16:51 UTC, GoldenAlpharex requested changes
There's a _lot_ of repetition going on here.
Try making something that's less repetitive, this could be a very good code improvement if you reduced all this repetition in here. If you need help with that, hit me up on Discord and we can go through it together.
However, this isn't ready for merging yet, there's simply too many things that repeat themselves, and there's some occasions where you make several identical proc calls in a row, like for `target.adjust_disgust()`, which would gain from using a temporary variable to store by how much you want the disgust to be modified, and only be called once if the disgust delta is different from 0, for instance.

2021-08-24 16:51 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/modules/projectiles/guns/energy/medgun/medcells.dm
> +	if(target.getBruteLoss() > 49)
Logically the same thing, but it just looks better code-wise.
```suggestion
	if(target.getBruteLoss() >= 50)
```

2021-08-24 16:51 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/modules/projectiles/guns/energy/medgun/medcells.dm
> +	if(target.getFireLoss() > 49)
Ditto.
```suggestion
	if(target.getFireLoss() >= 50)
```

2021-08-24 16:51 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/modules/projectiles/guns/energy/medgun/medcells.dm
>  	if(target.getBruteLoss() > 49)
Ditto.
```suggestion
	if(target.getBruteLoss() >= 50)
```

2021-08-24 16:51 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/modules/projectiles/guns/energy/medgun/medcells.dm
>  	if(target.getBruteLoss() > 99)
Ditto.
```suggestion
	if(target.getBruteLoss() >= 100)
```

2021-08-25 22:43 UTC, GoldenAlpharex requested changes
I think you should try having the medicells have three subtypes, `brute`, `burn`, `toxin` and then you just tweak the values this way, it would be much cleaner, I'd imagine.

2021-08-28 01:13 UTC, Gandalf2k15 commented
Is this done?@

2021-08-28 01:18 UTC, GoldenAlpharex approved these changes
I'm satisfied with the code quality, if this works as intended still, it's good to merge.

2021-08-28 01:19 UTC, softcerv commented
> 
> 
> I'm satisfied with the code quality, if this works as intended still, it's good to merge.

I did testing on everything, it should probably work.

2021-08-28 01:55 UTC, merged