[MODULAR] Makes the best carpet available for purchase
Skyrat-SS13/Skyrat-TG pull request #7765
Opened 2021-08-25 14:46 UTC by axietheaxolotl

## About The Pull Request

you can now buy a crate with executive carpet in it

## Why It's Good For The Game

The exec carpet is the best carpet, and the only way you can get is either it spawning in the map, or maint crawling, which is annoying. That is now fixed.

## Changelog
:cl:
add: added exec carpet crate
/:cl:

2021-08-25 16:25 UTC, Arctaisia commented
Best PR,,,,

2021-08-26 15:22 UTC, Krysonism commented
I'm happy that people enjoy my carpets. 

However I'd like to caution against making the supply of scare items infinite and easy to obtain.

I intentionally avoided adding a cargo crate for these carpets with the reasoning that rarity and scarcity is a big part of what makes something cool.

I don't play skyrat so my opinion should not be given much weight, but I think what I'd like to call "candy for breakfast design" is a big problem across all of SS13.

2021-08-26 17:45 UTC, GoldenAlpharex commented
> I'm happy that people enjoy my carpets.
> 
> However I'd like to caution against making the supply of scare items infinite and easy to obtain.
> 
> I intentionally avoided adding a cargo crate for these carpets with the reasoning that rarity and scarcity is a big part of what makes something cool.
> 
> I don't play skyrat so my opinion should not be given much weight, but I think what I'd like to call "candy for breakfast design" is a big problem across all of SS13.

That's a fair comment, and I at first was going to make a PR about it a few months back, but I do enjoy the scarcity of it, and if anything, I think it should be a lot more expensive to make up for the fact of how rare it's meant to be.

2021-08-26 18:21 UTC, SpaceVampire commented
Not only do I disagree with having it available for purchase at all.
But why in the world is it that cheap?
	/// Cost of the crate. DO NOT GO ANY LOWER THAN X1.4 the "CARGO_CRATE_VALUE" value if using regular crates, or infinite profit will be possible!
	var/cost = CARGO_CRATE_VALUE * 1.4
As you can see. That is the cost of just the crate, without anything in it.
So you have the most rare and fancy carpet, being sold at net loss on shipping alone.

2021-08-26 22:08 UTC, axietheaxolotl commented
> 
> 
> I'm happy that people enjoy my carpets.
> 
> However I'd like to caution against making the supply of scare items infinite and easy to obtain.
> 
> I intentionally avoided adding a cargo crate for these carpets with the reasoning that rarity and scarcity is a big part of what makes something cool.
> 
> I don't play skyrat so my opinion should not be given much weight, but I think what I'd like to call "candy for breakfast design" is a big problem across all of SS13.

I think that's a fair point, but honestly. Making it scarce doesn't really do much, at least for me. It doesn't really make it feel more special, it just makes it more annoying that I have something I want, but it's entirely up to RNG whether or not I get it. The scarcity of it does little for me, it's just an annoyance more then anything.

2021-08-26 22:09 UTC, axietheaxolotl commented
> 
> 
> Not only do I disagree with having it available for purchase at all.
> But why in the world is it that cheap?
> /// Cost of the crate. DO NOT GO ANY LOWER THAN X1.4 the "CARGO_CRATE_VALUE" value if using regular crates, or infinite profit will be possible!
> var/cost = CARGO_CRATE_VALUE * 1.4
> As you can see. That is the cost of just the crate, without anything in it.
> So you have the most rare and fancy carpet, being sold at net loss on shipping alone.

What I get for not reading the code, yeah it's been fixed. Bumped the price up a decent bit.

2021-08-29 01:18 UTC, GoldenAlpharex commented
I don't see why it's not like the other carpet single-packs.

2021-09-01 16:47 UTC, GoldenAlpharex requested changes
My offer on this, making it more expensive and there's less.

2021-09-01 16:47 UTC, GoldenAlpharex commented on modular_skyrat/modules/cargo/code/packs.dm
> +		/obj/item/stack/tile/carpet/executive/thirty,
```suggestion
```

2021-09-01 16:47 UTC, GoldenAlpharex commented on modular_skyrat/modules/cargo/code/packs.dm
> +	cost = CARGO_CRATE_VALUE * 3
```suggestion
	cost = CARGO_CRATE_VALUE * 4
```

2021-09-09 17:38 UTC, GoldenAlpharex commented
@axietheaxolotl Update from master to make sure the checks don't fail anymore.

2021-09-11 15:32 UTC, Gandalf2k15 commented
Given what the creator stated, let's not go down this slippery slope.

2021-09-11 15:32 UTC, closed without merging