[MIRROR] Exit on DreamMaker warnings in CI Windows build + Tools reset
Skyrat-SS13/Skyrat-TG pull request #7784
Opened 2021-08-26 09:09 UTC by SkyratBot

Original PR: https://github.com/tgstation/tgstation/pull/61025
--------------------

## About The Pull Request

Added an option to tools/build/build to treat DreamMaker warnings as errors. Enabled this option only for Windows Build (tools/ci/build.ps1).

## Why It's Good For The Game

Solves #60895. Warnings are treated only as errors if --error is flag is used in build. This is because you don't want local builds to fail because of warnings, sometimes you just want to test. It also is not enabled for all CI jobs. This is because I think it's beneficial to differentiate between map errors, integration error and and "warnings treated as errors" errors. The example is here https://github.com/mokulus/tgstation/pull/3. Only Windows build fails. The exit code is 2 to differentiate from a real error. There is also error message logged "=> Compile warnings treated as errors" and it only shows if there are warnings.

If any change doesn't seem right (for example naming or 2 return code) I'll change it.

## Changelog
:cl:
code: Treat DreamMaker warnings as errors in CI
/:cl:

2021-08-28 00:59 UTC, GoldenAlpharex commented
We need to compare all of our building tools with upstream, because there seems to be a lot of stuff missing.

2021-09-01 15:38 UTC, GoldenAlpharex requested changes
From what I can tell, this /should/ work. So long as this is Juke 0.8.1 and not Juke 0.9.0, we should be good to go. Just remove `gbp.toml` from the PR and this should (hopefully) have no impact on us.

2021-09-01 15:38 UTC, GoldenAlpharex commented on .github/gbp.toml
> +"Balance/Rebalance" = -8
Revert this file, this was modified for our needs.

2021-09-01 15:38 UTC, GoldenAlpharex commented on .github/workflows/pr_emoji.yml
> +name: PR emoji stripper
Hahaha, the Emoji stripper for PRs, that's a good one.

2021-09-01 15:40 UTC, Gandalf2k15 commented on .github/gbp.toml
> +"Quality of Life" = 1
```suggestion
"Quality of Life" = 2
```

2021-09-01 15:40 UTC, Gandalf2k15 commented on .github/gbp.toml
> +"Mechanic" = -10
```suggestion
"Mechanic" = -4
```

2021-09-01 15:40 UTC, Gandalf2k15 commented on .github/gbp.toml
> +"Fix" = 3
```suggestion
"Fix" = 4
```

2021-09-01 15:41 UTC, Gandalf2k15 commented on .github/gbp.toml
> +"Balance/Rebalance" = -8
```suggestion
"Balance/Rebalance" = -4
```

2021-09-01 15:41 UTC, merged