Additional Traitor Templates
Skyrat-SS13/Skyrat-TG pull request #7833
Opened 2021-08-28 16:15 UTC by Aether217

## About The Pull Request
Adds 4 new templates to help antagonists who have issues with new ideas or pushing themselves out of their comfort zone. It also adds another objective to the Data Theft template so it's not just rushing the blackbox and sitting in a pod.

## Why It's Good For The Game
More templates, more fun. A common issue we often have is people wanting to have their antag status removed because they didn't prepare a gimmick. These 4 templates should give people a few more options, ranging from more serious and mild to more extreme and a bit silly even.

## Changelog
:cl:
add: Added 4 new templates: Mind Control Victim, Lone Pirate, Cyber Terrorist, Stamp Collector.
add: Added an extra objective to the Data Theft template
/:cl:

2021-08-28 16:17 UTC, tf-4 commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	tips = list("You should add an objective on how you plan to go about this task.", "The Blackbox is located in Telecomms on most Stations.", "The Blackbox doesn't fit in most bags. You'd need a bag o
```suggestion
	tips = list("You should add an objective on how you plan to go about this task.", "The Blackbox is located in Telecomms on most Stations.", "The Blackbox doesn't fit in most bags. You'd need a bag of holding to hide it!", "To steal technology we'll have to print a disk from science and sneak our way to a research console and download nodes on the disk!")
```

Missed a quotation closing heh

2021-08-28 20:19 UTC, jjpark-kb commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	objectives = list("Steal the Blackbox.", "steal at least 20 technology nodes from the research division." "Escape on the emergency shuttle alive and out of custody.")
```suggestion
	objectives = list("Steal the Blackbox.", "steal at least 20 technology nodes from the research division.", "Escape on the emergency shuttle alive and out of custody.")
```

2021-08-28 21:25 UTC, tf-4 commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	narative = "<%Uplink connection established, welcome #Agent#%> We have detected multiple ways to weaken the station through their artificial units, you will be tasked with manipulating the cyberneti
```suggestion
	narrative = "<%Uplink connection established, welcome #Agent#%> We have detected multiple ways to weaken the station through their artificial units, you will be tasked with manipulating the cybernetic elements of the station to greatly hinder it's productivity and teach them a lesson about over-reliance on technology!"
```

2021-08-29 01:05 UTC, GoldenAlpharex requested changes
Just a few minor punctuation changes, otherwise this is pretty good, I'd say.

2021-08-29 01:05 UTC, GoldenAlpharex commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	tips = list("The workers, they probably don't know much about this so I should avoid harming them...", "The heads will likely be tough to crack but I know they're hiding it from me, sometimes you ha
```suggestion
	tips = list("The workers, they probably don't know much about this so I should avoid harming them...", "The heads will likely be tough to crack, but I know they're hiding it from me, sometimes you have to use force to get what you need.", "There might be others like me, I should try to contact them.")
```

2021-08-29 01:05 UTC, GoldenAlpharex commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	narrative = "Stamps, such an underappreciated art! Did you ever stop to take a closer look at one before marking a piece of paper with it? If you did you'd notice all the intricate details that go i
```suggestion
	narrative = "Stamps, such an underappreciated art! Did you ever stop to take a closer look at one before marking a piece of paper with it? If you did, you'd notice all the intricate details that go into them, the beautiful sculpted pieces soaked in the ink... All left to gather dust in the offices of those moronic heads. I think it's time for someone with more appreciation for the art to take care of them!"
```

2021-08-29 01:05 UTC, GoldenAlpharex commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	tips = list("A multitool can be used to mess with the focus of the camera, it also won't trigger it's alert system.", "With a bit of experimentation and some signallers we can remotely turn off powe
```suggestion
	tips = list("A multitool can be used to mess with the focus of the camera, it also won't trigger it's alert system.", "With a bit of experimentation and some signallers, we can remotely turn off power in areas via their APCs.", "The ability to read all messages is quite powerful, shame that the Chief Engineer did not bother to hide the paper with the password in his office!")
```

2021-08-29 09:10 UTC, Aether217 commented
Done with all of the changes above

2021-08-29 16:06 UTC, Lauwma commented
Very good addition, good themes and good flavors

2021-09-01 15:56 UTC, GoldenAlpharex requested changes
Last little nitpick!

2021-09-01 15:56 UTC, GoldenAlpharex commented on modular_skyrat/modules/ambitions/code/ambition_templates.dm
> +	tips = list("You should add an objective on how you plan to go about this task.", "The Blackbox is located in Telecomms on most Stations.", "The Blackbox doesn't fit in most bags. You'd need a bag o
```suggestion
	tips = list("You should add an objective on how you plan to go about this task.", "The Blackbox is located in Telecomms on most Stations.", "The Blackbox doesn't fit in most bags. You'd need a bag of holding to hide it!", "To steal technology we'll have to print a disk from science and sneak our way to a research console to download nodes on the disk!")
```

2021-09-06 11:43 UTC, merged