[Mostly Nonmodular] Chameleon Mutation Buffs
Skyrat-SS13/Skyrat-TG pull request #7873
Opened 2021-08-31 02:33 UTC by Snakebittenn

## About The Pull Request
Makes the mutation a toggle, so that it isn't constantly on no matter what. Raises the instability to 35. If this is deemed too powerful, I'm willing to make it so that you're **constantly slightly transparent even if it's turned off**, so people know you have it. Like the old TK aura.

## How This Contributes To The Skyrat Roleplay Experience
I know a lot of people generally dislike genetics mutations, but I feel like some of them can be used, basically, as roleplay props. It's difficult to make use of Chameleon in such a way right now because it's, let's face it, difficult to roleplay with someone that is nonstop permanently invisible, and it can be a little straining on the immersion to have them be carrying like 9 syringes of it and 9 pills of mutadone just to toggle it on and off. I could see people using it to prank their friends like hiding in a room and waiting for them, or even using it with telepathy to narrate stuff to them (like their SECRET LOVE CRUSH ON THE CAPTAIN WOOOO.) 
also i want to make a qt chameleon girl.

## Changelog
:cl:
add:  Chameleon mutation can now be toggled on and off.
balance: Chameleon mutation instability raised to 35.
/:cl:

2021-08-31 02:53 UTC, GoldenAlpharex commented
You got mixed indentation, you need to go to the bottom-right in VSC and check the "Tabs" button, and then click "Convert To Tabs" and it will convert all the indentation to tabs.

2021-08-31 03:09 UTC, RatFromTheJungle commented
Does this also affect changelings? 👍  if it does

2021-08-31 16:57 UTC, tf-4 commented on code/datums/mutations/chameleon.dm
> +		user.alpha = 255
```suggestion
	REMOVE_TRAIT(user, TRAIT_CHAMELEON_SKIN, GENETIC_MUTATION)
	user.alpha = 255
```

2021-08-31 17:00 UTC, Snakebittenn commented
gottem

2021-08-31 22:10 UTC, SpaceVampire commented
I think this buff is fine, given the other stuff we have already removed from genetics.
I even think that not having it show if you have it will actually make it potentially useful for doing sneaky stuff.
It's not really like TK, where having no visual sign would actually be cancer.
Because the power is a lot more useful and offensively focused.

2021-09-01 15:47 UTC, GoldenAlpharex requested changes
Almost there!

2021-09-01 15:47 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +	to_chat(user, text("The pigmentation of your skin shifts and starts to take on the colors of your surroundings."))
```suggestion
	to_chat(user, "The pigmentation of your skin shifts and starts to take on the colors of your surroundings.")
```

2021-09-01 15:47 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +
There's no reason to have two lines there, you're going to confuse people.
```suggestion
```

2021-09-01 15:47 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +	to_chat(user, text("Your skin shifts as it shimmers back into its' original colors."))
```suggestion
	to_chat(user, text("Your skin shifts as it shimmers back into its original colors."))
```

2021-09-01 15:54 UTC, Snakebittenn commented
redy

2021-09-02 02:54 UTC, merged