[Semi-Modular] SeleneStation
Skyrat-SS13/Skyrat-TG pull request #7932
Opened 2021-09-02 14:04 UTC by sergeirocks100

## About The Pull Request

![s85](https://user-images.githubusercontent.com/31294280/131853741-e764e1e0-8b0d-4b93-889c-6accd70ba91c.png)

Serene is a medium to high-pop map, originally from Fulp.

I think it's a pretty unique and interesting map, and i think it would fit in well on Skyrat's map rotation.

## How This Contributes To The Skyrat Roleplay Experience

Variety is the spice of life, and i think Selene will bring some variety to the map rotation.

Plus, it's not attached to a map on the /tg/ mainline, so it allows for more mapping freedom.

## Changelog
:cl:
add: Nanotrasen space station 621-A, codename "Selene", has been put into service.
/:cl:

2021-09-02 14:10 UTC, FlamingLily commented
This map looks fucking awesome

No annoying gimmick

A robust layout that isn't just Box/Meta/Delta

Sign me the fuck up

2021-09-02 14:12 UTC, FlamingLily requested changes
The mining shuttle's still referencing fulp, be sure to fix that

2021-09-02 14:12 UTC, FlamingLily commented on _maps/_basemap.dm
> +		#include "map_files\SeleneStation\SeleneStation.dmm"
Skyrat edit comment

2021-09-02 15:55 UTC, softcerv commented
Looks neat, although I do wonder why there are two viro workstations

2021-09-02 17:32 UTC, Trubbl3 commented
something new is always welcomed

2021-09-02 20:22 UTC, GoldenAlpharex commented
Looks good! If I may suggest, I would put some reinforced windows here, to improve the visibility (and overall look) of Xenobiology:
![image](https://user-images.githubusercontent.com/58045821/131908367-ae9e97b4-1ea7-4ef1-bd43-a0e34fbd8d19.png)

Here, I would move the cyborg charger to this stall (in red) and then turn the cyborg charger spot into some showers (in green), because the only showers being kind of open in the locker room is a bit awkward:
![image](https://user-images.githubusercontent.com/58045821/131908785-631f6db3-387a-4867-9f77-78c211d7971a.png)

This is cool, but are you sure that people won't hurt themselves big time going in and out of that room? Also, what's the point of barricading that part off?
![image](https://user-images.githubusercontent.com/58045821/131909213-fcfe80b5-b4c9-402e-b212-4a56de5e800c.png)

This is a lot of free tools lockers:
![image](https://user-images.githubusercontent.com/58045821/131909455-cb4a7e6b-234a-4042-a6f7-207cdf50966d.png)

If you wanted to be real cool, you could add some windoors here, to stop cross-polinisation, or rather, toggle it on/off depending on what the botanists would like. Could be a nice little QoL:
![image](https://user-images.githubusercontent.com/58045821/131909666-5be5defc-bfec-4e47-917a-d3f7ea50cd8a.png)

If I recall correctly, all walls exposed to space are supposed to be reinforced walls, no? Otherwise it's really, really easy to space a room.
![image](https://user-images.githubusercontent.com/58045821/131909822-4abdcd07-add1-49b5-913f-bc96a7282bf8.png)

This feels like a bit too much protection for these boards:
![image](https://user-images.githubusercontent.com/58045821/131910524-e12df2b4-4f11-4db6-a8a4-2eecb0146835.png)

There's also no Blueshield or NT Rep office.

Overall, it looks really nice and I can't wait to try it out.

2021-09-02 21:02 UTC, Gandalf2k15 commented
We can test this next round.

2021-09-02 21:35 UTC, GoldenAlpharex commented
Whoops, I think those weren't the right bedsheets.
![image](https://user-images.githubusercontent.com/58045821/131919380-f06e0dab-df41-43f3-8e84-7fe15a7bcb2b.png)

2021-09-02 22:05 UTC, MidoriWroth commented
Hydroponics trays seem to consider water a nutrient, and the water in the trays rapidly fluctuates
![S8qxapq](https://user-images.githubusercontent.com/18170896/131922406-c1a89177-8e8b-4139-8245-e68dc70cbc75.png)

2021-09-02 22:24 UTC, axietheaxolotl commented
> 
> 
> Whoops, I think those weren't the right bedsheets.
> ![image](https://user-images.githubusercontent.com/58045821/131919380-f06e0dab-df41-43f3-8e84-7fe15a7bcb2b.png)

This isn't the fault of the map creator. This is the fault of me being autistic. Double bedsheets now spawn in the random sheet obj. Which is being fixed soon

2021-09-02 22:25 UTC, GoldenAlpharex commented
> > Whoops, I think those weren't the right bedsheets.
> > ![image](https://user-images.githubusercontent.com/58045821/131919380-f06e0dab-df41-43f3-8e84-7fe15a7bcb2b.png)
> 
> This isn't the fault of the map creator. This is the fault of me being autistic. Double bedsheets now spawn in the random sheet obj. Which is being fixed soon

🎊

2021-09-02 22:34 UTC, axietheaxolotl commented
C+P from Discord:
> This map looks good, but it's missing a lot because if it's port status. People have already mentioned there's no NTRep or Blueshield office, but as well: there's no Command Clothing Vendor, there's no SecMed locker (it could also deal with a healthy sprinkling of our custom airlocks)

2021-09-02 23:10 UTC, SpookyTheFox commented
Looks really good! A few first impressions for possible improvements, I will edit to add to this list as I look closer at it:
I'm mostly focusing in mebay, because that's what I main. Overall, very very good!
A+ on the lobby/reception area. I love everything about it. Public facing chemistry counter, a reception desk, sofas, tables, lamps, potted plants... excellent!
The chemistry plumbing room- could use more interior windows facing into the hallway, preferably also with shutters like the ones on other maps. Ideally, the windows should expose the chem dispenser set to the hallway, so it can be upgraded by someone walking by with a BSRPED. It also needs a second door, probably just into maintenance in the south.
The recovery room- makes sense ICly, but usually anyone afk while in medbay gets just put out in the lobby. The space may be 
Plasma man/vox medbay is really cool! It needs the air alarm set to not be in alarm state at round start though. Maybe some signage of some sort to indicate what it is. While the chutes do their job, doors with tiny fans under them might do the job better. They will let people go in and out in a less... silly way.
I don't see a MULE chute anywhere in medbay.

Lots of good maintenance features I've seen so far, but it will take a while to look at all of it.

Rec area has weight machines- finally! Half my characters are _ripped_ and it makes no sense that they wouldn't be found in a gym environment at least some of the time.
AI sat access in the rec area is a little odd, maybe make that a strong door with reinforced walls on the part facing into the public area.
Seems like there's plenty of holopads, that's good too, I use them a lot as AI.

2021-09-03 04:52 UTC, CandleJaxx commented
toxins/ordinance mass driver isn't connected to the controller
![image](https://user-images.githubusercontent.com/68376391/131952145-ba89ef90-2228-494b-92dc-13664810fae2.png)
door is, driver not

2021-09-03 13:08 UTC, Sonic121x commented
1:Engineering lacking a portable generator.(there is plasma but no portable generator in engineering,maybe consider replace one of the budget solar panel crate in power storage or secure storage)

2021-09-03 17:01 UTC, JohnFulpWillard commented
This has been really painful for me to watch from the very start.

You tried porting this map to your own server, one that one of our mappers spent months making, but couldn't even bother to be respectful enough to properly spell (calling it 'Serene' instead of 'Selene') until the creator of the map themselves (Helianthus) commented on your original PR about how hurt they are that you are deliberately misspelling their map's name and that you couldn't even bother to ask them beforehand, to which you didn't respond to at all (but at least you are using the right name for the map this time, so you've obviously seen the comment they left).

Then, a few days after their comment, you are now porting it to ANOTHER server, and AGAIN without asking the original map maker first (something that takes a minute to ask over discord, there's even a dedicated channel for this sort of stuff), nor did you again bother crediting the original maker of the map or the server it originated from https://github.com/fulpstation/fulpstation/pull/109

I don't know what Fulpstation did to you or why you are doing this, whether it's out of spite or grudge against the server or the map maker as an individual, but what you've done and have been doing has been really disrespectful and personally comes off to me as doing it maliciously or out of hate.

2021-09-03 19:36 UTC, Helianthus00 commented
Please be aware that I absolutely hate the idea of my map being used on an ERP server, though I have no way to stop you.

Though I'm not sure why you're porting something to this "shitty codebase" as you called it. It is disgusting, your lack of respect for fellow contributors in the community.

2021-09-03 21:10 UTC, hugmeorelse commented
> Please be aware that I absolutely hate the idea of my map being used on an ERP server, though I have no way to stop you.
> 
> Though I'm not sure why you're porting something to this "shitty codebase" as you called it. It is disgusting, your lack of respect for fellow contributors in the community.

I don't know what you have against ERP servers (nor why you would specify that as if we're tainted), but I have to agree that it seems pretty bad faith on the part of the person here to port the map out of spite. We have no plans of merging this any time soon out of respect.

2021-09-03 21:44 UTC, tf-4 commented
-1
Lovely map, ported in the most disrespectful, unbecoming way possible.
Not at all interested in seeing it on Skyrat for that reason alone - which is somewhat of a shame, as it is legitimately a nice map.

2021-09-03 21:50 UTC, FlamingLily commented
As much as I hate to say it, I have to agree with the above.

This map is a really wonderful map, it's balanced, well designed, it's just fantastic all around, from what I've seen.

But we shouldn't merge it without the creator's wishes.

2021-09-03 21:52 UTC, Helianthus00 commented
> I don't know what you have against ERP servers (nor why you would specify that as if we're tainted), but I have to agree that it seems pretty bad faith on the part of the person here to port the map out of spite. We have no plans of merging this any time soon out of respect. Let me confer with my maintainers and get their take as a formality, but we will most likely close this PR.

I am also a Fulpstation admin, as well as mapper. I have nothing personally against ERP servers, but I do have administrative issues with them. I won't go into it here, but I can say I don't hate Skyrat or its community (and especially not the contributors, as prolific and creative as they are) so please don't take that with offense. 

My real issue is the person PRing this and the way they went about it. The whole things with the map more has to do with alterations I find distasteful, which would certainly be necessary for a server like this.

2021-09-03 22:03 UTC, GoldenAlpharex commented
-1
We can port it ourselves at a later date, without doing so in a disrespectful way. I don't support ripping stuff out of somewhere else without even asking first, nor properly crediting them.

Also, porting something out of spite to another codebase while also being extremely condescending about it is never something I could ever support.

A shame, really.

2021-09-03 22:52 UTC, tralezab commented
sergei is really toxic in the tg community as well i suggest sending this spiteful man packing

2021-09-03 23:50 UTC, KathyRyals commented
EXTREMELY good map, superb asthetics, I am genuinely interested in porting it to /tg/ if anyone would be so kind as to give me Helianthus00 discord handle to talk about it first. I'm Cimika on the tg cord.

2021-09-04 00:18 UTC, LemonInTheDark commented
Good map, needs more airlocks.

Stop being a cock serge It'll get you nowhere at breakneck speed

2021-09-04 03:16 UTC, sergeirocks100 commented
I may as well try to address the shit stew that i boiled for myself.

First, lets talk about Fulp's allegations and concerns.

Selene/Serene is not really unique in terms of me spelling things wrong on purpose, i actually do it with a few other things, such as spelling GAGS as "GAS", and spelling Ervin Bransfield's name as "Erwin".

It actually originated as a honest misremembering of the map's name, until it entered my lexicon of things i say wrong on purpose.

However, if it truly does bother the people responsible for the map in question, i will start calling it by its proper name.

I had no clue at all that the map's creator had replied to the PR, as i stopped looking at it after i merged it.

Being that the map was CC-BY-SA, i didn't think i would have to ask for permission to use the map, or even that the author would have cared that i used the map without asking him.

Had i known that the creator would have been displeased had i not, i would have asked for permission first.

Anyways, now lets get on to the story of how i ended up porting the map to Skyrat in the first place.

From pretty much the moment i had managed to open the map on StrongDMM, i had noticed quite a few design decisions that i didn't think were very good, such as the permabrig and brig being halfway across the station from eachother, which caused me to have a low opinion of the map.

I also was not a fan of Skyrat as a codebase very much, mostly because it had a lot of things that i disliked on /tg/, which Skyrat is a direct downstream of, and some other things i disliked on Skyrat's side.

Therefore, i decided i would try to port Selene to Skyrat, and see how what i thought was a bad map fared on Skyrat.

I saw a map like Outpost get merged successfully on Skyrat, so i figured that Selene wouldn't fare all that badly here.

So i went ahead, spent about a hour of initial work or so to get the map to Skyrat mapping standards, and then i made the PR.

As Fulp said, i had forgotten to credit the map's creator properly on the PR, but that was a mistake on my end, and Golden fixed it for me.

To my utter surprise, the map was not only tolerated, but praised.

It had even gotten test merged just 7 hours after i made the PR.

I then spent the next day or two in a state of disbelief that the map had actually fared well, and i spent a little while fixing bugs on the map that people had alerted to me, all the while, talking about, in probably harsher words than i should have, the goings on with the map on the Manuel discord.

Then Fulp brought all of my fuckups into the public light, and you know the story from there.

For all that has happened, i do think that i owe some apologies.

I apologize to Helianthus, for not asking for his permission, not properly crediting him, misspelling the name of his map on purpose, and insulting the map.

I apologize to Skyrat as a community, for trying to port a map that i thought they would dislike to the codebase, even if they actually liked it, and provided helpful feedback for how to improve it.

And finally, i think i should apologize to Fulpstation, for the stuff i did to Helianthus, a admin and contributor for them.

I won't be closing this PR, as people actually liked the map, however troubled its past may be, and i want to leave the map's fate in the hands of the Skyrat development staff.

2021-09-04 23:33 UTC, KasparoVy commented
The end of this comment section feels net-neutral
The map is awesome and hopefully all the contribution/respect/courtesy issues can be resolved. Np if it doesn't get in, the work of the OG authors is greatly appreciated either way

Had no idea this was a Fulpstation map until now, seems like one many folks would enjoy

2021-10-13 20:08 UTC, Gandalf2k15 commented
Given that we have too many maps as it is, we will not be adding this one.

2021-10-13 20:08 UTC, closed without merging