[Non modular] Small booze changes to make it more sensible
Skyrat-SS13/Skyrat-TG pull request #795
Opened 2020-09-14 08:17 UTC by Azarak

## About The Pull Request
Now you get drunk 60% slower, but your drunkiness decays around 300% slower. Allowing people to get smashed after a proper amount of alcohol, not just one glass, but also making so the alcohol persists through a long duration of time.
This is the change we've had before and before

## Why It's Good For The Game
more RP friendly drunkiness

## Changelog
:cl:
/:cl:

2020-09-14 19:30 UTC, Gandalf2k15 commented
Perhaps an upstream change?

2020-09-15 00:33 UTC, Azarak commented
> 
> 
> Perhaps an upstream change?

TG rounds end up being quite short most often than not, not sure if this is something they'd like

2020-09-18 14:03 UTC, Gandalf2k15 requested changes

2020-09-18 14:03 UTC, Gandalf2k15 commented on code/modules/mob/living/carbon/life.dm
> -		drunkenness = max(drunkenness - (drunkenness * 0.04) - 0.01, 0)
Remember to have original

2020-09-18 15:06 UTC, Azarak commented on code/modules/mob/living/carbon/life.dm
> -		drunkenness = max(drunkenness - (drunkenness * 0.04) - 0.01, 0)
done!

2020-09-19 23:56 UTC, merged