[Modular] Chameleon Mutation Fix
Skyrat-SS13/Skyrat-TG pull request #7952
Opened 2021-09-03 14:57 UTC by Snakebittenn

## About The Pull Request
It accidentally made you slightly more invisible than 255 if you clicked on stuff. Now it don't.

## How This Contributes To The Skyrat Roleplay Experience
Allows me to stop facing existential dread about how I occasionally become slightly transparent when I'm using this mutation.

## Changelog
:cl:
fix: Fixes a minor bug with chameleon mutation and transparency.
/:cl:

2021-09-03 23:19 UTC, GoldenAlpharex requested changes
I'm sorry, I didn't do my job at reviewing your previous PR properly, so there might be a bit more work involved in this PR.

2021-09-03 23:19 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +		return //SKYRAT EDIT END
```suggestion
	/// SKYRAT EDIT BEGIN
	if(HAS_TRAIT(owner,TRAIT_CHAMELEON_SKIN))
		return 
	/// SKYRAT EDIT END
```

2021-09-03 23:19 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +/obj/effect/proc_holder/spell/self/chameleon_skin_activate/cast(list/targets, mob/user = usr) //SKYRAT EDIT BEGIN
If those two procs are self-contained, then they should be moved to modular. Man, I really wasn't awake when I reviewed that last PR, my apologies.

2021-09-03 23:19 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
>  /datum/mutation/human/chameleon/on_life(delta_time, times_fired)
Same as previous comment

2021-09-03 23:19 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +	if(HAS_TRAIT(owner, TRAIT_CHAMELEON_SKIN)) //SKYRAT EDIT BEGIN
```suggestion
	/// SKYRAT EDIT BEGIN
	if(HAS_TRAIT(owner, TRAIT_CHAMELEON_SKIN))
```

2021-09-03 23:19 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +		owner.alpha = 255 //SKYRAT EDIT END
```suggestion
		owner.alpha = 255
		/// SKYRAT EDIT END
```

2021-09-03 23:19 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +		owner.alpha = 255 //SKYRAT EDIT END
```suggestion
	/// SKYRAT EDIT BEGIN
	if(HAS_TRAIT(owner, TRAIT_CHAMELEON_SKIN))
		owner.alpha = CHAMELEON_MUTATION_DEFAULT_TRANSPARENCY
	else
		owner.alpha = 255
	/// SKYRAT EDIT END
```

2021-09-04 01:07 UTC, GoldenAlpharex requested changes
One last nitpick.

2021-09-04 01:07 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +		owner.alpha = max(owner.alpha - (12.5 * delta_time), 0) //SKYRAT EDIT END
```suggestion
	/// SKYRAT EDIT BEGIN
	if(HAS_TRAIT(owner, TRAIT_CHAMELEON_SKIN))
		owner.alpha = max(owner.alpha - (12.5 * delta_time), 0)
	/// SKYRAT EDIT END
```

2021-09-04 01:41 UTC, Snakebittenn commented
;w;

2021-09-04 14:07 UTC, GoldenAlpharex requested changes

2021-09-04 14:07 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +	action_icon_state = "ninja_cloak" //SKYRAT EDIT END
That needs to be modularized too ;)

2021-09-04 19:30 UTC, GoldenAlpharex approved these changes
Good work. We got there at the end.

2021-09-04 19:30 UTC, GoldenAlpharex commented on code/datums/mutations/chameleon.dm
> +	power = /obj/effect/proc_holder/spell/self/chameleon_skin_activate //SKYRAT EDIT END
I'll commit this myself, it'll be faster.
```suggestion
	 /// SKYRAT EDIT BEGIN
	instability = 35
	power = /obj/effect/proc_holder/spell/self/chameleon_skin_activate
	/// SKYRAT EDIT END
```

2021-09-04 19:57 UTC, GoldenAlpharex commented
At long last.

2021-09-04 19:57 UTC, merged