[SEMI-MODULAR] Gunpointing! Similar to bay-aiming
Skyrat-SS13/Skyrat-TG pull request #800
Opened 2020-09-14 09:46 UTC by Azarak

## About The Pull Request
This is pretty much the gunpointing we've had before. Had to add an extra trait and signals and stuff, also the "direct" variable for radios.

## Why It's Good For The Game

## Changelog
:cl:
/:cl:

2020-09-14 23:13 UTC, Gandalf2k15 requested changes

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/_onclick/hud/radial.dm
> +			new_element.icon = icon_path //SKYRAT CHANGE - module GUNPOINT
//SKYRAT EDIT ADDITION - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/_onclick/hud/radial.dm
> +	var/icon_path = 'icons/mob/radial.dmi' //SKYRAT CHANGE - module GUNPOINT
//SKYRAT EDIT ADDITION - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/_onclick/item_attack.dm
> +	SEND_SIGNAL(user, COMSIG_MOB_ITEM_ATTACK_SELF, src) //SKYRAT EDIT - module GUNPOINT - extra signal
//SKYRAT EDIT ADDITION - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/game/objects/items/devices/radio/headset.dm
> +/obj/item/radio/headset/talk_into(mob/living/M, message, channel, list/spans, datum/language/language, list/message_mods, direct = TRUE) //SKYRAT EDIT - module GUNPOINT - adds direct variable
///obj/item/radio/headset/talk_into(mob/living/M, message, channel, list/spans, datum/language/language, list/message_mods) - ORIGINAL
/obj/item/radio/headset/talk_into(mob/living/M, message, channel, list/spans, datum/language/language, list/message_mods, direct = TRUE) //SKYRAT EDIT CHANGE - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/game/objects/items/devices/radio/radio.dm
> +/obj/item/radio/talk_into(atom/movable/M, message, channel, list/spans, datum/language/language, list/message_mods, direct = TRUE) //SKYRAT EDIT - module GUNPOINT - adds direct variable
///obj/item/radio/talk_into(atom/movable/M, message, channel, list/spans, datum/language/language, list/message_mods) - ORIGINAL
/obj/item/radio/talk_into(atom/movable/M, message, channel, list/spans, datum/language/language, list/message_mods, direct = TRUE) //SKYRAT EDIT CHANGE - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/game/objects/items/devices/radio/radio.dm
> +	SEND_SIGNAL(M, COMSIG_MOVABLE_RADIO_TALK_INTO, src, message, channel, spans, language, direct) //SKYRAT EDIT - module GUNPOINT - extra signal
//SKYRAT EDIT ADDITION - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/game/objects/items/devices/radio/radio.dm
> +	talk_into(speaker, raw_message, , spans, language=message_language, direct=FALSE) //SKYRAT EDIT - module GUNPOINT - differentiate between things spoken into radios directly vs overheard by an interc
//	talk_into(speaker, raw_message, , spans, language=message_language)
	talk_into(speaker, raw_message, , spans, language=message_language, direct=FALSE) //SKYRAT EDIT CHANGE - GUNPOINT - differentiate between things spoken into radios directly vs overheard by an intercom/station-bounced

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/living/carbon/human/examine.dm
> +	//SKYRAT CHANGES BEGIN - module GUNPOINT
//SKYRAT EDIT ADDITION BEGIN - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/living/carbon/human/examine.dm
> +	//SKYRAT CHANGES END
//SKYRAT EDIT ADDITION END

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/living/living.dm
> +		//SKYRAT CHANGES START - module GUNPOINT
//SKYRAT EDIT ADDITION BEGIN - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/living/living.dm
> +		//END OF SKYRAT CHANGES
//SKYRAT EDIT ADDITION END

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/living/living.dm
> +	SEND_SIGNAL(src, COMSIG_LIVING_UPDATED_MOBILITY, mobility_flags) //SKYRAT CHANGE - module GUNPOINT - extra signal
//SKYRAT EDIT ADDITION - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/mob_movement.dm
> +		//SKYRAT EDIT BEGIN - module GUNPOINT
//SKYRAT EDIT ADDITION BEGIN - GUNPOINT

2020-09-14 23:13 UTC, Gandalf2k15 commented on code/modules/mob/mob_movement.dm
> +		//SKYRAT EDIT END
//SKYRAT EDIT ADDITION END

2020-09-14 23:13 UTC, Gandalf2k15 commented on modular_skyrat/modules/gunpoint/readme.md
> +- /mob/proc/toggle_move_intent() - modified
Include file names

2020-09-15 06:03 UTC, Azarak commented
Adressed about everything

2020-09-15 22:32 UTC, Gandalf2k15 approved these changes
Final checks complete and passing. You are go for launch Major Tom.

2020-09-16 02:42 UTC, Gandalf2k15 approved these changes

2020-09-17 01:17 UTC, Gandalf2k15 approved these changes

2020-09-17 01:18 UTC, merged