[SEMI-MODULAR][FIX]Fixes split personality - No more crashing
Skyrat-SS13/Skyrat-TG pull request #8098
Opened 2021-09-10 22:14 UTC by nevimer

## About The Pull Request

Ports the Citadel version of Split Personality, mixed with the modern TG version. Does not crash clients anymore.  It's been broken for months.

## How This Contributes To The Skyrat Roleplay Experience

Split personality works again. 
## Changelog

:cl:

fix: split personality works again

/:cl:

2021-09-10 22:15 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	if(M.stat == DEAD)	//No use assigning people to a corpse
you must put skyrat edit

2021-09-10 22:15 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	RegisterSignal(M, COMSIG_LIVING_DEATH, .proc/revert_to_normal)
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		C.transfer_ckey(stranger_backseat, FALSE)
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	if(prob(3))
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	UnregisterSignal(owner, COMSIG_LIVING_DEATH)
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	qdel(src)
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	if(QDELETED(owner) || (owner.stat == DEAD && !forced) || QDELETED(stranger_backseat) || QDELETED(owner_backseat))
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	if(current_controller == OWNER)
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		free_backseat = stranger_backseat
you must put skyrat edit

2021-09-10 22:16 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(current_backseat, "<span class='userdanger'>You manage to take control of your body!</span>")
you must put skyrat edit

2021-09-10 22:17 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(current_backseat, "<span class='userdanger'>You manage to take control of your body!</span>")
No, this is incorrect. We do not use <span class=''>
only use span_notice() etc.

2021-09-10 22:17 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	free_backseat.ckey = owner.ckey
you must put skyrat edit

2021-09-10 22:17 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	free_backseat.name = owner.name
you must put skyrat edit

2021-09-10 22:17 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		free_backseat.mind = owner.mind
you must put skyrat edit

2021-09-10 22:17 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		free_backseat.computer_id = h2b_id
you must put skyrat edit

2021-09-10 22:17 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		free_backseat.lastKnownIP = h2b_ip
you must put skyrat edit

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		return
you must put skyrat edit

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> -
you must put skyrat edit

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> -
comment out any block of code rather than remove when nonmodular.

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +/mob/living/split_personality/Login()
you must put skyrat edit

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, "<span class='warning'><b>Do not commit suicide or put the body in a deadly position. Behave like you care about it as much as the owner.</b></span>")
you must put skyrat edit

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, "<span class='warning'>You cannot speak, your other self is controlling your body!</span>")
you must put skyrat edit

2021-09-10 22:18 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	return
you must put skyrat edit

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		C.transfer_ckey(stranger_backseat, FALSE)
you must put skyrat edit

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +/datum/brain_trauma/severe/split_personality/brainwashing/on_life()
you must put skyrat edit

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		hearing_args[HEARING_RAW_MESSAGE] = replacetext(message, codeword, "<span class='warning'>[codeword]</span>")
you must put skyrat edit

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, "<span class='notice'>Your activation codeword is: <b>[codeword]</b></span>")
you must put skyrat edit

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		to_chat(src, "<span class='notice'>Your master left you an objective: <b>[objective]</b>. Follow it at all costs when in control.</span>")
you must put skyrat edit

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		to_chat(src, "<span class='notice'>Your master left you an objective: <b>[objective]</b>. Follow it at all costs when in control.</span>")
No, do not do this. Read above message about spans.

2021-09-10 22:19 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, "<span class='notice'>Your activation codeword is: <b>[codeword]</b></span>")
No, do not do this. Read above message about spans.

2021-09-10 22:20 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +		hearing_args[HEARING_RAW_MESSAGE] = replacetext(message, codeword, "<span class='warning'>[codeword]</span>")
No, do not do this. Read above message about spans.

2021-09-10 22:20 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	return
Are you sure removing an argument/parameter is a good idea?

2021-09-10 22:20 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, "<span class='warning'>You cannot speak, your other self is controlling your body!</span>")
No, do not do this. Read above message about spans.

2021-09-10 22:20 UTC, jjpark-kb commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, "<span class='warning'><b>Do not commit suicide or put the body in a deadly position. Behave like you care about it as much as the owner.</b></span>")
No, do not do this. Read above message about spans.

2021-09-11 00:52 UTC, nevimer commented
Closing this for now due to not wanting to be contributing to skyrat until major issues are addressed.

2021-10-07 13:38 UTC, GoldenAlpharex requested changes
Once the concerns are addressed, I'd like this test-merged and stress-tested on the server, because I've got a hunch there might be one or two issues about this.

2021-10-07 13:38 UTC, GoldenAlpharex commented on code/datums/brain_damage/split_personality.dm
> +	to_chat(src, span_warning("You cannot speak, your other self is controlling your body!")) //SKYRAT EDIT
Do all of your SKYRAT EDIT comments like this when it's more than one or two lines. I'm not feeling up to do that for the whole file myself.
```suggestion
	// SKYRAT EDIT START - Fixing split personality
	..()
	to_chat(src, span_notice("As a split personality, you cannot do anything but observe. However, you will eventually gain control of your body, switching places with the current personality."))
	to_chat(src, span_warning("<b>Do not commit suicide or put the body in a deadly position. Behave like you care about it as much as the owner.</b>"))
/mob/living/split_personality/say(message, bubble_type, list/spans = list(), sanitize = TRUE, datum/language/language = null, ignore_spam = FALSE, forced = null)
	to_chat(src, span_warning("You cannot speak, your other self is controlling your body!"))
	// SKYRAT EDIT END
```

2021-10-07 13:38 UTC, GoldenAlpharex commented on code/datums/brain_damage/split_personality.dm
> +/datum/brain_trauma/severe/split_personality/brainwashing/on_life() //SKYRAT EDIT
This removal of arguments is unnecessary, please add them back.

2021-10-07 13:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/mob/mob.dm
> +	// 			client.prefs.chat_toggles ^= CHAT_OOC
If you're not using it, yeet it

2021-10-07 13:49 UTC, nevimer commented on code/datums/brain_damage/split_personality.dm
> +/datum/brain_trauma/severe/split_personality/brainwashing/on_life() //SKYRAT EDIT
> This was tested without, and the functional version did not have them. Will re-add anyways.

2021-12-09 12:22 UTC, hugmeorelse commented
> Once the concerns are addressed, I'd like this test-merged and stress-tested on the server, because I've got a hunch there might be one or two issues about this.

Let's get this TM eventually if it hasn't yet. This has been floating around for a very long while.

2021-12-13 10:52 UTC, Gandalf2k15 commented
This didn't work

2021-12-16 23:54 UTC, Gandalf2k15 commented
This is caused by ambitions which are being scrapped

2021-12-16 23:54 UTC, closed without merging