[NON MODULAR] Vape carts
Skyrat-SS13/Skyrat-TG pull request #8285
Opened 2021-09-20 00:52 UTC by linnpap

## About The Pull Request
Adds a variety of vape carts, which are now the only way to refill vapes.

## Why It's Good For The Game
PLEASe PEALSe PLEASE I JUST NEED VAPE CARTS IN THIS GAME PELASE EIE IJEIJIFEJIOUHEFJIOU FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK FUCK

## Changelog
:cl:
add: Added vape carts
/:cl:

2021-09-20 01:07 UTC, linnpap commented
dear god when did the integration test become 13 minutes long
fuck me

2021-09-20 02:28 UTC, softcerv commented
It might be better to have a separate sub-type of vape that uses this new cartridge system.

2021-09-21 08:21 UTC, YakumoChen requested changes

2021-09-21 08:21 UTC, YakumoChen commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +/obj/item/reagent_containers/vapecart/empty/attackby(obj/item/I, mob/user, params)
use descriptive and obvious names, no single-letter variables

2021-09-21 08:21 UTC, YakumoChen commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +		var/t = stripped_input(user, "What would you like to label the vape cart?", name, null, 53)
as above

2021-10-02 09:42 UTC, linnpap commented
Im So Happy :3

2021-10-10 01:48 UTC, GoldenAlpharex requested changes
Here's what I got for now, after a quick read, man it's getting late.

2021-10-10 01:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +	list_reagents = list(/datum/reagent/drug/nicotine = 50)
I don't understand why this is literally the only non-custom one in this file that's not containing THC. Hard drugs shouldn't be sold in vendors.

2021-10-10 01:48 UTC, GoldenAlpharex commented on code/modules/vending/cigarette.dm
> +		/obj/item/reagent_containers/vapecart/empty = 5,
I'm curious about the reasoning behind this change. Either make it have the empty cart available for sale without being hacked, or put everything behind hacking.

2021-10-10 01:48 UTC, GoldenAlpharex commented on code/modules/uplink/uplink_items.dm
> +
This needs to be modularized, I don't remember where our modular traitor item file is, but put it in there.

2021-10-10 01:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +			to_chat(user, "<span class='notice'>You scribble illegibly on the label of the vape cart!</span>")
Change all of your spans to stuff like this in this file, I'm too tired to suggest them all right now.
```suggestion
			to_chat(user, span_notice("You scribble illegibly on the label of the vape cart!"))
```

2021-10-10 01:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +	list_reagents = list(/datum/reagent/drug/thc = 25, /datum/reagent/medicine/stimulants = 20)
I'm a bit confused as to why this one has more drugs in it than the other ones. This just seems like a very balance-heavy item, if I recall correctly, chemicals are consumed pretty slowly through vapes, no?

2021-10-10 01:48 UTC, GoldenAlpharex commented on code/modules/hydroponics/grown/cannabis.dm
> +	//axed lipolicide, replaced space drugs with thc
What's the point of removing lipolicide?

2021-10-10 01:48 UTC, GoldenAlpharex commented on code/game/objects/items/cigs_lighters.dm
> +			//SKYRAT REMOVAL - VAPE CARTS //reagents.flags |= OPENCONTAINER
SKYRAT EDIT comments should be after commented out lines, not before.

2021-10-10 03:42 UTC, linnpap commented on code/modules/vending/cigarette.dm
> +		/obj/item/reagent_containers/vapecart/empty = 5,
because im pretty sure the main reason the vape itself would be behind hacking was because you could put any chemical you wanted into it, now the only way to do that is with an empty vape cart

2021-10-10 03:50 UTC, linnpap commented on code/modules/hydroponics/grown/cannabis.dm
> +	//axed lipolicide, replaced space drugs with thc
it makes you feel sick whenever you smoke cannabis in game, and is frankly obnoxious

2021-10-10 03:54 UTC, linnpap commented on modular_skyrat/modules/morenarcotics/items/vapecarts.dm
> +	list_reagents = list(/datum/reagent/drug/nicotine = 50)
is thc really "hard" though?

2021-10-13 20:08 UTC, merged