[Semi-modular][wip] Blood-Red hardsuit reskinning + Winterized Syndicate hardsuit reskin
Skyrat-SS13/Skyrat-TG pull request #8390
Opened 2021-09-25 07:14 UTC by Ebin-Halcyon

## About The Pull Request
Adds in two new looking variants of the classic Blood-Red hardsuit, A slick white, black and fur lined suit for everyone that gets their hands on the hardsuit. Pressing Z in hand with it, or enabling the helmet will bring up a radial menu for you to change the skin of the suit. with three choices, The Original look, The Winterized look, and the Winterized look without the leg tassets.

This also replaces the hardsuits in DS-2 + Interdyne with the reskinabble suit so people can choose between the original suit and winter ones.

https://user-images.githubusercontent.com/81479835/134761717-c8289599-9e94-4906-89dd-6873d58471a6.mp4

Since syndie suit code is jank with combat mode/EVA mode there is a 'new' "variant" that has the radial named 'syndi/camo' in the files so if you wanna get the suit that CAN be reskinned into these replace the 'hardsuit/syndi' with 'hardsuit/syndi/camo'.

That being said, corpses of Syndicate commando corpses are given this variant of the hardsuit so space explorers and miners can choose the variant they want if they find a hardsuited corpse. It also replaces the Uplink hardsuit with 'hardsuit/syndi/camo' so traitors can choose to use the original skin, Winterized, or tassetless Winterized. Nuclear operatives all still have their original redsuits only.

https://user-images.githubusercontent.com/81479835/134761880-07f20ac3-b1b2-421a-afca-ce072b3819dc.mp4

Both plantigrade and Digitigrades have custom sprites
EVA Directionals:
![](https://cdn.discordapp.com/attachments/376656352405225477/891217395497197578/unknown.png)

![](https://cdn.discordapp.com/attachments/376656352405225477/891217540607537182/unknown.png)

![](https://cdn.discordapp.com/attachments/376656352405225477/891217629249937438/unknown.png)

![](https://cdn.discordapp.com/attachments/376656352405225477/891217692277739570/unknown.png)

Combat Directionals:
![](https://cdn.discordapp.com/attachments/376656352405225477/891217922268229672/unknown.png)

![](https://cdn.discordapp.com/attachments/376656352405225477/891218034776219658/unknown.png)

![](https://cdn.discordapp.com/attachments/376656352405225477/891218079118413884/unknown.png)

![](https://cdn.discordapp.com/attachments/376656352405225477/891218133187182613/unknown.png)

**THIS IS A DRAFT BECAUSE THE OBJ SPRITES FOR THE RADIAL MENU SHOW UP AS ERRORS (As seen in the videos) IF YOU HAVE ANY IDEA HOW TO FIX THIS, PLEASE SHOOT ME A MESSAGE ON DISCORD: Halcyon#7104**

## How This Contributes To The Skyrat Roleplay Experience

A nicer looking variant of the original already nice looking hardsuit is pretty nice, and people might appreciate being able to run around in something other than the original redsuit.
That and Dead space 3 suits are top notch and I wanted that in game 😩 

## Changelog

:cl:
add: The Syndicate have exported newly designed Winterized Hardsuits for frozen conditions, beware it does not have any better protection.
refactor: A Blood-red Hardsuit variant that can be reskinned has been added in
/:cl:

2021-09-25 14:44 UTC, Fikou commented
why doesnt this just use the alternate skin system that like double barrel shotguns or captain pens have

2021-09-25 19:51 UTC, YakumoChen commented
not really a fan? The hardsuits are iconic. I feel like its too easy to confuse them with the other white hardsuits we currently have (especially the security one that doesn't see action most rounds)

Not to mention they aren't... y'know... _blood red_ anywhere.

2021-09-25 20:17 UTC, bluetshirtguy commented
They already decided to differentiate sec from the syndicate with red and blue, what justifies changing the syndicate red and black to a grey, white and black?

2021-09-26 04:06 UTC, Ebin-Halcyon commented
> why doesnt this just use the alternate skin system that like double barrel shotguns or captain pens have

Tried doing it before with Orion but couldn't get it to work, along with alt-click already being the 'open the cell cover' hotkey I'm a shoddy at best coder and wouldn't be able to make a work around or stuff in already existing code and make it work. Everyone that could help is a bit busy with making the new prefs menu work on SR as well, so I'm shit out of luck.

> not really a fan? The hardsuits are iconic. I feel like its too easy to confuse them with the other white hardsuits we currently have (especially the security one that doesn't see action most rounds)
> 
> Not to mention they aren't... y'know... _blood red_ anywhere. They _need_ to be iconic as the crew is trained to spot the originals and almost everyone who plays ss13 knows what a blood-red hardsuit normally looks like.

There are exactly two white hardsuits in game and in code, one being the security one as you said and the CE's suit. The reskin variant differentiates itself from both of them by having something extremely different, with the tassets on the legs and the bright red spine light in EVA mode, and even then the tassetless version has a different look compared to them in the spine light and how it's designed anyway.
The helmet also is still the same look as the second most iconic part of the hardsuit, the helmet. It's 4 bright red eyes + antennae compared to both the CE's blue Isaac Clarke style slits and the Sec voidsuit's blue mono visor.

Comparisons between the three:

![comparison](https://user-images.githubusercontent.com/81479835/134791505-bab6944f-c5c2-4a6d-8cb6-c3c06ed70131.png)



> They already decided to differentiate sec from the syndicate with red and blue, what justifies changing the syndicate red and black to a grey, white and black?

This isn't removing the original Redsuit nor changing anything else that's Black and red in the Syndicate, and it still has the motif of black and red, just a white, black and a hint of red motif instead. I'm just giving players a choice to look either winterized or original.

A ''''lore'''' friendly way to add it in is also "Yeah we have bases and operatives on winter planets. Let's roll out a suit to help with those conditions."

2021-09-26 04:24 UTC, Ebin-Halcyon commented
> > why doesnt this just use the alternate skin system that like double barrel shotguns or captain pens have
> 
> Tried doing it before with Orion but couldn't get it to work, along with alt-click already being the 'open the cell cover' hotkey I'm a shoddy at best coder and wouldn't be able to make a work around or stuff in already existing code and make it work. Everyone that could help is a bit busy with making the new prefs menu work on SR as well, so I'm shit out of luck.
> 
> > not really a fan? The hardsuits are iconic. I feel like its too easy to confuse them with the other white hardsuits we currently have (especially the security one that doesn't see action most rounds)
> > Not to mention they aren't... y'know... _blood red_ anywhere. They _need_ to be iconic as the crew is trained to spot the originals and almost everyone who plays ss13 knows what a blood-red hardsuit normally looks like.
> 
> There are exactly two white hardsuits in game and in code, one being the security one as you said and the CE's suit. The reskin variant differentiates itself from both of them by having something extremely different, with the tassets on the legs and the bright red spine light in EVA mode, and even then the tassetless version has a different look compared to them in the spine light and how it's designed anyway.
> The helmet also is still the same look as the second most iconic part of the hardsuit, It's 4 bright red eyes + antennae compared to both the CE's blue Isaac Clarke style slits and the Sec voidsuit's blue mono visor.
> 
> Comparisons between the three:
> 
> ![comparison](https://user-images.githubusercontent.com/81479835/134791505-bab6944f-c5c2-4a6d-8cb6-c3c06ed70131.png)
> 
> > They already decided to differentiate sec from the syndicate with red and blue, what justifies changing the syndicate red and black to a grey, white and black?
> 
> This isn't removing the original Redsuit nor changing anything else that's Black and red in the Syndicate, and it still has the motif of black and red, just a white, black and a hint of red motif instead. I'm just giving players a choice to look either winterized or original.
> 
> A ''''lore'''' friendly way to add it in is also "Yeah we have bases and operatives on winter planets. Let's roll out a suit to help with those conditions."

2021-09-26 20:48 UTC, YakumoChen commented
The sprites are not distinctively different aside from the little lights on them and the shape of the helmet.

Again, players are trained, both mechanically and through experience, to report _blood red_ hardsuits. These I feel should be limited to say, interdyne and not general antagonists.

2021-09-27 21:21 UTC, MessoDepresso commented
> why doesnt this just use the alternate skin system that like double barrel shotguns or captain pens have

To be more specific than Halcyons answer, me and them tried this. Its coded with single objects in mind, the suit-helmet combo is two objects. To top it off, all the suit toggling stuff is stored in the helmet, while the altskin stuff would need to be stored in the suit itself (as the helmet isnt always accessible)
It was janky and gross and didnt work regardless; tldr altskin is for single obj, hardsuits are two objs

2021-09-28 03:18 UTC, Ebin-Halcyon commented
> The sprites are not distinctively different aside from the little lights on them and the shape of the helmet.
> 
> Again, players are trained, both mechanically and through experience, to report _blood red_ hardsuits. These I feel should be limited to say, interdyne and not general antagonists.

Fair I suppose, i'll just make it Interdyne DS-2 Specific.

2021-10-12 07:05 UTC, axietheaxolotl commented
based and syndiepilled

2021-10-16 23:51 UTC, Ebin-Halcyon commented
@GoldenAlpharex Mind taking a glance over these and seeing if it's all fine? I should be finished with just about everything.

2021-10-19 02:35 UTC, GoldenAlpharex commented
> @GoldenAlpharex Mind taking a glance over these and seeing if it's all fine? I should be finished with just about everything.

I'm dumb and didn't get the message, hit me up on Discord next time.

2021-10-19 03:05 UTC, Ebin-Halcyon commented
> > @GoldenAlpharex Mind taking a glance over these and seeing if it's all fine? I should be finished with just about everything.
> 
> I'm dumb and didn't get the message, hit me up on Discord next time.

Gotcha

2021-10-29 17:10 UTC, axietheaxolotl requested changes
Don't start non-proper nouns (Winterized) with capitals in item names, it looks fucky in game

2021-10-29 17:10 UTC, axietheaxolotl commented on modular_skyrat/modules/Winter-hardsuit/code/clothing/suit/winter_hardsuit.dm
> +	name = "Winterized Syndicate hardsuit helmet"
yoyo

2021-10-29 17:10 UTC, axietheaxolotl commented on modular_skyrat/modules/Winter-hardsuit/code/clothing/suit/winter_hardsuit.dm
> +	name = "Winterized Syndicate Hardsuit"
Same here.

2021-10-29 17:10 UTC, axietheaxolotl commented on modular_skyrat/modules/Winter-hardsuit/code/clothing/suit/winter_hardsuit.dm
> +	name = "Winterized Syndicate hardsuit helmet"
weh

2021-10-29 17:10 UTC, axietheaxolotl commented on modular_skyrat/modules/Winter-hardsuit/code/clothing/suit/winter_hardsuit.dm
> +	name = "Winterized Syndicate Hardsuit"
guh

2021-10-31 22:47 UTC, merged