feeshy's fucking cursed donator plushie.
Skyrat-SS13/Skyrat-TG pull request #8620
Opened 2021-10-05 05:20 UTC by capsaicinz

## About The Pull Request

fuck this. fuck this plushie, fuck everything about it, fuck everything to do with it, fuck anything that WILL do with it.

## How This Contributes To The Skyrat Roleplay Experience

it took years off my life.

## Changelog
:cl:
add: added odd lizzy plushie.
/:cl:

del: removed my will to live to age 30.

2021-10-05 05:21 UTC, Kapu1178 commented
post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite post the sprite

2021-10-05 05:24 UTC, capsaicinz commented
![](https://gifmaker.me/files/download/home/20211004/18/0zjj5hX2rLJ6Fi0AHsfti8/output_BU2NYc.gif)

2021-10-05 05:24 UTC, axietheaxolotl commented
![image](https://user-images.githubusercontent.com/86872535/135965154-977f84d2-ce01-4e80-9269-b9d7b1b334ff.png)

2021-10-05 05:25 UTC, capsaicinz commented
![output_BU2NYc](https://user-images.githubusercontent.com/84609863/135965278-a9e7612f-7aec-49eb-92be-4d7660806823.gif)

2021-10-05 05:25 UTC, Kapu1178 commented
OH GOD OH FUCK

2021-10-05 12:17 UTC, capsaicinz commented
i'm gonna need to fix some stuff on this later because feesh wants a new description and it STILL isn't passing checks :")

2021-10-05 19:59 UTC, linnpap requested changes

2021-10-05 19:59 UTC, linnpap commented on modular_skyrat/modules/customization/game/objects/items/plushes.dm
> +	attack_verb_simple = "weh"
```suggestion
	attack_verb_continuous = list("wehs")
	attack_verb_simple = list("weh")
```
should get the integration test to past

2021-10-06 20:31 UTC, GoldenAlpharex approved these changes

2021-10-06 20:31 UTC, GoldenAlpharex commented
The Icon Diff bot had a stroke with that animation, hopefully it's not broken.

2021-10-06 20:32 UTC, merged