Living latex update
Skyrat-SS13/Skyrat-TG pull request #8624
Opened 2021-10-05 14:46 UTC by Lamella-0587

Living latex update is a 1.2 patch of organic-interface-update that was merged a couple of months ago. This update will add a lot of new content to the game. Kit with new instruments to create a latex suit that you want. Fully customizable living latex suit that can be removed only by spraying special dissolving liquid on character, new animations, and even new ghost-role. If you customized a latex suit to have special personal AI - you can request one! PAI in the suit can control functions and talk with the wearer, providing new interesting experiences of roleplay. 

We're planning to spend 3-4 months on this update, but you can speed up our work with financial support on Patreon. 
https://www.patreon.com/lamella

And finally, some of our developments.

![latex_box2](https://user-images.githubusercontent.com/76873041/136045711-cbda166c-3b9b-431d-adcd-e78f1ac5972f.png)

![latex_box2_op](https://user-images.githubusercontent.com/76873041/136045755-f221a9f1-a012-4621-b8c0-542ec4184222.png)

![latex_coating_front3](https://user-images.githubusercontent.com/76873041/136045772-1582e644-141d-47c6-ac64-4fca5455cc47.gif)

![blacc](https://user-images.githubusercontent.com/76873041/136045789-5ab0e27f-51cc-4bac-8c2c-6cad79f459f5.gif)

2021-10-05 15:22 UTC, Yawet330 commented
Remove the PAI's ability to control the user in any way useful, and then it'll be accepted.

We do not want another 'RIG' incident where PAI's could control dead/crit bodies to move them about and to safety.

This was not fun.

2021-10-05 15:36 UTC, Lamella-0587 commented
> Remove the PAI's ability to control the user in any way useful, and then it'll be accepted.
> 
> We do not want another 'RIG' incident where PAI's could control dead/crit bodies to move them about and to safety.
> 
> This was not fun.

The PAI that we're going to use have nothing similar with existing ones. Ours will require ghost role and this ghost can only use toys or speak with wearer, nothing else.

2021-10-05 22:35 UTC, axietheaxolotl commented
SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3 SEX 3

2021-10-07 16:18 UTC, faaaay commented
This seems interesting, but I think it may be good to have _some_ "OOC escape" option if someone forces you into the suit. Unless I'm misunderstanding, it can be put on you and then you _need_ a specific item to get it off?

2021-10-07 22:37 UTC, CandleJaxx commented
oh hell yeah, not even meming, this is good shit- will be used on my latex slime girl for ultimate rp

2021-10-08 00:32 UTC, KathyRyals requested changes

2021-10-08 00:32 UTC, KathyRyals commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/kink_collars.dm
> +		return
Use early returns.

2021-10-08 00:32 UTC, KathyRyals commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/kink_collars.dm
> +		return
This goes for literally every if(condition)else return in your PR.

2021-10-08 00:40 UTC, optimumtact commented
wanna be my coder gf?

2021-10-08 18:41 UTC, Iamgoofball commented on code/modules/cargo/packs.dm
> +/datum/supply_pack/vending/lustwish
No. Modular folder this.

2021-10-08 18:41 UTC, Iamgoofball commented on modular_skyrat/modules/modular_items/lewd_items/code/arousal_system.dm
> +	duration = 900 SECONDS
Use MINUTES here. Also, what the hell. This is way too long.

2021-10-08 18:42 UTC, Iamgoofball commented on modular_skyrat/modules/modular_items/lewd_items/code/arousal_system.dm
> +	duration = 10 MINUTES
Why?

2021-10-08 19:02 UTC, Lamella-0587 commented on modular_skyrat/modules/modular_items/lewd_items/code/arousal_system.dm
> +	duration = 10 MINUTES
because :Р

Actually, we tested it in-game and I changed it because it doesn't work as we wanted, so yeah.

2021-10-08 19:02 UTC, Lamella-0587 commented
> wanna be my coder gf?

Nah, i'm spriter

2021-10-08 19:03 UTC, Lamella-0587 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/kink_collars.dm
> +		return
> This seems interesting, but I think it may be good to have _some_ "OOC escape" option if someone forces you into the suit. Unless I'm misunderstanding, it can be put on you and then you _need_ a specific item to get it off?

This is a good idea, actually, we will think about it's implementation

2021-10-08 19:06 UTC, Fikou commented
wanna be my spriter gf?

2021-10-28 02:08 UTC, gonenoculer5 commented
Any idea how soon this'll be done outta curiousity?

2021-10-28 19:05 UTC, Echopsychotic commented
will the suit be able to control the body? or is it more similar to that of a sentient blade/scythe

2021-11-11 17:13 UTC, softcerv commented
> 
> 
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 5 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself.

lmao, are they seriously able to just close drafts?

2021-11-27 13:01 UTC, tf-4 commented
Please don't have any comments in Russian. It needs to be English only.

2021-11-29 13:31 UTC, Lamella-0587 commented
It's work in progress, we will make comments in russian. Final version wouldn't have these.

2021-11-29 16:50 UTC, twilightwanderer commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/livinglatex.dm
> +/// Тело:
Don't forget to translate this.

2021-12-09 12:25 UTC, hugmeorelse commented
Removing stale.

2021-12-09 12:26 UTC, hugmeorelse commented
Drafts probably shouldn't go stale, @Gandalf2k15

2021-12-27 14:38 UTC, tf-4 commented
While there's been some tolerance to how stale this is, it's been a month since the last commit. Feel free to reopen when ready to start working on this again.

2021-12-27 14:38 UTC, closed without merging