Migrates SEVA away from explorer subtype
Skyrat-SS13/Skyrat-TG pull request #8631
Opened 2021-10-05 21:53 UTC by gonenoculer5

## About The Pull Request
Migrates the SEVA Suit from /obj/item/clothing/suit/hooded/explorer/seva to /obj/item/clothing/suit/hooded/seva and make appropriate migrations of code from explorer to ensure it inherits the correct temperature flags and such, to prevent inconsistancies.
## How This Contributes To The Skyrat Roleplay Experience
N/A
## Changelog

:cl: Gonenoculer5
balance: SEVA suits no longer accept goliath plates, as was intended by the original PR author. Dont shoot the messenger.
fix: A recent factory mixup in the core worlds made it so that SEVA suits were comming with plate hooks for enviromental suits. Centcom has corrected this, and as such SEVA suits are now back to their manufactuing spec.
refactor: Relocated SEVA from explorer subtype to its own, to avoid inheriting plate addition from the hooded/explorer/XYZ subtype.
/:cl:

2021-10-05 21:57 UTC, gonenoculer5 commented
(This was tested thoroughly on a private server, it is appropriately fireproof, does not burn, you can walk in lava for a second and get a full firestack to test. Standing in a storm results in no damage as intended. Woo.)

2021-10-05 23:18 UTC, Iamgoofball commented
:-1:

Remove the SEVA suit and make it a cosmetic subtype of the default mining outfit.

2021-10-06 01:40 UTC, gonenoculer5 commented
> 👎
> 
> Remove the SEVA suit and make it a cosmetic subtype of the default mining outfit.

It serves a genuine purpose though. I see no reason to remove it.

2021-10-06 20:25 UTC, GoldenAlpharex commented
Lol, this isn't big enough to be a refactor.

2021-10-06 20:29 UTC, GoldenAlpharex approved these changes
So whoever ported it didn't add the code for the added stun duration for this suit?

Other than that, the code looks alright.

2021-10-06 20:30 UTC, GoldenAlpharex commented
Also, update from master before we merge, so it runs the GBP action.

2021-10-06 20:34 UTC, gonenoculer5 commented
> So whoever ported it didn't add the code for the added stun duration for this suit?
> 
> Other than that, the code looks alright.

Yeah because it was ported from cit(?), and the original porter did not carry over the trait. According to cold it was intended to have a trait added called goliath_stun or something that would extend the stun duration, as it does on citbase, but it was never implemented. I could come back at a later date and add it, maybe. I'm not super familiar with trait code but supposedly its easy.

2021-10-06 20:35 UTC, gonenoculer5 commented
> Also, update from master before we merge, so it runs the GBP action.

This was made off my personal repo that had just been created that day, but then again I think cobalt fixed the GBP that day too so I probably have to update my master anyway.

2021-10-06 20:36 UTC, gonenoculer5 commented
> Lol, this isn't big enough to be a refactor.

Also whoops my bad. Yes this was intended to be a code improvement not a refactor!

2021-10-06 20:39 UTC, gonenoculer5 commented
> Also, update from master before we merge, so it runs the GBP action.

Done!

2021-10-06 20:43 UTC, GoldenAlpharex commented
You didn't push you dork ;)

> > Also, update from master before we merge, so it runs the GBP action.
> 
> Done!

2021-10-06 21:03 UTC, SpaceVampire commented
I feel like you should add the whole easily grabbed by goliath trait as a part of this PR, if you are already tweaking it.
If only because I doubt it is really going to get done otherwise, but that is just my two cents.

2021-10-06 21:07 UTC, gonenoculer5 commented
> I feel like you should add the whole easily grabbed by goliath trait as a part of this PR, if you are already tweaking it. If only because I doubt it is really going to get done otherwise, but that is just my two cents.

Unfortunately its more of a time thing than an interest thing, I would much rather push this fix/improvement now and return to it when I have time for the rest. Cold said the goliath stun time extention wasnt essential to it and it could always be added later.

2021-10-06 21:08 UTC, GoldenAlpharex commented
> > I feel like you should add the whole easily grabbed by goliath trait as a part of this PR, if you are already tweaking it. If only because I doubt it is really going to get done otherwise, but that is just my two cents.
> 
> Unfortunately its more of a time thing than an interest thing, I would much rather push this fix/improvement now and return to it when I have time for the rest. Cold said the goliath stun time extention wasnt essential to it and it could always be added later.

To be fair, it's not critical or time-sensitive, so even if you take a week to do it, it would make it better than just having it be done by someone at a later date and everyone shooing them for it.

2021-10-06 21:14 UTC, gonenoculer5 commented
> > > I feel like you should add the whole easily grabbed by goliath trait as a part of this PR, if you are already tweaking it. If only because I doubt it is really going to get done otherwise, but that is just my two cents.
> > 
> > 
> > Unfortunately its more of a time thing than an interest thing, I would much rather push this fix/improvement now and return to it when I have time for the rest. Cold said the goliath stun time extention wasnt essential to it and it could always be added later.
> 
> To be fair, it's not critical or time-sensitive, so even if you take a week to do it, it would make it better than just having it be done by someone at a later date and everyone shooing them for it.

Eh just go ahead and merge it. I have to take time to poke and look at traits and ask azarak a few questions since he made the suggestion.

2021-10-08 10:13 UTC, gonenoculer5 commented
No longer fully modular because it has to edit code for goliaths.

2021-10-11 03:09 UTC, gonenoculer5 commented
@GoldenAlpharex So is this set to go? Its all ready and been tested, if someone wants to adjust the timing from higher than what it is, feel free. Its set to 12 seconds right now afaik.

2021-10-14 00:25 UTC, GoldenAlpharex requested changes
Just move those numbers to be defines and this should be good to go. Sorry for taking so long.

2021-10-14 00:25 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +			L.Stun(100)
These numbers should be defines.

2021-10-15 16:27 UTC, GoldenAlpharex approved these changes
Going to commit my suggestions and then probably merge this once CI passes.

2021-10-15 16:27 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +#define GOLIATH_STUN_TIME_SEVA 12 SECONDS
```suggestion
#define GOLIATH_STUN_TIME_SEVA 12 SECONDS //SKYRAT EDIT - SEVA Fix
```

2021-10-15 16:27 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +			L.Stun(100)
```suggestion
		 //SKYRAT EDIT START - GOLIATH STUN TIME FOR SEVA
		if(HAS_TRAIT(L,TRAIT_GOLIATH_STUN))
			L.Stun(GOLIATH_STUN_TIME_SEVA)
		else
			L.Stun(100)
		//SKYRAT EDIT END
```

2021-10-15 16:35 UTC, gonenoculer5 commented
pfft why is CI not passing now

2021-10-18 15:25 UTC, GoldenAlpharex requested changes

2021-10-18 15:25 UTC, GoldenAlpharex commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +		//SKYRAT EDIT END
There's mixed indentations here and that's what's messing up the linters. Check this in VSC and make sure it's all just tabs.

2021-10-19 22:13 UTC, gonenoculer5 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +		//SKYRAT EDIT END
It should be. I dont do anything BUT tab indentations. One moment.

2021-10-19 22:14 UTC, gonenoculer5 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +		//SKYRAT EDIT END
Yeah. Everything in here is indented with tabs.

2021-10-24 16:38 UTC, GoldenAlpharex approved these changes

2021-10-24 18:56 UTC, merged