[Modular] [Bounty Fix] Finally gives botany more fermentation options
Skyrat-SS13/Skyrat-TG pull request #8661
Opened 2021-10-07 14:51 UTC by lyricalpaws

## About The Pull Request
I didn't know what was causing it before, and it took a few months of sometimes prodding at it, but I've finally fixed it. Plants can be distilled in to a lot of new options now, instead of "X Wine". 

![dreamseeker_EVVEy5eihT](https://user-images.githubusercontent.com/26838744/136409238-c995f0a3-2d9c-4de8-b029-db6c5922f552.png)

## How This Contributes To The Skyrat Roleplay Experience
Fixes a problem with a bounty I took. I kept to my word of fixing my own bugs with the bounty.

## Changelog

:cl:
fix: Plants distill in to their distill reagents properly.
/:cl:

2021-10-07 15:13 UTC, Iamgoofball requested changes

2021-10-07 15:13 UTC, Iamgoofball commented on tgstation.dme
> +#include "modular_skyrat\modules\morefermentplants\code\modules\hydroponics\grown\nettle.dm"
i believe you forgot to add all these files to the actual commit

2021-10-07 15:16 UTC, lyricalpaws commented on tgstation.dme
> +#include "modular_skyrat\modules\morefermentplants\code\modules\hydroponics\grown\nettle.dm"
No, they existed already. They just weren't referenced in the dme. That was the reason distillation wasn't working properly and making wines still.

2021-10-07 15:16 UTC, lyricalpaws commented on tgstation.dme
> +#include "modular_skyrat\modules\morefermentplants\code\modules\hydroponics\grown\nettle.dm"
https://github.com/Skyrat-SS13/Skyrat-tg/tree/master/modular_skyrat/modules/morefermentplants/code/modules/hydroponics/grown

2021-10-07 16:39 UTC, GoldenAlpharex requested changes
If we can avoid modifying like 27 of those 29 files, it'd be nice, y'know.

2021-10-07 16:39 UTC, GoldenAlpharex commented on code/modules/hydroponics/grown/ambrosia.dm
> +	//wine_power = 30 //SKYRAT EDIT - REMOVAL: Given distill_reagent in morefermentplants
Okay, but can't you just override what this was doing previously so it just doesn't get used, instead of commenting it out everywhere?

2021-10-07 16:40 UTC, lyricalpaws commented on code/modules/hydroponics/grown/ambrosia.dm
> +	//wine_power = 30 //SKYRAT EDIT - REMOVAL: Given distill_reagent in morefermentplants
Tried testing without removing wine power, it still made X wine rather than reagents. It made reagents when I changed it. But whatever you say boss

2021-10-08 12:27 UTC, GoldenAlpharex commented
@lyricalpaws Uh, am I stupid or is there no change to the fermentation options stuff? It seems like you just uncommented the stuff I asked to uncomment (which is good).

2021-10-08 12:42 UTC, lyricalpaws commented
> @lyricalpaws Uh, am I stupid or is there no change to the fermentation options stuff? It seems like you just uncommented the stuff I asked to uncomment (which is good).

Like I told goof, the code for fermenting stuff exists already, the files just weren't checked

https://github.com/Skyrat-SS13/Skyrat-tg/tree/master/modular_skyrat/modules/morefermentplants/code/modules/hydroponics/grown

2021-10-08 12:43 UTC, GoldenAlpharex commented
Oh, lmao.

2021-10-08 12:43 UTC, GoldenAlpharex approved these changes

2021-10-08 12:43 UTC, merged