[Semi-modular] Adds Teshari
Skyrat-SS13/Skyrat-TG pull request #8663
Opened 2021-10-07 15:55 UTC by NotRanged

## About The Pull Request

For a while, a big problem with porting Teshari has been having to remake all clothing sprites to fit them. However, Shiptest developer MarkSuckerberg came up with a rather genius solution for that which I have ported and applied in this PR. Credits to the clothing system go to him, along with this PR: https://github.com/shiptest-ss13/Shiptest/pull/251

This PR adds the Teshari species, along with:

- Body markings for the chest, arms, and hands
- 14 different ear/hair styles for them, most of which I have converted with much effort to make use of matrixed RGB colouring (more customization wooo)
- 3 different tail styles

As a species, Teshari:

- Have their temperature damage tolerances shifted by -30 degrees (-33C to 37C)
- Take 50% more brute, burn and heat damage
- Take 33% less cold damage
- are smol
- Do reduced unarmed attack damage (range 0 to 6)

Not included in this PR:

- Mob holder code (the thing that lets you pick up and backpack Teshari on some codebases)
- Teshari being able to run over/under tables unhindered
- Xenowear. Custom fitting and properly sprited clothing will have to be added in a different PR, for now /most/ clothing pieces work fine/good enough with the greyscale template clothing system.

Sprites for ears and tails were taken from a mix of Polaris, Vorestation and Arkstation sources, and custom modified by me (over... far too many hours of work) to support multiple colour options with our matrix colouring system.

Sample image along with some common job outfits:
![image](https://user-images.githubusercontent.com/20977204/136420133-3ae35d8b-1d10-4516-8a95-a171ee9c9e12.png)

Additionally includes code in _quirks.dm that allows certain species to be banned from obtaining certain quirks.

## How This Contributes To The Skyrat Roleplay Experience
I'll just add and update current issues in this section as the testmerge procedes.

- Backpacks (not satchels) currently lack a sprite that doesn't clip/float.
- Genitals aren't supported. (idk can't get this to work)
- ~~Cloak sprite looks TOO THICK (imo) and will be shrunk.~~
- ~~I'll probably change the jumpskirt sprite a bit too~~
- ~~The schechi language is not granted by default, and can't be spoken~~
- Changing underwear bluescreens your character creator (I hate tgui I hate tgui)
- ~~Unarmed attacks always miss.~~
- ~~Husked Teshari are invisible.~~

## Changelog

:cl:
add: Added the Teshari species.
add: Added the Schechi language, innate to Teshari but usable by anyone, described as an avian language.
imageadd: Added Teshari bodymarkings, 13 ear variants, and 3 tail variants.
/:cl:

2021-10-07 16:07 UTC, Iamgoofball commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/human_update_icons.dm
> +/mob/living/carbon/human/update_inv_glasses()
These are extremely high-intensity procs to be messing with. Please profile these extensively.

2021-10-07 16:08 UTC, Iamgoofball commented on modular_skyrat/modules/teshari/modules/clothing/clothing.dm
> +/obj/item/clothing
Spin this out to it's own folder, no need for it to be teshari specific.

2021-10-07 16:08 UTC, Iamgoofball commented on modular_skyrat/modules/teshari/modules/language/schechi.dm
> +	icon_state = "lizard"
Needs an icon.

2021-10-07 16:08 UTC, Iamgoofball commented on modular_skyrat/modules/teshari/modules/language/schechi.dm
> +	flags = LANGUAGE_HIDE_ICON_IF_NOT_UNDERSTOOD
See above.

2021-10-07 16:09 UTC, Iamgoofball commented on modular_skyrat/modules/teshari/modules/mob/living/carbon/human/species_types/teshari.dm
> +	// speedmod = -0.25 // no, because people /will/ bitch about balance
Just pull the comment entirely, no need to leave the line in.

2021-10-07 16:09 UTC, Iamgoofball commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/teshari.ts
> +    "Teshari lore TBD. For visual reference, see https://avali.fandom.com/wiki/Art_%26_Concepts (The lore of this wiki does not apply to Teshari.)\
Please don't link directly to these guys, they get really mad at people who use their stuff, especially if people dont use the lore parts.

2021-10-07 16:11 UTC, NotRanged commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/teshari.ts
> +    "Teshari lore TBD. For visual reference, see https://avali.fandom.com/wiki/Art_%26_Concepts (The lore of this wiki does not apply to Teshari.)\
They don't though, that's probably some other furry species you're confusing it with (like Protogen).

2021-10-07 16:15 UTC, Iamgoofball commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/teshari.ts
> +    "Teshari lore TBD. For visual reference, see https://avali.fandom.com/wiki/Art_%26_Concepts (The lore of this wiki does not apply to Teshari.)\
I am positive I got told specifically that the folks who do the Avali wiki are, like, google it 24/7 to yell at people about the lore. Maybe they were wrong?

2021-10-07 16:24 UTC, GoldenAlpharex requested changes
I got a feeling we'll have to talk for a bit, because I'd really like to understand your reasoning for trying to add a whole new greyscale system.

2021-10-07 16:24 UTC, GoldenAlpharex commented on code/controllers/subsystem/traumas.dm
> +		"birds" = typecacheof(list(/datum/species/teshari)) // Skyrat edit - Teshari birds heheh
Wouldn't Voxes be classified as birds too? I can never remember if they're more raptors or more bird-like.

2021-10-07 16:24 UTC, GoldenAlpharex commented on code/modules/clothing/under/_under.dm
> +		greyscale_icon_state = "under_skirt"
```suggestion
	// SKYRAT EDIT START - Teshari skirt
	if(!(body_parts_covered & LEGS))
		greyscale_icon_state = "under_skirt"
	// SKYRAT EDIT END
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on code/modules/mob/living/carbon/human/species.dm
> +	var/list/offset_features = list(OFFSET_UNIFORM = list(0,0), OFFSET_ID = list(0,0), OFFSET_GLOVES = list(0,0), OFFSET_GLASSES = list(0,0), OFFSET_EARS = list(0,0), OFFSET_SHOES = list(0,0), OFFSET_S_
Too lazy to press the shift key SMH
```suggestion
	var/list/offset_features = list(OFFSET_UNIFORM = list(0,0), OFFSET_ID = list(0,0), OFFSET_GLOVES = list(0,0), OFFSET_GLASSES = list(0,0), OFFSET_EARS = list(0,0), OFFSET_SHOES = list(0,0), OFFSET_S_STORE = list(0,0), OFFSET_FACEMASK = list(0,0), OFFSET_HEAD = list(0,0), OFFSET_FACE = list(0,0), OFFSET_BELT = list(0,0), OFFSET_BACK = list(0,0), OFFSET_SUIT = list(0,0), OFFSET_NECK = list(0,0), OFFSET_ACCESSORY = list(0, 0)) // SKYRAT EDIT - OFFSET_ACCESSORY
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/carbon_update_icons.dm
> +	apply_overlay(NECK_LAYER)
So, what's changed here compared to the original code that you commented out in the /tg/ file?

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/human_update_icons.dm
> +/obj/item/clothing/wear_species_version(file2use, state2use, layer, species)
```suggestion
/obj/item/clothing/wear_species_version(file_to_use, state_to_use, layer, species)
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/human_update_icons.dm
> +/obj/item/proc/wear_species_version(file2use, state2use, layer, species)
Respect the snake_case please ;)
```suggestion
/obj/item/proc/wear_species_version(file_to_use, state_to_use, layer, species)
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species.dm
> +	///Override of the eyes icon file, used for Vox and maybe more in the future // The future is now, with Teshari using it too
```suggestion
	///Override of the eyes icon file, used for Vox and maybe more in the future - The future is now, with Teshari using it too
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species.dm
> +	var/species_clothing_path
Thanks for properly documenting your stuff, it's going to be helpful in the future. I'm glad I don't have to come up with a documentation string for this myself ;)

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/clothing.dm
> +	var/greyscale_icon_state
Hold up chief, what's that? We already have GAGS, I'm not sure what you're trying to implement here.

This shouldn't use a different system that's basically the same, go with GAGS, it's more coherent in the grand scheme of things.

Hit me up on Discord if you need help figuring out how to do that.

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/clothing.dm
> +/obj/item/clothing/proc/generate_species_clothing(file2use, state2use, species)
If this stays, please use snake_case for your variable names. And I'd probably name them differently as well, this is just an example. No need to use this exact wording.
```suggestion
/obj/item/clothing/proc/generate_species_clothing(clothing_file, clothing_item_state, species)
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/glasses/_glasses.dm
> +/obj/item/clothing/glasses
This shouldn't exist either.

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/gloves/_gloves.dm
> +/obj/item/clothing/gloves
Same as above. Use GAGS.

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/neck/_neck.dm
> +	greyscale_icon_state = "tie"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/shoes/_shoes.dm
> +	greyscale_icon_state = "shoes"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/spacesuits/_spacesuits.dm
> +	greyscale_icon_state = "spacesuit"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/spacesuits/hardsuit.dm
> +	greyscale_icon_state = "hardsuit"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/suits/_suits.dm
> +	greyscale_icon_state = "coat"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/suits/armor.dm
> +	greyscale_icon_state = "armor"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/suits/cloaks.dm
> +	greyscale_icon_state = "cloak"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/under/_under.dm
> +	greyscale_icon_state = "under"
Ditto

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/language/language_holder.dm
> +							/datum/language/schechi = list(LANGUAGE_ATOM))
This indentation looks really weird, align the `/datum/`s with one-another.

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/language/schechi.dm
> +	flags = LANGUAGE_HIDE_ICON_IF_NOT_UNDERSTOOD
Why would you hide the icon in this situation? This isn't codespeak or anything, it shouldn't hide its icon if people can't understand it.

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/language/schechi.dm
> +	icon_state = "lizard"
I'd consider adding a different icon for that if I were you.

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/mob/living/carbon/human/species_types/teshari.dm
> +	// speedmod = -0.25 // no, because people /will/ bitch about balance
Just yeet this line if you're not using it ;)

2021-10-07 16:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/__DEFINES/teshari.dm
> +#define TESHARI_PUNCH_HIGH 6
Don't put this in a different file, there's not that many. Add them to `modular_skyrat/modules/teshari/modules/mob/living/carbon/human/species_types/teshari.dm`

2021-10-07 16:24 UTC, GoldenAlpharex commented on code/modules/research/nanites/nanite_programs/sensor.dm
> +		"Teshari" = /datum/species/teshari,
This is kinda funny considering how the nanites don't exist anymore, I wonder if this is just a ghost file that we still have that /tg/ doesn't.

2021-10-07 16:24 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/ScannerGate.js
> +    value: 'tesh',
This wouldn't work otherwise, because that's not what your define is in the .dm file ;)
```suggestion
    value: 'teshari',
```

2021-10-07 16:24 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/teshari.ts
> +     Hairstyles likely won't look great on Teshari, it is recommended you stick to the styles built in on the various custom-tailored ear sprites!",
I feel like this would be the perfect moment to try to actually give them lore before they're merged, so we don't have people complaining later when they do get some lore.

2021-10-07 16:29 UTC, NotRanged commented on code/controllers/subsystem/traumas.dm
> +		"birds" = typecacheof(list(/datum/species/teshari)) // Skyrat edit - Teshari birds heheh
adding them

2021-10-07 16:30 UTC, NotRanged commented on modular_skyrat/modules/customization/modules/mob/living/carbon/carbon_update_icons.dm
> +	apply_overlay(NECK_LAYER)
species = dna?.species.species_clothing_path)

so I added it to the modular file where the rest of the similar procs already live

2021-10-07 16:35 UTC, NotRanged commented on code/modules/research/nanites/nanite_programs/sensor.dm
> +		"Teshari" = /datum/species/teshari,
This just goes to show that I haven't played in... A while. I thought they were still in :)

2021-10-07 16:38 UTC, NotRanged commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/teshari.ts
> +     Hairstyles likely won't look great on Teshari, it is recommended you stick to the styles built in on the various custom-tailored ear sprites!",
I'm not writing lore so I am considering that out of scope for this PR to be honest, unless you get something DM'd to me to add here instead.

2021-10-07 16:51 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/teshari.ts
> +     Hairstyles likely won't look great on Teshari, it is recommended you stick to the styles built in on the various custom-tailored ear sprites!",
> I'm not writing lore so I am considering that out of scope for this PR to be honest, unless you get something DM'd to me to add here instead.

I'll talk with Xyel about it.

2021-10-07 16:51 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/carbon_update_icons.dm
> +	apply_overlay(NECK_LAYER)
Gotcha.

2021-10-07 16:52 UTC, NotRanged commented on modular_skyrat/modules/teshari/modules/language/language_holder.dm
> +							/datum/language/schechi = list(LANGUAGE_ATOM))
This looks fine in vscode though

2021-10-07 16:53 UTC, NotRanged commented on modular_skyrat/modules/teshari/modules/language/language_holder.dm
> +							/datum/language/schechi = list(LANGUAGE_ATOM))
https://i.imgur.com/SOTXMlT.png

2021-10-08 19:12 UTC, ZephyrTFA commented
This is an amazing port; but you didn't credit Mark for the entirety of the code. Mark designed the entirety of the code from the ground up and is actually a bit frustrated that you didn't even let them know you were copying their code.
You credited them for the clothing portion but didn't credit them for the entire rest of the Teshari code which they also wrote from scratch. You modified it to work with Skyrat which I'm sure was a lot of work, but it is still clearly based on Mark's original.

TL;DR:
Please let us know you are going to copy our code in the future (if only so we can help you port it)
Give proper credit for all aspects of the code.

2021-10-08 22:48 UTC, NotRanged commented
> This is an amazing port; but you didn't credit Mark for the entirety of the code. Mark designed the entirety of the code from the ground up and is actually a bit frustrated that you didn't even let them know you were copying their code. You credited them for the clothing portion but didn't credit them for the entire rest of the Teshari code which they also wrote from scratch. You modified it to work with Skyrat which I'm sure was a lot of work, but it is still clearly based on Mark's original.
> 
> TL;DR: Please let us know you are going to copy our code in the future (if only so we can help you port it) Give proper credit for all aspects of the code.

The /vast/ majority of the code in this PR is related to that clothing system, which is exactly what I credited him for? What other code is there to accredit, setting the brutemod to 1.5? I guess there's the language but other than that, I don't know what you're talking about, and I even made the icon for that myself. I gave credit where credit is due.

2021-10-09 10:54 UTC, softcerv commented
>I guess there's the language
I feel like you should have also included this in the changelog and description. Anyways, this is going to be a language that anyone can equip, right?

2021-10-10 21:50 UTC, CandleJaxx commented
i feel like this may be better suited via species customization in anthro / such by making their custom snouts / ears / etc instead of editing and porting a whole separate system, but as it is

2021-10-13 11:21 UTC, NotRanged commented
Requested changes have been implemented

2021-10-14 21:34 UTC, ZephyrTFA commented on .github/gbp.toml
> +"Fix" = 4
Hmm

2021-10-14 22:16 UTC, NotRanged commented on .github/gbp.toml
> +"Fix" = 4
lol thanks rebase

2021-10-14 22:17 UTC, NotRanged commented on .github/gbp.toml
> +"Fix" = 4
wait what this is literally not even in this pr

2021-10-18 15:57 UTC, GoldenAlpharex requested changes
So, have you implemented anything to like, allow them to pretty much piggyback on you, but they take your backpack slot and when you click on them, you basically interface with their backpack (with possibly an action button to punt them off or something, I don't think having them in your hands is a good idea for now at the very least). They'd also need to have their hands filled, so they can't do anything else when in backpack mode.

Other than that, did you make any progress on the GAGS part? I remember we talked about it in DMs already, I'm not sure how far you've gotten and if you're still planning to do that.

2021-10-18 15:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/glasses/_glasses.dm
> +	species_clothing_colors = list(list(14, 26), list(17, 26))
What do those numbers mean? They should be defines, not just arbitrary numbers.

2021-10-18 15:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/gloves/_gloves.dm
> +	species_clothing_colors = list(list(10, 13))
Same as previous comment, use defines.

2021-10-18 15:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/teshari/modules/clothing/neck/_neck.dm
> +	species_clothing_colors = list(list(15, 19))
I think you get the point by now.

2021-10-18 17:55 UTC, Low3 commented
Ill note that https://github.com/Skyrat-SS13/Skyrat-tg/pull/3255 exists and has mechanics for picking up humans and putting them in pockets. Maybe it can be fullmerged already and used for teshpack mechanics? Also i will riot if i cant fill my dufflebug with tesharis.

2021-10-19 00:02 UTC, NotRanged commented
> Ill note that #3255 exists and has mechanics for picking up humans and putting them in pockets. Maybe it can be fullmerged already and used for teshpack mechanics? Also i will riot if i cant fill my dufflebug with tesharis.

Stuffing small things into your backpack will come later!

2021-10-19 07:04 UTC, Low3 commented
> > Ill note that #3255 exists and has mechanics for picking up humans and putting them in pockets. Maybe it can be fullmerged already and used for teshpack mechanics? Also i will riot if i cant fill my dufflebug with tesharis.
> 
> Stuffing small things into your backpack will come later!

That's all i wanted to hear.

2021-10-19 20:30 UTC, ArdentSpark commented
Would it be heretical to propose parts of the Teshari to be ported to a quirk instead for players of other species that play very small characters? I.E (none of the temperature stuff, so that small lizards don't break the game) 50% increased damage received, reduced unarmed attacks, whatever table shenanigans Teshari get and the backpack code?

2021-10-19 20:47 UTC, NotRanged commented
They take increased damage to make up for their small sprite size. Perhaps after this PR more functionality will be moved and tied to small sprite sizes (body_size 85 or below or teshari etc)

2021-10-19 20:59 UTC, ArdentSpark commented
Oh for sure. If you're down with the idea I might take a look at it in the future

2021-10-20 19:10 UTC, CypressBz commented
Okay list of clothing stuff here we go!

- Can we get a unique sprite for each type of poly chromatic cloak type things? it'd add more variety than not on account of the suits all being the same but different, and almost every tesh wearing one anyways?
- Gear harnesses also make the whole tesh body black.
- Mining chest rigs show up on their heads
- Helmets and head wear is all offset to the left by a pixel. might be fixable by trimming a single column of pixels out of the center of the hat and moving the remaining pixels right.
- as many of the suits as you feel like doing would be rad, right now they are all a generic lab coat looking thing with a different color. the generic suit also has the issue of sticking out a pixel on all sides of the shoulders and back when you wear a cloak over it.

Some non-clothing related things:

- I know it wasn't mentioned but Tesh also have bits coming out of their chest, as well as ofset to the left by one. which would be cool if that wasn't the case.
- On another note, many of the ears aren't ears are instead hair that's supposed to be used with the ears, but we can't use them both on account of it all being under the ears menu.

2021-10-21 13:17 UTC, NotRanged commented
I genuinely can't deal with the 1-pixel offset of helmets and other things, without like... Making the Teshari base sprite 1 pixel thicker, which would look garbage probably. I'll implement a custom sprite override system for species soon:tm:, so the solution would just be custom helmet sprites.

2021-10-21 13:23 UTC, NotRanged commented
No idea what you mean by 'bits coming out of the chest'. Got an image example? Are you sure it's not just some body marking you still have selected? The teshari characters I've made don't have it.

2021-10-21 17:29 UTC, CypressBz commented
> 
> 
> No idea what you mean by 'bits coming out of the chest'. Got an image example? Are you sure it's not just some body marking you still have selected? The teshari characters I've made don't have it.

By bits, I mean genitalia.

2021-10-26 16:28 UTC, Gandalf2k15 approved these changes
You know why I use FullMerge instead of TestMerge? It's because FullMerge shows conflicts where as TGS always fails.

2021-10-26 16:28 UTC, merged