[SEMI-MODULAR] Brings back custom Ash Walkers and Primal Podpeople, also fixes job banned species checks
Skyrat-SS13/Skyrat-TG pull request #8665
Opened 2021-10-07 17:58 UTC by Lyroy

## About The Pull Request
This re-adds the always_customizable species (Ash Walkers and Primal Podpeople) that were left out of the new preferences menu.
I had to fix the has_banned_species check from jobs and re-add it to the roundstart job distribution as well as latejoin job options to prevent them from just joining the station.
Also prevents them from learning any language not in their learnable_languages list. It's a bit of a hack but I'm expecting an upcoming backgrounds PR to change how that entire thing works.
Also gave ashies a description and some quirks for their race selection. Podpeople have a very barebones one.

This solves #8424.

## How This Contributes To The Skyrat Roleplay Experience
The Ash Walker ghost role brings great opportunities for RP, and it's basically been abandoned since people weren't allowed to play as their characters there.
Oh yeah and Podpeople too but nobody plays that hahah...

## Changelog

:cl:
fix: fixes the has_banned_species proc for jobs
fix: The recent strong storm keeping the Ash Walkers trapped and isolated has finally ended. Miners should be cautious, as the Lavaland natives might start showing up again.
fix: Primal Podpeople have finally managed to exit their cryopods again.
/:cl:

2021-10-07 18:39 UTC, Iamgoofball commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm
> +		if(species.always_customizable && !(language.type in species.learnable_languages)) //For the ghostrole species. We don't want ashwalkers speaking beachtongue now.
Please make sure this doesn't apply to any of the station species.

2021-10-07 18:49 UTC, Lyroy commented on modular_skyrat/master_files/code/modules/client/preferences/middleware/languages.dm
> +		if(species.always_customizable && !(language.type in species.learnable_languages)) //For the ghostrole species. We don't want ashwalkers speaking beachtongue now.
I made sure, it doesn't. The only two species with always_customizable = TRUE are ashwalkers and (primal) podpeople.
No idea why we don't just rename it to ghost_role_species really.

2021-10-07 21:07 UTC, gonenoculer5 commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/ashlizard.ts
> +  description: "The primitive natives of Indecipheres, this race, \
Is this the canon name for Lavaland?

2021-10-07 21:57 UTC, Lyroy commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/ashlizard.ts
> +  description: "The primitive natives of Indecipheres, this race, \
It's the most canon one we have afaik, at least according to the trading card game

2021-10-08 02:22 UTC, GoldenAlpharex requested changes
Looks like some very solid code that I'm happy I didn't have to do myself.

Two questions remain, however:
What does it look like in the Occupations menu when you can't select a job because your race doesn't allow for it?
Could you add a check so that ashwalkers are only used on Ash Walker spawners, and Pod People, on Pod People spawners? Thanks!

2021-10-08 02:22 UTC, GoldenAlpharex commented on code/modules/client/preferences/species.dm
> +	for (var/species_id in (get_selectable_species()+get_customizable_races())) //SKYRAT EDIT CHANGE - ORIGINAL: for (var/species_id in get_selectable_species())
Just to make it more readable.
```suggestion
	for (var/species_id in (get_selectable_species() + get_customizable_races())) //SKYRAT EDIT CHANGE - ORIGINAL: for (var/species_id in get_selectable_species())
```

2021-10-08 02:22 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/mob/living/carbon/human/species.dm
> +/proc/generate_customizable_races()
I love documented procs, thanks a lot!

2021-10-08 02:22 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/pod.ts
> +    good: [],
I feel like the perks of podpeople should be listed here. Also, I'd rename this whole thing to PrimalPodpeople just to make it easier and more straight-forward.

2021-10-08 07:10 UTC, Lyroy commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/pod.ts
> +    good: [],
I'm not too familiar with podpeople perks but I'll try! Can't really rename it though, as the species selection page looks for a .ts file named exactly like the species datum and I'd have to change the datum itself as well.

2021-10-08 07:16 UTC, Lyroy commented
> What does it look like in the Occupations menu when you can't select a job because your race doesn't allow for it?

Right now it looks like normal, nothing has been changed there, so you're able to set your job priorities, it just won't let you qualify for a job on roundstart or latejoin one which I believe was how it worked with the old prefs menu. I could make each job check for banned species when you open the occupations tab, though.

> Could you add a check so that ashwalkers are only used on Ash Walker spawners, and Pod People, on Pod People spawners?

I don't quite understand this though. Do you mean like add a check when you use a prefs character on a species-exclusive spawner? This is already the case.

2021-10-08 09:10 UTC, gonenoculer5 commented
> > What does it look like in the Occupations menu when you can't select a job because your race doesn't allow for it?
> 
> Right now it looks like normal, nothing has been changed there, so you're able to set your job priorities, it just won't let you qualify for a job on roundstart or latejoin one which I believe was how it worked with the old prefs menu. I could make each job check for banned species when you open the occupations tab, though.

Originally, the case was that it would grey out every bar on the occupations menu when you selected a non-qualifying race. So if you were an ashwalker for example, you would be unable to take any position on the roster because it was unselectable in the first place. Non-qualifying at roundstart would probably work too, but drawing a vingrete (I think thats the word) over the occupations menu, and saying "Unable to qualify for position due to ineligble species." or something might be a visually pleasant way to handle it.

2021-10-08 09:16 UTC, Lyroy commented
> > Right now it looks like normal, nothing has been changed there, so you're able to set your job priorities, it just won't let you qualify for a job on roundstart or latejoin one which I believe was how it worked with the old prefs menu. I could make each job check for banned species when you open the occupations tab, though.
> 
> Originally, the case was that it would grey out every bar on the occupations menu when you selected a non-qualifying race. So if you were an ashwalker for example, you would be unable to take any position on the roster because it was unselectable in the first place. Non-qualifying at roundstart would probably work too, but drawing a vingrete (I think thats the word) over the occupations menu, and saying "Unable to qualify for position due to ineligble species." or something might be a visually pleasant way to handle it.

A vignette isn't a bad idea but I think checking on a job by job basis and displaying a "Bad species" text instead of the priority selector will be better for future-proofing as opposed to just locking the entire screen, in case we ever end up adding species that can't take specific jobs.

I'll commit it later today.

2021-10-08 11:50 UTC, gonenoculer5 commented
> > > Right now it looks like normal, nothing has been changed there, so you're able to set your job priorities, it just won't let you qualify for a job on roundstart or latejoin one which I believe was how it worked with the old prefs menu. I could make each job check for banned species when you open the occupations tab, though.
> > 
> > 
> > Originally, the case was that it would grey out every bar on the occupations menu when you selected a non-qualifying race. So if you were an ashwalker for example, you would be unable to take any position on the roster because it was unselectable in the first place. Non-qualifying at roundstart would probably work too, but drawing a vingrete (I think thats the word) over the occupations menu, and saying "Unable to qualify for position due to ineligble species." or something might be a visually pleasant way to handle it.
> 
> A vignette isn't a bad idea but I think checking on a job by job basis and displaying a "Bad species" text instead of the priority selector will be better for future-proofing as opposed to just locking the entire screen, in case we ever end up adding species that can't take specific jobs.
> 
> I'll commit it later today.

Sounds good!

2021-10-08 12:25 UTC, GoldenAlpharex commented
Perfect, if you're still working on this, I'll make this a draft.

2021-10-10 01:38 UTC, GoldenAlpharex commented
I'm going to test this in local tomorrow, if I'm satisfied with it as-is I'll undraft and merge.

2021-10-12 20:35 UTC, Lyroy commented
Here's some previews of how it looks right now.

The occupations tab
![jobs menu](https://user-images.githubusercontent.com/57791262/137025276-470e950c-bc9b-4885-a1ff-42c8f55e6402.PNG)

The join menu
![join menu](https://user-images.githubusercontent.com/57791262/137025277-fecad5a6-eb87-4ecc-931d-f6b5e006a593.PNG)

And what it tells you when you join as an ashie
![ash spawn](https://user-images.githubusercontent.com/57791262/137025279-35d9421a-d7b2-497d-9614-49920bb975e9.PNG)
![ash spawn 2](https://user-images.githubusercontent.com/57791262/137025278-d46800a2-8844-47d5-9f2a-5d3c690bec51.PNG)

2021-10-12 23:20 UTC, GoldenAlpharex commented
Give me like an hour and I'm fixing the conflict and merging this bad boy.

2021-10-12 23:20 UTC, GoldenAlpharex commented
Unless you can do it yourself :)

2021-10-13 14:20 UTC, Lyroy commented
> Unless you can do it yourself :)

Done! Feel free to merge whenever.

2021-10-13 19:32 UTC, merged