[MODULAR] Modularises Detective reskins, and adds a blade runner skin
Skyrat-SS13/Skyrat-TG pull request #8667
Opened 2021-10-07 21:52 UTC by axietheaxolotl

## About The Pull Request

Moves Detective reskinning to a modular file, because, yeah. It's better.

Also adds a reskin that looks like the Blaster from Bladerunner 2049

![image](https://user-images.githubusercontent.com/86872535/136467244-ccceb2a1-18e1-4bdd-b3eb-6e37023e7f65.png)

## How This Contributes To The Skyrat Roleplay Experience

no

## Changelog

:cl:
qol: Modularises detective reskin
imageadd: adds Detective Bladerunner 2049 skin
/:cl:

2021-10-08 01:08 UTC, thestubborn commented
wouldnt it be better to submit this sprite upstream?

2021-10-14 00:48 UTC, GoldenAlpharex requested changes
You also need to show it being used in-game.

2021-10-14 00:48 UTC, GoldenAlpharex commented on code/modules/projectiles/guns/ballistic/revolver.dm
> +//						)
This isn't a proper way to comment something. Please follow the contribution guidelines, `/* SKYRAT EDIT - MOVED TO MODULAR (path/to/the/new/thing)` at the start and `*/ // SKYRAT EDIT END` at the end

2021-10-14 00:48 UTC, GoldenAlpharex commented on modular_skyrat/modules/aesthetics/guns/code/guns.dm
> +
This is not mentioned anywhere in the PR body or title. I also would like it to be clear that it can't be reloaded, because that doesn't feel right when I'm looking at the code, I don't see how this wouldn't be able to reload.

2021-10-16 05:24 UTC, axietheaxolotl commented
ugh

2021-11-10 07:10 UTC, dawsonkeyes commented
why not make it the revolver from blade runner
I know you know the one

2021-11-24 00:17 UTC, closed without merging