[nonmodular] runtime fix for cryopods and shoes
Skyrat-SS13/Skyrat-TG pull request #8744
Opened 2021-10-10 16:57 UTC by Seris02

## About The Pull Request

*Runtime in _shoes.dm, line 92: Cannot execute null.clear alert().*

## How This Contributes To The Skyrat Roleplay Experience

it doesn't

## Changelog
N/A

2021-10-11 03:50 UTC, GoldenAlpharex requested changes

2021-10-11 03:50 UTC, GoldenAlpharex commented on code/game/machinery/cryopod.dm
> +			item_content.dropped(mob_occupant)
Needs a SKYRAT EDIT

2021-10-11 05:06 UTC, Seris02 commented on code/game/machinery/cryopod.dm
> +			item_content.dropped(mob_occupant)
it's already inside a skyrat edit you nerd

2021-10-13 00:48 UTC, GoldenAlpharex approved these changes

2021-10-13 00:48 UTC, merged