[MODULAR] Add new decker uniform without the mask
Skyrat-SS13/Skyrat-TG pull request #8762
Opened 2021-10-11 17:28 UTC by Merek2

## About The Pull Request

Adds a decker uniform without the mask to the game. This has been playtested and will work to add it to the clothesmate and add it to the game. This doesn't change any files, it's basically just an alternative outfit of the decker for aesthetic.

![(null)scrnshot1](https://user-images.githubusercontent.com/33470978/137574400-67dcd76b-d26c-49cd-9cac-c2d2f315a21b.png)
![scrnshot1](https://user-images.githubusercontent.com/33470978/137574434-383f039a-2450-4bdb-9856-4d3100c5fe07.png)
![scrnshot2](https://user-images.githubusercontent.com/33470978/137574408-9bd4c39b-9c58-4cba-ac6b-686a5611f61f.png)
![scrnshot3](https://user-images.githubusercontent.com/33470978/137574405-bc61a4bf-79df-47b5-b917-8d5cc5aa3917.png)

Changes clothes
mate to permit purchase.
Changes costume.dm to make sure it is referenced.
costume.dmi for icon and costume.dmi for the wear state are added. These are
 both their own entries.

This will not make any changes to the original deckers outfit, so it won't affect decker antag and any original.

## How This Contributes To The Skyrat Roleplay Experience

Roleplay is good with aesthetic. It shouldn't make any change to roleplay experience that will be that much of an issue. I'd say it's pretty neutral, and mainly for an aesthetic.

## Changelog

:cl:
add: Deckers maskless outfit.
imageadd: Added decking_jumpsuit to two costume.dmi files for icon and wear state.
code: Modified clothesmate to add deckers maskless outfit.
/:cl:

2021-10-11 17:32 UTC, Iamgoofball commented
You gotta make sure to update the digitigrade version too.

2021-10-11 17:35 UTC, Iamgoofball commented
Other than that, :+1:

2021-10-11 22:02 UTC, Merek2 commented
> 
> 
> You gotta make sure to update the digitigrade version too.

Alright! Updated it!

2021-10-11 22:55 UTC, thestubborn commented
this isnt modular, modular means you edited the skyrat files

you edited base tg files

2021-10-11 22:56 UTC, thestubborn commented
other than that the code's good, the sprite's fine for the edit as well

you just need to move it to the modular folders
customization for the clothing, modular vending for the vending and the dmis in masterfiles

2021-10-12 01:20 UTC, Merek2 commented
> 
> 
> other than that the code's good, the sprite's fine for the edit as well
> 
> you just need to move it to the modular folders customization for the clothing, modular vending for the vending and the dmis in masterfiles

I think that I did it right.

2021-10-12 02:53 UTC, Funce commented
You forgot to remove the code and sprites from their old location there.

2021-10-12 03:01 UTC, Merek2 commented
> 
> 
> You forgot to remove the code and sprites from their old location there.

Alright!

2021-10-12 03:02 UTC, Funce commented
Get some pictures in that PR description!~

2021-10-12 03:22 UTC, Merek2 commented
> 
> 
> Get some pictures in that PR description!~

Alright! I did what I could, I am not that great at image.

2021-10-12 06:23 UTC, thestubborn commented on modular_skyrat/modules/customization/modules/clothing/under/costumes.dm
> +
you're gonna need to add
```suggestion
icon = 'modular_skyrat/master_files/icons/obj/clothing/uniforms.dmi'
worn_icon = 'modular_skyrat/master_files/icons/mob/clothing/uniform.dmi'
```
so the outfit actually shows
and, its not a hard requirement, but i'd advise making it a subtype

2021-10-14 03:35 UTC, Merek2 commented
Anything new to add to this? @GoldenAlpharex

2021-10-15 02:50 UTC, GoldenAlpharex requested changes
Also please post **in-game** screenshots of your new outfit being used.

2021-10-15 02:50 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/under/costumes.dm
> +/obj/item/clothing/under/costume/decking
A better name than this would be pretty nice. Also, shouldn't it be a subtype of the `/obj/clothing/suit/deckers`? So that way you wouldn't have to touch `body_parts_covered`?

2021-10-15 05:04 UTC, thestubborn commented on modular_skyrat/modules/customization/modules/clothing/under/costumes.dm
> +/obj/item/clothing/under/costume/decking
i did say that!

better to make it a subtype
other than that it just needs to be unmerge conflicted

2021-10-16 19:09 UTC, GoldenAlpharex approved these changes

2021-10-16 19:09 UTC, merged