[SEMI-MODULAR] Thieving Gloves
Skyrat-SS13/Skyrat-TG pull request #8768
Opened 2021-10-12 03:05 UTC by ZephyrTFA

## About The Pull Request

Adds thieving gloves.
They give you a static 50% speed boost to all stripping, and they also allow you to steal from the pockets and ID slot silently.
They also automatically pickup items you steal, no more dropping onto the floor!

## How This Contributes To The Skyrat Roleplay Experience

Approved Bounty

## Changelog

:cl:
add: Added thieving gloves, which give a boost to stripping speed and also allow you to automatically pickup items you steal.
/:cl:

2021-10-12 03:06 UTC, ZephyrTFA reviewed
oops debug code

2021-10-12 03:06 UTC, ZephyrTFA commented on code/modules/mob/living/living.dm
> +		to_chat(src, "Stripping when user ih human.")
```suggestion
```

2021-10-12 03:06 UTC, ZephyrTFA commented on code/modules/mob/living/living.dm
> +			to_chat(src, "gloves worn")
```suggestion
```

2021-10-12 03:06 UTC, ZephyrTFA commented on code/modules/mob/living/living.dm
> +			to_chat(src, "Victim is human")
```suggestion
```

2021-10-12 03:06 UTC, ZephyrTFA commented on code/modules/mob/living/living.dm
> +				to_chat(src, "seamless")
```suggestion
```

2021-10-12 03:32 UTC, YakumoChen requested changes

2021-10-12 03:32 UTC, YakumoChen commented on modular_skyrat/modules/modular_items/code/game/objects/items/thieving_gloves.dm
> +	desc = "These gloves make stealing things a problem of the past, using advanced nanochips they allow the wearer to steal items from others in only a fraction of the time and also have built in subro
I would appreciate if you gave them a description that didn't preclude the use of "Glove Nanochips" which are a little nonsensical and similar items have had references to nanochips purged (see: infiltrator gloves, nitrile gloves)

2021-10-12 03:32 UTC, YakumoChen commented on modular_skyrat/modules/modular_items/code/game/objects/items/thieving_gloves.dm
> +/obj/item/clothing/gloves/color/black/thieving
Instead of making these a subtype of black gloves with extra fixings, they should be a subtype of Combat gloves which already preclude insulation and fire resistance.

2021-10-12 03:34 UTC, YakumoChen commented
I was going to suggest a trait-based thing instead of looking for the clothes but you just did that already lol

2021-10-23 00:01 UTC, ZephyrTFA commented on modular_skyrat/modules/modular_items/code/game/objects/items/thieving_gloves.dm
> +	clothing_traits = TRAIT_STICKY_FINGERS
```suggestion
	clothing_traits = list(TRAIT_STICKY_FINGERS)
```

2021-11-09 20:43 UTC, GoldenAlpharex commented
As I have merged https://github.com/Skyrat-SS13/Skyrat-tg/pull/8772, I'll be closing this, I appreciate the effort regardless!

2021-11-09 20:43 UTC, closed without merging