[Semi-modular] Silicon flavor texts
Skyrat-SS13/Skyrat-TG pull request #8788
Opened 2021-10-13 02:10 UTC by NotRanged

## About The Pull Request
Re-implements silicon flavor texts. Tested and working, only issue is I can't figure out how to get the icon of a cyborg show up in the examine, so it's just a black screen right now.
![image](https://user-images.githubusercontent.com/20977204/137054511-ad7c79a0-d305-4dad-99bc-d3726e4001df.png)

## How This Contributes To The Skyrat Roleplay Experience
fun cat fact this is the second time I've implemented silicon flavor texts on this codebase

because this reuses the old key 'silicon_flavor_text' this should grab the flavor texts you had before the prefs change but idk for sure since I have no way to actually test that

## Changelog

:cl:
add: Re-implemented silicon flavor texts!
/:cl:

2021-10-13 02:11 UTC, GoldenAlpharex commented
I actually made some verifications on the server, I'm pretty sure the silicon flavor text is still there in its integrity, yeah.

2021-10-13 02:13 UTC, GoldenAlpharex commented
I love how that picture is telling a story as well, hahahah.

2021-10-13 02:14 UTC, NotRanged commented
NOT THE BEES
**_AAAAAAAAAAAAAAAAA_**

2021-10-13 02:14 UTC, Seris02 commented
"Burn with me."

2021-10-13 02:35 UTC, ORCACommander commented
Oh boy one of red's children has discovered video games....

2021-10-14 00:12 UTC, GoldenAlpharex requested changes
Just one thing I want to make sure of first.

2021-10-14 00:12 UTC, GoldenAlpharex commented on code/modules/mob/living/carbon/human/examine_tgui.dm
> +	ooc_notes += preferences.read_preference(/datum/preference/text/ooc_notes)
Will that read the person's OOC preferences or that of the body? Because we want that of the body, so that if a changeling impersonates someone, people can't easily tell "Hey it's not the same person because they don't have the same OOC notes!"

2021-10-14 00:52 UTC, NotRanged commented on code/modules/mob/living/carbon/human/examine_tgui.dm
> +	ooc_notes += preferences.read_preference(/datum/preference/text/ooc_notes)
it reads the client here, I'll change it to be contained within the ishuman/issilicon so it doesn't

2021-10-18 17:43 UTC, GoldenAlpharex approved these changes
Looks good to me. :+1:

2021-10-18 17:47 UTC, merged