GoofMed: Self-Actualization Device, Stasis Operating Tables!
Skyrat-SS13/Skyrat-TG pull request #8791
Opened 2021-10-13 03:50 UTC by Iamgoofball

## About The Pull Request

![32rVaEmJfa](https://user-images.githubusercontent.com/4081722/137063968-af8a69e1-52bc-4fa2-8d08-1ac573c9c96e.png)
https://file.house/egqL.mp4

You can access it via the Genetics research node.

Operating tables now provide stasis when buckled to them. If someone wishes to not be under stasis, they can simply lie down on the table like normal.

## How This Contributes To The Skyrat Roleplay Experience

It's bad for roleplay when people succumb after being revived because they're upset about the revival method.

Regarding stasis tables, this is a change that the person who refactored medbay upstream thought was a good idea, and I agree. It will reduce patient issues.

## Changelog

:cl:
add: Adds the Self-Actualization Device for Medbay! Find it under Genetics research.
qol: Operating Tables have been equipped with stasis functionality!
qol: Cyborgs are no longer immune to surgery speedups.
add: You now work faster when alone with a patient!
fix: Painkillers now properly numb pain.
/:cl:

2021-10-13 03:58 UTC, Acer202 commented
Goof with the good stuff again. The SIMS music really caught me off-guard and it made that video 10x funnier than it should have been, pfft.

I like this, for a lot of reasons. Body horror stuff tweaks me out more than I thought it would, and this is a nice big step away from "Too bad, wait for next shift so you can stop feeling weird."

2021-10-13 04:03 UTC, ZephyrTFA commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +			icon_state = "sad_closed"
```suggestion
	if(occupant)
		icon_state = processing ? "sad_on" : "sad_off"
	else
		icon_state = state_open ? "sad_open" : "sad_closed"
```

ternary man good, if else man bad

2021-10-13 04:04 UTC, ZephyrTFA commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +		next_fact--
```suggestion
	if(--next_fact <= 0)
		next_fact = initial(next_fact)
		say(pick(advertisements))
		playsound(loc, 'sound/machines/chime.ogg', 30, FALSE)
```

2021-10-13 04:05 UTC, ZephyrTFA commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +		if(obj_flags & EMAGGED)
hehe

2021-10-13 04:36 UTC, sqnztb commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +			patient.updateappearance(icon_update=TRUE, mutcolor_update=TRUE, mutations_overlay_update=TRUE)
Someone on discord brought this up - What happens if you change your prefs while in-game and then hop into the SAD? Is there potential for abuse here with literal switching chars/mulligan style shenanigans?

If there's not a way to block that from happening, may want to add some sort of admin logging in here. Just a thought.

2021-10-13 04:46 UTC, Iamgoofball commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +			patient.updateappearance(icon_update=TRUE, mutcolor_update=TRUE, mutations_overlay_update=TRUE)
This is a thing I think we're just going to need to handle administratively, yeah.

2021-10-13 05:44 UTC, softcerv commented
One of the best ideas I've seen in a long time for Skyrat medical players. Thank you so much.

2021-10-13 14:27 UTC, Azarak commented
consider: set_species() with the data stored in the DNA, instead of using volatile client and volatile prefs

2021-10-13 18:22 UTC, YakumoChen commented
this is unbelievably based. Bring back polymorph wizards with this?

2021-10-13 19:28 UTC, Gandalf2k15 approved these changes

2021-10-13 19:28 UTC, Gandalf2k15 commented on code/modules/research/techweb/all_nodes.dm
> +		"oc_donut_steel_restoration_device", // SKYRAT EDIT ADDITION: Added the Self-Actualization Device
I will likely be changing how we deal with all_node changes, however, for now, this is acceptable.

2021-10-13 19:28 UTC, Gandalf2k15 commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +/obj/machinery/oc_donut_steel_restoration_device/Destroy()
What happens if this is destroyed and someone is inside it?

2021-10-13 20:38 UTC, Iamgoofball commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +/obj/machinery/oc_donut_steel_restoration_device/Destroy()
Same as if someone's in any other machine, should shunt them out.

2021-10-13 22:37 UTC, YakumoChen commented
I don't think stasis surgery is going to be popular, it was explicitly removed.

Maybe atomize this? The SAD is definitely a winner

2021-10-13 22:53 UTC, Iamgoofball commented
The person who did the stasis pods is no longer contributing, and I'm not removing the table.

2021-10-13 23:06 UTC, softcerv commented
Does the stasis function on the table still let people use anesthetic on patients?

2021-10-13 23:07 UTC, Iamgoofball commented
@softcerv Once that bug w/ anesthetic gets patched, yeah.

2021-10-13 23:13 UTC, ZephyrTFA commented
> The person who did the stasis pods is no longer contributing, and I'm not removing the table.

This should still be atomized.

2021-10-13 23:17 UTC, Iamgoofball commented
I'm just going to be putting more GoofMed stuff into this as I've got other things I want to do to medical.

2021-10-13 23:26 UTC, softcerv commented
> 
> 
> @softcerv Once that bug w/ anesthetic gets patched, yeah.

Dope,

2021-10-14 03:11 UTC, YakumoChen commented
I feel like stasis tables should be an upgrade rather than the default, to encourage medical to be less lazy. Stasis already makes them better than alien operating tables which are strictly better.

We also have the stasis beds still which function as worse tables (since the operating computers can't hook up)

2021-10-14 03:22 UTC, Iamgoofball commented
We are going to be dealing with 176 player rounds going forward. Medbay needs every tool available to it.

2021-10-14 07:24 UTC, YakumoChen commented
more players will mean more doctors. I don't agree with powercreeping the job as well. 

More upgrades as the round progresses is more fun for everyone involved, no job needs everything handed to them at shift start.

2021-10-14 17:36 UTC, Iamgoofball commented
I don't agree.

2021-10-14 18:09 UTC, GoldenAlpharex requested changes
Got a few more things that need addressed before we can merge this.

2021-10-14 18:09 UTC, GoldenAlpharex commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +	// SKYRAT EDIT END
This should probably go in another PR as it's more time-sensitive to have it merged than this PR.

2021-10-14 18:09 UTC, GoldenAlpharex commented on code/modules/surgery/surgery_step.dm
> +		to_chat(user, span_notice("You are able to work faster due to the quiet environment!"))
This seems entirely unrelated to the Self-Actualization Device and the stasis operating tables, and would probably require a PR on its own, so it's easy to find back in the future and properly documented.

So, either way, this is basically making surgery *even* faster if there's only two people in the room in which surgery is happening?

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +	departmental_flags = DEPARTMENTAL_FLAG_MEDICAL
The fact that things aren't really organized by what they are and just going in order in whatever order is kind of a strange code design choice. I'd appreciate if things were shuffled around to make the code easier to read and to follow.

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +/obj/machinery/oc_donut_steel_restoration_device
The examine of the decive could use being a little smaller and only have one hell of a long description when you double-examine it. Otherwise it just clutters your chat for no good reason.

Furthermore, I'd appreciate if the examine would say when it's processing and when there's someone inside. I know the visual aspect is already there, but it can't hurt to have one line for each in your chat.

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +		next_fact = initial(next_fact)
Adding some randomness to when they're played should be nice here, to make it feel less repetitive.
```suggestion
		next_fact = rand(initial(next_fact), 2 * initial(next_fact))
```

2021-10-14 18:09 UTC, GoldenAlpharex commented on code/game/objects/structures/tables_racks.dm
> +	desc = "Used for advanced medical procedures. Now comes with built in stasis technology, patented by Cinco: A Family Company!" // SKYRAT EDIT desc = "Used for advanced medical procedures."
Wouldn't it be better if it was, like, an upgrade or something? Because it makes little sense that it does exactly what the stasis beds do, but cheaper and requiring no tool nor stock parts to build.

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +	obj_flags |= EMAGGED
Two things:
First, do we really want this to be able to be done when there's currently someone inside?
Second, shouldn't there be a way for people, either through examining or some slight sprite change, to know that the device was emagged?

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +			patient.updateappearance(icon_update=TRUE, mutcolor_update=TRUE, mutations_overlay_update=TRUE)
I think that there should be something here to at least log if someone's using the machine to change their character's look within the same round through modifying their preferences, at the very least. Ideally, we'd have initial preferences from whenever the person joined the round first, but I doubt that it's currently possible and viable.

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +		update_appearance()
I think this should probably be moved to something else, like Alt-click as a shortcut, and possibly a neat little menu that'd show the progress of the current system. Ideally, I'd prefer someone else than the person entering being able to start the machine, to stay in line with all the other machines in medical.

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +/obj/machinery/oc_donut_steel_restoration_device/proc/eject_new_you()
Documentation for this proc would be appreciated.

2021-10-14 18:09 UTC, GoldenAlpharex commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +			patient.updateappearance(icon_update=TRUE, mutcolor_update=TRUE, mutations_overlay_update=TRUE)
Furthermore, do you know why, in your video, the person coming out of the machine didn't have the same hair color? Feels a little strange if it doesn't actually properly set all the appearance stuff to the right thing.

Oh, and finally, is that proc really written like that? `updateappearance()`? That's... Not good, no matter the code standards, honestly. Should be snakecased in another PR later.

2021-10-14 18:21 UTC, Iamgoofball commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +	departmental_flags = DEPARTMENTAL_FLAG_MEDICAL
Sure. I just wanted to keep it all in one file.

2021-10-14 18:23 UTC, Iamgoofball commented on code/modules/surgery/surgery_step.dm
> +		to_chat(user, span_notice("You are able to work faster due to the quiet environment!"))
Players were complaining that there was no reason to use the surgery areas, and I wanted to cater to that but without adding hardcoded area checks.

2021-10-14 18:23 UTC, Iamgoofball commented on code/game/objects/structures/tables_racks.dm
> +	desc = "Used for advanced medical procedures. Now comes with built in stasis technology, patented by Cinco: A Family Company!" // SKYRAT EDIT desc = "Used for advanced medical procedures."
Ideally we'd phase stasis beds out entirely.

2021-10-14 20:15 UTC, Iamgoofball commented on modular_skyrat/modules/donut_steel_restoration_device/code/oc_donut_steel_restoration_device.dm
> +/obj/machinery/oc_donut_steel_restoration_device
I removed the newlines to condense it a bit.

2021-10-14 22:08 UTC, GoldenAlpharex commented on code/game/objects/structures/tables_racks.dm
> +	desc = "Used for advanced medical procedures. Now comes with built in stasis technology, patented by Cinco: A Family Company!" // SKYRAT EDIT desc = "Used for advanced medical procedures."
I mean, regardless, it makes little sense that just some iron and some silver allows you to be in stasis forever. It should require a board of some sort to have that, or literally anything else. But just free stasis everywhere for just some silver and iron is too cheap.

2021-10-15 10:57 UTC, necromanceranne commented
I think the only thing to be conscious of with this is whether or not it could be used as a ling tell by shoving someone into it and it reverts them back to their previous identity. 

Other than that, a cool grief reversal tool/accidental brain transplantation resolver. And the game could do with that, since a lot of the most toxic things players can do to each other is almost impossible to reverse and really frustrating to deal with long term.

_cough mulligan smoke cough_

2021-10-15 12:50 UTC, KathyRyals commented
I purposefully removed operating on stasis beds for a reason, it was lazy and overpowered. I'm not looking forward to it being added again. Patients potentially passing away mid surgery or needing chems not to rot was exciting.

2021-10-15 12:54 UTC, Iamgoofball commented
It's exciting for the people playing doctor.

It's not exciting for the person stuck in deadchat for another ~~15~~ 45 minutes because they got the person who plays medbay exclusively to wear the nurse outfit to the bar as their doctor that day.

2021-10-15 15:00 UTC, softcerv commented
> 
> 
> It's exciting for the people playing doctor.
> 
> It's not exciting for the person stuck in deadchat for another ~15~ 45 minutes because they got the person who plays medbay exclusively to wear the nurse outfit to the bar as their doctor that day.

Heavily agreed, having medbay be harder only ends up "benefiting" the doctors and nobody else. Medbay, especially on Skyrat, needs more leeway. 

It'd really be nice if the bulk of medbay content wasn't just about how long it takes to revive someone, balancing medbay like that isn't fun for the patients, and doctors shouldn't be loosing content whenever medbay has something that makes it more efficient.

2021-10-15 15:03 UTC, softcerv commented
I'd suggest that you have like an alt+click option to toggle the stasis mode on the tables, if you don't already have that in.

2021-10-18 00:12 UTC, merged

2021-10-18 05:10 UTC, Trubbl3 commented
always nice some actual buffs and QOL stuff for medbay, i am tired of it getting gutted or made harder for no reason other than "its too easy" or "Make it more fun".

No it doesn't make it fun, no its not more exciting not for the patient or the doctors, it makes it more tedious and harder for no actual gain, making both he patient and doctor feel worse in the end. 
Thanks goof