Oversized quirk
Skyrat-SS13/Skyrat-TG pull request #8897
Opened 2021-10-17 21:05 UTC by Gandalf2k15

## About The Pull Request
Adds a new quirk to the game, requested by a friend.

The oversized quirk is for those that really just want to stand out and pay for it.

Description:
It makes your sprite size a multiple of 2, which is .5 bigger than you can be normally.

Benefits:
You do 5 extra damage per punch.
You have a 10% bonus to resisting grabs and grabbing people.
You start with 50% more blood.
You are harder to throw and throw things harder.

Downsides:
You will hit your head off any door you go through unless you are walking or crawling. This does a decent amount of damage and knocks you down.
You do not fit in bodybags.
You do not fit in lockers.
You have a slowdown of +0.5, which means you walk and run substantially slower.
Pulling them has a slowdown unless the one pulling them is also oversized or a cyborg.
You cannot be fireman carried by anyone without the quirk.
Sitting in chairs will cause them to buckle and break.

## How This Contributes To The Skyrat Roleplay Experience

I guess my man wants to be really big and have some cool stuff to tackle.

![dreamseeker_cC5avWI3Dq](https://user-images.githubusercontent.com/9026500/137645309-8a28be07-4e45-4c4a-bf00-4be196663152.png)

## Changelog

:cl:
add: Added a new quirk, oversized. See: for more details.
/:cl:

2021-10-17 21:23 UTC, Sigmar-alkahest commented
perhaps implement a thing where it is mutually exclusive with the separate chunky fingers quirk so people don't try to game for free quirk points? (personally something i don't care for, but it would apease those who'd use the above to say this shouldn't go through because power game)

2021-10-17 21:38 UTC, GoldenAlpharex requested changes

2021-10-17 21:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	lose_text = "<span class='notice'>Is its still the same size?...</span>" //Lol
There you go.
```suggestion
	gain_text = span_notice("That airlock looks small...")
	lose_text = span_notice("Is it still the same size...?") //Lol
```

2021-10-17 21:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	human_holder.dna.features["body_size"] = 1
Shouldn't this be back to whatever it was set to in their prefs? I think it might make more sense, even if a tad bit harder to reach.

2021-10-17 21:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	human_holder.blood_volume = BLOOD_VOLUME_OVERSIZED
Won't this scale down over time though? Like, won't they progressively have less blood until they reach their species' normal max volume?

2021-10-17 21:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	var/speedmod = human_holder.dna.species.speedmod - OVERSIZED_SPEED_SLOWDOWN
Otherwise they'll end up zooming around when getting that removed.
```suggestion
	var/speedmod = human_holder.dna.species.speedmod
```

2021-10-17 21:38 UTC, GoldenAlpharex commented on modular_skyrat/modules/oversized/code/door.dm
> +	return ..()
Uhhhhh, that already exists in core /tg/ code, line 63 of `code\game\machinery\doors\door.dm`, you probably should add it there, no?

2021-10-17 21:40 UTC, Gandalf2k15 commented on modular_skyrat/modules/oversized/code/door.dm
> +	return ..()
Modularity

2021-10-17 21:42 UTC, Gandalf2k15 commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	human_holder.blood_volume = BLOOD_VOLUME_OVERSIZED
true, I'll che ckit out

2021-10-17 21:42 UTC, RatFromTheJungle commented
@Gandalf2k15 pls explain "You are harder throw and throw things harder."

2021-10-17 21:42 UTC, Arctaisia commented
I can't wait to hit my head :)

Still, very nice, makes me happy to see that we'll have 2x spritesize in a fairly balanced way, means I can bring my extra big characters over <3

2021-10-17 21:42 UTC, Gandalf2k15 commented
> @Gandalf2k15 pls explain "You are harder throw and throw things harder."

You know how dwarves are easy to throw? Well, this is like that, only, inverted.

2021-10-17 21:43 UTC, RatFromTheJungle commented
> 
> 
> > @Gandalf2k15 pls explain "You are harder throw and throw things harder."
> 
> You know how dwarves are easy to throw? Well, this is like that, only, inverted.

what the fuck does 'you are harder throw' mean gandalf pls

2021-10-17 21:44 UTC, Gandalf2k15 commented
> > > @Gandalf2k15 pls explain "You are harder throw and throw things harder."
> > 
> > 
> > You know how dwarves are easy to throw? Well, this is like that, only, inverted.
> 
> what the fuck does 'you are harder throw mean' gandalf pls

it means you throw them not as far and they throw you further you dent

2021-10-17 21:54 UTC, Funce commented
> > > > @Gandalf2k15 pls explain "You are harder throw and throw things harder."
> > > 
> > > 
> > > You know how dwarves are easy to throw? Well, this is like that, only, inverted.
> > 
> > 
> > what the fuck does 'you are harder throw mean' gandalf pls
> 
> it means you throw them not as far and they throw you further you dent

You absolute baboon, "You are harder throw" you mean "you are harder **_to_** throw"

2021-10-17 22:03 UTC, Gandalf2k15 commented
> > > > > @Gandalf2k15 pls explain "You are harder throw and throw things harder."
> > > > 
> > > > 
> > > > You know how dwarves are easy to throw? Well, this is like that, only, inverted.
> > > 
> > > 
> > > what the fuck does 'you are harder throw mean' gandalf pls
> > 
> > 
> > it means you throw them not as far and they throw you further you dent
> 
> You absolute baboon, "You are harder throw" you mean "you are harder **_to_** throw"

You are harder to throw and throw things harder.

2021-10-17 22:18 UTC, Echopsychotic commented
I feel like I know the person who requested this :3

2021-10-17 22:21 UTC, Iamgoofball commented
>You have a slowdown of +0.5, which means you walk and run substantially slower.
>You cannot be moved by normal humans, you require another big lad to move you OR a cyborg OR you need to be in zero G.

These are both the only two actual downsides here.
One of them is *incredibly* easily fixable.
One of them is actually not a downside, it's "you cant be arrested".

I am not looking forward to Security players taking this and then making themselves impossible to remove from medbay when they trespass without having to do the law dance argument with a fucking cyborg, because that's the only person who can move them.

2021-10-17 22:29 UTC, MisterLiuvik commented
It should surprise literally no one that "A Friend" is literally me.

Anyways, I can't read code, but the intention I had behind this particular quirk was to make it to where you couldn't be fireman carried by people without the quirk. You should still be able to get dragged at a slow pace by them, however.
Also, being big by itself is already a downside. You're easier to click. You can't click people that stay above you (You literally can't hardly see their sprite.)
In melee combat, you will likely beat the shit out of yourself if you have to dance around someone. Especially if you go that extra mile and have wings, or, god forbid, happen to also be a taur. (Not saying taurs are bad, of course, just that you better be ready to smack your own ass with a DEsword. It's a big ass.)
The other downside, as written, should be that if you /run/ through an airlock, you bonk your fucking head. This means you can literally, in the midst of a high octane situation, totally forget and just smash your nose on a door overhang. 
Also the slowdown for being big makes very little sense. I'm not asking to be faster, of course, but if you go by that logic, people who are smaller should be faster, and they're already harder to click. That's not how movement works. 
The chair bit was silly, but yeah, I already figured that it was a bad idea considering that means sec will have to actively remember that you can be buckled to piping. Or tables.

2021-10-17 23:30 UTC, GoldenAlpharex requested changes

2021-10-17 23:30 UTC, GoldenAlpharex commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	human_holder.dna.features["body_size"] = human_holder?.client?.prefs?.read_preference(/datum/preference/numeric/body_size)
Just to avoid a runtime in case we have a mob with no client, we'll just reset it to 1, at this point it's their problem.
```suggestion
	human_holder.dna.features["body_size"] = human_holder?.client?.prefs ?human_holder?.client?.prefs?.read_preference(/datum/preference/numeric/body_size) : 1
```

2021-10-18 00:25 UTC, Funce approved these changes

2021-10-18 00:25 UTC, merged

2021-10-18 12:44 UTC, hugmeorelse commented
I did not approve these changes nor was I consulted.