[SEMI-MODULAR] Adds chest-rig holstering and adds actual syndie bowmans to DS-2
Skyrat-SS13/Skyrat-TG pull request #8902
Opened 2021-10-18 07:31 UTC by axietheaxolotl

## About The Pull Request

See the title. The pseudo-sec bowmans DS-2 had are also gone, and use the syndie headset sprite that's already in the game. Admiral gets one too.

## How This Contributes To The Skyrat Roleplay Experience

haha `modular_skyrat/modules/sec_haul/sound/holsterout.ogg` go rustle

https://user-images.githubusercontent.com/86872535/137687171-a1c634f7-d441-4071-8a84-58d67e654f79.mp4

## Changelog

:cl:
add: chest-rig holstering
add: DS-2 syndie headsets
/:cl:

2021-10-18 15:17 UTC, GoldenAlpharex requested changes
This is also a balance change and I'd really like you to respect the PR template and actually try to convince us why this is a good thing for Skyrat in the "How This Contributes To The Skyrat Roleplay Experience" section.

A PR is supposed to convince us why this is a good change, if you can't do that, I don't see why I should be hitting the "merge" button.

2021-10-18 15:17 UTC, GoldenAlpharex commented on code/game/objects/items/storage/belt.dm
> +			viewing.show_message("<span class='notice'>[M] puts [I] [insert_preposition]to [parent].</span>", MSG_VISUAL)
This should be in a modular file, there is no reason this has to be included in this file.

2021-10-18 15:17 UTC, GoldenAlpharex commented on code/game/objects/items/storage/belt.dm
> +// SKYRAT EDIT ADDITION END - HOLSTERING
I hope you realize you now need to make sure this doesn't happen in the tactical snack rig to ensure that people can't put guns in it, right?

2021-10-18 15:17 UTC, GoldenAlpharex commented on code/game/objects/items/storage/belt.dm
> +	user.visible_message("<span class='warning'>[user] draws [gun_to_draw] from [parent]!</span>", "<span class='notice'>You draw [gun_to_draw] from [parent].</span>")
This also needs to use the span defines.

2021-10-19 02:06 UTC, tf-4 commented on code/game/objects/items/storage/belt.dm
> +	var/atom/A = parent
https://github.com/tgstation/tgstation/pull/56872

2021-10-23 18:58 UTC, GoldenAlpharex commented
No changes were made to the PR body in five days, giving you two more days to convince me that it's a good and well thought-out change before I close the PR.

2021-10-29 15:26 UTC, GoldenAlpharex commented
I ended up giving you six days instead of two. Oh well.

2021-10-29 15:26 UTC, closed without merging