Nerfs oversized quirk
Skyrat-SS13/Skyrat-TG pull request #8919
Opened 2021-10-18 22:37 UTC by linnpap

## About The Pull Request
Nerfs the oversized quirk, making it more of a neutral quirk to have **for the time being**. This is meant to be a temporary measure, and I've left most of the oversized quirk code commented out, as opposed to fully removed.

This removes the grab resist bonus and damage bonus.

This also adds a temporary knockdown when buckled to a chair. This is because a combat strategy I've seen is to buckle a player to a chair in order to prevent them from moving.

## How This Contributes To The Skyrat Roleplay Experience
The oversized quirk has proven itself to be controversial as all hell, mainly due to its (no offense) half-baked nature. I think that, for now, it should be nerfed to have less powergamey traits, and to be more a neutral trait. I am assuming that this will be temporary, and that eventually the trait will be sorted out balance-wise.

## Changelog

:cl:
balance: Nerfed the oversized quirk
/:cl:

2021-10-18 22:39 UTC, linnpap commented
please dont kill me for this

2021-10-18 22:39 UTC, Gandalf2k15 commented on code/modules/mob/living/carbon/carbon.dm
> -		//SKYRAT EDIT ADDITION
No, this was to mirror the dwarfisim trait. So leave this alone.

2021-10-18 22:39 UTC, Gandalf2k15 commented on modular_skyrat/modules/oversized/code/door.dm
> +			//var/affecting = crossing_human.get_bodypart(BODY_ZONE_HEAD)
Undo this

2021-10-18 22:39 UTC, Gandalf2k15 commented on modular_skyrat/modules/oversized/code/door.dm
> +			//crossing_human.adjustOrganLoss(ORGAN_SLOT_BRAIN, 15) //We do a bit of brain damage
Undo this too

2021-10-18 22:39 UTC, Gandalf2k15 commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	//var/speedmod = human_holder.dna.species.speedmod + OVERSIZED_SPEED_SLOWDOWN
Undo this as well

2021-10-18 22:40 UTC, Gandalf2k15 commented on modular_skyrat/modules/oversized/code/oversized_quirk.dm
> +	//var/speedmod = human_holder.dna.species.speedmod
Ditto

2021-10-18 22:40 UTC, Gandalf2k15 commented
Fix the above otherwise this likely won't go through, and consult others in the discord on what needs to change.

2021-10-18 22:49 UTC, linnpap commented
im questioning whether or not to remove the ability to not be carried

2021-10-18 22:54 UTC, Sigmar-alkahest commented
> im questioning whether or not to remove the ability to not be carried

cue 80% size kobold carrying a 12-13 foot tall brick shithouse of a being like it's nothing. i don't think that's the best idea?

2021-10-18 22:56 UTC, GoldenAlpharex requested changes
Mhmm.

2021-10-18 22:56 UTC, GoldenAlpharex commented on code/game/objects/structures/beds_chairs/chair.dm
>  		deconstruct()
I dunno how I feel about this, I'd rather not have the chairs being broken, to be honest it's got a lot of side-effects that weren't foreseen, like the interlink tram.

2021-10-18 23:00 UTC, GoldenAlpharex commented
They also need to be able to be carried by Bluespace Bodybags, which they currently cannot, afaik.

2021-10-18 23:01 UTC, Gandalf2k15 commented
> They also need to be able to be carried by Bluespace Bodybags, which they currently cannot, afaik.
They can

2021-10-18 23:02 UTC, ArdentSpark commented
> > im questioning whether or not to remove the ability to not be carried
> 
> cue 80% size kobold carrying a 12-13 foot tall brick shithouse of a being like it's nothing. i don't think that's the best idea?

Wierdly people saw the difficulty of movement to be one of the most balance adjusting parts of the quirk. I.E Antagonist trying to kidnap someone, or medical trying to relocate a patient, or security trying to arrest and relocate a prisoner.

I don't believe inability to be firecarried is that bad, however it was one of the points raised most commonly. Removing the ability to grab entirely would also be a point of contention

2021-10-19 01:03 UTC, Gandalf2k15 commented
I think given we've moved this to veteran crew, these are no longer required. We will discuss it further.

2021-10-19 06:21 UTC, Trubbl3 commented
i don't like a mechanical solution to an RP issue, you can RP as someone big if you want, no need of a quirk for it, 150% should be enough

2021-10-19 07:23 UTC, FridayRemada commented
Honestly, if it were my decision, I'd take NO upsides, but you dont bang your head on the doors. I'd sacrifice the grab buffs and everything just to have a cosmetic, slightly and OVERALL inconvenient quirk, with the upside that you get to be big.

2021-10-27 16:36 UTC, Gandalf2k15 commented
Given the fact this is now VC only, we don't need to nerf it anymore.

2021-10-27 16:36 UTC, closed without merging

2021-10-27 16:43 UTC, Iamgoofball commented
actually we do, VC only doesn't mean it's immune to being balanced, but OK