Goofmed Bugfix: Screaming no longer kills you. God. Why. Come on.
Skyrat-SS13/Skyrat-TG pull request #8977
Opened 2021-10-22 10:27 UTC by Iamgoofball

doctors were suffocating people with pain screams by accident

i don't need to explain why this is bad

2021-10-22 10:59 UTC, Iamgoofball commented
according to gitblame this was an oldbase thing

2021-10-22 15:52 UTC, SpaceVampire commented
This seems like it could be another reason for people to want to use painkillers.
Isn't that a good thing?

2021-10-22 15:59 UTC, ZephyrTFA commented
Doctors should already be using painkillers or putting their patient to sleep using sleeping gas.
This is a bad change.

2021-10-22 16:49 UTC, Iamgoofball commented
You two don't understand the actual problem here. The scream emote should not be killing people given the amount of ways you can force someone to *scream.

2021-10-22 17:56 UTC, ZephyrTFA commented
> You two don't understand the actual problem here. The scream emote should not be killing people given the amount of ways you can force someone to *scream.

Its a grand total of 5 oxy damage.
It doesnt apply lose breath stacks, it doesnt apply nobreathe, it just gives a flat 5 oxy.
You are making a problem where there isn't one.

2021-10-23 18:53 UTC, GoldenAlpharex requested changes

2021-10-23 18:53 UTC, GoldenAlpharex commented on modular_skyrat/modules/emotes/code/scream_emote.dm
> -			user.adjustOxyLoss(5)
Have it be stamina loss instead, bam, issue fixed.

2021-10-23 20:26 UTC, Gandalf2k15 commented
This was added on citadel to prevent scream spamming. We have a literal hard cooldown on emotes which includes screaming. So damage is no longer required.

2021-10-23 20:26 UTC, merged