Revert #8978
Skyrat-SS13/Skyrat-TG pull request #9058
Opened 2021-10-26 16:58 UTC by axietheaxolotl

## About The Pull Request

title

done on head maintainer's request. Was merged prematurely

![image](https://user-images.githubusercontent.com/86872535/138926560-6f994fbc-536f-4620-9f99-01844d054df6.png)

## How This Contributes To The Skyrat Roleplay Experience

## Changelog

:cl:
expansion: added back HoP's armour
/:cl:

2021-10-26 17:08 UTC, GoldenAlpharex commented
Still remove the ability to have a gun in its suit slot. It's not needed.

2021-10-28 17:03 UTC, GoldenAlpharex requested changes

2021-10-28 17:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/suits/armor.dm
> +	allowed = GLOB.security_wintercoat_allowed
No more of this. You choose between fashion and open carrying. You don't have both as a non-combat-oriented role.
```suggestion
```

2021-10-28 17:03 UTC, GoldenAlpharex commented on modular_skyrat/modules/customization/modules/clothing/suits/armor.dm
> +	armor = list(MELEE = 25, BULLET = 20, LASER = 20, ENERGY = 30, BOMB = 20, BIO = 0, RAD = 0, FIRE = 50, ACID = 50, WOUND = 8)
Why does it have wound armor?

2021-10-31 23:57 UTC, jjpark-kb commented
stale.

2021-10-31 23:57 UTC, closed without merging