balancing fishing a little
Skyrat-SS13/Skyrat-TG pull request #9192
Opened 2021-11-02 02:41 UTC by jjpark-kb

## About The Pull Request
I find that you are actually getting good things from trash... I dont want that!
Made it only get trash from the loot, not just goodies from maint.

Just a little more strange rocks for the poor man, please? Promoting xenoarch should be fine.

We are getting too many fishing skill chips... suffer from less of them!

## How This Contributes To The Skyrat Roleplay Experience
balancing fishing to be "less" rewarding from the trash loot.

## Changelog

:cl:
balance: fishing and getting trash will result in actual trash items, not goodies
balance: upped the chance to get strange rocks from the ore result in fishing
balance: lowered the chance to get the fishing skillchip
/:cl:

2021-11-02 14:28 UTC, GoldenAlpharex requested changes

2021-11-02 14:28 UTC, GoldenAlpharex commented on modular_skyrat/modules/fishing/code/fishing.dm
> +	/obj/item/xenoarch/strange_rock = 3,
Let's start with double first, just to see what it's like. They should still be kinda rare.
```suggestion
	/obj/item/xenoarch/strange_rock = 2,
```

2021-11-02 14:28 UTC, GoldenAlpharex commented on modular_skyrat/modules/fishing/code/fishing.dm
> +		if(98 to 100)
I'd honestly almost make it 2 percents, so from 99 to 100. Maybe just 1 percent even. Gotta make it actually rare and desireable.

2021-11-03 00:54 UTC, jjpark-kb commented on modular_skyrat/modules/fishing/code/fishing.dm
> +		if(66 to 97)
```suggestion
		if(66 to 98)
```

2021-11-03 00:54 UTC, jjpark-kb commented on modular_skyrat/modules/fishing/code/fishing.dm
> +		if(98 to 100)
```suggestion
		if(98=9 to 100)
```

2021-11-03 00:54 UTC, jjpark-kb commented on modular_skyrat/modules/fishing/code/fishing.dm
> +		if(98 to 100)
```suggestion
		if(99 to 100)
```

2021-11-03 12:53 UTC, softcerv commented
Maybe you could look into magnet fishing as a way for people to still get loot maint loot of some kind? It would also make it easier to balance around people getting loot from it if you had it as a separate type of rod. (Although, I'm not sure how much refactoring that would require)

I would also recommend maybe lowering the rate of fishing up trash a bit more to like 30% or maybe have the Fishing Master Skillchip lower it.

2021-11-06 21:24 UTC, jjpark-kb commented
okay, its been awhile, I have thought of something else to do instead. I do not know when the PR will be up, but itll be something instead of this.

2021-11-06 21:24 UTC, closed without merging