powerarmor balance
Skyrat-SS13/Skyrat-TG pull request #9382
Opened 2021-11-11 01:42 UTC by jjpark-kb

## About The Pull Request
there has been almost no use of power armor, and that is due to how awful it is.
This PR is buffing power armor with the hopes more people will use it.

## How This Contributes To The Skyrat Roleplay Experience
making this more relevant can promote forging, interactions with robotics for the suits, etc.

## Changelog

:cl:
balance: makes some of the power armor modules cost less
balance: caps power armor armor to 80
/:cl:

2021-11-12 13:24 UTC, GoldenAlpharex requested changes
Needs some improvement when it comes to all the magic numbers, make use of more defines for the different armor types and different healing types.

2021-11-12 13:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/powerarmor/code/powerarmor.dm
> +	living_wearer.adjustStaminaLoss(-healing_upgraded[5])
Those numbers should all be defines.

2021-11-12 13:24 UTC, GoldenAlpharex commented on modular_skyrat/modules/powerarmor/code/powerarmor.dm
> +				healing_upgraded[5]++
A lot of magic numbers, I do not know what a `healing_upgraded[3]` or an `armor_upgraded[1]` is.

Also, I'm fairly confident lists start at 0 so this is just a bunch of runtimes for index out of bounds waiting to happen.

2021-11-14 01:14 UTC, ChungusGamer666 commented on modular_skyrat/modules/powerarmor/code/powerarmor.dm
> +				healing_upgraded[5]++
Lists start at 1 in byond code.

2021-11-14 01:15 UTC, ChungusGamer666 commented on modular_skyrat/modules/powerarmor/code/powerarmor.dm
> +	living_wearer.adjustStaminaLoss(-healing_upgraded[5])
No, they shouldn't, as they can get changed in runtime. Using a list is acceptable, but i'd recommend using an associated list (damagetype = damage healing value)

2021-11-16 21:39 UTC, GoldenAlpharex commented on modular_skyrat/modules/powerarmor/code/powerarmor.dm
> +	living_wearer.adjustStaminaLoss(-healing_upgraded[5])
> No, they shouldn't, as they can get changed in runtime. Using a list is acceptable, but i'd recommend using an associated list (damagetype = damage healing value)

That isn't what I meant. `1` should be `BRUTE_HEALING` or something like that. That way, it's actually clearer which is which.

2021-11-23 00:16 UTC, closed without merging