Fixes borg emotes, wooooooooo!
Skyrat-SS13/Skyrat-TG pull request #9448
Opened 2021-11-14 21:01 UTC by nikothedude

## About The Pull Request
Fixes borg emotes, by making all borg emotes be within synth_emote.dm.

## How This Contributes To The Skyrat Roleplay Experience
Someone messed up the borg emotes when they added synth emotes. This fixes them. Woo.

## Changelog

:cl:
fix: Fixes all borg emotes. Woo! Also adds some new emotes to borgs.
refactor: Borg emotes are now handled in synth_emote.dm.
/:cl:

2021-11-14 21:01 UTC, nikothedude commented
ignore the commit name idk why its that

2021-11-15 04:21 UTC, Gandalf2k15 commented on modular_skyrat/modules/emotes/code/silicon_emotes.dm
> +/* /datum/emote/silicon
Reeeemove the file if it's being deleted ;-; I need to make a new contrib update don't I?

2021-11-15 04:22 UTC, GoldenAlpharex requested changes

2021-11-15 04:22 UTC, GoldenAlpharex commented on code/datums/emotes.dm
> +	var/silicon_allowed = FALSE
Please document the variable, even if it's straight forward.

2021-11-15 04:45 UTC, nikothedude commented
*inhale FUCK ci

2021-11-16 21:35 UTC, GoldenAlpharex approved these changes

2021-11-16 21:35 UTC, merged