[PRIORITY] MODULARISATION AUDIT PART 1: MAKING SKYRAT GREAT AGAIN
Skyrat-SS13/Skyrat-TG pull request #9464
Opened 2021-11-15 03:31 UTC by Gandalf2k15

## About The Pull Request

Audit completed.

Results:
Fucking shit.

Remedial action:
> Reorganised all modules to conform to the MODULARISATION GUIDELINES.
> Compressed the number of folders.
> Compressed the number of files.
> Removed some redundant and unused files.

![Code_4yzxWSK9zI](https://user-images.githubusercontent.com/9026500/141718010-b7d200e0-ce91-4442-86aa-0b88c43a98e9.png)
?????????????????????????

Before:
![explorer_H64rHvhOYR](https://user-images.githubusercontent.com/9026500/141717944-3c204eeb-fe67-49cb-b793-a749ef5c14e8.png)

After:
![explorer_uqPQoxqhJI](https://user-images.githubusercontent.com/9026500/141717961-c74c54e0-0e70-40ee-9c1c-b43584bd5f3d.png)

## How This Contributes To The Skyrat Roleplay Experience

The codebase should download about 3.2 seconds quicker.

Things look better.

Things are legal.

## Changelog

:cl:
server: MODULARISATION AUDIT 15/11/21
/:cl:

2021-11-15 03:41 UTC, Gandalf2k15 commented
Files that have been deleted have either been merged with another file or were obsolete.

2021-11-16 01:21 UTC, GoldenAlpharex requested changes
Just one tiny change so we don't have duplicate definitions of the same code.

2021-11-16 01:21 UTC, GoldenAlpharex commented on modular_skyrat/modules/additionalert/code/pizza/misc.dm
> +	icon_state = "dominos"
This appears to also be in `modular_skyrat/modules/additionalert/code/pizza/misc_clothing.dm`

2021-11-16 02:12 UTC, ORCACommander commented
*screams in Diff*

2021-11-16 04:51 UTC, Gandalf2k15 commented on modular_skyrat/modules/additionalert/code/pizza/misc.dm
> +	icon_state = "dominos"
Good catch

2021-11-16 17:01 UTC, GoldenAlpharex approved these changes

2021-11-16 17:01 UTC, merged