[MODULAR] Rebinds Hypospray Controls
Skyrat-SS13/Skyrat-TG pull request #9558
Opened 2021-11-19 01:17 UTC by softcerv

## About The Pull Request
Remaps the hypospray controls to be more responsive and use the Right mouse button.

- Injecting is done by left clicking a patient, spraying is done by right clicking.
  - Because of this change, the button to swap between spraying and injecting has been removed
- You can now left click on a hypospray or use it in hand to change the transfer amount
  - Alternatively you can now Ctrl+Click to decrease the transfer amount. 
- Ejecting a vial is now mapped to using the right mouse button on the Hypospray

Here is a video of the changes in action:

https://user-images.githubusercontent.com/68373373/142527012-b3157f30-1905-4315-a5aa-45b244e9aaa8.mp4

## How This Contributes To The Skyrat Roleplay Experience
This should make the Hypospray feel more responsive to use, making it a better tool for doctors.

## Changelog

:cl:
qol: the controls on the Hypospray have been rebinded to take advantage of the right mouse button, please check : for details
/:cl:

2021-11-19 03:56 UTC, tf-4 commented
I'm not sure right mouse to eject is intuitive. It should, in my opinion, be done through an attack with an empty hand, à la guns with their magazines.

2021-11-19 04:26 UTC, softcerv commented
> 
> 
> I'm not sure right mouse to eject is intuitive. It should, in my opinion, be done through an attack with an empty hand, à la guns with their magazines.

I could possibly look into that.

2021-11-22 00:25 UTC, GoldenAlpharex requested changes
Tiny nitpick.

2021-11-22 00:25 UTC, GoldenAlpharex commented on modular_skyrat/modules/hyposprays/code/hyposprays_II.dm
> +	. += span_notice("<b>Left Click</b> on patients to inject, <b>Right Click</b> to spray.")
```suggestion
	. += span_notice("<b>Left-Click</b> on patients to inject, <b>Right-Click</b> to spray.")
```

2021-11-23 16:14 UTC, GoldenAlpharex approved these changes

2021-11-23 16:14 UTC, merged