[MOSTLY MODULAR] Body Teleporter Medicell
Skyrat-SS13/Skyrat-TG pull request #9599
Opened 2021-11-21 21:11 UTC by softcerv

## About The Pull Request

Adds in the Body Teleporter Medicell that shoots a projectile that teleports a dead body to the user with it if hit this only works on humans.

![body_teleporter](https://user-images.githubusercontent.com/68373373/142779030-f9d3ebc8-a888-4211-9bb7-a52686f9c7a2.png)

Video of the cell in action

https://user-images.githubusercontent.com/68373373/142778981-5fab5ec2-9da0-42ce-8862-83104aa13d4c.mp4

Ingame Screenshot
![image](https://user-images.githubusercontent.com/68373373/142778997-e6d723c2-79a4-4457-9a6d-bb6a8dbb9446.png)
## How This Contributes To The Skyrat Roleplay Experience

This gives paramedics an easier way to rescue bodies from crowded areas, especially if sec is being uncooperative. Having it require a bluespace slime core also means that medical will  have to interact with science more.
## Changelog

:cl:
add: Adds the Body Teleporter Medicell to the game.
/:cl:

2021-11-22 01:06 UTC, YakumoChen commented
give these a check so you can't antag test fake death changelings with it please

2021-11-22 01:12 UTC, softcerv commented
> give these a check so you can't antag test fake death changelings with it please

I'm not familiar with the code, how would you go about doing that?

2021-11-22 21:09 UTC, YakumoChen commented
Check ling code if fake death grants a trait and add it to the argument

2021-11-23 03:39 UTC, softcerv commented
> Check ling code if fake death grants a trait and add it to the argument

done

2021-11-28 01:27 UTC, GoldenAlpharex requested changes
We're close.

2021-11-28 01:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/medguns.dm
> +	icon_state = "body" //IMPORT A CUSTOM TEXTURE LATER
Is this meant to still be there?

2021-11-28 01:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/medguns.dm
> +	desc = "an unactivated Body Teleporter Medicell, use this on a bluespace slime extract to make this into a usable cell"
Item names are never capitalized unless it's a proper noun.
```suggestion
	name = "empty body teleporter medicell"
	desc = "An inactive body teleporter medicell, use this on a bluespace slime extract to make this into a usable cell."
```

2021-11-28 01:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/medguns.dm
>  	name = "Empty Salve Medicell"
Ditto.
```suggestion
	name = "empty salve medicell"
```

2021-11-28 01:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/medguns.dm
> +	desc = "an unactivated Salve Medicell, use this on an aloe leaf to make this into a usable cell"
```suggestion
	desc = "An inactive salve medicell, use this on an aloe leaf to make this into a usable cell."
```

2021-11-28 01:27 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/mediguns.dm
> +	desc = "A Empty Medicell that can be upgraded by a bluespace slime extract into a usable Body Teleporter Medicell."
```suggestion
	desc = "An empty medicell that can be upgraded by a bluespace slime extract into an usable body teleporter medicell."
```

2021-11-28 19:16 UTC, GoldenAlpharex approved these changes

2021-11-28 19:16 UTC, merged