Respites latex
Skyrat-SS13/Skyrat-TG pull request #9740
Opened 2021-11-27 15:22 UTC by StrangeWeirdKitten

## About The Pull Request

Resprites the current Latex into something that looks more appealing. This is a huge WIP PR

## How This Contributes To The Skyrat Roleplay Experience

Better latex is nice. 

## Changelog
:cl: Syndishork
imageadd: Better Latex Sprites
/:cl:

2021-11-28 15:08 UTC, StrangeWeirdKitten commented
This is what the sprites currently look in game. Note that I did use a couple extra items.

![image](https://user-images.githubusercontent.com/95130227/143773695-fcdf28d1-8dd2-45e6-a5cf-0114a60c9e48.png)

2021-11-29 03:35 UTC, StrangeWeirdKitten commented
I think I got it all.

2021-12-11 09:35 UTC, StrangeWeirdKitten commented
This PR is not stale 🔪

2021-12-13 10:59 UTC, Gandalf2k15 commented on .vscode/launch.json
> -		},
no

2021-12-17 00:15 UTC, tf-4 requested changes
Show ALL sprites in-game, please.

2021-12-23 02:05 UTC, Gandalf2k15 commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_clothing/latex_catsuit.dm
> +	if(B?.genital_size >= 6 & B?.genital_type == "pair")
Incorrect operator

2021-12-23 14:50 UTC, tf-4 commented
This still needs to have sprite pictures added.

2021-12-24 02:52 UTC, Gandalf2k15 commented
reopen with completed changes.

2021-12-24 02:52 UTC, closed without merging

2022-01-19 08:36 UTC, chizzy376 commented
Any chances of trying to get this re-opened, @StrangeWeirdKitten ? I dig the new sprites you wanted to add, they look good