[modular] fixes some lewd furnitures spawnable inside people's hands
Skyrat-SS13/Skyrat-TG pull request #9910
Opened 2021-12-06 22:38 UTC by jupyterkat

## About The Pull Request

it's possible for some lewd furniture to spawn in people's hands and they will delete themselves if they try to interact with it

## How This Contributes To The Skyrat Roleplay Experience

it's a fix

## Changelog

:cl:
fix: fixed lewd furnitures spawning in people's hands
/:cl:

2021-12-07 00:11 UTC, GoldenAlpharex requested changes

2021-12-07 00:11 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_machinery/milking_machine.dm
>  					N.machine_color = N.machine_color_list[1]
While you're there, replace `N` by something more significant, please.

2021-12-07 02:32 UTC, jjpark-kb commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/dancing_pole.dm
> +			new /obj/item/polepack(get_turf(user))
```suggestion
			new /obj/item/polepack(get_turf(src))
```
perhaps this instead? I don't know, this is just preference at this point, ahaha.

2021-12-07 02:32 UTC, jjpark-kb commented on modular_skyrat/modules/modular_items/lewd_items/code/lewd_structures/bdsm_furniture.dm
> +			new /obj/item/x_stand_kit(get_turf(user))
```suggestion
			new /obj/item/x_stand_kit(get_turf(src))
```
perhaps this instead? I don't know, this is just preference at this point, ahaha.

2021-12-17 00:10 UTC, tf-4 commented
Address reviews or accept your fate

2021-12-17 00:11 UTC, jupyterkat commented
preference reviews are irrelevant

2021-12-17 00:33 UTC, tf-4 approved these changes

2021-12-17 00:33 UTC, merged