[NON-MODULAR] Adjusts Runechat layers to allow blind characters to 'see' visual messages.
Skyrat-SS13/Skyrat-TG pull request #9918
Opened 2021-12-07 03:01 UTC by CandleJaxx

## About The Pull Request

Adjusts runechat to make for a form of sensory supplement for blind players, being able to determine where someone is talking to them from by allowing them to see the runechat bubbles.

## How This Contributes To The Skyrat Roleplay Experience

Being able to tell if someone is roughly infront of you or behind you allows for people to better act as though they're in the world. You'd be able to tell if someone was standing infront, behind,l or near you and speaking.

## Changelog

:cl:

fix: Blind players can now see runechat.

/:cl:

2021-12-07 15:50 UTC, ChungusGamer666 commented
this will cause unintended consequences like runechat displaying above hud elements, which is really distracting
absolute thumbs down for me.

2021-12-07 17:29 UTC, GoldenAlpharex requested changes
I feel like there's going to be a lot of unintended side-effects, with Runechat clipping over a lot of things. Surely, there's got to be a better way of doing this.

2021-12-07 18:25 UTC, CandleJaxx commented
hm, i can't see where it'd clip over hud elements- the only element it clips over is damage, which is the red hue around the screen, which shouldn't be over text anyway

2021-12-07 21:29 UTC, Azarak commented
```//HUD layer defines
#define HUD_PLANE 1000
#define ABOVE_HUD_PLANE 1100```
Hud is above fullscreen. There isn't a better way of doing this. It's just a matter if finding the render order you want things to be, in this case it being over all fullscreen effects (usually sight obstructions, which don't affect hearing)

2021-12-07 21:35 UTC, CandleJaxx commented
that's what i was thinking- if it shows up in chat, it should show up in runechat

2021-12-08 21:45 UTC, CandleJaxx commented
closed, to be deleted if upstream passes

2021-12-08 21:45 UTC, closed without merging