[MODULAR][FIX]Body Teleporter Medicell no longer teleports living people
Skyrat-SS13/Skyrat-TG pull request #9947
Opened 2021-12-08 02:34 UTC by softcerv

## About The Pull Request
Fixes the code for the body Teleporter Medicell so that it now properly checks to see if the target is dead, preventing people still alive from being teleported. 

Such robustness...... This was _not_ my intention....

## How This Contributes To The Skyrat Roleplay Experience
This fixes a bug that made the body teleporter medicell far more powerful than it was intended to be.

## Changelog

:cl:
fix: the body teleporter medicell no longer teleports people that are still alive
/:cl:

2021-12-08 02:57 UTC, GoldenAlpharex requested changes

2021-12-08 02:57 UTC, GoldenAlpharex commented on modular_skyrat/modules/modular_weapons/code/medcells.dm
> +		return FALSE
You could also probably put all of them on the same line.

2021-12-08 20:29 UTC, softcerv commented
oh god why is the CI failing

2021-12-09 00:34 UTC, GoldenAlpharex approved these changes

2021-12-09 00:35 UTC, merged