Population control cap
Skyrat-SS13/Skyrat-TG pull request #9979
Opened 2021-12-09 23:55 UTC by Gandalf2k15

For maintainers:
Population cap config required
Overflow server IP required

Simply transfers a connecting client to a designated overflow server if TGS_CLIENT_COUNT > player_cap, fails if both of the above are not met.

Alternative to hard cap which does not include a send to overflow option.

**Technical review only**

2021-12-10 01:19 UTC, OrionTheFox commented on code/modules/mob/dead/new_player/login.dm
> +			message_admins("[src] attempted to join however the server is full and has been sent to the overflow server.")
```suggestion
			message_admins("[src] attempted to join, but the server was full and they've been sent to the overflow server.")
```
Better grammar/not a run-on sentance

2021-12-10 12:15 UTC, ChungusGamer666 commented
> Admins are exempt, obviously
Literally 1984

2021-12-25 18:25 UTC, GoldenAlpharex requested changes
Just a tiny bit of change needed and then we're good to go.

2021-12-25 18:25 UTC, GoldenAlpharex commented on code/modules/admin/verbs/adminhelp.dm
> +			world.send_cross_comms(I, additional_data)
```suggestion
		for(var/server in servers)
			if(server == our_id)
				continue
			world.send_cross_comms(server, additional_data)
```

2021-12-25 18:25 UTC, GoldenAlpharex commented on modular_skyrat/master_files/code/_onclick/hud/new_player.dm
>  		var/confirm = tgui_alert(new_player, "Are you sure you want to swap to [server_name] ([server_ip])?", "Swapping server!", list("Connect me!", "Stay here!"))
```suggestion
		var/confirm = tgui_alert(new_player, "Are you sure you want to swap to [server_name] ([server_ip])?", "Swapping server!", list("Send me there", "Stay here"))
```

2021-12-25 18:25 UTC, GoldenAlpharex commented on modular_skyrat/modules/server_overflow/code/client_procs.dm
> +/client/proc/check_population(connecting_admin = FALSE)
```suggestion
/**
 * This proc is designed to be lightweight and straight forward, clients are finicky and joining all the time.
 * FALSE = Deny connection
 * True = Confirm connection
 */
/client/proc/check_population(connecting_admin = FALSE)
```

2021-12-25 18:25 UTC, GoldenAlpharex commented on modular_skyrat/modules/server_overflow/code/client_procs.dm
> +	if(choice != "Connect me!")
This could probably be a define, in order to avoid more issues in the future.
```suggestion
	if(choice != "Send me there")
```

2021-12-25 18:25 UTC, GoldenAlpharex commented on tgui/packages/tgui/interfaces/ServerControlPanel.js
> +            No servers are currently online.
```suggestion
            No server is currently online.
```

2021-12-25 18:51 UTC, GoldenAlpharex approved these changes

2021-12-25 19:08 UTC, merged